// Punjabi sentence pattern bank for Vietnamese-speaking and English-speaking learners.
// Gurmukhi is primary. Romanization is practical learner support. Shahmukhi is
// mentioned only for awareness; this is not a Shahmukhi course. Native review is deferred.

export type PunjabiPatternTopic =
  | "greeting"
  | "want_need"
  | "can_cannot"
  | "location"
  | "time"
  | "buying"
  | "asking"
  | "giving_reason"
  | "comparing"
  | "polite_request"
  | "complaint"
  | "opinion"
  | "family"
  | "workplace"
  | "clinic"
  | "public_office";

export type PunjabiSentencePattern = {
  id: string;
  topic: PunjabiPatternTopic;
  level: "A1" | "A2";
  pattern: string;
  romanization: string;
  meaning_vi: string;
  meaning_en: string;
  examples: { pa: string; romanization: string; vi: string; en: string }[];
  substitution_slots: string[];
  common_mistake: { audience: "vi" | "en" | "both"; vi: string; en: string };
};

export const sentencePatternScriptAwareness =
  "Gurmukhi is primary. Shahmukhi is awareness only here, not a full course track.";

export const sentencePatterns: PunjabiSentencePattern[] = [
  { id: "pa_pattern_001", topic: "greeting", level: "A1", pattern: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ।", romanization: "sat sri akal", meaning_vi: "Xin chào lịch sự.", meaning_en: "Respectful hello.", examples: [{ pa: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ ਜੀ।", romanization: "sat sri akal ji", vi: "Xin chào ạ.", en: "Hello, respectfully." }], substitution_slots: ["ਜੀ"], common_mistake: { audience: "vi", vi: "Đừng thêm nguyên âm sau ਸਤ.", en: "Vietnamese speakers should not add a vowel after final ਤ." } },
  { id: "pa_pattern_002", topic: "greeting", level: "A1", pattern: "ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?", romanization: "tusi kive ho?", meaning_vi: "Bạn khỏe không?", meaning_en: "How are you?", examples: [{ pa: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ। ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?", romanization: "sat sri akal. tusi kive ho?", vi: "Xin chào. Bạn khỏe không?", en: "Hello. How are you?" }], substitution_slots: ["ਤੁਸੀਂ", "ਕਿਵੇਂ"], common_mistake: { audience: "en", vi: "Dùng ਤੁਸੀਂ với người mới gặp.", en: "Use polite ਤੁਸੀਂ with new adults, not intimate ਤੂੰ." } },
  { id: "pa_pattern_003", topic: "greeting", level: "A1", pattern: "ਮੈਂ ਠੀਕ ਹਾਂ।", romanization: "main thik han", meaning_vi: "Tôi ổn.", meaning_en: "I am fine.", examples: [{ pa: "ਮੈਂ ਠੀਕ ਹਾਂ, ਧੰਨਵਾਦ।", romanization: "main thik han, dhanvad", vi: "Tôi ổn, cảm ơn.", en: "I am fine, thank you." }], substitution_slots: ["ਠੀਕ", "ਖੁਸ਼"], common_mistake: { audience: "both", vi: "Giữ ਹਾਂ với ਮੈਂ.", en: "Keep ਹਾਂ with ਮੈਂ in this pattern." } },
  { id: "pa_pattern_004", topic: "greeting", level: "A1", pattern: "ਫਿਰ ਮਿਲਾਂਗੇ।", romanization: "phir milange", meaning_vi: "Hẹn gặp lại.", meaning_en: "See you again.", examples: [{ pa: "ਠੀਕ ਹੈ, ਫਿਰ ਮਿਲਾਂਗੇ।", romanization: "thik hai, phir milange", vi: "Được, hẹn gặp lại.", en: "Okay, see you again." }], substitution_slots: ["ਫਿਰ", "ਕੱਲ੍ਹ"], common_mistake: { audience: "both", vi: "Không dùng như lời chào mở đầu.", en: "Do not use it as an opening greeting." } },
  { id: "pa_pattern_005", topic: "greeting", level: "A1", pattern: "ਤੁਹਾਨੂੰ ਮਿਲ ਕੇ ਖੁਸ਼ੀ ਹੋਈ।", romanization: "tuhanu mil ke khushi hoi", meaning_vi: "Rất vui được gặp bạn.", meaning_en: "Nice to meet you.", examples: [{ pa: "ਤੁਹਾਨੂੰ ਮਿਲ ਕੇ ਬਹੁਤ ਖੁਸ਼ੀ ਹੋਈ।", romanization: "tuhanu mil ke bahut khushi hoi", vi: "Rất vui được gặp bạn.", en: "Very nice to meet you." }], substitution_slots: ["ਬਹੁਤ", "ਤੁਹਾਨੂੰ"], common_mistake: { audience: "vi", vi: "Không bỏ ਹੋਈ ở cuối.", en: "Vietnamese speakers may drop the final verb; keep ਹੋਈ." } },

  { id: "pa_pattern_006", topic: "want_need", level: "A1", pattern: "ਮੈਨੂੰ ___ ਚਾਹੀਦਾ ਹੈ।", romanization: "mainu ___ chahida hai", meaning_vi: "Tôi cần/muốn ___", meaning_en: "I need/want ___", examples: [{ pa: "ਮੈਨੂੰ ਪਾਣੀ ਚਾਹੀਦਾ ਹੈ।", romanization: "mainu pani chahida hai", vi: "Tôi cần nước.", en: "I need water." }], substitution_slots: ["ਪਾਣੀ", "ਟਿਕਟ", "ਕਮਰਾ"], common_mistake: { audience: "both", vi: "Không dịch từng chữ theo trật tự tiếng Anh.", en: "Do not force English word order onto this Punjabi frame." } },
  { id: "pa_pattern_007", topic: "want_need", level: "A1", pattern: "ਮੈਨੂੰ ___ ਚਾਹੀਦੀ ਹੈ।", romanization: "mainu ___ chahidi hai", meaning_vi: "Tôi cần/muốn ___ (danh từ giống cái).", meaning_en: "I need/want ___ (feminine noun).", examples: [{ pa: "ਮੈਨੂੰ ਚਾਹ ਚਾਹੀਦੀ ਹੈ।", romanization: "mainu chah chahidi hai", vi: "Tôi muốn trà.", en: "I want tea." }], substitution_slots: ["ਚਾਹ", "ਮਦਦ", "ਰਸੀਦ"], common_mistake: { audience: "en", vi: "Người nói tiếng Anh dễ bỏ qua giống danh từ.", en: "English speakers may miss noun gender agreement." } },
  { id: "pa_pattern_008", topic: "want_need", level: "A2", pattern: "ਮੈਨੂੰ ___ ਦੀ ਲੋੜ ਹੈ।", romanization: "mainu ___ di lor hai", meaning_vi: "Tôi cần ___", meaning_en: "I need ___", examples: [{ pa: "ਮੈਨੂੰ ਮਦਦ ਦੀ ਲੋੜ ਹੈ।", romanization: "mainu madad di lor hai", vi: "Tôi cần sự giúp đỡ.", en: "I need help." }], substitution_slots: ["ਮਦਦ", "ਦਵਾਈ", "ਜਾਣਕਾਰੀ"], common_mistake: { audience: "vi", vi: "Giữ ਦੀ trong cụm ਲੋੜ ਹੈ.", en: "Keep ਦੀ in the ਲੋੜ ਹੈ pattern." } },
  { id: "pa_pattern_009", topic: "want_need", level: "A2", pattern: "ਮੈਂ ___ ਲੈਣਾ ਚਾਹੁੰਦਾ ਹਾਂ।", romanization: "main ___ laina chahunda han", meaning_vi: "Tôi muốn lấy/mua ___ (người nói nam).", meaning_en: "I want to take/buy ___ (male speaker).", examples: [{ pa: "ਮੈਂ ਟਿਕਟ ਲੈਣਾ ਚਾਹੁੰਦਾ ਹਾਂ।", romanization: "main ticket laina chahunda han", vi: "Tôi muốn mua vé.", en: "I want to buy a ticket." }], substitution_slots: ["ਟਿਕਟ", "ਪਾਣੀ", "ਇਹ"], common_mistake: { audience: "both", vi: "Dạng người nói nữ thường là ਚਾਹੁੰਦੀ.", en: "A female speaker commonly uses ਚਾਹੁੰਦੀ." } },
  { id: "pa_pattern_010", topic: "want_need", level: "A2", pattern: "ਕੀ ਤੁਹਾਨੂੰ ___ ਚਾਹੀਦਾ ਹੈ?", romanization: "ki tuhanu ___ chahida hai?", meaning_vi: "Bạn có cần ___ không?", meaning_en: "Do you need ___?", examples: [{ pa: "ਕੀ ਤੁਹਾਨੂੰ ਪਾਣੀ ਚਾਹੀਦਾ ਹੈ?", romanization: "ki tuhanu pani chahida hai?", vi: "Bạn có cần nước không?", en: "Do you need water?" }], substitution_slots: ["ਪਾਣੀ", "ਬੈਗ", "ਫਾਰਮ"], common_mistake: { audience: "en", vi: "Không cần trợ động từ do/does.", en: "Do not add an English-style do/does auxiliary." } },

  { id: "pa_pattern_011", topic: "can_cannot", level: "A2", pattern: "ਮੈਂ ___ ਸਕਦਾ ਹਾਂ।", romanization: "main ___ sakda han", meaning_vi: "Tôi có thể ___ (nam).", meaning_en: "I can ___ (male speaker).", examples: [{ pa: "ਮੈਂ ਪੰਜਾਬੀ ਬੋਲ ਸਕਦਾ ਹਾਂ।", romanization: "main panjabi bol sakda han", vi: "Tôi có thể nói Punjabi.", en: "I can speak Punjabi." }], substitution_slots: ["ਬੋਲ", "ਜਾ", "ਲਿਖ"], common_mistake: { audience: "both", vi: "Nhớ dạng ਸਕਦਾ/ਸਕਦੀ theo người nói.", en: "Remember ਸਕਦਾ/ਸਕਦੀ can agree with the speaker." } },
  { id: "pa_pattern_012", topic: "can_cannot", level: "A2", pattern: "ਮੈਂ ___ ਸਕਦੀ ਹਾਂ।", romanization: "main ___ sakdi han", meaning_vi: "Tôi có thể ___ (nữ).", meaning_en: "I can ___ (female speaker).", examples: [{ pa: "ਮੈਂ ਆ ਸਕਦੀ ਹਾਂ।", romanization: "main aa sakdi han", vi: "Tôi có thể đến.", en: "I can come." }], substitution_slots: ["ਆ", "ਪੜ੍ਹ", "ਕਰ"], common_mistake: { audience: "vi", vi: "Tiếng Việt không đổi theo giới; Punjabi có thể đổi.", en: "Vietnamese speakers should notice gendered forms." } },
  { id: "pa_pattern_013", topic: "can_cannot", level: "A2", pattern: "ਮੈਂ ___ ਨਹੀਂ ਸਕਦਾ।", romanization: "main ___ nahin sakda", meaning_vi: "Tôi không thể ___ (nam).", meaning_en: "I cannot ___ (male speaker).", examples: [{ pa: "ਮੈਂ ਅੱਜ ਨਹੀਂ ਆ ਸਕਦਾ।", romanization: "main ajj nahin aa sakda", vi: "Hôm nay tôi không thể đến.", en: "I cannot come today." }], substitution_slots: ["ਆ", "ਜਾ", "ਕਰ"], common_mistake: { audience: "en", vi: "ਨਹੀਂ thường đứng trước động từ/cụm khả năng.", en: "ਨਹੀਂ is placed before the verb/ability phrase." } },
  { id: "pa_pattern_014", topic: "can_cannot", level: "A2", pattern: "ਕੀ ਮੈਂ ___ ਸਕਦਾ ਹਾਂ?", romanization: "ki main ___ sakda han?", meaning_vi: "Tôi có thể ___ không?", meaning_en: "Can I ___?", examples: [{ pa: "ਕੀ ਮੈਂ ਅੰਦਰ ਆ ਸਕਦਾ ਹਾਂ?", romanization: "ki main andar aa sakda han", vi: "Tôi có thể vào không?", en: "Can I come in?" }], substitution_slots: ["ਅੰਦਰ ਆ", "ਬੈਠ", "ਪੁੱਛ"], common_mistake: { audience: "both", vi: "Dùng ਕੀ để đánh dấu câu hỏi yes/no.", en: "Use ਕੀ to mark a yes/no question." } },
  { id: "pa_pattern_015", topic: "can_cannot", level: "A2", pattern: "ਤੁਸੀਂ ___ ਕਰ ਸਕਦੇ ਹੋ।", romanization: "tusi ___ kar sakde ho", meaning_vi: "Bạn có thể làm ___.", meaning_en: "You can do ___.", examples: [{ pa: "ਤੁਸੀਂ ਇੱਥੇ ਉਡੀਕ ਕਰ ਸਕਦੇ ਹੋ।", romanization: "tusi ithe udik kar sakde ho", vi: "Bạn có thể đợi ở đây.", en: "You can wait here." }], substitution_slots: ["ਉਡੀਕ", "ਭੁਗਤਾਨ", "ਦਸਤਖ਼ਤ"], common_mistake: { audience: "en", vi: "Với ਤੁਸੀਂ dùng ਹੋ, không dùng ਹਾਂ.", en: "With ਤੁਸੀਂ use ਹੋ, not ਹਾਂ." } },

  { id: "pa_pattern_016", topic: "location", level: "A1", pattern: "___ ਕਿੱਥੇ ਹੈ?", romanization: "___ kithe hai?", meaning_vi: "___ ở đâu?", meaning_en: "Where is ___?", examples: [{ pa: "ਸਟੇਸ਼ਨ ਕਿੱਥੇ ਹੈ?", romanization: "station kithe hai", vi: "Nhà ga ở đâu?", en: "Where is the station?" }], substitution_slots: ["ਸਟੇਸ਼ਨ", "ਬੱਸ ਅੱਡਾ", "ਦਫ਼ਤਰ"], common_mistake: { audience: "en", vi: "Không đảo is như tiếng Anh.", en: "Do not invert like English 'where is'." } },
  { id: "pa_pattern_017", topic: "location", level: "A1", pattern: "___ ਇੱਥੇ ਹੈ।", romanization: "___ ithe hai", meaning_vi: "___ ở đây.", meaning_en: "___ is here.", examples: [{ pa: "ਦਫ਼ਤਰ ਇੱਥੇ ਹੈ।", romanization: "daftar ithe hai", vi: "Văn phòng ở đây.", en: "The office is here." }], substitution_slots: ["ਦਫ਼ਤਰ", "ਬੈਗ", "ਕਮਰਾ"], common_mistake: { audience: "vi", vi: "Đừng bỏ ਹੈ dù tiếng Việt có thể không cần 'là/ở'.", en: "Vietnamese speakers may drop ਹੈ; keep it." } },
  { id: "pa_pattern_018", topic: "location", level: "A1", pattern: "___ ਉੱਥੇ ਹੈ।", romanization: "___ utthe hai", meaning_vi: "___ ở kia.", meaning_en: "___ is there.", examples: [{ pa: "ਦੁਕਾਨ ਉੱਥੇ ਹੈ।", romanization: "dukan utthe hai", vi: "Cửa hàng ở kia.", en: "The shop is there." }], substitution_slots: ["ਦੁਕਾਨ", "ਕਲਿਨਿਕ", "ਕਾਊਂਟਰ"], common_mistake: { audience: "both", vi: "Phân biệt ਇੱਥੇ ở đây và ਉੱਥੇ ở kia.", en: "Distinguish ਇੱਥੇ here and ਉੱਥੇ there." } },
  { id: "pa_pattern_019", topic: "location", level: "A2", pattern: "___ ਦੇ ਨੇੜੇ ਹੈ।", romanization: "___ de nere hai", meaning_vi: "Ở gần ___.", meaning_en: "It is near ___.", examples: [{ pa: "ਬੈਂਕ ਸਟੇਸ਼ਨ ਦੇ ਨੇੜੇ ਹੈ।", romanization: "bank station de nere hai", vi: "Ngân hàng ở gần nhà ga.", en: "The bank is near the station." }], substitution_slots: ["ਸਟੇਸ਼ਨ", "ਬਜ਼ਾਰ", "ਘਰ"], common_mistake: { audience: "en", vi: "ਦੇ là hậu giới từ; đứng sau danh từ.", en: "ਦੇ is part of a postpositional phrase after the noun." } },
  { id: "pa_pattern_020", topic: "location", level: "A2", pattern: "___ ਦੇ ਸਾਹਮਣੇ ਹੈ।", romanization: "___ de sahmane hai", meaning_vi: "Ở trước/đối diện ___.", meaning_en: "It is in front of/opposite ___.", examples: [{ pa: "ਕਲਿਨਿਕ ਬੈਂਕ ਦੇ ਸਾਹਮਣੇ ਹੈ।", romanization: "clinic bank de sahmane hai", vi: "Phòng khám ở đối diện ngân hàng.", en: "The clinic is opposite the bank." }], substitution_slots: ["ਬੈਂਕ", "ਸਕੂਲ", "ਦਫ਼ਤਰ"], common_mistake: { audience: "vi", vi: "Không đặt ਦੇ trước danh từ theo kiểu tiếng Việt.", en: "Do not place ਦੇ before the noun like a Vietnamese preposition." } },

  { id: "pa_pattern_021", topic: "time", level: "A1", pattern: "ਹੁਣ ___ ਵਜੇ ਹਨ।", romanization: "hun ___ vaje han", meaning_vi: "Bây giờ là ___ giờ.", meaning_en: "It is ___ o'clock now.", examples: [{ pa: "ਹੁਣ ਦੋ ਵਜੇ ਹਨ।", romanization: "hun do vaje han", vi: "Bây giờ là hai giờ.", en: "It is two o'clock now." }], substitution_slots: ["ਇੱਕ", "ਦੋ", "ਤਿੰਨ"], common_mistake: { audience: "both", vi: "ਵਜੇ đi với giờ đồng hồ.", en: "ਵਜੇ is used for clock time." } },
  { id: "pa_pattern_022", topic: "time", level: "A1", pattern: "ਕਿੰਨੇ ਵਜੇ ਹਨ?", romanization: "kinne vaje han?", meaning_vi: "Mấy giờ rồi?", meaning_en: "What time is it?", examples: [{ pa: "ਹੁਣ ਕਿੰਨੇ ਵਜੇ ਹਨ?", romanization: "hun kinne vaje han", vi: "Bây giờ mấy giờ?", en: "What time is it now?" }], substitution_slots: ["ਹੁਣ"], common_mistake: { audience: "both", vi: "ਕਿੰਨੇ cũng dùng ở câu hỏi giá; xem ਵਜੇ để biết là giờ.", en: "ਕਿੰਨੇ also appears in price questions; ਵਜੇ signals time." } },
  { id: "pa_pattern_023", topic: "time", level: "A1", pattern: "ਮੈਂ ___ ਆਵਾਂਗਾ।", romanization: "main ___ avanga", meaning_vi: "Tôi sẽ đến lúc/vào ___.", meaning_en: "I will come at/on ___.", examples: [{ pa: "ਮੈਂ ਕੱਲ੍ਹ ਆਵਾਂਗਾ।", romanization: "main kallh avanga", vi: "Tôi sẽ đến ngày mai.", en: "I will come tomorrow." }], substitution_slots: ["ਕੱਲ੍ਹ", "ਅੱਜ", "ਸ਼ਾਮ ਨੂੰ"], common_mistake: { audience: "vi", vi: "Người nói nữ thường dùng ਆਵਾਂਗੀ.", en: "A female speaker commonly uses ਆਵਾਂਗੀ." } },
  { id: "pa_pattern_024", topic: "time", level: "A2", pattern: "___ ਤੋਂ ___ ਤੱਕ", romanization: "___ ton ___ takk", meaning_vi: "Từ ___ đến ___.", meaning_en: "From ___ to ___.", examples: [{ pa: "ਨੌਂ ਤੋਂ ਪੰਜ ਤੱਕ ਕੰਮ ਹੈ।", romanization: "naun ton panj takk kamm hai", vi: "Làm việc từ chín đến năm.", en: "Work is from nine to five." }], substitution_slots: ["ਨੌਂ", "ਪੰਜ", "ਸੋਮਵਾਰ"], common_mistake: { audience: "en", vi: "ਤੋਂ và ਤੱਕ đứng sau mốc thời gian.", en: "ਤੋਂ and ਤੱਕ follow the time points." } },
  { id: "pa_pattern_025", topic: "time", level: "A2", pattern: "ਮੈਨੂੰ ___ ਵਜੇ ਜਾਣਾ ਹੈ।", romanization: "mainu ___ vaje jana hai", meaning_vi: "Tôi phải đi lúc ___ giờ.", meaning_en: "I have to go at ___ o'clock.", examples: [{ pa: "ਮੈਨੂੰ ਛੇ ਵਜੇ ਜਾਣਾ ਹੈ।", romanization: "mainu chhe vaje jana hai", vi: "Tôi phải đi lúc sáu giờ.", en: "I have to go at six." }], substitution_slots: ["ਛੇ", "ਸੱਤ", "ਅੱਠ"], common_mistake: { audience: "both", vi: "ਮੈਨੂੰ ... ਜਾਣਾ ਹੈ là mẫu nghĩa vụ, không phải sở hữu.", en: "ਮੈਨੂੰ ... ਜਾਣਾ ਹੈ marks obligation, not possession." } },

  { id: "pa_pattern_026", topic: "buying", level: "A1", pattern: "ਇਹ ਕਿੰਨੇ ਦਾ ਹੈ?", romanization: "ih kinne da hai?", meaning_vi: "Cái này bao nhiêu tiền?", meaning_en: "How much is this?", examples: [{ pa: "ਇਹ ਕਿੰਨੇ ਦਾ ਹੈ ਜੀ?", romanization: "ih kinne da hai ji", vi: "Cái này bao nhiêu tiền ạ?", en: "How much is this, please?" }], substitution_slots: ["ਇਹ", "ਉਹ", "ਜੀ"], common_mistake: { audience: "both", vi: "Không dùng ਕਿੱਥੇ để hỏi giá.", en: "Do not use ਕਿੱਥੇ for price." } },
  { id: "pa_pattern_027", topic: "buying", level: "A1", pattern: "ਮੈਨੂੰ ਇਹ ਚਾਹੀਦਾ ਹੈ।", romanization: "mainu ih chahida hai", meaning_vi: "Tôi muốn cái này.", meaning_en: "I want this.", examples: [{ pa: "ਮੈਨੂੰ ਇਹ ਬੈਗ ਚਾਹੀਦਾ ਹੈ।", romanization: "mainu ih bag chahida hai", vi: "Tôi muốn cái túi này.", en: "I want this bag." }], substitution_slots: ["ਇਹ", "ਬੈਗ", "ਟਿਕਟ"], common_mistake: { audience: "vi", vi: "Giữ ਮੈਨੂੰ thay vì dịch từng chữ 'tôi muốn'.", en: "Keep ਮੈਨੂੰ rather than translating word by word." } },
  { id: "pa_pattern_028", topic: "buying", level: "A1", pattern: "ਕੀ ਇਹ ਸਸਤਾ ਹੈ?", romanization: "ki ih sasta hai?", meaning_vi: "Cái này rẻ không?", meaning_en: "Is this cheap?", examples: [{ pa: "ਕੀ ਇਹ ਹੋਰ ਸਸਤਾ ਹੈ?", romanization: "ki ih hor sasta hai", vi: "Cái này rẻ hơn không?", en: "Is this cheaper?" }], substitution_slots: ["ਸਸਤਾ", "ਮਹਿੰਗਾ", "ਹੋਰ"], common_mistake: { audience: "en", vi: "ਸਸਤਾ/ਮਹਿੰਗਾ có thể đổi dạng theo danh từ.", en: "ਸਸਤਾ/ਮਹਿੰਗਾ can change form with nouns." } },
  { id: "pa_pattern_029", topic: "buying", level: "A2", pattern: "ਰਸੀਦ ਦੇ ਦਿਓ ਜੀ।", romanization: "rasid de dio ji", meaning_vi: "Vui lòng đưa hóa đơn.", meaning_en: "Please give the receipt.", examples: [{ pa: "ਮੈਨੂੰ ਰਸੀਦ ਦੇ ਦਿਓ ਜੀ।", romanization: "mainu rasid de dio ji", vi: "Vui lòng đưa tôi hóa đơn.", en: "Please give me the receipt." }], substitution_slots: ["ਰਸੀਦ", "ਥੈਲਾ", "ਟਿਕਟ"], common_mistake: { audience: "both", vi: "ਜੀ làm yêu cầu mềm hơn.", en: "ਜੀ softens the request." } },
  { id: "pa_pattern_030", topic: "buying", level: "A2", pattern: "ਮੈਂ ਕਾਰਡ ਨਾਲ ਭੁਗਤਾਨ ਕਰਾਂਗਾ।", romanization: "main card nal bhugtan karanga", meaning_vi: "Tôi sẽ thanh toán bằng thẻ.", meaning_en: "I will pay by card.", examples: [{ pa: "ਮੈਂ ਨਕਦ ਨਾਲ ਭੁਗਤਾਨ ਕਰਾਂਗਾ।", romanization: "main nakad nal bhugtan karanga", vi: "Tôi sẽ thanh toán bằng tiền mặt.", en: "I will pay in cash." }], substitution_slots: ["ਕਾਰਡ", "ਨਕਦ", "ਆਨਲਾਈਨ"], common_mistake: { audience: "vi", vi: "Người nói nữ thường dùng ਕਰਾਂਗੀ.", en: "A female speaker commonly uses ਕਰਾਂਗੀ." } },

  { id: "pa_pattern_031", topic: "asking", level: "A1", pattern: "ਇਹ ਕੀ ਹੈ?", romanization: "ih ki hai?", meaning_vi: "Đây là gì?", meaning_en: "What is this?", examples: [{ pa: "ਇਹ ਕੀ ਹੈ ਜੀ?", romanization: "ih ki hai ji", vi: "Đây là gì ạ?", en: "What is this, please?" }], substitution_slots: ["ਇਹ", "ਉਹ", "ਜੀ"], common_mistake: { audience: "both", vi: "ਕੀ đứng trước ਹੈ trong mẫu này.", en: "ਕੀ comes before ਹੈ in this pattern." } },
  { id: "pa_pattern_032", topic: "asking", level: "A1", pattern: "ਤੁਹਾਡਾ ਨਾਮ ਕੀ ਹੈ?", romanization: "tuhada nam ki hai?", meaning_vi: "Tên bạn là gì?", meaning_en: "What is your name?", examples: [{ pa: "ਤੁਹਾਡਾ ਨਾਮ ਕੀ ਹੈ ਜੀ?", romanization: "tuhada nam ki hai ji", vi: "Tên bạn là gì ạ?", en: "What is your name, please?" }], substitution_slots: ["ਤੁਹਾਡਾ", "ਨਾਮ", "ਜੀ"], common_mistake: { audience: "vi", vi: "Đừng bỏ ਹੈ ở cuối.", en: "Vietnamese speakers may drop ਹੈ; keep it." } },
  { id: "pa_pattern_033", topic: "asking", level: "A1", pattern: "ਤੁਸੀਂ ਕਿੱਥੋਂ ਹੋ?", romanization: "tusi kitthon ho?", meaning_vi: "Bạn đến từ đâu?", meaning_en: "Where are you from?", examples: [{ pa: "ਤੁਸੀਂ ਵੀਅਤਨਾਮ ਤੋਂ ਹੋ?", romanization: "tusi Vietnam ton ho", vi: "Bạn đến từ Việt Nam à?", en: "Are you from Vietnam?" }], substitution_slots: ["ਤੁਸੀਂ", "ਕਿੱਥੋਂ", "ਤੋਂ"], common_mistake: { audience: "en", vi: "ਕਿੱਥੇ là ở đâu; ਕਿੱਥੋਂ là từ đâu.", en: "ਕਿੱਥੇ is where; ਕਿੱਥੋਂ is from where." } },
  { id: "pa_pattern_034", topic: "asking", level: "A2", pattern: "ਕੀ ਤੁਸੀਂ ___?", romanization: "ki tusi ___?", meaning_vi: "Bạn có ___ không?", meaning_en: "Do you ___?", examples: [{ pa: "ਕੀ ਤੁਸੀਂ ਪੰਜਾਬੀ ਬੋਲਦੇ ਹੋ?", romanization: "ki tusi panjabi bolde ho", vi: "Bạn có nói Punjabi không?", en: "Do you speak Punjabi?" }], substitution_slots: ["ਪੰਜਾਬੀ ਬੋਲਦੇ ਹੋ", "ਇੱਥੇ ਰਹਿੰਦੇ ਹੋ"], common_mistake: { audience: "both", vi: "ਕੀ đánh dấu câu hỏi yes/no.", en: "ਕੀ marks a yes/no question." } },
  { id: "pa_pattern_035", topic: "asking", level: "A2", pattern: "ਮੈਂ ___ ਕਿਵੇਂ ਕਰਾਂ?", romanization: "main ___ kive karan?", meaning_vi: "Tôi làm ___ như thế nào?", meaning_en: "How do I do ___?", examples: [{ pa: "ਮੈਂ ਭੁਗਤਾਨ ਕਿਵੇਂ ਕਰਾਂ?", romanization: "main bhugtan kive karan", vi: "Tôi thanh toán như thế nào?", en: "How do I pay?" }], substitution_slots: ["ਭੁਗਤਾਨ", "ਅਰਜ਼ੀ", "ਰਜਿਸਟਰ"], common_mistake: { audience: "en", vi: "ਕਿਵੇਂ đứng trước ਕਰਾਂ.", en: "ਕਿਵੇਂ comes before ਕਰਾਂ." } },

  { id: "pa_pattern_036", topic: "giving_reason", level: "A2", pattern: "ਮੈਂ ਨਹੀਂ ਆ ਸਕਦਾ ਕਿਉਂਕਿ ___।", romanization: "main nahin aa sakda kyonki ___", meaning_vi: "Tôi không thể đến vì ___.", meaning_en: "I cannot come because ___.", examples: [{ pa: "ਮੈਂ ਨਹੀਂ ਆ ਸਕਦਾ ਕਿਉਂਕਿ ਮੈਂ ਬੀਮਾਰ ਹਾਂ।", romanization: "main nahin aa sakda kyonki main bimar han", vi: "Tôi không thể đến vì tôi bị bệnh.", en: "I cannot come because I am sick." }], substitution_slots: ["ਮੈਂ ਬੀਮਾਰ ਹਾਂ", "ਕੰਮ ਹੈ", "ਦੇਰ ਹੈ"], common_mistake: { audience: "vi", vi: "Giữ ਕਿਉਂਕਿ cho mệnh đề lý do.", en: "Keep ਕਿਉਂਕਿ before the reason clause." } },
  { id: "pa_pattern_037", topic: "giving_reason", level: "A2", pattern: "ਕਿਉਂਕਿ ___, ਮੈਂ ___।", romanization: "kyonki ___, main ___", meaning_vi: "Vì ___, tôi ___.", meaning_en: "Because ___, I ___.", examples: [{ pa: "ਕਿਉਂਕਿ ਮੀਂਹ ਹੈ, ਮੈਂ ਘਰ ਰਹਾਂਗਾ।", romanization: "kyonki minh hai, main ghar rahanga", vi: "Vì trời mưa, tôi sẽ ở nhà.", en: "Because it is raining, I will stay home." }], substitution_slots: ["ਮੀਂਹ ਹੈ", "ਦੇਰ ਹੈ", "ਘਰ ਰਹਾਂਗਾ"], common_mistake: { audience: "en", vi: "Có thể đặt lý do trước, nhưng giữ cấu trúc rõ.", en: "The reason can come first; keep the clause structure clear." } },
  { id: "pa_pattern_038", topic: "giving_reason", level: "A2", pattern: "ਮੈਨੂੰ ___ ਹੈ, ਇਸ ਲਈ ___।", romanization: "mainu ___ hai, is lai ___", meaning_vi: "Tôi có ___, nên ___.", meaning_en: "I have ___, so ___.", examples: [{ pa: "ਮੈਨੂੰ ਕੰਮ ਹੈ, ਇਸ ਲਈ ਮੈਂ ਜਾਵਾਂਗਾ।", romanization: "mainu kamm hai, is lai main javanga", vi: "Tôi có việc, nên tôi sẽ đi.", en: "I have work, so I will go." }], substitution_slots: ["ਕੰਮ", "ਸਮਾਂ", "ਦਰਦ"], common_mistake: { audience: "both", vi: "ਇਸ ਲਈ nghĩa là vì vậy/nên.", en: "ਇਸ ਲਈ means therefore/so." } },
  { id: "pa_pattern_039", topic: "giving_reason", level: "A2", pattern: "ਮਾਫ਼ ਕਰਨਾ, ___।", romanization: "maf karna, ___", meaning_vi: "Xin lỗi, ___.", meaning_en: "Sorry, ___.", examples: [{ pa: "ਮਾਫ਼ ਕਰਨਾ, ਮੈਂ ਦੇਰ ਨਾਲ ਆਇਆ।", romanization: "maf karna, main der nal aia", vi: "Xin lỗi, tôi đến muộn.", en: "Sorry, I came late." }], substitution_slots: ["ਮੈਂ ਦੇਰ ਨਾਲ ਆਇਆ", "ਮੈਨੂੰ ਸਮਝ ਨਹੀਂ ਆਈ"], common_mistake: { audience: "vi", vi: "Đừng dùng ਧੰਨਵਾਦ cho xin lỗi.", en: "Do not use ਧੰਨਵਾਦ for apology." } },
  { id: "pa_pattern_040", topic: "giving_reason", level: "A2", pattern: "ਮੇਰੇ ਕੋਲ ___ ਨਹੀਂ ਹੈ, ਇਸ ਲਈ ___।", romanization: "mere kol ___ nahin hai, is lai ___", meaning_vi: "Tôi không có ___, nên ___.", meaning_en: "I do not have ___, so ___.", examples: [{ pa: "ਮੇਰੇ ਕੋਲ ਸਮਾਂ ਨਹੀਂ ਹੈ, ਇਸ ਲਈ ਮੈਂ ਨਹੀਂ ਆ ਸਕਦਾ।", romanization: "mere kol sama nahin hai, is lai main nahin aa sakda", vi: "Tôi không có thời gian, nên tôi không thể đến.", en: "I do not have time, so I cannot come." }], substitution_slots: ["ਸਮਾਂ", "ਪੈਸੇ", "ਕਾਰਡ"], common_mistake: { audience: "en", vi: "Punjabi dùng ਮੇਰੇ ਕੋਲ cho 'I have'.", en: "Punjabi uses ਮੇਰੇ ਕੋਲ for possession." } },

  { id: "pa_pattern_041", topic: "comparing", level: "A2", pattern: "___ ___ ਨਾਲੋਂ ਵੱਡਾ ਹੈ।", romanization: "___ ___ nalon vadda hai", meaning_vi: "___ lớn hơn ___.", meaning_en: "___ is bigger than ___.", examples: [{ pa: "ਇਹ ਕਮਰਾ ਉਸ ਕਮਰੇ ਨਾਲੋਂ ਵੱਡਾ ਹੈ।", romanization: "ih kamra us kamre nalon vadda hai", vi: "Phòng này lớn hơn phòng kia.", en: "This room is bigger than that room." }], substitution_slots: ["ਇਹ ਕਮਰਾ", "ਉਸ ਕਮਰੇ", "ਵੱਡਾ"], common_mistake: { audience: "en", vi: "ਨਾਲੋਂ đi sau chuẩn so sánh.", en: "ਨਾਲੋਂ follows the comparison standard." } },
  { id: "pa_pattern_042", topic: "comparing", level: "A2", pattern: "___ ___ ਨਾਲੋਂ ਸਸਤਾ ਹੈ।", romanization: "___ ___ nalon sasta hai", meaning_vi: "___ rẻ hơn ___.", meaning_en: "___ is cheaper than ___.", examples: [{ pa: "ਇਹ ਬੈਗ ਉਸ ਬੈਗ ਨਾਲੋਂ ਸਸਤਾ ਹੈ।", romanization: "ih bag us bag nalon sasta hai", vi: "Túi này rẻ hơn túi kia.", en: "This bag is cheaper than that bag." }], substitution_slots: ["ਇਹ ਬੈਗ", "ਉਸ ਬੈਗ", "ਸਸਤਾ"], common_mistake: { audience: "both", vi: "Không dùng more/less kiểu tiếng Anh.", en: "Do not insert English more/less words." } },
  { id: "pa_pattern_043", topic: "comparing", level: "A2", pattern: "___ ਸਭ ਤੋਂ ਵਧੀਆ ਹੈ।", romanization: "___ sabh ton vadhia hai", meaning_vi: "___ là tốt nhất.", meaning_en: "___ is the best.", examples: [{ pa: "ਇਹ ਰਸਤਾ ਸਭ ਤੋਂ ਵਧੀਆ ਹੈ।", romanization: "ih rasta sabh ton vadhia hai", vi: "Đường này là tốt nhất.", en: "This route is the best." }], substitution_slots: ["ਇਹ ਰਸਤਾ", "ਇਹ ਚੋਣ", "ਵਧੀਆ"], common_mistake: { audience: "vi", vi: "ਸਭ ਤੋਂ là dấu hiệu so sánh nhất.", en: "ਸਭ ਤੋਂ marks a superlative." } },
  { id: "pa_pattern_044", topic: "comparing", level: "A2", pattern: "___ ਥੋੜ੍ਹਾ ਜ਼ਿਆਦਾ ___ ਹੈ।", romanization: "___ thora ziada ___ hai", meaning_vi: "___ hơi ___ hơn/nhiều hơn.", meaning_en: "___ is a little more ___.", examples: [{ pa: "ਇਹ ਥੋੜ੍ਹਾ ਜ਼ਿਆਦਾ ਮਹਿੰਗਾ ਹੈ।", romanization: "ih thora ziada mahinga hai", vi: "Cái này hơi đắt hơn.", en: "This is a little more expensive." }], substitution_slots: ["ਇਹ", "ਮਹਿੰਗਾ", "ਵੱਡਾ"], common_mistake: { audience: "both", vi: "ਜ਼ਿਆਦਾ dùng cho 'hơn/nhiều hơn' theo ngữ cảnh.", en: "ਜ਼ਿਆਦਾ can mean more depending on context." } },
  { id: "pa_pattern_045", topic: "comparing", level: "A2", pattern: "ਦੋਵੇਂ ___ ਹਨ।", romanization: "dove ___ han", meaning_vi: "Cả hai đều ___.", meaning_en: "Both are ___.", examples: [{ pa: "ਦੋਵੇਂ ਚੰਗੇ ਹਨ।", romanization: "dove change han", vi: "Cả hai đều tốt.", en: "Both are good." }], substitution_slots: ["ਚੰਗੇ", "ਮਹਿੰਗੇ", "ਨੇੜੇ"], common_mistake: { audience: "en", vi: "Với số nhiều thường dùng ਹਨ.", en: "Use ਹਨ with plural subjects." } },

  { id: "pa_pattern_046", topic: "polite_request", level: "A1", pattern: "ਕਿਰਪਾ ਕਰਕੇ ___।", romanization: "kirpa karke ___", meaning_vi: "Làm ơn ___.", meaning_en: "Please ___.", examples: [{ pa: "ਕਿਰਪਾ ਕਰਕੇ ਹੌਲੀ ਬੋਲੋ।", romanization: "kirpa karke hauli bolo", vi: "Làm ơn nói chậm.", en: "Please speak slowly." }], substitution_slots: ["ਹੌਲੀ ਬੋਲੋ", "ਇੱਥੇ ਬੈਠੋ", "ਉਡੀਕ ਕਰੋ"], common_mistake: { audience: "both", vi: "Dùng với dạng yêu cầu phù hợp.", en: "Use it with an appropriate request form." } },
  { id: "pa_pattern_047", topic: "polite_request", level: "A1", pattern: "___ ਕਰੋ ਜੀ।", romanization: "___ karo ji", meaning_vi: "Vui lòng làm ___.", meaning_en: "Please do ___.", examples: [{ pa: "ਮਦਦ ਕਰੋ ਜੀ।", romanization: "madad karo ji", vi: "Vui lòng giúp.", en: "Please help." }], substitution_slots: ["ਮਦਦ", "ਉਡੀਕ", "ਦਸਤਖ਼ਤ"], common_mistake: { audience: "vi", vi: "ਜੀ không phải lúc nào cũng tương đương 'ạ' 1-1.", en: "ਜੀ is not always a one-to-one equivalent of Vietnamese 'ạ'." } },
  { id: "pa_pattern_048", topic: "polite_request", level: "A2", pattern: "ਕੀ ਤੁਸੀਂ ___ ਸਕਦੇ ਹੋ?", romanization: "ki tusi ___ sakde ho?", meaning_vi: "Bạn có thể ___ được không?", meaning_en: "Could you ___?", examples: [{ pa: "ਕੀ ਤੁਸੀਂ ਮਦਦ ਕਰ ਸਕਦੇ ਹੋ?", romanization: "ki tusi madad kar sakde ho", vi: "Bạn có thể giúp không?", en: "Could you help?" }], substitution_slots: ["ਮਦਦ ਕਰ", "ਦੱਸ", "ਲਿਖ"], common_mistake: { audience: "en", vi: "Không cần could như một từ riêng.", en: "Do not add a separate word for English 'could'." } },
  { id: "pa_pattern_049", topic: "polite_request", level: "A2", pattern: "ਮੈਨੂੰ ___ ਦਿਓ ਜੀ।", romanization: "mainu ___ dio ji", meaning_vi: "Vui lòng đưa tôi ___.", meaning_en: "Please give me ___.", examples: [{ pa: "ਮੈਨੂੰ ਫਾਰਮ ਦਿਓ ਜੀ।", romanization: "mainu form dio ji", vi: "Vui lòng đưa tôi mẫu đơn.", en: "Please give me the form." }], substitution_slots: ["ਫਾਰਮ", "ਰਸੀਦ", "ਪਾਣੀ"], common_mistake: { audience: "both", vi: "ਦਿਓ ਜੀ mềm hơn ਦੇ.", en: "ਦਿਓ ਜੀ is softer than a bare ਦੇ." } },
  { id: "pa_pattern_050", topic: "polite_request", level: "A2", pattern: "ਮੈਨੂੰ ___ ਸਮਝਾਓ ਜੀ।", romanization: "mainu ___ samjhao ji", meaning_vi: "Vui lòng giải thích ___ cho tôi.", meaning_en: "Please explain ___ to me.", examples: [{ pa: "ਮੈਨੂੰ ਇਹ ਸਮਝਾਓ ਜੀ।", romanization: "mainu ih samjhao ji", vi: "Vui lòng giải thích cái này cho tôi.", en: "Please explain this to me." }], substitution_slots: ["ਇਹ", "ਫਾਰਮ", "ਨਿਯਮ"], common_mistake: { audience: "vi", vi: "Không bỏ ਮੈਨੂੰ nếu muốn nói 'cho tôi'.", en: "Keep ਮੈਨੂੰ when you mean 'to me'." } },

  { id: "pa_pattern_051", topic: "complaint", level: "A2", pattern: "ਇਹ ਕੰਮ ਨਹੀਂ ਕਰ ਰਿਹਾ।", romanization: "ih kamm nahin kar riha", meaning_vi: "Cái này không hoạt động.", meaning_en: "This is not working.", examples: [{ pa: "ਇਹ ਮਸ਼ੀਨ ਕੰਮ ਨਹੀਂ ਕਰ ਰਹੀ।", romanization: "ih machine kamm nahin kar rahi", vi: "Máy này không hoạt động.", en: "This machine is not working." }], substitution_slots: ["ਇਹ", "ਮਸ਼ੀਨ", "ਫੋਨ"], common_mistake: { audience: "en", vi: "ਰਿਹਾ/ਰਹੀ đổi theo danh từ/ngữ cảnh.", en: "ਰਿਹਾ/ਰਹੀ changes with noun/context." } },
  { id: "pa_pattern_052", topic: "complaint", level: "A2", pattern: "ਮੈਨੂੰ ਸਮੱਸਿਆ ਹੈ।", romanization: "mainu samassia hai", meaning_vi: "Tôi có vấn đề.", meaning_en: "I have a problem.", examples: [{ pa: "ਮੈਨੂੰ ਭੁਗਤਾਨ ਨਾਲ ਸਮੱਸਿਆ ਹੈ।", romanization: "mainu bhugtan nal samassia hai", vi: "Tôi có vấn đề với thanh toán.", en: "I have a problem with payment." }], substitution_slots: ["ਭੁਗਤਾਨ ਨਾਲ", "ਫੋਨ ਨਾਲ"], common_mistake: { audience: "vi", vi: "Giữ ਮੈਨੂੰ cho trải nghiệm/cảm nhận.", en: "Use ਮੈਨੂੰ for the experiencer pattern." } },
  { id: "pa_pattern_053", topic: "complaint", level: "A2", pattern: "ਇਹ ਬਹੁਤ ਮਹਿੰਗਾ ਹੈ।", romanization: "ih bahut mahinga hai", meaning_vi: "Cái này rất đắt.", meaning_en: "This is very expensive.", examples: [{ pa: "ਇਹ ਟਿਕਟ ਬਹੁਤ ਮਹਿੰਗੀ ਹੈ।", romanization: "ih ticket bahut mahingi hai", vi: "Vé này rất đắt.", en: "This ticket is very expensive." }], substitution_slots: ["ਬਹੁਤ", "ਮਹਿੰਗਾ", "ਮਹਿੰਗੀ"], common_mistake: { audience: "both", vi: "Tính từ có thể đổi dạng.", en: "The adjective may change form." } },
  { id: "pa_pattern_054", topic: "complaint", level: "A2", pattern: "ਮੈਨੂੰ ਇਹ ਪਸੰਦ ਨਹੀਂ।", romanization: "mainu ih pasand nahin", meaning_vi: "Tôi không thích cái này.", meaning_en: "I do not like this.", examples: [{ pa: "ਮੈਨੂੰ ਇਹ ਖਾਣਾ ਪਸੰਦ ਨਹੀਂ।", romanization: "mainu ih khana pasand nahin", vi: "Tôi không thích món ăn này.", en: "I do not like this food." }], substitution_slots: ["ਇਹ", "ਖਾਣਾ", "ਕਮਰਾ"], common_mistake: { audience: "en", vi: "Không dịch 'like' bằng cấu trúc chủ ngữ giống tiếng Anh.", en: "Do not force English subject-verb 'like' word order." } },
  { id: "pa_pattern_055", topic: "complaint", level: "A2", pattern: "ਕਿਰਪਾ ਕਰਕੇ ਇਸਨੂੰ ਠੀਕ ਕਰੋ।", romanization: "kirpa karke isnu thik karo", meaning_vi: "Làm ơn sửa cái này.", meaning_en: "Please fix this.", examples: [{ pa: "ਕਿਰਪਾ ਕਰਕੇ ਫੋਨ ਠੀਕ ਕਰੋ।", romanization: "kirpa karke phone thik karo", vi: "Làm ơn sửa điện thoại.", en: "Please fix the phone." }], substitution_slots: ["ਇਸਨੂੰ", "ਫੋਨ", "ਮਸ਼ੀਨ"], common_mistake: { audience: "both", vi: "Dù phàn nàn, vẫn có thể dùng ਕਿਰਪਾ ਕਰਕੇ để lịch sự.", en: "Even in a complaint, ਕਿਰਪਾ ਕਰਕੇ keeps it polite." } },

  { id: "pa_pattern_056", topic: "opinion", level: "A2", pattern: "ਮੇਰੇ ਖ਼ਿਆਲ ਵਿੱਚ ___।", romanization: "mere khial vich ___", meaning_vi: "Theo tôi thì ___.", meaning_en: "In my opinion, ___.", examples: [{ pa: "ਮੇਰੇ ਖ਼ਿਆਲ ਵਿੱਚ ਇਹ ਚੰਗਾ ਹੈ।", romanization: "mere khial vich ih changa hai", vi: "Theo tôi thì cái này tốt.", en: "In my opinion, this is good." }], substitution_slots: ["ਇਹ ਚੰਗਾ ਹੈ", "ਇਹ ਔਖਾ ਹੈ"], common_mistake: { audience: "en", vi: "ਵਿੱਚ đứng sau ਖ਼ਿਆਲ.", en: "ਵਿੱਚ follows ਖ਼ਿਆਲ in this phrase." } },
  { id: "pa_pattern_057", topic: "opinion", level: "A2", pattern: "ਮੈਨੂੰ ਲੱਗਦਾ ਹੈ ਕਿ ___।", romanization: "mainu lagda hai ki ___", meaning_vi: "Tôi nghĩ rằng ___.", meaning_en: "I think that ___.", examples: [{ pa: "ਮੈਨੂੰ ਲੱਗਦਾ ਹੈ ਕਿ ਇਹ ਠੀਕ ਹੈ।", romanization: "mainu lagda hai ki ih thik hai", vi: "Tôi nghĩ rằng điều này ổn.", en: "I think this is okay." }], substitution_slots: ["ਇਹ ਠੀਕ ਹੈ", "ਉਹ ਆਵੇਗਾ"], common_mistake: { audience: "vi", vi: "ਕਿ giống 'rằng/là' trong nhiều câu.", en: "ਕਿ often works like 'that' introducing a clause." } },
  { id: "pa_pattern_058", topic: "opinion", level: "A2", pattern: "ਇਹ ਚੰਗਾ ਵਿਚਾਰ ਹੈ।", romanization: "ih changa vichar hai", meaning_vi: "Đây là ý kiến hay.", meaning_en: "This is a good idea.", examples: [{ pa: "ਹਾਂ, ਇਹ ਚੰਗਾ ਵਿਚਾਰ ਹੈ।", romanization: "han, ih changa vichar hai", vi: "Vâng, đây là ý kiến hay.", en: "Yes, this is a good idea." }], substitution_slots: ["ਚੰਗਾ", "ਵਧੀਆ", "ਵਿਚਾਰ"], common_mistake: { audience: "both", vi: "Giữ ਹੈ ở cuối câu danh từ.", en: "Keep ਹੈ at the end of this noun sentence." } },
  { id: "pa_pattern_059", topic: "opinion", level: "A2", pattern: "ਮੈਂ ਸਹਿਮਤ ਹਾਂ।", romanization: "main sahimat han", meaning_vi: "Tôi đồng ý.", meaning_en: "I agree.", examples: [{ pa: "ਮੈਂ ਤੁਹਾਡੇ ਨਾਲ ਸਹਿਮਤ ਹਾਂ।", romanization: "main tuhade nal sahimat han", vi: "Tôi đồng ý với bạn.", en: "I agree with you." }], substitution_slots: ["ਤੁਹਾਡੇ ਨਾਲ", "ਪੂਰੀ ਤਰ੍ਹਾਂ"], common_mistake: { audience: "en", vi: "Với 'with you' dùng ਨਾਲ.", en: "Use ਨਾਲ for 'with you'." } },
  { id: "pa_pattern_060", topic: "opinion", level: "A2", pattern: "ਮੈਂ ਸਹਿਮਤ ਨਹੀਂ ਹਾਂ।", romanization: "main sahimat nahin han", meaning_vi: "Tôi không đồng ý.", meaning_en: "I disagree.", examples: [{ pa: "ਮੈਂ ਇਸ ਨਾਲ ਸਹਿਮਤ ਨਹੀਂ ਹਾਂ।", romanization: "main is nal sahimat nahin han", vi: "Tôi không đồng ý với điều này.", en: "I do not agree with this." }], substitution_slots: ["ਇਸ ਨਾਲ", "ਪੂਰੀ ਤਰ੍ਹਾਂ"], common_mistake: { audience: "both", vi: "ਨਹੀਂ đặt trước ਹਾਂ trong mẫu này.", en: "ਨਹੀਂ appears before ਹਾਂ in this pattern." } },

  { id: "pa_pattern_061", topic: "family", level: "A1", pattern: "ਇਹ ਮੇਰਾ ___ ਹੈ।", romanization: "ih mera ___ hai", meaning_vi: "Đây là ___ của tôi (giống đực).", meaning_en: "This is my ___ (masculine).", examples: [{ pa: "ਇਹ ਮੇਰਾ ਭਰਾ ਹੈ।", romanization: "ih mera bhara hai", vi: "Đây là anh/em trai tôi.", en: "This is my brother." }], substitution_slots: ["ਭਰਾ", "ਪਿਤਾ", "ਦੋਸਤ"], common_mistake: { audience: "en", vi: "ਮੇਰਾ đổi theo danh từ.", en: "ਮੇਰਾ can change with the noun." } },
  { id: "pa_pattern_062", topic: "family", level: "A1", pattern: "ਇਹ ਮੇਰੀ ___ ਹੈ।", romanization: "ih meri ___ hai", meaning_vi: "Đây là ___ của tôi (giống cái).", meaning_en: "This is my ___ (feminine).", examples: [{ pa: "ਇਹ ਮੇਰੀ ਮਾਂ ਹੈ।", romanization: "ih meri man hai", vi: "Đây là mẹ tôi.", en: "This is my mother." }], substitution_slots: ["ਮਾਂ", "ਭੈਣ", "ਦੋਸਤ"], common_mistake: { audience: "vi", vi: "Tiếng Việt không có giống danh từ; chú ý ਮੇਰਾ/ਮੇਰੀ.", en: "Vietnamese speakers should watch ਮੇਰਾ/ਮੇਰੀ agreement." } },
  { id: "pa_pattern_063", topic: "family", level: "A1", pattern: "ਮੇਰੇ ਕੋਲ ___ ਹੈ।", romanization: "mere kol ___ hai", meaning_vi: "Tôi có ___.", meaning_en: "I have ___.", examples: [{ pa: "ਮੇਰੇ ਕੋਲ ਦੋ ਭਰਾ ਹਨ।", romanization: "mere kol do bhara han", vi: "Tôi có hai anh/em trai.", en: "I have two brothers." }], substitution_slots: ["ਦੋ ਭਰਾ", "ਇੱਕ ਭੈਣ", "ਪਰਿਵਾਰ"], common_mistake: { audience: "en", vi: "Punjabi dùng 'near me' cho sở hữu.", en: "Punjabi uses a 'near me' possession pattern." } },
  { id: "pa_pattern_064", topic: "family", level: "A2", pattern: "ਮੇਰਾ ਪਰਿਵਾਰ ___ ਵਿੱਚ ਰਹਿੰਦਾ ਹੈ।", romanization: "mera parivar ___ vich rahinda hai", meaning_vi: "Gia đình tôi sống ở ___.", meaning_en: "My family lives in ___.", examples: [{ pa: "ਮੇਰਾ ਪਰਿਵਾਰ ਵੀਅਤਨਾਮ ਵਿੱਚ ਰਹਿੰਦਾ ਹੈ।", romanization: "mera parivar Vietnam vich rahinda hai", vi: "Gia đình tôi sống ở Việt Nam.", en: "My family lives in Vietnam." }], substitution_slots: ["ਵੀਅਤਨਾਮ", "ਕੈਨੇਡਾ", "ਪਿੰਡ"], common_mistake: { audience: "both", vi: "ਵਿੱਚ đứng sau nơi chốn.", en: "ਵਿੱਚ follows the place." } },
  { id: "pa_pattern_065", topic: "family", level: "A2", pattern: "ਮੈਂ ਆਪਣੇ ___ ਨੂੰ ਫੋਨ ਕਰਦਾ ਹਾਂ।", romanization: "main apne ___ nu phone karda han", meaning_vi: "Tôi gọi điện cho ___ của mình.", meaning_en: "I call my ___.", examples: [{ pa: "ਮੈਂ ਆਪਣੇ ਪਿਤਾ ਨੂੰ ਫੋਨ ਕਰਦਾ ਹਾਂ।", romanization: "main apne pita nu phone karda han", vi: "Tôi gọi điện cho cha tôi.", en: "I call my father." }], substitution_slots: ["ਪਿਤਾ", "ਮਾਂ", "ਦੋਸਤ"], common_mistake: { audience: "vi", vi: "ਨੂੰ đánh dấu người nhận/hướng tới.", en: "ਨੂੰ marks the person receiving the action." } },

  { id: "pa_pattern_066", topic: "workplace", level: "A1", pattern: "ਮੈਂ ___ ਵਿੱਚ ਕੰਮ ਕਰਦਾ ਹਾਂ।", romanization: "main ___ vich kamm karda han", meaning_vi: "Tôi làm việc ở ___.", meaning_en: "I work in/at ___.", examples: [{ pa: "ਮੈਂ ਦਫ਼ਤਰ ਵਿੱਚ ਕੰਮ ਕਰਦਾ ਹਾਂ।", romanization: "main daftar vich kamm karda han", vi: "Tôi làm việc ở văn phòng.", en: "I work in an office." }], substitution_slots: ["ਦਫ਼ਤਰ", "ਸਕੂਲ", "ਦੁਕਾਨ"], common_mistake: { audience: "both", vi: "Người nói nữ thường dùng ਕਰਦੀ.", en: "A female speaker commonly uses ਕਰਦੀ." } },
  { id: "pa_pattern_067", topic: "workplace", level: "A2", pattern: "ਮੇਰੀ ਮੀਟਿੰਗ ___ ਵਜੇ ਹੈ।", romanization: "meri meeting ___ vaje hai", meaning_vi: "Cuộc họp của tôi lúc ___ giờ.", meaning_en: "My meeting is at ___ o'clock.", examples: [{ pa: "ਮੇਰੀ ਮੀਟਿੰਗ ਤਿੰਨ ਵਜੇ ਹੈ।", romanization: "meri meeting tin vaje hai", vi: "Cuộc họp của tôi lúc ba giờ.", en: "My meeting is at three." }], substitution_slots: ["ਤਿੰਨ", "ਚਾਰ", "ਦੱਸ"], common_mistake: { audience: "en", vi: "Không cần at như một từ riêng.", en: "Do not add a separate word for English 'at'." } },
  { id: "pa_pattern_068", topic: "workplace", level: "A2", pattern: "ਮੈਨੂੰ ਈਮੇਲ ਭੇਜੋ ਜੀ।", romanization: "mainu email bhejo ji", meaning_vi: "Vui lòng gửi email cho tôi.", meaning_en: "Please send me an email.", examples: [{ pa: "ਮੈਨੂੰ ਰਿਪੋਰਟ ਈਮੇਲ ਕਰੋ ਜੀ।", romanization: "mainu report email karo ji", vi: "Vui lòng gửi báo cáo qua email cho tôi.", en: "Please email me the report." }], substitution_slots: ["ਈਮੇਲ", "ਰਿਪੋਰਟ", "ਫਾਇਲ"], common_mistake: { audience: "vi", vi: "Giữ ਜੀ trong bối cảnh công việc lịch sự.", en: "Keep ਜੀ for polite workplace requests." } },
  { id: "pa_pattern_069", topic: "workplace", level: "A2", pattern: "ਮੈਨੂੰ ਛੁੱਟੀ ਚਾਹੀਦੀ ਹੈ।", romanization: "mainu chhutti chahidi hai", meaning_vi: "Tôi cần nghỉ phép.", meaning_en: "I need leave/time off.", examples: [{ pa: "ਮੈਨੂੰ ਕੱਲ੍ਹ ਛੁੱਟੀ ਚਾਹੀਦੀ ਹੈ।", romanization: "mainu kallh chhutti chahidi hai", vi: "Ngày mai tôi cần nghỉ phép.", en: "I need leave tomorrow." }], substitution_slots: ["ਕੱਲ੍ਹ", "ਅੱਜ", "ਇੱਕ ਦਿਨ"], common_mistake: { audience: "en", vi: "ਛੁੱਟੀ không chỉ là holiday; có thể là nghỉ phép.", en: "ਛੁੱਟੀ can mean leave/time off, not only holiday." } },
  { id: "pa_pattern_070", topic: "workplace", level: "A2", pattern: "ਕੰਮ ਮੁਕ ਗਿਆ ਹੈ।", romanization: "kamm muk gia hai", meaning_vi: "Công việc đã xong.", meaning_en: "The work is finished.", examples: [{ pa: "ਮੇਰਾ ਕੰਮ ਮੁਕ ਗਿਆ ਹੈ।", romanization: "mera kamm muk gia hai", vi: "Công việc của tôi đã xong.", en: "My work is finished." }], substitution_slots: ["ਮੇਰਾ ਕੰਮ", "ਰਿਪੋਰਟ", "ਮੀਟਿੰਗ"], common_mistake: { audience: "both", vi: "Đừng dịch từng chữ 'finish' bằng một mẫu tiếng Anh.", en: "Do not force an English 'finish' structure." } },

  { id: "pa_pattern_071", topic: "clinic", level: "A1", pattern: "ਮੈਨੂੰ ਦਰਦ ਹੈ।", romanization: "mainu dard hai", meaning_vi: "Tôi bị đau.", meaning_en: "I have pain.", examples: [{ pa: "ਮੈਨੂੰ ਸਿਰ ਦਰਦ ਹੈ।", romanization: "mainu sir dard hai", vi: "Tôi đau đầu.", en: "I have a headache." }], substitution_slots: ["ਸਿਰ", "ਪੇਟ", "ਦੰਦ"], common_mistake: { audience: "en", vi: "Dùng ਮੈਨੂੰ cho cảm giác đau.", en: "Use ਮੈਨੂੰ for experiencing pain." } },
  { id: "pa_pattern_072", topic: "clinic", level: "A1", pattern: "ਮੈਂ ਬੀਮਾਰ ਹਾਂ।", romanization: "main bimar han", meaning_vi: "Tôi bị bệnh.", meaning_en: "I am sick.", examples: [{ pa: "ਅੱਜ ਮੈਂ ਬੀਮਾਰ ਹਾਂ।", romanization: "ajj main bimar han", vi: "Hôm nay tôi bị bệnh.", en: "I am sick today." }], substitution_slots: ["ਅੱਜ", "ਥੋੜ੍ਹਾ", "ਬਹੁਤ"], common_mistake: { audience: "vi", vi: "Không bỏ ਹਾਂ.", en: "Vietnamese speakers should keep ਹਾਂ." } },
  { id: "pa_pattern_073", topic: "clinic", level: "A2", pattern: "ਮੈਨੂੰ ਡਾਕਟਰ ਚਾਹੀਦਾ ਹੈ।", romanization: "mainu daktar chahida hai", meaning_vi: "Tôi cần bác sĩ.", meaning_en: "I need a doctor.", examples: [{ pa: "ਮੈਨੂੰ ਹੁਣ ਡਾਕਟਰ ਚਾਹੀਦਾ ਹੈ।", romanization: "mainu hun daktar chahida hai", vi: "Tôi cần bác sĩ ngay bây giờ.", en: "I need a doctor now." }], substitution_slots: ["ਹੁਣ", "ਡਾਕਟਰ", "ਮਦਦ"], common_mistake: { audience: "both", vi: "Mẫu này nghiêng về nhu cầu, không phải sở hữu.", en: "This pattern marks need, not possession." } },
  { id: "pa_pattern_074", topic: "clinic", level: "A2", pattern: "ਮੈਨੂੰ ਦਵਾਈ ਕਦੋਂ ਲੈਣੀ ਹੈ?", romanization: "mainu davai kadon laini hai?", meaning_vi: "Tôi phải uống/lấy thuốc khi nào?", meaning_en: "When should I take the medicine?", examples: [{ pa: "ਮੈਨੂੰ ਇਹ ਦਵਾਈ ਕਦੋਂ ਲੈਣੀ ਹੈ?", romanization: "mainu ih davai kadon laini hai", vi: "Tôi phải uống thuốc này khi nào?", en: "When should I take this medicine?" }], substitution_slots: ["ਇਹ ਦਵਾਈ", "ਕਦੋਂ", "ਲੈਣੀ"], common_mistake: { audience: "en", vi: "ਕਦੋਂ đứng trước cụm động từ.", en: "ਕਦੋਂ comes before the verb phrase here." } },
  { id: "pa_pattern_075", topic: "clinic", level: "A2", pattern: "ਮੈਨੂੰ ਐਲਰਜੀ ਹੈ।", romanization: "mainu allergy hai", meaning_vi: "Tôi bị dị ứng.", meaning_en: "I have an allergy.", examples: [{ pa: "ਮੈਨੂੰ ਇਸ ਦਵਾਈ ਨਾਲ ਐਲਰਜੀ ਹੈ।", romanization: "mainu is davai nal allergy hai", vi: "Tôi dị ứng với thuốc này.", en: "I am allergic to this medicine." }], substitution_slots: ["ਇਸ ਦਵਾਈ ਨਾਲ", "ਖਾਣੇ ਨਾਲ"], common_mistake: { audience: "both", vi: "ਨਾਲ diễn đạt 'với' trong dị ứng với thứ gì.", en: "ਨਾਲ can mark 'to/with' for allergy triggers." } },

  { id: "pa_pattern_076", topic: "public_office", level: "A1", pattern: "ਮੈਨੂੰ ਫਾਰਮ ਚਾਹੀਦਾ ਹੈ।", romanization: "mainu form chahida hai", meaning_vi: "Tôi cần mẫu đơn.", meaning_en: "I need a form.", examples: [{ pa: "ਮੈਨੂੰ ਇਹ ਫਾਰਮ ਚਾਹੀਦਾ ਹੈ।", romanization: "mainu ih form chahida hai", vi: "Tôi cần mẫu đơn này.", en: "I need this form." }], substitution_slots: ["ਇਹ ਫਾਰਮ", "ਅਰਜ਼ੀ", "ਰਸੀਦ"], common_mistake: { audience: "vi", vi: "Không bỏ ਮੈਨੂੰ trong mẫu cần.", en: "Do not drop ਮੈਨੂੰ in this need pattern." } },
  { id: "pa_pattern_077", topic: "public_office", level: "A2", pattern: "ਮੈਂ ਅਰਜ਼ੀ ਦੇਣੀ ਹੈ।", romanization: "main arzi deni hai", meaning_vi: "Tôi phải nộp đơn.", meaning_en: "I have to submit an application.", examples: [{ pa: "ਮੈਂ ਅੱਜ ਅਰਜ਼ੀ ਦੇਣੀ ਹੈ।", romanization: "main ajj arzi deni hai", vi: "Hôm nay tôi phải nộp đơn.", en: "I have to submit the application today." }], substitution_slots: ["ਅੱਜ", "ਅਰਜ਼ੀ", "ਫਾਰਮ"], common_mistake: { audience: "en", vi: "ਦੇਣੀ là động từ trong cụm nghĩa vụ.", en: "ਦੇਣੀ is part of the obligation phrase here." } },
  { id: "pa_pattern_078", topic: "public_office", level: "A2", pattern: "ਕਿਹੜਾ ਕਾਊਂਟਰ ਹੈ?", romanization: "kihra counter hai?", meaning_vi: "Quầy nào?", meaning_en: "Which counter is it?", examples: [{ pa: "ਪਾਸਪੋਰਟ ਲਈ ਕਿਹੜਾ ਕਾਊਂਟਰ ਹੈ?", romanization: "passport lai kihra counter hai", vi: "Làm hộ chiếu thì quầy nào?", en: "Which counter is for passports?" }], substitution_slots: ["ਪਾਸਪੋਰਟ ਲਈ", "ਵੀਜ਼ਾ ਲਈ", "ਕਾਊਂਟਰ"], common_mistake: { audience: "both", vi: "ਲਈ nghĩa là cho/để trong ngữ cảnh này.", en: "ਲਈ means for in this context." } },
  { id: "pa_pattern_079", topic: "public_office", level: "A2", pattern: "ਮੈਨੂੰ ਦਸਤਖ਼ਤ ਕਰਨੇ ਹਨ।", romanization: "mainu dastakhat karne han", meaning_vi: "Tôi phải ký.", meaning_en: "I have to sign.", examples: [{ pa: "ਮੈਨੂੰ ਇੱਥੇ ਦਸਤਖ਼ਤ ਕਰਨੇ ਹਨ।", romanization: "mainu ithe dastakhat karne han", vi: "Tôi phải ký ở đây.", en: "I have to sign here." }], substitution_slots: ["ਇੱਥੇ", "ਫਾਰਮ ਤੇ", "ਦਸਤਖ਼ਤ"], common_mistake: { audience: "vi", vi: "ਤੇ có thể nghĩa là trên/tại trong mẫu biểu.", en: "ਤੇ can mean on/at for forms." } },
  { id: "pa_pattern_080", topic: "public_office", level: "A2", pattern: "ਕੀ ਮੈਨੂੰ ਪਛਾਣ ਪੱਤਰ ਚਾਹੀਦਾ ਹੈ?", romanization: "ki mainu pachhan pattar chahida hai?", meaning_vi: "Tôi có cần giấy tờ tùy thân không?", meaning_en: "Do I need ID?", examples: [{ pa: "ਕੀ ਮੈਨੂੰ ਅੱਜ ਪਛਾਣ ਪੱਤਰ ਚਾਹੀਦਾ ਹੈ?", romanization: "ki mainu ajj pachhan pattar chahida hai", vi: "Hôm nay tôi có cần giấy tờ tùy thân không?", en: "Do I need ID today?" }], substitution_slots: ["ਅੱਜ", "ਪਛਾਣ ਪੱਤਰ", "ਫੋਟੋ"], common_mistake: { audience: "en", vi: "ਕੀ mở câu hỏi yes/no; không thêm do/does.", en: "ਕੀ opens the yes/no question; do not add do/does." } },
];

export default sentencePatterns;
