// src/languages/vietnamese/lessons-c2.ts
// C2 (Mastery) — Advanced intellectual, professional, and literary Vietnamese.
// IDs 487–491 — First batch (5 lessons).

import type { VietnameseLesson } from "./lessons";

export const lessons: VietnameseLesson[] = [
  {
    id: 487,
    level: "C2",
    title_en: "Analyzing Narrative Voice and Subtext",
    subtitle: "Phân tích giọng kể và ẩn ý trong văn học — khi người kể không nói hết sự thật.",
    intro: "Ở bậc C2, đọc văn học không chỉ là hiểu cốt truyện mà là phát hiện những gì người kể che giấu. Giọng kể (narrative voice) là công cụ đầu tiên: người kể là ai? Có đáng tin không? Đang nói với ai? Ẩn ý (subtext) là tầng nghĩa bên dưới câu chữ. Văn học Việt Nam từ Nam Cao đến Nguyễn Huy Thiệp đều là bậc thầy về người kể không đáng tin — họ kể một đằng, sự thật một nẻo.",
    phrases: [
      { english: "The narrator is not telling us everything. Look at what they choose to reveal — and in what order. That choice is never innocent.", vietnamese: "Người kể chuyện không kể cho mình tất cả. Hãy nhìn vào những gì họ chọn tiết lộ, và theo trình tự nào — sự lựa chọn đó không bao giờ là vô tội.", pronunciation: "nguoi ke chuyen khong ke cho minh tat ka, hay nhin vao nhung zi ho chon tiet lo, va theo trinh tu nao, su lua chon do khong bao gio la vo toi", context: "Dùng khi phân tích độ tin cậy của người kể — mọi lựa chọn kể chuyện đều mang hàm ý." },
      { english: "A first-person narrator is the most dangerous kind — they sound honest precisely because they say they saw it themselves. But their 'I' is a mask, not a window.", vietnamese: "Người kể ngôi thứ nhất là loại nguy hiểm nhất — họ nghe có vẻ thật thà chính vì họ nói 'tôi tận mắt thấy'. Nhưng cái 'tôi' ấy là mặt nạ, không phải cửa sổ.", pronunciation: "nguoi ke ngoi thu nhat la loai nguy hiem nhat, ho nghe ko ve that tha chinh vi ho noi toy tan mat thay, nhung kai toy ay la mat na, khong fai kua so", context: "Dùng khi giới thiệu khái niệm người kể ngôi thứ nhất không đáng tin." },
      { english: "Subtext is not what the character hides on purpose — it is what the author hides from the character, and shows only to us.", vietnamese: "Ẩn ý không phải là điều nhân vật cố tình che giấu — mà là điều tác giả giấu khỏi nhân vật, và chỉ tiết lộ cho độc giả chúng ta.", pronunciation: "an i khong fai la dieu nhan vat ko tinh che zau, ma la dieu tak za zau khoi nhan vat, va chi tiet lo cho dok za chung ta", context: "Dùng để phân biệt ẩn ý với mỉa mai kịch tính (dramatic irony)." },
      { english: "Nam Cao's Chí Phèo is told by a narrator who sounds compassionate — but look closer: he is mocking everyone, including the reader who feels sorry for Chí.", vietnamese: "Chí Phèo của Nam Cao được kể bởi một giọng nghe có vẻ thương cảm — nhưng nhìn kỹ thì người kể đang châm biếm tất cả, kể cả độc giả đang thương Chí.", pronunciation: "chi feo kua nam kao duoc ke boi mot zong nghe ko ve thuong kam, nhung nhin ki thi nguoi ke dang cham biem tat ka, ke ka dok za dang thuong chi", context: "Dùng khi phân tích Nam Cao — ví dụ kinh điển về người kể không đáng tin trong văn học Việt." },
      { english: "When a narrator insists too much — 'trust me, I am telling the truth' — that is exactly when you should trust them least.", vietnamese: "Khi người kể cứ nhấn mạnh 'tin tôi đi, tôi nói thật đấy' — đó chính là lúc bạn nên tin họ ít nhất.", pronunciation: "khi nguoi ke ku nhan manh tin toy di, toy noi that day, do chinh la luk ban nen tin ho it nhat", context: "Dùng để dạy nguyên tắc: càng khẳng định trung thực, càng đáng ngờ." },
      { english: "The gap between what the narrator says and what the text shows — that gap is where literature lives.", vietnamese: "Khoảng cách giữa điều người kể nói và điều văn bản cho thấy — chính khoảng cách ấy là nơi văn học tồn tại.", pronunciation: "khwang kach zua dieu nguoi ke noi va dieu van ban cho thay, chinh khwang kach ay la noi van hok ton tai", context: "Dùng làm câu kết luận — văn học nằm ở khe hở giữa lời kể và sự thật." }
    ],
    dialogue: [
      { speaker: "Học viên", vietnamese: "Thưa thầy, làm sao để biết một người kể đang nói dối? Có dấu hiệu nào trong văn bản không ạ?", english: "Professor, how do you know when a narrator is lying? Are there signs in the text?", pronunciation: "thua thay, lam sao de biet mot nguoi ke dang noi doi, ko zou hieu nao trong van ban khong a" },
      { speaker: "Giảng viên", vietnamese: "Có ba dấu hiệu chính. Một: họ tự biện hộ quá nhiều, như kiểu 'tôi không phải loại người như thế'. Hai: họ kể sự kiện nhưng lại bỏ trống cảm xúc của chính mình ở những thời điểm then chốt. Ba: phiên bản của họ mâu thuẫn với lời kể của nhân vật khác mà tác giả cố tình để lộ ra.", english: "Three main signs. One: they justify themselves too much — 'I'm not that kind of person.' Two: they recount events but leave out their own emotions at key moments. Three: their version contradicts other characters' accounts that the author deliberately reveals.", pronunciation: "ko ba zou hieu chinh, mot ho tu bien ho kwa nhieu, nhu kieu toy khong fai loai nguoi nhu the, hai ho ke su kien nhung lai bo trong kam xuk kua chinh minh o nhung thoi diem then chot, ba fien ban kua ho mau thuan voi loi ke kua nhan vat khak ma tak za ko tinh de lo ra" },
      { speaker: "Học viên", vietnamese: "Vậy trong văn học Việt, tác phẩm nào nên đọc để luyện kỹ năng này ạ?", english: "So in Vietnamese literature, which works should one read to practice this skill?", pronunciation: "vay trong van hok viet, tak fam nao nen dok de luyen ki nang nay a" },
      { speaker: "Giảng viên", vietnamese: "Không thể bỏ qua Chí Phèo của Nam Cao. Đọc xong, em thử trả lời câu này: người kể có thực sự thương Chí Phèo không, hay đang dùng Chí Phèo để chửi cả xã hội? Đọc Nỗi Buồn Chiến Tranh của Bảo Ninh — nhân vật Kiên kể chuyện, nhưng ký ức của anh ta có đáng tin không, khi mà chính anh ta cũng thừa nhận mình 'không phân biệt được đâu là nhớ, đâu là tưởng tượng'?", english: "You must not skip Nam Cao's Chí Phèo. After reading, try answering: does the narrator really pity Chí Phèo, or is he using Chí Phèo to curse the whole society? Read Bảo Ninh's The Sorrow of War — the character Kiên narrates, but are his memories trustworthy when he himself admits he 'cannot tell memory from imagination'?", pronunciation: "khong the bo kwa chi feo kua nam kao, dok xong em thu tra loi kau nay nguoi ke ko thuc su thuong chi feo khong, hay dang dung chi feo de chui ka xa hoi, dok noi buon chien tranh kua bao ninh, nhan vat kien ke chuyen, nhung ki uk kua anh ta ko dang tin khong, khi ma chinh anh ta kung thua nhan minh khong fan biet duoc dau la nho dau la tuong tuong" }
    ],
    cultural_note: "VĂN HỌC VIỆT VÀ NGƯỜI KỂ KHÔNG ĐÁNG TIN:\n\n(1) Nam Cao (1915-1951): Bậc thầy về giọng kể mỉa mai. Trong Chí Phèo (1941), người kể dùng giọng có vẻ thương cảm nhưng thực chất đang châm biếm toàn bộ trật tự xã hội — từ Bá Kiến đến người nông dân.\n\n(2) Nguyễn Huy Thiệp (1950-2021): Tướng Về Hưu (1987) — người kể là con dâu của vị tướng, nhưng giọng kể lạnh lùng đến mức tàn nhẫn, buộc độc giả phải tự phán xét.\n\n(3) Bảo Ninh (1952-): Nỗi Buồn Chiến Tranh (1990) — người kể ngôi thứ nhất (Kiên) liên tục nhảy giữa quá khứ và hiện tại, giữa ký ức và ảo giác. Độc giả không bao giờ biết chắc điều gì là thật.\n\n(4) Nguyễn Ngọc Tư (1976-): Cánh Đồng Bất Tận (2005) — giọng kể của một đứa trẻ, nhưng đứa trẻ ấy hiểu nhiều hơn những gì nó nói ra.\n\n(5) KỸ THUẬT ĐỌC C2: Khi đọc, hãy gạch chân ba thứ: (a) những chỗ người kể tự biện hộ, (b) những chỗ người kể bỏ trống cảm xúc, (c) những chỗ lời kể của nhân vật khác mâu thuẫn với người kể chính.",
    tip: "LUYỆN TẬP: Đọc một truyện ngắn của Nguyễn Huy Thiệp. Gạch ra tất cả những câu mà người kể đưa ra lời bình luận (không phải lời kể sự kiện). Tự hỏi: lời bình luận đó có đáng tin không? Nếu không, tác giả muốn độc giả nghĩ gì?"
  },
  {
    id: 488,
    level: "C2",
    title_en: "Media Framing and Editorial Tone Analysis",
    subtitle: "Phê bình truyền thông — khi tiêu đề không trung tính và từ ngữ biết nói dối.",
    intro: "Báo chí Việt Nam có hai hệ thống song song: báo chí nhà nước (Nhân Dân, Tuổi Trẻ, Thanh Niên) và báo chí độc lập/truyền thông xã hội. Ở bậc C2, bạn không chỉ đọc tin — bạn phân tích cách tin được đóng khung (framing). Cùng một sự kiện, việc chọn từ 'biểu tình' hay 'tụ tập đông người', 'yêu cầu' hay 'đòi hỏi', 'cải cách' hay 'xóa bỏ' — tất cả đều là lựa chọn chính trị. Người đọc C2 phải nhìn thấy khung tin (frame) trước khi đọc nội dung bên trong.",
    phrases: [
      { english: "Before I read the article, I ask: who owns this newspaper? What is their interest in this story? The frame appears before the first sentence.", vietnamese: "Trước khi đọc bài báo, tôi tự hỏi: tờ báo này của ai? Lợi ích của họ trong câu chuyện này là gì? Khung tin xuất hiện trước cả câu đầu tiên.", pronunciation: "chuok khi dok bai bao, toy tu hoi, to bao nay kua ai, loi ich kua ho trong kau chuyen nay la zi, khung tin xuat hien chuok ka kau dau tien", context: "Dùng để dạy nguyên tắc đầu tiên của phân tích truyền thông." },
      { english: "Look at the headline verb. 'Government announces' versus 'Government admits' — one is neutral, one implies they tried to hide it.", vietnamese: "Nhìn vào động từ ở tiêu đề. 'Chính phủ công bố' với 'Chính phủ thừa nhận' — một cái trung tính, một cái ám chỉ họ đã cố che giấu.", pronunciation: "nhin vao dong tu o tieu de, chinh fu kong bo voi chinh fu thua nhan, mot kai trung tinh, mot kai am chi ho da ko che zau", context: "Dùng để phân tích động từ dẫn — công cụ framing cơ bản nhất." },
      { english: "The same event can be 'a gathering of concerned citizens' or 'an unruly mob' — the choice of noun is the choice of reality.", vietnamese: "Cùng một sự kiện, có thể là 'tập hợp người dân quan tâm' hoặc 'đám đông quá khích' — lựa chọn danh từ là lựa chọn thực tại.", pronunciation: "kung mot su kien, ko the la tap hop nguoi dan kwan tam hoak dam dong kwa khich, lua chon danh tu la lua chon thuc tai", context: "Dùng khi giảng về danh từ framing — cùng sự kiện, hai thực tại." },
      { english: "Vietnamese state media uses a distinct register: 'đồng chí' for allies, 'phần tử' for enemies. Those words are not descriptions — they are verdicts.", vietnamese: "Báo chí nhà nước Việt Nam dùng một ngữ vực riêng: 'đồng chí' cho đồng minh, 'phần tử' cho kẻ thù. Những từ đó không phải mô tả — chúng là phán quyết.", pronunciation: "bao chi nha nuoc viet nam dung mot ngu vuc rieng, dong chi cho dong minh, fun tu cho ke thu, nhung tu do khong fai mo ta, chung la fan kwyet", context: "Dùng khi phân tích báo chí nhà nước Việt Nam." },
      { english: "Headline placement matters: page one top-left versus page four bottom-right. The front page is not news — it is the editorial board's judgment about what you should care about today.", vietnamese: "Vị trí đặt bài cũng quan trọng: trang nhất góc trái trên với trang bốn góc phải dưới. Trang nhất không phải tin tức — đó là phán quyết của ban biên tập về điều bạn nên quan tâm hôm nay.", pronunciation: "vi chi dat bai kung kwan trong, trang nhat gok trai tren voi trang bon gok fai duoi, trang nhat khong fai tin tuk, do la fan kwyet kua ban bien tap ve dieu ban nen kwan tam hom nay", context: "Dùng để phân tích vị trí bài báo như một công cụ framing." },
      { english: "Digital media adds a new layer: the algorithm that chooses what you see is also a frame. But unlike a newspaper, its frame is invisible — you cannot flip to see what it chose NOT to show you.", vietnamese: "Truyền thông số thêm một tầng mới: thuật toán chọn cho bạn thấy gì cũng là một cái khung. Nhưng khác với báo giấy, khung của nó vô hình — bạn không thể lật trang để xem nó đã chọn KHÔNG cho bạn thấy gì.", pronunciation: "chuyen thong so them mot tang moi, thuat toan chon cho ban thay zi kung la mot kai khung, nhung khak voi bao zay, khung kua no vo hinh, ban khong the lat trang de xem no da chon khong cho ban thay zi", context: "Dùng để mở rộng phân tích framing sang truyền thông số." }
    ],
    dialogue: [
      { speaker: "Học viên", vietnamese: "Thưa cô, làm sao phân biệt được bài báo đưa tin khách quan và bài báo có lập trường?", english: "Professor, how do you distinguish between an objective news article and one with a stance?", pronunciation: "thua co, lam sao fan biet duoc bai bao dua tin khach kwan va bai bao ko lap chuong" },
      { speaker: "Nhà báo", vietnamese: "Tin khách quan tuyệt đối không tồn tại. Nhưng có một cách thực tế hơn: đếm số nguồn được trích dẫn. Bài càng ít nguồn, càng dễ là lập trường. Bài có từ ba nguồn trở lên, trong đó có ít nhất một nguồn đối lập — đó là bài có nỗ lực cân bằng.", english: "Absolutely objective news does not exist. But there is a more practical way: count the number of sources cited. Fewer sources means more likely a stance piece. An article with three or more sources, including at least one opposing source — that shows an effort at balance.", pronunciation: "tin khach kwan tuyet doi khong ton tai, nhung ko mot kach thuc te hon, dem so nguon duoc trich dan, bai kang it nguon kang de la lap chuong, bai ko tu ba nguon cho len, trong do ko it nhat mot nguon doi lap, do la bai ko no luk kan bang" },
      { speaker: "Học viên", vietnamese: "Còn báo mạng xã hội thì sao ạ? Mỗi ngày tôi thấy hàng chục bài trên Facebook, không biết tin gì.", english: "What about social media news? Every day I see dozens of posts on Facebook and don't know what to believe.", pronunciation: "kon bao mang xa hoi thi sao a, moi ngay toy thay hang chuk bai tren facebook, khong biet tin zi" },
      { speaker: "Nhà báo", vietnamese: "Với mạng xã hội, có hai nguyên tắc. Một: bài viết không ghi tên tác giả thật — đừng đọc. Hai: bài viết chỉ có một nguồn mà nguồn đó là 'một người giấu tên' — đừng tin. Và quan trọng nhất: nếu một tin làm em tức giận ngay lập tức, hãy dừng lại. Đó là lúc em dễ bị dắt mũi nhất.", english: "For social media, two rules. One: no real author name — don't read it. Two: only one source and that source is 'an anonymous person' — don't trust it. And most importantly: if a story makes you angry immediately, stop. That is when you are easiest to manipulate.", pronunciation: "voi mang xa hoi, ko hai nguyen tak, mot bai viet khong ghi ten tak za that, dung dok, hai bai viet chi ko mot nguon ma nguon do la mot nguoi zau ten, dung tin, va kwan trong nhat, new mot tin lam em tuk zan ngay lap tuk, hay dung lai, do la luk em de bi zat mui nhat" }
    ],
    cultural_note: "TRUYỀN THÔNG VIỆT NAM — BA HỆ THỐNG:\n\n(1) BÁO CHÍ NHÀ NƯỚC: Nhân Dân (cơ quan ngôn luận của Đảng), Tuổi Trẻ (phổ biến miền Nam), Thanh Niên, VietnamNet, VnExpress. Có quy định về 'tôn chỉ mục đích' và chịu sự quản lý của Bộ Thông Tin và Truyền Thông.\n\n(2) BÁO CHÍ ĐỘC LẬP: Một số tờ báo online hoạt động với không gian hẹp hơn. Ngôn ngữ thường dùng lối nói gián tiếp (dog whistle) để truyền tải thông điệp.\n\n(3) TRUYỀN THÔNG XÃ HỘI: Facebook, Zalo, TikTok — nguồn tin chính của phần lớn người Việt dưới 40 tuổi. Thiếu kiểm chứng, dễ lan truyền tin giả.\n\n(4) TỪ VỰNG FRAMING TRONG TIẾNG VIỆT:\n- 'biểu tình' vs 'tụ tập đông người gây rối'\n- 'yêu cầu' vs 'đòi hỏi' vs 'kiến nghị'\n- 'cải cách' vs 'xóa bỏ' vs 'đổi mới'\n- 'phần tử xấu' / 'thế lực thù địch' vs 'người bất đồng chính kiến'\n- 'dư luận' vs 'tin đồn'\n\n(5) KỸ THUẬT ĐỌC C2: Khi đọc bất kỳ bài báo tiếng Việt nào, hãy tìm câu trả lời cho ba câu hỏi: (a) Tờ báo này của ai? (b) Những từ nào trong bài mang tính phán xét chứ không mô tả? (c) Ai không được trích dẫn?",
    tip: "LUYỆN TẬP: Chọn một sự kiện trong tuần. Đọc ba bài về cùng sự kiện đó từ ba nguồn khác nhau (ví dụ: Tuổi Trẻ, BBC Tiếng Việt, và một bài Facebook). Gạch ra tất cả các từ mang tính phán xét. So sánh xem mỗi nguồn 'đóng khung' sự kiện khác nhau thế nào."
  },
  {
    id: 489,
    level: "C2",
    title_en: "Diplomatic Language and Strategic Indirectness",
    subtitle: "Ngôn ngữ ngoại giao và nghệ thuật nói giảm nói tránh chiến lược — khi 'chưa đồng ý' có nghĩa là 'phản đối'.",
    intro: "Trong tiếng Việt, nói thẳng không phải lúc nào cũng là nói thật — đôi khi nói thẳng là nói mất lòng, và nói mất lòng là mất tất cả. Ở bậc C2, bạn cần làm chủ nghệ thuật nói giảm nói tránh chiến lược (strategic indirectness): biết cách bày tỏ sự phản đối mà không khiến đối phương mất mặt, biết cách từ chối mà vẫn để ngỏ cánh cửa, và quan trọng nhất — biết cách đọc những gì người khác không nói ra.",
    phrases: [
      { english: "Instead of saying 'I disagree,' say: 'That is an interesting approach. Have we considered the possibility that...?' The word 'interesting' in Vietnamese diplomacy means 'I have serious reservations.'", vietnamese: "Thay vì nói 'tôi không đồng ý', hãy nói: 'Đó là một hướng tiếp cận thú vị. Mình đã cân nhắc khả năng là... chưa ạ?' Từ 'thú vị' trong ngoại giao tiếng Việt có nghĩa là 'tôi có bảo lưu nghiêm trọng'.", pronunciation: "thay vi noi toy khong dong i, hay noi do la mot huong tiep kan thu vi, minh da kan nhak kha nang la... chua a, tu thu vi trong ngoai ziao tieng viet ko ngia la toy ko bao luu ngiem trong", context: "Dùng để dạy từ 'thú vị' như một công cụ phản đối lịch sự." },
      { english: "'We need more time to study this' in a government meeting means 'We are not going to approve this, but we will not say so directly because you are an important partner.'", vietnamese: "'Chúng tôi cần thêm thời gian nghiên cứu' trong cuộc họp chính phủ có nghĩa là 'Chúng tôi sẽ không phê duyệt cái này, nhưng không nói thẳng vì anh chị là đối tác quan trọng'.", pronunciation: "chung toy kun them thoi zan nghien kuu trong kuok hop chinh fu ko ngia la chung toy se khong fe duyet kai nay, nhung khong noi thang vi anh chi la doi tak kwan trong", context: "Dùng để giải mã ngôn ngữ ngoại giao Việt Nam." },
      { english: "The most dangerous phrase in a Vietnamese meeting: 'Để em xem lại đã.' Literally 'Let me review it first.' Actually means 'I am never going to do this, but I will not say no to your face.'", vietnamese: "Câu nguy hiểm nhất trong họp hành tiếng Việt: 'Để em xem lại đã.' Nghĩa đen là 'cho em xem xét lại'. Nghĩa thật là 'em sẽ không bao giờ làm cái này, nhưng em không nói không trước mặt anh chị'.", pronunciation: "kau nguy hiem nhat trong hop hanh tieng viet, de em xem lai da, ngia den la cho em xem xet lai, ngia that la em se khong bao zio lam kai nay, nhung em khong noi khong chuok mat anh chi", context: "Dùng để dạy cách nhận biết lời từ chối gián tiếp." },
      { english: "When a senior leader says 'Đồng ý về nguyên tắc' — agreed in principle — they have just rejected your specific proposal while preserving the relationship.", vietnamese: "Khi lãnh đạo cấp trên nói 'Đồng ý về nguyên tắc' — họ vừa từ chối đề xuất cụ thể của bạn, trong khi vẫn giữ gìn quan hệ.", pronunciation: "khi lanh dao kap tren noi dong i ve nguyen tak, ho vua tu choi de xuat ku the kua ban, trong khi van ziu zin kwan he", context: "Dùng khi phân tích 'đồng ý về nguyên tắc' — một công thức từ chối kinh điển." },
      { english: "The hierarchy of diplomatic rejection in Vietnamese, from softest to hardest: 'Để mình nghiên cứu thêm' → 'Có lẽ chưa phải lúc' → 'Còn nhiều ý kiến khác nhau' → 'Chưa đồng thuận' → 'Không khả thi'. Never say 'Không' alone.", vietnamese: "Thang bậc từ chối ngoại giao trong tiếng Việt, từ nhẹ nhất đến mạnh nhất: 'Để mình nghiên cứu thêm' → 'Có lẽ chưa phải lúc' → 'Còn nhiều ý kiến khác nhau' → 'Chưa đồng thuận' → 'Không khả thi'. Tuyệt đối không nói 'Không' một mình.", pronunciation: "thang bak tu choi ngoai ziao trong tieng viet, tu nhe nhat den manh nhat, de minh nghien kuu them, ko le chua fai luk, kon nhieu i kien khak nhau, chua dong thuan, khong kha thi, tuyet doi khong noi khong mot minh", context: "Dùng làm bảng tham khảo cho học viên." },
      { english: "In multilateral settings, the Vietnamese delegation's silence is not absence — it is a position. Understanding when to stay silent is as important as knowing what to say.", vietnamese: "Trong họp đa phương, sự im lặng của phái đoàn Việt Nam không phải là vắng mặt — đó là một lập trường. Hiểu khi nào nên im lặng cũng quan trọng như biết nói gì.", pronunciation: "trong hop da fuong, su im lang kua fai doan viet nam khong fai la vang mat, do la mot lap chuong, hieu khi nao nen im lang kung kwan trong nhu biet noi zi", context: "Dùng để dạy về vai trò của im lặng trong ngoại giao." }
    ],
    dialogue: [
      { speaker: "Đối tác nước ngoài", vietnamese: "Cảm ơn anh chị đã trình bày. Vậy phía Việt Nam có đồng ý với đề xuất này không ạ?", english: "Thank you for the presentation. So does the Vietnamese side agree with this proposal?", pronunciation: "kam on anh chi da trinh bay, vay fia viet nam ko dong i voi de xuat nay khong a" },
      { speaker: "Trưởng đoàn Việt Nam", vietnamese: "Cảm ơn anh. Đề xuất của anh có nhiều điểm rất đáng quan tâm. Phía chúng tôi sẽ nghiên cứu kỹ và có ý kiến chính thức bằng văn bản trong thời gian sớm nhất.", english: "Thank you. Your proposal has many points of real interest. Our side will study it carefully and provide an official response in writing at the earliest opportunity.", pronunciation: "kam on anh, de xuat kua anh ko nhieu diem rat dang kwan tam, fia chung toy se nghien kuu ki va ko i kien chinh thuc bang van ban trong thoi zan som nhat" },
      { speaker: "Đối tác nước ngoài", vietnamese: "(nói với trợ lý sau cuộc họp) Họ nói vậy là có nghĩa là đồng ý hay không đồng ý?", english: "(to their assistant after the meeting) Does that mean they agreed or disagreed?", pronunciation: "noi voi cho li sau kuok hop, ho noi vay la ko ngia la dong i hay khong dong i" },
      { speaker: "Trợ lý (người Việt)", vietnamese: "Dạ thưa sếp, trong ngôn ngữ ngoại giao Việt Nam, 'nghiên cứu kỹ và trả lời bằng văn bản' có nghĩa là họ chưa đồng ý. Nhưng họ cũng không từ chối dứt khoát — họ để ngỏ. Nếu mình điều chỉnh đề xuất, cửa vẫn mở.", english: "Sir, in Vietnamese diplomatic language, 'study carefully and respond in writing' means they have not agreed. But they also have not refused outright — they left the door open. If we adjust the proposal, the door is still open.", pronunciation: "da thua sep, trong ngon ngu ngoai ziao viet nam, nghien kuu ki va tra loi bang van ban ko ngia la ho chua dong i, nhung ho kung khong tu choi dut khoat, ho de ngo, new minh dieu chinh de xuat, kua van mo" }
    ],
    cultural_note: "NGOẠI GIAO VIỆT NAM — ĐẶC TRƯNG:\n\n(1) NGUYÊN TẮC 'GIỮ THỂ DIỆN': Trong văn hóa Việt Nam, làm người khác mất mặt (mất thể diện) là một trong những điều tối kỵ. Vì vậy, từ chối trực tiếp hiếm khi xảy ra trong môi trường chuyên nghiệp. Thay vào đó, người Việt dùng hệ thống tín hiệu gián tiếp.\n\n(2) BẢNG GIẢI MÃ NGOẠI GIAO:\n- 'Rất đáng quan tâm' = Tôi ghi nhận, nhưng chưa cam kết gì.\n- 'Sẽ nghiên cứu thêm' = Chưa đồng ý, cần thời gian.\n- 'Sẽ có ý kiến chính thức bằng văn bản' = Quyết định sẽ được đưa ra sau khi tham khảo cấp trên.\n- 'Còn có ý kiến khác nhau' = Nội bộ đang bất đồng.\n- 'Chưa phải lúc thích hợp' = Từ chối lịch sự.\n\n(3) VAI TRÒ CỦA CẤP TRÊN: Trong hệ thống Việt Nam, người đàm phán thường không có thẩm quyền quyết định cuối cùng. 'Xin ý kiến cấp trên' không phải là thoái thác — đó là thực tế tổ chức.\n\n(4) IM LẶNG CHIẾN LƯỢC: Im lặng trong họp hành Việt Nam có thể mang nhiều nghĩa: (a) Tôi đồng ý nhưng không cần nói thêm, (b) Tôi không đồng ý nhưng không muốn nói thẳng, (c) Tôi chưa có đủ thông tin để phát biểu, (d) Tôi đang chờ người có thẩm quyền cao hơn phát biểu trước.",
    tip: "LUYỆN TẬP: Xem một cuộc họp báo của Bộ Ngoại Giao Việt Nam trên VTV. Ghi lại tất cả những câu trả lời của người phát ngôn. Với mỗi câu, thử dịch ra 'nghĩa thật'. So sánh bản dịch của bạn với cách truyền thông quốc tế tường thuật cùng sự kiện đó."
  },
  {
    id: 490,
    level: "C2",
    title_en: "Persuasion Theory and Abstract Argumentation",
    subtitle: "Lý thuyết thuyết phục và lập luận trừu tượng — khi bạn không thể nói 'tôi nghĩ', bạn phải nói 'lý do là'.",
    intro: "Ở bậc C2, bạn không còn nói 'theo tôi' hay 'ý kiến của tôi là' nữa. Thay vào đó, bạn xây dựng lập luận trên nền tảng logic và bằng chứng. Tiếng Việt có một kho từ Hán Việt đồ sộ dành riêng cho lập luận trừu tượng: 'luận điểm', 'luận cứ', 'phản biện', 'suy luận', 'diễn dịch', 'quy nạp'. Biết dùng những từ này đúng chỗ là dấu hiệu của người nói tiếng Việt bậc thầy.",
    phrases: [
      { english: "'I think this policy is wrong' is weak. Instead: 'This policy rests on an assumption that has not been verified — namely, that X leads to Y. The evidence actually suggests the opposite.'", vietnamese: "'Tôi nghĩ chính sách này sai' là yếu. Thay vào đó: 'Chính sách này dựa trên một giả định chưa được kiểm chứng — đó là X dẫn đến Y. Bằng chứng thực tế cho thấy điều ngược lại'.", pronunciation: "toy nghi chinh sach nay sai la yeu, thay vao do, chinh sach nay dua tren mot za dinh chua duoc kiem chung, do la X dan den Y, bang chung thuc te cho thay dieu nguoc lai", context: "Dùng khi dạy cách thay thế 'tôi nghĩ' bằng phân tích logic." },
      { english: "A strong argument in Vietnamese academic writing follows this structure: claim (luận điểm) → evidence (luận cứ) → reasoning (lập luận) → counter-argument consideration (phản biện) → conclusion with limits (kết luận kèm giới hạn).", vietnamese: "Một lập luận mạnh trong văn học thuật tiếng Việt theo cấu trúc: luận điểm → luận cứ → lập luận → phản biện → kết luận kèm giới hạn. Thiếu phản biện, lập luận chưa trưởng thành.", pronunciation: "mot lap luan manh trong van hok thuat tieng viet theo kau truk, luan diem, luan ku, lap luan, fan bien, ket luan kem zoi han, thieu fan bien, lap luan chua chuong thanh", context: "Dùng làm cấu trúc chuẩn cho sinh viên viết luận." },
      { english: "Abstract reasoning requires you to step back from the specific case and ask: what is the general principle at work here? If this case is an instance of a broader pattern, what does that pattern tell us?", vietnamese: "Lập luận trừu tượng đòi bạn lùi lại khỏi trường hợp cụ thể và tự hỏi: nguyên tắc tổng quát nào đang vận hành ở đây? Nếu trường hợp này là một biểu hiện của một khuôn mẫu rộng hơn, khuôn mẫu đó nói với ta điều gì?", pronunciation: "lap luan chuu tuong doi ban lui lai khoi chuong hop ku the va tu hoi, nguyen tak tong kwat nao dang van hanh o day, new chuong hop nay la mot bieu hien kua mot khuon mau rong hon, khuon mau do noi voi ta dieu zi", context: "Dùng để dạy cách chuyển từ tư duy cụ thể sang tư duy trừu tượng." },
      { english: "In Vietnamese intellectual tradition, citing a respected authority carries weight. But C2-level argumentation must go beyond 'Professor X said so' — you must show WHY the authority's reasoning is sound, not just THAT they said it.", vietnamese: "Trong truyền thống tri thức Việt Nam, trích dẫn học giả có uy tín mang trọng lượng. Nhưng lập luận bậc C2 phải vượt qua 'Giáo sư X nói thế' — bạn phải chỉ ra TẠI SAO lập luận của học giả đó vững, chứ không chỉ là HỌ đã nói thế.", pronunciation: "trong chuyen thong chi thuc viet nam, trich dan hok za ko uy tin mang trong luong, nhung lap luan bak C2 fai vuot kwa zao su X noi the, ban fai chi ra tai sao lap luan kua hok za do vung, chu khong chi la ho da noi the", context: "Dùng để nâng cao chất lượng trích dẫn học thuật." },
      { english: "Concession is the mark of a mature arguer: 'I acknowledge that my position has a weakness on point X. However, this weakness does not undermine the core argument because...' This shows intellectual honesty and strengthens your credibility.", vietnamese: "Nhượng bộ là dấu hiệu của người lập luận trưởng thành: 'Tôi thừa nhận lập trường của mình có điểm yếu ở khía cạnh X. Tuy nhiên, điểm yếu này không làm suy yếu luận điểm cốt lõi vì...' Điều này thể hiện sự trung thực trí tuệ và củng cố độ tin cậy của bạn.", pronunciation: "nhuong bo la zou hieu kua nguoi lap luan chuong thanh, toy thua nhan lap chuong kua minh ko diem yeu o khia kanh X, tuy nhien diem yeu nay khong lam suy yeu luan diem kot loi vi, dieu nay the hien su trung thuc chi tue va kung ko do tin kay kua ban", context: "Dùng để dạy kỹ thuật nhượng bộ chiến lược." },
      { english: "When constructing an abstract argument in Vietnamese, use these connectors: 'một mặt... mặt khác' (on one hand... on the other), 'tuy nhiên' (however), 'điều này dẫn đến' (this leads to), 'giả định rằng' (assuming that), 'nói cách khác' (in other words).", vietnamese: "Khi xây dựng lập luận trừu tượng trong tiếng Việt, dùng các từ nối này: 'một mặt... mặt khác', 'tuy nhiên', 'điều này dẫn đến', 'giả định rằng', 'nói cách khác', 'điều này hàm ý rằng'. Đây là bộ khung của tư duy logic.", pronunciation: "khi xay dung lap luan chuu tuong trong tieng viet, dung kak tu noi nay, mot mat... mat khak, tuy nhien, dieu nay dan den, za dinh rang, noi kach khak, dieu nay ham i rang, day la bo khung kua tu duy logic", context: "Dùng làm bảng tham khảo từ nối lập luận." }
    ],
    dialogue: [
      { speaker: "Sinh viên cao học", vietnamese: "Thưa thầy, trong bài luận của em, em có nên viết 'theo quan điểm của em' không ạ?", english: "Professor, in my essay, should I write 'in my opinion'?", pronunciation: "thua thay, trong bai luan kua em, em ko nen viet theo kwan diem kua em khong a" },
      { speaker: "Giáo sư", vietnamese: "Tuyệt đối không. 'Theo quan điểm của em' là cách viết của học sinh cấp hai. Ở bậc cao học, em viết: 'Luận điểm này dựa trên ba luận cứ sau. Thứ nhất... Thứ hai... Thứ ba...' Không ai cần biết đó là quan điểm của em. Họ cần biết lập luận của em có đứng vững không.", english: "Absolutely not. 'In my opinion' is middle-school writing. At graduate level, you write: 'This argument rests on three pieces of evidence. First... Second... Third...' Nobody needs to know it is your opinion. They need to know whether your reasoning holds up.", pronunciation: "tuyet doi khong, theo kwan diem kua em la kach viet kua hok sinh kap hai, o bak kao hok, em viet, luan diem nay dua tren ba luan ku sau, thu nhat, thu hai, thu ba, khong ai kun biet do la kwan diem kua em, ho kun biet lap luan kua em ko dung vung khong" },
      { speaker: "Sinh viên cao học", vietnamese: "Dạ, nhưng nếu em muốn đưa ra một ý mới, mà chưa có bằng chứng mạnh, thì nên viết thế nào?", english: "But what if I want to propose a new idea, and I don't yet have strong evidence?", pronunciation: "da, nhung new em muon dua ra mot i moi, ma chua ko bang chung manh, thi nen viet the nao" },
      { speaker: "Giáo sư", vietnamese: "Lúc đó em dùng ngôn ngữ giả định: 'Có thể đặt ra giả thuyết rằng... Tuy nhiên, giả thuyết này cần được kiểm chứng thêm qua...' Em không che giấu sự yếu của bằng chứng — em công khai nó. Sự trung thực đó làm tăng độ tin cậy của em.", english: "Then use hypothetical language: 'One might hypothesize that... However, this hypothesis requires further verification through...' Don't hide the weakness of your evidence — declare it openly. That honesty increases your credibility.", pronunciation: "luk do em dung ngon ngu za dinh, ko the dat ra za thuyet rang, tuy nhien za thuyet nay kun duoc kiem chung them kwa, em khong che zau su yeu kua bang chung, em kong khai no, su trung thuc do lam tang do tin kay kua em" }
    ],
    cultural_note: "LẬP LUẬN TRONG TIẾNG VIỆT — ĐẶC TRƯNG:\n\n(1) TỪ HÁN VIỆT TRONG LẬP LUẬN: Tiếng Việt có hai lớp từ vựng — từ thuần Việt (nôm na, đời thường) và từ Hán Việt (trang trọng, trí tuệ). Ở bậc C2, bạn phải dùng từ Hán Việt đúng chỗ. Ví dụ: 'ý kiến' (thuần Việt, bình dân) → 'quan điểm' (Hán Việt, hơi trang trọng) → 'lập trường' (Hán Việt, rất trang trọng) → 'chính kiến' (Hán Việt, bậc cao nhất).\n\n(2) CẤU TRÚC LẬP LUẬN TRUYỀN THỐNG: Văn nghị luận Việt Nam chịu ảnh hưởng từ Trung Hoa (khởi - thừa - chuyển - hợp) và Pháp (these - antithèse - synthèse). Sinh viên Việt thường kết hợp cả hai.\n\n(3) TÔN TRỌNG THẨM QUYỀN: Trong lập luận học thuật Việt Nam, trích dẫn người đi trước (tiền bối) là bắt buộc, không phải tùy chọn. Tuy nhiên, trích dẫn phải đi kèm phân tích — không phải 'treo tên'.\n\n(4) TỪ NỐI LẬP LUẬN:\n- Bổ sung: hơn nữa, ngoài ra, thêm vào đó, không những thế\n- Đối lập: tuy nhiên, mặc dù vậy, trái lại, ngược lại\n- Nhân quả: do đó, vì vậy, bởi thế, hệ quả là\n- Giả định: giả sử rằng, nếu như, trong trường hợp\n- Kết luận: tóm lại, nhìn chung, tựu trung, nói cách khác",
    tip: "LUYỆN TẬP: Viết một đoạn 300 chữ bảo vệ một quan điểm gây tranh cãi (ví dụ: 'Có nên bỏ thi tốt nghiệp THPT?'). Cấu trúc: (1) Nêu luận điểm, (2) Đưa ba luận cứ, (3) Phản biện một luận cứ yếu nhất của chính mình, (4) Kết luận kèm giới hạn. Sau đó, gạch dưới tất cả từ Hán Việt bạn đã dùng. Đếm xem tỷ lệ từ Hán Việt có vượt quá 40% không — nếu có, bài viết quá nặng, cần thêm từ thuần Việt để tự nhiên hơn."
  },
  {
    id: 491,
    level: "C2",
    title_en: "Oral Defense and Conceptual Argumentation",
    subtitle: "Bảo vệ luận điểm và tranh luận khái niệm — đứng vững trước chất vấn mà không phòng thủ.",
    intro: "Bảo vệ luận án hay thuyết trình trước hội đồng là đỉnh cao của tiếng Việt C2. Bạn không chỉ trình bày — bạn bị chất vấn, bị phản biện, bị yêu cầu bảo vệ từng luận điểm. Người Việt gọi đây là 'phản biện kín' — chất vấn toàn diện để kiểm tra xem luận điểm có thực sự vững không. Nghệ thuật ở đây là: trả lời câu hỏi mà không tỏ ra phòng thủ, thừa nhận điểm yếu mà không đánh mất uy tín, và giữ được sự điềm tĩnh trí tuệ khi bị tấn công học thuật.",
    phrases: [
      { english: "When hit with a tough question, start by thanking the questioner. 'Cảm ơn câu hỏi rất sắc sảo của thầy.' This buys you 3 seconds to think and signals intellectual confidence — you are not afraid of challenges.", vietnamese: "Khi bị hỏi câu khó, hãy bắt đầu bằng cảm ơn người hỏi. 'Cảm ơn câu hỏi rất sắc sảo của thầy.' Câu này mua cho bạn ba giây để suy nghĩ, và phát tín hiệu tự tin trí tuệ — bạn không sợ bị thách thức.", pronunciation: "khi bi hoi kau kho, hay bat dau bang kam on nguoi hoi, kam on kau hoi rat sak sao kua thay, kau nay mua cho ban ba ziay de suy nghi, va fat tin hieu tu tin chi tue, ban khong so bi thach thuk", context: "Dùng để dạy kỹ thuật mở đầu khi bị chất vấn khó." },
      { english: "Never say 'That is a good question but...' The word 'but' cancels the compliment. Instead: 'That question goes to the heart of the matter. Let me address it directly.' Then answer — no 'but' needed.", vietnamese: "Không bao giờ nói 'Đó là câu hỏi hay nhưng...' Từ 'nhưng' hủy hoại lời khen. Thay vào đó: 'Câu hỏi này đi thẳng vào trọng tâm vấn đề. Xin phép trả lời trực tiếp.' Rồi trả lời — không cần 'nhưng'.", pronunciation: "khong bao zio noi do la kau hoi hay nhung, tu nhung huy hoai loi khen, thay vao do, kau hoi nay di thang vao trong tam van de, xin fep tra loi truc tiep, roi tra loi, khong kun nhung", context: "Dùng để sửa lỗi phổ biến khi trả lời chất vấn." },
      { english: "When you don't know the answer: 'Đây là một câu hỏi rất đáng nghiên cứu thêm. Trong phạm vi đề tài này, tôi chưa có đủ dữ liệu để trả lời dứt khoát, nhưng hướng suy nghĩ ban đầu của tôi là...' This is honest, shows limits, and keeps authority.", vietnamese: "Khi bạn không biết câu trả lời: 'Đây là một câu hỏi rất đáng nghiên cứu thêm. Trong phạm vi đề tài này, tôi chưa có đủ dữ liệu để trả lời dứt khoát, nhưng hướng suy nghĩ ban đầu của tôi là...' Cách này trung thực, chỉ ra giới hạn, và vẫn giữ được tư thế.", pronunciation: "khi ban khong biet kau tra loi, day la mot kau hoi rat dang nghien kuu them, trong fam vi de tai nay, toy chua ko du du lieu de tra loi dut khoat, nhung huong suy nghi ban dau kua toy la, kach nay trung thuc, chi ra zoi han, va van ziu duoc tu the", context: "Dùng khi không biết câu trả lời — kỹ năng quan trọng nhất trong bảo vệ." },
      { english: "The 'strategic concession': 'Tôi đồng ý với thầy về điểm này — dữ liệu của tôi ở đây chưa đủ mạnh. Tuy nhiên, tôi cho rằng hướng lập luận chính vẫn đứng vững vì lý do X và Y.' You win by losing the small point to save the big one.", vietnamese: "'Nhượng bộ chiến lược': 'Tôi đồng ý với thầy về điểm này — dữ liệu của tôi ở đây chưa đủ mạnh. Tuy nhiên, tôi cho rằng hướng lập luận chính vẫn đứng vững vì lý do X và Y.' Bạn thắng bằng cách thua điểm nhỏ để giữ điểm lớn.", pronunciation: "nhuong bo chien luoc, toy dong i voi thay ve diem nay, du lieu kua toy o day chua du manh, tuy nhien toy cho rang huong lap luan chinh van dung vung vi li do X va Y, ban thang bang kach thua diem nho de ziu diem lon", context: "Dùng để dạy kỹ thuật nhượng bộ chiến lược trong bảo vệ." },
      { english: "In Vietnamese academic settings, never interrupt the questioner, even if you know where they are going. Let them finish. Then pause. Count to two. Then respond. The pause signals thoughtfulness, not hesitation.", vietnamese: "Trong môi trường học thuật Việt Nam, không bao giờ ngắt lời người hỏi — dù bạn biết họ định nói gì. Hãy để họ nói hết. Rồi dừng lại. Đếm đến hai. Rồi mới trả lời. Khoảng dừng phát tín hiệu suy nghĩ cẩn trọng, không phải do dự.", pronunciation: "trong moi chuong hok thuat viet nam, khong bao zio ngat loi nguoi hoi, zu ban biet ho dinh noi zi, hay de ho noi het, roi dung lai, dem den hai, roi moi tra loi, khwang dung fat tin hieu suy nghi kan trong, khong fai do zu", context: "Dùng để dạy nghi thức hội đồng học thuật Việt Nam." },
      { english: "Closing your defense strongly: 'Kính thưa hội đồng, tôi tin rằng những phân tích trên đây đã cho thấy luận điểm của tôi có cơ sở. Tôi xin trân trọng lắng nghe mọi ý kiến đóng góp và sẵn sàng tiếp thu, chỉnh sửa.' This shows confidence plus openness.", vietnamese: "Kết thúc bảo vệ mạnh mẽ: 'Kính thưa hội đồng, tôi tin rằng những phân tích trên đây đã cho thấy luận điểm của tôi có cơ sở. Tôi xin trân trọng lắng nghe mọi ý kiến đóng góp và sẵn sàng tiếp thu, chỉnh sửa.' Vừa tự tin, vừa mở lòng.", pronunciation: "kinh thua hoi dong, toy tin rang nhung fan tich tren day da cho thay luan diem kua toy ko ko so, toy xin chan trong lang nghe moi i kien dong gop va san sang tiep thu, chinh sua, vua tu tin, vua mo long", context: "Dùng làm mẫu câu kết thúc bảo vệ." }
    ],
    dialogue: [
      { speaker: "Ủy viên hội đồng", vietnamese: "Thưa anh, tôi thấy ở chương ba, anh khẳng định X dẫn đến Y. Nhưng mẫu khảo sát của anh chỉ có 50 người, và tất cả đều ở Hà Nội. Anh dựa vào đâu để khái quát hóa cho toàn quốc?", english: "In chapter three, you assert that X leads to Y. But your survey sample only has 50 people, all in Hanoi. On what basis do you generalize to the entire country?", pronunciation: "thua anh, toy thay o chuong ba, anh khang dinh X dan den Y, nhung mau khao sat kua anh chi ko nam muoi nguoi, va tat ka deu o ha noi, anh dua vao dau de khai kwat hoa cho toan kuok" },
      { speaker: "Nghiên cứu sinh", vietnamese: "Dạ, em cảm ơn câu hỏi rất xác đáng của thầy. Em xin được làm rõ: khẳng định của em không phải là khái quát hóa thống kê cho toàn quốc. Em chỉ khẳng định mối liên hệ X-Y tồn tại trong bối cảnh đô thị phía Bắc. Đây là một giới hạn mà em đã nêu ở phần phương pháp. Hướng nghiên cứu tiếp theo sẽ mở rộng vào miền Trung và miền Nam để kiểm tra tính bền vững của mối liên hệ này.", english: "Thank you for this very pertinent question. Let me clarify: my assertion is not a statistical generalization for the entire country. I only assert that the X-Y relationship exists in the northern urban context. This is a limitation I noted in the methodology section. The next research direction will extend to central and southern regions to test the robustness of this relationship.", pronunciation: "da em kam on kau hoi rat sak dang kua thay, em xin duoc lam ro, khang dinh kua em khong fai la khai kwat hoa thong ke cho toan kuok, em chi khang dinh moi lien he X-Y ton tai trong boi kanh do thi fia bak, day la mot zoi han ma em da neu o fun fuong fap, huong nghien kuu tiep theo se mo rong vao mien trung va mien nam de kiem tra tinh ben vung kua moi lien he nay" },
      { speaker: "Ủy viên hội đồng", vietnamese: "Vậy nếu sau này mở rộng khảo sát mà mối liên hệ không còn, thì luận điểm của anh có sụp đổ không?", english: "So if future research expands the survey and the relationship no longer holds, would your argument collapse?", pronunciation: "vay new sau nay mo rong khao sat ma moi lien he khong kon, thi luan diem kua anh ko sup do khong" },
      { speaker: "Nghiên cứu sinh", vietnamese: "Dạ, nếu mối liên hệ không còn ở khu vực khác, thì điều đó không làm sụp đổ luận điểm — mà làm cho nó trở nên thú vị hơn. Vì nó cho thấy X-Y không phải là quy luật phổ quát, mà phụ thuộc vào bối cảnh văn hóa vùng miền. Đó sẽ là một phát hiện còn giá trị hơn là chứng minh X-Y đúng ở mọi nơi.", english: "If the relationship does not hold in other regions, that would not collapse the argument — it would make it more interesting. Because it would show that X-Y is not a universal law, but depends on regional cultural context. That would be an even more valuable finding than proving X-Y holds everywhere.", pronunciation: "da new moi lien he khong kon o khu vuk khak, thi dieu do khong lam sup do luan diem, ma lam cho no cho nen thu vi hon, vi no cho thay X-Y khong fai la kwy luat fo kwat, ma fu thuok vao boi kanh van hoa vung mien, do se la mot fat hien kon za chi hon la chung minh X-Y dung o moi noi" }
    ],
    cultural_note: "BẢO VỆ HỌC THUẬT Ở VIỆT NAM:\n\n(1) NGHI THỨC: Hội đồng thường có 5-7 thành viên, trong đó có chủ tịch hội đồng, thư ký, và các phản biện. Buổi bảo vệ mở đầu bằng lời khai mạc của chủ tịch, sau đó nghiên cứu sinh trình bày (15-20 phút), rồi đến phần chất vấn (45-60 phút).\n\n(2) ĐẠI TỪ NHÂN XƯNG: Trước hội đồng, nghiên cứu sinh luôn xưng 'em' (không bao giờ xưng 'tôi'), và gọi các thành viên là 'thầy/cô'. Đây là quy tắc bất di bất dịch, ngay cả khi bạn đã 40 tuổi và thành viên hội đồng trẻ hơn.\n\n(3) NGHỆ THUẬT TRẢ LỜI:\n- Luôn bắt đầu bằng 'Cảm ơn câu hỏi của thầy/cô'\n- Nếu câu hỏi dài, ghi nhanh các ý chính để không bỏ sót\n- Trả lời từng ý một: 'Về ý thứ nhất... Về ý thứ hai...'\n- Không bao giờ nói 'Thầy/cô hỏi sai rồi'\n- Nếu ý kiến phản biện đúng, nói: 'Em xin tiếp thu ý kiến của thầy/cô và sẽ chỉnh sửa trong bản cuối cùng'\n\n(4) TRANG PHỤC: Nam mặc complet, nữ mặc áo dài hoặc vest công sở. Trang phục thể hiện sự tôn trọng với hội đồng.\n\n(5) ĐIỀU TỐI KỴ: (a) Tranh cãi với hội đồng, (b) Đổ lỗi cho người hướng dẫn, (c) Nói 'vấn đề này không quan trọng' — mọi câu hỏi đều quan trọng với hội đồng.",
    tip: "LUYỆN TẬP: Tự quay video mình trả lời ba câu hỏi khó nhất về đề tài của bạn. Xem lại và chấm điểm: (1) Có bắt đầu bằng cảm ơn không? (2) Có trả lời trực tiếp không — hay né tránh? (3) Có thừa nhận giới hạn không? (4) Có dừng lại trước khi trả lời không — hay trả lời ngay lập tức? Làm lại đến khi đạt cả bốn tiêu chí."
  }
];

export default lessons;
