/**
 * AUTO-GENERATED: Do not edit manually
 * Generated by: scripts/generate-room-registry.js
 * Run: node scripts/generate-room-registry.js
 */
import { RoomData } from "@/lib/roomData";

export const roomDataMap: Record<string, RoomData> = {
  "addiction-support-free": {
      "id": "addiction-support-free",
      "nameEn": "Addiction Support",
      "nameVi": "Hỗ Trợ Cai Nghiện",
      "tier": "free",
      "hasData": true
  },
  "addiction-support-vip3": {
      "id": "addiction-support-vip3",
      "nameEn": "Addiction Support",
      "nameVi": "Hỗ Trợ Cai Nghiện",
      "tier": "vip3",
      "hasData": true
  },
  "adhd-support-free": {
      "id": "adhd-support-free",
      "nameEn": "ADHD Support",
      "nameVi": "Hỗ Trợ Rối Loạn Tăng Động Giảm Chú Ý",
      "tier": "free",
      "hasData": true
  },
  "adhd-support-vip1": {
      "id": "adhd-support-vip1",
      "nameEn": "ADHD Support",
      "nameVi": "Hỗ Trợ Rối Loạn Tăng Động Giảm Chú Ý",
      "tier": "vip1",
      "hasData": true
  },
  "adhd-support-vip2": {
      "id": "adhd-support-vip2",
      "nameEn": "ADHD Support — Advanced",
      "nameVi": "Hỗ Trợ Rối Loạn Tăng Động Giảm Chú Ý — Nâng Cao",
      "tier": "vip2",
      "hasData": true
  },
  "adhd-support-vip3": {
      "id": "adhd-support-vip3",
      "nameEn": "ADHD Support",
      "nameVi": "Hỗ Trợ Rối Loạn Tăng Động Giảm Chú Ý",
      "tier": "vip3",
      "hasData": true
  },
  "ai-free": {
      "id": "ai-free",
      "nameEn": "AI Fundamentals",
      "nameVi": "Nền Tảng AI",
      "tier": "free",
      "hasData": true
  },
  "ai-vip1": {
      "id": "ai-vip1",
      "nameEn": "AI Advanced Techniques VIP1",
      "nameVi": "Kỹ Thuật AI Nâng Cao VIP1",
      "tier": "vip1",
      "hasData": true
  },
  "ai-vip2": {
      "id": "ai-vip2",
      "nameEn": "AI Mastery",
      "nameVi": "Thành Thạo AI",
      "tier": "vip2",
      "hasData": true
  },
  "anxiety-relief-free": {
      "id": "anxiety-relief-free",
      "nameEn": "Anxiety Relief",
      "nameVi": "Giảm Lo Âu",
      "tier": "free",
      "hasData": true
  },
  "anxiety-relief-vip1": {
      "id": "anxiety-relief-vip1",
      "nameEn": "Social Anxiety",
      "nameVi": "Lo Âu Xã Hội",
      "tier": "vip1",
      "hasData": true
  },
  "anxiety-relief-vip2": {
      "id": "anxiety-relief-vip2",
      "nameEn": "Anxiety Relief",
      "nameVi": "Giảm Lo Âu",
      "tier": "vip2",
      "hasData": true
  },
  "anxiety-relief-vip3": {
      "id": "anxiety-relief-vip3",
      "nameEn": "Anxiety Relief",
      "nameVi": "Giảm Lo Âu",
      "tier": "vip3",
      "hasData": true
  },
  "bipolar-support-free": {
      "id": "bipolar-support-free",
      "nameEn": "Bipolar Support",
      "nameVi": "Hỗ Trợ Rối Loạn Lưỡng Cực",
      "tier": "free",
      "hasData": true
  },
  "bipolar-support-vip1": {
      "id": "bipolar-support-vip1",
      "nameEn": "Bipolar Support",
      "nameVi": "Hỗ Trợ Rối Loạn Lưỡng Cực",
      "tier": "vip1",
      "hasData": true
  },
  "bipolar-support-vip2": {
      "id": "bipolar-support-vip2",
      "nameEn": "Bipolar Support",
      "nameVi": "Hỗ Trợ Rối Loạn Lưỡng Cực",
      "tier": "vip2",
      "hasData": true
  },
  "bipolar-support-vip3": {
      "id": "bipolar-support-vip3",
      "nameEn": "Bipolar Support",
      "nameVi": "Hỗ Trợ Rối Loạn Lưỡng Cực",
      "tier": "vip3",
      "hasData": true
  },
  "burnout-recovery-free": {
      "id": "burnout-recovery-free",
      "nameEn": "Burnout Recovery",
      "nameVi": "Phục Hồi Kiệt Sức",
      "tier": "free",
      "hasData": true
  },
  "burnout-recovery-vip2": {
      "id": "burnout-recovery-vip2",
      "nameEn": "Burnout Recovery",
      "nameVi": "Phục Hồi Kiệt Sức",
      "tier": "vip2",
      "hasData": true
  },
  "burnout-recovery-vip3": {
      "id": "burnout-recovery-vip3",
      "nameEn": "Burnout Recovery",
      "nameVi": "Phục Hồi Kiệt Sức",
      "tier": "vip3",
      "hasData": true
  },
  "cognitive-clarity-and-mental-load-vip2": {
      "id": "cognitive-clarity-and-mental-load-vip2",
      "nameEn": "Cognitive Clarity & Mental Load Management — Room 7",
      "nameVi": "Rõ Ràng Tư Duy & Quản Lý Gánh Nặng Tâm Trí — Phòng 7",
      "tier": "vip2",
      "hasData": true
  },
  "confidence-building-vip2": {
      "id": "confidence-building-vip2",
      "nameEn": "Advanced Confidence Building",
      "nameVi": "Xây Dựng Tự Tin Nâng Cao",
      "tier": "vip2",
      "hasData": true
  },
  "corporate-analytics-strategy-vip9": {
      "id": "corporate-analytics-strategy-vip9",
      "nameEn": "Corporate Analytics Strategy",
      "nameVi": "Chiến Lược Phân Tích Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-conflict-navigation-vip9": {
      "id": "corporate-conflict-navigation-vip9",
      "nameEn": "Corporate Conflict Navigation",
      "nameVi": "Điều Hướng Xung Đột Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-crisis-strategy-vip9": {
      "id": "corporate-crisis-strategy-vip9",
      "nameEn": "Corporate Crisis Strategy",
      "nameVi": "Chiến Lược Ứng Phó Khủng Hoảng Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-cross-functional-vip9": {
      "id": "corporate-cross-functional-vip9",
      "nameEn": "Corporate Cross-Functional Collaboration",
      "nameVi": "Hợp Tác Chức Năng Chéo Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-execution-systems-vip9": {
      "id": "corporate-execution-systems-vip9",
      "nameEn": "Corporate Execution Systems",
      "nameVi": "Hệ Thống Thực Thi Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-foresight-vip9": {
      "id": "corporate-foresight-vip9",
      "nameEn": "Corporate Strategic Foresight",
      "nameVi": "Dự Báo Chiến Lược Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-global-strategy-vip9": {
      "id": "corporate-global-strategy-vip9",
      "nameEn": "Corporate Global Strategy",
      "nameVi": "Chiến Lược Toàn Cầu Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-governance-vip9": {
      "id": "corporate-governance-vip9",
      "nameEn": "Corporate Governance",
      "nameVi": "Quản Trị Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-innovation-engines-vip9": {
      "id": "corporate-innovation-engines-vip9",
      "nameEn": "Corporate Innovation Engines",
      "nameVi": "Động Cơ Sáng Tạo Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-leadership-leverage-vip9": {
      "id": "corporate-leadership-leverage-vip9",
      "nameEn": "Corporate Leadership Leverage",
      "nameVi": "Đòn Bẩy Lãnh Đạo Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-long-cycle-planning-vip9": {
      "id": "corporate-long-cycle-planning-vip9",
      "nameEn": "Corporate Long Cycle Planning",
      "nameVi": "Hoạch Định Chu Kỳ Dài Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-negotiation-vip9": {
      "id": "corporate-negotiation-vip9",
      "nameEn": "Corporate Negotiation",
      "nameVi": "Đàm Phán Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-positioning-vip9": {
      "id": "corporate-positioning-vip9",
      "nameEn": "Corporate Positioning",
      "nameVi": "Định Vị Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-resource-allocation-vip9": {
      "id": "corporate-resource-allocation-vip9",
      "nameEn": "Corporate Resource Allocation",
      "nameVi": "Phân Bổ Nguồn Lực Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-scaling-strategy-vip9": {
      "id": "corporate-scaling-strategy-vip9",
      "nameEn": "Corporate Scaling Strategy",
      "nameVi": "Chiến Lược Mở Rộng Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-talent-architecture-vip9": {
      "id": "corporate-talent-architecture-vip9",
      "nameEn": "Corporate Talent Architecture",
      "nameVi": "Kiến Trúc Tài Năng Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-team-culture-vip9": {
      "id": "corporate-team-culture-vip9",
      "nameEn": "Corporate Team Culture",
      "nameVi": "Văn Hóa Đội Nhóm Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "courage-to-begin-vip4": {
      "id": "courage-to-begin-vip4",
      "nameEn": "Courage to Begin",
      "nameVi": "Dám Bắt Đầu",
      "tier": "vip4",
      "hasData": true
  },
  "debate-fallacies-vip2": {
      "id": "debate-fallacies-vip2",
      "nameEn": "Fallacies in Debate — VIP2 Room",
      "nameVi": "Ngụy Biện Trong Tranh Luận — Phòng VIP2",
      "tier": "vip2",
      "hasData": true
  },
  "deep-work-and-focus-vip2": {
      "id": "deep-work-and-focus-vip2",
      "nameEn": "Deep Work & Focus Architecture — Room 3",
      "nameVi": "Làm Việc Sâu & Kiến Trúc Tập Trung — Phòng 3",
      "tier": "vip2",
      "hasData": true
  },
  "depression-support-vip1": {
      "id": "depression-support-vip1",
      "nameEn": "Depression Support",
      "nameVi": "Hỗ Trợ Trầm Cảm",
      "tier": "vip1",
      "hasData": true
  },
  "depression-support-vip3": {
      "id": "depression-support-vip3",
      "nameEn": "Depression Support",
      "nameVi": "Hỗ Trợ Trầm Cảm",
      "tier": "vip3",
      "hasData": true
  },
  "eating-disorder-support-vip1": {
      "id": "eating-disorder-support-vip1",
      "nameEn": "Eating Disorder Support",
      "nameVi": "Hỗ Trợ Rối Loạn Ăn Uống",
      "tier": "vip1",
      "hasData": true
  },
  "eating-disorder-support-vip2": {
      "id": "eating-disorder-support-vip2",
      "nameEn": "Eating Disorder Support",
      "nameVi": "Hỗ Trợ Rối Loạn Ăn Uống",
      "tier": "vip2",
      "hasData": true
  },
  "eating-disorder-support-vip3": {
      "id": "eating-disorder-support-vip3",
      "nameEn": "Eating Disorder Support",
      "nameVi": "Hỗ Trợ Rối Loạn Ăn Uống",
      "tier": "vip3",
      "hasData": true
  },
  "execution-flow-and-momentum-vip2": {
      "id": "execution-flow-and-momentum-vip2",
      "nameEn": "Execution Flow & Momentum — Room 5",
      "nameVi": "Dòng Chảy Thực Thi & Đà Tiến — Phòng 5",
      "tier": "vip2",
      "hasData": true
  },
  "executive-function-mastery-vip2": {
      "id": "executive-function-mastery-vip2",
      "nameEn": "Executive Function Mastery — Room 8",
      "nameVi": "Làm Chủ Chức Năng Điều Hành — Phòng 8",
      "tier": "vip2",
      "hasData": true
  },
  "finding-gods-peace-free": {
      "id": "finding-gods-peace-free",
      "nameEn": "Finding_Gods_Peace_free",
      "nameVi": "Tìm Bình An Của Thiên Chúa",
      "tier": "free",
      "hasData": true
  },
  "frederick-bismarck-comparison-vip9": {
      "id": "frederick-bismarck-comparison-vip9",
      "nameEn": "Frederick the Great vs Otto von Bismarck — Comparative Strategy",
      "nameVi": "Frederick Đại đế và Otto von Bismarck — So Sánh Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "grammar-accelerator-vip1": {
      "id": "grammar-accelerator-vip1",
      "nameEn": "Grammar Accelerator: Fast, Clear, Automatic",
      "nameVi": "Tăng Tốc Ngữ Pháp: Nhanh, Rõ, Tự Động",
      "tier": "vip1",
      "hasData": true
  },
  "grammar-fluency-structure-vip2": {
      "id": "grammar-fluency-structure-vip2",
      "nameEn": "Grammar for Fluency & Structure",
      "nameVi": "Ngữ Pháp Cho Độ Trôi Chảy & Cấu Trúc",
      "tier": "vip2",
      "hasData": true
  },
  "grammar-foundations-free": {
      "id": "grammar-foundations-free",
      "nameEn": "Grammar Foundations",
      "nameVi": "Grammar Foundations",
      "tier": "free",
      "hasData": true
  },
  "grief-healing-free": {
      "id": "grief-healing-free",
      "nameEn": "Grief Healing",
      "nameVi": "Chữa Lành Nỗi Đau Mất Mát",
      "tier": "free",
      "hasData": true
  },
  "interpersonal-intelligence-mastery-vip5": {
      "id": "interpersonal-intelligence-mastery-vip5",
      "nameEn": "Interpersonal Intelligence Mastery",
      "nameVi": "Làm Chủ Trí Tuệ Giao Tiếp",
      "tier": "vip5",
      "hasData": true
  },
  "loneliness-comfort-free": {
      "id": "loneliness-comfort-free",
      "nameEn": "Loneliness Comfort",
      "nameVi": "An Ủi Nỗi Cô Đơn",
      "tier": "free",
      "hasData": true
  },
  "long-term-projects-and-lifetime-systems-vip2": {
      "id": "long-term-projects-and-lifetime-systems-vip2",
      "nameEn": "Long-Term Projects & Lifetime Systems — Room 6",
      "nameVi": "Dự Án Dài Hạn & Hệ Thống Trọn Đời — Phòng 6",
      "tier": "vip2",
      "hasData": true
  },
  "lullabies-for-a-tired-heart-vip3": {
      "id": "lullabies-for-a-tired-heart-vip3",
      "nameEn": "Lullabies For A Tired Heart",
      "nameVi": "Khúc Ru Cho Trái Tim Mệt Mỏi",
      "tier": "vip3",
      "hasData": true
  },
  "machiavelli-grand-strategy-vip9": {
      "id": "machiavelli-grand-strategy-vip9",
      "nameEn": "Machiavelli Grand Strategy",
      "nameVi": "Đại Chiến Lược Machiavelli",
      "tier": "vip9",
      "hasData": true
  },
  "machiavelli-strategy-1-vip9": {
      "id": "machiavelli-strategy-1-vip9",
      "nameEn": "Machiavellian Strategy – Volume I",
      "nameVi": "Chiến Lược Machiavelli – Tập I",
      "tier": "vip9",
      "hasData": true
  },
  "machiavelli-strategy-2-vip9": {
      "id": "machiavelli-strategy-2-vip9",
      "nameEn": "Machiavellian Strategy – Volume II",
      "nameVi": "Chiến Lược Machiavelli – Tập II",
      "tier": "vip9",
      "hasData": true
  },
  "machiavelli-strategy-3-vip9": {
      "id": "machiavelli-strategy-3-vip9",
      "nameEn": "Machiavellian Strategy – Volume III",
      "nameVi": "Chiến Lược Machiavelli – Tập III",
      "tier": "vip9",
      "hasData": true
  },
  "machiavelli-strategy-4-vip9": {
      "id": "machiavelli-strategy-4-vip9",
      "nameEn": "Machiavellian Strategy – Volume IV",
      "nameVi": "Chiến Lược Machiavelli – Tập IV",
      "tier": "vip9",
      "hasData": true
  },
  "machiavelli-strategy-5-vip9": {
      "id": "machiavelli-strategy-5-vip9",
      "nameEn": "Machiavellian Strategy – Volume V",
      "nameVi": "Chiến Lược Machiavelli – Tập V",
      "tier": "vip9",
      "hasData": true
  },
  "master-english-high-efficiency-vip1": {
      "id": "master-english-high-efficiency-vip1",
      "nameEn": "Master English: High-Efficiency Foundations",
      "nameVi": "Làm Chủ Tiếng Anh: Nền Tảng Hiệu Quả Cao",
      "tier": "vip1",
      "hasData": true
  },
  "master-english-high-efficiency-vip2": {
      "id": "master-english-high-efficiency-vip2",
      "nameEn": "Master English: High-Efficiency Intermediate Accelerator",
      "nameVi": "Làm Chủ Tiếng Anh: Bộ Tăng Tốc Trung Cấp Hiệu Quả Cao",
      "tier": "vip2",
      "hasData": true
  },
  "meaning-of-life-free": {
      "id": "meaning-of-life-free",
      "nameEn": "The Meaning of Life: Foundations of Balance",
      "nameVi": "Ý Nghĩa Của Cuộc Sống: Nền Tảng Của Sự Cân Bằng",
      "tier": "free",
      "hasData": true
  },
  "meaning-of-life-vip1-vip1": {
      "id": "meaning-of-life-vip1-vip1",
      "nameEn": "The Meaning of Life: Seeds of Purpose",
      "nameVi": "Ý Nghĩa Cuộc Sống: Hạt Giống Mục Đích",
      "tier": "vip1",
      "hasData": true
  },
  "meaning-of-life-vip3": {
      "id": "meaning-of-life-vip3",
      "nameEn": "The Meaning of Life: Harmony of Being",
      "nameVi": "Ý Nghĩa Của Cuộc Sống: Hòa Điệu Của Tồn Tại",
      "tier": "vip3",
      "hasData": true
  },
  "mens-mental-health-free": {
      "id": "mens-mental-health-free",
      "nameEn": "Men's Mental Health",
      "nameVi": "Sức Khỏe Tinh Thần Nam Giới",
      "tier": "free",
      "hasData": true
  },
  "mens-mental-health-vip1": {
      "id": "mens-mental-health-vip1",
      "nameEn": "Men’s Mental Health",
      "nameVi": "Sức Khỏe Tinh Thần Nam Giới",
      "tier": "vip1",
      "hasData": true
  },
  "mens-mental-health-vip2": {
      "id": "mens-mental-health-vip2",
      "nameEn": "Men’s Mental Health",
      "nameVi": "Sức Khỏe Tinh Thần Nam Giới",
      "tier": "vip2",
      "hasData": true
  },
  "mens-mental-health-vip3": {
      "id": "mens-mental-health-vip3",
      "nameEn": "Men’s Mental Health",
      "nameVi": "Sức Khỏe Tinh Thần Nam Giới",
      "tier": "vip3",
      "hasData": true
  },
  "mental-health-vip1": {
      "id": "mental-health-vip1",
      "nameEn": "Mental Health VIP1",
      "nameVi": "Sức Khỏe Tinh Thần VIP1",
      "tier": "vip1",
      "hasData": true
  },
  "mentors-who-light-the-way-vip4": {
      "id": "mentors-who-light-the-way-vip4",
      "nameEn": "Mentors Who Light the Way",
      "nameVi": "Những Người Dẫn Đường Thắp Sáng",
      "tier": "vip4",
      "hasData": true
  },
  "mindfulness-vip1": {
      "id": "mindfulness-vip1",
      "nameEn": "Mindfulness",
      "nameVi": "Thực Hành Chánh Niệm",
      "tier": "vip1",
      "hasData": true
  },
  "national-civilization-cycles-vip9": {
      "id": "national-civilization-cycles-vip9",
      "nameEn": "National Civilization Cycles",
      "nameVi": "Chu Kỳ Văn Minh Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-culture-power-vip9": {
      "id": "national-culture-power-vip9",
      "nameEn": "National Culture Power",
      "nameVi": "Sức Mạnh Văn Hóa Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-cyber-strategy-vip9": {
      "id": "national-cyber-strategy-vip9",
      "nameEn": "National Cyber Strategy",
      "nameVi": "Chiến Lược An Ninh Mạng Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-diplomacy-vip9": {
      "id": "national-diplomacy-vip9",
      "nameEn": "National Diplomacy Strategy",
      "nameVi": "Chiến Lược Ngoại Giao Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-economic-strategy-vip9": {
      "id": "national-economic-strategy-vip9",
      "nameEn": "National Economic Strategy",
      "nameVi": "Chiến Lược Kinh Tế Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-energy-security-vip9": {
      "id": "national-energy-security-vip9",
      "nameEn": "National Energy Security",
      "nameVi": "An Ninh Năng Lượng Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-geopolitical-mapping-vip9": {
      "id": "national-geopolitical-mapping-vip9",
      "nameEn": "National Geopolitical Mapping",
      "nameVi": "Bản Đồ Địa Chính Trị Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-identity-strategy-vip9": {
      "id": "national-identity-strategy-vip9",
      "nameEn": "National Identity Strategy",
      "nameVi": "Chiến Lược Bản Sắc Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-megatrends-vip9": {
      "id": "national-megatrends-vip9",
      "nameEn": "National Megatrends Strategy",
      "nameVi": "Chiến Lược Megatrend Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-military-strategy-vip9": {
      "id": "national-military-strategy-vip9",
      "nameEn": "National Military Strategy",
      "nameVi": "Chiến Lược Quân Sự Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-power-capability-vip9": {
      "id": "national-power-capability-vip9",
      "nameEn": "National Power Capability",
      "nameVi": "Năng Lực Quyền Lực Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-resilience-systems-vip9": {
      "id": "national-resilience-systems-vip9",
      "nameEn": "National Resilience Systems",
      "nameVi": "Hệ Thống Chống Chịu Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-risk-intelligence-vip9": {
      "id": "national-risk-intelligence-vip9",
      "nameEn": "National Risk & Intelligence Strategy",
      "nameVi": "Chiến Lược Rủi Ro & Tình Báo Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-space-strategy-vip9": {
      "id": "national-space-strategy-vip9",
      "nameEn": "National Space Strategy",
      "nameVi": "Chiến Lược Không Gian Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-strategy-foundations-vip9": {
      "id": "national-strategy-foundations-vip9",
      "nameEn": "National Strategy Foundations",
      "nameVi": "Nền Tảng Chiến Lược Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "nutrition-free": {
      "id": "nutrition-free",
      "nameEn": "Nutrition",
      "nameVi": "Nutrition",
      "tier": "free",
      "hasData": true
  },
  "nutrition-vip2": {
      "id": "nutrition-vip2",
      "nameEn": "Advanced Nutrition Strategies",
      "nameVi": "Chiến Lược Dinh Dưỡng Nâng Cao",
      "tier": "vip2",
      "hasData": true
  },
  "obesity-free": {
      "id": "obesity-free",
      "nameEn": "Obesity Management",
      "nameVi": "Quản Lý Béo Phì",
      "tier": "free",
      "hasData": true
  },
  "obesity-management-ii-vip3": {
      "id": "obesity-management-ii-vip3",
      "nameEn": "Obesity Management II VIP3",
      "nameVi": "Quản Lý Béo Phì II VIP3",
      "tier": "vip3",
      "hasData": true
  },
  "obesity-management-vip3": {
      "id": "obesity-management-vip3",
      "nameEn": "Obesity Management VIP3",
      "nameVi": "Quản Lý Béo Phì VIP3",
      "tier": "vip3",
      "hasData": true
  },
  "ocd-support-free": {
      "id": "ocd-support-free",
      "nameEn": "OCD Support",
      "nameVi": "Hỗ Trợ Rối Loạn Ám Ảnh Cưỡng Chế",
      "tier": "free",
      "hasData": true
  },
  "ocd-support-vip1": {
      "id": "ocd-support-vip1",
      "nameEn": "OCD Support",
      "nameVi": "Hỗ Trợ Rối Loạn Ám Ảnh Cưỡng Chế",
      "tier": "vip1",
      "hasData": true
  },
  "ocd-support-vip2": {
      "id": "ocd-support-vip2",
      "nameEn": "OCD Support",
      "nameVi": "Hỗ Trợ Rối Loạn Ám Ảnh Cưỡng Chế",
      "tier": "vip2",
      "hasData": true
  },
  "ocd-support-vip3": {
      "id": "ocd-support-vip3",
      "nameEn": "OCD Support",
      "nameVi": "Hỗ Trợ Rối Loạn Ám Ảnh Cưỡng Chế",
      "tier": "vip3",
      "hasData": true
  },
  "personal-operating-system-vip2": {
      "id": "personal-operating-system-vip2",
      "nameEn": "Personal Operating System — Room 2",
      "nameVi": "Hệ Điều Hành Cá Nhân — Phòng 2",
      "tier": "vip2",
      "hasData": true
  },
  "philosophy-of-everyday-free": {
      "id": "philosophy-of-everyday-free",
      "nameEn": "Philosophy of Everyday (Free)",
      "nameVi": "Triết Học Đời Thường (Miễn Phí)",
      "tier": "free",
      "hasData": true
  },
  "philosophy-of-everyday-life-vip2": {
      "id": "philosophy-of-everyday-life-vip2",
      "nameEn": "Philosophy of Everyday Life",
      "nameVi": "Triết Lý Cuộc Sống Hằng Ngày",
      "tier": "vip2",
      "hasData": true
  },
  "physical-fitness-and-nutrition-free": {
      "id": "physical-fitness-and-nutrition-free",
      "nameEn": "Loneliness Comfort",
      "nameVi": "An Ủi Nỗi Cô Đơn",
      "tier": "free",
      "hasData": true
  },
  "productivity-and-focus-free": {
      "id": "productivity-and-focus-free",
      "nameEn": "Productivity & Focus",
      "nameVi": "Năng Suất & Tập Trung",
      "tier": "free",
      "hasData": true
  },
  "productivity-and-focus-vip1": {
      "id": "productivity-and-focus-vip1",
      "nameEn": "Productivity & Focus",
      "nameVi": "Năng Suất & Tập Trung",
      "tier": "vip1",
      "hasData": true
  },
  "productivity-and-focus-vip2": {
      "id": "productivity-and-focus-vip2",
      "nameEn": "Productivity & Focus",
      "nameVi": "Năng Suất & Tập Trung",
      "tier": "vip2",
      "hasData": true
  },
  "productivity-and-focus-vip3": {
      "id": "productivity-and-focus-vip3",
      "nameEn": "Productivity & Focus",
      "nameVi": "Năng Suất & Tập Trung",
      "tier": "vip3",
      "hasData": true
  },
  "productivity-foundations-vip2": {
      "id": "productivity-foundations-vip2",
      "nameEn": "Foundations of Productivity — Room 1",
      "nameVi": "Nền Tảng Năng Suất — Phòng 1",
      "tier": "vip2",
      "hasData": true
  },
  "ptsd-support-free": {
      "id": "ptsd-support-free",
      "nameEn": "PTSD Support",
      "nameVi": "Hỗ Trợ Rối Loạn Căng Thẳng Sau Sang Chấn",
      "tier": "free",
      "hasData": true
  },
  "public-speaking-delivery-vip3": {
      "id": "public-speaking-delivery-vip3",
      "nameEn": "Delivery & Presence — Room 3",
      "nameVi": "Trình Bày & Hiện Diện — Phòng 3",
      "tier": "vip3",
      "hasData": true
  },
  "public-speaking-foundations-vip3": {
      "id": "public-speaking-foundations-vip3",
      "nameEn": "Public Speaking Foundations — Room 1",
      "nameVi": "Nền Tảng Nói Trước Công Chúng — Phòng 1",
      "tier": "vip3",
      "hasData": true
  },
  "public-speaking-structure-vip3": {
      "id": "public-speaking-structure-vip3",
      "nameEn": "Structuring Your Message — Room 2",
      "nameVi": "Cấu Trúc Thông Điệp — Phòng 2",
      "tier": "vip3",
      "hasData": true
  },
  "relationship-healing-free": {
      "id": "relationship-healing-free",
      "nameEn": "Relationship Healing",
      "nameVi": "Hàn Gắn Mối Quan Hệ",
      "tier": "free",
      "hasData": true
  },
  "resilience-and-adaptation-vip4": {
      "id": "resilience-and-adaptation-vip4",
      "nameEn": "Resilience and Adaptation",
      "nameVi": "Khả Năng Phục Hồi và Thích Nghi",
      "tier": "vip4",
      "hasData": true
  },
  "self-love-free": {
      "id": "self-love-free",
      "nameEn": "Self Love",
      "nameVi": "Yêu Thương Bản Thân",
      "tier": "free",
      "hasData": true
  },
  "shadow-work-free": {
      "id": "shadow-work-free",
      "nameEn": "Shadow Work",
      "nameVi": "Làm Việc Với Bóng Tối",
      "tier": "free",
      "hasData": true
  },
  "shadow-work-vip1": {
      "id": "shadow-work-vip1",
      "nameEn": "Shadow Work",
      "nameVi": "Làm Việc Với Bóng Tối",
      "tier": "vip1",
      "hasData": true
  },
  "shadow-work-vip2": {
      "id": "shadow-work-vip2",
      "nameEn": "Shadow Work",
      "nameVi": "Làm Việc Với Bóng Tối",
      "tier": "vip2",
      "hasData": true
  },
  "shadow-work-vip3": {
      "id": "shadow-work-vip3",
      "nameEn": "Shadow Work",
      "nameVi": "Làm Việc Với Bóng Tối",
      "tier": "vip3",
      "hasData": true
  },
  "sleep-improvement-free": {
      "id": "sleep-improvement-free",
      "nameEn": "Sleep Improvement",
      "nameVi": "Cải Thiện Giấc Ngủ",
      "tier": "free",
      "hasData": true
  },
  "sleep-improvement-vip1": {
      "id": "sleep-improvement-vip1",
      "nameEn": "Sleep Improvement",
      "nameVi": "Cải Thiện Giấc Ngủ",
      "tier": "vip1",
      "hasData": true
  },
  "sleep-improvement-vip2": {
      "id": "sleep-improvement-vip2",
      "nameEn": "Intermediate Sleep Improvement",
      "nameVi": "Cải Thiện Giấc Ngủ Trung Cấp",
      "tier": "vip2",
      "hasData": true
  },
  "social-anxiety-free": {
      "id": "social-anxiety-free",
      "nameEn": "Social Anxiety",
      "nameVi": "Lo Âu Xã Hội",
      "tier": "free",
      "hasData": true
  },
  "social-anxiety-vip2": {
      "id": "social-anxiety-vip2",
      "nameEn": "Social Anxiety",
      "nameVi": "Lo Âu Xã Hội",
      "tier": "vip2",
      "hasData": true
  },
  "social-anxiety-vip3": {
      "id": "social-anxiety-vip3",
      "nameEn": "Social Anxiety",
      "nameVi": "Lo Âu Xã Hội",
      "tier": "vip3",
      "hasData": true
  },
  "soulmate-free": {
      "id": "soulmate-free",
      "nameEn": "Soulmate",
      "nameVi": "Người Tri Kỷ",
      "tier": "free",
      "hasData": true
  },
  "stoicism-free": {
      "id": "stoicism-free",
      "nameEn": "Stoic Philosophy (Free)",
      "nameVi": "Triết Học Khắc Kỷ (Miễn Phí)",
      "tier": "free",
      "hasData": true
  },
  "strategic-adaptive-intelligence-vip9": {
      "id": "strategic-adaptive-intelligence-vip9",
      "nameEn": "Strategic Adaptive Intelligence",
      "nameVi": "Trí Tuệ Thích Ứng Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-antifragile-growth-vip9": {
      "id": "strategic-antifragile-growth-vip9",
      "nameEn": "Antifragile Growth Mastery",
      "nameVi": "Làm Chủ Tăng Trưởng Chống Mong Manh",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-cognitive-models-vip9": {
      "id": "strategic-cognitive-models-vip9",
      "nameEn": "Cognitive Precision & Mental Models",
      "nameVi": "Độ Chính Xác Nhận Thức & Mô Hình Tư Duy",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-deep-work-vip9": {
      "id": "strategic-deep-work-vip9",
      "nameEn": "Deep Work Mastery",
      "nameVi": "Làm Chủ Công Việc Sâu",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-emotional-neutrality-vip9": {
      "id": "strategic-emotional-neutrality-vip9",
      "nameEn": "Strategic Emotional Neutrality",
      "nameVi": "Trung Lập Cảm Xúc Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-failure-recovery-vip9": {
      "id": "strategic-failure-recovery-vip9",
      "nameEn": "Failure Recovery Mastery",
      "nameVi": "Làm Chủ Hồi Phục Thất Bại",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-foundations-vip9": {
      "id": "strategic-foundations-vip9",
      "nameEn": "Foundations of Strategic Thinking",
      "nameVi": "Nền Tảng Tư Duy Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-identity-vip9": {
      "id": "strategic-identity-vip9",
      "nameEn": "Strategic Identity Mastery",
      "nameVi": "Làm Chủ Bản Sắc Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-influence-individual-vip9": {
      "id": "strategic-influence-individual-vip9",
      "nameEn": "Individual Influence Mastery",
      "nameVi": "Làm Chủ Ảnh Hưởng Cá Nhân",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-lifelong-fitness-vip9": {
      "id": "strategic-lifelong-fitness-vip9",
      "nameEn": "Lifelong Fitness Mastery",
      "nameVi": "Làm Chủ Thể Lực Suốt Đời",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-long-horizon-vip9": {
      "id": "strategic-long-horizon-vip9",
      "nameEn": "Long Horizon Mastery",
      "nameVi": "Làm Chủ Chân Trời Dài",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-negotiation-individual-vip9": {
      "id": "strategic-negotiation-individual-vip9",
      "nameEn": "Individual Negotiation Mastery",
      "nameVi": "Làm Chủ Đàm Phán Cá Nhân",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-pattern-recognition-vip9": {
      "id": "strategic-pattern-recognition-vip9",
      "nameEn": "Pattern Recognition Mastery",
      "nameVi": "Làm Chủ Nhận Diện Mẫu Hình",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-personal-systems-vip9": {
      "id": "strategic-personal-systems-vip9",
      "nameEn": "Personal Systems Mastery",
      "nameVi": "Làm Chủ Hệ Thống Cá Nhân",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-reputation-individual-vip9": {
      "id": "strategic-reputation-individual-vip9",
      "nameEn": "Individual Reputation Mastery",
      "nameVi": "Làm Chủ Danh Tiếng Cá Nhân",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-risk-calibration-vip9": {
      "id": "strategic-risk-calibration-vip9",
      "nameEn": "Risk Calibration Mastery",
      "nameVi": "Làm Chủ Hiệu Chỉnh Rủi Ro",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-scenario-thinking-vip9": {
      "id": "strategic-scenario-thinking-vip9",
      "nameEn": "Scenario Thinking Mastery",
      "nameVi": "Làm Chủ Tư Duy Kịch Bản",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-self-governance-vip9": {
      "id": "strategic-self-governance-vip9",
      "nameEn": "Self-Governance Mastery",
      "nameVi": "Làm Chủ Tự Quản Trị",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-signal-detection-vip9": {
      "id": "strategic-signal-detection-vip9",
      "nameEn": "Signal Detection Mastery",
      "nameVi": "Làm Chủ Phát Hiện Tín Hiệu",
      "tier": "vip9",
      "hasData": true
  },
  "stress-free": {
      "id": "stress-free",
      "nameEn": "Stress Relief",
      "nameVi": "Giảm Căng Thẳng",
      "tier": "free",
      "hasData": true
  },
  "stress-vip1-vip1": {
      "id": "stress-vip1-vip1",
      "nameEn": "Stress Management VIP1",
      "nameVi": "Quản Lý Căng Thẳng VIP1",
      "tier": "vip1",
      "hasData": true
  },
  "stress-vip2": {
      "id": "stress-vip2",
      "nameEn": "Intermediate Stress Management",
      "nameVi": "Quản Lý Căng Thẳng Trung Cấp",
      "tier": "vip2",
      "hasData": true
  },
  "stress-vip3": {
      "id": "stress-vip3",
      "nameEn": "Stress Management & Resilience",
      "nameVi": "Quản Lý Căng Thẳng & Sức Bền Tinh Thần",
      "tier": "vip3",
      "hasData": true
  },
  "study-skills-motivation-kids-l3-kidslevel3": {
      "id": "study-skills-motivation-kids-l3-kidslevel3",
      "nameEn": "Study Skills & Motivation",
      "nameVi": "Kỹ Năng Học Tập & Động Lực",
      "tier": "kidslevel3",
      "hasData": true
  },
  "sun-tzu-strategy-vip9": {
      "id": "sun-tzu-strategy-vip9",
      "nameEn": "Sun Tzu – Strategic Foundations",
      "nameVi": "Tôn Tử – Nền Tảng Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "universe-with-us-free": {
      "id": "universe-with-us-free",
      "nameEn": "Universe With US",
      "nameVi": "Vũ Trụ Ở Cùng Chúng Ta",
      "tier": "free",
      "hasData": true
  },
  "weight-loss-and-fitness-free": {
      "id": "weight-loss-and-fitness-free",
      "nameEn": "Weight Loss & Fitness",
      "nameVi": "Giảm Cân & Thể Dục",
      "tier": "free",
      "hasData": true
  },
  "weight-loss-and-fitness-vip2": {
      "id": "weight-loss-and-fitness-vip2",
      "nameEn": "Weight Loss & Fitness",
      "nameVi": "Giảm Cân & Thể Dục",
      "tier": "vip2",
      "hasData": true
  },
  "weight-loss-and-fitness-vip3": {
      "id": "weight-loss-and-fitness-vip3",
      "nameEn": "Weight Loss & Fitness",
      "nameVi": "Giảm Cân & Thể Dục",
      "tier": "vip3",
      "hasData": true
  }
};
