/**
 * AUTO-GENERATED: Do not edit manually
 * Generated by: scripts/generate-room-registry.js
 * Run: node scripts/generate-room-registry.js
 */
import { RoomData } from "@/lib/roomData";

export const roomDataMap: Record<string, RoomData> = {
  "cognitive-clarity-and-mental-load-vip2": {
      "id": "cognitive-clarity-and-mental-load-vip2",
      "nameEn": "Cognitive Clarity & Mental Load Management — Room 7",
      "nameVi": "Rõ Ràng Tư Duy & Quản Lý Gánh Nặng Tâm Trí — Phòng 7",
      "tier": "vip2",
      "hasData": true
  },
  "corporate-analytics-strategy-vip9": {
      "id": "corporate-analytics-strategy-vip9",
      "nameEn": "Corporate Analytics Strategy",
      "nameVi": "Chiến Lược Phân Tích Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-conflict-navigation-vip9": {
      "id": "corporate-conflict-navigation-vip9",
      "nameEn": "Corporate Conflict Navigation",
      "nameVi": "Điều Hướng Xung Đột Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-crisis-strategy-vip9": {
      "id": "corporate-crisis-strategy-vip9",
      "nameEn": "Corporate Crisis Strategy",
      "nameVi": "Chiến Lược Ứng Phó Khủng Hoảng Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-cross-functional-vip9": {
      "id": "corporate-cross-functional-vip9",
      "nameEn": "Corporate Cross-Functional Collaboration",
      "nameVi": "Hợp Tác Chức Năng Chéo Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-execution-systems-vip9": {
      "id": "corporate-execution-systems-vip9",
      "nameEn": "Corporate Execution Systems",
      "nameVi": "Hệ Thống Thực Thi Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-foresight-vip9": {
      "id": "corporate-foresight-vip9",
      "nameEn": "Corporate Strategic Foresight",
      "nameVi": "Dự Báo Chiến Lược Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-global-strategy-vip9": {
      "id": "corporate-global-strategy-vip9",
      "nameEn": "Corporate Global Strategy",
      "nameVi": "Chiến Lược Toàn Cầu Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-governance-vip9": {
      "id": "corporate-governance-vip9",
      "nameEn": "Corporate Governance",
      "nameVi": "Quản Trị Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-innovation-engines-vip9": {
      "id": "corporate-innovation-engines-vip9",
      "nameEn": "Corporate Innovation Engines",
      "nameVi": "Động Cơ Sáng Tạo Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-leadership-leverage-vip9": {
      "id": "corporate-leadership-leverage-vip9",
      "nameEn": "Corporate Leadership Leverage",
      "nameVi": "Đòn Bẩy Lãnh Đạo Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-long-cycle-planning-vip9": {
      "id": "corporate-long-cycle-planning-vip9",
      "nameEn": "Corporate Long Cycle Planning",
      "nameVi": "Hoạch Định Chu Kỳ Dài Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-negotiation-vip9": {
      "id": "corporate-negotiation-vip9",
      "nameEn": "Corporate Negotiation",
      "nameVi": "Đàm Phán Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-positioning-vip9": {
      "id": "corporate-positioning-vip9",
      "nameEn": "Corporate Positioning",
      "nameVi": "Định Vị Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-resource-allocation-vip9": {
      "id": "corporate-resource-allocation-vip9",
      "nameEn": "Corporate Resource Allocation",
      "nameVi": "Phân Bổ Nguồn Lực Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-scaling-strategy-vip9": {
      "id": "corporate-scaling-strategy-vip9",
      "nameEn": "Corporate Scaling Strategy",
      "nameVi": "Chiến Lược Mở Rộng Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-talent-architecture-vip9": {
      "id": "corporate-talent-architecture-vip9",
      "nameEn": "Corporate Talent Architecture",
      "nameVi": "Kiến Trúc Tài Năng Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "corporate-team-culture-vip9": {
      "id": "corporate-team-culture-vip9",
      "nameEn": "Corporate Team Culture",
      "nameVi": "Văn Hóa Đội Nhóm Doanh Nghiệp",
      "tier": "vip9",
      "hasData": true
  },
  "debate-fallacies-vip2": {
      "id": "debate-fallacies-vip2",
      "nameEn": "Fallacies in Debate — VIP2 Room",
      "nameVi": "Ngụy Biện Trong Tranh Luận — Phòng VIP2",
      "tier": "vip2",
      "hasData": true
  },
  "deep-work-and-focus-vip2": {
      "id": "deep-work-and-focus-vip2",
      "nameEn": "Deep Work & Focus Architecture — Room 3",
      "nameVi": "Làm Việc Sâu & Kiến Trúc Tập Trung — Phòng 3",
      "tier": "vip2",
      "hasData": true
  },
  "execution-flow-and-momentum-vip2": {
      "id": "execution-flow-and-momentum-vip2",
      "nameEn": "Execution Flow & Momentum — Room 5",
      "nameVi": "Dòng Chảy Thực Thi & Đà Tiến — Phòng 5",
      "tier": "vip2",
      "hasData": true
  },
  "executive-function-mastery-vip2": {
      "id": "executive-function-mastery-vip2",
      "nameEn": "Executive Function Mastery — Room 8",
      "nameVi": "Làm Chủ Chức Năng Điều Hành — Phòng 8",
      "tier": "vip2",
      "hasData": true
  },
  "frederick-bismarck-comparison-vip9": {
      "id": "frederick-bismarck-comparison-vip9",
      "nameEn": "Frederick the Great vs Otto von Bismarck — Comparative Strategy",
      "nameVi": "Frederick Đại đế và Otto von Bismarck — So Sánh Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "grammar-fluency-structure-vip2": {
      "id": "grammar-fluency-structure-vip2",
      "nameEn": "Grammar for Fluency & Structure",
      "nameVi": "Ngữ Pháp Cho Độ Trôi Chảy & Cấu Trúc",
      "tier": "vip2",
      "hasData": true
  },
  "grammar-foundations-free": {
      "id": "grammar-foundations-free",
      "nameEn": "Grammar Foundations",
      "nameVi": "Grammar Foundations",
      "tier": "free",
      "hasData": true
  },
  "interpersonal-intelligence-mastery-vip5": {
      "id": "interpersonal-intelligence-mastery-vip5",
      "nameEn": "Interpersonal Intelligence Mastery",
      "nameVi": "Làm Chủ Trí Tuệ Giao Tiếp",
      "tier": "vip5",
      "hasData": true
  },
  "long-term-projects-and-lifetime-systems-vip2": {
      "id": "long-term-projects-and-lifetime-systems-vip2",
      "nameEn": "Long-Term Projects & Lifetime Systems — Room 6",
      "nameVi": "Dự Án Dài Hạn & Hệ Thống Trọn Đời — Phòng 6",
      "tier": "vip2",
      "hasData": true
  },
  "machiavelli-grand-strategy-vip9": {
      "id": "machiavelli-grand-strategy-vip9",
      "nameEn": "Machiavelli Grand Strategy",
      "nameVi": "Đại Chiến Lược Machiavelli",
      "tier": "vip9",
      "hasData": true
  },
  "machiavelli-strategy-1-vip9": {
      "id": "machiavelli-strategy-1-vip9",
      "nameEn": "Machiavellian Strategy – Volume I",
      "nameVi": "Chiến Lược Machiavelli – Tập I",
      "tier": "vip9",
      "hasData": true
  },
  "machiavelli-strategy-2-vip9": {
      "id": "machiavelli-strategy-2-vip9",
      "nameEn": "Machiavellian Strategy – Volume II",
      "nameVi": "Chiến Lược Machiavelli – Tập II",
      "tier": "vip9",
      "hasData": true
  },
  "machiavelli-strategy-3-vip9": {
      "id": "machiavelli-strategy-3-vip9",
      "nameEn": "Machiavellian Strategy – Volume III",
      "nameVi": "Chiến Lược Machiavelli – Tập III",
      "tier": "vip9",
      "hasData": true
  },
  "machiavelli-strategy-4-vip9": {
      "id": "machiavelli-strategy-4-vip9",
      "nameEn": "Machiavellian Strategy – Volume IV",
      "nameVi": "Chiến Lược Machiavelli – Tập IV",
      "tier": "vip9",
      "hasData": true
  },
  "machiavelli-strategy-5-vip9": {
      "id": "machiavelli-strategy-5-vip9",
      "nameEn": "Machiavellian Strategy – Volume V",
      "nameVi": "Chiến Lược Machiavelli – Tập V",
      "tier": "vip9",
      "hasData": true
  },
  "master-english-high-efficiency-vip1": {
      "id": "master-english-high-efficiency-vip1",
      "nameEn": "Master English: High-Efficiency Foundations",
      "nameVi": "Làm Chủ Tiếng Anh: Nền Tảng Hiệu Quả Cao",
      "tier": "vip1",
      "hasData": true
  },
  "master-english-high-efficiency-vip2": {
      "id": "master-english-high-efficiency-vip2",
      "nameEn": "Master English: High-Efficiency Intermediate Accelerator",
      "nameVi": "Làm Chủ Tiếng Anh: Bộ Tăng Tốc Trung Cấp Hiệu Quả Cao",
      "tier": "vip2",
      "hasData": true
  },
  "national-civilization-cycles-vip9": {
      "id": "national-civilization-cycles-vip9",
      "nameEn": "National Civilization Cycles",
      "nameVi": "Chu Kỳ Văn Minh Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-culture-power-vip9": {
      "id": "national-culture-power-vip9",
      "nameEn": "National Culture Power",
      "nameVi": "Sức Mạnh Văn Hóa Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-cyber-strategy-vip9": {
      "id": "national-cyber-strategy-vip9",
      "nameEn": "National Cyber Strategy",
      "nameVi": "Chiến Lược An Ninh Mạng Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-diplomacy-vip9": {
      "id": "national-diplomacy-vip9",
      "nameEn": "National Diplomacy Strategy",
      "nameVi": "Chiến Lược Ngoại Giao Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-economic-strategy-vip9": {
      "id": "national-economic-strategy-vip9",
      "nameEn": "National Economic Strategy",
      "nameVi": "Chiến Lược Kinh Tế Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-energy-security-vip9": {
      "id": "national-energy-security-vip9",
      "nameEn": "National Energy Security",
      "nameVi": "An Ninh Năng Lượng Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-geopolitical-mapping-vip9": {
      "id": "national-geopolitical-mapping-vip9",
      "nameEn": "National Geopolitical Mapping",
      "nameVi": "Bản Đồ Địa Chính Trị Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-identity-strategy-vip9": {
      "id": "national-identity-strategy-vip9",
      "nameEn": "National Identity Strategy",
      "nameVi": "Chiến Lược Bản Sắc Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-megatrends-vip9": {
      "id": "national-megatrends-vip9",
      "nameEn": "National Megatrends Strategy",
      "nameVi": "Chiến Lược Megatrend Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-military-strategy-vip9": {
      "id": "national-military-strategy-vip9",
      "nameEn": "National Military Strategy",
      "nameVi": "Chiến Lược Quân Sự Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-power-capability-vip9": {
      "id": "national-power-capability-vip9",
      "nameEn": "National Power Capability",
      "nameVi": "Năng Lực Quyền Lực Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-resilience-systems-vip9": {
      "id": "national-resilience-systems-vip9",
      "nameEn": "National Resilience Systems",
      "nameVi": "Hệ Thống Chống Chịu Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-risk-intelligence-vip9": {
      "id": "national-risk-intelligence-vip9",
      "nameEn": "National Risk & Intelligence Strategy",
      "nameVi": "Chiến Lược Rủi Ro & Tình Báo Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-space-strategy-vip9": {
      "id": "national-space-strategy-vip9",
      "nameEn": "National Space Strategy",
      "nameVi": "Chiến Lược Không Gian Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "national-strategy-foundations-vip9": {
      "id": "national-strategy-foundations-vip9",
      "nameEn": "National Strategy Foundations",
      "nameVi": "Nền Tảng Chiến Lược Quốc Gia",
      "tier": "vip9",
      "hasData": true
  },
  "personal-operating-system-vip2": {
      "id": "personal-operating-system-vip2",
      "nameEn": "Personal Operating System — Room 2",
      "nameVi": "Hệ Điều Hành Cá Nhân — Phòng 2",
      "tier": "vip2",
      "hasData": true
  },
  "productivity-foundations-vip2": {
      "id": "productivity-foundations-vip2",
      "nameEn": "Foundations of Productivity — Room 1",
      "nameVi": "Nền Tảng Năng Suất — Phòng 1",
      "tier": "vip2",
      "hasData": true
  },
  "public-speaking-delivery-vip3": {
      "id": "public-speaking-delivery-vip3",
      "nameEn": "Delivery & Presence — Room 3",
      "nameVi": "Trình Bày & Hiện Diện — Phòng 3",
      "tier": "vip3",
      "hasData": true
  },
  "public-speaking-foundations-vip3": {
      "id": "public-speaking-foundations-vip3",
      "nameEn": "Public Speaking Foundations — Room 1",
      "nameVi": "Nền Tảng Nói Trước Công Chúng — Phòng 1",
      "tier": "vip3",
      "hasData": true
  },
  "public-speaking-structure-vip3": {
      "id": "public-speaking-structure-vip3",
      "nameEn": "Structuring Your Message — Room 2",
      "nameVi": "Cấu Trúc Thông Điệp — Phòng 2",
      "tier": "vip3",
      "hasData": true
  },
  "stoicism-free": {
      "id": "stoicism-free",
      "nameEn": "Stoicism",
      "nameVi": "Stoicism",
      "tier": "free",
      "hasData": true
  },
  "strategic-adaptive-intelligence-vip9": {
      "id": "strategic-adaptive-intelligence-vip9",
      "nameEn": "Strategic Adaptive Intelligence",
      "nameVi": "Trí Tuệ Thích Ứng Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-antifragile-growth-vip9": {
      "id": "strategic-antifragile-growth-vip9",
      "nameEn": "Antifragile Growth Mastery",
      "nameVi": "Làm Chủ Tăng Trưởng Chống Mong Manh",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-cognitive-models-vip9": {
      "id": "strategic-cognitive-models-vip9",
      "nameEn": "Cognitive Precision & Mental Models",
      "nameVi": "Độ Chính Xác Nhận Thức & Mô Hình Tư Duy",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-deep-work-vip9": {
      "id": "strategic-deep-work-vip9",
      "nameEn": "Deep Work Mastery",
      "nameVi": "Làm Chủ Công Việc Sâu",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-emotional-neutrality-vip9": {
      "id": "strategic-emotional-neutrality-vip9",
      "nameEn": "Strategic Emotional Neutrality",
      "nameVi": "Trung Lập Cảm Xúc Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-failure-recovery-vip9": {
      "id": "strategic-failure-recovery-vip9",
      "nameEn": "Failure Recovery Mastery",
      "nameVi": "Làm Chủ Hồi Phục Thất Bại",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-foundations-vip9": {
      "id": "strategic-foundations-vip9",
      "nameEn": "Foundations of Strategic Thinking",
      "nameVi": "Nền Tảng Tư Duy Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-identity-vip9": {
      "id": "strategic-identity-vip9",
      "nameEn": "Strategic Identity Mastery",
      "nameVi": "Làm Chủ Bản Sắc Chiến Lược",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-influence-individual-vip9": {
      "id": "strategic-influence-individual-vip9",
      "nameEn": "Individual Influence Mastery",
      "nameVi": "Làm Chủ Ảnh Hưởng Cá Nhân",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-lifelong-fitness-vip9": {
      "id": "strategic-lifelong-fitness-vip9",
      "nameEn": "Lifelong Fitness Mastery",
      "nameVi": "Làm Chủ Thể Lực Suốt Đời",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-long-horizon-vip9": {
      "id": "strategic-long-horizon-vip9",
      "nameEn": "Long Horizon Mastery",
      "nameVi": "Làm Chủ Chân Trời Dài",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-negotiation-individual-vip9": {
      "id": "strategic-negotiation-individual-vip9",
      "nameEn": "Individual Negotiation Mastery",
      "nameVi": "Làm Chủ Đàm Phán Cá Nhân",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-pattern-recognition-vip9": {
      "id": "strategic-pattern-recognition-vip9",
      "nameEn": "Pattern Recognition Mastery",
      "nameVi": "Làm Chủ Nhận Diện Mẫu Hình",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-personal-systems-vip9": {
      "id": "strategic-personal-systems-vip9",
      "nameEn": "Personal Systems Mastery",
      "nameVi": "Làm Chủ Hệ Thống Cá Nhân",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-reputation-individual-vip9": {
      "id": "strategic-reputation-individual-vip9",
      "nameEn": "Individual Reputation Mastery",
      "nameVi": "Làm Chủ Danh Tiếng Cá Nhân",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-risk-calibration-vip9": {
      "id": "strategic-risk-calibration-vip9",
      "nameEn": "Risk Calibration Mastery",
      "nameVi": "Làm Chủ Hiệu Chỉnh Rủi Ro",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-scenario-thinking-vip9": {
      "id": "strategic-scenario-thinking-vip9",
      "nameEn": "Scenario Thinking Mastery",
      "nameVi": "Làm Chủ Tư Duy Kịch Bản",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-self-governance-vip9": {
      "id": "strategic-self-governance-vip9",
      "nameEn": "Self-Governance Mastery",
      "nameVi": "Làm Chủ Tự Quản Trị",
      "tier": "vip9",
      "hasData": true
  },
  "strategic-signal-detection-vip9": {
      "id": "strategic-signal-detection-vip9",
      "nameEn": "Signal Detection Mastery",
      "nameVi": "Làm Chủ Phát Hiện Tín Hiệu",
      "tier": "vip9",
      "hasData": true
  },
  "sun-tzu-strategy-vip9": {
      "id": "sun-tzu-strategy-vip9",
      "nameEn": "Sun Tzu – Strategic Foundations",
      "nameVi": "Tôn Tử – Nền Tảng Chiến Lược",
      "tier": "vip9",
      "hasData": true
  }
};
