#!/bin/bash
# Auto-rename all MP3 & JSON to correct format
# Run in public/audio/rooms/ or public/

# MP3 renames (lowercase, hyphens, no spaces/UUID)
git mv ":public:paf_vip3_6_en.mp3.mp3" "aligning-aspirations-for-love-vip3.mp3" 2>/dev/null || true
git mv "Aligning_Aspirations_for_Love_VIP3.mp3" "aligning-aspirations-for-love-vip3.mp3"
git mv "Aligning_Goals_for_Love_VIP2.mp3" "aligning-goals-for-love-vip2.mp3"
git mv "Aligning_Goals_with_Values_VIP3.mp3" "aligning-goals-with-values-vip3.mp3"
git mv "Anchoring Divine Fortitude in Prayer_VIP3.mp3" "anchoring-divine-fortitude-in-prayer-vip3.mp3"
git mv "Anticipating and Handling Obstacles_free.mp3" "anticipating-and-handling-obstacles-free.mp3"
git mv "Attaining Internal Unity_VIP2.mp3" "attaining-internal-unity-vip2.mp3"
git mv "Automating Architecture Design_VIP3.mp3" "automating-architecture-design-vip3.mp3"
git mv "Avoiding Dependency Trap_VIP2.mp3" "avoiding-dependency-trap-vip2.mp3"
git mv "Avoiding Dependency Traps_VIP3.mp3" "avoiding-dependency-traps-vip3.mp3"
git mv "Awareness of Triggers_Free.mp3" "awareness-of-triggers-free.mp3"
git mv "Balanced Generosity for Inner Peace+VIP3.mp3" "balanced-generosity-for-inner-peace-vip3.mp3"
git mv "Balanced Generosity for Inner Peace_VIP2.mp3" "balanced-generosity-for-inner-peace-vip2.mp3"
git mv "Breast Self-Exam Guide_Free.mp3" "breast-self-exam-guide-free.mp3"
git mv "Build Resilience in Challenges_VIP3.mp3" "build-resilience-in-challenges-vip3.mp3"
git mv "Building Active Habits_vip1.mp3" "building-active-habits-vip1.mp3"
git mv "Building Behavioral Resilience_vip3.mp3" "building-behavioral-resilience-vip3.mp3"
git mv "Building Ethical AI Frameworks_VIP2.mp3" "building-ethical-ai-frameworks-vip2.mp3"
git mv "Building Positive Self-Talk — 02d9b264-3c0b-41d4-a632-6c8d071ad81d_vip1.mp3" "building-positive-self-talk-vip1.mp3"
git mv "Building Spiritual BondsVIP1.mp3" "building-spiritual-bonds-vip1.mp3"
git mv "Building a Consistent Sleep Schedule_vip2.mp3" "building-a-consistent-sleep-schedule-vip2.mp3"
git mv "Building_Authentic_Connections_VIP1.mp3" "building-authentic-connections-vip1.mp3"
git mv "Building_Authentic_Relationships_VIP3.mp3" "building-authentic-relationships-vip3.mp3"
git mv "Building_Hydration_Habits_Free.mp3" "building-hydration-habits-free.mp3"
git mv "Building_Mindful_Awareness_VIP1.mp3" "building-mindful-awareness-vip1.mp3"
git mv "Building_Resilience_through_Self_Talk_VIP3.mp3" "building-resilience-through-self-talk-vip3.mp3"
git mv "Building_Simple_Routines_Free.mp3" "building-simple-routines-free.mp3"
git mv "Building_Social_Confidence_VIP1.mp3" "building-social-confidence-vip1.mp3"
git mv "Choosing Nutrient-Dense Foods_vip2.mp3" "choosing-nutrient-dense-foods-vip2.mp3"
git mv "Choosing_Nutrient_Dense_Foods_VIP2.mp3" "choosing-nutrient-dense-foods-vip2.mp3"
git mv "Clarifying_Affirmations_for_Growth_VIP1.mp3" "clarifying-affirmations-for-growth-vip1.mp3"
git mv "Clarifying_Values_for_Love_VIP1.mp3" "clarifying-values-for-love-vip1.mp3"
git mv "Communicating_for_Deeper_Trust_VIP2.mp3" "communicating-for-deeper-trust-vip2.mp3"
git mv "Compressing Complex Models_Free.mp3" "compressing-complex-models-free.mp3"
git mv "Connecting with Faith Groups_Free.mp3" "connecting-with-faith-groups-free.mp3"
git mv "Contemplating Shadow Aspects_VIP2.mp3" "contemplating-shadow-aspects-vip2.mp3"
git mv "Controlling Portion Sizes_vip1.mp3" "controlling-portion-sizes-vip1.mp3"
git mv "Controlling_Portion_Sizes_VIP1.mp3" "controlling-portion-sizes-vip1.mp3"
git mv "Crafting Effective Prompts_free.mp3" "crafting-effective-prompts-free.mp3"
git mv "Creating Daily Calm Routines — 96dbb2b0-3b7d-4635-a1c1-9f90f1452b1f_vip1.mp3" "creating-daily-calm-routines-vip1.mp3"
git mv "Creating a Sleep-Friendly Environment_vip2.mp3" "creating-a-sleep-friendly-environment-vip2.mp3"
git mv "Creating_Stress_Reducing_Routines_VIP1.mp3" "creating-stress-reducing-routines-vip1.mp3"
git mv "Cultivating Positive Mindset_VIP.mp3" "cultivating-positive-mindset-vip1.mp3"
git mv "Cultivating Resilient Faith through Prayer_VIP2.mp3" "cultivating-resilient-faith-through-prayer-vip2.mp3"
git mv "Cultivating Stoic Moderation_VIP2.mp3" "cultivating-stoic-moderation-vip2.mp3"
git mv "Cultivating Stoic Moderation_VIP3.mp3" "cultivating-stoic-moderation-vip3.mp3"
git mv "Cultivating_Deep_Empathy_VIP3.mp3" "cultivating-deep-empathy-vip3.mp3"
git mv "Cultivating_Empathy_for_Bonds_VIP2.mp3" "cultivating-empathy-for-bonds-vip2.mp3"
git mv "Daily Routines for Calm Balance_VIP3.mp3" "daily-routines-for-calm-balance-vip3.mp3"
git mv "Dealing with PMS Symptoms_Free.mp3" "dealing-with-pms-symptoms-free.mp3"
git mv "Decentralized Learning for Privacy_VIP3.mp3" "decentralized-learning-for-privacy-vip3.mp3"
git mv "Decoding AI’s Black Box_free.mp3" "decoding-ais-black-box-free.mp3"
git mv "Deepening Human Rights Awareness_VIP3.mp3" "deepening-human-rights-awareness-vip3.mp3"
git mv "Deepening Insight with Scripture_VIP2.mp3" "deepening-insight-with-scripture-vip2.mp3"
git mv "Deepening Mindful Eating Practices_vip3.mp3" "deepening-mindful-eating-practices-vip3.mp3"
git mv "Deepening Mindful Eating_vip1.mp3" "deepening-mindful-eating-vip1.mp3"
git mv "Deepening Relaxation Practices-vip3.mp3" "deepening-relaxation-practices-vip3.mp3"
git mv "Deepening_Confidence_through_Awareness_VIP3.mp3" "deepening-confidence-through-awareness-vip3.mp3"
git mv "Deepening_Mindful_Eating_Practices_VIP3.mp3" "deepening-mindful-eating-practices-vip3.mp3"
git mv "Deepening_Mindfulness_for_Stress_Relief_VIP3.mp3" "deepening-mindfulness-for-stress-relief-vip3.mp3"
git mv "Deepening_Self_Awareness_for_Love_VIP3.mp3" "deepening-self-awareness-for-love-vip3.mp3"
git mv "Detecting Trigger Patterns_VIP2.mp3" "detecting-trigger-patterns-vip2.mp3"
git mv "Direct Preference Optimization_VIP1.mp3" "direct-preference-optimization-vip1.mp3"
git mv "Discerning God’s Eternal Plan_VIP3.mp3" "discerning-gods-eternal-plan-vip3.mp3"
git mv "Discernment in Relationships_VIP3.mp3" "discernment-in-relationships-vip3.mp3"
git mv "Distilling Knowledge for Efficiency_VIP2.mp3" "distilling-knowledge-for-efficiency-vip2.mp3"
git mv "Embracing Divine Trust_VIP1.mp3" "embracing-divine-trust-vip1.mp3"
git mv "Embracing God’s Timing for Peace_VIP2.mp3" "embracing-gods-timing-for-peace-vip2.mp3"
git mv "Embracing Inner Wholeness_Free.mp3" "embracing-inner-wholeness-free.mp3"
git mv "Embracing Shadow Integration_VIP1.mp3" "embracing-shadow-integration-vip1.mp3"
git mv "Encoding Latent Spaces with VAEs_VIP3.mp3" "encoding-latent-spaces-with-vaes-vip3.mp3"
git mv "Engaging in Shadow Pardon_VIP2.mp3" "engaging-in-shadow-pardon-vip2.mp3"
git mv "Engaging_Communities_Confidently_VIP2.mp3" "engaging-communities-confidently-vip2.mp3"
git mv "Enhancing Mindful Eating Practices_vip2.mp3" "enhancing-mindful-eating-practices-vip2.mp3"
git mv "Enhancing_Hydration_Habits_VIP1.mp3" "enhancing-hydration-habits-vip1.mp3"
git mv "Ensuring Ethical AI Use_free.mp3" "ensuring-ethical-ai-use-free.mp3"
git mv "Evolving Neural Networks_VIP3.mp3" "evolving-neural-networks-vip3.mp3"
git mv "Fine-Tuning for Task Adaptation_vip1.mp3" "fine-tuning-for-task-adaptation-vip1.mp3"
git mv "Forgiving Shadow Self_Free.mp3" "forgiving-shadow-self-free.mp3"
git mv "Fostering Equality through Solidarity_VIP3.mp3" "fostering-equality-through-solidarity-vip3.mp3"
git mv "Fostering Transcendent Community Bonds_VIP3.mp3" "fostering-transcendent-community-bonds-vip3.mp3"
git mv "Fostering_Social_Support_for_Stress_VIP3.mp3" "fostering-social-support-for-stress-vip3.mp3"
git mv "Fostering_Trust_through_Communication_VIP3.mp3" "fostering-trust-through-communication-vip3.mp3"
git mv "Fusing Shadow Components_VIP3.mp3" "fusing-shadow-components-vip3.mp3"
git mv "Graph-Augmented Retrieval Systems_VIP1.mp3" "graph-augmented-retrieval-systems-vip1.mp3"
git mv "Gratitude for Inner Tranquility_VIP3.mp3" "gratitude-for-inner-tranquility-vip3.mp3"
git mv "Handling Heavy Flow_Free.mp3" "handling-heavy-flow-free.mp3"
git mv "Hormonal Balance Tips_Free.mp3" "hormonal-balance-tips-free.mp3"
git mv "Hydration During Pain_Free.mp3" "hydration-during-pain-free.mp3"
git mv "Identifying Hidden Traits_Free.mp3" "identifying-hidden-traits-free.mp3"
git mv "Illuminating Divine Purpose with Scripture_VIP3.mp3" "illuminating-divine-purpose-with-scripture-vip3.mp3"
git mv "Improving Mental Focusf_VIP3.mp3" "improving-mental-focus-vip3.mp3"
git mv "Incorporating Mindful Activity_vip3.mp3" "incorporating-mindful-activity-vip3.mp3"
git mv "Integrating Shadow Parts_Free.mp3" "integrating-shadow-parts-free.mp3"
git mv "Journaling Divine Insights_VIP1.mp3" "journaling-divine-insights-vip1.mp3"
git mv "Learning with Stepwise Reasoning_VIP3.mp3" "learning-with-stepwise-reasoning-vip3.mp3"
git mv "Letting Go of External Needs_VIP1.mp3" "letting-go-of-external-needs-vip1.mp3"
git mv "Limiting Evening Stimulants_free.mp3" "limiting-evening-stimulants-free.mp3"
git mv "Listening_for_Better_Bonds_Free.mp3" "listening-for-better-bonds-free.mp3"
git mv "Listening_to_Foster_Trust_VIP1.mp3" "listening-to-foster-trust-vip1.mp3"
git mv "Low-Rank Adaptation Techniques_VIP1.mp3" "low-rank-adaptation-techniques-vip1.mp3"
git mv "Managing Evening Diet_vip2.mp3" "managing-evening-diet-vip2.mp3"
git mv "Managing Period Pain_Free.mp3" "managing-period-pain-free.mp3"
git mv "Managing Stress with Breathing — e842e995-f2cd-44f1-86a8-3e55debe1713_vip1.mp3" "managing-stress-with-breathing-vip1.mp3"
git mv "Managing_Portion_Sizes_VIP2.mp3" "managing-portion-sizes-vip2.mp3"
git mv "Mastering Attention Mechanisms_VIP2.mp3" "mastering-attention-mechanisms-vip2.mp3"
git mv "Mastering Balanced Meal Planning_vip3.mp3" "mastering-balanced-meal-planning-vip3.mp3"
git mv "Mastering Your Sleep Schedule_vip3.mp3" "mastering-your-sleep-schedule-vip3.mp3"
git mv "Mastering an Active Lifestyle_vip2.mp3" "mastering-an-active-lifestyle-vip2.mp3"
git mv "Mastering_Balanced_Meal_Planning_VIP3.mp3" "mastering-balanced-meal-planning-vip3.mp3"
git mv "Mastering_Deep_Breathing_for_Calm_VIP3.mp3" "mastering-deep-breathing-for-calm-vip3.mp3"
git mv "Mastering_Hydration_Habits_VIP2.mp3" "mastering-hydration-habits-vip2.mp3"
git mv "Mastering_Social_Confidence_VIP2.mp3" "mastering-social-confidence-vip2.mp3"
git mv "Meaning_of_Life_ VIP1.mp3" "meaning-of-life-vip1.mp3"
git mv "Meaning_of_Life_VIP2.mp3" "meaning-of-life-vip2.mp3"
git mv "Meaning_of_Life_VIP3.mp3" "meaning-of-life-vip3.mp3"
git mv "Meaning_of_Life_free.mp3" "meaning-of-life-free.mp3"
git mv "Meditating_for_Inner_Peace_Free.mp3" "meditating-for-inner-peace-free.mp3"
git mv "Memory_Enhancement_Tips_VIP3.mp3" "memory-enhancement-tips-vip3.mp3"
git mv "Mens_Mental_Health_Free.json" "mens-mental-health-free.json"
git mv "Mens_Mental_Health_VIP1.json" "mens-mental-health-vip1.json"
git mv "Mens_Mental_Health_VIP2.json" "mens-mental-health-vip2.json"
git mv "Mens_Mental_Health_VIP3.json" "mens-mental-health-vip3.json"
git mv "Menstrual Cycle Basics_Free.mp3" "menstrual-cycle-basics-free.mp3"
git mv "Mental Exercises for Sharpness_VIP3.mp3" "mental-exercises-for-sharpness-vip3.mp3"
git mv "Mental Health_VIP1.json" "mental-health-vip1.json"
git mv "Mental SharpnessVIP3.json" "mental-sharpness-vip3.json"
git mv "Mental_Sharpness_VIP3.json" "mental-sharpness-vip3.json"
git mv "Mentoring_Confidence_in_Others_VIP3.mp3" "mentoring-confidence-in-others-vip3.mp3"
git mv "Mercy Blade .mp3" "mercy-blade.mp3"
git mv "Mercy_Blade.mp3" "mercy-blade.mp3"
git mv "Merging Shadow Elements_VIP2.mp3" "merging-shadow-elements-vip2.mp3"
git mv "Mindful_Confidence_Building_VIP2.mp3" "mindful-confidence-building-vip2.mp3"
git mv "Mindfulness for Soul Serenity_VIP3.mp3" "mindfulness-for-soul-serenity-vip3.mp3"
git mv "Mindfulness_Free.json" "mindfulness-free.json"
git mv "Mindfulness_VIP1.json" "mindfulness-vip1.json"
git mv "Mindfulness_VIP2.json" "mindfulness-vip2.json"
git mv "Mindfulness_VIP3.json" "mindfulness-vip3.json"
git mv "Monitoring Abdominal Pain_Free.mp3" "monitoring-abdominal-pain-free.mp3"
git mv "Multimodal Data Integration_VIP1.mp3" "multimodal-data-integration-vip1.mp3"
git mv "Nurturing_Meaningful_Connections_VIP2.mp3" "nurturing-meaningful-connections-vip2.mp3"
git mv "OCD Support_Free.json" "ocd-support-free.json"
git mv "OCD Support_VIP1.json" "ocd-support-vip1.json"
git mv "OCD Support_VIP2.json" "ocd-support-vip2.json"
git mv "OCD Support_VIP3.json" "ocd-support-vip3.json"
git mv "Optimizing Portion Control_vip2.mp3" "optimizing-portion-control-vip2.mp3"
git mv "Optimizing Pre-Bed Nutrition.mp3" "optimizing-pre-bed-nutrition-free.mp3"
git mv "Optimizing with Expert Mixtures_VIP2.mp3" "optimizing-with-expert-mixtures-vip2.mp3"
git mv "Overcome_Storm_VIP3.json" "overcome-storm-vip3.json"
git mv "Overcoming_Confidence_Barriers_VIP3.mp3" "overcoming-confidence-barriers-vip3.mp3"
git mv "PTSD Support_Free.json" "ptsd-support-free.json"
git mv "PTSD Support_VIP1.json" "ptsd-support-vip1.json"
git mv "PTSD Support_VIP2.json" "ptsd-support-vip2.json"
git mv "PTSD Support_VIP3.json" "ptsd-support-vip3.json"
git mv "Participating in Shadow Absolution_VIP.mp3" "participating-in-shadow-absolution-vip1.mp3"
git mv "Perfecting Your Sleep Environment_vip3.mp3" "perfecting-your-sleep-environment-vip3.mp3"
git mv "Physical Fitness and Nutrition_Free.json" "physical-fitness-and-nutrition-free.json"
git mv "Physical Fitness and Nutrition_VIP1.json" "physical-fitness-and-nutrition-vip1.json"
git mv "Physical Fitness and Nutrition_VIP2.json" "physical-fitness-and-nutrition-vip2.json"
git mv "Physical Fitness and Nutrition_VIP3.json" "physical-fitness-and-nutrition-vip3.json"
git mv "Planning Balanced Meals_vip1.mp3" "planning-balanced-meals-vip1.mp3"
git mv "Planning_Balanced_Meals_VIP1.mp3" "planning-balanced-meals-vip1.mp3"
git mv "Planning_Goals_for_Growth_VIP2.mp3" "planning-goals-for-growth-vip2.mp3"
git mv "Pondering Shadow Elements_VIP3.mp3" "pondering-shadow-elements-vip3.mp3"
git mv "Practices for Inner Serenity_VIP3.mp3" "practices-for-inner-serenity-vip3.mp3"
git mv "Practicing Mindful Awareness — d70f7822-4b5f-47f0-8a44-2b3e60e6a1ee_vip1.mp3" "practicing-mindful-awareness-vip1.mp3"
git mv "Practicing Mindful Eating_free.mp3" "practicing-mindful-eating-free.mp3"
git mv "Practicing Relaxation Techniques_vip2.mp3" "practicing-relaxation-techniques-vip2.mp3"
git mv "Practicing Shadow Forgiveness_VIP1.mp3" "practicing-shadow-forgiveness-vip1.mp3"
git mv "Practicing_Deep_Breathing_VIP1.mp3" "practicing-deep-breathing-vip1.mp3"
git mv "Practicing_Empathy_in_Interactions_VIP1.mp3" "practicing-empathy-in-interactions-vip1.mp3"
git mv "Practicing_Empathy_in_Love_VIP1.mp3" "practicing-empathy-in-love-vip1.mp3"
git mv "Practicing_Mindful_Eating_VIP1.mp3" "practicing-mindful-eating-vip1.mp3"
git mv "Practicing_Self_Compassion_VIP3.mp3" "practicing-self-compassion-vip3.mp3"
git mv "Praying for Daily Strength_Free.mp3" "praying-for-daily-strength-free.mp3"
git mv "Praying for Inner StrengthVIP1.mp3" "praying-for-inner-strength-vip1.mp3"
git mv "Prioritizing Nutrient-Dense Diets_vip3.mp3" "prioritizing-nutrient-dense-diets-vip3.mp3"
git mv "Prioritizing Self-Care for Strength_VIP2.mp3" "prioritizing-self-care-for-strength-vip2.mp3"
git mv "Prioritizing Self-Care for Strength_VIP3.mp3" "prioritizing-self-care-for-strength-vip3.mp3"
git mv "Prioritizing_Nutrient_Dense_Foods_VIP3.mp3" "prioritizing-nutrient-dense-foods-vip3.mp3"
git mv "Productivity_And_Focus_Free.json" "productivity-and-focus-free.json"
git mv "Productivity_And_Focus_VIP1.json" "productivity-and-focus-vip1.json"
git mv "Productivity_And_Focus_VIP2.json" "productivity-and-focus-vip2.json"
git mv "Productivity_And_Focus_VIP3.json" "productivity-and-focus-vip3.json"
git mv "Protecting Energy from Exploitation_VIP3.mp3" "protecting-energy-from-exploitation-vip3.mp3"
git mv "Reading Holy Texts_Free.mp3" "reading-holy-texts-free.mp3"
git mv "Realizing Intrinsic Cohesion_VIP3.mp3" "realizing-intrinsic-cohesion-vip3.mp3"
git mv "Recognizing Hidden Aspects_VIP1.mp3" "recognizing-hidden-aspects-vip1.mp3"
git mv "Refining Balanced Meal Planning_vip2.mp3" "refining-balanced-meal-planning-vip2.mp3"
git mv "Refining Portion Control Strategies_vip3.mp3" "refining-portion-control-strategies-vip3.mp3"
git mv "Refining_Affirmations_for_Strength_VIP2.mp3" "refining-affirmations-for-strength-vip2.mp3"
git mv "Refining_Balanced_Meal_Planning_VIP2.mp3" "refining-balanced-meal-planning-vip2.mp3"
git mv "Refining_Portion_Control_VIP3.mp3" "refining-portion-control-vip3.mp3"
git mv "Refining_Values_for_Lasting_Love_VIP2.mp3" "refining-values-for-lasting-love-vip2.mp3"
git mv "Reflecting for Deeper Faith_VIP2.mp3" "reflecting-for-deeper-faith-vip2.mp3"
git mv "Reflecting on Shadows_Free.mp3" "reflecting-on-shadows-free.mp3"
git mv "Reframing Thoughts for Calm_VIP1.mp3" "reframing-thoughts-for-calm-vip1.mp3"
git mv "Reinforcement Learning with Feedback_VIP1.mp3" "reinforcement-learning-with-feedback-vip1.mp3"
git mv "Relationship Healing_Free.json" "relationship-healing-free.json"
git mv "Relationship Healing_VIP1.json" "relationship-healing-vip1.json"
git mv "Relationship Healing_VIP2.json" "relationship-healing-vip2.json"
git mv "Relationship Healing_VIP3.json" "relationship-healing-vip3.json"
git mv "Relieving Abdominal Pain_Free.mp3" "relieving-abdominal-pain-free.mp3"
git mv "Revealing Buried Characteristics_VIP3.mp3" "revealing-buried-characteristics-vip3.mp3"
git mv "Safeguarding Data in AI_free.mp3" "safeguarding-data-in-ai-free.mp3"
git mv "Seek Support in Tough Times_VIP3.mp3" "seek-support-in-tough-times-vip3.mp3"
git mv "Seeking Celestial Guidance through Meditation_VIP3.mp3" "seeking-celestial-guidance-through-meditation-vip3.mp3"
git mv "Seeking Divine Clarity via Meditation_VIP2.mp3" "seeking-divine-clarity-via-meditation-vip2.mp3"
git mv "Seeking Guidance through Meditation_VIP1.mp3" "seeking-guidance-through-meditation-vip1.mp3"
git mv "Self Love_Free.json" "self-love-free.json"
git mv "Self Love_VIP1.json" "self-love-vip1.json"
git mv "Self Love_VIP2.json" "self-love-vip2.json"
git mv "Self Love_VIP3.json" "self-love-vip3.json"
git mv "Self-Awareness for Emotional Balance_VIP2.mp3" "self-awareness-for-emotional-balance-vip2.mp3"
git mv "Self-Awareness for Emotional Balance_VIP3.mp3" "self-awareness-for-emotional-balance-vip3.mp3"
git mv "Setting Boundaries with Confidence_VIP3.mp3" "setting-boundaries-with-confidence-vip3.mp3"
git mv "Setting_Small_Goals_Free.mp3" "setting-small-goals-free.mp3"
git mv "Shadow Reflection Practices_VIP1.mp3" "shadow-reflection-practices-vip1.mp3"
git mv "Shadow Work_Free.json" "shadow-work-free.json"
git mv "Shadow Work_VIP1.json" "shadow-work-vip1.json"
git mv "Shadow Work_VIP2.json" "shadow-work-vip2.json"
git mv "Shadow Work_VIP3.json" "shadow-work-vip3.json"
git mv "Simple_Social_Steps_Free.mp3" "simple-social-steps-free.mp3"
git mv "Sleep_free.json" "sleep-free.json"
git mv "Social_Anxiety_Free.json" "social-anxiety-free.json"
git mv "Social_Anxiety_VIP1.json" "social-anxiety-vip1.json"
git mv "Social_Anxiety_VIP2.json" "social-anxiety-vip2.json"
git mv "Social_Anxiety_VIP3.json" "social-anxiety-vip3.json"
git mv "Sparking_Initial_Connections_Free.mp3" "sparking-initial-connections-free.mp3"
git mv "Spotting Trigger Configurations_VIP.mp3" "spotting-trigger-configurations-vip1.mp3"
git mv "Starting Healthy Meal Choices_free.mp3" "starting-healthy-meal-choices-free.mp3"
git mv "Starting a Bedtime Routine_free.mp3" "starting-a-bedtime-routine-free.mp3"
git mv "Starting_Affirmations_for_Confidence_Free.mp3" "starting-affirmations-for-confidence-free.mp3"
git mv "Starting_Balanced_Meal_Planning_Free.mp3" "starting-balanced-meal-planning-free.mp3"
git mv "Starting_Self_Awareness_for_Love_Free.mp3" "starting-self-awareness-for-love-free.mp3"
git mv "Starting_Stress_Relief_Breathing_Free.mp3" "starting-stress-relief-breathing-free.mp3"
git mv "Strengthening Models Against Attacks_VIP2.mp3" "strengthening-models-against-attacks-vip2.mp3"
git mv "Strengthening Sacred Connections_VIP2.mp3" "strengthening-sacred-connections-vip2.mp3"
git mv "Studying Scripture for Insight_VIP1.mp3" "studying-scripture-for-insight-vip1.mp3"
git mv "Surrendering to Cosmic Purpose_VIP3.mp3" "surrendering-to-cosmic-purpose-vip3.mp3"
git mv "Sustaining an Active Lifestyle_vip3.mp3" "sustaining-an-active-lifestyle-vip3.mp3"
git mv "Sustaining_Healthy_Eating_Habits_VIP3.mp3" "sustaining-healthy-eating-habits-vip3.mp3"
git mv "Sustaining_Long_Term_Bonds_VIP3.mp3" "sustaining-long-term-bonds-vip3.mp3"
git mv "Sustaining_Stress_Reducing_Routines_VIP3.mp3" "sustaining-stress-reducing-routines-vip3.mp3"
git mv "Tracking Sleep Patternsv_vip3.mp3" "tracking-sleep-patterns-vip3.mp3"
git mv "Tracking_Goals_for_Success_VIP1.mp3" "tracking-goals-for-success-vip1.mp3"
git mv "Trigger Awareness Techniques_VIP1.mp3" "trigger-awareness-techniques-vip1.mp3"
git mv "Trusting Divine Wisdom_Free.mp3" "trusting-divine-wisdom-free.mp3"
git mv "Trusting Universal Timing_VIP1.mp3" "trusting-universal-timing-vip1.mp3"
git mv "Trying Daily Movement_free.mp3" "trying-daily-movement-free.mp3"
git mv "Trying Simple Relaxation_free.mp3" "trying-simple-relaxation-free.mp3"
git mv "Trying_Mindful_Eating_Free.mp3" "trying-mindful-eating-free.mp3"
git mv "Trying_Mindful_Moments_Free.mp3" "trying-mindful-moments-free.mp3"
git mv "Uncovering Concealed Traits_VIP2.mp3" "uncovering-concealed-traits-vip2.mp3"
git mv "Using_Exercise_to_Manage_Stress_VIP3.mp3" "using-exercise-to-manage-stress-vip3.mp3"
git mv "Using_Positive_Self_Talk_VIP1.mp3" "using-positive-self-talk-vip1.mp3"
git mv "Virtuous Action for Respect_VIP2.mp3" "virtuous-action-for-respect-vip2.mp3"
git mv "Virtuous Action for Respect_VIP3.mp3" "virtuous-action-for-respect-vip3.mp3"
git mv "Weight_Loss_And_Fitness_Free.json" "weight-loss-and-fitness-free.json"
git mv "Weight_Loss_And_Fitness_VIP1.json" "weight-loss-and-fitness-vip1.json"
git mv "Weight_Loss_And_Fitness_VIP2.json" "weight-loss-and-fitness-vip2.json"
git mv "Weight_Loss_And_Fitness_VIP3.json" "weight-loss-and-fitness-vip3.json"
git mv "Women_Health.json" "women-health.json"

# Commit all changes
git add .
git commit -m "AUTO-FIX: Rename all MP3/JSON to lowercase-hyphen format"
echo "All files renamed! Push now."
