import type { ObsWorkpack } from "./types";

export const OBS_INT_SPRINT1_WORKPACKS = [
  {
    wp_id: "WP-OBS-AUDIO-000001",
    semantic_key: "obs.audio.unavailable",
    tm_int_id: "OBS-AUDIO-000001",
    source_file: "src/lib/tm-int/obs/detectors/audio.ts",
    source_line: 17,
    source_anchor_excerpt: "Audio URL was missing or unavailable.",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/audioObservation.test.ts",
    objective: "Record AudioUnavailable when a required listening URL is absent or unavailable.",
    expected_product_value: "Teacher Mercy can observe product audio failure without blaming the learner.",
    acceptance_tests: "audioObservation.test.ts asserts AudioUnavailable fact for missing requestedUrl.",
    judge_checks: "Independent Judge verifies this is a fact record only and does not infer learner weakness.",
    anti_fake_checks: "Must include concrete route/task/requestedUrl context when available; no verified=true self-promotion.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-AUDIO-000002",
    semantic_key: "obs.audio.duration_zero",
    tm_int_id: "OBS-AUDIO-000002",
    source_file: "src/lib/tm-int/obs/detectors/audio.ts",
    source_line: 32,
    source_anchor_excerpt: "Audio duration was zero.",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/audioObservation.test.ts",
    objective: "Record AudioDurationZero when media duration resolves to zero.",
    expected_product_value: "0:00 listening media becomes a product observation instead of a guessed learner answer.",
    acceptance_tests: "audioObservation.test.ts asserts AudioDurationZero for durationSeconds=0.",
    judge_checks: "Independent Judge checks duration fact is not converted into listening-score inference.",
    anti_fake_checks: "Requires numeric durationSeconds metric and verified=false.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-AUDIO-000003",
    semantic_key: "obs.audio.playback_failed",
    tm_int_id: "OBS-AUDIO-000003",
    source_file: "src/lib/tm-int/obs/detectors/audio.ts",
    source_line: 46,
    source_anchor_excerpt: "Audio playback failed:",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/audioObservation.test.ts",
    objective: "Record AudioPlaybackFailed when browser playback reports an error.",
    expected_product_value: "Playback errors are preserved as product failures for replay.",
    acceptance_tests: "audioObservation.test.ts asserts AudioPlaybackFailed for playbackError.",
    judge_checks: "Independent Judge checks captured message is factual and not psychological.",
    anti_fake_checks: "Requires concrete playbackError text and verified=false.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-AUDIO-000004",
    semantic_key: "obs.audio.replay_count",
    tm_int_id: "OBS-AUDIO-000004",
    source_file: "src/lib/tm-int/obs/detectors/audio.ts",
    source_line: 59,
    source_anchor_excerpt: "Audio replay count observed.",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/audioObservation.test.ts",
    objective: "Record AudioReplayCount as a neutral usage fact.",
    expected_product_value: "Repeated playback can be replayed without labeling confusion or weakness.",
    acceptance_tests: "audioObservation.test.ts asserts replayCount metric is preserved.",
    judge_checks: "Independent Judge checks replay count remains descriptive only.",
    anti_fake_checks: "Requires replayCount > 0 metric and verified=false.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-SPEECH-000001",
    semantic_key: "obs.speech.mic_permission_denied",
    tm_int_id: "OBS-SPEECH-000001",
    source_file: "src/lib/tm-int/obs/detectors/speech.ts",
    source_line: 7,
    source_anchor_excerpt: "Microphone permission was denied.",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/observationPacket.test.ts",
    objective: "Record MicPermissionDenied without treating typed fallback as learner deficit.",
    expected_product_value: "Speaking fallback can be audited as environment/product constraint.",
    acceptance_tests: "observationPacket.test.ts includes speech detector facts in valid packet coverage.",
    judge_checks: "Independent Judge checks no learner weakness inference.",
    anti_fake_checks: "Requires permissionState=denied input and verified=false.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-SPEECH-000002",
    semantic_key: "obs.speech.timeout",
    tm_int_id: "OBS-SPEECH-000002",
    source_file: "src/lib/tm-int/obs/detectors/speech.ts",
    source_line: 21,
    source_anchor_excerpt: "Speech capture timed out.",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/observationPacket.test.ts",
    objective: "Record SpeechTimeout as an observation fact.",
    expected_product_value: "Speech capture timeout can be replayed separately from learner performance.",
    acceptance_tests: "observationPacket.test.ts validates timeout facts can be packetized.",
    judge_checks: "Independent Judge checks timeout metric is factual only.",
    anti_fake_checks: "Requires timedOut=true and verified=false.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-LEARNING-000001",
    semantic_key: "obs.learning.retry_observed",
    tm_int_id: "OBS-LEARNING-000001",
    source_file: "src/lib/tm-int/obs/detectors/learning.ts",
    source_line: 9,
    source_anchor_excerpt: "Retry action observed.",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/observationPacket.test.ts",
    objective: "Record RetryObserved as a neutral learner action fact.",
    expected_product_value: "Retry behavior becomes replayable without motivational inference.",
    acceptance_tests: "observationPacket.test.ts covers learning fact packet creation.",
    judge_checks: "Independent Judge checks action-only semantics.",
    anti_fake_checks: "Requires action=retry and verified=false.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-LEARNING-000002",
    semantic_key: "obs.learning.skip_observed",
    tm_int_id: "OBS-LEARNING-000002",
    source_file: "src/lib/tm-int/obs/detectors/learning.ts",
    source_line: 23,
    source_anchor_excerpt: "Skip action observed.",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/observationPacket.test.ts",
    objective: "Record SkipObserved as a neutral learner action fact.",
    expected_product_value: "Skip events are available to product replay without judgment language.",
    acceptance_tests: "observationPacket.test.ts covers learning fact packet creation.",
    judge_checks: "Independent Judge checks no inferred intent.",
    anti_fake_checks: "Requires action=skip and verified=false.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-LEARNING-000003",
    semantic_key: "obs.learning.hint_used",
    tm_int_id: "OBS-LEARNING-000003",
    source_file: "src/lib/tm-int/obs/detectors/learning.ts",
    source_line: 37,
    source_anchor_excerpt: "Hint usage observed.",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/observationPacket.test.ts",
    objective: "Record HintUsed as a neutral learner action fact.",
    expected_product_value: "Hint use can be replayed without claiming learner weakness.",
    acceptance_tests: "observationPacket.test.ts covers learning fact packet creation.",
    judge_checks: "Independent Judge checks no weakness inference.",
    anti_fake_checks: "Requires action=hint and verified=false.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-EVD-000001",
    semantic_key: "obs.evidence.packet_schema",
    tm_int_id: "OBS-EVD-000001",
    source_file: "src/lib/tm-int/obs/evidencePacket.ts",
    source_line: 13,
    source_anchor_excerpt: "schemaVersion: \"tm-int-obs-packet-v1\"",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/observationPacket.test.ts",
    objective: "Define and validate observation evidence packets.",
    expected_product_value: "Observation facts have a stable artifact shape for Judge replay.",
    acceptance_tests: "observationPacket.test.ts validates packet schema and required fields.",
    judge_checks: "Independent Judge checks packet schema is sufficient before promotion.",
    anti_fake_checks: "Packet creation never sets verified and contains fact-only payloads.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-REP-000001",
    semantic_key: "obs.replay.observation_replay",
    tm_int_id: "OBS-REP-000001",
    source_file: "src/lib/tm-int/obs/replay.ts",
    source_line: 7,
    source_anchor_excerpt: "replayObservationScenario",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/linhAudioFailureReplay.test.ts",
    objective: "Replay observation scenarios into evidence packets.",
    expected_product_value: "Product failures can be deterministically replayed for Judge review.",
    acceptance_tests: "linhAudioFailureReplay.test.ts replays Linh audio failure scenario.",
    judge_checks: "Independent Judge checks replay matches source scenario and does not self-verify.",
    anti_fake_checks: "Replay emits facts only and no verified=true field.",
    status: "workpack_ready",
    verified: false,
  },
  {
    wp_id: "WP-OBS-VAL-000001",
    semantic_key: "obs.validation.linh_audio_failure_replay",
    tm_int_id: "OBS-VAL-000001",
    source_file: "src/lib/tm-int/obs/replay.ts",
    source_line: 19,
    source_anchor_excerpt: "linh-placement-audio-failure",
    related_test_or_replay_file: "src/lib/tm-int/obs/__tests__/linhAudioFailureReplay.test.ts",
    objective: "Capture Linh placement audio failure as AudioDurationZero facts only.",
    expected_product_value: "The gold scenario records product audio failure without weak-listening inference.",
    acceptance_tests: "linhAudioFailureReplay.test.ts asserts requested URL, duration zero, guessed action, and no weakness language.",
    judge_checks: "Independent Judge checks Linh replay is factual and promotion remains external.",
    anti_fake_checks: "Must not include psychology, weak listening, or verified=true.",
    status: "workpack_ready",
    verified: false,
  },
] as const satisfies readonly ObsWorkpack[];

export function validateObsSprint1Workpacks(workpacks: readonly ObsWorkpack[] = OBS_INT_SPRINT1_WORKPACKS): string[] {
  const failures: string[] = [];
  const semanticKeys = new Set<string>();

  for (const wp of workpacks) {
    if (semanticKeys.has(wp.semantic_key)) failures.push(`duplicate semantic_key: ${wp.semantic_key}`);
    semanticKeys.add(wp.semantic_key);
    if (!wp.acceptance_tests.trim()) failures.push(`${wp.wp_id} acceptance_tests empty`);
    if (!wp.judge_checks.trim()) failures.push(`${wp.wp_id} judge_checks empty`);
    if (!wp.anti_fake_checks.trim()) failures.push(`${wp.wp_id} anti_fake_checks empty`);
    if (wp.verified !== false) failures.push(`${wp.wp_id} verified must be false`);
    if (wp.source_file === wp.related_test_or_replay_file) failures.push(`${wp.wp_id} self-covers source and test`);
  }

  return failures;
}
