// Auto-generated static music track list
export const MUSIC_TRACKS = [
  { id: '2015_11_08___peace___david_fes', title: 'Peace', src: '/audio/music/2015-11-08_-_Peace_-_David_Fesliyan-2.mp3' },
  { id: '2015_12_22___an_ambient_day___', title: 'An Ambient Day', src: '/audio/music/2015-12-22_-_An_Ambient_Day_-_David_Fesliyan-2.mp3' },
  { id: '2016_04_26___peace_and_happy__', title: 'Peace And Happy', src: '/audio/music/2016-04-26_-_Peace_And_Happy_-_David_Fesliyan-2.mp3' },
  { id: '2016_05_06___strings_of_time__', title: 'Strings of Time', src: '/audio/music/2016-05-06_-_Strings_of_Time_-_David_Fesliyan_1.mp3' },
  { id: '2017_10_14___sad_winds_chapter', title: 'Sad Winds Chapter 1', src: '/audio/music/2017-10-14_-_Sad_Winds_Chapter_1_-_David_Fesliyan-2.mp3' },
  { id: '2019_01_10___land_of_8_bits___', title: 'Land of 8 Bits', src: '/audio/music/2019-01-10_-_Land_of_8_Bits_-_Stephen_Bennett_-_FesliyanStudios.com-2.mp3' },
  { id: '2019_05_03___elevator_ride___w', title: 'Elevator Ride', src: '/audio/music/2019-05-03_-_Elevator_Ride_-_www.fesliyanstudios.com-2.mp3' },
  { id: '2019_06_05___the_lounge___www_', title: 'The Lounge', src: '/audio/music/2019-06-05_-_The_Lounge_-_www.fesliyanstudios.com_-_David_Renda-2.mp3' },
  { id: '2019_06_07___chill_gaming___da', title: 'Chill Gaming', src: '/audio/music/2019-06-07_-_Chill_Gaming_-_David_Fesliyan-2.mp3' },
  { id: '2019_06_27___on_my_own___www_f', title: 'On My Own', src: '/audio/music/2019-06-27_-_On_My_Own_-_www.FesliyanStudios.com_-_David_Renda-2.mp3' },
  { id: '2019_07_02___done_with_work___', title: 'Done With Work', src: '/audio/music/2019-07-02_-_Done_With_Work_-_www.FesliyanStudios.com_-_David_Renda-2.mp3' },
  { id: '2019_07_29___elven_forest___fe', title: 'Elven Forest   FesliyanStudios.com', src: '/audio/music/2019-07-29_-_Elven_Forest_-_FesliyanStudios.com_-_David_Renda-2.mp3' },
  { id: '2020_02_11___not_much_to_say__', title: 'Not Much To Say', src: '/audio/music/2020-02-11_-_Not_Much_To_Say_-_David_Fesliyan-2.mp3' },
  { id: '2020_03_22___the_soft_lullaby_', title: 'The Soft Lullaby   FesliyanStudios.com', src: '/audio/music/2020-03-22_-_The_Soft_Lullaby_-_FesliyanStudios.com_-_David_Renda-2.mp3' },
  { id: '2020_08_19___cruisin_along___w', title: 'Cruisin Along', src: '/audio/music/2020-08-19_-_Cruisin_Along_-_www.FesliyanStudios.com_David_Renda-2.mp3' },
  { id: '2020_09_14___looking_up___www_', title: 'Looking Up', src: '/audio/music/2020-09-14_-_Looking_Up_-_www.FesliyanStudios.com_David_Renda-2.mp3' },
  { id: '2020_09_14___mellow_thoughts__', title: 'Mellow Thoughts', src: '/audio/music/2020-09-14_-_Mellow_Thoughts_-_www.FesliyanStudios.com_David_Renda-2.mp3' },
  { id: '2020_09_14___tropical_keys___w', title: 'Tropical Keys', src: '/audio/music/2020-09-14_-_Tropical_Keys_-_www.FesliyanStudios.com_David_Renda_1.mp3' },
  { id: '2020_09_24___simplicity___davi', title: 'Simplicity', src: '/audio/music/2020-09-24_-_Simplicity_-_David_Fesliyan-2.mp3' },
  { id: 'heart_of_the_blade___tr_i_tim_', title: 'Heart of the Blade   Trái Tim Của Lưỡi Gươm', src: '/audio/music/Heart of the Blade _ Trái Tim Của Lưỡi Gươm (1).mp3' },
  { id: 'heart_of_the_blade___tr_i_tim_', title: 'Heart of the Blade   Trái Tim Của Lưỡi Gươm', src: '/audio/music/Heart of the Blade _ Trái Tim Của Lưỡi Gươm.mp3' },
  { id: 'in_a_quiet_room__i_open_my_min', title: 'In a quiet room, I open my mind,', src: '/audio/music/In a quiet room, I open my mind,.mp3' },
  { id: 'in_the_quiet__mercy___trong_im', title: 'In the Quiet, Mercy   Trong Im Lặng, Mercy', src: '/audio/music/In the Quiet, Mercy _ Trong Im Lặng, Mercy.mp3' },
  { id: 'mercy_on_my_mind___mercy_trong', title: 'Mercy On My Mind   Mercy Trong Tâm Trí', src: '/audio/music/Mercy On My Mind _ Mercy Trong Tâm Trí (1).mp3' },
  { id: 'mercy_on_my_mind___mercy_trong', title: 'Mercy On My Mind   Mercy Trong Tâm Trí', src: '/audio/music/Mercy On My Mind _ Mercy Trong Tâm Trí.mp3' },
  { id: 'rise_with_mercy___tr_i_d_y_c_n', title: 'Rise With Mercy   Trỗi Dậy Cùng Mercy', src: '/audio/music/Rise With Mercy _ Trỗi Dậy Cùng Mercy.mp3' },
  { id: 'romanticmusic2018_11_11___tend', title: 'RomanticMusic2018 11 11   Tender Love', src: '/audio/music/RomanticMusic2018-11-11_-_Tender_Love_-_David_Fesliyan-2.mp3' },
  { id: 'say_my_name__mercy_blade_1', title: 'Say My Name, Mercy Blade 1', src: '/audio/music/Say My Name, Mercy Blade 1.mp3' },
  { id: 'say_my_name__mercy_blade', title: 'Say My Name, Mercy Blade', src: '/audio/music/Say My Name, Mercy Blade.mp3' },
  { id: 'step_with_me__mercy____i_c_ng_', title: 'Step With Me, Mercy   Đi Cùng Tôi, Mercy', src: '/audio/music/Step With Me, Mercy _ Đi Cùng Tôi, Mercy.mp3' },
  { id: 'the_song_of_mercy_blade____a_s', title: 'The Song of Mercy Blade  — A Signature Anthem for Your Inner Life 1', src: '/audio/music/The Song of Mercy Blade_ — A Signature Anthem for Your Inner Life 1.mp3' },
  { id: 'the_song_of_mercy_blade____a_s', title: 'The Song of Mercy Blade  — A Signature Anthem for Your Inner Life', src: '/audio/music/The Song of Mercy Blade_ — A Signature Anthem for Your Inner Life.mp3' },
  { id: 'the_song_of_mercy_blade____a_s', title: 'The Song of Mercy Blade” — A Signature Anthem for Your Inner Life', src: '/audio/music/The Song of Mercy Blade” — A Signature Anthem for Your Inner Life (1).mp3' },
  { id: 'the_song_of_mercy_blade____a_s', title: 'The Song of Mercy Blade” — A Signature Anthem for Your Inner Life', src: '/audio/music/The Song of Mercy Blade” — A Signature Anthem for Your Inner Life (3).mp3' },
  { id: 'the_song_of_mercy_blade____a_s', title: 'The Song of Mercy Blade” — A Signature Anthem for Your Inner Life', src: '/audio/music/The Song of Mercy Blade” — A Signature Anthem for Your Inner Life.mp3' },
  { id: 'when_mercy_looks_at_me___khi_m', title: 'When Mercy Looks at Me   Khi Mercy Nhìn Về Tôi', src: '/audio/music/When Mercy Looks at Me _ Khi Mercy Nhìn Về Tôi (1).mp3' },
  { id: 'when_mercy_looks_at_me___khi_m', title: 'When Mercy Looks at Me   Khi Mercy Nhìn Về Tôi', src: '/audio/music/When Mercy Looks at Me _ Khi Mercy Nhìn Về Tôi.mp3' },
  { id: 'where_mercy_finds_me___n_i_mer', title: 'Where Mercy Finds Me   Nơi Mercy Tìm Thấy Tôi', src: '/audio/music/Where Mercy Finds Me _ Nơi Mercy Tìm Thấy Tôi (1).mp3' },
  { id: 'where_mercy_finds_me___n_i_mer', title: 'Where Mercy Finds Me   Nơi Mercy Tìm Thấy Tôi', src: '/audio/music/Where Mercy Finds Me _ Nơi Mercy Tìm Thấy Tôi (2).mp3' },
  { id: 'where_mercy_finds_me___n_i_mer', title: 'Where Mercy Finds Me   Nơi Mercy Tìm Thấy Tôi', src: '/audio/music/Where Mercy Finds Me _ Nơi Mercy Tìm Thấy Tôi (3).mp3' },
  { id: 'where_mercy_finds_me___n_i_mer', title: 'Where Mercy Finds Me   Nơi Mercy Tìm Thấy Tôi', src: '/audio/music/Where Mercy Finds Me _ Nơi Mercy Tìm Thấy Tôi (4).mp3' },
  { id: 'where_mercy_finds_me___n_i_mer', title: 'Where Mercy Finds Me   Nơi Mercy Tìm Thấy Tôi', src: '/audio/music/Where Mercy Finds Me _ Nơi Mercy Tìm Thấy Tôi (5).mp3' },
  { id: 'where_mercy_finds_me___n_i_mer', title: 'Where Mercy Finds Me   Nơi Mercy Tìm Thấy Tôi', src: '/audio/music/Where Mercy Finds Me _ Nơi Mercy Tìm Thấy Tôi.mp3' },
  { id: 'mercy_blade_theme', title: 'mercy blade theme', src: '/audio/music/mercy_blade_theme.mp3' },
];
