export const lessons = [
  {
    id: 1,
    title: "Chào hỏi - Greetings",
    content: "Bonjour (Xin chào) / Salut (Chào) / Comment allez-vous? (Bạn khỏe không?) / Très bien, merci (Rất tốt, cảm ơn) / Au revoir (Tạm biệt)."
  },
  {
    id: 2,
    title: "Số đếm 1-10 - Numbers 1-10",
    content: "Un (1), Deux (2), Trois (3), Quatre (4), Cinq (5), Six (6), Sept (7), Huit (8), Neuf (9), Dix (10)."
  },
  {
    id: 3,
    title: "Màu sắc - Colors",
    content: "Rouge (đỏ), Bleu (xanh dương), Vert (xanh lá), Jaune (vàng), Noir (đen), Blanc (trắng), Orange (cam), Rose (hồng)."
  },
  {
    id: 4,
    title: "Các ngày trong tuần - Days of the week",
    content: "Lundi (Thứ Hai), Mardi (Thứ Ba), Mercredi (Thứ Tư), Jeudi (Thứ Năm), Vendredi (Thứ Sáu), Samedi (Thứ Bảy), Dimanche (Chủ Nhật)."
  },
  {
    id: 5,
    title: "Các tháng - Months",
    content: "Janvier (Tháng 1), Février (Tháng 2), Mars (Tháng 3), Avril (Tháng 4), Mai (Tháng 5), Juin (Tháng 6), Juillet (Tháng 7), Août (Tháng 8), Septembre (Tháng 9), Octobre (Tháng 10), Novembre (Tháng 11), Décembre (Tháng 12)."
  },
  {
    id: 6,
    title: "Thành viên gia đình - Family members",
    content: "La mère (mẹ), Le père (bố), La sœur (chị/em gái), Le frère (anh/em trai), La grand-mère (bà), Le grand-père (ông), La tante (cô/dì), L'oncle (chú/bác)."
  },
  {
    id: 7,
    title: "Động từ thường dùng - Common verbs",
    content: "Être (thì/là), Avoir (có), Aller (đi), Faire (làm), Dire (nói), Pouvoir (có thể), Vouloir (muốn), Savoir (biết)."
  },
  {
    id: 8,
    title: "Giới thiệu bản thân - Introduce yourself",
    content: "Je m'appelle [tên] (Tôi tên là...) / J'ai [tuổi] ans (Tôi ... tuổi) / Je viens du Vietnam (Tôi đến từ Việt Nam) / Je suis étudiant(e) (Tôi là sinh viên)."
  },
  {
    id: 9,
    title: "Hỏi đường - Asking for directions",
    content: "Où est la gare? (Nhà ga ở đâu?) / Tournez à droite (Rẽ phải) / Tournez à gauche (Rẽ trái) / Tout droit (Đi thẳng) / C'est loin? (Có xa không?)"
  },
  {
    id: 10,
    title: "Gọi món - Ordering food",
    content: "Je voudrais... (Tôi muốn...) / L'addition, s'il vous plaît (Xin hóa đơn) / Un café (Một cà phê) / Un verre d'eau (Một ly nước) / C'est délicieux! (Ngon quá!)"
  },
  {
    id: 11,
    title: "Thời tiết - Weather",
    content: "Il fait beau (Trời đẹp) / Il pleut (Trời mưa) / Il fait froid (Trời lạnh) / Il fait chaud (Trời nóng) / Quel temps fait-il? (Thời tiết thế nào?)"
  },
  {
    id: 12,
    title: "Giờ giấc - Time",
    content: "Quelle heure est-il? (Mấy giờ rồi?) / Il est une heure (1 giờ) / Il est deux heures (2 giờ) / Il est midi (12 giờ trưa) / Il est minuit (12 giờ đêm)."
  },
  {
    id: 13,
    title: "Ngày tháng - Dates",
    content: "Quelle est la date aujourd'hui? (Hôm nay là ngày mấy?) / Aujourd'hui c'est le [ngày] [tháng] [năm] (Hôm nay là ngày...) / Hier (Hôm qua) / Demain (Ngày mai)."
  },
  {
    id: 14,
    title: "Mua sắm - Shopping",
    content: "Combien ça coûte? (Cái này bao nhiêu?) / C'est trop cher (Đắt quá) / Avez-vous une taille plus grande? (Có size lớn hơn không?) / Je paie par carte (Tôi trả bằng thẻ)."
  },
  {
    id: 15,
    title: "Phương tiện giao thông - Transportation",
    content: "Le bus (xe buýt), Le train (tàu hỏa), Le métro (tàu điện ngầm), Le taxi (taxi), L'avion (máy bay), Le vélo (xe đạp)."
  },
  {
    id: 16,
    title: "Cảm xúc - Feelings",
    content: "Je suis heureux/heureuse (Tôi hạnh phúc) / Je suis triste (Tôi buồn) / J'ai peur (Tôi sợ) / Je suis fatigué(e) (Tôi mệt) / Je suis en colère (Tôi giận)."
  },
  {
    id: 17,
    title: "Bộ phận cơ thể - Body parts",
    content: "La tête (đầu), Les yeux (mắt), Le nez (mũi), La bouche (miệng), Les bras (cánh tay), Les jambes (chân), Les mains (tay)."
  },
  {
    id: 18,
    title: "Sở thích - Hobbies",
    content: "J'aime lire (Tôi thích đọc sách) / Je nage (Tôi bơi) / Je joue au football (Tôi chơi bóng đá) / Je dessine (Tôi vẽ) / Quels sont tes loisirs? (Sở thích của bạn là gì?)"
  },
  {
    id: 19,
    title: "Nghề nghiệp - Professions",
    content: "Médecin (bác sĩ), Enseignant(e) (giáo viên), Ingénieur (kỹ sư), Étudiant(e) (sinh viên), Commerçant(e) (thương nhân), Artiste (nghệ sĩ)."
  },
  {
    id: 20,
    title: "Cụm từ khẩn cấp - Emergency phrases",
    content: "Au secours! (Cứu tôi!) / Appelez une ambulance! (Gọi xe cứu thương!) / Je suis perdu(e) (Tôi bị lạc) / Aidez-moi, s'il vous plaît (Làm ơn giúp tôi) / Où est l'hôpital? (Bệnh viện ở đâu?)"
  },
{
    "id": 21,
    "title": "Passer un appel téléphonique",
    "content": "Vocabulaire:\ndécrocher (nhấc máy) [de-kro-shay]\ncomposer le numéro (quay số) [kom-po-zay luh noo-may-ro]\nsonner (đổ chuông) [so-nay]\nraccrocher (cúp máy) [ra-kro-shay]\nun répondeur (máy trả lời tự động) [uh ray-pon-deuhr]\nla tonalité (âm báo) [la to-na-lee-tay]\nun appel (cuộc gọi) [uh na-pel]\nla ligne (đường dây) [la leen-yuh]\npatienter (chờ đợi) [pa-syen-tay]\nlaisser un message (để lại lời nhắn) [le-say uh may-sazh]\n\nExemples:\nJe vais décrocher le téléphone. (Tôi sẽ nhấc máy.)\nTu peux composer son numéro ? (Bạn có thể quay số của anh ấy không?)\nLe téléphone sonne, qui est-ce ? (Điện thoại đang đổ chuông, ai vậy?)\nN'oublie pas de raccrocher après. (Đừng quên cúp máy sau đó nhé.)\nLaissez un message après le bip sonore. (Vui lòng để lại lời nhắn sau tiếng bíp.)\n\nDialogue:\n- A: Allô, bonjour. Puis-je parler à Madame Dupont ? (A lô, xin chào. Tôi có thể nói chuyện với bà Dupont không?)\n- B: Un instant, je vous la passe. (Một chút, tôi chuyển máy cho bà.)\n- A: Merci, j'attends. (Cảm ơn, tôi chờ.)\n- B: Désolée, la ligne est occupée. Voulez-vous rappeler ? (Xin lỗi, đường dây đang bận. Bạn có muốn gọi lại không?)\n\nExercices:\n1. Fill-blank: \"Avant de parler, il faut _______ le numéro.\"\n2. Matching: Associez les verbes aux définitions : décrocher / raccrocher / sonner.\n3. Translation: \"Please hold the line, I will transfer you.\""
  },
  {
    "id": 22,
    "title": "Écrire des emails",
    "content": "Vocabulaire:\nun email (thư điện tử) [uh ne-mayl]\nun objet (chủ đề) [uh nob-zhay]\nun destinataire (người nhận) [uh day-stee-nay-tuhr]\nun expéditeur (người gửi) [uh nek-spay-dee-tuhr]\nla pièce jointe (tệp đính kèm) [la pyes jwant]\njoindre (đính kèm) [jwand-ruh]\nle courriel (thư điện tử) [luh koo-ryel]\nrédiger (soạn thảo) [ray-dee-zhay]\nle corps du message (nội dung thư) [luh kor du may-sazh]\nenvoyer (gửi) [ahn-vway-yay]\n\nExemples:\nJ'ai reçu un email de mon collègue. (Tôi đã nhận được một email từ đồng nghiệp.)\nN'oublie pas de joindre le fichier PDF. (Đừng quên đính kèm tệp PDF.)\nQuel est l'objet de votre message ? (Chủ đề của thư bạn là gì?)\nJe vais rédiger une réponse ce soir. (Tôi sẽ soạn thảo câu trả lời tối nay.)\nVeuillez envoyer le courriel à tous les participants. (Vui lòng gửi email đến tất cả những người tham gia.)\n\nDialogue:\n- A: Salut, tu peux m'aider à rédiger un email professionnel ? (Chào, bạn có thể giúp tôi soạn một email chuyên nghiệp không?)\n- B: Bien sûr. Quel est l'objet ? (Tất nhiên. Chủ đề là gì?)\n- A: C'est pour une candidature. Je dois joindre mon CV. (Đó là cho một đơn xin việc. Tôi phải đính kèm CV.)\n- B: D'accord, commence par 'Objet : Candidature au poste de...' (Được rồi, hãy bắt đầu bằng 'Chủ đề: Ứng tuyển vị trí...')\n\nExercices:\n1. Fill-blank: \"Avant d'envoyer, vérifiez bien le _______ du destinataire.\"\n2. Matching: Associez les mots : objet / destinataire / pièce jointe / expéditeur.\n3. Translation: \"Please find attached the document you requested.\""
  },
  {
    "id": 23,
    "title": "À la banque",
    "content": "Vocabulaire:\nun compte bancaire (tài khoản ngân hàng) [uh kohnt bahn-kayr]\nun guichet (quầy giao dịch) [uh ghee-shay]\nun retrait (rút tiền) [uh ruh-tray]\nun dépôt (nộp tiền) [uh day-po]\nun chèque (séc) [uh shek]\nun relevé de compte (sao kê tài khoản) [uh ruh-luh-vay duh kohnt]\nun virement (chuyển khoản) [uh veer-mahn]\nle solde (số dư) [luh sold]\nun prêt (khoản vay) [uh pray]\nle taux d'intérêt (lãi suất) [luh toh dan-tay-ray]\n\nExemples:\nJe voudrais ouvrir un compte bancaire. (Tôi muốn mở một tài khoản ngân hàng.)\nPouvez-vous faire un retrait de 200 euros ? (Bạn có thể rút 200 euro không?)\nJ'ai besoin de mon relevé de compte. (Tôi cần sao kê tài khoản.)\nLe virement sera effectué demain. (Việc chuyển khoản sẽ được thực hiện vào ngày mai.)\nQuel est le taux d'intérêt pour un prêt immobilier ? (Lãi suất cho vay mua nhà là bao nhiêu?)\n\nDialogue:\n- A: Bonjour, je souhaite effectuer un dépôt. (Xin chào, tôi muốn nộp tiền.)\n- B: Oui, madame. Quel montant ? (Vâng, thưa bà. Số tiền là bao nhiêu?)\n- A: 500 euros en espèces. (500 euro tiền mặt.)\n- B: Très bien. Voici votre reçu. (Tốt lắm. Đây là biên nhận của bà.)\n\nExercices:\n1. Fill-blank: \"Pour retirer de l'argent, vous devez vous rendre au _______.\"\n2. Matching: Associez les mots : un compte / un retrait / un virement / le solde.\n3. Translation: \"I would like to check my account balance.\""
  },
  {
    "id": 24,
    "title": "À la poste",
    "content": "Vocabulaire:\nun timbre (tem) [uh tan-bruh]\nune enveloppe (phong bì) [oon ahn-vuh-lop]\nun colis (bưu kiện) [uh koh-lee]\nla poste (bưu điện) [la post]\nun courrier (thư tín) [uh koo-ryay]\nun facteur (người đưa thư) [uh fak-tuhr]\nun recommandé (thư bảo đảm) [uh ruh-koh-mahn-day]\nle poids (trọng lượng) [luh pwah]\naffranchir (dán tem) [a-frahn-sheer]\nun bureau de poste (bưu cục) [uh byoo-ro duh post]\n\nExemples:\nJ'ai besoin d'acheter des timbres. (Tôi cần mua tem.)\nVous pouvez envoyer ce colis en recommandé ? (Bạn có thể gửi bưu kiện này dạng bảo đảm không?)\nLe facteur passe tous les matins. (Người đưa thư đi qua mỗi sáng.)\nN'oubliez pas d'affranchir l'enveloppe. (Đừng quên dán tem lên phong bì.)\nQuel est le poids de votre courrier ? (Trọng lượng thư của bạn là bao nhiêu?)\n\nDialogue:\n- A: Bonjour, je voudrais envoyer une lettre au Vietnam. (Xin chào, tôi muốn gửi một bức thư đến Việt Nam.)\n- B: En voie aérienne ou maritime ? (Đường hàng không hay đường biển?)\n- A: Aérienne, s'il vous plaît. (Đường hàng không, làm ơn.)\n- B: D'accord. Voici le timbre à 1,30 euro. (Được rồi. Đây là tem 1,30 euro.)\n\nExercices:\n1. Fill-blank: \"Pour envoyer une lettre, il faut mettre un _______ sur l'enveloppe.\"\n2. Matching: Associez : un timbre / un colis / un recommandé / la poste.\n3. Translation: \"I would like to send this package by express mail.\""
  },
  {
    "id": 25,
    "title": "Louer un appartement",
    "content": "Vocabulaire:\nun appartement (căn hộ) [uh na-par-tuh-mahn]\nun bail (hợp đồng thuê) [uh by]\nun locataire (người thuê) [uh lo-ka-tuhr]\nun propriétaire (chủ nhà) [uh pro-pree-yay-tuhr]\nle loyer (tiền thuê) [luh lwa-yay]\nles charges (phí dịch vụ) [lay sharzh]\nla caution (tiền đặt cọc) [la ko-syon]\nun agence immobilière (công ty bất động sản) [uh na-zhahnss ee-mo-bee-lyayr]\nune pièce (phòng) [oon pyes]\nle préavis (thời gian báo trước) [luh pray-ah-vee]\n\nExemples:\nJe cherche un appartement à louer à Paris. (Tôi đang tìm căn hộ cho thuê ở Paris.)\nLe loyer est de 800 euros par mois, charges comprises. (Tiền thuê là 800 euro mỗi tháng, đã bao gồm phí dịch vụ.)\nIl faut verser une caution de deux mois. (Cần phải đặt cọc hai tháng.)\nLe propriétaire a signé le bail. (Chủ nhà đã ký hợp đồng thuê.)\nQuel est le préavis pour quitter l'appartement ? (Thời gian báo trước để rời căn hộ là bao lâu?)\n\nDialogue:\n- A: Bonjour, je suis intéressé par l'appartement que vous louez. (Xin chào, tôi quan tâm đến căn hộ ông cho thuê.)\n- B: Parfait. C'est un deux-pièces au troisième étage. (Tuyệt vời. Đó là căn hai phòng ở tầng ba.)\n- A: Quel est le loyer mensuel ? (Tiền thuê hàng tháng là bao nhiêu?)\n- B: 650 euros, charges non comprises. (650 euro, chưa bao gồm phí dịch vụ.)\n\nExercices:\n1. Fill-blank: \"Avant d'emménager, le locataire doit signer le _______.\"\n2. Matching: Associez les termes : loyer / caution / préavis / propriétaire.\n3. Translation: \"The apartment is available from the first of next month.\""
  },
  {
    "id": 26,
    "title": "Réclamations et retours",
    "content": "Vocabulaire:\nune réclamation (khiếu nại) [oon ray-kla-mah-syon]\nun retour (trả hàng) [uh ruh-toor]\nun remboursement (hoàn tiền) [uh rahn-boor-suh-mahn]\nun échange (đổi hàng) [uh nay-zhahnzh]\nun défaut (lỗi) [uh day-fo]\nle service client (dịch vụ khách hàng) [luh sayr-vees klee-ahn]\nle ticket de caisse (hóa đơn) [luh tee-kay duh kes]\nla garantie (bảo hành) [la ga-rahn-tee]\nun produit défectueux (sản phẩm lỗi) [uh pro-dwee day-fek-tuh-uh]\nun remboursement intégral (hoàn tiền toàn bộ) [uh rahn-boor-suh-mahn an-tay-gral]\n\nExemples:\nJe voudrais faire une réclamation concernant ce produit. (Tôi muốn khiếu nại về sản phẩm này.)\nPouvez-vous procéder au remboursement ? (Bạn có thể tiến hành hoàn tiền không?)\nL'article a un défaut, je souhaite un échange. (Món hàng có lỗi, tôi muốn đổi.)\nConservez le ticket de caisse pour le retour. (Giữ lại hóa đơn để trả hàng.)\nLa garantie est valable deux ans. (Bảo hành có hiệu lực hai năm.)\n\nDialogue:\n- A: Bonjour, j'ai acheté ce téléphone hier mais il ne s'allume pas. (Xin chào, tôi đã mua chiếc điện thoại này hôm qua nhưng nó không bật lên được.)\n- B: Je suis désolé. Avez-vous le ticket de caisse ? (Tôi xin lỗi. Bạn có hóa đơn không?)\n- A: Oui, le voici. (Có, đây ạ.)\n- B: Nous pouvons soit le réparer, soit vous rembourser. (Chúng tôi có thể sửa nó hoặc hoàn tiền cho bạn.)\n\nExercices:\n1. Fill-blank: \"Pour retourner un article, il faut présenter le _______.\"\n2. Matching: Associez : une réclamation / un échange / un remboursement / un défaut.\n3. Translation: \"The product is defective; I want a full refund.\""
  },
  {
    "id": 27,
    "title": "Donner des directions",
    "content": "Vocabulaire:\ntout droit (đi thẳng) [too drwah]\nà gauche (bên trái) [a gohsh]\nà droite (bên phải) [a drwaht]\nle carrefour (ngã tư) [luh ka-ruh-foor]\nle feu rouge (đèn đỏ) [luh fuh roozh]\nle rond-point (vòng xoay) [luh rohn-pwan]\nle panneau (biển báo) [luh pa-no]\nle trottoir (vỉa hè) [luh tro-twar]\ntraverser (băng qua) [tra-vayr-say]\nle coin (góc phố) [luh kwan]\n\nExemples:\nAllez tout droit jusqu'au feu rouge. (Hãy đi thẳng đến đèn đỏ.)\nTournez à gauche au carrefour. (Rẽ trái ở ngã tư.)\nLe supermarché se trouve au coin de la rue. (Siêu thị nằm ở góc phố.)\nTraversez la rue et continuez tout droit. (Băng qua đường và tiếp tục đi thẳng.)\nVous verrez un grand panneau bleu. (Bạn sẽ thấy một biển báo màu xanh lớn.)\n\nDialogue:\n- A: Excusez-moi, pour aller à la gare, s'il vous plaît ? (Xin lỗi, để đến ga tàu thì đi thế nào ạ?)\n- B: Prenez cette rue, puis tournez à droite au rond-point. (Đi theo đường này, sau đó rẽ phải ở vòng xoay.)\n- A: C'est loin ? (Có xa không?)\n- B: Non, à cinq minutes à pied. (Không, chỉ năm phút đi bộ.)\n\nExercices:\n1. Fill-blank: \"Pour aller au musée, vous devez _______ à gauche au premier feu.\"\n2. Matching: Associez les directions : tout droit / à gauche / à droite / traverser.\n3. Translation: \"Go straight ahead and then turn right at the traffic lights.\""
  },
  {
    "id": 28,
    "title": "Discuter des actualités",
    "content": "Vocabulaire:\nune actualité (tin tức thời sự) [oon nak-tua-lee-tay]\nun événement (sự kiện) [uh nay-vay-nahn]\nun journal (tờ báo) [uh zhoor-nal]\nun article (bài báo) [uh nar-teekl]\nun journaliste (nhà báo) [uh zhoor-na-leest]\nune information (thông tin) [oon an-for-ma-syon]\nle gouvernement (chính phủ) [luh goo-vayr-nuh-mahn]\nune élection (cuộc bầu cử) [oon ay-lek-syon]\nla politique (chính trị) [la po-lee-teek]\nles médias (phương tiện truyền thông) [lay may-dyah]\n\nExemples:\nAs-tu suivi l'actualité aujourd'hui ? (Bạn có theo dõi tin tức hôm nay không?)\nL'événement est très important pour le pays. (Sự kiện này rất quan trọng đối với đất nước.)\nJ'ai lu un article intéressant dans le journal. (Tôi đã đọc một bài báo thú vị trên báo.)\nLes journalistes enquêtent sur cette affaire. (Các nhà báo đang điều tra vụ việc này.)\nLes élections auront lieu le mois prochain. (Cuộc bầu cử sẽ diễn ra vào tháng sau.)\n\nDialogue:\n- A: Tu as entendu parler des manifestations ? (Bạn có nghe nói về các cuộc biểu tình không?)\n- B: Oui, j'ai vu ça aux informations. (Có, tôi đã thấy điều đó trên bản tin.)\n- A: C'est un sujet qui divise l'opinion. (Đó là một chủ đề gây chia rẽ dư luận.)\n- B: Je pense qu'il faut écouter les deux côtés. (Tôi nghĩ cần lắng nghe cả hai phía.)\n\nExercices:\n1. Fill-blank: \"Pour être informé, il faut regarder les _______ tous les jours.\"\n2. Matching: Associez : un événement / un journaliste / une élection / les médias.\n3. Translation: \"What is the latest news about the election?\""
  },
  {
    "id": 29,
    "title": "Différences culturelles",
    "content": "Vocabulaire:\nla culture (văn hóa) [la kool-tuhr]\nles coutumes (phong tục) [lay koo-tum]\nla politesse (phép lịch sự) [la po-lee-tes]\nles habitudes (thói quen) [lay za-bee-tud]\nle comportement (hành vi) [luh kohn-por-tuh-mahn]\nle repas (bữa ăn) [luh ruh-pah]\nle salut (lời chào) [luh sa-lu]\nle geste (cử chỉ) [luh zhest]\nla ponctualité (sự đúng giờ) [la pohnk-tua-lee-tay]\nles valeurs (giá trị) [lay va-luhr]\n\nExemples:\nEn France, la politesse est très importante. (Ở Pháp, phép lịch sự rất quan trọng.)\nLes habitudes alimentaires varient d'un pays à l'autre. (Thói quen ăn uống khác nhau giữa các nước.)\nIl faut faire la bise pour dire bonjour. (Cần hôn má để chào hỏi.)\nLa ponctualité n'est pas toujours respectée dans certaines cultures. (Sự đúng giờ không phải lúc nào cũng được tôn trọng trong một số nền văn hóa.)\nLes valeurs familiales sont fortes dans de nombreux pays. (Giá trị gia đình mạnh mẽ ở nhiều quốc gia.)\n\nDialogue:\n- A: Au Vietnam, on se serre la main ou on s'incline ? (Ở Việt Nam, người ta bắt tay hay cúi chào?)\n- B: On se serre la main généralement, mais on s'incline souvent pour les personnes âgées. (Thường thì bắt tay, nhưng thường cúi chào với người lớn tuổi.)\n- A: Intéressant. En France, on fait la bise entre amis. (Thú vị. Ở Pháp, bạn bè hôn má nhau.)\n- B: Oui, c'est une belle différence culturelle. (Vâng, đó là một khác biệt văn hóa đẹp.)\n\nExercices:\n1. Fill-blank: \"Dans certaines cultures, on évite de montrer la plante des _______ (pieds).\"\n2. Matching: Associez : la politesse / les coutumes / la ponctualité / le repas.\n3. Translation: \"In my culture, it is common to take off shoes before entering a home.\""
  },
  {
    "id": 30,
    "title": "Entretiens d'embauche",
    "content": "Vocabulaire:\nun entretien (buổi phỏng vấn) [uh nahn-truh-tyen]\nun recruteur (người tuyển dụng) [uh ruh-kroo-tuhr]\nun candidat (ứng viên) [uh kahn-dee-da]\nle CV (sơ yếu lý lịch) [luh say-vay]\nla lettre de motivation (thư xin việc) [la let-ruh duh mo-tee-va-syon]\nles compétences (kỹ năng) [lay kohn-pay-tahnss]\nl'expérience (kinh nghiệm) [lek-spay-ryahnss]\nle poste (vị trí) [luh post]\nles qualités (phẩm chất) [lay ka-lee-tay]\nles défauts (điểm yếu) [lay day-fo]\n\nExemples:\nJ'ai un entretien d'embauche demain matin. (Tôi có buổi phỏng vấn xin việc vào sáng mai.)\nLe recruteur m'a posé des questions sur mes compétences. (Người tuyển dụng đã hỏi tôi về kỹ năng.)\nN'oubliez pas d'apporter votre CV et votre lettre de motivation. (Đừng quên mang theo CV và thư xin việc.)\nParlez de votre expérience professionnelle. (Hãy nói về kinh nghiệm làm việc của bạn.)\nQualités et défauts : soyez honnête. (Điểm mạnh và điểm yếu: hãy thành thật.)\n\nDialogue:\n- A: Bonjour, je suis le recruteur. Parlez-moi de vous. (Xin chào, tôi là người tuyển dụng. Hãy nói về bạn.)\n- B: Bonjour, je suis diplômé en marketing et j'ai trois ans d'expérience. (Xin chào, tôi tốt nghiệp ngành marketing và có ba năm kinh nghiệm.)\n- A: Quelles sont vos principales qualités ? (Những phẩm chất chính của bạn là gì?)\n- B: Je suis organisé, ponctuel et j'aime travailler en équipe. (Tôi có tổ chức, đúng giờ và thích làm việc nhóm.)\n\nExercices:\n1. Fill-blank: \"Avant l'entretien, préparez votre _______ et votre lettre de motivation.\"\n2. Matching: Associez : le recruteur / le candidat / les compétences / l'expérience.\n3. Translation: \"I am flexible and can work under pressure.\""
  },
{
  id: 31,
  title: "Réunions d'affaires",
  content: "Vocabulaire:\nordre du jour (chương trình nghị sự) [ɔʁdʁ dy ʒuʁ]\nparticipant (người tham dự) [paʁtisipɑ̃]\nprojet (dự án) [pʁɔʒɛ]\npoint (điểm, mục) [pwɛ̃]\ndécision (quyết định) [desizjɔ̃]\ncompte rendu (biên bản) [kɔ̃t ʁɑ̃dy]\nobjectif (mục tiêu) [ɔbjɛktif]\ndélai (thời hạn) [delɛ]\nintervenant (diễn giả) [ɛ̃tɛʁvənɑ̃]\nordre du jour (chương trình nghị sự) [ɔʁdʁ dy ʒuʁ]\n\nExemples:\nNous allons commencer la réunion par le premier point. (Chúng ta sẽ bắt đầu cuộc họp với mục đầu tiên.)\nQui prendra les notes aujourd'hui ? (Ai sẽ ghi chép hôm nay?)\nLe projet doit être livré avant le délai fixé. (Dự án phải được bàn giao trước thời hạn đã định.)\nPouvez-vous envoyer le compte rendu à tous les participants ? (Anh/chị có thể gửi biên bản cho tất cả người tham dự không?)\nL'objectif de cette réunion est de finaliser le budget. (Mục tiêu của cuộc họp này là hoàn thiện ngân sách.)\n\nDialogue:\n- A: Bonjour à tous, passons au point 3 de l'ordre du jour. (Chào mọi người, chúng ta chuyển sang mục 3 của chương trình nghị sự.)\n- B: D'accord, j'ai une mise à jour sur le projet marketing. (Được rồi, tôi có một cập nhật về dự án marketing.)\n- A: Parfait, pouvez-vous nous donner les grandes lignes ? (Tuyệt vời, anh/chị có thể cho chúng tôi biết những nét chính không?)\n- B: Bien sûr, nous avons avancé sur le budget et les délais. (Tất nhiên, chúng tôi đã tiến triển về ngân sách và thời hạn.)\n\nExercices:\n1. Fill-blank: Le _______ (compte rendu / projet) de la réunion sera envoyé par email.\n2. Matching: associez chaque mot à sa définition : 1. ordre du jour a) personne qui participe ; 2. participant b) document résumant la réunion ; 3. compte rendu c) liste des sujets à discuter.\n3. Translation: The deadline for the project is next Friday. (Traduisez en français.)"
},
{
  id: 32,
  title: "Faire des présentations",
  content: "Vocabulaire:\npréparation (sự chuẩn bị) [pʁepaʁasjɔ̃]\ndiapositive (slide) [djapozitiv]\npublic (khán giả) [pyblik]\ncontenu (nội dung) [kɔ̃təny]\nconférencier (diễn giả) [kɔ̃feʁɑ̃sje]\nintroduction (phần giới thiệu) [ɛ̃tʁodyksjɔ̃]\nconclusion (kết luận) [kɔ̃klyzjɔ̃]\ngraphique (biểu đồ) [ɡʁafik]\ndonnées (dữ liệu) [dɔne]\nquestion (câu hỏi) [kɛstjɔ̃]\n\nExemples:\nPermettez-moi de me présenter avant de commencer. (Cho phép tôi tự giới thiệu trước khi bắt đầu.)\nJe vais structurer ma présentation en trois parties. (Tôi sẽ cấu trúc bài thuyết trình của mình thành ba phần.)\nCe graphique montre l'évolution des ventes. (Biểu đồ này cho thấy sự tiến triển của doanh số.)\nY a-t-il des questions à la fin ? (Có câu hỏi nào ở cuối không?)\nJe vous remercie de votre attention. (Cảm ơn sự chú ý của quý vị.)\n\nDialogue:\n- A: Bonjour, je suis ravi de vous présenter notre nouveau projet. (Xin chào, tôi rất vui được trình bày dự án mới của chúng tôi.)\n- B: Pouvez-vous commencer par les objectifs ? (Anh có thể bắt đầu bằng các mục tiêu không?)\n- A: Bien sûr. Tout d'abord, voici le contexte. (Tất nhiên. Trước hết, đây là bối cảnh.)\n- B: Très clair, continuez. (Rất rõ ràng, tiếp tục đi.)\n\nExercices:\n1. Fill-blank: La _______ (conclusion / introduction) doit résumer les points clés.\n2. Matching: associez : 1. diapositive a) personne qui présente ; 2. public b) support visuel ; 3. conférencier c) auditoire.\n3. Translation: I need to prepare my slides for the presentation. (Traduisez en français.)"
},
{
  id: 33,
  title: "Négocier",
  content: "Vocabulaire:\ncompromis (sự thỏa hiệp) [kɔ̃pʁɔmi]\nproposition (đề xuất) [pʁɔpozisjɔ̃]\ncontre-offre (lời đề nghị phản hồi) [kɔ̃tʁ ɔfʁ]\nconcession (nhượng bộ) [kɔ̃sesjɔ̃]\naccord (thỏa thuận) [akɔʁ]\ndésaccord (bất đồng) [dezakɔʁ]\ncondition (điều kiện) [kɔ̃disjɔ̃]\npriorité (ưu tiên) [pʁijɔʁite]\nargument (lý lẽ) [aʁɡymɑ̃]\nmarge (biên độ, lợi nhuận) [maʁʒ]\n\nExemples:\nNous devons trouver un compromis acceptable pour les deux parties. (Chúng ta phải tìm một sự thỏa hiệp chấp nhận được cho cả hai bên.)\nVotre contre-offre est trop élevée pour nous. (Lời đề nghị phản hồi của anh quá cao đối với chúng tôi.)\nSi vous réduisez le prix, nous augmenterons la commande. (Nếu anh giảm giá, chúng tôi sẽ tăng đơn hàng.)\nJe suis d'accord sur le principe, mais pas sur les conditions. (Tôi đồng ý về nguyên tắc, nhưng không đồng ý về các điều kiện.)\nPouvons-nous discuter de la marge bénéficiaire ? (Chúng ta có thể thảo luận về biên lợi nhuận không?)\n\nDialogue:\n- A: Votre prix initial est trop élevé. Pouvez-vous faire une concession ? (Giá ban đầu của anh quá cao. Anh có thể nhượng bộ không?)\n- B: Nous pouvons baisser de 5% si vous commandez au moins 100 unités. (Chúng tôi có thể giảm 5% nếu anh đặt ít nhất 100 đơn vị.)\n- A: C'est un bon début, mais j'aimerais 10% de réduction. (Đó là khởi đầu tốt, nhưng tôi muốn giảm 10%.)\n- B: 7% maximum, c'est notre dernier mot. (Tối đa 7%, đó là lời cuối cùng của chúng tôi.)\n\nExercices:\n1. Fill-blank: Pour parvenir à un ______ (accord / désaccord), il faut parfois faire des concessions.\n2. Matching: 1. compromis a) proposition en réponse ; 2. contre-offre b) solution mutuellement acceptable ; 3. concession c) renoncement partiel.\n3. Translation: We need to negotiate the terms of the contract. (Traduisez en français.)"
},
{
  id: 34,
  title: "Réseaux sociaux",
  content: "Vocabulaire:\npublication (bài đăng) [pyblikasjɔ̃]\nabonné (người theo dõi) [abɔne]\nlike (lượt thích) [lajk]\npartager (chia sẻ) [paʁtaʒe]\ncommentaire (bình luận) [kɔmɑ̃tɛʁ]\nhashtag (thẻ) [aʃtaɡ]\nfil d'actualité (bảng tin) [fil daktɥalite]\nprofil (hồ sơ) [pʁɔfil]\nmessage privé (tin nhắn riêng) [mesaʒ pʁive]\ninfluenceur (người có ảnh hưởng) [ɛ̃flyɑ̃sœʁ]\n\nExemples:\nJ'ai partagé ta publication sur mon fil d'actualité. (Tôi đã chia sẻ bài đăng của bạn lên bảng tin của tôi.)\nCet influenceur a beaucoup d'abonnés. (Người có ảnh hưởng này có rất nhiều người theo dõi.)\nPense à utiliser des hashtags pertinents. (Nhớ sử dụng các thẻ phù hợp.)\nJ'ai reçu un message privé de la part du service client. (Tôi đã nhận được một tin nhắn riêng từ bộ phận dịch vụ khách hàng.)\nLes commentaires sous la photo sont très positifs. (Các bình luận dưới bức ảnh rất tích cực.)\n\nDialogue:\n- A: As-tu vu le post de l'entreprise sur LinkedIn ? (Bạn đã xem bài đăng của công ty trên LinkedIn chưa?)\n- B: Oui, je l'ai aimé et partagé. (Rồi, tôi đã thích và chia sẻ nó.)\n- A: Parfait, ça augmente notre visibilité. (Tuyệt vời, điều đó tăng tầm nhìn của chúng ta.)\n- B: N'oublie pas d'ajouter des hashtags. (Đừng quên thêm các thẻ.)\n\nExercices:\n1. Fill-blank: Pour toucher plus de monde, utilise des _______ (hashtags / likes) populaires.\n2. Matching: 1. abonné a) contenu publié ; 2. publication b) personne qui suit ; 3. commentaire c) réaction écrite.\n3. Translation: I don't like to share personal information on social media. (Traduisez en français.)"
},
{
  id: 35,
  title: "Problèmes environnementaux",
  content: "Vocabulaire:\nréchauffement climatique (sự nóng lên toàn cầu) [ʁeʃofmɑ̃ klimatik]\nénergie renouvelable (năng lượng tái tạo) [eneʁʒi ʁənuvlabl]\npollution (ô nhiễm) [pɔlysjɔ̃]\ndéchet (rác thải) [deʃɛ]\nrecyclage (tái chế) [ʁəsiklaʒ]\nbiodiversité (đa dạng sinh học) [bjo diveʁsite]\nécosystème (hệ sinh thái) [ekɔsistɛm]\ndéforestation (phá rừng) [defɔʁɛstasjɔ̃]\nempreinte carbone (dấu chân carbon) [ɑ̃pʁɛ̃t kaʁbɔn]\ndurable (bền vững) [dyʁabl]\n\nExemples:\nLe réchauffement climatique est un problème majeur. (Sự nóng lên toàn cầu là một vấn đề lớn.)\nIl faut favoriser les énergies renouvelables. (Cần ưu tiên các năng lượng tái tạo.)\nNous devons réduire notre empreinte carbone. (Chúng ta phải giảm dấu chân carbon của mình.)\nLe recyclage permet de limiter les déchets. (Tái chế giúp hạn chế rác thải.)\nLa déforestation menace la biodiversité. (Phá rừng đe dọa đa dạng sinh học.)\n\nDialogue:\n- A: Que penses-tu de la pollution plastique dans les océans ? (Bạn nghĩ gì về ô nhiễm nhựa trong đại dương?)\n- B: C'est alarmant. Il faut agir rapidement. (Thật đáng báo động. Cần hành động nhanh chóng.)\n- A: Je suis d'accord. Réduire l'usage du plastique est essentiel. (Tôi đồng ý. Giảm sử dụng nhựa là thiết yếu.)\n- B: Et promouvoir le recyclage et les alternatives durables. (Và thúc đẩy tái chế và các giải pháp thay thế bền vững.)\n\nExercices:\n1. Fill-blank: L'_______ (empreinte carbone / écosystème) mesure l'impact sur le climat.\n2. Matching: 1. recyclage a) transformation des déchets ; 2. pollution b) altération de l'environnement ; 3. durable c) qui peut durer dans le temps.\n3. Translation: We must protect the environment for future generations. (Traduisez en français.)"
},
{
  id: 36,
  title: "Exprimer des opinions",
  content: "Vocabulaire:\nà mon avis (theo ý kiến của tôi) [a mɔn avi]\nselon moi (theo tôi) [səlɔ̃ mwa]\nje pense que (tôi nghĩ rằng) [ʒə pɑ̃s kə]\nje crois que (tôi tin rằng) [ʒə kʁwa kə]\npersonnellement (cá nhân tôi) [pɛʁsɔnɛlmɑ̃]\nje suis d'avis que (tôi đồng ý rằng) [ʒə sɥi davi kə]\nil me semble que (đối với tôi dường như) [il mə sɑ̃bl kə]\nje trouve que (tôi thấy rằng) [ʒə tʁuv kə]\nà mon sens (theo quan điểm của tôi) [a mɔ̃ sɑ̃s]\nje dirais que (tôi sẽ nói rằng) [ʒə diʁɛ kə]\n\nExemples:\nÀ mon avis, cette décision est risquée. (Theo ý kiến của tôi, quyết định này là rủi ro.)\nPersonnellement, je préfère travailler en équipe. (Cá nhân tôi, tôi thích làm việc nhóm hơn.)\nJe pense que le projet devrait être reporté. (Tôi nghĩ rằng dự án nên được hoãn lại.)\nIl me semble que vous avez oublié un point important. (Đối với tôi dường như anh đã quên một điểm quan trọng.)\nJe trouve que cette solution est la meilleure. (Tôi thấy giải pháp này là tốt nhất.)\n\nDialogue:\n- A: Que penses-tu de la nouvelle politique de l'entreprise ? (Bạn nghĩ gì về chính sách mới của công ty?)\n- B: Personnellement, je trouve qu'elle est trop stricte. (Cá nhân tôi thấy nó quá nghiêm ngặt.)\n- A: À mon avis, c'est nécessaire pour améliorer la productivité. (Theo ý kiến của tôi, nó cần thiết để cải thiện năng suất.)\n- B: Je ne suis pas d'accord. Il faudrait l'assouplir. (Tôi không đồng ý. Nên nới lỏng nó.)\n\nExercices:\n1. Fill-blank: ______ (Selon moi / Personnellement) dit-on pour exprimer un point de vue personnel.\n2. Matching: 1. je crois que a) opinion modeste ; 2. à mon avis b) opinion forte ; 3. il me semble que c) opinion hésitante.\n3. Translation: In my opinion, this is the best solution. (Traduisez en français.)"
},
{
  id: 37,
  title: "Faire des suggestions",
  content: "Vocabulaire:\nproposer (đề xuất) [pʁɔpoze]\nrecommander (khuyên, giới thiệu) [ʁəkɔmɑ̃de]\nsuggérer (gợi ý) [syɡʒeʁe]\npourquoi ne pas...? (tại sao không...?) [puʁkwa nə pa]\net si on...? (vậy nếu chúng ta...?) [e si ɔ̃]\nje suggère que (tôi gợi ý rằng) [ʒə syɡʒɛʁ kə]\nil serait bon de (sẽ tốt nếu) [il səʁɛ bɔ̃ də]\none pourrait (chúng ta có thể) [ɔn puʁɛ]\nje propose de (tôi đề xuất) [ʒə pʁɔpoz də]\nune idée (một ý tưởng) [yn ide]\n\nExemples:\nJe propose de commencer par une réunion de briefing. (Tôi đề xuất bắt đầu bằng một cuộc họp giao ban.)\nPourquoi ne pas organiser un atelier ? (Tại sao không tổ chức một buổi hội thảo?)\nEt si on essayait une nouvelle méthode ? (Vậy nếu chúng ta thử một phương pháp mới thì sao?)\nJe suggère que nous invitions un expert. (Tôi gợi ý rằng chúng ta mời một chuyên gia.)\nIl serait bon de préparer un plan B. (Sẽ tốt nếu chuẩn bị một kế hoạch B.)\n\nDialogue:\n- A: Nous avons un problème de délais. Que proposes-tu ? (Chúng ta có vấn đề về thời hạn. Bạn đề xuất gì?)\n- B: Et si on déléguait certaines tâches ? (Vậy nếu chúng ta ủy thác một số nhiệm vụ?)\n- A: Bonne idée. Je propose de contacter un freelance. (Ý kiến hay. Tôi đề xuất liên hệ một freelancer.)\n- B: D'accord, et on pourrait aussi revoir le planning. (Đồng ý, và chúng ta cũng có thể xem lại lịch trình.)\n\nExercices:\n1. Fill-blank: _______ (Pourquoi ne pas / Il serait bon de) + infinitif pour faire une suggestion.\n2. Matching: 1. proposer a) donner une idée ; 2. recommander b) conseiller fortement ; 3. suggérer c) avancer une option.\n3. Translation: I suggest we take a break. (Traduisez en français.)"
},
{
  id: 38,
  title: "S'excuser et donner des excuses",
  content: "Vocabulaire:\ns'excuser (xin lỗi) [sɛkskyze]\npardon (xin lỗi) [paʁdɔ̃]\nexcusez-moi (xin lỗi tôi) [ɛkskyze mwa]\nje suis désolé(e) (tôi xin lỗi) [ʒə sɥi dezɔle]\nje vous demande pardon (tôi xin anh/chị tha lỗi) [ʒə vu dəmɑ̃d paʁdɔ̃]\nce n'est pas de ma faute (đó không phải lỗi của tôi) [sə nɛ pa də ma fot]\nil y a eu un malentendu (đã có sự hiểu lầm) [il ja y œ̃ malɑ̃tɑ̃dy]\nje regrette (tôi rất tiếc) [ʒə ʁəɡʁɛt]\nveiller à (chú ý để) [veje a]\nfaire attention (chú ý) [fɛʁ atɑ̃sjɔ̃]\n\nExemples:\nJe suis désolé pour le retard. (Tôi xin lỗi vì sự chậm trễ.)\nExcusez-moi, je n'ai pas reçu votre email. (Xin lỗi, tôi đã không nhận được email của anh.)\nJe vous demande pardon pour cette erreur. (Tôi xin anh/chị tha lỗi cho lỗi này.)\nCe n'est pas de ma faute, le système était en panne. (Đó không phải lỗi của tôi, hệ thống đã bị hỏng.)\nJe regrette de ne pas avoir pu venir à la réunion. (Tôi rất tiếc đã không thể đến cuộc họp.)\n\nDialogue:\n- A: Je suis désolé d'être en retard, le trafic était terrible. (Tôi xin lỗi vì đến muộn, giao thông thật tệ.)\n- B: Ce n'est pas grave, mais veillez à être à l'heure la prochaine fois. (Không sao, nhưng lần sau hãy chú ý đến đúng giờ.)\n- A: Oui, je ferai attention. Merci de votre compréhension. (Vâng, tôi sẽ chú ý. Cảm ơn sự thông cảm của anh.)\n- B: D'accord, commençons la réunion. (Được rồi, chúng ta bắt đầu cuộc họp.)\n\nExercices:\n1. Fill-blank: Pour s'excuser formellement, on dit : _______ (Je suis désolé / Pardon) ou _______ (Je vous demande pardon / Ce n'est pas de ma faute).\n2. Matching: 1. s'excuser a) présenter des regrets ; 2. excuse b) raison donnée ; 3. pardonner c) ne pas en vouloir.\n3. Translation: I apologize for the inconvenience. (Traduisez en français.)"
},
{
  id: 39,
  title: "Donner des conseils",
  content: "Vocabulaire:\nconseiller (khuyên) [kɔ̃seje]\nrecommander (giới thiệu, khuyên) [ʁəkɔmɑ̃de]\nje te conseille de (tôi khuyên bạn nên) [ʒə tə kɔ̃sɛj də]\nil faudrait (cần) [il fodʁɛ]\nvous devriez (anh/chị nên) [vu dəvʁje]\nà ta place (ở vị trí của bạn) [a ta plas]\nle mieux serait (tốt nhất là) [lə mjø səʁɛ]\nun bon conseil (một lời khuyên tốt) [œ̃ bɔ̃ kɔ̃sɛj]\nsuivre un conseil (theo lời khuyên) [sɥivʁ œ̃ kɔ̃sɛj]\ndéconseiller (không khuyên) [dekɔ̃seje]\n\nExemples:\nJe te conseille de prendre des notes pendant la réunion. (Tôi khuyên bạn nên ghi chép trong cuộc họp.)\nÀ ta place, j'accepterais cette offre. (Ở vị trí của bạn, tôi sẽ chấp nhận lời đề nghị này.)\nVous devriez consulter un spécialiste. (Anh nên tham khảo ý kiến chuyên gia.)\nLe mieux serait de préparer un dossier complet. (Tốt nhất là chuẩn bị một hồ sơ đầy đủ.)\nJe déconseille de prendre une décision trop vite. (Tôi không khuyên bạn đưa ra quyết định quá nhanh.)\n\nDialogue:\n- A: J'hésite à postuler pour ce poste. (Tôi đang phân vân có nên nộp đơn cho vị trí này không.)\n- B: À ta place, je le ferais. Le salaire est attractif. (Ở vị trí của bạn, tôi sẽ làm. Lương hấp dẫn.)\n- A: Oui, mais les horaires sont flexibles, c'est un bon point. (Vâng, nhưng giờ làm linh hoạt, đó là điểm tốt.)\n- B: Alors je te conseille de postuler. (Vậy tôi khuyên bạn nên nộp đơn.)\n\nExercices:\n1. Fill-blank: _______ (Vous devriez / À ta place) s'utilise pour un conseil à une personne que l'on vouvoie.\n2. Matching: 1. conseiller a) dire ce qu'il faut faire ; 2. recommander b) appuyer une suggestion ; 3. déconseiller c) dire de ne pas faire.\n3. Translation: I advise you to be careful. (Traduisez en français.)"
},
{
  id: 40,
  title: "Décrire des expériences",
  content: "Vocabulaire:\nexpérience (kinh nghiệm) [ɛkspeʁjɑ̃s]\nvivre (trải qua) [vivʁ]\nressentir (cảm nhận) [ʁəsɑ̃tiʁ]\nse souvenir (nhớ lại) [sə suvniʁ]\nincroyable (không thể tin được) [ɛ̃kʁwajabl]\ninoubliable (không thể quên) [inublijabl]\néprouvant (gian nan, thử thách) [epʁuvɑ̃]\narricher (làm giàu) [aʁiʃe]\ntirer des leçons (rút ra bài học) [tiʁe de le sɔ̃]\nse rappeler (nhớ lại) [sə ʁaple]\n\nExemples:\nJ'ai vécu une expérience incroyable lors de mon voyage au Vietnam. (Tôi đã trải qua một trải nghiệm không thể tin được trong chuyến đi đến Việt Nam.)\nJe me souviens de ce moment inoubliable. (Tôi nhớ khoảnh khắc khó quên đó.)\nCette mission était très éprouvante mais enrichissante. (Nhiệm vụ này rất gian nan nhưng bổ ích.)\nJ'ai tiré des leçons importantes de cet échec. (Tôi đã rút ra những bài học quan trọng từ thất bại này.)\nSe rappeler les détails de cette réunion est difficile. (Nhớ lại chi tiết của cuộc họp đó thật khó.)\n\nDialogue:\n- A: Raconte-moi ton expérience à l'étranger. (Hãy kể cho tôi nghe về trải nghiệm của bạn ở nước ngoài.)\n- B: C'était génial ! J'ai rencontré des gens formidables. (Thật tuyệt vời! Tôi đã gặp những người tuyệt vời.)\n- A: Qu'as-tu ressenti en découvrant une nouvelle culture ? (Bạn đã cảm thấy thế nào khi khám phá một nền văn hóa mới?)\n- B: Un peu perdu au début, mais très vite à l'aise. (Hơi lạc lõng lúc đầu, nhưng rất nhanh đã thoải mái.)\n\nExercices:\n1. Fill-blank: Une expérience _______ (inoubliable / éprouvante) reste gravée dans la mémoire.\n2. Matching: 1. vivre a) avoir un souvenir ; 2. se souvenir b) traverser une situation ; 3. ressentir c) éprouver une émotion.\n3. Translation: I have never had such a wonderful experience. (Traduisez en français.)"
},
{
  "id": 41,
  "title": "Comparer des options",
  "content": "Vocabulaire:\n1. comparer (so sánh) [kɔ̃.pa.ʁe]\n2. option (lựa chọn) [ɔp.sjɔ̃]\n3. préférable (ưa thích hơn) [pʁe.fe.ʁabl]\n4. avantage (lợi thế) [a.vɑ̃.taʒ]\n5. inconvénient (bất lợi) [ɛ̃.kɔ̃.ve.njɑ̃]\n6. similaire (tương tự) [si.mi.lɛʁ]\n7. différent (khác nhau) [di.fe.ʁɑ̃]\n8. supérieur (cao hơn) [sy.pe.ʁjœʁ]\n9. inférieur (thấp hơn) [ɛ̃.fe.ʁjœʁ]\n10. équivalent (tương đương) [e.ki.va.lɑ̃]\n\nExemples:\n1. Cette option est plus avantageuse que l'autre. (Lựa chọn này có lợi hơn lựa chọn kia.)\n2. Le prix est inférieur, mais la qualité est supérieure. (Giá thấp hơn nhưng chất lượng cao hơn.)\n3. Il faut comparer les avantages et les inconvénients avant de décider. (Cần so sánh ưu và nhược điểm trước khi quyết định.)\n4. Ces deux modèles sont équivalents en termes de performance. (Hai mẫu này tương đương về hiệu suất.)\n5. Je préfère la solution la plus économique. (Tôi thích giải pháp kinh tế nhất.)\n\nDialogue:\n- A: Entre l'appartement en ville et la maison en banlieue, qu'est-ce qui est préférable ? (Giữa căn hộ ở thành phố và ngôi nhà ở ngoại ô, cái nào tốt hơn?)\n- B: L'appartement est plus pratique pour le travail, mais la maison offre plus d'espace. (Căn hộ tiện hơn cho công việc, nhưng ngôi nhà rộng rãi hơn.)\n- A: Oui, mais le loyer en ville est beaucoup plus élevé. (Đúng, nhưng tiền thuê nhà ở thành phố cao hơn nhiều.)\n- B: Alors il faut peser le pour et le contre. (Vậy thì phải cân nhắc ưu và nhược điểm.)\n\nExercices:\n1. Fill-blank: Cette voiture est plus _______ que la mienne. (chère / cher)\n2. Matching: Reliez les mots à leur synonyme : 1. supérieur - a. meilleur ; 2. inférieur - b. pire ; 3. équivalent - c. égal.\n3. Translation: Dịch sang tiếng Việt : 'Comparer les options est essentiel avant d'acheter.'"
},
{
  "id": 42,
  "title": "Situations hypothétiques",
  "content": "Vocabulaire:\n1. hypothétique (giả định) [i.pɔ.te.tik]\n2. si (nếu) [si]\n3. condition (điều kiện) [kɔ̃.di.sjɔ̃]\n4. imaginer (tưởng tượng) [i.ma.ʒi.ne]\n5. possible (có thể) [pɔ.sibl]\n6. improbable (không chắc) [ɛ̃.pʁɔ.babl]\n7. aurait (sẽ có - conditional) [o.ʁɛ]\n8. pourrait (có thể - conditional) [pu.ʁɛ]\n9. souhaiter (mong muốn) [swɛ.te]\n10. rêve (giấc mơ) [ʁɛv]\n\nExemples:\n1. Si j'avais plus d'argent, je voyagerais autour du monde. (Nếu tôi có nhiều tiền hơn, tôi sẽ đi du lịch vòng quanh thế giới.)\n2. Il serait plus heureux s'il changeait de travail. (Anh ấy sẽ hạnh phúc hơn nếu đổi việc.)\n3. Dans une situation hypothétique, que ferais-tu ? (Trong một tình huống giả định, bạn sẽ làm gì?)\n4. Nous pourrions partir en vacances si nous avions le temps. (Chúng tôi có thể đi nghỉ nếu có thời gian.)\n5. J'aimerais que ce soit vrai. (Tôi ước điều đó là đúng.)\n\nDialogue:\n- A: Si tu gagnais au loto, que ferais-tu ? (Nếu bạn trúng số, bạn sẽ làm gì?)\n- B: J'achèterais une maison à la campagne. (Tôi sẽ mua một ngôi nhà ở nông thôn.)\n- A: Et si tu perdais tout ? (Còn nếu bạn mất hết thì sao?)\n- B: Ce serait un désastre, mais je recommencerais. (Đó sẽ là một thảm họa, nhưng tôi sẽ bắt đầu lại.)\n\nExercices:\n1. Fill-blank: Si je _______ (avoir) plus de temps, je t'______ (aider).\n2. Matching: Associez les phrases hypothétiques : 1. Si je pouvais - a. je le ferais ; 2. Si j'avais su - b. je serais venu ; 3. Si tu veux - c. viens avec moi.\n3. Translation: Dịch sang tiếng Việt : 'Dans une situation hypothétique, il faudrait réfléchir avant d'agir.'"
},
{
  "id": 43,
  "title": "Discours rapporté",
  "content": "Vocabulaire:\n1. discours rapporté (lời nói gián tiếp) [dis.kuʁ ʁa.pɔʁ.te]\n2. dire (nói) [diʁ]\n3. que (rằng) [kə]\n4. rapporteur (người thuật lại) [ʁa.pɔʁ.tœʁ]\n5. affirmer (khẳng định) [a.fiʁ.me]\n6. nier (phủ nhận) [nje]\n7. demander (hỏi) [də.mɑ̃.de]\n8. si (liệu rằng) [si]\n9. déclarer (tuyên bố) [de.kla.ʁe]\n10. paroles (lời nói) [pa.ʁɔl]\n\nExemples:\n1. Il a dit qu'il viendrait demain. (Anh ấy nói rằng anh ấy sẽ đến vào ngày mai.)\n2. Elle a demandé si j'avais fini mon travail. (Cô ấy hỏi liệu tôi đã hoàn thành công việc chưa.)\n3. Ils ont affirmé que la réunion était annulée. (Họ khẳng định cuộc họp đã bị hủy.)\n4. Le professeur a déclaré que l'examen serait difficile. (Giáo viên tuyên bố rằng kỳ thi sẽ khó.)\n5. Pierre m'a dit : « Je suis fatigué. » -> Pierre m'a dit qu'il était fatigué. (Pierre nói với tôi rằng anh ấy mệt.)\n\nDialogue:\n- A: Qu'est-ce qu'il a dit exactement ? (Anh ấy đã nói chính xác điều gì?)\n- B: Il a dit qu'il partait en vacances la semaine prochaine. (Anh ấy nói rằng anh ấy sẽ đi nghỉ vào tuần sau.)\n- A: Et elle, qu'a-t-elle répondu ? (Còn cô ấy, cô ấy trả lời thế nào?)\n- B: Elle a répondu qu'elle ne pouvait pas l'accompagner. (Cô ấy trả lời rằng cô ấy không thể đi cùng.)\n\nExercices:\n1. Fill-blank: Il a dit qu'il _______ (être) malade.\n2. Matching: Transformez au discours rapporté : 1. « Je viens demain. » -> a. Il a dit qu'il... ; 2. « As-tu fini ? » -> b. Il a demandé si... ; 3. « Ne pars pas ! » -> c. Il a ordonné de...\n3. Translation: Dịch sang tiếng Việt : 'Elle a affirmé que le projet était terminé.'"
},
{
  "id": 44,
  "title": "La voix passive",
  "content": "Vocabulaire:\n1. voix passive (thể bị động) [vwa pa.siv]\n2. actif (chủ động) [ak.tif]\n3. être (được) [ɛtʁ]\n4. par (bởi) [paʁ]\n5. sujet (chủ ngữ) [sy.ʒɛ]\n6. verbe (động từ) [vɛʁb]\n7. complément d'agent (bổ ngữ tác nhân) [kɔ̃.ple.mɑ̃ da.ʒɑ̃]\n8. transformer (biến đổi) [tʁɑ̃s.fɔʁ.me]\n9. construction (cấu trúc) [kɔ̃s.tʁyk.sjɔ̃]\n10. passif impersonnel (bị động vô nhân xưng) [pa.sif ɛ̃.pɛʁ.sɔ.nɛl]\n\nExemples:\n1. La lettre a été envoyée par Marie. (Bức thư đã được gửi bởi Marie.)\n2. Le gâteau est mangé par les enfants. (Cái bánh đang được ăn bởi bọn trẻ.)\n3. Cette maison a été construite en 1990. (Ngôi nhà này được xây vào năm 1990.)\n4. Les règles doivent être respectées. (Các quy tắc phải được tuân thủ.)\n5. Il est interdit de fumer ici. (Cấm hút thuốc ở đây - thể bị động vô nhân xưng.)\n\nDialogue:\n- A: Qui a peint ce tableau ? (Ai vẽ bức tranh này?)\n- B: Il a été peint par un artiste célèbre. (Nó được vẽ bởi một nghệ sĩ nổi tiếng.)\n- A: Et cette sculpture ? (Còn tác phẩm điêu khắc này?)\n- B: Elle a été réalisée par une jeune sculpteure. (Nó được thực hiện bởi một nhà điêu khắc trẻ.)\n\nExercices:\n1. Fill-blank: Le livre _______ (lire) par beaucoup de gens.\n2. Matching: Transformez de l'actif au passif : 1. Le chien mange la viande. -> a. La viande est mangée par le chien ; 2. Les ouvriers construisent la route. -> b. La route est construite par les ouvriers ; 3. Marie a peint le portrait. -> c. Le portrait a été peint par Marie.\n3. Translation: Dịch sang tiếng Việt : 'Les fenêtres ont été nettoyées par le service d'entretien.'"
},
{
  "id": 45,
  "title": "Les propositions relatives",
  "content": "Vocabulaire:\n1. proposition relative (mệnh đề quan hệ) [pʁɔ.po.zi.sjɔ̃ ʁə.la.tiv]\n2. pronom relatif (đại từ quan hệ) [pʁɔ.nɔ̃ ʁə.la.tif]\n3. qui (người mà) [ki]\n4. que (mà) [kə]\n5. dont (mà - sở hữu) [dɔ̃]\n6. lequel (cái mà) [lə.kɛl]\n7. où (nơi mà) [u]\n8. antécédent (tiền ngữ) [ɑ̃.te.se.dɑ̃]\n9. explicative (giải thích) [ɛk.spli.ka.tiv]\n10. déterminative (xác định) [de.tɛʁ.mi.na.tiv]\n\nExemples:\n1. L'homme qui parle est mon frère. (Người đàn ông đang nói là anh trai tôi.)\n2. Le livre que tu lis est intéressant. (Cuốn sách mà bạn đang đọc rất thú vị.)\n3. C'est un ami dont je te parlais. (Đó là một người bạn mà tôi đã nói với bạn.)\n4. La ville où je suis né est belle. (Thành phố nơi tôi sinh ra rất đẹp.)\n5. Voici la maison dans laquelle j'ai grandi. (Đây là ngôi nhà mà tôi đã lớn lên.)\n\nDialogue:\n- A: Connais-tu l'étudiant qui a gagné le concours ? (Bạn có biết sinh viên đã thắng cuộc thi không?)\n- B: Oui, c'est celui dont le père est professeur. (Có, đó là người mà cha làm giáo sư.)\n- A: Et la fille que tu as rencontrée hier ? (Còn cô gái bạn gặp hôm qua?)\n- B: Elle habite dans une maison qui a un grand jardin. (Cô ấy sống trong một ngôi nhà có vườn lớn.)\n\nExercices:\n1. Fill-blank: C'est le film _______ j'ai vu hier.\n2. Matching: Choisissez le bon pronom : 1. La personne ... parle - a. qui ; 2. Le livre ... tu as acheté - b. que ; 3. L'ami ... je te parle - c. dont.\n3. Translation: Dịch sang tiếng Việt : 'Le musée où nous sommes allés était magnifique.'"
},
{
  "id": 46,
  "title": "Les phrases conditionnelles",
  "content": "Vocabulaire:\n1. conditionnel (điều kiện) [kɔ̃.di.sjɔ.nɛl]\n2. si + présent (nếu + hiện tại) [si pʁe.zɑ̃]\n3. futur simple (tương lai đơn) [fy.tyʁ sɛ̃pl]\n4. imparfait (chưa hoàn thành) [ɛ̃.paʁ.fɛ]\n5. conditionnel présent (điều kiện hiện tại) [kɔ̃.di.sjɔ.nɛl pʁe.zɑ̃]\n6. plus-que-parfait (quá khứ hoàn thành) [plys.kə.paʁ.fɛ]\n7. conditionnel passé (điều kiện quá khứ) [kɔ̃.di.sjɔ.nɛl pa.se]\n8. hypothèse (giả thuyết) [i.pɔ.tɛz]\n9. réalisation (thực hiện) [ʁe.a.li.za.sjɔ̃]\n10. conséquence (hậu quả) [kɔ̃.se.kɑ̃s]\n\nExemples:\n1. Si tu étudies, tu réussiras. (Nếu bạn học, bạn sẽ thành công - loại 1.)\n2. Si j'avais de l'argent, j'achèterais une maison. (Nếu tôi có tiền, tôi sẽ mua một ngôi nhà - loại 2.)\n3. Si j'avais su, je serais venu. (Nếu tôi biết, tôi đã đến - loại 3.)\n4. Il viendrait s'il avait le temps. (Anh ấy sẽ đến nếu có thời gian.)\n5. Si tu veux, nous pourrions aller au cinéma. (Nếu bạn muốn, chúng ta có thể đi xem phim.)\n\nDialogue:\n- A: Si tu pouvais voyager, où irais-tu ? (Nếu bạn có thể đi du lịch, bạn sẽ đi đâu?)\n- B: J'irais au Japon. (Tôi sẽ đi Nhật Bản.)\n- A: Et si tu avais plus d'argent, que ferais-tu ? (Và nếu bạn có nhiều tiền hơn, bạn sẽ làm gì?)\n- B: Je ferais le tour du monde. (Tôi sẽ đi vòng quanh thế giới.)\n\nExercices:\n1. Fill-blank: Si j'_______ (avoir) du temps, je t'______ (aider).\n2. Matching: Associez les types : 1. Si présent + futur - a. Type 2 ; 2. Si imparfait + conditionnel présent - b. Type 1 ; 3. Si plus-que-parfait + conditionnel passé - c. Type 3.\n3. Translation: Dịch sang tiếng Việt : 'Si elle m'avait invité, je serais allé à la fête.'"
},
{
  "id": 47,
  "title": "Expressions idiomatiques",
  "content": "Vocabulaire:\n1. expression idiomatique (thành ngữ) [ɛk.spʁɛ.sjɔ̃ i.djɔ.ma.tik]\n2. coûter les yeux de la tête (đắt cắt cổ) [ku.te le.z‿jø də la tɛt]\n3. avoir le cafard (buồn chán) [a.vwaʁ lə ka.faʁ]\n4. poser un lapin (hẹn mà không đến) [po.ze ɛ̃ la.pɛ̃]\n5. tomber dans les pommes (ngất xỉu) [tɔ̃.be dɑ̃ le pɔm]\n6. mettre de l'eau dans son vin (dịu đi) [mɛtʁ də lo dɑ̃ sɔ̃ vɛ̃]\n7. faire la grasse matinée (ngủ nướng) [fɛʁ la ɡʁas ma.ti.ne]\n8. être dans le même bateau (cùng cảnh ngộ) [ɛtʁ dɑ̃ lə mɛm ba.to]\n9. donner sa langue au chat (chịu thua) [dɔ.ne sa lɑ̃ɡ o ʃa]\n10. en avoir plein le dos (chán ngấy) [ɑ̃.n‿a.vwaʁ plɛ̃ lə do]\n\nExemples:\n1. Cette robe coûte les yeux de la tête. (Cái váy này đắt cắt cổ.)\n2. Depuis qu'il est parti, elle a le cafard. (Từ khi anh ấy đi, cô ấy buồn chán.)\n3. Il m'a posé un lapin, je l'ai attendu une heure. (Anh ấy hẹn mà không đến, tôi đợi anh ấy một tiếng.)\n4. Après la mauvaise nouvelle, elle est tombée dans les pommes. (Sau tin xấu, cô ấy ngất xỉu.)\n5. Il faut mettre de l'eau dans son vin et accepter les compromis. (Cần phải dịu đi và chấp nhận thỏa hiệp.)\n\nDialogue:\n- A: Pourquoi es-tu fatigué ? (Sao bạn mệt vậy?)\n- B: J'ai fait la grasse matinée, mais je n'arrive pas à me réveiller. (Tôi ngủ nướng, nhưng không thể tỉnh táo.)\n- A: Allez, on est dans le même bateau, il faut travailler. (Thôi nào, chúng ta cùng cảnh ngộ, phải làm việc thôi.)\n- B: J'en ai plein le dos de ce projet. (Tôi chán ngấy dự án này rồi.)\n\nExercices:\n1. Fill-blank: Il m'a _______ , je l'ai attendu deux heures. (posé un lapin / donné sa langue au chat)\n2. Matching: Associez les expressions à leur sens : 1. Coûter les yeux de la tête - a. être très cher ; 2. Avoir le cafard - b. être triste ; 3. Tomber dans les pommes - c. s'évanouir.\n3. Translation: Dịch sang tiếng Việt : 'Ne donne pas ta langue au chat, continue à chercher.'"
},
{
  "id": 48,
  "title": "Argot et langage familier",
  "content": "Vocabulaire:\n1. argot (tiếng lóng) [aʁ.ɡo]\n2. dingo (điên khùng) [dɛ̃.ɡo]\n3. flic (cảnh sát) [flik]\n4. bosser (làm việc) [bɔ.se]\n5. bouffer (ăn) [bu.fe]\n6. pognon (tiền) [pɔ.ɲɔ̃]\n7. mec (gã, chàng) [mɛk]\n8. nana (cô nàng) [na.na]\n9. choper (bắt, lấy) [ʃɔ.pe]\n10. se barrer (chuồn, đi) [sə ba.ʁe]\n\nExemples:\n1. Ce mec est complètement dingo. (Gã đó hoàn toàn điên.)\n2. Je bosse depuis huit heures du matin. (Tôi làm việc từ tám giờ sáng.)\n3. On va bouffer au resto ? (Chúng ta sẽ ăn ở nhà hàng chứ?)\n4. Il a chopé une amende pour excès de vitesse. (Anh ấy bị phạt vì vượt quá tốc độ.)\n5. Il s'est barré sans payer. (Anh ấy chuồn mất không trả tiền.)\n\nDialogue:\n- A: T'as du pognon ? (Bạn có tiền không?)\n- B: Non, je suis fauché. (Không, tôi cháy túi.)\n- A: Alors on va se barrer d'ici, y a des flics. (Vậy thì chúng ta chuồn khỏi đây, có cảnh sát.)\n- B: D'accord, on bouffe ailleurs. (Được, chúng ta ăn ở chỗ khác.)\n\nExercices:\n1. Fill-blank: Arrête de _______ , tu vas te faire mal. (choper / bosser)\n2. Matching: Remplacez le mot familier par le mot standard : 1. bouffer - a. manger ; 2. flic - b. policier ; 3. mec - c. homme.\n3. Translation: Dịch sang tiếng Việt (familier) : 'Ce nana a chopé un super taf.'"
},
{
  "id": 49,
  "title": "Compétences de débat",
  "content": "Vocabulaire:\n1. débat (tranh luận) [de.ba]\n2. argument (lý lẽ) [aʁ.ɡy.mɑ̃]\n3. contre-argument (phản biện) [kɔ̃tʁ aʁ.ɡy.mɑ̃]\n4. convaincre (thuyết phục) [kɔ̃.vɛ̃kʁ]\n5. réfuter (bác bỏ) [ʁe.fy.te]\n6. opinion (ý kiến) [ɔ.pi.njɔ̃]\n7. point de vue (quan điểm) [pwɛ̃ də vy]\n8. modérateur (người điều phối) [mɔ.de.ʁa.tœʁ]\n9. conclusion (kết luận) [kɔ̃.kly.zjɔ̃]\n10. compromis (thỏa hiệp) [kɔ̃.pʁɔ.mi]\n\nExemples:\n1. Selon mon point de vue, l'éducation est prioritaire. (Theo quan điểm của tôi, giáo dục là ưu tiên.)\n2. Je réfute cet argument car les données sont fausses. (Tôi bác bỏ lý lẽ đó vì dữ liệu sai.)\n3. Pour convaincre, il faut des preuves solides. (Để thuyết phục, cần có bằng chứng vững chắc.)\n4. Le modérateur a donné la parole à chacun. (Người điều phối đã cho mỗi người phát biểu.)\n5. Après le débat, ils ont trouvé un compromis. (Sau cuộc tranh luận, họ đã tìm ra thỏa hiệp.)\n\nDialogue:\n- A: Je pense que la technologie nuit aux relations humaines. (Tôi nghĩ công nghệ gây hại cho quan hệ con người.)\n- B: Je ne suis pas d'accord. Elle permet de rester connectés. (Tôi không đồng ý. Nó cho phép giữ kết nối.)\n- A: Oui, mais elle réduit les interactions en face-à-face. (Đúng, nhưng nó làm giảm tương tác trực tiếp.)\n- B: Peut-être, mais on peut aussi l'utiliser pour organiser des rencontres. (Có thể, nhưng ta cũng có thể dùng nó để tổ chức các cuộc gặp.)\n\nExercices:\n1. Fill-blank: Il faut _______ les arguments de l'adversaire. (réfuter / convaincre)\n2. Matching: Reliez chaque terme à sa définition : 1. Débat - a. échange d'idées ; 2. Compromis - b. solution mutuelle ; 3. Modérateur - c. régulateur.\n3. Translation: Dịch sang tiếng Việt : 'Il est important de savoir écouter les autres opinions lors d'un débat.'"
},
{
  "id": 50,
  "title": "Révision générale finale",
  "content": "Vocabulaire:\n1. révision (ôn tập) [ʁe.vi.zjɔ̃]\n2. bilan (tổng kết) [bi.lɑ̃]\n3. grammaire (ngữ pháp) [ɡʁa.mɛʁ]\n4. conjugaison (chia động từ) [kɔ̃.ʒy.ɡɛ.zɔ̃]\n5. vocabulaire (từ vựng) [vɔ.ka.by.lɛʁ]\n6. expression (diễn đạt) [ɛk.spʁɛ.sjɔ̃]\n7. compréhension (hiểu) [kɔ̃.pʁe.ɑ̃.sjɔ̃]\n8. exercice (bài tập) [ɛɡ.zɛʁ.sis]\n9. progrès (tiến bộ) [pʁɔ.ɡʁɛ]\n10. confiance (tự tin) [kɔ̃.fjɑ̃s]\n\nExemples:\n1. Cette révision couvre tous les points importants. (Bài ôn tập này bao gồm tất cả các điểm quan trọng.)\n2. J'ai besoin de revoir la conjugaison des verbes irréguliers. (Tôi cần xem lại cách chia động từ bất quy tắc.)\n3. Le bilan de l'année est positif. (Tổng kết năm học rất tích cực.)\n4. Il faut pratiquer les expressions pour les mémoriser. (Cần thực hành các diễn đạt để ghi nhớ.)\n5. Avec ce cours, j'ai gagné en confiance. (Với khóa học này, tôi đã tự tin hơn.)\n\nDialogue:\n- A: Prêt pour l'examen final ? (Sẵn sàng cho kỳ thi cuối chưa?)\n- B: Pas vraiment, il y a trop de choses à réviser. (Chưa thực sự, có quá nhiều thứ phải ôn.)\n- A: Concentre-toi sur les points faibles que tu as notés. (Tập trung vào điểm yếu mà bạn đã ghi lại.)\n- B: Oui, et je vais refaire les exercices de grammaire. (Vâng, và tôi sẽ làm lại các bài tập ngữ pháp.)\n\nExercices:\n1. Fill-blank: Pour réussir l'examen, il faut _______ régulièrement. (réviser / ignorer)\n2. Matching: Reliez les sujets de révision aux leçons : 1. Comparer des options - a. Leçon 41 ; 2. Discours rapporté - b. Leçon 43 ; 3. Phrases conditionnelles - c. Leçon 46.\n3. Translation: Dịch sang tiếng Việt : 'La révision générale permet de consolider les connaissances acquises.'"
}
];