/**
 * Teacher Mercy — Encouragement Timing Decision Policy
 *
 * Decides WHEN Teacher Mercy should deliver encouragement/praise to the learner.
 * Encouragement is earned, specific, and timed — never generic "good job" fluff.
 *
 * This module layers ALONGSIDE correction timing (teacherMercyCorrectionTiming.ts),
 * suppression rules (suppressionRules.ts), and drill timing (drillTimingPolicy.ts).
 * It answers a different question:
 * "Given the learner's current state, recent performance, and session context,
 *  is NOW the right moment to encourage, or should we wait?"
 *
 * Design principles:
 *   1. Encouragement is earned, not automatic — praise only when there's
 *      genuine improvement worth acknowledging (R3 NO_FAKE_PRAISE).
 *   2. Timing matters — encouraging too soon after struggle dismisses the
 *      learner's feeling; too late loses the reinforcement moment.
 *   3. Specific beats generic — this module decides WHEN, not WHAT;
 *      the praise content is generated by specificPraise.ts.
 *   4. Learner-aware — shy learners need gentle encouragement spaced out;
 *      frustrated learners need acknowledgment before encouragement.
 *   5. Session rhythm — encouragement is part of the teaching cadence,
 *      not an interruption; too much dilutes its power.
 *   6. Vietnamese-first — all rationale is produced in Vietnamese for the
 *      learner-facing layer; English rationale is for telemetry.
 *
 * Pure functions — no I/O, no side effects, deterministic.
 */

import type { LearnerConfidence } from "./teacherMercyCorrectionTiming";

// ─── Encouragement Decision Types ──────────────────────────────────────────

/**
 * The three encouragement timing decisions Teacher Mercy can make.
 *
 * ENCOURAGE_NOW    — deliver specific encouragement right now, in this turn.
 * ENCOURAGE_SOON    — queue encouragement for ~2 turns from now; let the
 *                     current moment breathe before praising.
 * NO_ENCOURAGE      — not the right time; continue normal interaction.
 */
export type EncouragementDecision =
  | "ENCOURAGE_NOW"
  | "ENCOURAGE_SOON"
  | "NO_ENCOURAGE";

/**
 * The type of positive signal that triggered the encouragement consideration.
 * This informs what the praise should be about — not just "good job" but
 * "you fixed that subject-verb agreement" or "nice recovery after struggling."
 */
export type EncouragementSignal =
  | "significant_improvement"
  | "struggle_recovery"
  | "self_correction_success"
  | "correct_new_pattern"
  | "beginner_basic_success"
  | "sustained_accuracy"
  | "none";

/**
 * Input context for the encouragement timing decision.
 */
export type EncouragementTimingInput = {
  /** Whether the learner's current turn shows significant improvement over recent turns. */
  hasSignificantImprovement: boolean;
  /** The type of positive signal detected in this turn. */
  encouragementSignal: EncouragementSignal;
  /** How many turns have passed since the last encouragement was delivered (or Infinity if none yet). */
  turnsSinceLastEncouragement: number;
  /** Total encouragements delivered in this session so far. */
  encouragementsThisSession: number;
  /** Whether the learner was struggling in the previous 1–2 turns (multiple corrections, shy/frustrated signals). */
  wasStruggling: boolean;
  /** The learner's apparent confidence level. */
  learnerConfidence: LearnerConfidence;
  /** Whether the learner is showing frustration signals. */
  isShowingFrustration: boolean;
  /** Known CEFR level (null = unknown, treated as beginner). */
  cefrLevel: string | null;
  /** Total corrections delivered in this session so far. */
  totalCorrectionsInSession: number;
  /** Whether the learner just successfully self-corrected. */
  didSelfCorrect: boolean;
  /** Whether the current turn is correct (no errors detected). */
  isCorrectTurn: boolean;
  /** How many turns in a row have been correct (≥1). */
  consecutiveCorrectTurns: number;
};

/**
 * The encouragement timing decision with full rationale.
 */
export type EncouragementTimingResult = {
  /** The chosen encouragement decision. */
  decision: EncouragementDecision;
  /** The positive signal that triggered this decision (or "none"). */
  signal: EncouragementSignal;
  /**
   * Human-readable reason for the decision, in English (for telemetry/logging).
   * Vietnamese-facing explanations belong in the response generation layer.
   */
  reason: string;
  /** Machine-readable reason code for telemetry/analytics. */
  reasonCode: string;
  /**
   * For ENCOURAGE_SOON: suggested number of turns to wait before delivering.
   * undefined for all other decisions.
   */
  suggestAfterTurns?: number;
  /**
   * The kind of praise that would be appropriate (tag for specificPraise.ts).
   * undefined when decision is NO_ENCOURAGE.
   */
  suggestedPraiseTag?: string;
};

// ─── CEFR Level Utilities ──────────────────────────────────────────────────

function isBeginnerLevel(cefrLevel: string | null): boolean {
  if (!cefrLevel) return true;
  const upper = cefrLevel.toUpperCase();
  return upper === "A1" || upper === "A2";
}

// ─── Core Decision Gates ───────────────────────────────────────────────────

/**
 * E1 — Significant Improvement Gate
 *
 * If the learner just showed measurable improvement (fixed a recurring error,
 * self-corrected successfully, used a new pattern correctly), encourage now.
 *
 * This is THE strongest signal for encouragement — genuine improvement
 * deserves immediate acknowledgment. A human teacher would never let a
 * breakthrough moment pass without recognition.
 *
 * Exception: if we just encouraged last turn, let that one land first
 * (prevents encouragement stacking).
 */
function checkSignificantImprovementGate(
  input: EncouragementTimingInput,
): EncouragementTimingResult | null {
  if (!input.hasSignificantImprovement) return null;

  // Don't stack encouragement — let the previous one land
  if (input.turnsSinceLastEncouragement < 1) return null;

  const signalMap: Record<string, string> = {
    significant_improvement: "improvement_recognition",
    self_correction_success: "self_correction_praise",
    correct_new_pattern: "new_pattern_acknowledgment",
    sustained_accuracy: "sustained_accuracy_recognition",
  };

  const praiseTag = signalMap[input.encouragementSignal] ?? "improvement_recognition";

  return {
    decision: "ENCOURAGE_NOW",
    signal: input.encouragementSignal,
    reason:
      `Significant improvement detected (signal: ${input.encouragementSignal}) — encouraging immediately to reinforce the positive change.`,
    reasonCode: "encourage_significant_improvement",
    suggestedPraiseTag: praiseTag,
  };
}

/**
 * E2 — Struggle Recovery Gate
 *
 * If the learner was struggling (multiple corrections, shy/frustrated signals)
 * but just produced a correct turn, encourage now. Recovery from struggle is
 * a crucial teaching moment — the learner needs to know their effort paid off.
 *
 * This gate prevents the learner from feeling like "I keep getting corrected
 * and nothing I do is right." After a string of corrections, a correct turn
 * MUST be acknowledged.
 *
 * Exception: if the learner is actively frustrated, defer to E7 (frustration gate)
 * which fires later and handles timing more carefully.
 */
function checkStruggleRecoveryGate(
  input: EncouragementTimingInput,
): EncouragementTimingResult | null {
  if (!input.wasStruggling) return null;
  if (!input.isCorrectTurn) return null;

  // If frustrated, let E7 handle the timing
  if (input.isShowingFrustration) return null;

  // Don't stack on top of a recent encouragement
  if (input.turnsSinceLastEncouragement < 1) return null;

  return {
    decision: "ENCOURAGE_NOW",
    signal: "struggle_recovery",
    reason:
      `Learner was struggling but just produced a correct turn — encouraging to reinforce recovery and rebuild confidence.`,
    reasonCode: "encourage_struggle_recovery",
    suggestedPraiseTag: "struggle_recovery",
  };
}

/**
 * E3 — Too Soon After Encouragement Gate
 *
 * If we encouraged very recently (< 3 turns ago), don't encourage again.
 * Stacking encouragement dilutes its power and veers into fake-praise
 * territory (violating R3 NO_FAKE_PRAISE).
 *
 * A human teacher doesn't say "good job" every 30 seconds — the praise
 * loses meaning. Space encouragements so each one lands.
 *
 * Exception: significant improvement signals (E1) already check for
 * turnsSinceLastEncouragement < 1 internally, but this gate provides
 * the broader 3-turn spacing for all other signals.
 */
function checkTooSoonAfterEncouragementGate(
  input: EncouragementTimingInput,
): EncouragementTimingResult | null {
  if (input.turnsSinceLastEncouragement >= 3) return null;

  return {
    decision: "NO_ENCOURAGE",
    signal: "none",
    reason:
      `Only ${input.turnsSinceLastEncouragement} turn(s) since last encouragement — too soon. Space encouragements so each one lands meaningfully.`,
    reasonCode: "encourage_too_soon_after_encouragement",
  };
}

/**
 * E4 — Encouragement Saturation Gate
 *
 * If we've encouraged a lot already this session (≥4 times), be selective.
 * Only significant improvement or struggle recovery still gets encouragement.
 * Minor positives (basic correct turn, beginner milestone) no longer trigger.
 *
 * This prevents the teacher from becoming a praise-dispenser. After 4
 * encouragements, the learner knows the teacher sees their work — further
 * praise must be reserved for genuinely noteworthy moments.
 */
function checkEncouragementSaturationGate(
  input: EncouragementTimingInput,
): EncouragementTimingResult | null {
  if (input.encouragementsThisSession < 4) return null;

  // Only the strongest signals break through saturation
  if (
    input.encouragementSignal === "significant_improvement" ||
    input.encouragementSignal === "struggle_recovery"
  ) {
    return null; // Let E1 or E2 handle these — they're worth it
  }

  return {
    decision: "NO_ENCOURAGE",
    signal: "none",
    reason:
      `Already ${input.encouragementsThisSession} encouragements this session — saving further praise for genuinely noteworthy moments only.`,
    reasonCode: "encourage_saturation_selective",
  };
}

/**
 * E5 — Correction Heavy Session Gate
 *
 * If the session is correction-heavy (≥6 corrections) and the learner just
 * produced a correct turn, encourage now — even for a basic correct turn.
 *
 * When a learner has been corrected a lot, they can feel like they're failing.
 * A well-timed encouragement breaks that narrative: "Yes, there were things to
 * fix, AND you're doing things right too."
 *
 * Without this gate, a correction-heavy session can feel punitive.
 */
function checkCorrectionHeavySessionGate(
  input: EncouragementTimingInput,
): EncouragementTimingResult | null {
  if (input.totalCorrectionsInSession < 6) return null;
  if (!input.isCorrectTurn) return null;

  // Don't encourage in a correction-heavy session if we just did
  if (input.turnsSinceLastEncouragement < 2) return null;

  // For correction-heavy sessions, even basic correctness is worth noting
  return {
    decision: "ENCOURAGE_NOW",
    signal: "struggle_recovery",
    reason:
      `After ${input.totalCorrectionsInSession} corrections this session, a correct turn deserves acknowledgment to prevent the session from feeling punitive.`,
    reasonCode: "encourage_correction_heavy_session_balance",
    suggestedPraiseTag: "correction_heavy_balance",
  };
}

/**
 * E6 — Shy Learner Gate
 *
 * Shy learners need more encouragement, but delivered gently — not as a
 * spotlight. Queue encouragement for 1–2 turns from now rather than
 * delivering it immediately.
 *
 * Immediate praise can make a shy learner self-conscious ("everyone is
 * looking at me now"). A delayed, quieter encouragement integrated into
 * the next turn's response feels more natural and less exposing.
 *
 * If the shy learner hasn't been encouraged at all in the last 5 turns
 * AND just did something correct, make sure they get encouragement soon.
 */
function checkShyLearnerGate(
  input: EncouragementTimingInput,
): EncouragementTimingResult | null {
  if (input.learnerConfidence !== "shy") return null;

  // Shy learners still get immediate encouragement for significant improvement
  // (E1 will have already fired). What remains here is gentle encouragement
  // for correct-but-not-groundbreaking turns.

  // If we just encouraged, don't add more — shy learners need space
  if (input.turnsSinceLastEncouragement < 5) return null;

  // Shy learner produced a correct turn after a gap in encouragement
  if (input.isCorrectTurn || input.consecutiveCorrectTurns >= 2) {
    return {
      decision: "ENCOURAGE_SOON",
      signal: "beginner_basic_success",
      reason:
        `Shy learner with ${input.turnsSinceLastEncouragement} turns since last encouragement — queue a gentle, low-spotlight encouragement for 2 turns from now.`,
      reasonCode: "encourage_shy_learner_gentle",
      suggestAfterTurns: 2,
      suggestedPraiseTag: "gentle_encouragement",
    };
  }

  return null;
}

/**
 * E7 — Frustration Gate
 *
 * If the learner is showing frustration signals, encouragement right now
 * may feel dismissive — like the teacher isn't acknowledging their struggle.
 *
 * Instead, queue encouragement for later (ENCOURAGE_SOON, 3 turns) after
 * the frustration has had time to subside. A human teacher would first
 * acknowledge the frustration ("I can see this is hard"), let the learner
 * settle, THEN offer encouragement.
 *
 * If the learner has been frustrated for ≥3 turns and is still trying,
 * encourage now — persistence through frustration IS worth acknowledging.
 */
function checkFrustrationGate(
  input: EncouragementTimingInput,
): EncouragementTimingResult | null {
  if (!input.isShowingFrustration) return null;

  // If the learner is frustrated AND just produced a correct turn,
  // that's struggle recovery — E2 should have caught it (but E2 skips
  // frustrated learners, so we handle it here with a softer touch)
  if (input.isCorrectTurn && input.wasStruggling) {
    return {
      decision: "ENCOURAGE_SOON",
      signal: "struggle_recovery",
      reason:
        `Learner showing frustration but still produced a correct turn — queue encouragement for 3 turns from now to let frustration subside first.`,
      reasonCode: "encourage_frustration_recovery_gentle",
      suggestAfterTurns: 3,
      suggestedPraiseTag: "struggle_recovery",
    };
  }

  // Frustrated but not correct — no encouragement now
  // Encouragement while still in the thick of frustration feels dismissive
  return {
    decision: "NO_ENCOURAGE",
    signal: "none",
    reason:
      `Learner is showing frustration — encouragement right now may feel dismissive. Focus on support and acknowledgment first.`,
    reasonCode: "encourage_frustration_defer",
  };
}

/**
 * E8 — Beginner Milestone Gate
 *
 * Beginners (A1–A2) benefit from frequent small encouragements for any
 * correct production. Without encouragement, beginners can feel the
 * language is impossibly hard and give up.
 *
 * This gate fires for basic successes: a correct sentence, a self-correction,
 * or even just a good attempt. The encouragement should be small and specific
 * ("That sentence was correct!"), not overblown.
 *
 * Limit: don't encourage more than once every 2 turns even for beginners.
 */
function checkBeginnerMilestoneGate(
  input: EncouragementTimingInput,
): EncouragementTimingResult | null {
  if (!isBeginnerLevel(input.cefrLevel)) return null;

  // Don't over-encourage even beginners — space by 2 turns minimum
  if (input.turnsSinceLastEncouragement < 2) return null;

  // Beginners get encouragement for any correct turn
  if (input.isCorrectTurn) {
    return {
      decision: "ENCOURAGE_NOW",
      signal: "beginner_basic_success",
      reason:
        `Beginner (${input.cefrLevel ?? "unknown"}) produced a correct turn — encouraging to build confidence and prevent discouragement.`,
      reasonCode: "encourage_beginner_milestone",
      suggestedPraiseTag: "beginner_milestone",
    };
  }

  // Also encourage after self-correction (even if the result has minor issues)
  if (input.didSelfCorrect) {
    return {
      decision: "ENCOURAGE_NOW",
      signal: "self_correction_success",
      reason:
        `Beginner successfully self-corrected — encouraging to reinforce the self-monitoring habit.`,
      reasonCode: "encourage_beginner_self_correction",
      suggestedPraiseTag: "self_correction_praise",
    };
  }

  return null;
}

// ─── Default Fallback ──────────────────────────────────────────────────────

/**
 * Default encouragement timing decision when no specific gate fires.
 *
 * Conservative default: NO_ENCOURAGE. Encouragement should be triggered by
 * specific pedagogical signals, not as a default behavior.
 * The gates above cover all the cases where encouragement is justified.
 *
 * One exception: if we've gone a long time without any encouragement AND
 * the learner has just had several correct turns in a row, suggest a gentle
 * encouragement soon to maintain warmth.
 */
function defaultEncouragementTiming(
  input: EncouragementTimingInput,
): EncouragementTimingResult {
  // Long gap with sustained correctness — gentle nudge
  if (
    input.encouragementsThisSession === 0 &&
    input.consecutiveCorrectTurns >= 4 &&
    input.turnsSinceLastEncouragement >= 100 // effectively "never encouraged"
  ) {
    return {
      decision: "ENCOURAGE_SOON",
      signal: "sustained_accuracy",
      reason:
        `No encouragements yet this session with ${input.consecutiveCorrectTurns} consecutive correct turns — suggest a gentle encouragement to establish warmth.`,
      reasonCode: "encourage_default_first_warmth",
      suggestAfterTurns: 2,
      suggestedPraiseTag: "sustained_accuracy_recognition",
    };
  }

  return {
    decision: "NO_ENCOURAGE",
    signal: "none",
    reason:
      "No specific pedagogical signal justifying encouragement at this moment — continue normal interaction.",
    reasonCode: "encourage_default_no_encourage",
  };
}

// ─── Public API ────────────────────────────────────────────────────────────

/**
 * The ordered list of gates that determine encouragement timing.
 * Gates are evaluated in order; the first non-null result wins.
 *
 * Priority hierarchy:
 *   1. Significant improvement — always encourage genuine progress (E1)
 *   2. Struggle recovery — acknowledge effort after difficulty (E2)
 *   3. Too soon after encouragement — never stack praise (E3)
 *   4. Encouragement saturation — be selective after many encouragements (E4)
 *   5. Correction-heavy session — balance corrections with warmth (E5)
 *   6. Shy learner — gentle, delayed encouragement (E6)
 *   7. Frustration — don't dismiss negative feelings (E7)
 *   8. Beginner milestone — frequent small wins for beginners (E8)
 *   9. Default — conservative NO_ENCOURAGE
 *
 * Design rationale for E3/E4 before E5/E6:
 *   Spacing and saturation are hard constraints — no matter how correction-heavy
 *   the session or how shy the learner, stacking encouragement is always wrong.
 *   E1/E2 fire first because significant improvement and struggle recovery are
 *   the strongest signals — they override spacing concerns (with E1 having its
 *   own internal check for turnsSinceLastEncouragement < 1).
 */
const GATES: ReadonlyArray<
  (input: EncouragementTimingInput) => EncouragementTimingResult | null
> = [
  checkSignificantImprovementGate,
  checkStruggleRecoveryGate,
  checkTooSoonAfterEncouragementGate,
  checkEncouragementSaturationGate,
  checkCorrectionHeavySessionGate,
  checkShyLearnerGate,
  checkFrustrationGate,
  checkBeginnerMilestoneGate,
];

/**
 * Decide whether to encourage the learner right now, soon, or not at all.
 *
 * Pure function — deterministic, no side effects, no I/O.
 *
 * @returns An EncouragementTimingResult with the chosen decision and rationale.
 */
export function decideEncouragementTiming(
  input: EncouragementTimingInput,
): EncouragementTimingResult {
  for (const gate of GATES) {
    const result = gate(input);
    if (result !== null) return result;
  }

  return defaultEncouragementTiming(input);
}

/**
 * Convenience: check whether encouragement is recommended now
 * (as opposed to later or not at all).
 */
export function isEncouragementRecommendedNow(
  result: EncouragementTimingResult,
): boolean {
  return result.decision === "ENCOURAGE_NOW";
}

/**
 * Convenience: check whether encouragement is queued for later (ENCOURAGE_SOON).
 */
export function isEncouragementQueued(
  result: EncouragementTimingResult,
): boolean {
  return result.decision === "ENCOURAGE_SOON";
}

/**
 * Convenience: check whether no encouragement is recommended at all.
 */
export function isNoEncouragementRecommended(
  result: EncouragementTimingResult,
): boolean {
  return result.decision === "NO_ENCOURAGE";
}

// ─── Catalogs ───────────────────────────────────────────────────────────────

export const ENCOURAGEMENT_TIMING_DECISION_CATALOG: ReadonlyArray<{
  decision: EncouragementDecision;
  titleEn: string;
  titleVi: string;
  descriptionVi: string;
}> = [
  {
    decision: "ENCOURAGE_NOW",
    titleEn: "Encourage now",
    titleVi: "Động viên ngay",
    descriptionVi: "Khen ngợi cụ thể ngay trong lượt này — cải thiện xứng đáng được ghi nhận.",
  },
  {
    decision: "ENCOURAGE_SOON",
    titleEn: "Encourage soon",
    titleVi: "Động viên lát nữa",
    descriptionVi: "Xếp lịch khen ngợi sau vài lượt — để khoảnh khắc hiện tại lắng xuống trước.",
  },
  {
    decision: "NO_ENCOURAGE",
    titleEn: "No encourage",
    titleVi: "Không động viên",
    descriptionVi: "Tiếp tục tương tác bình thường — chưa đến lúc phù hợp để khen ngợi.",
  },
];

export const ENCOURAGEMENT_TIMING_REASON_CODE_CATALOG: ReadonlyArray<{
  reasonCode: string;
  decision: EncouragementDecision;
  descriptionVi: string;
}> = [
  { reasonCode: "encourage_significant_improvement", decision: "ENCOURAGE_NOW", descriptionVi: "Cải thiện rõ rệt — động viên ngay để củng cố." },
  { reasonCode: "encourage_struggle_recovery", decision: "ENCOURAGE_NOW", descriptionVi: "Vừa vượt qua khó khăn — ghi nhận nỗ lực." },
  { reasonCode: "encourage_too_soon_after_encouragement", decision: "NO_ENCOURAGE", descriptionVi: "Vừa khen xong — để lời khen trước lắng xuống đã." },
  { reasonCode: "encourage_saturation_selective", decision: "NO_ENCOURAGE", descriptionVi: "Đã khen nhiều trong buổi — chỉ khen những khoảnh khắc thật sự đáng." },
  { reasonCode: "encourage_correction_heavy_session_balance", decision: "ENCOURAGE_NOW", descriptionVi: "Đã sửa nhiều lỗi — cân bằng lại bằng lời động viên." },
  { reasonCode: "encourage_shy_learner_gentle", decision: "ENCOURAGE_SOON", descriptionVi: "Người học nhút nhát — động viên nhẹ nhàng, không spotlight." },
  { reasonCode: "encourage_frustration_recovery_gentle", decision: "ENCOURAGE_SOON", descriptionVi: "Đang bực — để nguôi đã rồi động viên sau." },
  { reasonCode: "encourage_frustration_defer", decision: "NO_ENCOURAGE", descriptionVi: "Đang bực — động viên lúc này dễ bị coi là coi thường cảm xúc." },
  { reasonCode: "encourage_beginner_milestone", decision: "ENCOURAGE_NOW", descriptionVi: "Mới học, nói đúng — khen ngay để khỏi nản." },
  { reasonCode: "encourage_beginner_self_correction", decision: "ENCOURAGE_NOW", descriptionVi: "Mới học, tự sửa được — khen để củng cố thói quen tốt." },
  { reasonCode: "encourage_default_first_warmth", decision: "ENCOURAGE_SOON", descriptionVi: "Chưa khen lần nào, đang nói đúng liên tục — gợi ý nhẹ nhàng." },
  { reasonCode: "encourage_default_no_encourage", decision: "NO_ENCOURAGE", descriptionVi: "Chưa có tín hiệu cần động viên — tiếp tục bình thường." },
];
