import { TUTOR_LANGUAGE_PACKS } from "./languages";
import {
  getTutorLanguage,
  resolveTutorTargetLanguage,
} from "./languageRegistry";
import type { TutorCopy, TutorTarget, TutorUiLanguage } from "./tutorCopyTypes";

export type { TutorCopy, TutorLanguagePack, TutorTarget, TutorUiLanguage } from "./tutorCopyTypes";

function normalizeTargetLanguage(value: unknown): TutorTarget {
  return resolveTutorTargetLanguage(value);
}

function normalizeUiLanguage(value: unknown): TutorUiLanguage {
  return String(value ?? "").trim().toLowerCase() === "en" ? "en" : "vi";
}

export function getTutorCopy(targetLanguage: unknown, uiLanguage: unknown): TutorCopy {
  const target = normalizeTargetLanguage(targetLanguage);
  const ui = normalizeUiLanguage(uiLanguage);
  const packs = TUTOR_LANGUAGE_PACKS;
  const pack = packs[target] ?? packs.en;
  const language = getTutorLanguage(target);

  const uiCopy = ui === "en"
    ? {
        title: target === "en" ? "Teacher Mercy AI Tutor" : `Teacher Mercy · ${pack.nameEn} Tutor`,
        subtitle: `Practice ${pack.nameEn} with Mercy. Write a ${pack.nameEn} sentence; Mercy corrects it and explains in English.`,
        helper: `Mercy corrects the selected target language: ${pack.nameEn}.`,
        eyebrow: "Teacher Mercy",
        footer: "Teacher Mercy keeps target practice separate from explanations. No raw audio or full transcript storage.",
        inputLabel: `Your ${pack.nameEn} sentence`,
        correctionTitle: pack.correctionTitle,
        conversationTitle: pack.conversationTitle,
        conversationEyebrow: "Mercy asks · You answer",
        conversationBody: `Practice in ${pack.nameEn}. Mercy corrects gently, replies naturally, and asks one next question.`,
        conversationDescription: `Practice in ${pack.nameEn}. Mercy corrects gently, replies naturally, and asks one next question.`,
        conversationEmpty: "Mercy will start with one easy question.",
        conversationThinking: "Mercy is thinking...",
        conversationInputLabel: "Your answer",
        conversationPlaceholder: `Type your ${pack.nameEn} answer here...`,
        conversationSend: "Send",
        conversationMercyLabel: "Mercy",
        conversationUserLabel: "You",
        conversationCorrectedLabel: "Corrected",
        conversationExplanationLabel: "Explanation",
        conversationReplyLabel: "Mercy reply",
        conversationFallback: "I can still help you practice. Try a simpler sentence, or use the AI correction engine when it is available.",
        emptyConversation: "Mercy will start with one easy question.",
        answerLabel: "Your answer",
        answerPlaceholder: `Type your ${pack.nameEn} answer here...`,
        send: "Send",
        submit: "Correct my sentence",
        submitting: "Correcting...",
        reset: "Reset",
        emptyTitle: "AI is ready to correct your sentence",
        emptyBody: `Type a ${pack.nameEn} sentence above and press Correct my sentence.`,
        loadingTitle: "AI is analyzing your sentence...",
        loadingBody: "Mercy will correct the language you selected.",
        correctedLabel: "Corrected",
        ttsUnavailable: "Browser voice playback is not supported on this device.",
        ttsAriaStop: "Stop Mercy voice",
        ttsAriaPlay: "Read corrected sentence with Mercy AI voice",
        ttsPreparing: "Preparing Mercy voice...",
        ttsStop: "Stop",
        ttsPlay: "Mercy reads",
        ttsBrowserFallback: "Mercy voice unavailable. Using device voice.",
        ttsMercyVoiceLabel: "Mercy voice",
        ttsDeviceVoiceFallbackLabel: "Device voice fallback",
        voiceInputTitle: "Speak instead of typing",
        voiceDraftTitle: "Voice draft",
        useVoiceDraft: "Use this sentence",
        clearVoiceDraft: "Record again",
        sendToSpeak: "Send this sentence to Speak practice",
        explanationLabel: "Explanation",
        grammarTipLabel: "Grammar tip",
        practiceLabel: "Practice",
        practicePlaceholder: "Write your answer here...",
        practiceSubmitting: "Checking...",
        practiceSubmit: "Submit answer",
        feedbackLabel: "Feedback",
        tipLabel: "Tip",
        nextStepLabel: "Next step",
        tryAnother: "Try another sentence",
        journeyModeLabel: "Journey",
        grammarModeLabel: "Grammar",
        speakModeLabel: "Speak",
        logicModeLabel: "Logic",
        journeyTitle: "Journey practice",
        journeyDescription: `Conversation practice in ${pack.nameEn}. Mercy corrects gently, replies naturally, and asks the next question.`,
        speakTitle: "Speak practice",
        speakDescription: `Use the mic to say a ${pack.nameEn} sentence. Mercy helps you hear and improve the natural version.`,
        speakInputLabel: "Sentence to practice aloud",
        speakPlaceholder: `Speak or type a ${pack.nameEn} sentence for Mercy...`,
        speakSend: "Practice speaking",
        logicTitle: "English logic coach",
        logicDescription: "Mercy explains why natural English works, why Vietlish sounds unnatural, and which pattern to remember.",
        logicInputLabel: "English or Vietlish sentence",
        logicPlaceholder: "Ask why “I’m interested in English” is natural, why “I go school” is incomplete, or why “I bought a hat yesterday” needs past tense...",
        logicSend: "Explain the logic",
      }
    : {
        title: target === "en" ? "Sửa tiếng Anh với Mercy" : `Teacher Mercy · Gia sư ${pack.nameVi}`,
        subtitle: `Gõ một câu ${pack.nameVi}. Mercy sẽ sửa giúp bạn.`,
        helper: "",
        eyebrow: "Teacher Mercy",
        footer: "Mercy sửa đúng ngôn ngữ bạn chọn. Không lưu âm thanh thô hoặc toàn bộ transcript.",
        inputLabel: `Gõ câu ${pack.nameVi} của bạn`,
        correctionTitle: `Sửa ${pack.nameVi}`,
        conversationTitle: "Trò chuyện với Mercy",
        conversationEyebrow: "Mercy hỏi · Bạn trả lời",
        conversationBody: `Luyện ${pack.nameVi}. Mercy sửa nhẹ nhàng, trả lời tự nhiên, rồi hỏi tiếp một câu.`,
        conversationDescription: `Luyện ${pack.nameVi}. Mercy sửa nhẹ nhàng, trả lời tự nhiên, rồi hỏi tiếp một câu.`,
        conversationEmpty: "Mercy sẽ bắt đầu bằng một câu hỏi dễ.",
        conversationThinking: "Mercy đang nghĩ...",
        conversationInputLabel: "Câu trả lời của bạn",
        conversationPlaceholder: `Gõ câu trả lời ${pack.nameVi} của bạn ở đây...`,
        conversationSend: "Gửi",
        conversationMercyLabel: "Mercy",
        conversationUserLabel: "Bạn",
        conversationCorrectedLabel: "Câu đã sửa",
        conversationExplanationLabel: "Giải thích",
        conversationReplyLabel: "Mercy trả lời",
        conversationFallback: "Mercy vẫn có thể giúp bạn luyện tập. Hãy thử một câu đơn giản hơn, hoặc dùng bộ sửa lỗi AI khi khả dụng.",
        emptyConversation: "Mercy sẽ bắt đầu bằng một câu hỏi dễ.",
        answerLabel: "Câu trả lời của bạn",
        answerPlaceholder: `Gõ câu trả lời ${pack.nameVi} của bạn ở đây...`,
        send: "Gửi",
        submit: "Sửa câu này",
        submitting: "Đang sửa...",
        reset: "Làm mới",
        emptyTitle: "Sẵn sàng sửa câu",
        emptyBody: `Gõ một câu ${pack.nameVi}. Mercy sẽ sửa giúp bạn.`,
        loadingTitle: "Mercy đang sửa...",
        loadingBody: "Chờ một chút nhé.",
        correctedLabel: "Câu đã sửa",
        ttsUnavailable: "Giọng đọc trình duyệt chưa khả dụng trên thiết bị này.",
        ttsAriaStop: "Dừng đọc",
        ttsAriaPlay: "Mercy đọc câu đã sửa bằng giọng AI",
        ttsPreparing: "Đang chuẩn bị giọng Mercy...",
        ttsStop: "Dừng",
        ttsPlay: "Mercy đọc",
        ttsBrowserFallback: "Chưa dùng được giọng Mercy. Đang dùng giọng của thiết bị.",
        ttsMercyVoiceLabel: "Giọng Mercy",
        ttsDeviceVoiceFallbackLabel: "Giọng thiết bị",
        voiceInputTitle: "Đọc câu thay vì gõ",
        voiceDraftTitle: "Bản nháp giọng nói",
        useVoiceDraft: "Dùng câu này",
        clearVoiceDraft: "Thu lại",
        sendToSpeak: "Đưa câu này sang Luyện nói",
        explanationLabel: "Giải thích",
        grammarTipLabel: "Mẹo ngữ pháp",
        practiceLabel: "Luyện tập",
        practicePlaceholder: "Viết câu trả lời của bạn ở đây...",
        practiceSubmitting: "Đang kiểm tra...",
        practiceSubmit: "Gửi câu trả lời",
        feedbackLabel: "Nhận xét",
        tipLabel: "Mẹo",
        nextStepLabel: "Bước tiếp theo",
        tryAnother: "Sửa câu khác",
        journeyModeLabel: "Lộ trình",
        grammarModeLabel: "Sửa câu",
        speakModeLabel: "Luyện nói",
        logicModeLabel: "Logic",
        journeyTitle: "Lộ trình luyện tập",
        journeyDescription: `Trả lời câu hỏi ngắn. Mercy sửa nhẹ và hỏi tiếp.`,
        speakTitle: "Luyện nói",
        speakDescription: `Nói hoặc gõ một câu. Mercy giúp bạn luyện câu tự nhiên hơn.`,
        speakInputLabel: "Câu để luyện nói",
        speakPlaceholder: `Nói hoặc gõ một câu ${pack.nameVi} cho Mercy...`,
        speakSend: "Luyện nói",
        logicTitle: "Giải thích logic tiếng Anh",
        logicDescription: "Mercy giúp bạn hiểu vì sao tiếng Anh nói như vậy, để tránh dịch từng chữ từ tiếng Việt.",
        logicInputLabel: "Câu tiếng Anh/Vietlish bạn muốn hiểu",
        logicPlaceholder: "Ví dụ: Vì sao nói “I’m interested in English” mà không nói “I’m interesting in English”?",
        logicSend: "Giải thích logic",
      };

  return {
    ...pack,
    nameEn: language.labelEn,
    nameVi: language.labelVi,
    placeholder: language.beginnerPlaceholder,
    exampleSentences: [language.defaultExampleSentence, ...pack.exampleSentences.filter((example) => example !== language.defaultExampleSentence)],
    speakerLabels: ui === "en" ? {
      tutor: "Teacher Mercy",
      learner: "You",
      correctedVersion: "Corrected version",
      shortExplanation: "Short explanation",
      naturalReply: "Natural reply",
      thinking: "Mercy is thinking...",
    } : {
      tutor: "Teacher Mercy",
      learner: "Bạn",
      correctedVersion: "Câu đã sửa",
      shortExplanation: "Giải thích ngắn",
      naturalReply: "Câu trả lời tự nhiên",
      thinking: "Mercy đang suy nghĩ...",
    },
    micLabels: ui === "en" ? {
      input: "Speak your sentence",
      listening: "Listening to your voice...",
      helper: "Mercy turns your voice into text for correction.",
      unavailable: "Microphone unavailable in this browser. You can still type your sentence.",
      ariaStart: "Speak your sentence for voice input",
      ariaStop: "Stop listening",
    } : {
      input: "Nhập bằng giọng nói",
      listening: "Đang nghe giọng của bạn...",
      helper: "Mercy sẽ chuyển giọng nói của bạn thành câu để sửa.",
      unavailable: "Không dùng được micro trên trình duyệt này. Bạn vẫn có thể gõ câu.",
      ariaStart: "Nhập bằng giọng nói",
      ariaStop: "Dừng nghe",
    },
    targetLanguage: target,
    uiLanguage: ui,
    ui: uiCopy,
  };
}
