import type { TutorLanguageCode } from "./languageRegistry";

export type TutorTarget = TutorLanguageCode;
export type TutorUiLanguage = "vi" | "en";

export type TutorLanguagePack = {
  code: TutorTarget;
  nameEn: string;
  nameVi: string;
  correctionTitle: string;
  conversationTitle: string;
  inputLabel: string;
  placeholder: string;
  exampleSentences: string[];
  starterQuestions: string[];
  commonBeginnerMistakes: string[];
  grammarHints: string[];
  nextQuestionTemplates: string[];
  naturalReplies: string[];
  fallbackMessages: {
    correctionNeedsAi: string;
    conversationNeedsAi: string;
  };
  speakerLabels: {
    tutor: string;
    learner: string;
    correctedVersion: string;
    shortExplanation: string;
    naturalReply: string;
    thinking: string;
  };
  micLabels: {
    input: string;
    listening: string;
    helper: string;
    unavailable: string;
    ariaStart: string;
    ariaStop: string;
  };
};

export type TutorCopy = TutorLanguagePack & {
  targetLanguage: TutorTarget;
  uiLanguage: TutorUiLanguage;
  ui: {
    title: string;
    subtitle: string;
    helper: string;
    eyebrow: string;
    footer: string;
    inputLabel: string;
    correctionTitle: string;
    conversationTitle: string;
    conversationEyebrow: string;
    conversationBody: string;
    conversationDescription: string;
    conversationEmpty: string;
    conversationThinking: string;
    conversationInputLabel: string;
    conversationPlaceholder: string;
    conversationSend: string;
    conversationMercyLabel: string;
    conversationUserLabel: string;
    conversationCorrectedLabel: string;
    conversationExplanationLabel: string;
    conversationReplyLabel: string;
    conversationFallback: string;
    emptyConversation: string;
    answerLabel: string;
    answerPlaceholder: string;
    send: string;
    submit: string;
    submitting: string;
    reset: string;
    emptyTitle: string;
    emptyBody: string;
    loadingTitle: string;
    loadingBody: string;
    correctedLabel: string;
    ttsUnavailable: string;
    ttsAriaStop: string;
    ttsAriaPlay: string;
    ttsPreparing: string;
    ttsStop: string;
    ttsPlay: string;
    ttsBrowserFallback: string;
    ttsMercyVoiceLabel: string;
    ttsDeviceVoiceFallbackLabel: string;
    voiceInputTitle: string;
    voiceDraftTitle: string;
    useVoiceDraft: string;
    clearVoiceDraft: string;
    sendToSpeak: string;
    explanationLabel: string;
    grammarTipLabel: string;
    practiceLabel: string;
    practicePlaceholder: string;
    practiceSubmitting: string;
    practiceSubmit: string;
    feedbackLabel: string;
    tipLabel: string;
    nextStepLabel: string;
    tryAnother: string;
    journeyModeLabel: string;
    grammarModeLabel: string;
    speakModeLabel: string;
    logicModeLabel: string;
    journeyTitle: string;
    journeyDescription: string;
    speakTitle: string;
    speakDescription: string;
    speakInputLabel: string;
    speakPlaceholder: string;
    speakSend: string;
    logicTitle: string;
    logicDescription: string;
    logicInputLabel: string;
    logicPlaceholder: string;
    logicSend: string;
  };
};
