export type VietlishCorpusCategory =
  | "calque"
  | "word_order"
  | "register"
  | "collocation"
  | "false_friend"
  | "literal_translation";

export type VietlishCorpusFrequency = "high" | "medium" | "low";

export type VietlishCorpusEntry = {
  vietlish: string;
  natural: string;
  sourcePattern: string;
  category: VietlishCorpusCategory;
  frequency: VietlishCorpusFrequency;
  context: string;
};

export const VIETLISH_CORPUS = [
  {
    vietlish: "open the light",
    natural: "turn on the light",
    sourcePattern: "mo den -> mo means open, used for activating lights and devices",
    category: "calque",
    frequency: "high",
    context: "Can you open the light? It is too dark here.",
  },
  {
    vietlish: "close the light",
    natural: "turn off the light",
    sourcePattern: "tat den / dong can map to stop or close; learners overuse close for deactivation",
    category: "calque",
    frequency: "high",
    context: "Please close the light before you sleep.",
  },
  {
    vietlish: "open the air conditioner",
    natural: "turn on the air conditioner",
    sourcePattern: "mo may lanh -> mo is used for switching appliances on",
    category: "calque",
    frequency: "high",
    context: "It is hot, so I will open the air conditioner.",
  },
  {
    vietlish: "close the fan",
    natural: "turn off the fan",
    sourcePattern: "tat quat / dong as a general stop-close idea for devices",
    category: "calque",
    frequency: "high",
    context: "Can you close the fan? I feel cold.",
  },
  {
    vietlish: "open the computer",
    natural: "turn on the computer",
    sourcePattern: "mo may tinh -> mo means open/start for machines",
    category: "calque",
    frequency: "low",
    context: "I open the computer every morning to check email.",
  },
  {
    vietlish: "close the computer",
    natural: "shut down the computer",
    sourcePattern: "tat may tinh -> tat is a broad off action; close is overgeneralized from Vietnamese",
    category: "calque",
    frequency: "low",
    context: "I forgot to close the computer last night.",
  },
  {
    vietlish: "play with my friends",
    natural: "hang out with my friends",
    sourcePattern: "di choi voi ban -> choi means play but also go out socially",
    category: "calque",
    frequency: "high",
    context: "On Sunday I play with my friends at the mall.",
  },
  {
    vietlish: "go play coffee",
    natural: "go out for coffee",
    sourcePattern: "di choi / di ca phe -> social leisure is often expressed with choi or di",
    category: "literal_translation",
    frequency: "low",
    context: "After work we go play coffee near my office.",
  },
  {
    vietlish: "take a bath",
    natural: "take a shower",
    sourcePattern: "tam covers bathing and showering; learners choose bath for daily showering",
    category: "collocation",
    frequency: "high",
    context: "I take a bath quickly before going to work.",
  },
  {
    vietlish: "learn lesson",
    natural: "study the lesson",
    sourcePattern: "hoc bai -> hoc can mean learn or study; bai means lesson/homework",
    category: "collocation",
    frequency: "high",
    context: "I need to learn lesson before the test tomorrow.",
  },
  {
    vietlish: "learn English center",
    natural: "study at an English center",
    sourcePattern: "hoc trung tam Anh ngu -> hoc plus place without English preposition",
    category: "literal_translation",
    frequency: "high",
    context: "My sister learns English center every evening.",
  },
  {
    vietlish: "go to the hometown",
    natural: "go back to my hometown",
    sourcePattern: "ve que -> ve carries return-home meaning",
    category: "calque",
    frequency: "low",
    context: "This weekend I will go to the hometown.",
  },
  {
    vietlish: "eat rice",
    natural: "have a meal",
    sourcePattern: "an com means eat rice literally but often means have a meal",
    category: "literal_translation",
    frequency: "high",
    context: "Did you eat rice yet?",
  },
  {
    vietlish: "drink medicine",
    natural: "take medicine",
    sourcePattern: "uong thuoc -> uong means drink and is used for medicine",
    category: "collocation",
    frequency: "high",
    context: "The doctor told me to drink medicine twice a day.",
  },
  {
    vietlish: "make homework",
    natural: "do homework",
    sourcePattern: "lam bai tap -> lam can mean do or make",
    category: "collocation",
    frequency: "high",
    context: "I make homework after dinner.",
  },
  {
    vietlish: "do a mistake",
    natural: "make a mistake",
    sourcePattern: "lam sai / lam loi -> lam can map to do, but English uses make a mistake",
    category: "collocation",
    frequency: "low",
    context: "I did a mistake in the interview.",
  },
  {
    vietlish: "say with me",
    natural: "tell me",
    sourcePattern: "noi voi toi -> noi voi maps word-for-word to say with",
    category: "calque",
    frequency: "medium",
    context: "Can you say with me the address again?",
  },
  {
    vietlish: "explain me",
    natural: "explain it to me",
    sourcePattern: "giai thich cho toi -> Vietnamese object marking differs from English explain to",
    category: "collocation",
    frequency: "medium",
    context: "Please explain me this grammar.",
  },
  {
    vietlish: "discuss about the problem",
    natural: "discuss the problem",
    sourcePattern: "thao luan ve -> ve means about; English discuss usually takes a direct object",
    category: "collocation",
    frequency: "medium",
    context: "We need to discuss about the problem today.",
  },
  {
    vietlish: "mention about that",
    natural: "mention that",
    sourcePattern: "de cap ve -> ve means about; mention usually does not take about",
    category: "collocation",
    frequency: "medium",
    context: "She mentioned about that in the meeting.",
  },
  {
    vietlish: "contact with me",
    natural: "contact me",
    sourcePattern: "lien he voi toi -> voi means with; English contact takes a direct object",
    category: "collocation",
    frequency: "high",
    context: "Please contact with me when you arrive.",
  },
  {
    vietlish: "marry with him",
    natural: "marry him",
    sourcePattern: "cuoi voi anh ay -> voi means with; English marry takes a direct object",
    category: "collocation",
    frequency: "medium",
    context: "She will marry with him next year.",
  },
  {
    vietlish: "listen music",
    natural: "listen to music",
    sourcePattern: "nghe nhac -> Vietnamese places object after hear/listen without to",
    category: "literal_translation",
    frequency: "high",
    context: "I listen music when I study.",
  },
  {
    vietlish: "wait you",
    natural: "wait for you",
    sourcePattern: "cho ban -> Vietnamese verb cho takes the object directly",
    category: "literal_translation",
    frequency: "high",
    context: "I will wait you outside the station.",
  },
  {
    vietlish: "enter university",
    natural: "get into university",
    sourcePattern: "vao dai hoc -> vao means enter/go into for school admission",
    category: "calque",
    frequency: "medium",
    context: "My brother entered university last year.",
  },
  {
    vietlish: "I yesterday went to store",
    natural: "I went to the store yesterday",
    sourcePattern: "Hom qua toi di cua hang -> Vietnamese commonly places time before the verb phrase",
    category: "word_order",
    frequency: "high",
    context: "I yesterday went to store to buy milk.",
  },
  {
    vietlish: "I tomorrow will meet you",
    natural: "I will meet you tomorrow",
    sourcePattern: "Ngay mai toi se gap ban -> time phrase comes early before the action",
    category: "word_order",
    frequency: "high",
    context: "I tomorrow will meet you after class.",
  },
  {
    vietlish: "She every day goes to work by bus",
    natural: "She goes to work by bus every day",
    sourcePattern: "Co ay moi ngay di lam bang xe buyt -> frequency marker before verb",
    category: "word_order",
    frequency: "medium",
    context: "She every day goes to work by bus.",
  },
  {
    vietlish: "I in the morning drink coffee",
    natural: "I drink coffee in the morning",
    sourcePattern: "Toi buoi sang uong ca phe -> Vietnamese can place time after subject before verb",
    category: "word_order",
    frequency: "medium",
    context: "I in the morning drink coffee with my wife.",
  },
  {
    vietlish: "My hometown, it is very beautiful",
    natural: "My hometown is very beautiful",
    sourcePattern: "Que toi, no rat dep -> topic-comment structure with resumptive pronoun",
    category: "word_order",
    frequency: "high",
    context: "My hometown, it is very beautiful in spring.",
  },
  {
    vietlish: "This book I like very much",
    natural: "I like this book very much",
    sourcePattern: "Quyen sach nay toi rat thich -> topic-fronting before subject",
    category: "word_order",
    frequency: "high",
    context: "This book I like very much because it is simple.",
  },
  {
    vietlish: "English I study every day",
    natural: "I study English every day",
    sourcePattern: "Tieng Anh toi hoc moi ngay -> object/topic before subject",
    category: "word_order",
    frequency: "high",
    context: "English I study every day for my job.",
  },
  {
    vietlish: "The room has many people",
    natural: "There are many people in the room",
    sourcePattern: "Trong phong co nhieu nguoi -> co can map to have/exist",
    category: "literal_translation",
    frequency: "high",
    context: "The room has many people, so it is noisy.",
  },
  {
    vietlish: "My family has five people",
    natural: "There are five people in my family",
    sourcePattern: "Gia dinh toi co nam nguoi -> co means have/there are",
    category: "literal_translation",
    frequency: "high",
    context: "My family has five people and we live in Da Nang.",
  },
  {
    vietlish: "Near my house has a supermarket",
    natural: "There is a supermarket near my house",
    sourcePattern: "Gan nha toi co sieu thi -> location plus co existence pattern",
    category: "word_order",
    frequency: "high",
    context: "Near my house has a supermarket, so shopping is easy.",
  },
  {
    vietlish: "On the table has my phone",
    natural: "My phone is on the table",
    sourcePattern: "Tren ban co dien thoai cua toi -> place plus co for existence",
    category: "word_order",
    frequency: "medium",
    context: "On the table has my phone. Can you bring it?",
  },
  {
    vietlish: "I go to store",
    natural: "I go to the store",
    sourcePattern: "Toi di cua hang -> Vietnamese has no articles like a/the",
    category: "literal_translation",
    frequency: "high",
    context: "After work I go to store near my house.",
  },
  {
    vietlish: "She is teacher",
    natural: "She is a teacher",
    sourcePattern: "Co ay la giao vien -> Vietnamese job nouns do not need a/an",
    category: "literal_translation",
    frequency: "high",
    context: "She is teacher at my son's school.",
  },
  {
    vietlish: "I bought new phone",
    natural: "I bought a new phone",
    sourcePattern: "Toi mua dien thoai moi -> Vietnamese omits indefinite article",
    category: "literal_translation",
    frequency: "high",
    context: "I bought new phone yesterday.",
  },
  {
    vietlish: "He has car",
    natural: "He has a car",
    sourcePattern: "Anh ay co xe hoi -> no article before singular count noun in Vietnamese",
    category: "literal_translation",
    frequency: "high",
    context: "He has car, so he can drive us.",
  },
  {
    vietlish: "I need umbrella",
    natural: "I need an umbrella",
    sourcePattern: "Toi can o -> no a/an distinction in Vietnamese",
    category: "literal_translation",
    frequency: "medium",
    context: "It is raining, so I need umbrella.",
  },
  {
    vietlish: "She has two cat",
    natural: "She has two cats",
    sourcePattern: "Co ay co hai con meo -> Vietnamese nouns do not take plural -s after numbers",
    category: "literal_translation",
    frequency: "high",
    context: "She has two cat in her apartment.",
  },
  {
    vietlish: "Many student like English",
    natural: "Many students like English",
    sourcePattern: "Nhieu hoc sinh thich tieng Anh -> plural is marked by quantity word, not noun ending",
    category: "literal_translation",
    frequency: "high",
    context: "Many student like English but fear speaking.",
  },
  {
    vietlish: "I have three question",
    natural: "I have three questions",
    sourcePattern: "Toi co ba cau hoi -> no plural suffix on noun after number",
    category: "literal_translation",
    frequency: "high",
    context: "I have three question about the lesson.",
  },
  {
    vietlish: "There are many house here",
    natural: "There are many houses here",
    sourcePattern: "Co nhieu nha o day -> noun stays unchanged after many",
    category: "literal_translation",
    frequency: "medium",
    context: "There are many house here for rent.",
  },
  {
    vietlish: "Yesterday I go to market",
    natural: "Yesterday I went to the market",
    sourcePattern: "Vietnamese uses time words such as hom qua instead of verb conjugation",
    category: "literal_translation",
    frequency: "high",
    context: "Yesterday I go to market with my mother.",
  },
  {
    vietlish: "Last week I see him",
    natural: "Last week I saw him",
    sourcePattern: "Vietnamese verbs do not change form for past time",
    category: "literal_translation",
    frequency: "high",
    context: "Last week I see him at the bank.",
  },
  {
    vietlish: "Two days ago she buy a laptop",
    natural: "Two days ago she bought a laptop",
    sourcePattern: "Da / hom qua / ago context marks past without verb inflection",
    category: "literal_translation",
    frequency: "high",
    context: "Two days ago she buy a laptop for school.",
  },
  {
    vietlish: "When I was child, I live in Hue",
    natural: "When I was a child, I lived in Hue",
    sourcePattern: "Vietnamese past context can carry tense for the whole clause",
    category: "literal_translation",
    frequency: "medium",
    context: "When I was child, I live in Hue with my grandparents.",
  },
  {
    vietlish: "Tomorrow I go to Canada",
    natural: "Tomorrow I am going to Canada",
    sourcePattern: "Ngay mai marks future; Vietnamese does not require auxiliary will/be going to",
    category: "literal_translation",
    frequency: "high",
    context: "Tomorrow I go to Canada for work.",
  },
  {
    vietlish: "Next month she have exam",
    natural: "Next month she has an exam",
    sourcePattern: "Future time phrase carries time; verb form and article are unmarked in Vietnamese",
    category: "literal_translation",
    frequency: "medium",
    context: "Next month she have exam at university.",
  },
  {
    vietlish: "I very like this song",
    natural: "I really like this song",
    sourcePattern: "Rat can intensify adjectives and some verbs in Vietnamese; learners map it to very",
    category: "calque",
    frequency: "high",
    context: "I very like this song because it is relaxing.",
  },
  {
    vietlish: "I very miss my family",
    natural: "I really miss my family",
    sourcePattern: "Rat nho -> rat is overmapped to very before English verbs",
    category: "calque",
    frequency: "high",
    context: "I very miss my family when I live abroad.",
  },
  {
    vietlish: "This food is too delicious",
    natural: "This food is so delicious",
    sourcePattern: "Qua ngon -> qua can mean very/so, but too often means excessive in English",
    category: "false_friend",
    frequency: "high",
    context: "This food is too delicious. I want to eat more.",
  },
  {
    vietlish: "Your dress is too beautiful",
    natural: "Your dress is so beautiful",
    sourcePattern: "Qua dep -> qua as praise maps incorrectly to too",
    category: "false_friend",
    frequency: "high",
    context: "Your dress is too beautiful for the party.",
  },
  {
    vietlish: "He is sympathetic",
    natural: "He is nice",
    sourcePattern: "co cam tinh / de thuong can mean likable or nice, not necessarily sympathetic",
    category: "false_friend",
    frequency: "medium",
    context: "My new coworker is very sympathetic and always helps me.",
  },
  {
    vietlish: "I feel boring",
    natural: "I feel bored",
    sourcePattern: "chan can describe the feeling without English -ed/-ing adjective split",
    category: "false_friend",
    frequency: "high",
    context: "I feel boring when I wait at the airport.",
  },
  {
    vietlish: "I am interesting in English",
    natural: "I am interested in English",
    sourcePattern: "thich / co hung thu does not require interested versus interesting distinction",
    category: "false_friend",
    frequency: "high",
    context: "I am interesting in English because I need it for work.",
  },
  {
    vietlish: "My job is pressure",
    natural: "My job is stressful",
    sourcePattern: "ap luc means pressure; learners use the noun where English uses stressful",
    category: "false_friend",
    frequency: "medium",
    context: "My job is pressure during the holiday season.",
  },
  {
    vietlish: "This problem is headache",
    natural: "This problem is a headache",
    sourcePattern: "dau dau can describe a troublesome issue; article and idiom shape differ",
    category: "literal_translation",
    frequency: "medium",
    context: "This problem is headache for our team.",
  },
  {
    vietlish: "I am hot in my body",
    natural: "I feel hot",
    sourcePattern: "nong trong nguoi -> body-state phrase translated literally",
    category: "literal_translation",
    frequency: "medium",
    context: "I am hot in my body after walking outside.",
  },
  {
    vietlish: "I lost sleep",
    natural: "I could not sleep",
    sourcePattern: "mat ngu -> literally lose sleep, often means have insomnia/could not sleep",
    category: "literal_translation",
    frequency: "medium",
    context: "Last night I lost sleep because I drank coffee.",
  },
  {
    vietlish: "I go first",
    natural: "I should leave now",
    sourcePattern: "toi di truoc -> polite leaving formula literally says go first",
    category: "literal_translation",
    frequency: "medium",
    context: "It is late, so I go first. See you tomorrow.",
  },
  {
    vietlish: "I invite you eat",
    natural: "Let me treat you to a meal",
    sourcePattern: "moi ban an -> moi can mean invite/offer/treat depending on context",
    category: "calque",
    frequency: "medium",
    context: "For your birthday, I invite you eat tonight.",
  },
  {
    vietlish: "You eat already?",
    natural: "Have you eaten yet?",
    sourcePattern: "Ban an chua? -> Vietnamese question uses already/yet idea without auxiliary",
    category: "literal_translation",
    frequency: "medium",
    context: "You eat already? We can go for lunch.",
  },
  {
    vietlish: "Long time no meet",
    natural: "Long time no see",
    sourcePattern: "Lau roi khong gap -> gap means meet/see; English fixed phrase uses see",
    category: "collocation",
    frequency: "medium",
    context: "Long time no meet! How are you?",
  },
  {
    vietlish: "Wish you a nice day",
    natural: "Have a nice day",
    sourcePattern: "Chuc ban mot ngay tot lanh -> subjectless wish greeting maps directly",
    category: "register",
    frequency: "high",
    context: "Thanks for calling. Wish you a nice day!",
  },
  {
    vietlish: "I wish you have good health",
    natural: "I hope you stay healthy",
    sourcePattern: "Chuc ban suc khoe -> chuc maps to wish, but casual English often uses hope",
    category: "register",
    frequency: "medium",
    context: "I wish you have good health after your trip.",
  },
  {
    vietlish: "Dear teacher, I have a question",
    natural: "Hi teacher, I have a question",
    sourcePattern: "Vietnamese school English often teaches Dear for many messages, even casual chat",
    category: "register",
    frequency: "medium",
    context: "Dear teacher, I have a question about homework.",
  },
  {
    vietlish: "I kindly request you to help me",
    natural: "Could you help me?",
    sourcePattern: "Formal request templates from school/business English overused in casual contexts",
    category: "register",
    frequency: "medium",
    context: "I kindly request you to help me with this app login.",
  },
  {
    vietlish: "Please reply me soonest",
    natural: "Please reply as soon as you can",
    sourcePattern: "Business-email register and reply me pattern transferred into general English",
    category: "register",
    frequency: "medium",
    context: "I sent the document. Please reply me soonest.",
  },
  {
    vietlish: "Give me your phone number",
    natural: "Could I have your phone number?",
    sourcePattern: "Cho toi so dien thoai cua ban -> direct imperative is natural in Vietnamese but too direct in formal English",
    category: "register",
    frequency: "high",
    context: "At the front desk I said, Give me your phone number.",
  },
  {
    vietlish: "You must send me the file today",
    natural: "Could you send me the file today?",
    sourcePattern: "Phai / can can be direct in Vietnamese task talk; English workplace requests soften modal force",
    category: "register",
    frequency: "medium",
    context: "I emailed my manager, You must send me the file today.",
  },
  {
    vietlish: "Why you do that?",
    natural: "Why did you do that?",
    sourcePattern: "Tai sao ban lam vay? -> Vietnamese question order has no do-support inversion",
    category: "word_order",
    frequency: "high",
    context: "Why you do that in the meeting yesterday?",
  },
  {
    vietlish: "You like coffee?",
    natural: "Do you like coffee?",
    sourcePattern: "Ban thich ca phe khong? -> question particle/order, no auxiliary do",
    category: "word_order",
    frequency: "high",
    context: "You like coffee? I can make one for you.",
  },
  {
    vietlish: "Where you live?",
    natural: "Where do you live?",
    sourcePattern: "Ban song o dau? -> wh-question without English do-support",
    category: "word_order",
    frequency: "high",
    context: "Where you live in Calgary?",
  },
  {
    vietlish: "How to say this word?",
    natural: "How do you say this word?",
    sourcePattern: "Noi tu nay nhu the nao? -> impersonal Vietnamese question maps to how to",
    category: "word_order",
    frequency: "high",
    context: "Teacher, how to say this word in English?",
  },
  {
    vietlish: "I don't know how can I do it",
    natural: "I don't know how I can do it",
    sourcePattern: "Embedded questions often keep direct-question order after translation",
    category: "word_order",
    frequency: "medium",
    context: "I don't know how can I do it without help.",
  },
  {
    vietlish: "Can you borrow me your pen?",
    natural: "Can you lend me your pen?",
    sourcePattern: "muon can mean borrow, and cho muon means lend; direction is often confused",
    category: "false_friend",
    frequency: "high",
    context: "Can you borrow me your pen for one minute?",
  },
  {
    vietlish: "I borrow him money",
    natural: "I lend him money",
    sourcePattern: "cho muon tien -> muon maps to borrow, but English changes verb by direction",
    category: "false_friend",
    frequency: "medium",
    context: "Sometimes I borrow him money when he needs help.",
  },

  // === Professional-context Vietlish: diaspora professions ===

  // Nail salon
  {
    vietlish: "do gel",
    natural: "do a gel manicure",
    sourcePattern: "lam gel -> lam = do/make is the all-purpose verb for any service",
    category: "collocation",
    frequency: "high",
    context: "You want do gel today or just regular color?",
  },
  {
    vietlish: "take off nail",
    natural: "remove the old polish",
    sourcePattern: "thao mong / lay ra -> generic take off; missing article and wrong noun for polish",
    category: "literal_translation",
    frequency: "high",
    context: "First I take off nail, then I do new color for you.",
  },
  {
    vietlish: "you want design",
    natural: "would you like a design?",
    sourcePattern: "VN yes/no question by intonation drops do/would and the article",
    category: "literal_translation",
    frequency: "high",
    context: "You want design on this finger or all plain?",
  },
  {
    vietlish: "sit here please I do for you",
    natural: "please have a seat and I'll take care of you",
    sourcePattern: "moi ngoi day -> chained imperatives; 'do for you' calques lam cho",
    category: "literal_translation",
    frequency: "medium",
    context: "Sit here please I do for you now, very fast.",
  },
  {
    vietlish: "your nail is dry already",
    natural: "your nails are dry now",
    sourcePattern: "kho roi -> roi marks completion as 'already'; missing plural",
    category: "calque",
    frequency: "high",
    context: "Don't touch anything, your nail is dry already.",
  },
  {
    vietlish: "cut skin",
    natural: "trim the cuticles",
    sourcePattern: "cat da -> literal cut + skin for cuticle",
    category: "literal_translation",
    frequency: "medium",
    context: "I cut skin first, then push back, okay?",
  },
  {
    vietlish: "you choose color",
    natural: "go ahead and pick a color",
    sourcePattern: "drops the imperative softener and the article",
    category: "literal_translation",
    frequency: "high",
    context: "Here is the book, you choose color you like.",
  },
  {
    vietlish: "make your nail beautiful",
    natural: "make your nails look nice",
    sourcePattern: "lam dep mong -> lam dep = make beautiful; missing plural",
    category: "collocation",
    frequency: "medium",
    context: "Don't worry, I make your nail beautiful for the party.",
  },
  {
    vietlish: "thirty dollar",
    natural: "thirty dollars",
    sourcePattern: "VN nouns are not marked for plural, so the price stays singular",
    category: "literal_translation",
    frequency: "high",
    context: "Gel and pedicure together is thirty dollar.",
  },
  {
    vietlish: "you wait five minute",
    natural: "it'll be about five minutes",
    sourcePattern: "missing plural and a dropped subject 'it'",
    category: "literal_translation",
    frequency: "medium",
    context: "Color is drying, you wait five minute please.",
  },
  {
    vietlish: "same like last time",
    natural: "the same as last time",
    sourcePattern: "giong nhu -> giong = same and nhu maps to 'like' instead of 'as'",
    category: "collocation",
    frequency: "high",
    context: "You want same like last time, French tip?",
  },
  {
    vietlish: "I do nice for you",
    natural: "I'll do a nice job for you",
    sourcePattern: "lam ky cho -> adverb 'nice' plus the 'do for you' calque of lam cho",
    category: "literal_translation",
    frequency: "medium",
    context: "Don't worry, I do nice for you, you come back again.",
  },

  // Restaurant
  {
    vietlish: "you want drink first",
    natural: "would you like something to drink first?",
    sourcePattern: "drops do/would and the article 'a drink'; VN asks by intonation",
    category: "literal_translation",
    frequency: "high",
    context: "Welcome, please sit, you want drink first?",
  },
  {
    vietlish: "this one is spicy already",
    natural: "this one is already spicy",
    sourcePattern: "cay roi -> roi = already is placed sentence-final in VN",
    category: "calque",
    frequency: "high",
    context: "Be careful, this one is spicy already, no need more chili.",
  },
  {
    vietlish: "I bring for you",
    natural: "I'll bring it right over",
    sourcePattern: "mang cho -> mang = bring + cho = for; the object is dropped",
    category: "calque",
    frequency: "high",
    context: "Your soup is ready, I bring for you now.",
  },
  {
    vietlish: "you eat here or take away",
    natural: "is that for here or to go?",
    sourcePattern: "an o day hay mang ve -> word-for-word rendering",
    category: "literal_translation",
    frequency: "high",
    context: "You eat here or take away today?",
  },
  {
    vietlish: "table for how many",
    natural: "how many people?",
    sourcePattern: "ban may nguoi -> the question word stays at the end",
    category: "word_order",
    frequency: "medium",
    context: "Hello, welcome, table for how many?",
  },
  {
    vietlish: "it is finish",
    natural: "we're out of it",
    sourcePattern: "het roi -> het = run out gets mapped to 'finish'",
    category: "false_friend",
    frequency: "medium",
    context: "Sorry, the beef pho it is finish for today.",
  },
  {
    vietlish: "you want more rice",
    natural: "would you like more rice?",
    sourcePattern: "drops the do/would auxiliary in a yes/no question",
    category: "literal_translation",
    frequency: "high",
    context: "You want more rice? Refill is free.",
  },
  {
    vietlish: "I recommend you this one",
    natural: "I'd recommend this one",
    sourcePattern: "goi y cho ban -> recommend takes a double object as in VN",
    category: "collocation",
    frequency: "medium",
    context: "If you like spicy, I recommend you this one.",
  },
  {
    vietlish: "spicy or no spicy",
    natural: "mild or spicy?",
    sourcePattern: "cay hay khong cay -> khong = 'no' used for negation",
    category: "literal_translation",
    frequency: "high",
    context: "Your noodle, you want spicy or no spicy?",
  },
  {
    vietlish: "wait a little bit",
    natural: "it'll just be a moment",
    sourcePattern: "doi mot chut -> 'a little bit' stands in for a short time",
    category: "collocation",
    frequency: "high",
    context: "Kitchen is busy now, wait a little bit, okay?",
  },
  {
    vietlish: "just cook this morning",
    natural: "it was just cooked this morning",
    sourcePattern: "moi nau -> missing the be-verb and the -ed participle",
    category: "literal_translation",
    frequency: "medium",
    context: "The fish very fresh, just cook this morning.",
  },
  {
    vietlish: "pay here or pay card",
    natural: "will you be paying cash or card?",
    sourcePattern: "tra tien mat hay the -> elliptical, no auxiliary",
    category: "literal_translation",
    frequency: "medium",
    context: "When you finish, pay here or pay card both okay.",
  },

  // Healthcare
  {
    vietlish: "you have pain where",
    natural: "where does it hurt?",
    sourcePattern: "ban dau o dau -> the wh-word 'where' stays in place at the end",
    category: "word_order",
    frequency: "high",
    context: "Tell me, you have pain where exactly?",
  },
  {
    vietlish: "take medicine two time",
    natural: "take the medicine twice a day",
    sourcePattern: "uong thuoc hai lan -> uong = drink/take; missing plural and 'a day'",
    category: "literal_translation",
    frequency: "high",
    context: "This pill you take medicine two time, morning and night.",
  },
  {
    vietlish: "you come back next week",
    natural: "please come back next week",
    sourcePattern: "tuan sau quay lai -> drops the imperative softener",
    category: "literal_translation",
    frequency: "high",
    context: "If it still hurts, you come back next week, okay?",
  },
  {
    vietlish: "how long you have this",
    natural: "how long have you had this?",
    sourcePattern: "drops the auxiliary and tense; VN has no perfect aspect",
    category: "word_order",
    frequency: "high",
    context: "This cough, how long you have this?",
  },
  {
    vietlish: "you have fever or no",
    natural: "do you have a fever?",
    sourcePattern: "co sot khong -> the 'khong' tag becomes 'or no'; missing auxiliary and article",
    category: "literal_translation",
    frequency: "medium",
    context: "Last night you have fever or no?",
  },
  {
    vietlish: "open your mouth big",
    natural: "open wide",
    sourcePattern: "ha mieng to -> the adjective 'big' stands in for the adverb 'wide'",
    category: "collocation",
    frequency: "medium",
    context: "Okay, open your mouth big and say ah.",
  },
  {
    vietlish: "you must drink a lot water",
    natural: "you should drink plenty of water",
    sourcePattern: "uong nhieu nuoc -> 'a lot water' drops 'of'; 'must' is too strong for advice",
    category: "register",
    frequency: "medium",
    context: "When you have fever, you must drink a lot water.",
  },
  {
    vietlish: "I give you medicine three day",
    natural: "I'll give you three days of medication",
    sourcePattern: "drops the future, the plural, and 'of'",
    category: "literal_translation",
    frequency: "medium",
    context: "Take this, I give you medicine three day, then we see.",
  },
  {
    vietlish: "your blood pressure high",
    natural: "your blood pressure is high",
    sourcePattern: "VN adjectives are verbal, so the copula 'is' is dropped",
    category: "literal_translation",
    frequency: "high",
    context: "Today your blood pressure high, we check again next time.",
  },
  {
    vietlish: "you sick how many day",
    natural: "how many days have you been sick?",
    sourcePattern: "benh may ngay -> wh-phrase at the end; missing plural and perfect",
    category: "word_order",
    frequency: "medium",
    context: "You sick how many day already?",
  },
  {
    vietlish: "you no eat before blood test",
    natural: "don't eat before the blood test",
    sourcePattern: "khong an -> 'no' for the negative imperative; missing article",
    category: "literal_translation",
    frequency: "medium",
    context: "Tomorrow morning you no eat before blood test.",
  },
  {
    vietlish: "do you feel better more",
    natural: "are you feeling any better?",
    sourcePattern: "co do hon khong -> 'more' is added redundantly after the comparative",
    category: "collocation",
    frequency: "low",
    context: "After the pill, do you feel better more?",
  },

  // Driver
  {
    vietlish: "you go to where",
    natural: "where are you headed?",
    sourcePattern: "di dau -> the wh-word stays in place at the end (VN in-situ)",
    category: "word_order",
    frequency: "high",
    context: "Hello, welcome, you go to where today?",
  },
  {
    vietlish: "traffic is jam",
    natural: "the traffic is heavy",
    sourcePattern: "ket xe -> 'jam' is used as a predicate adjective",
    category: "collocation",
    frequency: "high",
    context: "Sorry I am late, traffic is jam everywhere now.",
  },
  {
    vietlish: "I pick you at 8",
    natural: "I'll pick you up at 8",
    sourcePattern: "don ban -> drops the particle 'up' and the future",
    category: "literal_translation",
    frequency: "high",
    context: "Tomorrow I pick you at 8 in front of the hotel.",
  },
  {
    vietlish: "you sit front or back",
    natural: "would you like to sit in the front or the back?",
    sourcePattern: "ngoi truoc hay sau -> drops the preposition and article",
    category: "literal_translation",
    frequency: "medium",
    context: "You sit front or back, both okay for me.",
  },
  {
    vietlish: "the road is many car",
    natural: "there are a lot of cars on the road",
    sourcePattern: "duong nhieu xe -> existential 'has/is many car' calque plus missing plural",
    category: "word_order",
    frequency: "medium",
    context: "Now is rush hour, the road is many car.",
  },
  {
    vietlish: "I wait you outside",
    natural: "I'll wait for you outside",
    sourcePattern: "doi ban -> 'wait' used without 'for'",
    category: "collocation",
    frequency: "high",
    context: "You go shopping, I wait you outside, no problem.",
  },
  {
    vietlish: "you have small money",
    natural: "do you have any small change?",
    sourcePattern: "tien le -> 'small money' calques the term for change",
    category: "literal_translation",
    frequency: "high",
    context: "Fifty is too big, you have small money?",
  },
  {
    vietlish: "we almost arrive",
    natural: "we're almost there",
    sourcePattern: "gan toi roi -> 'arrive' stands in for 'there'; the be-verb is dropped",
    category: "literal_translation",
    frequency: "medium",
    context: "Don't worry, we almost arrive, two minute more.",
  },
  {
    vietlish: "close door strong",
    natural: "shut the door firmly",
    sourcePattern: "dong cua manh -> the adjective 'strong' stands in for the adverb",
    category: "collocation",
    frequency: "medium",
    context: "The door is old, you close door strong, okay?",
  },
  {
    vietlish: "your address what number",
    natural: "what's the house number?",
    sourcePattern: "so may -> fragmented, wh-word at the end",
    category: "word_order",
    frequency: "medium",
    context: "This is the street, your address what number?",
  },
  {
    vietlish: "I drop you here can",
    natural: "is it okay if I drop you here?",
    sourcePattern: "tha o day duoc khong -> the 'duoc khong' permission tag goes to the end",
    category: "word_order",
    frequency: "medium",
    context: "Cannot stop long here, I drop you here can?",
  },
  {
    vietlish: "which way you want",
    natural: "which way would you like to go?",
    sourcePattern: "drops the auxiliary and the verb of motion",
    category: "literal_translation",
    frequency: "low",
    context: "Highway or small road, which way you want?",
  },

  // Tech worker
  {
    vietlish: "I will check and revert",
    natural: "I'll check and get back to you",
    sourcePattern: "'revert' is misused to mean reply/respond in Asian business English",
    category: "false_friend",
    frequency: "high",
    context: "Thanks for the bug report, I will check and revert.",
  },
  {
    vietlish: "please help me to review",
    natural: "could you review this for me?",
    sourcePattern: "giup toi review -> 'help me to + verb' calques giup toi",
    category: "collocation",
    frequency: "high",
    context: "When you have time, please help me to review my PR.",
  },
  {
    vietlish: "the code is not work",
    natural: "the code isn't working",
    sourcePattern: "drops -ing and agreement; VN verbs are not conjugated",
    category: "literal_translation",
    frequency: "high",
    context: "I tried already but the code is not work on my machine.",
  },
  {
    vietlish: "please do the needful",
    natural: "please take care of it",
    sourcePattern: "an Asian business-English cliche adopted in VN tech teams",
    category: "register",
    frequency: "medium",
    context: "The ticket is urgent, please do the needful today.",
  },
  {
    vietlish: "I am blocking",
    natural: "I'm blocked",
    sourcePattern: "bi block -> the passive is dropped, leaving an active form",
    category: "literal_translation",
    frequency: "medium",
    context: "I cannot continue, I am blocking by the API team.",
  },
  {
    vietlish: "can you share me the file",
    natural: "can you share the file with me?",
    sourcePattern: "chia se cho toi -> 'share me' double object, dropping 'with'",
    category: "collocation",
    frequency: "high",
    context: "Can you share me the design file before standup?",
  },
  {
    vietlish: "I already done",
    natural: "I've already finished",
    sourcePattern: "xong roi -> drops the auxiliary have/am",
    category: "literal_translation",
    frequency: "high",
    context: "No need to remind me, I already done that part.",
  },
  {
    vietlish: "it has many bug",
    natural: "it has a lot of bugs",
    sourcePattern: "nhieu bug -> the plural is not marked",
    category: "literal_translation",
    frequency: "medium",
    context: "This module is old, it has many bug.",
  },
  {
    vietlish: "please confirm me",
    natural: "please confirm with me",
    sourcePattern: "xac nhan cho toi -> 'confirm me' calques the dative cho toi",
    category: "collocation",
    frequency: "medium",
    context: "Before we deploy, please confirm me the version.",
  },
  {
    vietlish: "it work on my machine",
    natural: "it works on my machine",
    sourcePattern: "drops the third-person -s agreement",
    category: "literal_translation",
    frequency: "high",
    context: "I don't understand the error, it work on my machine.",
  },
  {
    vietlish: "I push code already",
    natural: "I've already pushed the code",
    sourcePattern: "push roi -> drops the perfect aspect; 'already' goes sentence-final",
    category: "word_order",
    frequency: "high",
    context: "You can pull now, I push code already.",
  },
  {
    vietlish: "I open the bug",
    natural: "I'll file a ticket for the bug",
    sourcePattern: "mo -> 'open' calques the verb for create/file a ticket",
    category: "calque",
    frequency: "low",
    context: "I open the bug in Jira now so we can track it.",
  },

  // Hospitality
  {
    vietlish: "your room is ready already",
    natural: "your room is ready now",
    sourcePattern: "san sang roi -> roi = already is redundant with 'ready'",
    category: "calque",
    frequency: "high",
    context: "Good news sir, your room is ready already.",
  },
  {
    vietlish: "you need anything more",
    natural: "is there anything else you need?",
    sourcePattern: "can gi them -> 'more' stands in for 'else'; no wh-fronting",
    category: "collocation",
    frequency: "high",
    context: "Before I go, you need anything more?",
  },
  {
    vietlish: "check out time is 12",
    natural: "the check-out time is noon",
    sourcePattern: "drops the article 'the' before the noun phrase",
    category: "literal_translation",
    frequency: "medium",
    context: "Just to remind you, check out time is 12, no late please.",
  },
  {
    vietlish: "I help you carry luggage",
    natural: "let me help you with your luggage",
    sourcePattern: "giup ban xach -> drops the future and the possessive 'your'",
    category: "collocation",
    frequency: "medium",
    context: "Welcome, I help you carry luggage to the room.",
  },
  {
    vietlish: "you stay how many night",
    natural: "how many nights are you staying?",
    sourcePattern: "o may dem -> wh-phrase at the end; missing plural",
    category: "word_order",
    frequency: "high",
    context: "For the booking, you stay how many night?",
  },
  {
    vietlish: "breakfast is open from 7",
    natural: "breakfast is served from 7",
    sourcePattern: "mo cua -> 'open' calques the verb for served/available",
    category: "calque",
    frequency: "high",
    context: "In the morning, breakfast is open from 7 to 10.",
  },
  {
    vietlish: "the room have two bed",
    natural: "the room has two beds",
    sourcePattern: "drops the agreement and the plural marker",
    category: "literal_translation",
    frequency: "high",
    context: "This room have two bed, good for the family.",
  },
  {
    vietlish: "you want wake up call",
    natural: "would you like a wake-up call?",
    sourcePattern: "drops do/would and the article in a yes/no question",
    category: "literal_translation",
    frequency: "medium",
    context: "You have early flight, you want wake up call?",
  },
  {
    vietlish: "sorry for the inconvenient",
    natural: "sorry for the inconvenience",
    sourcePattern: "the adjective 'inconvenient' is used where the noun is needed",
    category: "false_friend",
    frequency: "medium",
    context: "The lift is repairing today, sorry for the inconvenient.",
  },
  {
    vietlish: "the price is included breakfast",
    natural: "the price includes breakfast",
    sourcePattern: "da bao gom -> a passive 'is included' replaces the active verb",
    category: "literal_translation",
    frequency: "medium",
    context: "Don't worry, the price is included breakfast and wifi.",
  },
  {
    vietlish: "you can leave luggage here also",
    natural: "you can leave your luggage here too",
    sourcePattern: "cung -> 'also' goes sentence-final and 'your' is dropped",
    category: "word_order",
    frequency: "low",
    context: "After check out, you can leave luggage here also.",
  },
  {
    vietlish: "I will arrange for you",
    natural: "I'll arrange it for you",
    sourcePattern: "sap xep cho ban -> the object 'it' is dropped",
    category: "collocation",
    frequency: "medium",
    context: "You want late check out? I will arrange for you.",
  },
] as const satisfies readonly VietlishCorpusEntry[];
