export type VietlishCorpusCategory =
  | "calque"
  | "word_order"
  | "register"
  | "collocation"
  | "false_friend"
  | "literal_translation";

export type VietlishCorpusFrequency = "high" | "medium" | "low";

export type VietlishCorpusEntry = {
  vietlish: string;
  natural: string;
  sourcePattern: string;
  category: VietlishCorpusCategory;
  frequency: VietlishCorpusFrequency;
  context: string;
};

export const VIETLISH_CORPUS = [
  {
    vietlish: "open the light",
    natural: "turn on the light",
    sourcePattern: "mo den -> mo means open, used for activating lights and devices",
    category: "calque",
    frequency: "high",
    context: "Can you open the light? It is too dark here.",
  },
  {
    vietlish: "close the light",
    natural: "turn off the light",
    sourcePattern: "tat den / dong can map to stop or close; learners overuse close for deactivation",
    category: "calque",
    frequency: "high",
    context: "Please close the light before you sleep.",
  },
  {
    vietlish: "open the air conditioner",
    natural: "turn on the air conditioner",
    sourcePattern: "mo may lanh -> mo is used for switching appliances on",
    category: "calque",
    frequency: "high",
    context: "It is hot, so I will open the air conditioner.",
  },
  {
    vietlish: "close the fan",
    natural: "turn off the fan",
    sourcePattern: "tat quat / dong as a general stop-close idea for devices",
    category: "calque",
    frequency: "high",
    context: "Can you close the fan? I feel cold.",
  },
  {
    vietlish: "open the computer",
    natural: "turn on the computer",
    sourcePattern: "mo may tinh -> mo means open/start for machines",
    category: "calque",
    frequency: "low",
    context: "I open the computer every morning to check email.",
  },
  {
    vietlish: "close the computer",
    natural: "shut down the computer",
    sourcePattern: "tat may tinh -> tat is a broad off action; close is overgeneralized from Vietnamese",
    category: "calque",
    frequency: "low",
    context: "I forgot to close the computer last night.",
  },
  {
    vietlish: "play with my friends",
    natural: "hang out with my friends",
    sourcePattern: "di choi voi ban -> choi means play but also go out socially",
    category: "calque",
    frequency: "high",
    context: "On Sunday I play with my friends at the mall.",
  },
  {
    vietlish: "go play coffee",
    natural: "go out for coffee",
    sourcePattern: "di choi / di ca phe -> social leisure is often expressed with choi or di",
    category: "literal_translation",
    frequency: "low",
    context: "After work we go play coffee near my office.",
  },
  {
    vietlish: "take a bath",
    natural: "take a shower",
    sourcePattern: "tam covers bathing and showering; learners choose bath for daily showering",
    category: "collocation",
    frequency: "high",
    context: "I take a bath quickly before going to work.",
  },
  {
    vietlish: "learn lesson",
    natural: "study the lesson",
    sourcePattern: "hoc bai -> hoc can mean learn or study; bai means lesson/homework",
    category: "collocation",
    frequency: "high",
    context: "I need to learn lesson before the test tomorrow.",
  },
  {
    vietlish: "learn English center",
    natural: "study at an English center",
    sourcePattern: "hoc trung tam Anh ngu -> hoc plus place without English preposition",
    category: "literal_translation",
    frequency: "high",
    context: "My sister learns English center every evening.",
  },
  {
    vietlish: "go to the hometown",
    natural: "go back to my hometown",
    sourcePattern: "ve que -> ve carries return-home meaning",
    category: "calque",
    frequency: "low",
    context: "This weekend I will go to the hometown.",
  },
  {
    vietlish: "eat rice",
    natural: "have a meal",
    sourcePattern: "an com means eat rice literally but often means have a meal",
    category: "literal_translation",
    frequency: "high",
    context: "Did you eat rice yet?",
  },
  {
    vietlish: "drink medicine",
    natural: "take medicine",
    sourcePattern: "uong thuoc -> uong means drink and is used for medicine",
    category: "collocation",
    frequency: "high",
    context: "The doctor told me to drink medicine twice a day.",
  },
  {
    vietlish: "make homework",
    natural: "do homework",
    sourcePattern: "lam bai tap -> lam can mean do or make",
    category: "collocation",
    frequency: "high",
    context: "I make homework after dinner.",
  },
  {
    vietlish: "do a mistake",
    natural: "make a mistake",
    sourcePattern: "lam sai / lam loi -> lam can map to do, but English uses make a mistake",
    category: "collocation",
    frequency: "low",
    context: "I did a mistake in the interview.",
  },
  {
    vietlish: "say with me",
    natural: "tell me",
    sourcePattern: "noi voi toi -> noi voi maps word-for-word to say with",
    category: "calque",
    frequency: "medium",
    context: "Can you say with me the address again?",
  },
  {
    vietlish: "explain me",
    natural: "explain it to me",
    sourcePattern: "giai thich cho toi -> Vietnamese object marking differs from English explain to",
    category: "collocation",
    frequency: "medium",
    context: "Please explain me this grammar.",
  },
  {
    vietlish: "discuss about the problem",
    natural: "discuss the problem",
    sourcePattern: "thao luan ve -> ve means about; English discuss usually takes a direct object",
    category: "collocation",
    frequency: "medium",
    context: "We need to discuss about the problem today.",
  },
  {
    vietlish: "mention about that",
    natural: "mention that",
    sourcePattern: "de cap ve -> ve means about; mention usually does not take about",
    category: "collocation",
    frequency: "medium",
    context: "She mentioned about that in the meeting.",
  },
  {
    vietlish: "contact with me",
    natural: "contact me",
    sourcePattern: "lien he voi toi -> voi means with; English contact takes a direct object",
    category: "collocation",
    frequency: "high",
    context: "Please contact with me when you arrive.",
  },
  {
    vietlish: "marry with him",
    natural: "marry him",
    sourcePattern: "cuoi voi anh ay -> voi means with; English marry takes a direct object",
    category: "collocation",
    frequency: "medium",
    context: "She will marry with him next year.",
  },
  {
    vietlish: "listen music",
    natural: "listen to music",
    sourcePattern: "nghe nhac -> Vietnamese places object after hear/listen without to",
    category: "literal_translation",
    frequency: "high",
    context: "I listen music when I study.",
  },
  {
    vietlish: "wait you",
    natural: "wait for you",
    sourcePattern: "cho ban -> Vietnamese verb cho takes the object directly",
    category: "literal_translation",
    frequency: "high",
    context: "I will wait you outside the station.",
  },
  {
    vietlish: "enter university",
    natural: "get into university",
    sourcePattern: "vao dai hoc -> vao means enter/go into for school admission",
    category: "calque",
    frequency: "medium",
    context: "My brother entered university last year.",
  },
  {
    vietlish: "I yesterday went to store",
    natural: "I went to the store yesterday",
    sourcePattern: "Hom qua toi di cua hang -> Vietnamese commonly places time before the verb phrase",
    category: "word_order",
    frequency: "high",
    context: "I yesterday went to store to buy milk.",
  },
  {
    vietlish: "I tomorrow will meet you",
    natural: "I will meet you tomorrow",
    sourcePattern: "Ngay mai toi se gap ban -> time phrase comes early before the action",
    category: "word_order",
    frequency: "high",
    context: "I tomorrow will meet you after class.",
  },
  {
    vietlish: "She every day goes to work by bus",
    natural: "She goes to work by bus every day",
    sourcePattern: "Co ay moi ngay di lam bang xe buyt -> frequency marker before verb",
    category: "word_order",
    frequency: "medium",
    context: "She every day goes to work by bus.",
  },
  {
    vietlish: "I in the morning drink coffee",
    natural: "I drink coffee in the morning",
    sourcePattern: "Toi buoi sang uong ca phe -> Vietnamese can place time after subject before verb",
    category: "word_order",
    frequency: "medium",
    context: "I in the morning drink coffee with my wife.",
  },
  {
    vietlish: "My hometown, it is very beautiful",
    natural: "My hometown is very beautiful",
    sourcePattern: "Que toi, no rat dep -> topic-comment structure with resumptive pronoun",
    category: "word_order",
    frequency: "high",
    context: "My hometown, it is very beautiful in spring.",
  },
  {
    vietlish: "This book I like very much",
    natural: "I like this book very much",
    sourcePattern: "Quyen sach nay toi rat thich -> topic-fronting before subject",
    category: "word_order",
    frequency: "high",
    context: "This book I like very much because it is simple.",
  },
  {
    vietlish: "English I study every day",
    natural: "I study English every day",
    sourcePattern: "Tieng Anh toi hoc moi ngay -> object/topic before subject",
    category: "word_order",
    frequency: "high",
    context: "English I study every day for my job.",
  },
  {
    vietlish: "The room has many people",
    natural: "There are many people in the room",
    sourcePattern: "Trong phong co nhieu nguoi -> co can map to have/exist",
    category: "literal_translation",
    frequency: "high",
    context: "The room has many people, so it is noisy.",
  },
  {
    vietlish: "My family has five people",
    natural: "There are five people in my family",
    sourcePattern: "Gia dinh toi co nam nguoi -> co means have/there are",
    category: "literal_translation",
    frequency: "high",
    context: "My family has five people and we live in Da Nang.",
  },
  {
    vietlish: "Near my house has a supermarket",
    natural: "There is a supermarket near my house",
    sourcePattern: "Gan nha toi co sieu thi -> location plus co existence pattern",
    category: "word_order",
    frequency: "high",
    context: "Near my house has a supermarket, so shopping is easy.",
  },
  {
    vietlish: "On the table has my phone",
    natural: "My phone is on the table",
    sourcePattern: "Tren ban co dien thoai cua toi -> place plus co for existence",
    category: "word_order",
    frequency: "medium",
    context: "On the table has my phone. Can you bring it?",
  },
  {
    vietlish: "I go to store",
    natural: "I go to the store",
    sourcePattern: "Toi di cua hang -> Vietnamese has no articles like a/the",
    category: "literal_translation",
    frequency: "high",
    context: "After work I go to store near my house.",
  },
  {
    vietlish: "She is teacher",
    natural: "She is a teacher",
    sourcePattern: "Co ay la giao vien -> Vietnamese job nouns do not need a/an",
    category: "literal_translation",
    frequency: "high",
    context: "She is teacher at my son's school.",
  },
  {
    vietlish: "I bought new phone",
    natural: "I bought a new phone",
    sourcePattern: "Toi mua dien thoai moi -> Vietnamese omits indefinite article",
    category: "literal_translation",
    frequency: "high",
    context: "I bought new phone yesterday.",
  },
  {
    vietlish: "He has car",
    natural: "He has a car",
    sourcePattern: "Anh ay co xe hoi -> no article before singular count noun in Vietnamese",
    category: "literal_translation",
    frequency: "high",
    context: "He has car, so he can drive us.",
  },
  {
    vietlish: "I need umbrella",
    natural: "I need an umbrella",
    sourcePattern: "Toi can o -> no a/an distinction in Vietnamese",
    category: "literal_translation",
    frequency: "medium",
    context: "It is raining, so I need umbrella.",
  },
  {
    vietlish: "She has two cat",
    natural: "She has two cats",
    sourcePattern: "Co ay co hai con meo -> Vietnamese nouns do not take plural -s after numbers",
    category: "literal_translation",
    frequency: "high",
    context: "She has two cat in her apartment.",
  },
  {
    vietlish: "Many student like English",
    natural: "Many students like English",
    sourcePattern: "Nhieu hoc sinh thich tieng Anh -> plural is marked by quantity word, not noun ending",
    category: "literal_translation",
    frequency: "high",
    context: "Many student like English but fear speaking.",
  },
  {
    vietlish: "I have three question",
    natural: "I have three questions",
    sourcePattern: "Toi co ba cau hoi -> no plural suffix on noun after number",
    category: "literal_translation",
    frequency: "high",
    context: "I have three question about the lesson.",
  },
  {
    vietlish: "There are many house here",
    natural: "There are many houses here",
    sourcePattern: "Co nhieu nha o day -> noun stays unchanged after many",
    category: "literal_translation",
    frequency: "medium",
    context: "There are many house here for rent.",
  },
  {
    vietlish: "Yesterday I go to market",
    natural: "Yesterday I went to the market",
    sourcePattern: "Vietnamese uses time words such as hom qua instead of verb conjugation",
    category: "literal_translation",
    frequency: "high",
    context: "Yesterday I go to market with my mother.",
  },
  {
    vietlish: "Last week I see him",
    natural: "Last week I saw him",
    sourcePattern: "Vietnamese verbs do not change form for past time",
    category: "literal_translation",
    frequency: "high",
    context: "Last week I see him at the bank.",
  },
  {
    vietlish: "Two days ago she buy a laptop",
    natural: "Two days ago she bought a laptop",
    sourcePattern: "Da / hom qua / ago context marks past without verb inflection",
    category: "literal_translation",
    frequency: "high",
    context: "Two days ago she buy a laptop for school.",
  },
  {
    vietlish: "When I was child, I live in Hue",
    natural: "When I was a child, I lived in Hue",
    sourcePattern: "Vietnamese past context can carry tense for the whole clause",
    category: "literal_translation",
    frequency: "medium",
    context: "When I was child, I live in Hue with my grandparents.",
  },
  {
    vietlish: "Tomorrow I go to Canada",
    natural: "Tomorrow I am going to Canada",
    sourcePattern: "Ngay mai marks future; Vietnamese does not require auxiliary will/be going to",
    category: "literal_translation",
    frequency: "high",
    context: "Tomorrow I go to Canada for work.",
  },
  {
    vietlish: "Next month she have exam",
    natural: "Next month she has an exam",
    sourcePattern: "Future time phrase carries time; verb form and article are unmarked in Vietnamese",
    category: "literal_translation",
    frequency: "medium",
    context: "Next month she have exam at university.",
  },
  {
    vietlish: "I very like this song",
    natural: "I really like this song",
    sourcePattern: "Rat can intensify adjectives and some verbs in Vietnamese; learners map it to very",
    category: "calque",
    frequency: "high",
    context: "I very like this song because it is relaxing.",
  },
  {
    vietlish: "I very miss my family",
    natural: "I really miss my family",
    sourcePattern: "Rat nho -> rat is overmapped to very before English verbs",
    category: "calque",
    frequency: "high",
    context: "I very miss my family when I live abroad.",
  },
  {
    vietlish: "This food is too delicious",
    natural: "This food is so delicious",
    sourcePattern: "Qua ngon -> qua can mean very/so, but too often means excessive in English",
    category: "false_friend",
    frequency: "high",
    context: "This food is too delicious. I want to eat more.",
  },
  {
    vietlish: "Your dress is too beautiful",
    natural: "Your dress is so beautiful",
    sourcePattern: "Qua dep -> qua as praise maps incorrectly to too",
    category: "false_friend",
    frequency: "high",
    context: "Your dress is too beautiful for the party.",
  },
  {
    vietlish: "He is sympathetic",
    natural: "He is nice",
    sourcePattern: "co cam tinh / de thuong can mean likable or nice, not necessarily sympathetic",
    category: "false_friend",
    frequency: "medium",
    context: "My new coworker is very sympathetic and always helps me.",
  },
  {
    vietlish: "I feel boring",
    natural: "I feel bored",
    sourcePattern: "chan can describe the feeling without English -ed/-ing adjective split",
    category: "false_friend",
    frequency: "high",
    context: "I feel boring when I wait at the airport.",
  },
  {
    vietlish: "I am interesting in English",
    natural: "I am interested in English",
    sourcePattern: "thich / co hung thu does not require interested versus interesting distinction",
    category: "false_friend",
    frequency: "high",
    context: "I am interesting in English because I need it for work.",
  },
  {
    vietlish: "My job is pressure",
    natural: "My job is stressful",
    sourcePattern: "ap luc means pressure; learners use the noun where English uses stressful",
    category: "false_friend",
    frequency: "medium",
    context: "My job is pressure during the holiday season.",
  },
  {
    vietlish: "This problem is headache",
    natural: "This problem is a headache",
    sourcePattern: "dau dau can describe a troublesome issue; article and idiom shape differ",
    category: "literal_translation",
    frequency: "medium",
    context: "This problem is headache for our team.",
  },
  {
    vietlish: "I am hot in my body",
    natural: "I feel hot",
    sourcePattern: "nong trong nguoi -> body-state phrase translated literally",
    category: "literal_translation",
    frequency: "medium",
    context: "I am hot in my body after walking outside.",
  },
  {
    vietlish: "I lost sleep",
    natural: "I could not sleep",
    sourcePattern: "mat ngu -> literally lose sleep, often means have insomnia/could not sleep",
    category: "literal_translation",
    frequency: "medium",
    context: "Last night I lost sleep because I drank coffee.",
  },
  {
    vietlish: "I go first",
    natural: "I should leave now",
    sourcePattern: "toi di truoc -> polite leaving formula literally says go first",
    category: "literal_translation",
    frequency: "medium",
    context: "It is late, so I go first. See you tomorrow.",
  },
  {
    vietlish: "I invite you eat",
    natural: "Let me treat you to a meal",
    sourcePattern: "moi ban an -> moi can mean invite/offer/treat depending on context",
    category: "calque",
    frequency: "medium",
    context: "For your birthday, I invite you eat tonight.",
  },
  {
    vietlish: "You eat already?",
    natural: "Have you eaten yet?",
    sourcePattern: "Ban an chua? -> Vietnamese question uses already/yet idea without auxiliary",
    category: "literal_translation",
    frequency: "medium",
    context: "You eat already? We can go for lunch.",
  },
  {
    vietlish: "Long time no meet",
    natural: "Long time no see",
    sourcePattern: "Lau roi khong gap -> gap means meet/see; English fixed phrase uses see",
    category: "collocation",
    frequency: "medium",
    context: "Long time no meet! How are you?",
  },
  {
    vietlish: "Wish you a nice day",
    natural: "Have a nice day",
    sourcePattern: "Chuc ban mot ngay tot lanh -> subjectless wish greeting maps directly",
    category: "register",
    frequency: "high",
    context: "Thanks for calling. Wish you a nice day!",
  },
  {
    vietlish: "I wish you have good health",
    natural: "I hope you stay healthy",
    sourcePattern: "Chuc ban suc khoe -> chuc maps to wish, but casual English often uses hope",
    category: "register",
    frequency: "medium",
    context: "I wish you have good health after your trip.",
  },
  {
    vietlish: "Dear teacher, I have a question",
    natural: "Hi teacher, I have a question",
    sourcePattern: "Vietnamese school English often teaches Dear for many messages, even casual chat",
    category: "register",
    frequency: "medium",
    context: "Dear teacher, I have a question about homework.",
  },
  {
    vietlish: "I kindly request you to help me",
    natural: "Could you help me?",
    sourcePattern: "Formal request templates from school/business English overused in casual contexts",
    category: "register",
    frequency: "medium",
    context: "I kindly request you to help me with this app login.",
  },
  {
    vietlish: "Please reply me soonest",
    natural: "Please reply as soon as you can",
    sourcePattern: "Business-email register and reply me pattern transferred into general English",
    category: "register",
    frequency: "medium",
    context: "I sent the document. Please reply me soonest.",
  },
  {
    vietlish: "Give me your phone number",
    natural: "Could I have your phone number?",
    sourcePattern: "Cho toi so dien thoai cua ban -> direct imperative is natural in Vietnamese but too direct in formal English",
    category: "register",
    frequency: "high",
    context: "At the front desk I said, Give me your phone number.",
  },
  {
    vietlish: "You must send me the file today",
    natural: "Could you send me the file today?",
    sourcePattern: "Phai / can can be direct in Vietnamese task talk; English workplace requests soften modal force",
    category: "register",
    frequency: "medium",
    context: "I emailed my manager, You must send me the file today.",
  },
  {
    vietlish: "Why you do that?",
    natural: "Why did you do that?",
    sourcePattern: "Tai sao ban lam vay? -> Vietnamese question order has no do-support inversion",
    category: "word_order",
    frequency: "high",
    context: "Why you do that in the meeting yesterday?",
  },
  {
    vietlish: "You like coffee?",
    natural: "Do you like coffee?",
    sourcePattern: "Ban thich ca phe khong? -> question particle/order, no auxiliary do",
    category: "word_order",
    frequency: "high",
    context: "You like coffee? I can make one for you.",
  },
  {
    vietlish: "Where you live?",
    natural: "Where do you live?",
    sourcePattern: "Ban song o dau? -> wh-question without English do-support",
    category: "word_order",
    frequency: "high",
    context: "Where you live in Calgary?",
  },
  {
    vietlish: "How to say this word?",
    natural: "How do you say this word?",
    sourcePattern: "Noi tu nay nhu the nao? -> impersonal Vietnamese question maps to how to",
    category: "word_order",
    frequency: "high",
    context: "Teacher, how to say this word in English?",
  },
  {
    vietlish: "I don't know how can I do it",
    natural: "I don't know how I can do it",
    sourcePattern: "Embedded questions often keep direct-question order after translation",
    category: "word_order",
    frequency: "medium",
    context: "I don't know how can I do it without help.",
  },
  {
    vietlish: "Can you borrow me your pen?",
    natural: "Can you lend me your pen?",
    sourcePattern: "muon can mean borrow, and cho muon means lend; direction is often confused",
    category: "false_friend",
    frequency: "high",
    context: "Can you borrow me your pen for one minute?",
  },
  {
    vietlish: "I borrow him money",
    natural: "I lend him money",
    sourcePattern: "cho muon tien -> muon maps to borrow, but English changes verb by direction",
    category: "false_friend",
    frequency: "medium",
    context: "Sometimes I borrow him money when he needs help.",
  },
] as const satisfies readonly VietlishCorpusEntry[];
