export type VietlishCorpusCategory =
  | "calque"
  | "word_order"
  | "register"
  | "collocation"
  | "false_friend"
  | "literal_translation";

export type VietlishCorpusFrequency = "high" | "medium" | "low";

export type VietlishCorpusEntry = {
  vietlish: string;
  natural: string;
  sourcePattern: string;
  category: VietlishCorpusCategory;
  frequency: VietlishCorpusFrequency;
  context: string;
};

export const VIETLISH_CORPUS = [
  {
    vietlish: "open the light",
    natural: "turn on the light",
    sourcePattern: "mo den -> mo means open, used for activating lights and devices",
    category: "calque",
    frequency: "high",
    context: "Can you open the light? It is too dark here.",
  },
  {
    vietlish: "close the light",
    natural: "turn off the light",
    sourcePattern: "tat den / dong can map to stop or close; learners overuse close for deactivation",
    category: "calque",
    frequency: "high",
    context: "Please close the light before you sleep.",
  },
  {
    vietlish: "open the air conditioner",
    natural: "turn on the air conditioner",
    sourcePattern: "mo may lanh -> mo is used for switching appliances on",
    category: "calque",
    frequency: "high",
    context: "It is hot, so I will open the air conditioner.",
  },
  {
    vietlish: "close the fan",
    natural: "turn off the fan",
    sourcePattern: "tat quat / dong as a general stop-close idea for devices",
    category: "calque",
    frequency: "high",
    context: "Can you close the fan? I feel cold.",
  },
  {
    vietlish: "open the computer",
    natural: "turn on the computer",
    sourcePattern: "mo may tinh -> mo means open/start for machines",
    category: "calque",
    frequency: "low",
    context: "I open the computer every morning to check email.",
  },
  {
    vietlish: "close the computer",
    natural: "shut down the computer",
    sourcePattern: "tat may tinh -> tat is a broad off action; close is overgeneralized from Vietnamese",
    category: "calque",
    frequency: "low",
    context: "I forgot to close the computer last night.",
  },
  {
    vietlish: "play with my friends",
    natural: "hang out with my friends",
    sourcePattern: "di choi voi ban -> choi means play but also go out socially",
    category: "calque",
    frequency: "high",
    context: "On Sunday I play with my friends at the mall.",
  },
  {
    vietlish: "go play coffee",
    natural: "go out for coffee",
    sourcePattern: "di choi / di ca phe -> social leisure is often expressed with choi or di",
    category: "literal_translation",
    frequency: "low",
    context: "After work we go play coffee near my office.",
  },
  {
    vietlish: "take a bath",
    natural: "take a shower",
    sourcePattern: "tam covers bathing and showering; learners choose bath for daily showering",
    category: "collocation",
    frequency: "high",
    context: "I take a bath quickly before going to work.",
  },
  {
    vietlish: "learn lesson",
    natural: "study the lesson",
    sourcePattern: "hoc bai -> hoc can mean learn or study; bai means lesson/homework",
    category: "collocation",
    frequency: "high",
    context: "I need to learn lesson before the test tomorrow.",
  },
  {
    vietlish: "learn English center",
    natural: "study at an English center",
    sourcePattern: "hoc trung tam Anh ngu -> hoc plus place without English preposition",
    category: "literal_translation",
    frequency: "high",
    context: "My sister learns English center every evening.",
  },
  {
    vietlish: "go to the hometown",
    natural: "go back to my hometown",
    sourcePattern: "ve que -> ve carries return-home meaning",
    category: "calque",
    frequency: "low",
    context: "This weekend I will go to the hometown.",
  },
  {
    vietlish: "eat rice",
    natural: "have a meal",
    sourcePattern: "an com means eat rice literally but often means have a meal",
    category: "literal_translation",
    frequency: "high",
    context: "Did you eat rice yet?",
  },
  {
    vietlish: "drink medicine",
    natural: "take medicine",
    sourcePattern: "uong thuoc -> uong means drink and is used for medicine",
    category: "collocation",
    frequency: "high",
    context: "The doctor told me to drink medicine twice a day.",
  },
  {
    vietlish: "make homework",
    natural: "do homework",
    sourcePattern: "lam bai tap -> lam can mean do or make",
    category: "collocation",
    frequency: "high",
    context: "I make homework after dinner.",
  },
  {
    vietlish: "do a mistake",
    natural: "make a mistake",
    sourcePattern: "lam sai / lam loi -> lam can map to do, but English uses make a mistake",
    category: "collocation",
    frequency: "low",
    context: "I did a mistake in the interview.",
  },
  {
    vietlish: "say with me",
    natural: "tell me",
    sourcePattern: "noi voi toi -> noi voi maps word-for-word to say with",
    category: "calque",
    frequency: "medium",
    context: "Can you say with me the address again?",
  },
  {
    vietlish: "explain me",
    natural: "explain it to me",
    sourcePattern: "giai thich cho toi -> Vietnamese object marking differs from English explain to",
    category: "collocation",
    frequency: "medium",
    context: "Please explain me this grammar.",
  },
  {
    vietlish: "discuss about the problem",
    natural: "discuss the problem",
    sourcePattern: "thao luan ve -> ve means about; English discuss usually takes a direct object",
    category: "collocation",
    frequency: "medium",
    context: "We need to discuss about the problem today.",
  },
  {
    vietlish: "mention about that",
    natural: "mention that",
    sourcePattern: "de cap ve -> ve means about; mention usually does not take about",
    category: "collocation",
    frequency: "medium",
    context: "She mentioned about that in the meeting.",
  },
  {
    vietlish: "contact with me",
    natural: "contact me",
    sourcePattern: "lien he voi toi -> voi means with; English contact takes a direct object",
    category: "collocation",
    frequency: "high",
    context: "Please contact with me when you arrive.",
  },
  {
    vietlish: "marry with him",
    natural: "marry him",
    sourcePattern: "cuoi voi anh ay -> voi means with; English marry takes a direct object",
    category: "collocation",
    frequency: "medium",
    context: "She will marry with him next year.",
  },
  {
    vietlish: "listen music",
    natural: "listen to music",
    sourcePattern: "nghe nhac -> Vietnamese places object after hear/listen without to",
    category: "literal_translation",
    frequency: "high",
    context: "I listen music when I study.",
  },
  {
    vietlish: "wait you",
    natural: "wait for you",
    sourcePattern: "cho ban -> Vietnamese verb cho takes the object directly",
    category: "literal_translation",
    frequency: "high",
    context: "I will wait you outside the station.",
  },
  {
    vietlish: "enter university",
    natural: "get into university",
    sourcePattern: "vao dai hoc -> vao means enter/go into for school admission",
    category: "calque",
    frequency: "medium",
    context: "My brother entered university last year.",
  },
  {
    vietlish: "I yesterday went to store",
    natural: "I went to the store yesterday",
    sourcePattern: "Hom qua toi di cua hang -> Vietnamese commonly places time before the verb phrase",
    category: "word_order",
    frequency: "high",
    context: "I yesterday went to store to buy milk.",
  },
  {
    vietlish: "I tomorrow will meet you",
    natural: "I will meet you tomorrow",
    sourcePattern: "Ngay mai toi se gap ban -> time phrase comes early before the action",
    category: "word_order",
    frequency: "high",
    context: "I tomorrow will meet you after class.",
  },
  {
    vietlish: "She every day goes to work by bus",
    natural: "She goes to work by bus every day",
    sourcePattern: "Co ay moi ngay di lam bang xe buyt -> frequency marker before verb",
    category: "word_order",
    frequency: "medium",
    context: "She every day goes to work by bus.",
  },
  {
    vietlish: "I in the morning drink coffee",
    natural: "I drink coffee in the morning",
    sourcePattern: "Toi buoi sang uong ca phe -> Vietnamese can place time after subject before verb",
    category: "word_order",
    frequency: "medium",
    context: "I in the morning drink coffee with my wife.",
  },
  {
    vietlish: "My hometown, it is very beautiful",
    natural: "My hometown is very beautiful",
    sourcePattern: "Que toi, no rat dep -> topic-comment structure with resumptive pronoun",
    category: "word_order",
    frequency: "high",
    context: "My hometown, it is very beautiful in spring.",
  },
  {
    vietlish: "This book I like very much",
    natural: "I like this book very much",
    sourcePattern: "Quyen sach nay toi rat thich -> topic-fronting before subject",
    category: "word_order",
    frequency: "high",
    context: "This book I like very much because it is simple.",
  },
  {
    vietlish: "English I study every day",
    natural: "I study English every day",
    sourcePattern: "Tieng Anh toi hoc moi ngay -> object/topic before subject",
    category: "word_order",
    frequency: "high",
    context: "English I study every day for my job.",
  },
  {
    vietlish: "The room has many people",
    natural: "There are many people in the room",
    sourcePattern: "Trong phong co nhieu nguoi -> co can map to have/exist",
    category: "literal_translation",
    frequency: "high",
    context: "The room has many people, so it is noisy.",
  },
  {
    vietlish: "My family has five people",
    natural: "There are five people in my family",
    sourcePattern: "Gia dinh toi co nam nguoi -> co means have/there are",
    category: "literal_translation",
    frequency: "high",
    context: "My family has five people and we live in Da Nang.",
  },
  {
    vietlish: "Near my house has a supermarket",
    natural: "There is a supermarket near my house",
    sourcePattern: "Gan nha toi co sieu thi -> location plus co existence pattern",
    category: "word_order",
    frequency: "high",
    context: "Near my house has a supermarket, so shopping is easy.",
  },
  {
    vietlish: "On the table has my phone",
    natural: "My phone is on the table",
    sourcePattern: "Tren ban co dien thoai cua toi -> place plus co for existence",
    category: "word_order",
    frequency: "medium",
    context: "On the table has my phone. Can you bring it?",
  },
  {
    vietlish: "I go to store",
    natural: "I go to the store",
    sourcePattern: "Toi di cua hang -> Vietnamese has no articles like a/the",
    category: "literal_translation",
    frequency: "high",
    context: "After work I go to store near my house.",
  },
  {
    vietlish: "She is teacher",
    natural: "She is a teacher",
    sourcePattern: "Co ay la giao vien -> Vietnamese job nouns do not need a/an",
    category: "literal_translation",
    frequency: "high",
    context: "She is teacher at my son's school.",
  },
  {
    vietlish: "I bought new phone",
    natural: "I bought a new phone",
    sourcePattern: "Toi mua dien thoai moi -> Vietnamese omits indefinite article",
    category: "literal_translation",
    frequency: "high",
    context: "I bought new phone yesterday.",
  },
  {
    vietlish: "He has car",
    natural: "He has a car",
    sourcePattern: "Anh ay co xe hoi -> no article before singular count noun in Vietnamese",
    category: "literal_translation",
    frequency: "high",
    context: "He has car, so he can drive us.",
  },
  {
    vietlish: "I need umbrella",
    natural: "I need an umbrella",
    sourcePattern: "Toi can o -> no a/an distinction in Vietnamese",
    category: "literal_translation",
    frequency: "medium",
    context: "It is raining, so I need umbrella.",
  },
  {
    vietlish: "She has two cat",
    natural: "She has two cats",
    sourcePattern: "Co ay co hai con meo -> Vietnamese nouns do not take plural -s after numbers",
    category: "literal_translation",
    frequency: "high",
    context: "She has two cat in her apartment.",
  },
  {
    vietlish: "Many student like English",
    natural: "Many students like English",
    sourcePattern: "Nhieu hoc sinh thich tieng Anh -> plural is marked by quantity word, not noun ending",
    category: "literal_translation",
    frequency: "high",
    context: "Many student like English but fear speaking.",
  },
  {
    vietlish: "I have three question",
    natural: "I have three questions",
    sourcePattern: "Toi co ba cau hoi -> no plural suffix on noun after number",
    category: "literal_translation",
    frequency: "high",
    context: "I have three question about the lesson.",
  },
  {
    vietlish: "There are many house here",
    natural: "There are many houses here",
    sourcePattern: "Co nhieu nha o day -> noun stays unchanged after many",
    category: "literal_translation",
    frequency: "medium",
    context: "There are many house here for rent.",
  },
  {
    vietlish: "Yesterday I go to market",
    natural: "Yesterday I went to the market",
    sourcePattern: "Vietnamese uses time words such as hom qua instead of verb conjugation",
    category: "literal_translation",
    frequency: "high",
    context: "Yesterday I go to market with my mother.",
  },
  {
    vietlish: "Last week I see him",
    natural: "Last week I saw him",
    sourcePattern: "Vietnamese verbs do not change form for past time",
    category: "literal_translation",
    frequency: "high",
    context: "Last week I see him at the bank.",
  },
  {
    vietlish: "Two days ago she buy a laptop",
    natural: "Two days ago she bought a laptop",
    sourcePattern: "Da / hom qua / ago context marks past without verb inflection",
    category: "literal_translation",
    frequency: "high",
    context: "Two days ago she buy a laptop for school.",
  },
  {
    vietlish: "When I was child, I live in Hue",
    natural: "When I was a child, I lived in Hue",
    sourcePattern: "Vietnamese past context can carry tense for the whole clause",
    category: "literal_translation",
    frequency: "medium",
    context: "When I was child, I live in Hue with my grandparents.",
  },
  {
    vietlish: "Tomorrow I go to Canada",
    natural: "Tomorrow I am going to Canada",
    sourcePattern: "Ngay mai marks future; Vietnamese does not require auxiliary will/be going to",
    category: "literal_translation",
    frequency: "high",
    context: "Tomorrow I go to Canada for work.",
  },
  {
    vietlish: "Next month she have exam",
    natural: "Next month she has an exam",
    sourcePattern: "Future time phrase carries time; verb form and article are unmarked in Vietnamese",
    category: "literal_translation",
    frequency: "medium",
    context: "Next month she have exam at university.",
  },
  {
    vietlish: "I very like this song",
    natural: "I really like this song",
    sourcePattern: "Rat can intensify adjectives and some verbs in Vietnamese; learners map it to very",
    category: "calque",
    frequency: "high",
    context: "I very like this song because it is relaxing.",
  },
  {
    vietlish: "I very miss my family",
    natural: "I really miss my family",
    sourcePattern: "Rat nho -> rat is overmapped to very before English verbs",
    category: "calque",
    frequency: "high",
    context: "I very miss my family when I live abroad.",
  },
  {
    vietlish: "This food is too delicious",
    natural: "This food is so delicious",
    sourcePattern: "Qua ngon -> qua can mean very/so, but too often means excessive in English",
    category: "false_friend",
    frequency: "high",
    context: "This food is too delicious. I want to eat more.",
  },
  {
    vietlish: "Your dress is too beautiful",
    natural: "Your dress is so beautiful",
    sourcePattern: "Qua dep -> qua as praise maps incorrectly to too",
    category: "false_friend",
    frequency: "high",
    context: "Your dress is too beautiful for the party.",
  },
  {
    vietlish: "He is sympathetic",
    natural: "He is nice",
    sourcePattern: "co cam tinh / de thuong can mean likable or nice, not necessarily sympathetic",
    category: "false_friend",
    frequency: "medium",
    context: "My new coworker is very sympathetic and always helps me.",
  },
  {
    vietlish: "I feel boring",
    natural: "I feel bored",
    sourcePattern: "chan can describe the feeling without English -ed/-ing adjective split",
    category: "false_friend",
    frequency: "high",
    context: "I feel boring when I wait at the airport.",
  },
  {
    vietlish: "I am interesting in English",
    natural: "I am interested in English",
    sourcePattern: "thich / co hung thu does not require interested versus interesting distinction",
    category: "false_friend",
    frequency: "high",
    context: "I am interesting in English because I need it for work.",
  },
  {
    vietlish: "My job is pressure",
    natural: "My job is stressful",
    sourcePattern: "ap luc means pressure; learners use the noun where English uses stressful",
    category: "false_friend",
    frequency: "medium",
    context: "My job is pressure during the holiday season.",
  },
  {
    vietlish: "This problem is headache",
    natural: "This problem is a headache",
    sourcePattern: "dau dau can describe a troublesome issue; article and idiom shape differ",
    category: "literal_translation",
    frequency: "medium",
    context: "This problem is headache for our team.",
  },
  {
    vietlish: "I am hot in my body",
    natural: "I feel hot",
    sourcePattern: "nong trong nguoi -> body-state phrase translated literally",
    category: "literal_translation",
    frequency: "medium",
    context: "I am hot in my body after walking outside.",
  },
  {
    vietlish: "I lost sleep",
    natural: "I could not sleep",
    sourcePattern: "mat ngu -> literally lose sleep, often means have insomnia/could not sleep",
    category: "literal_translation",
    frequency: "medium",
    context: "Last night I lost sleep because I drank coffee.",
  },
  {
    vietlish: "I go first",
    natural: "I should leave now",
    sourcePattern: "toi di truoc -> polite leaving formula literally says go first",
    category: "literal_translation",
    frequency: "medium",
    context: "It is late, so I go first. See you tomorrow.",
  },
  {
    vietlish: "I invite you eat",
    natural: "Let me treat you to a meal",
    sourcePattern: "moi ban an -> moi can mean invite/offer/treat depending on context",
    category: "calque",
    frequency: "medium",
    context: "For your birthday, I invite you eat tonight.",
  },
  {
    vietlish: "You eat already?",
    natural: "Have you eaten yet?",
    sourcePattern: "Ban an chua? -> Vietnamese question uses already/yet idea without auxiliary",
    category: "literal_translation",
    frequency: "medium",
    context: "You eat already? We can go for lunch.",
  },
  {
    vietlish: "Long time no meet",
    natural: "Long time no see",
    sourcePattern: "Lau roi khong gap -> gap means meet/see; English fixed phrase uses see",
    category: "collocation",
    frequency: "medium",
    context: "Long time no meet! How are you?",
  },
  {
    vietlish: "Wish you a nice day",
    natural: "Have a nice day",
    sourcePattern: "Chuc ban mot ngay tot lanh -> subjectless wish greeting maps directly",
    category: "register",
    frequency: "high",
    context: "Thanks for calling. Wish you a nice day!",
  },
  {
    vietlish: "I wish you have good health",
    natural: "I hope you stay healthy",
    sourcePattern: "Chuc ban suc khoe -> chuc maps to wish, but casual English often uses hope",
    category: "register",
    frequency: "medium",
    context: "I wish you have good health after your trip.",
  },
  {
    vietlish: "Dear teacher, I have a question",
    natural: "Hi teacher, I have a question",
    sourcePattern: "Vietnamese school English often teaches Dear for many messages, even casual chat",
    category: "register",
    frequency: "medium",
    context: "Dear teacher, I have a question about homework.",
  },
  {
    vietlish: "I kindly request you to help me",
    natural: "Could you help me?",
    sourcePattern: "Formal request templates from school/business English overused in casual contexts",
    category: "register",
    frequency: "medium",
    context: "I kindly request you to help me with this app login.",
  },
  {
    vietlish: "Please reply me soonest",
    natural: "Please reply as soon as you can",
    sourcePattern: "Business-email register and reply me pattern transferred into general English",
    category: "register",
    frequency: "medium",
    context: "I sent the document. Please reply me soonest.",
  },
  {
    vietlish: "Give me your phone number",
    natural: "Could I have your phone number?",
    sourcePattern: "Cho toi so dien thoai cua ban -> direct imperative is natural in Vietnamese but too direct in formal English",
    category: "register",
    frequency: "high",
    context: "At the front desk I said, Give me your phone number.",
  },
  {
    vietlish: "You must send me the file today",
    natural: "Could you send me the file today?",
    sourcePattern: "Phai / can can be direct in Vietnamese task talk; English workplace requests soften modal force",
    category: "register",
    frequency: "medium",
    context: "I emailed my manager, You must send me the file today.",
  },
  {
    vietlish: "Why you do that?",
    natural: "Why did you do that?",
    sourcePattern: "Tai sao ban lam vay? -> Vietnamese question order has no do-support inversion",
    category: "word_order",
    frequency: "high",
    context: "Why you do that in the meeting yesterday?",
  },
  {
    vietlish: "You like coffee?",
    natural: "Do you like coffee?",
    sourcePattern: "Ban thich ca phe khong? -> question particle/order, no auxiliary do",
    category: "word_order",
    frequency: "high",
    context: "You like coffee? I can make one for you.",
  },
  {
    vietlish: "Where you live?",
    natural: "Where do you live?",
    sourcePattern: "Ban song o dau? -> wh-question without English do-support",
    category: "word_order",
    frequency: "high",
    context: "Where you live in Calgary?",
  },
  {
    vietlish: "How to say this word?",
    natural: "How do you say this word?",
    sourcePattern: "Noi tu nay nhu the nao? -> impersonal Vietnamese question maps to how to",
    category: "word_order",
    frequency: "high",
    context: "Teacher, how to say this word in English?",
  },
  {
    vietlish: "I don't know how can I do it",
    natural: "I don't know how I can do it",
    sourcePattern: "Embedded questions often keep direct-question order after translation",
    category: "word_order",
    frequency: "medium",
    context: "I don't know how can I do it without help.",
  },
  {
    vietlish: "Can you borrow me your pen?",
    natural: "Can you lend me your pen?",
    sourcePattern: "muon can mean borrow, and cho muon means lend; direction is often confused",
    category: "false_friend",
    frequency: "high",
    context: "Can you borrow me your pen for one minute?",
  },
  {
    vietlish: "I borrow him money",
    natural: "I lend him money",
    sourcePattern: "cho muon tien -> muon maps to borrow, but English changes verb by direction",
    category: "false_friend",
    frequency: "medium",
    context: "Sometimes I borrow him money when he needs help.",
  },

  // === Professional-context Vietlish: diaspora professions ===

  // Nail salon
  {
    vietlish: "do gel",
    natural: "do a gel manicure",
    sourcePattern: "lam gel -> lam = do/make is the all-purpose verb for any service",
    category: "collocation",
    frequency: "high",
    context: "You want do gel today or just regular color?",
  },
  {
    vietlish: "take off nail",
    natural: "remove the old polish",
    sourcePattern: "thao mong / lay ra -> generic take off; missing article and wrong noun for polish",
    category: "literal_translation",
    frequency: "high",
    context: "First I take off nail, then I do new color for you.",
  },
  {
    vietlish: "you want design",
    natural: "would you like a design?",
    sourcePattern: "VN yes/no question by intonation drops do/would and the article",
    category: "literal_translation",
    frequency: "high",
    context: "You want design on this finger or all plain?",
  },
  {
    vietlish: "sit here please I do for you",
    natural: "please have a seat and I'll take care of you",
    sourcePattern: "moi ngoi day -> chained imperatives; 'do for you' calques lam cho",
    category: "literal_translation",
    frequency: "medium",
    context: "Sit here please I do for you now, very fast.",
  },
  {
    vietlish: "your nail is dry already",
    natural: "your nails are dry now",
    sourcePattern: "kho roi -> roi marks completion as 'already'; missing plural",
    category: "calque",
    frequency: "high",
    context: "Don't touch anything, your nail is dry already.",
  },
  {
    vietlish: "cut skin",
    natural: "trim the cuticles",
    sourcePattern: "cat da -> literal cut + skin for cuticle",
    category: "literal_translation",
    frequency: "medium",
    context: "I cut skin first, then push back, okay?",
  },
  {
    vietlish: "you choose color",
    natural: "go ahead and pick a color",
    sourcePattern: "drops the imperative softener and the article",
    category: "literal_translation",
    frequency: "high",
    context: "Here is the book, you choose color you like.",
  },
  {
    vietlish: "make your nail beautiful",
    natural: "make your nails look nice",
    sourcePattern: "lam dep mong -> lam dep = make beautiful; missing plural",
    category: "collocation",
    frequency: "medium",
    context: "Don't worry, I make your nail beautiful for the party.",
  },
  {
    vietlish: "thirty dollar",
    natural: "thirty dollars",
    sourcePattern: "VN nouns are not marked for plural, so the price stays singular",
    category: "literal_translation",
    frequency: "high",
    context: "Gel and pedicure together is thirty dollar.",
  },
  {
    vietlish: "you wait five minute",
    natural: "it'll be about five minutes",
    sourcePattern: "missing plural and a dropped subject 'it'",
    category: "literal_translation",
    frequency: "medium",
    context: "Color is drying, you wait five minute please.",
  },
  {
    vietlish: "same like last time",
    natural: "the same as last time",
    sourcePattern: "giong nhu -> giong = same and nhu maps to 'like' instead of 'as'",
    category: "collocation",
    frequency: "high",
    context: "You want same like last time, French tip?",
  },
  {
    vietlish: "I do nice for you",
    natural: "I'll do a nice job for you",
    sourcePattern: "lam ky cho -> adverb 'nice' plus the 'do for you' calque of lam cho",
    category: "literal_translation",
    frequency: "medium",
    context: "Don't worry, I do nice for you, you come back again.",
  },

  // Restaurant
  {
    vietlish: "you want drink first",
    natural: "would you like something to drink first?",
    sourcePattern: "drops do/would and the article 'a drink'; VN asks by intonation",
    category: "literal_translation",
    frequency: "high",
    context: "Welcome, please sit, you want drink first?",
  },
  {
    vietlish: "this one is spicy already",
    natural: "this one is already spicy",
    sourcePattern: "cay roi -> roi = already is placed sentence-final in VN",
    category: "calque",
    frequency: "high",
    context: "Be careful, this one is spicy already, no need more chili.",
  },
  {
    vietlish: "I bring for you",
    natural: "I'll bring it right over",
    sourcePattern: "mang cho -> mang = bring + cho = for; the object is dropped",
    category: "calque",
    frequency: "high",
    context: "Your soup is ready, I bring for you now.",
  },
  {
    vietlish: "you eat here or take away",
    natural: "is that for here or to go?",
    sourcePattern: "an o day hay mang ve -> word-for-word rendering",
    category: "literal_translation",
    frequency: "high",
    context: "You eat here or take away today?",
  },
  {
    vietlish: "table for how many",
    natural: "how many people?",
    sourcePattern: "ban may nguoi -> the question word stays at the end",
    category: "word_order",
    frequency: "medium",
    context: "Hello, welcome, table for how many?",
  },
  {
    vietlish: "it is finish",
    natural: "we're out of it",
    sourcePattern: "het roi -> het = run out gets mapped to 'finish'",
    category: "false_friend",
    frequency: "medium",
    context: "Sorry, the beef pho it is finish for today.",
  },
  {
    vietlish: "you want more rice",
    natural: "would you like more rice?",
    sourcePattern: "drops the do/would auxiliary in a yes/no question",
    category: "literal_translation",
    frequency: "high",
    context: "You want more rice? Refill is free.",
  },
  {
    vietlish: "I recommend you this one",
    natural: "I'd recommend this one",
    sourcePattern: "goi y cho ban -> recommend takes a double object as in VN",
    category: "collocation",
    frequency: "medium",
    context: "If you like spicy, I recommend you this one.",
  },
  {
    vietlish: "spicy or no spicy",
    natural: "mild or spicy?",
    sourcePattern: "cay hay khong cay -> khong = 'no' used for negation",
    category: "literal_translation",
    frequency: "high",
    context: "Your noodle, you want spicy or no spicy?",
  },
  {
    vietlish: "wait a little bit",
    natural: "it'll just be a moment",
    sourcePattern: "doi mot chut -> 'a little bit' stands in for a short time",
    category: "collocation",
    frequency: "high",
    context: "Kitchen is busy now, wait a little bit, okay?",
  },
  {
    vietlish: "just cook this morning",
    natural: "it was just cooked this morning",
    sourcePattern: "moi nau -> missing the be-verb and the -ed participle",
    category: "literal_translation",
    frequency: "medium",
    context: "The fish very fresh, just cook this morning.",
  },
  {
    vietlish: "pay here or pay card",
    natural: "will you be paying cash or card?",
    sourcePattern: "tra tien mat hay the -> elliptical, no auxiliary",
    category: "literal_translation",
    frequency: "medium",
    context: "When you finish, pay here or pay card both okay.",
  },

  // Healthcare
  {
    vietlish: "you have pain where",
    natural: "where does it hurt?",
    sourcePattern: "ban dau o dau -> the wh-word 'where' stays in place at the end",
    category: "word_order",
    frequency: "high",
    context: "Tell me, you have pain where exactly?",
  },
  {
    vietlish: "take medicine two time",
    natural: "take the medicine twice a day",
    sourcePattern: "uong thuoc hai lan -> uong = drink/take; missing plural and 'a day'",
    category: "literal_translation",
    frequency: "high",
    context: "This pill you take medicine two time, morning and night.",
  },
  {
    vietlish: "you come back next week",
    natural: "please come back next week",
    sourcePattern: "tuan sau quay lai -> drops the imperative softener",
    category: "literal_translation",
    frequency: "high",
    context: "If it still hurts, you come back next week, okay?",
  },
  {
    vietlish: "how long you have this",
    natural: "how long have you had this?",
    sourcePattern: "drops the auxiliary and tense; VN has no perfect aspect",
    category: "word_order",
    frequency: "high",
    context: "This cough, how long you have this?",
  },
  {
    vietlish: "you have fever or no",
    natural: "do you have a fever?",
    sourcePattern: "co sot khong -> the 'khong' tag becomes 'or no'; missing auxiliary and article",
    category: "literal_translation",
    frequency: "medium",
    context: "Last night you have fever or no?",
  },
  {
    vietlish: "open your mouth big",
    natural: "open wide",
    sourcePattern: "ha mieng to -> the adjective 'big' stands in for the adverb 'wide'",
    category: "collocation",
    frequency: "medium",
    context: "Okay, open your mouth big and say ah.",
  },
  {
    vietlish: "you must drink a lot water",
    natural: "you should drink plenty of water",
    sourcePattern: "uong nhieu nuoc -> 'a lot water' drops 'of'; 'must' is too strong for advice",
    category: "register",
    frequency: "medium",
    context: "When you have fever, you must drink a lot water.",
  },
  {
    vietlish: "I give you medicine three day",
    natural: "I'll give you three days of medication",
    sourcePattern: "drops the future, the plural, and 'of'",
    category: "literal_translation",
    frequency: "medium",
    context: "Take this, I give you medicine three day, then we see.",
  },
  {
    vietlish: "your blood pressure high",
    natural: "your blood pressure is high",
    sourcePattern: "VN adjectives are verbal, so the copula 'is' is dropped",
    category: "literal_translation",
    frequency: "high",
    context: "Today your blood pressure high, we check again next time.",
  },
  {
    vietlish: "you sick how many day",
    natural: "how many days have you been sick?",
    sourcePattern: "benh may ngay -> wh-phrase at the end; missing plural and perfect",
    category: "word_order",
    frequency: "medium",
    context: "You sick how many day already?",
  },
  {
    vietlish: "you no eat before blood test",
    natural: "don't eat before the blood test",
    sourcePattern: "khong an -> 'no' for the negative imperative; missing article",
    category: "literal_translation",
    frequency: "medium",
    context: "Tomorrow morning you no eat before blood test.",
  },
  {
    vietlish: "do you feel better more",
    natural: "are you feeling any better?",
    sourcePattern: "co do hon khong -> 'more' is added redundantly after the comparative",
    category: "collocation",
    frequency: "low",
    context: "After the pill, do you feel better more?",
  },

  // Driver
  {
    vietlish: "you go to where",
    natural: "where are you headed?",
    sourcePattern: "di dau -> the wh-word stays in place at the end (VN in-situ)",
    category: "word_order",
    frequency: "high",
    context: "Hello, welcome, you go to where today?",
  },
  {
    vietlish: "traffic is jam",
    natural: "the traffic is heavy",
    sourcePattern: "ket xe -> 'jam' is used as a predicate adjective",
    category: "collocation",
    frequency: "high",
    context: "Sorry I am late, traffic is jam everywhere now.",
  },
  {
    vietlish: "I pick you at 8",
    natural: "I'll pick you up at 8",
    sourcePattern: "don ban -> drops the particle 'up' and the future",
    category: "literal_translation",
    frequency: "high",
    context: "Tomorrow I pick you at 8 in front of the hotel.",
  },
  {
    vietlish: "you sit front or back",
    natural: "would you like to sit in the front or the back?",
    sourcePattern: "ngoi truoc hay sau -> drops the preposition and article",
    category: "literal_translation",
    frequency: "medium",
    context: "You sit front or back, both okay for me.",
  },
  {
    vietlish: "the road is many car",
    natural: "there are a lot of cars on the road",
    sourcePattern: "duong nhieu xe -> existential 'has/is many car' calque plus missing plural",
    category: "word_order",
    frequency: "medium",
    context: "Now is rush hour, the road is many car.",
  },
  {
    vietlish: "I wait you outside",
    natural: "I'll wait for you outside",
    sourcePattern: "doi ban -> 'wait' used without 'for'",
    category: "collocation",
    frequency: "high",
    context: "You go shopping, I wait you outside, no problem.",
  },
  {
    vietlish: "you have small money",
    natural: "do you have any small change?",
    sourcePattern: "tien le -> 'small money' calques the term for change",
    category: "literal_translation",
    frequency: "high",
    context: "Fifty is too big, you have small money?",
  },
  {
    vietlish: "we almost arrive",
    natural: "we're almost there",
    sourcePattern: "gan toi roi -> 'arrive' stands in for 'there'; the be-verb is dropped",
    category: "literal_translation",
    frequency: "medium",
    context: "Don't worry, we almost arrive, two minute more.",
  },
  {
    vietlish: "close door strong",
    natural: "shut the door firmly",
    sourcePattern: "dong cua manh -> the adjective 'strong' stands in for the adverb",
    category: "collocation",
    frequency: "medium",
    context: "The door is old, you close door strong, okay?",
  },
  {
    vietlish: "your address what number",
    natural: "what's the house number?",
    sourcePattern: "so may -> fragmented, wh-word at the end",
    category: "word_order",
    frequency: "medium",
    context: "This is the street, your address what number?",
  },
  {
    vietlish: "I drop you here can",
    natural: "is it okay if I drop you here?",
    sourcePattern: "tha o day duoc khong -> the 'duoc khong' permission tag goes to the end",
    category: "word_order",
    frequency: "medium",
    context: "Cannot stop long here, I drop you here can?",
  },
  {
    vietlish: "which way you want",
    natural: "which way would you like to go?",
    sourcePattern: "drops the auxiliary and the verb of motion",
    category: "literal_translation",
    frequency: "low",
    context: "Highway or small road, which way you want?",
  },

  // Tech worker
  {
    vietlish: "I will check and revert",
    natural: "I'll check and get back to you",
    sourcePattern: "'revert' is misused to mean reply/respond in Asian business English",
    category: "false_friend",
    frequency: "high",
    context: "Thanks for the bug report, I will check and revert.",
  },
  {
    vietlish: "please help me to review",
    natural: "could you review this for me?",
    sourcePattern: "giup toi review -> 'help me to + verb' calques giup toi",
    category: "collocation",
    frequency: "high",
    context: "When you have time, please help me to review my PR.",
  },
  {
    vietlish: "the code is not work",
    natural: "the code isn't working",
    sourcePattern: "drops -ing and agreement; VN verbs are not conjugated",
    category: "literal_translation",
    frequency: "high",
    context: "I tried already but the code is not work on my machine.",
  },
  {
    vietlish: "please do the needful",
    natural: "please take care of it",
    sourcePattern: "an Asian business-English cliche adopted in VN tech teams",
    category: "register",
    frequency: "medium",
    context: "The ticket is urgent, please do the needful today.",
  },
  {
    vietlish: "I am blocking",
    natural: "I'm blocked",
    sourcePattern: "bi block -> the passive is dropped, leaving an active form",
    category: "literal_translation",
    frequency: "medium",
    context: "I cannot continue, I am blocking by the API team.",
  },
  {
    vietlish: "can you share me the file",
    natural: "can you share the file with me?",
    sourcePattern: "chia se cho toi -> 'share me' double object, dropping 'with'",
    category: "collocation",
    frequency: "high",
    context: "Can you share me the design file before standup?",
  },
  {
    vietlish: "I already done",
    natural: "I've already finished",
    sourcePattern: "xong roi -> drops the auxiliary have/am",
    category: "literal_translation",
    frequency: "high",
    context: "No need to remind me, I already done that part.",
  },
  {
    vietlish: "it has many bug",
    natural: "it has a lot of bugs",
    sourcePattern: "nhieu bug -> the plural is not marked",
    category: "literal_translation",
    frequency: "medium",
    context: "This module is old, it has many bug.",
  },
  {
    vietlish: "please confirm me",
    natural: "please confirm with me",
    sourcePattern: "xac nhan cho toi -> 'confirm me' calques the dative cho toi",
    category: "collocation",
    frequency: "medium",
    context: "Before we deploy, please confirm me the version.",
  },
  {
    vietlish: "it work on my machine",
    natural: "it works on my machine",
    sourcePattern: "drops the third-person -s agreement",
    category: "literal_translation",
    frequency: "high",
    context: "I don't understand the error, it work on my machine.",
  },
  {
    vietlish: "I push code already",
    natural: "I've already pushed the code",
    sourcePattern: "push roi -> drops the perfect aspect; 'already' goes sentence-final",
    category: "word_order",
    frequency: "high",
    context: "You can pull now, I push code already.",
  },
  {
    vietlish: "I open the bug",
    natural: "I'll file a ticket for the bug",
    sourcePattern: "mo -> 'open' calques the verb for create/file a ticket",
    category: "calque",
    frequency: "low",
    context: "I open the bug in Jira now so we can track it.",
  },

  // Hospitality
  {
    vietlish: "your room is ready already",
    natural: "your room is ready now",
    sourcePattern: "san sang roi -> roi = already is redundant with 'ready'",
    category: "calque",
    frequency: "high",
    context: "Good news sir, your room is ready already.",
  },
  {
    vietlish: "you need anything more",
    natural: "is there anything else you need?",
    sourcePattern: "can gi them -> 'more' stands in for 'else'; no wh-fronting",
    category: "collocation",
    frequency: "high",
    context: "Before I go, you need anything more?",
  },
  {
    vietlish: "check out time is 12",
    natural: "the check-out time is noon",
    sourcePattern: "drops the article 'the' before the noun phrase",
    category: "literal_translation",
    frequency: "medium",
    context: "Just to remind you, check out time is 12, no late please.",
  },
  {
    vietlish: "I help you carry luggage",
    natural: "let me help you with your luggage",
    sourcePattern: "giup ban xach -> drops the future and the possessive 'your'",
    category: "collocation",
    frequency: "medium",
    context: "Welcome, I help you carry luggage to the room.",
  },
  {
    vietlish: "you stay how many night",
    natural: "how many nights are you staying?",
    sourcePattern: "o may dem -> wh-phrase at the end; missing plural",
    category: "word_order",
    frequency: "high",
    context: "For the booking, you stay how many night?",
  },
  {
    vietlish: "breakfast is open from 7",
    natural: "breakfast is served from 7",
    sourcePattern: "mo cua -> 'open' calques the verb for served/available",
    category: "calque",
    frequency: "high",
    context: "In the morning, breakfast is open from 7 to 10.",
  },
  {
    vietlish: "the room have two bed",
    natural: "the room has two beds",
    sourcePattern: "drops the agreement and the plural marker",
    category: "literal_translation",
    frequency: "high",
    context: "This room have two bed, good for the family.",
  },
  {
    vietlish: "you want wake up call",
    natural: "would you like a wake-up call?",
    sourcePattern: "drops do/would and the article in a yes/no question",
    category: "literal_translation",
    frequency: "medium",
    context: "You have early flight, you want wake up call?",
  },
  {
    vietlish: "sorry for the inconvenient",
    natural: "sorry for the inconvenience",
    sourcePattern: "the adjective 'inconvenient' is used where the noun is needed",
    category: "false_friend",
    frequency: "medium",
    context: "The lift is repairing today, sorry for the inconvenient.",
  },
  {
    vietlish: "the price is included breakfast",
    natural: "the price includes breakfast",
    sourcePattern: "da bao gom -> a passive 'is included' replaces the active verb",
    category: "literal_translation",
    frequency: "medium",
    context: "Don't worry, the price is included breakfast and wifi.",
  },
  {
    vietlish: "you can leave luggage here also",
    natural: "you can leave your luggage here too",
    sourcePattern: "cung -> 'also' goes sentence-final and 'your' is dropped",
    category: "word_order",
    frequency: "low",
    context: "After check out, you can leave luggage here also.",
  },
  {
    vietlish: "I will arrange for you",
    natural: "I'll arrange it for you",
    sourcePattern: "sap xep cho ban -> the object 'it' is dropped",
    category: "collocation",
    frequency: "medium",
    context: "You want late check out? I will arrange for you.",
  },
  {
    vietlish: "the landlord increase price too much",
    natural: "the landlord raised the rent too much",
    sourcePattern: "gia nha -> price is overgeneralized for rent; present-tense verb is used for past/finished action",
    category: "collocation",
    frequency: "medium",
    context: "Last month the landlord increase price too much, so I need to ask about it.",
  },
  {
    vietlish: "my house has leaking water",
    natural: "there is a leak in my apartment",
    sourcePattern: "nha co bi ro nuoc -> existential have replaces there is and apartment/house are conflated",
    category: "literal_translation",
    frequency: "medium",
    context: "My house has leaking water in the bathroom ceiling.",
  },
  {
    vietlish: "I want fix the sink",
    natural: "I want to get the sink fixed",
    sourcePattern: "muon sua -> drops 'to' and uses active fix where English often uses get something fixed",
    category: "collocation",
    frequency: "high",
    context: "I want fix the sink because water is not going down.",
  },
  {
    vietlish: "the heater is not warm",
    natural: "the heat is not working",
    sourcePattern: "khong am -> describes the result instead of the system not working",
    category: "collocation",
    frequency: "medium",
    context: "The heater is not warm since yesterday night.",
  },
  {
    vietlish: "can you repair for me",
    natural: "can you repair it for me?",
    sourcePattern: "sua giup toi -> English needs the object 'it'",
    category: "collocation",
    frequency: "high",
    context: "The cabinet door is broken, can you repair for me?",
  },
  {
    vietlish: "I live in here two year",
    natural: "I have lived here for two years",
    sourcePattern: "o day hai nam -> duration is expressed without for/have lived",
    category: "word_order",
    frequency: "high",
    context: "I live in here two year and always pay rent on time.",
  },
  {
    vietlish: "the neighbor make noise too loud",
    natural: "the neighbor is making too much noise",
    sourcePattern: "lam on -> make noise calque plus adverb order transfer",
    category: "collocation",
    frequency: "medium",
    context: "At midnight the neighbor make noise too loud.",
  },
  {
    vietlish: "I want move out next month",
    natural: "I want to move out next month",
    sourcePattern: "muon + verb -> English infinitive marker 'to' is dropped",
    category: "literal_translation",
    frequency: "high",
    context: "I want move out next month because my job changed.",
  },
  {
    vietlish: "please return deposit for me",
    natural: "please return my deposit to me",
    sourcePattern: "tra lai tien coc cho toi -> possessive and object placement transfer",
    category: "word_order",
    frequency: "medium",
    context: "I cleaned everything, please return deposit for me.",
  },
  {
    vietlish: "the washing machine cannot use",
    natural: "the washing machine cannot be used",
    sourcePattern: "khong su dung duoc -> passive meaning is expressed with active cannot use",
    category: "literal_translation",
    frequency: "medium",
    context: "The washing machine cannot use since Monday.",
  },
  {
    vietlish: "water come out from wall",
    natural: "water is coming out of the wall",
    sourcePattern: "nuoc chay ra tu tuong -> missing progressive and out of phrase",
    category: "word_order",
    frequency: "medium",
    context: "Water come out from wall when I turn on the shower.",
  },
  {
    vietlish: "my room smell bad smell",
    natural: "my room smells bad",
    sourcePattern: "co mui hoi -> repeats smell as noun and verb",
    category: "literal_translation",
    frequency: "medium",
    context: "After the rain, my room smell bad smell.",
  },
  {
    vietlish: "the door lock cannot open",
    natural: "the door lock will not open",
    sourcePattern: "khong mo duoc -> ability/passive transfer with cannot",
    category: "literal_translation",
    frequency: "medium",
    context: "The door lock cannot open, so I am waiting outside.",
  },
  {
    vietlish: "I already pay rent",
    natural: "I have already paid the rent",
    sourcePattern: "da tra tien nha -> already carries perfect meaning; article before rent is dropped",
    category: "literal_translation",
    frequency: "high",
    context: "I already pay rent by e-transfer this morning.",
  },
  {
    vietlish: "the light is broken one",
    natural: "one of the lights is broken",
    sourcePattern: "cai den bi hu mot cai -> classifier/order transfer",
    category: "word_order",
    frequency: "low",
    context: "In the kitchen, the light is broken one.",
  },
  {
    vietlish: "my child have appointment with teacher",
    natural: "my child has an appointment with the teacher",
    sourcePattern: "co hen voi giao vien -> drops agreement and articles",
    category: "literal_translation",
    frequency: "high",
    context: "Tomorrow my child have appointment with teacher.",
  },
  {
    vietlish: "teacher said bring paper home",
    natural: "the teacher said to bring the paper home",
    sourcePattern: "co giao noi mang giay ve -> drops article and infinitive marker",
    category: "literal_translation",
    frequency: "medium",
    context: "Teacher said bring paper home and sign it.",
  },
  {
    vietlish: "my son study grade three",
    natural: "my son is in third grade",
    sourcePattern: "hoc lop ba -> study grade maps directly but English uses be in grade",
    category: "collocation",
    frequency: "high",
    context: "My son study grade three at the public school.",
  },
  {
    vietlish: "he absent school yesterday",
    natural: "he was absent from school yesterday",
    sourcePattern: "vang hoc -> missing be and from",
    category: "collocation",
    frequency: "medium",
    context: "He absent school yesterday because he had a fever.",
  },
  {
    vietlish: "I want talk with teacher",
    natural: "I want to talk to the teacher",
    sourcePattern: "muon noi chuyen voi giao vien -> drops to before verb and uses with for talk to",
    category: "collocation",
    frequency: "high",
    context: "I want talk with teacher about homework.",
  },
  {
    vietlish: "my child not understand lesson",
    natural: "my child does not understand the lesson",
    sourcePattern: "khong hieu bai -> missing auxiliary do and article",
    category: "literal_translation",
    frequency: "high",
    context: "My child not understand lesson about fractions.",
  },
  {
    vietlish: "can you explain homework for me",
    natural: "can you explain the homework to me?",
    sourcePattern: "giai thich bai tap cho toi -> explain takes to me in English",
    category: "collocation",
    frequency: "medium",
    context: "Can you explain homework for me so I can help my daughter?",
  },
  {
    vietlish: "she has test tomorrow math",
    natural: "she has a math test tomorrow",
    sourcePattern: "kiem tra mon toan ngay mai -> modifier order transfer",
    category: "word_order",
    frequency: "medium",
    context: "She has test tomorrow math and she is nervous.",
  },
  {
    vietlish: "I send email already to school",
    natural: "I already sent an email to the school",
    sourcePattern: "da gui email -> already placement and past marking transfer",
    category: "word_order",
    frequency: "medium",
    context: "I send email already to school about the absence.",
  },
  {
    vietlish: "my daughter need practice more English",
    natural: "my daughter needs to practice English more",
    sourcePattern: "can luyen tap them tieng Anh -> drops third-person s and moves more before object",
    category: "word_order",
    frequency: "medium",
    context: "My daughter need practice more English at home.",
  },
  {
    vietlish: "school bus come late every day",
    natural: "the school bus comes late every day",
    sourcePattern: "xe bus den tre -> drops article and third-person s",
    category: "literal_translation",
    frequency: "medium",
    context: "School bus come late every day this week.",
  },
  {
    vietlish: "I want register my kid to school",
    natural: "I want to register my child for school",
    sourcePattern: "dang ky cho con vao truong -> to/for preposition transfer",
    category: "collocation",
    frequency: "medium",
    context: "I want register my kid to school for September.",
  },
  {
    vietlish: "the form need sign",
    natural: "the form needs to be signed",
    sourcePattern: "can ky -> passive meaning without be signed",
    category: "literal_translation",
    frequency: "medium",
    context: "The form need sign before Friday.",
  },
  {
    vietlish: "I have meeting with my boss about salary",
    natural: "I have a meeting with my boss about my salary",
    sourcePattern: "co cuoc hop -> article and possessive often dropped",
    category: "literal_translation",
    frequency: "high",
    context: "I have meeting with my boss about salary tomorrow.",
  },
  {
    vietlish: "I cannot join meeting because busy",
    natural: "I cannot join the meeting because I am busy",
    sourcePattern: "vi ban -> drops subject and be in reason clause",
    category: "literal_translation",
    frequency: "high",
    context: "I cannot join meeting because busy with a customer.",
  },
  {
    vietlish: "please send me document again",
    natural: "please send me the document again",
    sourcePattern: "gui lai tai lieu -> article before singular document is dropped",
    category: "literal_translation",
    frequency: "medium",
    context: "Please send me document again because I cannot open it.",
  },
  {
    vietlish: "I need take day off",
    natural: "I need to take a day off",
    sourcePattern: "can nghi mot ngay -> drops to and article",
    category: "literal_translation",
    frequency: "high",
    context: "I need take day off for my child's appointment.",
  },
  {
    vietlish: "my schedule change already",
    natural: "my schedule has already changed",
    sourcePattern: "da thay doi -> already/perfect meaning without have",
    category: "literal_translation",
    frequency: "medium",
    context: "My schedule change already, so I cannot work Sunday.",
  },
  {
    vietlish: "I will come office late",
    natural: "I will come to the office late",
    sourcePattern: "den cong ty tre -> missing to and article before office",
    category: "literal_translation",
    frequency: "medium",
    context: "I will come office late because the bus is delayed.",
  },
  {
    vietlish: "can you help check this one",
    natural: "can you help me check this?",
    sourcePattern: "giup kiem tra cai nay -> drops object me and uses this one",
    category: "collocation",
    frequency: "medium",
    context: "Can you help check this one before I send it?",
  },
  {
    vietlish: "I am off today already",
    natural: "I am already off today",
    sourcePattern: "da nghi hom nay -> already placement transfer",
    category: "word_order",
    frequency: "low",
    context: "I am off today already, but I can answer tomorrow.",
  },
  {
    vietlish: "we need discuss about customer complaint",
    natural: "we need to discuss the customer complaint",
    sourcePattern: "thao luan ve -> discuss takes a direct object in English",
    category: "collocation",
    frequency: "medium",
    context: "We need discuss about customer complaint this afternoon.",
  },
  {
    vietlish: "I forgot clock in",
    natural: "I forgot to clock in",
    sourcePattern: "quen cham cong -> drops infinitive marker before clock in",
    category: "literal_translation",
    frequency: "medium",
    context: "I forgot clock in when I arrived this morning.",
  },
  {
    vietlish: "the system not allow me",
    natural: "the system does not allow me to do it",
    sourcePattern: "he thong khong cho -> missing auxiliary and object complement",
    category: "literal_translation",
    frequency: "medium",
    context: "The system not allow me to upload the file.",
  },
  {
    vietlish: "I want confirm again with you",
    natural: "I want to confirm it with you again",
    sourcePattern: "xac nhan lai voi ban -> drops to and the object it",
    category: "collocation",
    frequency: "medium",
    context: "I want confirm again with you about the deadline.",
  },
  {
    vietlish: "please advise me what should I do",
    natural: "please advise me on what I should do",
    sourcePattern: "cho toi loi khuyen -> direct advise plus embedded question word order",
    category: "word_order",
    frequency: "low",
    context: "The client changed the request, please advise me what should I do.",
  },
  {
    vietlish: "I need see doctor",
    natural: "I need to see a doctor",
    sourcePattern: "can di kham bac si -> drops to and article",
    category: "literal_translation",
    frequency: "high",
    context: "I need see doctor because my cough is worse.",
  },
  {
    vietlish: "I have pain on my stomach",
    natural: "I have pain in my stomach",
    sourcePattern: "dau o bung -> preposition transfer to on",
    category: "collocation",
    frequency: "medium",
    context: "I have pain on my stomach after eating.",
  },
  {
    vietlish: "my insurance cover or no",
    natural: "does my insurance cover it?",
    sourcePattern: "co bao hiem khong -> yes/no question ending maps to or no",
    category: "word_order",
    frequency: "medium",
    context: "For this medicine, my insurance cover or no?",
  },
  {
    vietlish: "I want book appointment",
    natural: "I want to book an appointment",
    sourcePattern: "muon dat lich hen -> drops to and article",
    category: "literal_translation",
    frequency: "high",
    context: "I want book appointment with the family doctor.",
  },
  {
    vietlish: "my throat is pain",
    natural: "my throat hurts",
    sourcePattern: "dau hong -> uses pain as adjective/noun instead of verb hurts",
    category: "false_friend",
    frequency: "high",
    context: "My throat is pain when I swallow.",
  },
  {
    vietlish: "I cough many",
    natural: "I cough a lot",
    sourcePattern: "ho nhieu -> many is overused for frequency/amount",
    category: "false_friend",
    frequency: "medium",
    context: "At night I cough many and cannot sleep.",
  },
  {
    vietlish: "the medicine make me sleepy too much",
    natural: "the medicine makes me too sleepy",
    sourcePattern: "lam toi buon ngu qua -> too much placement transfer",
    category: "word_order",
    frequency: "medium",
    context: "The medicine make me sleepy too much at work.",
  },
  {
    vietlish: "I need refill medicine",
    natural: "I need to refill my prescription",
    sourcePattern: "lay them thuoc -> medicine/prescription collocation transfer",
    category: "collocation",
    frequency: "medium",
    context: "I need refill medicine before the weekend.",
  },
  {
    vietlish: "I am allergy with peanuts",
    natural: "I am allergic to peanuts",
    sourcePattern: "di ung voi -> adjective form and preposition transfer",
    category: "false_friend",
    frequency: "high",
    context: "Please note I am allergy with peanuts.",
  },
  {
    vietlish: "my appointment is on next Monday",
    natural: "my appointment is next Monday",
    sourcePattern: "vao thu hai toi -> unnecessary on before next Monday",
    category: "collocation",
    frequency: "medium",
    context: "My appointment is on next Monday at 9.",
  },
  {
    vietlish: "can I change other doctor",
    natural: "can I switch to another doctor?",
    sourcePattern: "doi bac si khac -> change other calque",
    category: "collocation",
    frequency: "low",
    context: "If the schedule is full, can I change other doctor?",
  },
  {
    vietlish: "I wait doctor long time",
    natural: "I waited a long time for the doctor",
    sourcePattern: "cho bac si lau -> object order and tense transfer",
    category: "word_order",
    frequency: "medium",
    context: "Yesterday I wait doctor long time in the clinic.",
  },
  {
    vietlish: "the nurse call my name already",
    natural: "the nurse has already called my name",
    sourcePattern: "da goi ten -> already/perfect without have",
    category: "literal_translation",
    frequency: "low",
    context: "The nurse call my name already, so I should go in.",
  },
  {
    vietlish: "I want open bank account",
    natural: "I want to open a bank account",
    sourcePattern: "mo tai khoan -> drops to and article",
    category: "literal_translation",
    frequency: "high",
    context: "I want open bank account for my paycheque.",
  },
  {
    vietlish: "I need deposit money to my account",
    natural: "I need to deposit money into my account",
    sourcePattern: "gui tien vao tai khoan -> to is used instead of into",
    category: "collocation",
    frequency: "medium",
    context: "I need deposit money to my account today.",
  },
  {
    vietlish: "can you print statement for me",
    natural: "can you print the statement for me?",
    sourcePattern: "in sao ke -> article before singular statement is dropped",
    category: "literal_translation",
    frequency: "medium",
    context: "For my visa file, can you print statement for me?",
  },
  {
    vietlish: "my card cannot tap",
    natural: "my card is not tapping",
    sourcePattern: "khong tap duoc -> ability/passive transfer",
    category: "literal_translation",
    frequency: "medium",
    context: "At the store, my card cannot tap.",
  },
  {
    vietlish: "I transfer money wrong person",
    natural: "I transferred money to the wrong person",
    sourcePattern: "chuyen tien nham nguoi -> missing to and past tense",
    category: "literal_translation",
    frequency: "medium",
    context: "I transfer money wrong person by mistake.",
  },
  {
    vietlish: "the fee is take from account",
    natural: "the fee is taken from the account",
    sourcePattern: "bi tru tu tai khoan -> passive form missing participle",
    category: "literal_translation",
    frequency: "low",
    context: "Every month the fee is take from account automatically.",
  },
  {
    vietlish: "I want cancel automatic payment",
    natural: "I want to cancel the automatic payment",
    sourcePattern: "muon huy thanh toan tu dong -> drops to and article",
    category: "literal_translation",
    frequency: "medium",
    context: "I want cancel automatic payment for my gym.",
  },
  {
    vietlish: "how much interest I get",
    natural: "how much interest will I get?",
    sourcePattern: "toi duoc bao nhieu tien lai -> question word order transfer",
    category: "word_order",
    frequency: "low",
    context: "For this savings account, how much interest I get?",
  },
  {
    vietlish: "I forgot my pin number already",
    natural: "I have forgotten my PIN",
    sourcePattern: "da quen -> already/perfect transfer and redundant PIN number",
    category: "literal_translation",
    frequency: "medium",
    context: "I forgot my pin number already and cannot use the card.",
  },
  {
    vietlish: "my cheque is bounce",
    natural: "my cheque bounced",
    sourcePattern: "bi tra lai -> passive be overused with intransitive bounced",
    category: "false_friend",
    frequency: "low",
    context: "The landlord said my cheque is bounce.",
  },
  {
    vietlish: "I need pay tax for government",
    natural: "I need to pay taxes to the government",
    sourcePattern: "dong thue cho nha nuoc -> for/to preposition transfer and plural taxes",
    category: "collocation",
    frequency: "medium",
    context: "Every year I need pay tax for government.",
  },
  {
    vietlish: "I want apply benefit",
    natural: "I want to apply for benefits",
    sourcePattern: "nop don xin tro cap -> apply needs for and benefits often plural",
    category: "collocation",
    frequency: "medium",
    context: "I lost work hours, so I want apply benefit.",
  },
  {
    vietlish: "where I submit document",
    natural: "where do I submit the document?",
    sourcePattern: "nop giay to o dau -> question auxiliary and article are dropped",
    category: "word_order",
    frequency: "high",
    context: "For the form, where I submit document?",
  },
  {
    vietlish: "I need make appointment with immigration",
    natural: "I need to make an appointment with immigration",
    sourcePattern: "can dat lich hen -> drops to and article",
    category: "literal_translation",
    frequency: "medium",
    context: "I need make appointment with immigration about my card.",
  },
  {
    vietlish: "my card expired already",
    natural: "my card has already expired",
    sourcePattern: "da het han -> already/perfect transfer",
    category: "literal_translation",
    frequency: "medium",
    context: "My card expired already, so I need a new one.",
  },
  {
    vietlish: "I wait letter from government",
    natural: "I am waiting for a letter from the government",
    sourcePattern: "cho thu -> wait requires for; articles dropped",
    category: "collocation",
    frequency: "medium",
    context: "I wait letter from government about my application.",
  },
  {
    vietlish: "the office close what time",
    natural: "what time does the office close?",
    sourcePattern: "dong cua may gio -> wh-phrase at the end and missing auxiliary",
    category: "word_order",
    frequency: "high",
    context: "The office close what time today?",
  },
  {
    vietlish: "I need translate paper",
    natural: "I need to translate the document",
    sourcePattern: "dich giay to -> drops to and uses paper for document",
    category: "collocation",
    frequency: "medium",
    context: "I need translate paper before I submit it.",
  },
  {
    vietlish: "can I walk in or need appointment",
    natural: "can I walk in, or do I need an appointment?",
    sourcePattern: "co can hen khong -> second clause drops subject and auxiliary",
    category: "word_order",
    frequency: "medium",
    context: "For the service office, can I walk in or need appointment?",
  },
  {
    vietlish: "I want change address on file",
    natural: "I want to change the address on file",
    sourcePattern: "muon doi dia chi -> drops to and article",
    category: "literal_translation",
    frequency: "medium",
    context: "I want change address on file because I moved.",
  },
  {
    vietlish: "please check status for me",
    natural: "please check the status for me",
    sourcePattern: "kiem tra tinh trang -> article before status is dropped",
    category: "literal_translation",
    frequency: "medium",
    context: "Please check status for me because I applied last month.",
  },
  {
    vietlish: "my name spell wrong",
    natural: "my name is spelled wrong",
    sourcePattern: "ten bi viet sai -> passive be is dropped",
    category: "literal_translation",
    frequency: "medium",
    context: "On the document, my name spell wrong.",
  },
  {
    vietlish: "I need notarize this paper",
    natural: "I need to notarize this document",
    sourcePattern: "cong chung giay to -> drops to and uses paper for document",
    category: "collocation",
    frequency: "low",
    context: "For the application, I need notarize this paper.",
  },
  {
    vietlish: "I just came Canada",
    natural: "I just came to Canada",
    sourcePattern: "moi qua Canada -> movement to a country drops to",
    category: "literal_translation",
    frequency: "medium",
    context: "I just came Canada and need help with the form.",
  },
  {
    vietlish: "I want ask one question",
    natural: "I want to ask one question",
    sourcePattern: "muon hoi mot cau -> drops to before ask",
    category: "literal_translation",
    frequency: "high",
    context: "Before you go, I want ask one question.",
  },
  {
    vietlish: "you free this weekend or no",
    natural: "are you free this weekend?",
    sourcePattern: "co ranh khong -> yes/no tag maps to or no",
    category: "word_order",
    frequency: "medium",
    context: "You free this weekend or no? We can meet.",
  },
  {
    vietlish: "I invite you come my house",
    natural: "I invite you to come to my house",
    sourcePattern: "moi ban den nha toi -> invite needs to plus movement to",
    category: "collocation",
    frequency: "medium",
    context: "Next Sunday I invite you come my house.",
  },
  {
    vietlish: "we go eat outside",
    natural: "we are going out to eat",
    sourcePattern: "di an ngoai -> literal go eat outside",
    category: "literal_translation",
    frequency: "medium",
    context: "Tonight we go eat outside for my birthday.",
  },
  {
    vietlish: "I busy a little",
    natural: "I am a little busy",
    sourcePattern: "hoi ban -> adjective phrase missing be and adverb placement transfer",
    category: "word_order",
    frequency: "high",
    context: "Sorry, I busy a little right now.",
  },
  {
    vietlish: "can you wait me five minute",
    natural: "can you wait for me for five minutes?",
    sourcePattern: "doi toi nam phut -> wait requires for; plural minutes",
    category: "collocation",
    frequency: "high",
    context: "Can you wait me five minute? I am almost ready.",
  },
  {
    vietlish: "I come your house now",
    natural: "I am coming to your house now",
    sourcePattern: "toi qua nha ban -> progressive and to are dropped",
    category: "literal_translation",
    frequency: "medium",
    context: "I come your house now, maybe ten minutes.",
  },
  {
    vietlish: "you bring your wife go together",
    natural: "you can bring your wife with you",
    sourcePattern: "di chung -> go together transferred into bring phrase",
    category: "literal_translation",
    frequency: "low",
    context: "For dinner, you bring your wife go together.",
  },
  {
    vietlish: "I cannot go because rain",
    natural: "I cannot go because it is raining",
    sourcePattern: "vi mua -> drops subject and be in weather clause",
    category: "literal_translation",
    frequency: "high",
    context: "I cannot go because rain is too heavy.",
  },
  {
    vietlish: "we meet at my side",
    natural: "we can meet at my place",
    sourcePattern: "ben toi -> side calque for place/home",
    category: "false_friend",
    frequency: "low",
    context: "If you want, we meet at my side tomorrow.",
  },
  {
    vietlish: "call me when you reach",
    natural: "call me when you arrive",
    sourcePattern: "toi noi -> Indian/Vietnamese English reach used without destination; natural North American English uses arrive",
    category: "collocation",
    frequency: "medium",
    context: "Drive safe and call me when you reach.",
  },
  {
    vietlish: "I message you later more",
    natural: "I'll message you more later",
    sourcePattern: "nhan tin sau them -> adverb order transfer",
    category: "word_order",
    frequency: "low",
    context: "I am at work now, I message you later more.",
  },
  {
    vietlish: "do you want drink coffee with me",
    natural: "do you want to have coffee with me?",
    sourcePattern: "uong ca phe -> drink coffee is grammatical but invitation collocation is have coffee",
    category: "collocation",
    frequency: "medium",
    context: "After class, do you want drink coffee with me?",
  },
  {
    vietlish: "I cannot hear you clear",
    natural: "I cannot hear you clearly",
    sourcePattern: "nghe ro -> adjective clear used instead of adverb clearly",
    category: "false_friend",
    frequency: "high",
    context: "On the phone, I cannot hear you clear.",
  },
  {
    vietlish: "the line is noisy too much",
    natural: "there is too much noise on the line",
    sourcePattern: "duong day on qua -> adjective/noisy structure calque",
    category: "word_order",
    frequency: "medium",
    context: "The line is noisy too much, can you call again?",
  },
  {
    vietlish: "I will call back for you",
    natural: "I will call you back",
    sourcePattern: "goi lai cho ban -> for you maps into phrasal verb position",
    category: "word_order",
    frequency: "high",
    context: "I am driving now, I will call back for you.",
  },
  {
    vietlish: "please text message to me",
    natural: "please text me",
    sourcePattern: "nhan tin cho toi -> over-expanded text message to me",
    category: "collocation",
    frequency: "medium",
    context: "If I miss the call, please text message to me.",
  },
  {
    vietlish: "I lost your call",
    natural: "I missed your call",
    sourcePattern: "lo cuoc goi -> lost is chosen for missed",
    category: "false_friend",
    frequency: "high",
    context: "Sorry, I lost your call when I was cooking.",
  },
  {
    vietlish: "my phone no battery",
    natural: "my phone has no battery",
    sourcePattern: "dien thoai het pin -> no battery without have",
    category: "literal_translation",
    frequency: "medium",
    context: "My phone no battery, so I could not answer.",
  },
  {
    vietlish: "can you speak slow again",
    natural: "can you speak slowly again?",
    sourcePattern: "noi cham lai -> adjective slow used instead of adverb slowly",
    category: "false_friend",
    frequency: "high",
    context: "Can you speak slow again? I am learning English.",
  },
  {
    vietlish: "I am in outside",
    natural: "I am outside",
    sourcePattern: "o ben ngoai -> unnecessary in before outside",
    category: "collocation",
    frequency: "medium",
    context: "I am in outside the building now.",
  },
  {
    vietlish: "send location for me",
    natural: "send me the location",
    sourcePattern: "gui vi tri cho toi -> for me and article/order transfer",
    category: "word_order",
    frequency: "medium",
    context: "I cannot find the place, send location for me.",
  },
] as const satisfies readonly VietlishCorpusEntry[];
