// src/types/vstep.ts
//
// Shared types for the VSTEP (Vietnamese Standardized Test of English
// Proficiency) preparation pack. Used by listening-items, reading-passages,
// writing-topics, and the score estimator.
//
// The Speaking types live in src/data/exam-prep/vstep/speaking-topics.ts
// alongside the content; these types are for the new skills added in the
// Wave 1 expansion and the estimator.

export type VstepLevel = "B1" | "B2";

// ── Listening ───────────────────────────────────────────────────────────

export type VstepListeningSectionType =
  | "short_conversation"
  | "announcement"
  | "talk"
  | "lecture"
  | "discussion"
  | "news_report";

export interface VstepListeningQuestion {
  /** 1-based question number within the item. */
  number: number;
  /** Question stem in English. */
  question_en: string;
  /** Question stem in Vietnamese. */
  question_vi: string;
  /** For MCQ: 4 options (A–D). Absent for True/False questions. */
  options?: string[];
  /** Correct answer. For MCQ: "A"–"D". For T/F: "True" or "False". */
  answer: string;
}

export interface VstepListeningItem {
  /** Pattern: vstep_b[12]_listening_[topic] */
  id: string;
  level: VstepLevel;
  section: VstepListeningSectionType;
  /** Short descriptive title in English. */
  title_en: string;
  /** Short descriptive title in Vietnamese. */
  title_vi: string;
  /**
   * Full transcript in plain prose — TTS-ready. No stage directions,
   * no [pause] markers, no SSML. Speaker labels (A:, B:) are fine.
   */
  transcript: string;
  questions: VstepListeningQuestion[];
  /**
   * Difficulty label for Vietnamese learners.
   * "easy" | "moderate" | "challenging"
   */
  difficulty: "easy" | "moderate" | "challenging";
  /**
   * Supabase storage key for the pre-rendered MP3.
   * Pattern: vstep-listening/{id}.mp3
   * Generated by Tui 3b (audio agent) — NOT by Tui 1.
   */
  audioKey: string;
  /** Estimated duration of the audio in seconds. */
  estimatedDurationSec: number;
  /** Vietnamese learner tips specific to this item. At least 3. */
  vietnameseLearnerTips: string[];
}

// ── Reading ─────────────────────────────────────────────────────────────

export type VstepReadingSectionType =
  | "email"
  | "notice"
  | "short_article"
  | "academic_text"
  | "opinion_piece"
  | "report";

export interface VstepReadingQuestion {
  /** 1-based question number within the passage. */
  number: number;
  /** Question stem in English. */
  question_en: string;
  /** Question stem in Vietnamese. */
  question_vi: string;
  /** For MCQ: 4 options (A–D). For T/F/NG: absent (True/False/Not Given). */
  options?: string[];
  /** Correct answer. For MCQ: "A"–"D". For T/F/NG: "True", "False", or "Not Given". */
  answer: string;
}

export interface VstepReadingPassage {
  /** Pattern: vstep_b[12]_reading_[topic] */
  id: string;
  level: VstepLevel;
  section: VstepReadingSectionType;
  /** Short descriptive title in English. */
  title_en: string;
  /** Short descriptive title in Vietnamese. */
  title_vi: string;
  /** The passage text. */
  passage: string;
  questions: VstepReadingQuestion[];
  difficulty: "easy" | "moderate" | "challenging";
  /** Key vocabulary from the passage. At least 3 items. */
  vocabulary: Array<{
    word: string;
    translation_vi: string;
  }>;
  /** Vietnamese learner notes — what makes this passage tricky. */
  vietnameseLearnerNotes: string;
}

// ── Writing ─────────────────────────────────────────────────────────────

export type VstepWritingTaskType = "task1_email" | "task1_letter" | "task2_essay";

export interface VstepWritingTopic {
  /** Pattern: vstep_b[12]_writing_[topic] */
  id: string;
  level: VstepLevel;
  task: VstepWritingTaskType;
  /** Short descriptive title in English. */
  title_en: string;
  /** Short descriptive title in Vietnamese. */
  title_vi: string;
  /** The prompt / question. */
  prompt_en: string;
  /** Prompt in Vietnamese. */
  prompt_vi: string;
  /** Suggested word count range. */
  wordCount: { min: number; max: number };
  /** A model / sample answer. */
  sampleAnswer: string;
  /** Band descriptors for this specific topic. At least 2. */
  bandDescriptors: Array<{
    band: "B1" | "B2" | "C1";
    description_en: string;
    description_vi: string;
  }>;
  /** Vietnamese learner tips. At least 3. */
  vietnameseLearnerTips: string[];
  /** Estimated time in minutes. */
  estimatedTimeMinutes: number;
}

// ── Score Estimator ─────────────────────────────────────────────────────

export interface VstepSkillScore {
  /** Raw score (varies per skill — e.g. listening raw = correct answers). */
  raw: number;
}

export interface VstepEstimatedResult {
  /** Overall band: B1, B2, or C1. null if below B1. */
  overallBand: "B1" | "B2" | "C1" | null;
  /** Per-skill bands. */
  skills: {
    listening: "B1" | "B2" | "C1" | null;
    reading: "B1" | "B2" | "C1" | null;
    writing: "B1" | "B2" | "C1" | null;
    speaking: "B1" | "B2" | "C1" | null;
  };
  /** Human-readable summary in English. */
  summary_en: string;
  /** Human-readable summary in Vietnamese. */
  summary_vi: string;
}
