import type { EduLearningSignalDefinition, EduLearningSignalId, EduLearningSignalKey } from "./types";

export const EDU_LEARNING_SIGNAL_DEFINITIONS = [
  {
    edu_id: "EDU-LS-000001",
    signal_key: "productive_hesitation",
    name: "ProductiveHesitation",
    educational_definition: "A learner takes meaningful time before a correct final response without relying on a hint.",
    observable_evidence: ["pause or delayed answer timing", "final answer correct", "no hint used for the same item"],
    alternative_explanations: ["slow device", "interruption", "reading time", "accessibility need"],
    teacher_goal: "Preserve thinking time while confirming the learner can explain the answer.",
    teacher_actions: ["allow wait time", "ask for reasoning", "avoid marking the pause as weakness"],
    validation_criteria: ["answer timing exceeds pause threshold", "final answer is correct", "no HintUsed fact for the item"],
    anti_fake_checks: ["must include source facts", "must not infer anxiety", "must not infer unsupported learner capacity"],
  },
  {
    edu_id: "EDU-LS-000002",
    signal_key: "healthy_self_correction",
    name: "HealthySelfCorrection",
    educational_definition: "A learner revises an initially wrong response and reaches a correct response for the same item or concept.",
    observable_evidence: ["wrong answer fact", "later correct answer fact", "shared item or concept anchor"],
    alternative_explanations: ["accidental first tap", "ambiguous prompt", "interface correction", "peer or teacher cue"],
    teacher_goal: "Support revision as productive learning evidence without over-crediting mastery.",
    teacher_actions: ["acknowledge correction", "ask what changed", "check transfer on a nearby item"],
    validation_criteria: ["wrong response precedes correct response", "facts share the same task anchor", "source sequence is preserved"],
    anti_fake_checks: ["must not fabricate revision", "must not infer character traits", "must not conclude mastery from one correction"],
  },
  {
    edu_id: "EDU-LS-000003",
    signal_key: "hint_dependency",
    name: "HintDependency",
    educational_definition: "A learner repeatedly uses hints in a short evidence window, suggesting the teacher should check scaffolding fit.",
    observable_evidence: ["multiple HintUsed facts", "same route, task, or short session window"],
    alternative_explanations: ["unclear directions", "new format", "language load", "exploratory use"],
    teacher_goal: "Adjust support while avoiding blame for using available help.",
    teacher_actions: ["check prompt clarity", "model one example", "fade hints gradually"],
    validation_criteria: ["hint count meets threshold", "evidence list includes every counted hint", "no ability conclusion is emitted"],
    anti_fake_checks: ["must not label dependency as weakness", "must not ignore unclear prompt alternatives", "must include source facts"],
  },
  {
    edu_id: "EDU-LS-000004",
    signal_key: "misconception_recurrence",
    name: "MisconceptionRecurrence",
    educational_definition: "A similar wrong response pattern recurs for the same concept anchor across multiple attempts.",
    observable_evidence: ["repeated wrong answer facts", "shared concept or task anchor", "separate attempts"],
    alternative_explanations: ["miskeyed answer", "ambiguous item", "content not taught yet", "translation mismatch"],
    teacher_goal: "Find the specific concept to reteach rather than lowering the learner broadly.",
    teacher_actions: ["reteach the concept", "use a contrast example", "verify with a new item"],
    validation_criteria: ["wrong count meets threshold", "same concept or task anchor is present", "facts are not a single duplicate event"],
    anti_fake_checks: ["must not infer unsupported learner capacity", "must not generalize beyond the concept anchor", "must preserve alternatives"],
  },
  {
    edu_id: "EDU-LS-000005",
    signal_key: "retrieval_success",
    name: "RetrievalSuccess",
    educational_definition: "A learner retrieves a correct response after a meaningful delay without relying on immediate hints.",
    observable_evidence: ["correct answer fact", "response time exceeds retrieval delay threshold", "no immediate hint required"],
    alternative_explanations: ["easy item", "prior knowledge", "slow input", "reading time"],
    teacher_goal: "Recognize successful retrieval while checking that the knowledge transfers.",
    teacher_actions: ["briefly reinforce", "ask a transfer question", "space future practice"],
    validation_criteria: ["answer is correct", "delay threshold is met", "evidence includes timing fact"],
    anti_fake_checks: ["must not conclude broad mastery", "must not ignore easy item or prior knowledge alternatives", "must include evidence"],
  },
  {
    edu_id: "EDU-LS-000006",
    signal_key: "productive_struggle",
    name: "ProductiveStruggle",
    educational_definition: "A learner persists through multiple imperfect attempts and eventually reaches a correct response.",
    observable_evidence: ["multiple wrong answer facts", "later correct answer fact", "shared concept or task anchor"],
    alternative_explanations: ["new format", "unclear directions", "temporary distraction", "product_latency_issue"],
    teacher_goal: "Protect persistence while checking which support helped the learner finish.",
    teacher_actions: ["acknowledge persistence", "ask what strategy helped", "offer a similar transfer item"],
    validation_criteria: ["at least two wrong attempts precede a correct response", "facts share a concept or task anchor", "evidence sequence is preserved"],
    anti_fake_checks: ["must not label struggle as weakness", "must not reduce mastery from one sequence", "must preserve alternatives"],
  },
  {
    edu_id: "EDU-LS-000007",
    signal_key: "sustained_attention",
    name: "SustainedAttention",
    educational_definition: "A learner maintains repeated thoughtful response timing across a short assessment window.",
    observable_evidence: ["three or more answer facts", "response times above skim threshold", "single route or session window"],
    alternative_explanations: ["slow input device", "reading load", "accessibility need", "network delay"],
    teacher_goal: "Maintain engagement while avoiding over-reading quiet focus as full understanding.",
    teacher_actions: ["continue flow", "check comprehension periodically", "keep pacing steady"],
    validation_criteria: ["answer count meets threshold", "each counted response has evidence timing", "no broad mastery conclusion is emitted"],
    anti_fake_checks: ["must not infer motivation", "must not infer broad mastery", "must include every counted fact"],
  },
  {
    edu_id: "EDU-LS-000008",
    signal_key: "confidence_calibration",
    name: "ConfidenceCalibration",
    educational_definition: "A learner's stated confidence aligns with observed answer outcome in the same evidence item.",
    observable_evidence: ["answer correctness fact", "confidence rating metric", "shared item anchor"],
    alternative_explanations: ["misread confidence scale", "interface selection error", "cultural response style", "lucky guess"],
    teacher_goal: "Use confidence data to ask better reflection questions without judging self-belief.",
    teacher_actions: ["ask why they felt confident", "compare confidence with evidence", "calibrate with one follow-up item"],
    validation_criteria: ["confidence metric is present", "answer outcome is present", "evidence item is anchored"],
    anti_fake_checks: ["must not infer personality", "must not infer ability from confidence alone", "must preserve alternatives"],
  },
  {
    edu_id: "EDU-LS-000009",
    signal_key: "cognitive_overload",
    name: "CognitiveOverload",
    educational_definition: "A short window shows repeated high-effort signals with low success or support-seeking, requiring a support check.",
    observable_evidence: ["slow wrong answer facts", "hint usage or repeated attempts", "same route or concept window"],
    alternative_explanations: ["product_latency_issue", "unclear instructions", "fatigue", "content not taught yet"],
    teacher_goal: "Reduce load and check instructions before interpreting the learning signal.",
    teacher_actions: ["pause and simplify", "check directions", "offer one worked example"],
    validation_criteria: ["multiple high-effort low-success facts exist", "support-seeking or repeated attempts are present", "system alternatives are preserved"],
    anti_fake_checks: ["must not infer weakness", "must not reduce mastery from one overloaded window", "must include product/system alternatives"],
  },
  {
    edu_id: "EDU-LS-000010",
    signal_key: "transfer_success",
    name: "TransferSuccess",
    educational_definition: "A learner answers correctly on at least two distinct items sharing a concept anchor.",
    observable_evidence: ["correct answer facts", "shared concept anchor", "distinct item anchors"],
    alternative_explanations: ["question_too_easy", "prior_knowledge", "pattern recognition", "lucky guess"],
    teacher_goal: "Check whether knowledge transfers while avoiding broad mastery claims.",
    teacher_actions: ["ask a novel transfer question", "space future practice", "record concept-level evidence"],
    validation_criteria: ["at least two distinct correct items share concept anchor", "source facts are preserved", "alternatives remain visible"],
    anti_fake_checks: ["must not conclude broad mastery", "must not ignore prior knowledge", "must not collapse distinct items into one fact"],
  },
] as const satisfies readonly EduLearningSignalDefinition[];

export function eduDefinitionById(eduId: EduLearningSignalId): EduLearningSignalDefinition | null {
  return EDU_LEARNING_SIGNAL_DEFINITIONS.find((definition) => definition.edu_id === eduId) ?? null;
}

export function eduDefinitionBySignalKey(signalKey: EduLearningSignalKey): EduLearningSignalDefinition | null {
  return EDU_LEARNING_SIGNAL_DEFINITIONS.find((definition) => definition.signal_key === signalKey) ?? null;
}
