// Auto-generated by scripts/split-lessons-by-level.mjs.
// Edit the source lesson content here directly. DO NOT regenerate
// from a stale lessons.ts — the registry replaced that file.

import type { KoreanLesson } from "./lessons";

export const lessons: KoreanLesson[] = [
  {
    "id": 31,
    "level": "B1",
    "title_vi": "Họp công việc",
    "title_en": "Business Meetings",
    "intro_vi": "Cách diễn đạt trong họp trang trọng. Dùng 회의 cho cuộc họp và 의견을 내다 để nêu ý kiến.",
    "vocabulary": [
      {
        "hangul": "회의",
        "meaning": "meeting"
      },
      {
        "hangul": "의제",
        "meaning": "agenda"
      },
      {
        "hangul": "발표",
        "meaning": "presentation"
      },
      {
        "hangul": "토의",
        "meaning": "discussion"
      },
      {
        "hangul": "결정",
        "meaning": "decision"
      },
      {
        "hangul": "참석하다",
        "meaning": "to attend"
      },
      {
        "hangul": "의견을 내다",
        "meaning": "to give an opinion"
      },
      {
        "hangul": "진행하다",
        "meaning": "to proceed"
      },
      {
        "hangul": "마감",
        "meaning": "deadline"
      },
      {
        "hangul": "회의록",
        "meaning": "meeting minutes"
      }
    ],
    "sentences": [
      {
        "korean": "회의를 시작하겠습니다.",
        "romanized": "Hoeuireul sijakhagetseumnida.",
        "en": "Let's start the meeting.",
        "vi": "Bắt đầu cuộc họp."
      },
      {
        "korean": "오늘 의제는 무엇인가요?",
        "romanized": "Oneul uijeneun mueosingayo?",
        "en": "What is today's agenda?",
        "vi": "Chương trình hôm nay là gì?"
      },
      {
        "korean": "다음 프로젝트에 대해 토의합시다.",
        "romanized": "Daeum peurojekteue daehae touihapsida.",
        "en": "Let's discuss the next project.",
        "vi": "Hãy thảo luận dự án tiếp theo."
      },
      {
        "korean": "결정은 다음 주까지 미루겠습니다.",
        "romanized": "Gyeoljeongeun daeum jukkaji mirugetseumnida.",
        "en": "We will postpone the decision until next week.",
        "vi": "Quyết định sẽ hoãn đến tuần sau."
      },
      {
        "korean": "회의록을 이메일로 보내 드리겠습니다.",
        "romanized": "Hoeuirogeul imeilro bonae deurigetseumnida.",
        "en": "I will send you the meeting minutes by email.",
        "vi": "Tôi sẽ gửi biên bản họp qua email."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "모두 모였으니 회의를 시작하겠습니다.",
        "meaning": "Since everyone is here, let's start the meeting."
      },
      {
        "speaker": "B",
        "hangul": "네, 먼저 지난주 진행 상황을 보고하겠습니다.",
        "meaning": "Yes, first I will report on last week's progress."
      },
      {
        "speaker": "A",
        "hangul": "수고하셨습니다. 다음 의제로 넘어갑시다.",
        "meaning": "Good work. Let's move to the next agenda."
      },
      {
        "speaker": "B",
        "hangul": "새로운 마케팅 전략에 대해 논의하고 싶습니다.",
        "meaning": "I'd like to discuss the new marketing strategy."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "회의를 ___겠습니다.",
        "answer": "시작하"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "의제",
            "meaning": "agenda"
          },
          {
            "hangul": "회의록",
            "meaning": "minutes"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Chúng ta hãy thảo luận về dự án tiếp theo.",
        "hangul": "다음 프로젝트에 대해 토의합시다."
      }
    ]
  },
  {
    "id": 32,
    "level": "B1",
    "title_vi": "Thuyết trình",
    "title_en": "Giving Presentations",
    "intro_vi": "Cách diễn đạt khi thuyết trình. Dùng 발표 cho thuyết trình và 자료 cho tài liệu.",
    "vocabulary": [
      {
        "hangul": "발표",
        "meaning": "presentation"
      },
      {
        "hangul": "자료",
        "meaning": "materials"
      },
      {
        "hangul": "슬라이드",
        "meaning": "slide"
      },
      {
        "hangul": "요약",
        "meaning": "summary"
      },
      {
        "hangul": "질문",
        "meaning": "question"
      },
      {
        "hangul": "대답",
        "meaning": "answer"
      },
      {
        "hangul": "청중",
        "meaning": "audience"
      },
      {
        "hangul": "준비하다",
        "meaning": "to prepare"
      },
      {
        "hangul": "설명하다",
        "meaning": "to explain"
      },
      {
        "hangul": "마무리하다",
        "meaning": "to conclude"
      }
    ],
    "sentences": [
      {
        "korean": "오늘 발표 주제는 시장 분석입니다.",
        "romanized": "Oneul balpyo jujeneun sijang bunseogimnida.",
        "en": "Today's presentation topic is market analysis.",
        "vi": "Chủ đề thuyết trình hôm nay là phân tích thị trường."
      },
      {
        "korean": "다음 슬라이드를 봐 주세요.",
        "romanized": "Daeum seulraideureul bwa juseyo.",
        "en": "Please look at the next slide.",
        "vi": "Xin xem slide tiếp theo."
      },
      {
        "korean": "간단히 요약하겠습니다.",
        "romanized": "Gandanhi yoyakhagetseumnida.",
        "en": "I will give a brief summary.",
        "vi": "Tôi sẽ tóm tắt ngắn gọn."
      },
      {
        "korean": "질문이 있으시면 언제든지 해 주세요.",
        "romanized": "Jilmuni isseusimyeon eonjedeunji hae juseyo.",
        "en": "If you have questions, please feel free to ask anytime.",
        "vi": "Có câu hỏi xin cứ tự nhiên."
      },
      {
        "korean": "발표를 마치겠습니다. 감사합니다.",
        "romanized": "Balpyoreul machigetseumnida. gamsahamnida.",
        "en": "I will conclude the presentation. Thank you.",
        "vi": "Tôi xin kết thúc bài thuyết trình. Cảm ơn."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "안녕하세요, 오늘 발표를 시작하겠습니다.",
        "meaning": "Hello, I will begin today's presentation."
      },
      {
        "speaker": "B",
        "hangul": "주제가 무엇인가요?",
        "meaning": "What is the topic?"
      },
      {
        "speaker": "A",
        "hangul": "신제품 출시 전략에 관한 것입니다.",
        "meaning": "It is about the new product launch strategy."
      },
      {
        "speaker": "B",
        "hangul": "자료를 미리 받을 수 있나요?",
        "meaning": "Can I get the materials in advance?"
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "다음 ___를 봐 주세요.",
        "answer": "슬라이드"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "발표",
            "meaning": "presentation"
          },
          {
            "hangul": "요약",
            "meaning": "summary"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi sẽ kết thúc bài thuyết trình. Cảm ơn.",
        "hangul": "발표를 마치겠습니다. 감사합니다."
      }
    ]
  },
  {
    "id": 33,
    "level": "B1",
    "title_vi": "Đàm phán",
    "title_en": "Negotiating",
    "intro_vi": "Từ vựng đàm phán. Dùng 협상 cho đàm phán và 조건 cho điều kiện.",
    "vocabulary": [
      {
        "hangul": "협상",
        "meaning": "negotiation"
      },
      {
        "hangul": "조건",
        "meaning": "condition"
      },
      {
        "hangul": "제안",
        "meaning": "proposal"
      },
      {
        "hangul": "타협",
        "meaning": "compromise"
      },
      {
        "hangul": "할인",
        "meaning": "discount"
      },
      {
        "hangul": "가격",
        "meaning": "price"
      },
      {
        "hangul": "계약서",
        "meaning": "contract"
      },
      {
        "hangul": "양보하다",
        "meaning": "to concede"
      },
      {
        "hangul": "이익",
        "meaning": "profit"
      },
      {
        "hangul": "마감일",
        "meaning": "deadline"
      }
    ],
    "sentences": [
      {
        "korean": "협상을 시작합시다.",
        "romanized": "Hyeopsangeul sijakhapsida.",
        "en": "Let's start the negotiation.",
        "vi": "Hãy bắt đầu đàm phán."
      },
      {
        "korean": "조건을 조금 완화해 주실 수 있나요?",
        "romanized": "Jogeoneul jogeum wanhwahae jusil su itnayo?",
        "en": "Could you ease the conditions a little?",
        "vi": "Bạn có thể nới lỏng điều kiện một chút không?"
      },
      {
        "korean": "우리는 10% 할인을 제안합니다.",
        "romanized": "Urineun 10% harineul jeanhamnida.",
        "en": "We propose a 10% discount.",
        "vi": "Chúng tôi đề xuất giảm giá 10%."
      },
      {
        "korean": "서로 타협점을 찾아야 합니다.",
        "romanized": "Seoro tahyeopjeomeul chajaya hamnida.",
        "en": "We need to find a compromise.",
        "vi": "Chúng ta cần tìm điểm thỏa hiệp."
      },
      {
        "korean": "계약서에 서명하기 전에 검토하겠습니다.",
        "romanized": "Gyeyakseoe seomyeonghagi jeone geomtohagetseumnida.",
        "en": "I will review the contract before signing.",
        "vi": "Tôi sẽ xem xét hợp đồng trước khi ký."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "가격을 낮출 수 있을까요?",
        "meaning": "Can you lower the price?"
      },
      {
        "speaker": "B",
        "hangul": "최대 5%까지 할인이 가능합니다.",
        "meaning": "A maximum of 5% discount is possible."
      },
      {
        "speaker": "A",
        "hangul": "그럼 10% 할인은 어려운가요?",
        "meaning": "Then is 10% discount difficult?"
      },
      {
        "speaker": "B",
        "hangul": "죄송합니다. 그 이상은 어렵습니다.",
        "meaning": "Sorry, it's difficult beyond that."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "___을 시작합시다.",
        "answer": "협상"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "할인",
            "meaning": "discount"
          },
          {
            "hangul": "양보하다",
            "meaning": "to concede"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Chúng tôi đề xuất giảm giá 10%.",
        "hangul": "우리는 10% 할인을 제안합니다."
      }
    ]
  },
  {
    "id": 34,
    "level": "B1",
    "title_vi": "Mạng xã hội",
    "title_en": "Social Media",
    "intro_vi": "Thuật ngữ mạng xã hội. Dùng 소셜 미디어 cho mạng xã hội và 팔로우 cho theo dõi.",
    "vocabulary": [
      {
        "hangul": "소셜 미디어",
        "meaning": "social media"
      },
      {
        "hangul": "팔로우",
        "meaning": "follow"
      },
      {
        "hangul": "좋아요",
        "meaning": "like"
      },
      {
        "hangul": "댓글",
        "meaning": "comment"
      },
      {
        "hangul": "공유하다",
        "meaning": "to share"
      },
      {
        "hangul": "게시물",
        "meaning": "post"
      },
      {
        "hangul": "프로필",
        "meaning": "profile"
      },
      {
        "hangul": "해시태그",
        "meaning": "hashtag"
      },
      {
        "hangul": "인스타그램",
        "meaning": "Instagram"
      },
      {
        "hangul": "트위터",
        "meaning": "Twitter"
      }
    ],
    "sentences": [
      {
        "korean": "소셜 미디어에서 자주 활동하세요?",
        "romanized": "Sosyeol midieoeseo jaju hwaldonghaseyo?",
        "en": "Do you often use social media?",
        "vi": "Bạn có hay dùng mạng xã hội không?"
      },
      {
        "korean": "제 게시물에 좋아요를 눌러 주세요.",
        "romanized": "Je gesimure joayoreul nulreo juseyo.",
        "en": "Please like my post.",
        "vi": "Xin nhấn like cho bài đăng của tôi."
      },
      {
        "korean": "댓글을 달아 주셔서 감사합니다.",
        "romanized": "Daetgeureul dara jusyeoseo gamsahamnida.",
        "en": "Thank you for leaving a comment.",
        "vi": "Cảm ơn bạn đã bình luận."
      },
      {
        "korean": "이 사진을 공유하고 싶어요.",
        "romanized": "I sajineul gongyuhago sipeoyo.",
        "en": "I want to share this photo.",
        "vi": "Tôi muốn chia sẻ bức ảnh này."
      },
      {
        "korean": "해시태그를 사용하면 검색이 쉬워요.",
        "romanized": "Haesitaegeureul sayonghamyeon geomsaegi swiwoyo.",
        "en": "Using hashtags makes searching easier.",
        "vi": "Dùng hashtag thì tìm kiếm dễ hơn."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "인스타그램 계정이 있어요?",
        "meaning": "Do you have an Instagram account?"
      },
      {
        "speaker": "B",
        "hangul": "네, 있어요. 당신을 팔로우할게요.",
        "meaning": "Yes, I do. I'll follow you."
      },
      {
        "speaker": "A",
        "hangul": "감사합니다. 저도 팔로우할게요.",
        "meaning": "Thank you. I'll follow you too."
      },
      {
        "speaker": "B",
        "hangul": "게시물이 정말 예쁘네요!",
        "meaning": "Your posts are really pretty!"
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "게시물에 ___를 눌러 주세요.",
        "answer": "좋아요"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "팔로우",
            "meaning": "follow"
          },
          {
            "hangul": "공유하다",
            "meaning": "to share"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi muốn chia sẻ bức ảnh này.",
        "hangul": "이 사진을 공유하고 싶어요."
      }
    ]
  },
  {
    "id": 35,
    "level": "B1",
    "title_vi": "Vấn đề môi trường",
    "title_en": "Environmental Issues",
    "intro_vi": "Từ vựng môi trường. Dùng 환경 cho môi trường và 문제 cho vấn đề.",
    "vocabulary": [
      {
        "hangul": "환경",
        "meaning": "environment"
      },
      {
        "hangul": "문제",
        "meaning": "problem"
      },
      {
        "hangul": "오염",
        "meaning": "pollution"
      },
      {
        "hangul": "재활용",
        "meaning": "recycling"
      },
      {
        "hangul": "쓰레기",
        "meaning": "trash"
      },
      {
        "hangul": "지구 온난화",
        "meaning": "global warming"
      },
      {
        "hangul": "에너지",
        "meaning": "energy"
      },
      {
        "hangul": "탄소 배출",
        "meaning": "carbon emission"
      },
      {
        "hangul": "자연 보호",
        "meaning": "nature protection"
      },
      {
        "hangul": "생태계",
        "meaning": "ecosystem"
      }
    ],
    "sentences": [
      {
        "korean": "환경 오염이 심각해지고 있어요.",
        "romanized": "Hwangyeong oyeomi simgakhaejigo isseoyo.",
        "en": "Environmental pollution is becoming serious.",
        "vi": "Ô nhiễm môi trường đang trở nên nghiêm trọng."
      },
      {
        "korean": "재활용을 생활화해야 합니다.",
        "romanized": "Jaehwaryongeul saenghwalhwahaeya hamnida.",
        "en": "We should make recycling a habit.",
        "vi": "Chúng ta phải biến tái chế thành thói quen."
      },
      {
        "korean": "지구 온난화를 막기 위해 노력합시다.",
        "romanized": "Jigu onnanhwareul makgi wihae noryeokhapsida.",
        "en": "Let's try to prevent global warming.",
        "vi": "Hãy cùng nhau ngăn chặn nóng lên toàn cầu."
      },
      {
        "korean": "탄소 배출을 줄이는 것이 중요해요.",
        "romanized": "Tanso baechureul jurineun geosi jungyohaeyo.",
        "en": "Reducing carbon emissions is important.",
        "vi": "Giảm khí thải carbon là điều quan trọng."
      },
      {
        "korean": "자연을 보호하는 일에 동참해 주세요.",
        "romanized": "Jayeoneul bohohaneun ire dongchamhae juseyo.",
        "en": "Please join in protecting nature.",
        "vi": "Xin hãy cùng tham gia bảo vệ thiên nhiên."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "요즘 환경 문제에 관심이 많아졌어요.",
        "meaning": "I've become more interested in environmental issues these days."
      },
      {
        "speaker": "B",
        "hangul": "저도요. 특히 플라스틱 사용을 줄이려고 해요.",
        "meaning": "Me too. Especially I try to reduce plastic use."
      },
      {
        "speaker": "A",
        "hangul": "재활용도 열심히 하고 있어요.",
        "meaning": "I'm also doing recycling diligently."
      },
      {
        "speaker": "B",
        "hangul": "작은 실천이 큰 변화를 만들 수 있죠.",
        "meaning": "Small actions can make big changes."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "환경 ___이 심각해지고 있어요.",
        "answer": "오염"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "재활용",
            "meaning": "recycling"
          },
          {
            "hangul": "오염",
            "meaning": "pollution"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Giảm lượng khí thải carbon là rất quan trọng.",
        "hangul": "탄소 배출을 줄이는 것이 중요해요."
      }
    ]
  },
  {
    "id": 36,
    "level": "B1",
    "title_vi": "Bày tỏ ý kiến",
    "title_en": "Expressing Opinions",
    "intro_vi": "Dùng 의견 cho ý kiến và 표현 cho cách diễn đạt. Học cách nêu và bảo vệ quan điểm.",
    "vocabulary": [
      {
        "hangul": "의견",
        "meaning": "opinion"
      },
      {
        "hangul": "생각",
        "meaning": "thought"
      },
      {
        "hangul": "주장",
        "meaning": "claim / argument"
      },
      {
        "hangul": "근거",
        "meaning": "evidence"
      },
      {
        "hangul": "찬성하다",
        "meaning": "to agree"
      },
      {
        "hangul": "반대하다",
        "meaning": "to disagree"
      },
      {
        "hangul": "관점",
        "meaning": "perspective"
      },
      {
        "hangul": "논리",
        "meaning": "logic"
      },
      {
        "hangul": "확신",
        "meaning": "conviction"
      },
      {
        "hangul": "의문",
        "meaning": "doubt"
      }
    ],
    "sentences": [
      {
        "korean": "제 의견을 말씀드리겠습니다.",
        "romanized": "Je uigyeoneul malsseumdeurigetseumnida.",
        "en": "I will express my opinion.",
        "vi": "Tôi xin nêu ý kiến của mình."
      },
      {
        "korean": "저는 그 주장에 동의하지 않습니다.",
        "romanized": "Jeoneun geu jujange donguihaji ansseumnida.",
        "en": "I do not agree with that claim.",
        "vi": "Tôi không đồng ý với lập luận đó."
      },
      {
        "korean": "다른 관점에서 생각해 볼 필요가 있어요.",
        "romanized": "Dareun gwanjeomeseo saenggakhae bol piryoga isseoyo.",
        "en": "We need to think from a different perspective.",
        "vi": "Cần suy nghĩ từ một góc nhìn khác."
      },
      {
        "korean": "그 근거가 충분하다고 생각하나요?",
        "romanized": "Geu geungeoga chungbunhadago saenggakhanayo?",
        "en": "Do you think that evidence is sufficient?",
        "vi": "Bạn có nghĩ căn cứ đó là đủ không?"
      },
      {
        "korean": "저는 확신이 서지 않아요.",
        "romanized": "Jeoneun hwaksini seoji anayo.",
        "en": "I am not convinced.",
        "vi": "Tôi không chắc chắn lắm."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "새 정책에 대해 어떻게 생각하세요?",
        "meaning": "What do you think about the new policy?"
      },
      {
        "speaker": "B",
        "hangul": "저는 찬성합니다. 효과적일 거예요.",
        "meaning": "I agree. It will be effective."
      },
      {
        "speaker": "A",
        "hangul": "그런데 비용이 너무 많이 들지 않을까요?",
        "meaning": "But won't it cost too much?"
      },
      {
        "speaker": "B",
        "hangul": "장기적으로 보면 이익이 더 클 거예요.",
        "meaning": "In the long run, the benefits will be greater."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "제 ___을 말씀드리겠습니다.",
        "answer": "의견"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "찬성하다",
            "meaning": "to agree"
          },
          {
            "hangul": "반대하다",
            "meaning": "to disagree"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi không đồng ý với lập luận đó.",
        "hangul": "저는 그 주장에 동의하지 않습니다."
      }
    ]
  },
  {
    "id": 37,
    "level": "B1",
    "title_vi": "Đưa ra gợi ý",
    "title_en": "Making Suggestions",
    "intro_vi": "Dùng 제안 cho gợi ý. Dùng -는 게 어때요? để gợi ý.",
    "vocabulary": [
      {
        "hangul": "제안",
        "meaning": "suggestion"
      },
      {
        "hangul": "추천",
        "meaning": "recommendation"
      },
      {
        "hangul": "대안",
        "meaning": "alternative"
      },
      {
        "hangul": "의견을 묻다",
        "meaning": "to ask for opinion"
      },
      {
        "hangul": "제안하다",
        "meaning": "to suggest"
      },
      {
        "hangul": "투표",
        "meaning": "vote"
      },
      {
        "hangul": "선택",
        "meaning": "choice"
      },
      {
        "hangul": "계획",
        "meaning": "plan"
      },
      {
        "hangul": "실행",
        "meaning": "execution"
      },
      {
        "hangul": "고려하다",
        "meaning": "to consider"
      }
    ],
    "sentences": [
      {
        "korean": "같이 영화 보는 게 어때요?",
        "romanized": "Gati yeonghwa boneun ge eottaeyo?",
        "en": "How about watching a movie together?",
        "vi": "Cùng đi xem phim nhé?"
      },
      {
        "korean": "제안이 있으신 분?",
        "romanized": "Jeani isseusin bun?",
        "en": "Anyone have a suggestion?",
        "vi": "Có ai có gợi ý không?"
      },
      {
        "korean": "이 대안을 고려해 보세요.",
        "romanized": "I daeaneul goryeohae boseyo.",
        "en": "Please consider this alternative.",
        "vi": "Hãy cân nhắc phương án này."
      },
      {
        "korean": "제가 추천하는 곳이 있어요.",
        "romanized": "Jega chucheonhaneun gosi isseoyo.",
        "en": "I have a recommendation.",
        "vi": "Tôi có một địa điểm muốn giới thiệu."
      },
      {
        "korean": "우선 계획을 세우는 게 좋겠어요.",
        "romanized": "Useon gyehoegeul seuneun ge jokesseoyo.",
        "en": "I think it would be good to make a plan first.",
        "vi": "Tốt nhất nên lập kế hoạch trước."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "이번 주말에 뭐 할까요?",
        "meaning": "What shall we do this weekend?"
      },
      {
        "speaker": "B",
        "hangul": "등산 가는 게 어때요?",
        "meaning": "How about going hiking?"
      },
      {
        "speaker": "A",
        "hangul": "좋아요! 어디로 갈까요?",
        "meaning": "Good idea! Where shall we go?"
      },
      {
        "speaker": "B",
        "hangul": "북한산이 어때요? 경치가 좋아요.",
        "meaning": "How about Bukhansan? The scenery is nice."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "같이 영화 보는 게 ___?",
        "answer": "어때요"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "제안",
            "meaning": "suggestion"
          },
          {
            "hangul": "추천",
            "meaning": "recommendation"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi đề xuất chúng ta đi leo núi.",
        "hangul": "등산 가는 것을 제안합니다."
      }
    ]
  },
  {
    "id": 38,
    "level": "B1",
    "title_vi": "Xin lỗi và biện hộ",
    "title_en": "Apologizing and Making Excuses",
    "intro_vi": "Dùng 사과 cho xin lỗi và 변명 cho biện hộ. Học các cách xin lỗi lịch sự.",
    "vocabulary": [
      {
        "hangul": "사과",
        "meaning": "apology"
      },
      {
        "hangul": "변명",
        "meaning": "excuse"
      },
      {
        "hangul": "죄송합니다",
        "meaning": "I'm sorry"
      },
      {
        "hangul": "용서",
        "meaning": "forgiveness"
      },
      {
        "hangul": "실수",
        "meaning": "mistake"
      },
      {
        "hangul": "늦다",
        "meaning": "to be late"
      },
      {
        "hangul": "이해하다",
        "meaning": "to understand"
      },
      {
        "hangul": "다행이다",
        "meaning": "to be relieved"
      },
      {
        "hangul": "약속",
        "meaning": "promise"
      },
      {
        "hangul": "재발",
        "meaning": "recurrence"
      }
    ],
    "sentences": [
      {
        "korean": "정말 죄송합니다.",
        "romanized": "Jeongmal joesonghamnida.",
        "en": "I am really sorry.",
        "vi": "Tôi thực sự xin lỗi."
      },
      {
        "korean": "제 실수였어요. 용서해 주세요.",
        "romanized": "Je silsuyeosseoyo. yongseohae juseyo.",
        "en": "It was my mistake. Please forgive me.",
        "vi": "Đó là lỗi của tôi. Xin tha lỗi."
      },
      {
        "korean": "늦은 이유를 설명해 주세요.",
        "romanized": "Neujeun iyureul seolmyeonghae juseyo.",
        "en": "Please explain the reason for being late.",
        "vi": "Xin giải thích lý do đến trễ."
      },
      {
        "korean": "다시는 그러지 않겠습니다.",
        "romanized": "Dasineun geureoji anketseumnida.",
        "en": "I won't do that again.",
        "vi": "Tôi sẽ không tái phạm."
      },
      {
        "korean": "이해해 주셔서 감사합니다.",
        "romanized": "Ihaehae jusyeoseo gamsahamnida.",
        "en": "Thank you for understanding.",
        "vi": "Cảm ơn bạn đã thông cảm."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "어제 약속에 늦어서 정말 미안해요.",
        "meaning": "I'm really sorry for being late to the appointment yesterday."
      },
      {
        "speaker": "B",
        "hangul": "괜찮아요. 무슨 일이 있었어요?",
        "meaning": "It's okay. What happened?"
      },
      {
        "speaker": "A",
        "hangul": "교통이 많이 막혔어요.",
        "meaning": "There was heavy traffic."
      },
      {
        "speaker": "B",
        "hangul": "다행히 큰 문제는 없었어요.",
        "meaning": "Luckily, there was no big issue."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "정말 ___합니다.",
        "answer": "죄송"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "사과",
            "meaning": "apology"
          },
          {
            "hangul": "변명",
            "meaning": "excuse"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Đó là lỗi của tôi. Xin hãy tha thứ cho tôi.",
        "hangul": "제 실수였어요. 용서해 주세요."
      }
    ]
  },
  {
    "id": 39,
    "level": "B1",
    "title_vi": "Đưa ra lời khuyên",
    "title_en": "Giving Advice",
    "intro_vi": "Dùng 조언 cho lời khuyên. Dùng -는 것이 좋다 để khuyên nhủ.",
    "vocabulary": [
      {
        "hangul": "조언",
        "meaning": "advice"
      },
      {
        "hangul": "충고",
        "meaning": "counsel"
      },
      {
        "hangul": "추천하다",
        "meaning": "to recommend"
      },
      {
        "hangul": "도움이 되다",
        "meaning": "to be helpful"
      },
      {
        "hangul": "경험",
        "meaning": "experience"
      },
      {
        "hangul": "조심하다",
        "meaning": "to be careful"
      },
      {
        "hangul": "노력하다",
        "meaning": "to make an effort"
      },
      {
        "hangul": "기회",
        "meaning": "opportunity"
      },
      {
        "hangul": "실패",
        "meaning": "failure"
      },
      {
        "hangul": "성공",
        "meaning": "success"
      }
    ],
    "sentences": [
      {
        "korean": "제 조언을 들어 보세요.",
        "romanized": "Je joeoneul deureo boseyo.",
        "en": "Listen to my advice.",
        "vi": "Hãy nghe lời khuyên của tôi."
      },
      {
        "korean": "그 일을 먼저 처리하는 것이 좋아요.",
        "romanized": "Geu ireul meonjeo cheorihaneun geosi joayo.",
        "en": "It's better to handle that task first.",
        "vi": "Nên xử lý việc đó trước."
      },
      {
        "korean": "실패를 두려워하지 마세요.",
        "romanized": "Silpaereul duryeowohaji maseyo.",
        "en": "Don't be afraid of failure.",
        "vi": "Đừng sợ thất bại."
      },
      {
        "korean": "기회가 올 때 잡으세요.",
        "romanized": "Gihoega ol ttae jabeuseyo.",
        "en": "Seize the opportunity when it comes.",
        "vi": "Hãy nắm bắt cơ hội khi đến."
      },
      {
        "korean": "충고를 명심하겠습니다.",
        "romanized": "Chunggoreul myeongsimhagetseumnida.",
        "en": "I will keep your advice in mind.",
        "vi": "Tôi sẽ ghi nhớ lời khuyên."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "한국어 공부가 어려워요. 조언 좀 해 주세요.",
        "meaning": "Studying Korean is difficult. Please give me some advice."
      },
      {
        "speaker": "B",
        "hangul": "매일 조금씩 꾸준히 공부하는 게 좋아요.",
        "meaning": "It's good to study a little bit every day consistently."
      },
      {
        "speaker": "A",
        "hangul": "듣기 실력을 어떻게 늘릴까요?",
        "meaning": "How can I improve my listening skills?"
      },
      {
        "speaker": "B",
        "hangul": "한국 드라마를 보는 것도 도움이 돼요.",
        "meaning": "Watching Korean dramas also helps."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "제 ___을 들어 보세요.",
        "answer": "조언"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "조언",
            "meaning": "advice"
          },
          {
            "hangul": "충고",
            "meaning": "counsel"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi sẽ ghi nhớ lời khuyên của bạn.",
        "hangul": "충고를 명심하겠습니다."
      }
    ]
  },
  {
    "id": 40,
    "level": "B1",
    "title_vi": "Kể trải nghiệm",
    "title_en": "Describing Experiences",
    "intro_vi": "Dùng 경험 cho trải nghiệm. Dùng -아/어 보다 cho việc đã từng làm.",
    "vocabulary": [
      {
        "hangul": "경험",
        "meaning": "experience"
      },
      {
        "hangul": "여행",
        "meaning": "trip"
      },
      {
        "hangul": "체험",
        "meaning": "hands-on experience"
      },
      {
        "hangul": "도전",
        "meaning": "challenge"
      },
      {
        "hangul": "즐기다",
        "meaning": "to enjoy"
      },
      {
        "hangul": "배우다",
        "meaning": "to learn"
      },
      {
        "hangul": "기억",
        "meaning": "memory"
      },
      {
        "hangul": "인상적이다",
        "meaning": "impressive"
      },
      {
        "hangul": "처음",
        "meaning": "first time"
      },
      {
        "hangul": "느끼다",
        "meaning": "to feel"
      }
    ],
    "sentences": [
      {
        "korean": "한국에 처음 왔을 때가 기억나요.",
        "romanized": "Hanguge cheoeum wasseul ttaega gieoknayo.",
        "en": "I remember the first time I came to Korea.",
        "vi": "Tôi nhớ lần đầu đến Hàn Quốc."
      },
      {
        "korean": "김치를 처음 먹어 봤어요.",
        "romanized": "Gimchireul cheoeum meogeo bwasseoyo.",
        "en": "I tried kimchi for the first time.",
        "vi": "Tôi đã thử ăn kimchi lần đầu."
      },
      {
        "korean": "그 경험은 정말 인상적이었어요.",
        "romanized": "Geu gyeongheomeun jeongmal insangjeogieosseoyo.",
        "en": "That experience was really impressive.",
        "vi": "Trải nghiệm đó thực sự ấn tượng."
      },
      {
        "korean": "여행하면서 많은 것을 배웠어요.",
        "romanized": "Yeohaenghamyeonseo maneun geoseul baewosseoyo.",
        "en": "I learned a lot while traveling.",
        "vi": "Tôi học được nhiều điều khi đi du lịch."
      },
      {
        "korean": "새로운 도전을 즐기는 편이에요.",
        "romanized": "Saeroun dojeoneul jeulgineun pyeonieyo.",
        "en": "I tend to enjoy new challenges.",
        "vi": "Tôi thích đón nhận thử thách mới."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "제주도에 가 본 적 있어요?",
        "meaning": "Have you ever been to Jeju Island?"
      },
      {
        "speaker": "B",
        "hangul": "네, 작년에 다녀왔어요. 정말 아름다웠어요.",
        "meaning": "Yes, I went last year. It was really beautiful."
      },
      {
        "speaker": "A",
        "hangul": "무엇이 가장 기억에 남나요?",
        "meaning": "What is most memorable?"
      },
      {
        "speaker": "B",
        "hangul": "한라산 등반이 가장 인상 깊었어요.",
        "meaning": "Climbing Hallasan was the most impressive."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "김치를 처음 ___ 봤어요.",
        "answer": "먹어"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "경험",
            "meaning": "experience"
          },
          {
            "hangul": "체험",
            "meaning": "hands-on experience"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Trải nghiệm đó thực sự ấn tượng.",
        "hangul": "그 경험은 정말 인상적이었어요."
      }
    ]
  },
  {
    "id": 41,
    "level": "B1",
    "title_vi": "So sánh các lựa chọn",
    "title_en": "Comparing Options",
    "intro_vi": "Dùng 비교 cho so sánh. Dùng -보다 더 cho 'hơn'.",
    "vocabulary": [
      {
        "hangul": "비교",
        "meaning": "comparison"
      },
      {
        "hangul": "옵션",
        "meaning": "option"
      },
      {
        "hangul": "선택",
        "meaning": "choice"
      },
      {
        "hangul": "장점",
        "meaning": "advantage"
      },
      {
        "hangul": "단점",
        "meaning": "disadvantage"
      },
      {
        "hangul": "비슷하다",
        "meaning": "similar"
      },
      {
        "hangul": "다르다",
        "meaning": "different"
      },
      {
        "hangul": "저렴하다",
        "meaning": "cheap"
      },
      {
        "hangul": "비싸다",
        "meaning": "expensive"
      },
      {
        "hangul": "효율적",
        "meaning": "efficient"
      }
    ],
    "sentences": [
      {
        "korean": "이 옵션과 저 옵션을 비교해 보세요.",
        "romanized": "I opsyeongwa jeo opsyeoneul bigyohae boseyo.",
        "en": "Compare this option and that option.",
        "vi": "Hãy so sánh phương án này với phương án kia."
      },
      {
        "korean": "이 제품이 더 저렴하지만 품질은 비슷해요.",
        "romanized": "I jepumi deo jeoryeomhajiman pumjireun biseuthaeyo.",
        "en": "This product is cheaper, but quality is similar.",
        "vi": "Sản phẩm này rẻ hơn nhưng chất lượng tương tự."
      },
      {
        "korean": "장점과 단점을 따져 봐야 해요.",
        "romanized": "Jangjeomgwa danjeomeul ttajyeo bwaya haeyo.",
        "en": "We need to weigh the pros and cons.",
        "vi": "Cần cân nhắc ưu và nhược điểm."
      },
      {
        "korean": "어느 것이 더 효율적이라고 생각하세요?",
        "romanized": "Eoneu geosi deo hyoyuljeogirago saenggakhaseyo?",
        "en": "Which one do you think is more efficient?",
        "vi": "Bạn nghĩ cái nào hiệu quả hơn?"
      },
      {
        "korean": "비교 결과가 흥미로웠어요.",
        "romanized": "Bigyo gyeolgwaga heungmirowosseoyo.",
        "en": "The comparison result was interesting.",
        "vi": "Kết quả so sánh rất thú vị."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "이 핸드폰과 저 핸드폰 중에 뭐가 더 좋아요?",
        "meaning": "Between this phone and that phone, which is better?"
      },
      {
        "speaker": "B",
        "hangul": "이쪽이 카메라가 더 좋지만 배터리는 짧아요.",
        "meaning": "This one has a better camera but shorter battery."
      },
      {
        "speaker": "A",
        "hangul": "가격은 비슷한가요?",
        "meaning": "Are the prices similar?"
      },
      {
        "speaker": "B",
        "hangul": "아니요, 이게 조금 더 비싸요.",
        "meaning": "No, this one is a bit more expensive."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "이 옵션과 저 옵션을 ___해 보세요.",
        "answer": "비교"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "장점",
            "meaning": "advantage"
          },
          {
            "hangul": "단점",
            "meaning": "disadvantage"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Chúng ta cần cân nhắc ưu và nhược điểm.",
        "hangul": "장점과 단점을 따져 봐야 해요."
      }
    ]
  },
  {
    "id": 42,
    "level": "B1",
    "title_vi": "Tình huống giả định",
    "title_en": "Hypothetical Situations",
    "intro_vi": "Dùng 가상 cho giả định. Dùng -면 -을 텐데 cho giả định có điều kiện.",
    "vocabulary": [
      {
        "hangul": "가상",
        "meaning": "hypothetical"
      },
      {
        "hangul": "상황",
        "meaning": "situation"
      },
      {
        "hangul": "만약",
        "meaning": "if"
      },
      {
        "hangul": "가정하다",
        "meaning": "to assume"
      },
      {
        "hangul": "상상",
        "meaning": "imagination"
      },
      {
        "hangul": "현실",
        "meaning": "reality"
      },
      {
        "hangul": "가능성",
        "meaning": "possibility"
      },
      {
        "hangul": "꿈",
        "meaning": "dream"
      },
      {
        "hangul": "소원",
        "meaning": "wish"
      },
      {
        "hangul": "행동",
        "meaning": "action"
      }
    ],
    "sentences": [
      {
        "korean": "만약 내가 백만장자라면 무엇을 할까?",
        "romanized": "Manyak naega baekmanjangjaramyeon mueoseul halkka?",
        "en": "If I were a millionaire, what would I do?",
        "vi": "Nếu tôi là triệu phú, tôi sẽ làm gì?"
      },
      {
        "korean": "그 상황이 현실이라면 어쩌겠어요?",
        "romanized": "Geu sanghwangi hyeonsiriramyeon eojjeogesseoyo?",
        "en": "If that situation were real, what would you do?",
        "vi": "Nếu tình huống đó là thật, bạn sẽ làm gì?"
      },
      {
        "korean": "가상의 시나리오를 생각해 봅시다.",
        "romanized": "Gasangui sinarioreul saenggakhae bopsida.",
        "en": "Let's think of a hypothetical scenario.",
        "vi": "Hãy nghĩ về một kịch bản giả định."
      },
      {
        "korean": "소원이 이루어진다면 가장 먼저 뭘 하고 싶어요?",
        "romanized": "Sowoni irueojindamyeon gajang meonjeo mwol hago sipeoyo?",
        "en": "If your wish came true, what would you want to do first?",
        "vi": "Nếu điều ước thành sự thật, bạn muốn làm gì đầu tiên?"
      },
      {
        "korean": "꿈을 쫓는 것이 중요해요.",
        "romanized": "Kkumeul jjotneun geosi jungyohaeyo.",
        "en": "It's important to chase your dreams.",
        "vi": "Theo đuổi ước mơ là điều quan trọng."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "만약 시간을 되돌릴 수 있다면 뭘 하고 싶어요?",
        "meaning": "If you could turn back time, what would you want to do?"
      },
      {
        "speaker": "B",
        "hangul": "더 열심히 공부할 거예요.",
        "meaning": "I would study harder."
      },
      {
        "speaker": "A",
        "hangul": "저도요. 후회되는 일이 있어요.",
        "meaning": "Me too. I have some regrets."
      },
      {
        "speaker": "B",
        "hangul": "하지만 과거는 바꿀 수 없으니 미래를 위해 노력합시다.",
        "meaning": "But we can't change the past, so let's work for the future."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "___ 내가 백만장자라면 무엇을 할까?",
        "answer": "만약"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "가상",
            "meaning": "hypothetical"
          },
          {
            "hangul": "상상",
            "meaning": "imagination"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Nếu tôi có thể quay ngược thời gian, tôi sẽ học chăm chỉ hơn.",
        "hangul": "만약 시간을 되돌릴 수 있다면 더 열심히 공부할 거예요."
      }
    ]
  },
  {
    "id": 43,
    "level": "B1",
    "title_vi": "Tường thuật lời nói",
    "title_en": "Reporting Speech",
    "intro_vi": "Dùng 전달 화법 cho lời nói tường thuật. Học các mẫu -다고 하다 và -라고 하다.",
    "vocabulary": [
      {
        "hangul": "전달",
        "meaning": "report / delivery"
      },
      {
        "hangul": "화법",
        "meaning": "speech style"
      },
      {
        "hangul": "인용",
        "meaning": "quotation"
      },
      {
        "hangul": "직접 화법",
        "meaning": "direct speech"
      },
      {
        "hangul": "간접 화법",
        "meaning": "indirect speech"
      },
      {
        "hangul": "말하다",
        "meaning": "to say"
      },
      {
        "hangul": "주장하다",
        "meaning": "to claim"
      },
      {
        "hangul": "묻다",
        "meaning": "to ask"
      },
      {
        "hangul": "대답하다",
        "meaning": "to answer"
      },
      {
        "hangul": "전하다",
        "meaning": "to convey"
      }
    ],
    "sentences": [
      {
        "korean": "그가 내일 올 거라고 했어요.",
        "romanized": "Geuga naeil ol georago haesseoyo.",
        "en": "He said he would come tomorrow.",
        "vi": "Anh ấy nói sẽ đến vào ngày mai."
      },
      {
        "korean": "그녀는 자기는 배고프지 않다고 말했어요.",
        "romanized": "Geunyeoneun jagineun baegopeuji antago malhaesseoyo.",
        "en": "She said she was not hungry.",
        "vi": "Cô ấy nói rằng cô ấy không đói."
      },
      {
        "korean": "선생님께서 숙제를 내일까지 하라고 하셨어요.",
        "romanized": "Seonsaengnimkkeseo sukjereul naeilkkaji harago hasyeosseoyo.",
        "en": "The teacher told us to do the homework by tomorrow.",
        "vi": "Thầy bảo phải làm bài tập đến ngày mai."
      },
      {
        "korean": "그가 뭐라고 했어요?",
        "romanized": "Geuga mworago haesseoyo?",
        "en": "What did he say?",
        "vi": "Anh ấy đã nói gì?"
      },
      {
        "korean": "그 소식을 친구에게 전했어요.",
        "romanized": "Geu sosigeul chinguege jeonhaesseoyo.",
        "en": "I conveyed the news to my friend.",
        "vi": "Tôi đã chuyển tin đó cho bạn."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "민수가 뭐라고 했어요?",
        "meaning": "What did Minsu say?"
      },
      {
        "speaker": "B",
        "hangul": "내일 시간이 안 된다고 했어요.",
        "meaning": "He said he doesn't have time tomorrow."
      },
      {
        "speaker": "A",
        "hangul": "그럼 모레는 괜찮다고 물어봐 주세요.",
        "meaning": "Then please ask if the day after tomorrow is okay."
      },
      {
        "speaker": "B",
        "hangul": "알겠어요. 전해 줄게요.",
        "meaning": "Okay. I'll pass it on."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "그가 내일 올 ___고 했어요.",
        "answer": "거라"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "직접 화법",
            "meaning": "direct speech"
          },
          {
            "hangul": "간접 화법",
            "meaning": "indirect speech"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Cô ấy nói rằng cô ấy không đói.",
        "hangul": "그녀는 자기는 배고프지 않다고 말했어요."
      }
    ]
  },
  {
    "id": 44,
    "level": "B1",
    "title_vi": "Câu bị động",
    "title_en": "Passive Voice",
    "intro_vi": "Dùng 수동태 cho câu bị động. Học các đuôi bị động như -이/히/리/기-.",
    "vocabulary": [
      {
        "hangul": "수동태",
        "meaning": "passive voice"
      },
      {
        "hangul": "능동태",
        "meaning": "active voice"
      },
      {
        "hangul": "동사",
        "meaning": "verb"
      },
      {
        "hangul": "주어",
        "meaning": "subject"
      },
      {
        "hangul": "목적어",
        "meaning": "object"
      },
      {
        "hangul": "쓰이다",
        "meaning": "to be used"
      },
      {
        "hangul": "열리다",
        "meaning": "to be opened"
      },
      {
        "hangul": "닫히다",
        "meaning": "to be closed"
      },
      {
        "hangul": "만들어지다",
        "meaning": "to be made"
      },
      {
        "hangul": "알려지다",
        "meaning": "to be known"
      }
    ],
    "sentences": [
      {
        "korean": "이 문은 아침 9시에 열립니다.",
        "romanized": "I muneun achim 9sie yeolrimnida.",
        "en": "This door is opened at 9 AM.",
        "vi": "Cánh cửa này được mở lúc 9 giờ sáng."
      },
      {
        "korean": "한국어가 세계에서 많이 쓰이고 있어요.",
        "romanized": "Hangugeoga segyeeseo mani sseuigo isseoyo.",
        "en": "Korean is being used a lot in the world.",
        "vi": "Tiếng Hàn đang được sử dụng nhiều trên thế giới."
      },
      {
        "korean": "그 소식은 금방 알려졌어요.",
        "romanized": "Geu sosigeun geumbang alryeojyeosseoyo.",
        "en": "That news was quickly known.",
        "vi": "Tin đó nhanh chóng được biết đến."
      },
      {
        "korean": "이 빵은 밀가루로 만들어져요.",
        "romanized": "I ppangeun milgaruro mandeureojyeoyo.",
        "en": "This bread is made from flour.",
        "vi": "Bánh mì này được làm từ bột mì."
      },
      {
        "korean": "창문이 닫혀 있어요.",
        "romanized": "Changmuni dathyeo isseoyo.",
        "en": "The window is closed.",
        "vi": "Cửa sổ đang đóng."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "이 건물은 언제 지어졌어요?",
        "meaning": "When was this building built?"
      },
      {
        "speaker": "B",
        "hangul": "10년 전에 지어졌어요.",
        "meaning": "It was built 10 years ago."
      },
      {
        "speaker": "A",
        "hangul": "누구에 의해 설계되었나요?",
        "meaning": "By whom was it designed?"
      },
      {
        "speaker": "B",
        "hangul": "유명한 건축가에 의해 설계되었어요.",
        "meaning": "It was designed by a famous architect."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "이 문은 아침 9시에 ___.",
        "answer": "열립니다"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "열리다",
            "meaning": "to be opened"
          },
          {
            "hangul": "닫히다",
            "meaning": "to be closed"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Tin tức đó nhanh chóng được biết đến.",
        "hangul": "그 소식은 금방 알려졌어요."
      }
    ]
  },
  {
    "id": 45,
    "level": "B1",
    "title_vi": "Mệnh đề quan hệ",
    "title_en": "Relative Clauses",
    "intro_vi": "Dùng 관형사절 cho mệnh đề quan hệ. Học -는, -은, -을 để bổ nghĩa danh từ.",
    "vocabulary": [
      {
        "hangul": "관형사절",
        "meaning": "relative clause"
      },
      {
        "hangul": "수식",
        "meaning": "modification"
      },
      {
        "hangul": "명사",
        "meaning": "noun"
      },
      {
        "hangul": "관형사",
        "meaning": "determiner"
      },
      {
        "hangul": "형용사",
        "meaning": "adjective"
      },
      {
        "hangul": "현재",
        "meaning": "present tense"
      },
      {
        "hangul": "과거",
        "meaning": "past tense"
      },
      {
        "hangul": "미래",
        "meaning": "future tense"
      },
      {
        "hangul": "연결",
        "meaning": "connection"
      },
      {
        "hangul": "관계",
        "meaning": "relation"
      }
    ],
    "sentences": [
      {
        "korean": "제가 산 책이 재미있어요.",
        "romanized": "Jega san chaegi jaemiisseoyo.",
        "en": "The book that I bought is interesting.",
        "vi": "Quyển sách tôi mua rất hay."
      },
      {
        "korean": "한국어를 배우는 사람이 많아요.",
        "romanized": "Hangugeoreul baeuneun sarami manayo.",
        "en": "There are many people who learn Korean.",
        "vi": "Có nhiều người học tiếng Hàn."
      },
      {
        "korean": "어제 만난 친구가 전화했어요.",
        "romanized": "Eoje mannan chinguga jeonhwahaesseoyo.",
        "en": "The friend I met yesterday called.",
        "vi": "Người bạn tôi gặp hôm qua đã gọi điện."
      },
      {
        "korean": "먹을 음식을 준비할게요.",
        "romanized": "Meogeul eumsigeul junbihalgeyo.",
        "en": "I will prepare food to eat.",
        "vi": "Tôi sẽ chuẩn bị thức ăn để ăn."
      },
      {
        "korean": "그가 쓴 편지를 읽었어요.",
        "romanized": "Geuga sseun pyeonjireul ilgeosseoyo.",
        "en": "I read the letter that he wrote.",
        "vi": "Tôi đọc lá thư anh ấy viết."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "어제 산 치마가 마음에 들어요?",
        "meaning": "Do you like the skirt you bought yesterday?"
      },
      {
        "speaker": "B",
        "hangul": "네, 그런데 좀 작아요.",
        "meaning": "Yes, but it's a bit small."
      },
      {
        "speaker": "A",
        "hangul": "다른 색으로 교환할 수 있어요.",
        "meaning": "You can exchange it for another color."
      },
      {
        "speaker": "B",
        "hangul": "괜찮아요. 그냥 입을게요.",
        "meaning": "It's okay. I'll just wear it."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "제가 ___ 책이 재미있어요.",
        "answer": "산"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "현재",
            "meaning": "present tense"
          },
          {
            "hangul": "과거",
            "meaning": "past tense"
          }
        ],
        "instruction": "Match Korean with English"
      },
      {
        "type": "translation",
        "vietnamese": "Có nhiều người học tiếng Hàn.",
        "hangul": "한국어를 배우는 사람이 많아요."
      }
    ]
  }
];

export default lessons;
