// Auto-generated by scripts/split-lessons-by-level.mjs.
// Edit the source lesson content here directly. DO NOT regenerate
// from a stale lessons.ts — the registry replaced that file.

import type { KoreanLesson } from "./lessons";

export const lessons: KoreanLesson[] = [
  {
    "id": 1,
    "level": "A1",
    "title_vi": "Nguyên âm cơ bản",
    "title_en": "Basic Vowels",
    "intro_vi": "10 nguyên âm cơ bản trong Hangul. Đây là nền tảng của chữ viết tiếng Hàn.",
    "vocabulary": [
      {
        "hangul": "ㅏ",
        "meaning": "a"
      },
      {
        "hangul": "ㅑ",
        "meaning": "ya"
      },
      {
        "hangul": "ㅓ",
        "meaning": "eo (ơ)"
      },
      {
        "hangul": "ㅕ",
        "meaning": "yeo"
      },
      {
        "hangul": "ㅗ",
        "meaning": "o (ô)"
      },
      {
        "hangul": "ㅛ",
        "meaning": "yo"
      },
      {
        "hangul": "ㅜ",
        "meaning": "u"
      },
      {
        "hangul": "ㅠ",
        "meaning": "yu"
      },
      {
        "hangul": "ㅡ",
        "meaning": "eu (ư)"
      },
      {
        "hangul": "ㅣ",
        "meaning": "i"
      }
    ],
    "sentences": [
      {
        "korean": "아",
        "romanized": "a",
        "en": "a",
        "vi": "Nguyên âm 'a'"
      },
      {
        "korean": "야",
        "romanized": "ya",
        "en": "ya",
        "vi": "Nguyên âm 'ya'"
      },
      {
        "korean": "어",
        "romanized": "eo",
        "en": "eo",
        "vi": "Nguyên âm 'eo'"
      },
      {
        "korean": "오",
        "romanized": "o",
        "en": "o",
        "vi": "Nguyên âm 'ô'"
      },
      {
        "korean": "우",
        "romanized": "u",
        "en": "u",
        "vi": "Nguyên âm 'u'"
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "이게 뭐예요?",
        "meaning": "What is this?",
        "text_vi": "Cái này là gì?"
      },
      {
        "speaker": "B",
        "hangul": "그건 '아'예요.",
        "meaning": "That is 'a'.",
        "text_vi": "Đó là chữ 'a'."
      },
      {
        "speaker": "A",
        "hangul": "아, 알겠어요.",
        "meaning": "Ah, I understand.",
        "text_vi": "À, tôi hiểu rồi."
      },
      {
        "speaker": "B",
        "hangul": "네, 잘했어요!",
        "meaning": "Yes, well done!",
        "text_vi": "Vâng, bạn làm tốt lắm!"
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "Nguyên âm giống 'ơ' là ___",
        "answer": "ㅓ"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "ㅏ",
            "meaning": "a"
          },
          {
            "hangul": "ㅗ",
            "meaning": "o"
          }
        ],
        "instruction": "Ghép nguyên âm"
      },
      {
        "type": "translation",
        "vietnamese": "Nguyên âm 'i' là gì?",
        "hangul": "ㅣ"
      }
    ]
  },
  {
    "id": 2,
    "level": "A1",
    "title_vi": "Phụ âm cơ bản",
    "title_en": "Basic Consonants",
    "intro_vi": "14 phụ âm cơ bản trong Hangul. Cách phát âm thay đổi tùy vị trí.",
    "vocabulary": [
      {
        "hangul": "ㄱ",
        "meaning": "g/k"
      },
      {
        "hangul": "ㄴ",
        "meaning": "n"
      },
      {
        "hangul": "ㄷ",
        "meaning": "d/t"
      },
      {
        "hangul": "ㄹ",
        "meaning": "r/l"
      },
      {
        "hangul": "ㅁ",
        "meaning": "m"
      },
      {
        "hangul": "ㅂ",
        "meaning": "b/p"
      },
      {
        "hangul": "ㅅ",
        "meaning": "s"
      },
      {
        "hangul": "ㅇ",
        "meaning": "ng/null"
      },
      {
        "hangul": "ㅈ",
        "meaning": "j"
      },
      {
        "hangul": "ㅎ",
        "meaning": "h"
      }
    ],
    "sentences": [
      {
        "korean": "가",
        "romanized": "ga",
        "en": "ga",
        "vi": "Âm tiết 'ga'"
      },
      {
        "korean": "나",
        "romanized": "na",
        "en": "na",
        "vi": "Âm tiết 'na'"
      },
      {
        "korean": "다",
        "romanized": "da",
        "en": "da",
        "vi": "Âm tiết 'da'"
      },
      {
        "korean": "마",
        "romanized": "ma",
        "en": "ma",
        "vi": "Âm tiết 'ma'"
      },
      {
        "korean": "바",
        "romanized": "ba",
        "en": "ba",
        "vi": "Âm tiết 'ba'"
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "이건 무슨 글자예요?",
        "meaning": "What letter?",
        "text_vi": "Đây là chữ gì?"
      },
      {
        "speaker": "B",
        "hangul": "'ㄱ'이에요.",
        "meaning": "It's ㄱ.",
        "text_vi": "Là chữ 'ㄱ'."
      },
      {
        "speaker": "A",
        "hangul": "어려워요.",
        "meaning": "It's hard.",
        "text_vi": "Khó quá."
      },
      {
        "speaker": "B",
        "hangul": "괜찮아요. 연습하면 돼요.",
        "meaning": "Practice makes perfect.",
        "text_vi": "Không sao đâu. Cứ luyện tập là được."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "Phụ âm giống 'n' là ___",
        "answer": "ㄴ"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "ㄱ",
            "meaning": "g/k"
          },
          {
            "hangul": "ㅁ",
            "meaning": "m"
          }
        ],
        "instruction": "Ghép phụ âm"
      },
      {
        "type": "translation",
        "vietnamese": "Phụ âm 'h' là gì?",
        "hangul": "ㅎ"
      }
    ]
  },
  {
    "id": 3,
    "level": "A1",
    "title_vi": "Khối âm tiết",
    "title_en": "Syllable Blocks",
    "intro_vi": "Mỗi âm tiết = phụ âm + nguyên âm. ㅇ là âm câm khi đứng đầu.",
    "vocabulary": [
      {
        "hangul": "가",
        "meaning": "ga"
      },
      {
        "hangul": "나",
        "meaning": "na"
      },
      {
        "hangul": "다",
        "meaning": "da"
      },
      {
        "hangul": "라",
        "meaning": "ra"
      },
      {
        "hangul": "마",
        "meaning": "ma"
      },
      {
        "hangul": "바",
        "meaning": "ba"
      },
      {
        "hangul": "사",
        "meaning": "sa"
      },
      {
        "hangul": "아",
        "meaning": "a"
      },
      {
        "hangul": "자",
        "meaning": "ja"
      },
      {
        "hangul": "하",
        "meaning": "ha"
      }
    ],
    "sentences": [
      {
        "korean": "가가 가요.",
        "romanized": "Gaga gayo.",
        "en": "Ga is going.",
        "vi": "Ga đang đi."
      },
      {
        "korean": "아기가 자요.",
        "romanized": "Agiga jayo.",
        "en": "Baby is sleeping.",
        "vi": "Em bé đang ngủ."
      },
      {
        "korean": "바다가 파래요.",
        "romanized": "Badaga paraeyo.",
        "en": "The sea is blue.",
        "vi": "Biển màu xanh."
      },
      {
        "korean": "사자가 자요.",
        "romanized": "Sajaga jayo.",
        "en": "Lion sleeps.",
        "vi": "Sư tử ngủ."
      },
      {
        "korean": "나가 가요.",
        "romanized": "Naga gayo.",
        "en": "Going out.",
        "vi": "Đi ra ngoài."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "이 글자 읽을 수 있어요?",
        "meaning": "Can you read this?",
        "text_vi": "Bạn đọc được chữ này không?"
      },
      {
        "speaker": "B",
        "hangul": "네, '가'예요.",
        "meaning": "Yes, it's 'ga'.",
        "text_vi": "Vâng, là 'ga'."
      },
      {
        "speaker": "A",
        "hangul": "잘했어요!",
        "meaning": "Well done!",
        "text_vi": "Làm tốt lắm!"
      },
      {
        "speaker": "B",
        "hangul": "감사합니다!",
        "meaning": "Thank you!",
        "text_vi": "Cảm ơn ạ!"
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'사자' là ___",
        "answer": "sư tử"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "바다",
            "meaning": "biển"
          },
          {
            "hangul": "아기",
            "meaning": "em bé"
          }
        ],
        "instruction": "Ghép từ"
      },
      {
        "type": "translation",
        "vietnamese": "Con sư tử",
        "hangul": "사자"
      }
    ]
  },
  {
    "id": 4,
    "level": "A1",
    "title_vi": "Phụ âm đôi",
    "title_en": "Double Consonants",
    "intro_vi": "5 phụ âm căng (fortis): ㄲㄸㅃㅆㅉ. Phát âm mạnh và căng hơn.",
    "vocabulary": [
      {
        "hangul": "ㄲ",
        "meaning": "kk"
      },
      {
        "hangul": "ㄸ",
        "meaning": "tt"
      },
      {
        "hangul": "ㅃ",
        "meaning": "pp"
      },
      {
        "hangul": "ㅆ",
        "meaning": "ss"
      },
      {
        "hangul": "ㅉ",
        "meaning": "jj"
      },
      {
        "hangul": "까",
        "meaning": "kka"
      },
      {
        "hangul": "따",
        "meaning": "tta"
      },
      {
        "hangul": "빠",
        "meaning": "ppa"
      },
      {
        "hangul": "싸",
        "meaning": "ssa"
      },
      {
        "hangul": "짜",
        "meaning": "jja"
      }
    ],
    "sentences": [
      {
        "korean": "까만색이에요.",
        "romanized": "Kkamansaegieyo.",
        "en": "It's black.",
        "vi": "Nó màu đen."
      },
      {
        "korean": "따뜻해요.",
        "romanized": "Ttatteushaeyo.",
        "en": "It's warm.",
        "vi": "Nó ấm áp."
      },
      {
        "korean": "빨리 가요.",
        "romanized": "Ppalli gayo.",
        "en": "Go quickly.",
        "vi": "Đi nhanh."
      },
      {
        "korean": "싸요.",
        "romanized": "Ssayo.",
        "en": "It's cheap.",
        "vi": "Nó rẻ."
      },
      {
        "korean": "짜요.",
        "romanized": "Jjayo.",
        "en": "It's salty.",
        "vi": "Nó mặn."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "이거 비싸요?",
        "meaning": "Is it expensive?",
        "text_vi": "Cái này có đắt không?"
      },
      {
        "speaker": "B",
        "hangul": "아니요, 싸요.",
        "meaning": "No, it's cheap.",
        "text_vi": "Không, rẻ mà."
      },
      {
        "speaker": "A",
        "hangul": "빨리 사세요!",
        "meaning": "Buy it fast!",
        "text_vi": "Mua nhanh đi!"
      },
      {
        "speaker": "B",
        "hangul": "네, 살게요.",
        "meaning": "Yes, I'll buy it.",
        "text_vi": "Vâng, tôi sẽ mua."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'Rẻ' là ___",
        "answer": "싸요"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "빨리",
            "meaning": "nhanh"
          },
          {
            "hangul": "따뜻해요",
            "meaning": "ấm áp"
          }
        ],
        "instruction": "Ghép từ"
      },
      {
        "type": "translation",
        "vietnamese": "Nó màu đen.",
        "hangul": "까만색이에요."
      }
    ]
  },
  {
    "id": 5,
    "level": "A1",
    "title_vi": "Nguyên âm ghép",
    "title_en": "Compound Vowels",
    "intro_vi": "11 nguyên âm ghép: ㅐㅒㅔㅖㅘㅙㅚㅝㅞㅟㅢ.",
    "vocabulary": [
      {
        "hangul": "ㅐ",
        "meaning": "ae"
      },
      {
        "hangul": "ㅔ",
        "meaning": "e"
      },
      {
        "hangul": "ㅘ",
        "meaning": "wa"
      },
      {
        "hangul": "ㅙ",
        "meaning": "wae"
      },
      {
        "hangul": "ㅚ",
        "meaning": "oe"
      },
      {
        "hangul": "ㅝ",
        "meaning": "wo"
      },
      {
        "hangul": "ㅞ",
        "meaning": "we"
      },
      {
        "hangul": "ㅟ",
        "meaning": "wi"
      },
      {
        "hangul": "ㅢ",
        "meaning": "ui"
      },
      {
        "hangul": "ㅒ",
        "meaning": "yae"
      }
    ],
    "sentences": [
      {
        "korean": "왜 왔어요?",
        "romanized": "Wae wasseoyo?",
        "en": "Why did you come?",
        "vi": "Sao bạn đến?"
      },
      {
        "korean": "괜찮아요.",
        "romanized": "Gwaenchanayo.",
        "en": "It's okay.",
        "vi": "Không sao."
      },
      {
        "korean": "뭐 해요?",
        "romanized": "Mwo haeyo?",
        "en": "What are you doing?",
        "vi": "Bạn làm gì?"
      },
      {
        "korean": "돼요.",
        "romanized": "Dwaeyo.",
        "en": "It's fine.",
        "vi": "Được."
      },
      {
        "korean": "쉬워요.",
        "romanized": "Swiwoyo.",
        "en": "It's easy.",
        "vi": "Dễ."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "한국어 어때요?",
        "meaning": "How's Korean?",
        "text_vi": "Tiếng Hàn thế nào?"
      },
      {
        "speaker": "B",
        "hangul": "쉬워요!",
        "meaning": "Easy!",
        "text_vi": "Dễ lắm!"
      },
      {
        "speaker": "A",
        "hangul": "정말요?",
        "meaning": "Really?",
        "text_vi": "Thật không?"
      },
      {
        "speaker": "B",
        "hangul": "네, 한글은 배우기 쉬워요.",
        "meaning": "Yes, Hangul is easy.",
        "text_vi": "Vâng, Hangeul học rất dễ."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'Không sao' là ___",
        "answer": "괜찮아요"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "왜",
            "meaning": "tại sao"
          },
          {
            "hangul": "뭐",
            "meaning": "cái gì"
          }
        ],
        "instruction": "Ghép từ hỏi"
      },
      {
        "type": "translation",
        "vietnamese": "Nó dễ.",
        "hangul": "쉬워요."
      }
    ]
  },
  {
    "id": 6,
    "level": "A1",
    "title_vi": "Phụ âm cuối (받침)",
    "title_en": "Final Consonants",
    "intro_vi": "받침 là phụ âm cuối âm tiết. Chỉ 7 âm được phát âm ở vị trí cuối.",
    "vocabulary": [
      {
        "hangul": "받침",
        "meaning": "phụ âm cuối"
      },
      {
        "hangul": "각",
        "meaning": "gak"
      },
      {
        "hangul": "간",
        "meaning": "gan"
      },
      {
        "hangul": "갈",
        "meaning": "gal"
      },
      {
        "hangul": "감",
        "meaning": "gam"
      },
      {
        "hangul": "갑",
        "meaning": "gap"
      },
      {
        "hangul": "갓",
        "meaning": "gat"
      },
      {
        "hangul": "강",
        "meaning": "gang"
      },
      {
        "hangul": "값",
        "meaning": "gap (giá)"
      },
      {
        "hangul": "같",
        "meaning": "gat"
      }
    ],
    "sentences": [
      {
        "korean": "한국 사람이에요.",
        "romanized": "Hanguk saramieyo.",
        "en": "I am Korean.",
        "vi": "Tôi là người Hàn."
      },
      {
        "korean": "밥을 먹어요.",
        "romanized": "Babeul meogeoyo.",
        "en": "I eat rice.",
        "vi": "Tôi ăn cơm."
      },
      {
        "korean": "책을 읽어요.",
        "romanized": "Chaekeul ilgeoyo.",
        "en": "I read a book.",
        "vi": "Tôi đọc sách."
      },
      {
        "korean": "꽃이 예뻐요.",
        "romanized": "Kkochi yeppeoyo.",
        "en": "The flower is pretty.",
        "vi": "Hoa đẹp."
      },
      {
        "korean": "산에 가요.",
        "romanized": "Sane gayo.",
        "en": "I go to the mountain.",
        "vi": "Tôi đi lên núi."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "어디 가요?",
        "meaning": "Where?",
        "text_vi": "Bạn đi đâu vậy?"
      },
      {
        "speaker": "B",
        "hangul": "산에 가요.",
        "meaning": "To the mountain.",
        "text_vi": "Tôi đi lên núi."
      },
      {
        "speaker": "A",
        "hangul": "누구랑?",
        "meaning": "With whom?",
        "text_vi": "Đi với ai?"
      },
      {
        "speaker": "B",
        "hangul": "친구랑 같이.",
        "meaning": "With a friend.",
        "text_vi": "Đi cùng bạn."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'Tôi ăn cơm': 밥을 ___",
        "answer": "먹어요"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "책",
            "meaning": "sách"
          },
          {
            "hangul": "산",
            "meaning": "núi"
          }
        ],
        "instruction": "Ghép từ"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi là người Hàn.",
        "hangul": "한국 사람이에요."
      }
    ]
  },
  {
    "id": 7,
    "level": "A1",
    "title_vi": "Phụ âm cuối kép",
    "title_en": "Complex Final Consonants",
    "intro_vi": "Âm tiết có 2 phụ âm cuối. Khi đứng một mình chỉ phát âm phụ âm bên trái.",
    "vocabulary": [
      {
        "hangul": "ㄳ",
        "meaning": "gs→ㄱ"
      },
      {
        "hangul": "ㄵ",
        "meaning": "nj→ㄴ"
      },
      {
        "hangul": "ㄺ",
        "meaning": "lg→ㄱ"
      },
      {
        "hangul": "ㄻ",
        "meaning": "lm→ㅁ"
      },
      {
        "hangul": "ㄼ",
        "meaning": "lb→ㄹ"
      },
      {
        "hangul": "ㄽ",
        "meaning": "ls→ㄹ"
      },
      {
        "hangul": "ㄾ",
        "meaning": "lt→ㄹ"
      },
      {
        "hangul": "ㅀ",
        "meaning": "lh→ㄹ"
      },
      {
        "hangul": "ㅄ",
        "meaning": "bs→ㅂ"
      },
      {
        "hangul": "ㄿ",
        "meaning": "lp→ㅂ"
      }
    ],
    "sentences": [
      {
        "korean": "닭을 먹어요.",
        "romanized": "Dalgeul meogeoyo.",
        "en": "I eat chicken.",
        "vi": "Tôi ăn gà."
      },
      {
        "korean": "앉으세요.",
        "romanized": "Anjeuseyo.",
        "en": "Please sit.",
        "vi": "Mời ngồi."
      },
      {
        "korean": "값이 비싸요.",
        "romanized": "Gapsi bissayo.",
        "en": "The price is high.",
        "vi": "Giá đắt."
      },
      {
        "korean": "넓어요.",
        "romanized": "Neolbeoyo.",
        "en": "It's wide.",
        "vi": "Nó rộng."
      },
      {
        "korean": "읊어요.",
        "romanized": "Eulpeoyo.",
        "en": "I recite.",
        "vi": "Tôi ngâm thơ."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "여기 앉으세요.",
        "meaning": "Sit here.",
        "text_vi": "Mời ngồi đây ạ."
      },
      {
        "speaker": "B",
        "hangul": "감사합니다.",
        "meaning": "Thanks.",
        "text_vi": "Cảm ơn ạ."
      },
      {
        "speaker": "A",
        "hangul": "뭐 드실래요?",
        "meaning": "What to eat?",
        "text_vi": "Bạn muốn ăn gì?"
      },
      {
        "speaker": "B",
        "hangul": "닭 먹을래요.",
        "meaning": "I'll have chicken.",
        "text_vi": "Tôi muốn ăn gà."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'Mời ngồi': ___",
        "answer": "앉으세요"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "값",
            "meaning": "giá"
          },
          {
            "hangul": "닭",
            "meaning": "gà"
          }
        ],
        "instruction": "Ghép từ"
      },
      {
        "type": "translation",
        "vietnamese": "Nó rộng.",
        "hangul": "넓어요."
      }
    ]
  },
  {
    "id": 8,
    "level": "A1",
    "title_vi": "Chào hỏi",
    "title_en": "Greetings",
    "intro_vi": "Các câu chào hỏi cơ bản. 안녕하세요 là cách chào lịch sự phổ biến nhất.",
    "vocabulary": [
      {
        "hangul": "안녕하세요",
        "meaning": "Xin chào"
      },
      {
        "hangul": "감사합니다",
        "meaning": "Cảm ơn"
      },
      {
        "hangul": "네",
        "meaning": "Vâng"
      },
      {
        "hangul": "아니요",
        "meaning": "Không"
      },
      {
        "hangul": "안녕히 가세요",
        "meaning": "Tạm biệt (người đi)"
      },
      {
        "hangul": "안녕히 계세요",
        "meaning": "Tạm biệt (người ở)"
      },
      {
        "hangul": "죄송합니다",
        "meaning": "Xin lỗi"
      },
      {
        "hangul": "괜찮아요",
        "meaning": "Không sao"
      },
      {
        "hangul": "반갑습니다",
        "meaning": "Rất vui gặp"
      },
      {
        "hangul": "또 만나요",
        "meaning": "Hẹn gặp lại"
      }
    ],
    "sentences": [
      {
        "korean": "안녕하세요, 처음 뵙겠습니다.",
        "romanized": "Annyeonghaseyo, cheoeum boepgesseumnida.",
        "en": "Hello, nice to meet you.",
        "vi": "Xin chào, rất vui gặp bạn."
      },
      {
        "korean": "감사합니다.",
        "romanized": "Gamsahamnida.",
        "en": "Thank you.",
        "vi": "Cảm ơn."
      },
      {
        "korean": "안녕히 가세요.",
        "romanized": "Annyeonghi gaseyo.",
        "en": "Goodbye (to one leaving).",
        "vi": "Tạm biệt."
      },
      {
        "korean": "죄송합니다.",
        "romanized": "Joesonghamnida.",
        "en": "I'm sorry.",
        "vi": "Xin lỗi."
      },
      {
        "korean": "또 만나요.",
        "romanized": "Tto mannayo.",
        "en": "See you again.",
        "vi": "Hẹn gặp lại."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "안녕하세요! 저는 민수예요.",
        "meaning": "Hello! I'm Minsu.",
        "text_vi": "Xin chào! Tôi là Minsu."
      },
      {
        "speaker": "B",
        "hangul": "안녕하세요, 지영이에요. 반갑습니다.",
        "meaning": "Hi, I'm Jiyoung. Nice to meet you.",
        "text_vi": "Xin chào, tôi là Jiyoung. Rất vui được gặp bạn."
      },
      {
        "speaker": "A",
        "hangul": "지금 어디 가세요?",
        "meaning": "Where are you going?",
        "text_vi": "Bây giờ bạn đi đâu vậy?"
      },
      {
        "speaker": "B",
        "hangul": "집에 가요. 안녕히 계세요!",
        "meaning": "Going home. Bye!",
        "text_vi": "Tôi về nhà đây. Tạm biệt nhé!"
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'Xin chào' là ___",
        "answer": "안녕하세요"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "감사합니다",
            "meaning": "cảm ơn"
          },
          {
            "hangul": "죄송합니다",
            "meaning": "xin lỗi"
          }
        ],
        "instruction": "Ghép câu"
      },
      {
        "type": "translation",
        "vietnamese": "Tạm biệt, hẹn gặp lại.",
        "hangul": "안녕히 가세요. 또 만나요."
      }
    ]
  },
  {
    "id": 9,
    "level": "A1",
    "title_vi": "Tự giới thiệu",
    "title_en": "Self-Introduction",
    "intro_vi": "Cách giới thiệu bản thân. Dùng 저는 (tôi - khiêm tốn) trong tình huống trang trọng.",
    "vocabulary": [
      {
        "hangul": "저",
        "meaning": "tôi (khiêm tốn)"
      },
      {
        "hangul": "이름",
        "meaning": "tên"
      },
      {
        "hangul": "입니다",
        "meaning": "là"
      },
      {
        "hangul": "학생",
        "meaning": "học sinh"
      },
      {
        "hangul": "선생님",
        "meaning": "thầy/cô"
      },
      {
        "hangul": "회사원",
        "meaning": "nhân viên"
      },
      {
        "hangul": "한국 사람",
        "meaning": "người Hàn"
      },
      {
        "hangul": "베트남 사람",
        "meaning": "người Việt"
      },
      {
        "hangul": "에서 왔어요",
        "meaning": "đến từ"
      },
      {
        "hangul": "살",
        "meaning": "tuổi"
      }
    ],
    "sentences": [
      {
        "korean": "저는 마이클입니다.",
        "romanized": "Jeoneun Maikeurimnida.",
        "en": "I am Michael.",
        "vi": "Tôi là Michael."
      },
      {
        "korean": "저는 베트남 사람이에요.",
        "romanized": "Jeoneun Beteunam saramieyo.",
        "en": "I'm Vietnamese.",
        "vi": "Tôi là người Việt."
      },
      {
        "korean": "저는 학생입니다.",
        "romanized": "Jeoneun haksaengimnida.",
        "en": "I'm a student.",
        "vi": "Tôi là học sinh."
      },
      {
        "korean": "저는 스무 살이에요.",
        "romanized": "Jeoneun seumu sarieyo.",
        "en": "I'm 20.",
        "vi": "Tôi 20 tuổi."
      },
      {
        "korean": "하노이에서 왔어요.",
        "romanized": "Hanoieseo wasseoyo.",
        "en": "I'm from Hanoi.",
        "vi": "Tôi từ Hà Nội."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "이름이 뭐예요?",
        "meaning": "Your name?",
        "text_vi": "Bạn tên là gì?"
      },
      {
        "speaker": "B",
        "hangul": "저는 투안입니다.",
        "meaning": "I'm Tuan.",
        "text_vi": "Tôi là Tuấn."
      },
      {
        "speaker": "A",
        "hangul": "어디에서 오셨어요?",
        "meaning": "Where from?",
        "text_vi": "Bạn đến từ đâu?"
      },
      {
        "speaker": "B",
        "hangul": "베트남에서 왔어요.",
        "meaning": "From Vietnam.",
        "text_vi": "Tôi đến từ Việt Nam."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'Tôi là học sinh': 저는 ___",
        "answer": "학생입니다"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "회사원",
            "meaning": "nhân viên"
          },
          {
            "hangul": "학생",
            "meaning": "học sinh"
          }
        ],
        "instruction": "Ghép nghề"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi từ Việt Nam.",
        "hangul": "베트남에서 왔어요."
      }
    ]
  },
  {
    "id": 10,
    "level": "A1",
    "title_vi": "Số đếm 1-10",
    "title_en": "Numbers 1-10",
    "intro_vi": "Số thuần Hàn dùng đếm đồ vật, tuổi, giờ. Số Hán-Hàn dùng cho ngày tháng, tiền.",
    "vocabulary": [
      {
        "hangul": "하나",
        "meaning": "1"
      },
      {
        "hangul": "둘",
        "meaning": "2"
      },
      {
        "hangul": "셋",
        "meaning": "3"
      },
      {
        "hangul": "넷",
        "meaning": "4"
      },
      {
        "hangul": "다섯",
        "meaning": "5"
      },
      {
        "hangul": "여섯",
        "meaning": "6"
      },
      {
        "hangul": "일곱",
        "meaning": "7"
      },
      {
        "hangul": "여덟",
        "meaning": "8"
      },
      {
        "hangul": "아홉",
        "meaning": "9"
      },
      {
        "hangul": "열",
        "meaning": "10"
      }
    ],
    "sentences": [
      {
        "korean": "사과 하나 주세요.",
        "romanized": "Sagwa hana juseyo.",
        "en": "One apple please.",
        "vi": "Cho một quả táo."
      },
      {
        "korean": "스물다섯 살이에요.",
        "romanized": "Seumuldaseot sarieyo.",
        "en": "I'm 25.",
        "vi": "Tôi 25 tuổi."
      },
      {
        "korean": "커피 두 잔 주세요.",
        "romanized": "Keopi du jan juseyo.",
        "en": "Two coffees.",
        "vi": "Hai ly cà phê."
      },
      {
        "korean": "책 세 권 있어요.",
        "romanized": "Chaek se gwon isseoyo.",
        "en": "I have 3 books.",
        "vi": "Có 3 quyển sách."
      },
      {
        "korean": "한 시에 만나요.",
        "romanized": "Han sie mannayo.",
        "en": "Meet at 1.",
        "vi": "Gặp lúc 1 giờ."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "몇 살이에요?",
        "meaning": "How old?",
        "text_vi": "Bạn bao nhiêu tuổi?"
      },
      {
        "speaker": "B",
        "hangul": "스물셋 살이에요.",
        "meaning": "23.",
        "text_vi": "Tôi hai mươi ba tuổi."
      },
      {
        "speaker": "A",
        "hangul": "커피 몇 잔?",
        "meaning": "How many coffees?",
        "text_vi": "Mấy ly cà phê?"
      },
      {
        "speaker": "B",
        "hangul": "두 잔 주세요.",
        "meaning": "Two please.",
        "text_vi": "Cho tôi hai ly."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "Số 5 thuần Hàn: ___",
        "answer": "다섯"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "하나",
            "meaning": "1"
          },
          {
            "hangul": "열",
            "meaning": "10"
          }
        ],
        "instruction": "Ghép số"
      },
      {
        "type": "translation",
        "vietnamese": "Cho 3 quyển sách.",
        "hangul": "책 세 권 주세요."
      }
    ]
  },
  {
    "id": 11,
    "level": "A1",
    "title_vi": "Ngày trong tuần",
    "title_en": "Days of the Week",
    "intro_vi": "Tên ngày bắt đầu bằng thiên thể: 월(trăng), 화(lửa), 수(nước), 목(gỗ), 금(vàng), 토(đất), 일(mặt trời).",
    "vocabulary": [
      {
        "hangul": "월요일",
        "meaning": "Thứ Hai"
      },
      {
        "hangul": "화요일",
        "meaning": "Thứ Ba"
      },
      {
        "hangul": "수요일",
        "meaning": "Thứ Tư"
      },
      {
        "hangul": "목요일",
        "meaning": "Thứ Năm"
      },
      {
        "hangul": "금요일",
        "meaning": "Thứ Sáu"
      },
      {
        "hangul": "토요일",
        "meaning": "Thứ Bảy"
      },
      {
        "hangul": "일요일",
        "meaning": "Chủ Nhật"
      },
      {
        "hangul": "주말",
        "meaning": "cuối tuần"
      },
      {
        "hangul": "오늘",
        "meaning": "hôm nay"
      },
      {
        "hangul": "내일",
        "meaning": "ngày mai"
      }
    ],
    "sentences": [
      {
        "korean": "오늘은 월요일이에요.",
        "romanized": "Oneureun woryoilieyo.",
        "en": "Today is Monday.",
        "vi": "Hôm nay thứ Hai."
      },
      {
        "korean": "금요일에 영화 볼 거예요.",
        "romanized": "Geumyoire bol geoyeyo.",
        "en": "Watching a movie Friday.",
        "vi": "Thứ Sáu xem phim."
      },
      {
        "korean": "주말에 뭐 해요?",
        "romanized": "Jumare mwo haeyo?",
        "en": "What on weekend?",
        "vi": "Cuối tuần làm gì?"
      },
      {
        "korean": "내일 수요일이에요.",
        "romanized": "Naeil suyoilieyo.",
        "en": "Tomorrow is Wed.",
        "vi": "Mai thứ Tư."
      },
      {
        "korean": "일요일에 교회에 가요.",
        "romanized": "Iryoire gyohoee gayo.",
        "en": "Church on Sunday.",
        "vi": "CN đi nhà thờ."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "오늘 무슨 요일?",
        "meaning": "What day?",
        "text_vi": "Hôm nay thứ mấy?"
      },
      {
        "speaker": "B",
        "hangul": "금요일이에요!",
        "meaning": "Friday!",
        "text_vi": "Thứ Sáu rồi!"
      },
      {
        "speaker": "A",
        "hangul": "주말에 뭐 해요?",
        "meaning": "Weekend plans?",
        "text_vi": "Cuối tuần bạn làm gì?"
      },
      {
        "speaker": "B",
        "hangul": "쇼핑 갈 거예요.",
        "meaning": "Shopping.",
        "text_vi": "Tôi sẽ đi mua sắm."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'Thứ Hai' là ___",
        "answer": "월요일"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "주말",
            "meaning": "cuối tuần"
          },
          {
            "hangul": "오늘",
            "meaning": "hôm nay"
          }
        ],
        "instruction": "Ghép từ"
      },
      {
        "type": "translation",
        "vietnamese": "Hôm nay thứ Sáu.",
        "hangul": "오늘은 금요일이에요."
      }
    ]
  },
  {
    "id": 12,
    "level": "A1",
    "title_vi": "Động từ cơ bản",
    "title_en": "Basic Verbs",
    "intro_vi": "Động từ kết thúc bằng -다 ở dạng từ điển. Bỏ -다 để chia.",
    "vocabulary": [
      {
        "hangul": "하다",
        "meaning": "làm"
      },
      {
        "hangul": "가다",
        "meaning": "đi"
      },
      {
        "hangul": "오다",
        "meaning": "đến"
      },
      {
        "hangul": "먹다",
        "meaning": "ăn"
      },
      {
        "hangul": "마시다",
        "meaning": "uống"
      },
      {
        "hangul": "보다",
        "meaning": "xem"
      },
      {
        "hangul": "듣다",
        "meaning": "nghe"
      },
      {
        "hangul": "읽다",
        "meaning": "đọc"
      },
      {
        "hangul": "쓰다",
        "meaning": "viết"
      },
      {
        "hangul": "자다",
        "meaning": "ngủ"
      }
    ],
    "sentences": [
      {
        "korean": "밥을 먹어요.",
        "romanized": "Babeul meogeoyo.",
        "en": "I eat rice.",
        "vi": "Tôi ăn cơm."
      },
      {
        "korean": "물을 마셔요.",
        "romanized": "Mureul masyeoyo.",
        "en": "I drink water.",
        "vi": "Tôi uống nước."
      },
      {
        "korean": "학교에 가요.",
        "romanized": "Hakgyoe gayo.",
        "en": "I go to school.",
        "vi": "Tôi đi học."
      },
      {
        "korean": "책을 읽어요.",
        "romanized": "Chaekeul ilgeoyo.",
        "en": "I read a book.",
        "vi": "Tôi đọc sách."
      },
      {
        "korean": "음악을 들어요.",
        "romanized": "Eumageul deureoyo.",
        "en": "I listen to music.",
        "vi": "Tôi nghe nhạc."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "뭐 해요?",
        "meaning": "What doing?",
        "text_vi": "Bạn đang làm gì?"
      },
      {
        "speaker": "B",
        "hangul": "책 읽어요.",
        "meaning": "Reading.",
        "text_vi": "Tôi đang đọc sách."
      },
      {
        "speaker": "A",
        "hangul": "무슨 책?",
        "meaning": "What book?",
        "text_vi": "Sách gì vậy?"
      },
      {
        "speaker": "B",
        "hangul": "한국어 책.",
        "meaning": "Korean book.",
        "text_vi": "Sách tiếng Hàn."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'Tôi ăn cơm': 밥을 ___",
        "answer": "먹어요"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "마시다",
            "meaning": "uống"
          },
          {
            "hangul": "자다",
            "meaning": "ngủ"
          }
        ],
        "instruction": "Ghép động từ"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi đi học.",
        "hangul": "학교에 가요."
      }
    ]
  },
  {
    "id": 13,
    "level": "A1",
    "title_vi": "Chia thì hiện tại",
    "title_en": "Present Tense",
    "intro_vi": "Thêm -아요/-어요/-해요 vào gốc động từ. Quy tắc phụ thuộc nguyên âm cuối.",
    "vocabulary": [
      {
        "hangul": "가요",
        "meaning": "đi"
      },
      {
        "hangul": "와요",
        "meaning": "đến"
      },
      {
        "hangul": "먹어요",
        "meaning": "ăn"
      },
      {
        "hangul": "해요",
        "meaning": "làm"
      },
      {
        "hangul": "봐요",
        "meaning": "xem"
      },
      {
        "hangul": "들어요",
        "meaning": "nghe"
      },
      {
        "hangul": "읽어요",
        "meaning": "đọc"
      },
      {
        "hangul": "마셔요",
        "meaning": "uống"
      },
      {
        "hangul": "써요",
        "meaning": "viết"
      },
      {
        "hangul": "자요",
        "meaning": "ngủ"
      }
    ],
    "sentences": [
      {
        "korean": "매일 커피 마셔요.",
        "romanized": "Maeil keopi masyeoyo.",
        "en": "I drink coffee daily.",
        "vi": "Ngày nào cũng uống cà phê."
      },
      {
        "korean": "주말에 친구 만나요.",
        "romanized": "Jumare chingu mannayo.",
        "en": "Meet friends on weekends.",
        "vi": "Cuối tuần gặp bạn."
      },
      {
        "korean": "한국어 공부해요.",
        "romanized": "Hangukeo gongbuhaeyo.",
        "en": "I study Korean.",
        "vi": "Tôi học tiếng Hàn."
      },
      {
        "korean": "TV 봐요.",
        "romanized": "TV bwayo.",
        "en": "I watch TV.",
        "vi": "Tôi xem TV."
      },
      {
        "korean": "일찍 자요.",
        "romanized": "Iljjik jayo.",
        "en": "I sleep early.",
        "vi": "Tôi ngủ sớm."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "취미가 뭐예요?",
        "meaning": "Hobby?",
        "text_vi": "Sở thích của bạn là gì?"
      },
      {
        "speaker": "B",
        "hangul": "한국어 공부해요.",
        "meaning": "Studying Korean.",
        "text_vi": "Tôi học tiếng Hàn."
      },
      {
        "speaker": "A",
        "hangul": "매일 해요?",
        "meaning": "Every day?",
        "text_vi": "Ngày nào cũng học à?"
      },
      {
        "speaker": "B",
        "hangul": "네, 한 시간씩.",
        "meaning": "Yes, 1 hour.",
        "text_vi": "Vâng, mỗi ngày một tiếng."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'Tôi học tiếng Hàn': 한국어 ___",
        "answer": "공부해요"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "가요",
            "meaning": "đi"
          },
          {
            "hangul": "먹어요",
            "meaning": "ăn"
          }
        ],
        "instruction": "Ghép dạng chia"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi xem TV.",
        "hangul": "TV 봐요."
      }
    ]
  },
  {
    "id": 14,
    "level": "A1",
    "title_vi": "Tiểu từ 은/는 và 이/가",
    "title_en": "Topic & Subject Particles",
    "intro_vi": "은/는 = chủ đề câu. 이/가 = chủ ngữ. Sự khác biệt quan trọng trong tiếng Hàn.",
    "vocabulary": [
      {
        "hangul": "은/는",
        "meaning": "tiểu từ chủ đề"
      },
      {
        "hangul": "이/가",
        "meaning": "tiểu từ chủ ngữ"
      },
      {
        "hangul": "저는",
        "meaning": "tôi (chủ đề)"
      },
      {
        "hangul": "제가",
        "meaning": "tôi (chủ ngữ)"
      },
      {
        "hangul": "이것은",
        "meaning": "cái này (CĐ)"
      },
      {
        "hangul": "이것이",
        "meaning": "cái này (CN)"
      },
      {
        "hangul": "날씨가",
        "meaning": "thời tiết (CN)"
      },
      {
        "hangul": "한국어는",
        "meaning": "tiếng Hàn (CĐ)"
      },
      {
        "hangul": "오늘은",
        "meaning": "hôm nay (CĐ)"
      },
      {
        "hangul": "친구가",
        "meaning": "bạn (CN)"
      }
    ],
    "sentences": [
      {
        "korean": "저는 학생이에요.",
        "romanized": "Jeoneun haksaengieyo.",
        "en": "I'm a student.",
        "vi": "Tôi là học sinh."
      },
      {
        "korean": "날씨가 좋아요.",
        "romanized": "Nalssiga joayo.",
        "en": "The weather is good.",
        "vi": "Thời tiết đẹp."
      },
      {
        "korean": "오늘은 금요일이에요.",
        "romanized": "Oneureun geumyoilieyo.",
        "en": "Today is Friday.",
        "vi": "Hôm nay thứ Sáu."
      },
      {
        "korean": "친구가 왔어요.",
        "romanized": "Chinguga wasseoyo.",
        "en": "A friend came.",
        "vi": "Bạn đến."
      },
      {
        "korean": "한국어는 재미있어요.",
        "romanized": "Hangukeoneun jaemiisseoyo.",
        "en": "Korean is fun.",
        "vi": "Tiếng Hàn thú vị."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "오늘 날씨 어때요?",
        "meaning": "Weather today?",
        "text_vi": "Hôm nay thời tiết thế nào?"
      },
      {
        "speaker": "B",
        "hangul": "날씨가 정말 좋아요.",
        "meaning": "Really nice.",
        "text_vi": "Thời tiết đẹp lắm."
      },
      {
        "speaker": "A",
        "hangul": "공원에 갈까요?",
        "meaning": "Park?",
        "text_vi": "Mình đi công viên nhé?"
      },
      {
        "speaker": "B",
        "hangul": "네, 좋아요!",
        "meaning": "Yes!",
        "text_vi": "Vâng, được đấy!"
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "저___ 학생이에요.",
        "answer": "는"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "날씨가 좋아요",
            "meaning": "Đẹp trời"
          },
          {
            "hangul": "한국어는 재미있어요",
            "meaning": "Tiếng Hàn thú vị"
          }
        ],
        "instruction": "Ghép câu"
      },
      {
        "type": "translation",
        "vietnamese": "Hôm nay đẹp trời.",
        "hangul": "오늘은 날씨가 좋아요."
      }
    ]
  },
  {
    "id": 15,
    "level": "A1",
    "title_vi": "Tính từ thông dụng",
    "title_en": "Common Adjectives",
    "intro_vi": "Tính từ chia như động từ. 크다 → 커요 (lớn, hiện tại).",
    "vocabulary": [
      {
        "hangul": "크다",
        "meaning": "to/lớn"
      },
      {
        "hangul": "작다",
        "meaning": "nhỏ"
      },
      {
        "hangul": "좋다",
        "meaning": "tốt/thích"
      },
      {
        "hangul": "나쁘다",
        "meaning": "xấu/tệ"
      },
      {
        "hangul": "맛있다",
        "meaning": "ngon"
      },
      {
        "hangul": "맛없다",
        "meaning": "dở"
      },
      {
        "hangul": "예쁘다",
        "meaning": "đẹp"
      },
      {
        "hangul": "길다",
        "meaning": "dài"
      },
      {
        "hangul": "짧다",
        "meaning": "ngắn"
      },
      {
        "hangul": "빠르다",
        "meaning": "nhanh"
      }
    ],
    "sentences": [
      {
        "korean": "이 집은 커요.",
        "romanized": "I jibeun keoyo.",
        "en": "This house is big.",
        "vi": "Nhà này to."
      },
      {
        "korean": "김치가 맛있어요.",
        "romanized": "Gimchiga masisseoyo.",
        "en": "Kimchi is delicious.",
        "vi": "Kimchi ngon."
      },
      {
        "korean": "그 옷이 예뻐요.",
        "romanized": "Geu osi yeppeoyo.",
        "en": "Those clothes are pretty.",
        "vi": "Áo đó đẹp."
      },
      {
        "korean": "오늘 기분 좋아요.",
        "romanized": "Oneul gibun joayo.",
        "en": "I feel good.",
        "vi": "Tâm trạng tốt."
      },
      {
        "korean": "이 길은 짧아요.",
        "romanized": "I gireun jjalbayo.",
        "en": "This road is short.",
        "vi": "Đường này ngắn."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "hangul": "이 음식 어때요?",
        "meaning": "How's the food?",
        "text_vi": "Món ăn này thế nào?"
      },
      {
        "speaker": "B",
        "hangul": "정말 맛있어요!",
        "meaning": "Delicious!",
        "text_vi": "Ngon thật đấy!"
      },
      {
        "speaker": "A",
        "hangul": "다행이에요. 더 드세요!",
        "meaning": "Glad! Eat more!",
        "text_vi": "May quá. Ăn thêm chút nữa đi!"
      },
      {
        "speaker": "B",
        "hangul": "감사합니다!",
        "meaning": "Thanks!",
        "text_vi": "Cảm ơn ạ!"
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "'Kimchi ngon': 김치가 ___",
        "answer": "맛있어요"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "hangul": "예쁘다",
            "meaning": "đẹp"
          },
          {
            "hangul": "빠르다",
            "meaning": "nhanh"
          }
        ],
        "instruction": "Ghép tính từ"
      },
      {
        "type": "translation",
        "vietnamese": "Nhà đó rất to.",
        "hangul": "그 집은 아주 커요."
      }
    ]
  }
];

export default lessons;
