// src/components/room/BilingualEssay.tsx
// MB-BLUE-99.6b — 2026-01-25 (+0700)
//
// ESSAY ZOOM (GLOBAL):
// - Reads localStorage("mbEssayZoom")
// - Listens to window event "mb:essayZoom"
// - Applies zoom by scaling BASE FONT SIZE (safe layout)
// - Also respects CSS var --mb-essay-zoom if present
//
// HIGHLIGHT SUPPORT (EN/VI):
// - Essay blocks now render inside `.mb-entryText` so roomHighlightsCss.ts can color keywords.
// - If `en/vi` contains HTML spans (e.g. <span data-mb-kw="3">...</span>), we render as HTML.
// - If plain text, we render as text (no risky HTML).

import React, { useEffect, useMemo, useState } from "react";

// ...keep your existing imports

const LS_ZOOM = "mbEssayZoom";
const DEFAULT_ZOOM = 1.0;

function clamp(n: number, a: number, b: number) {
  return Math.max(a, Math.min(b, n));
}

function readCssZoomVar(): number | null {
  try {
    if (typeof window === "undefined") return null;
    const raw = window
      .getComputedStyle(document.documentElement)
      .getPropertyValue("--mb-essay-zoom")
      .trim();
    if (!raw) return null;
    const n = Number(raw);
    return Number.isFinite(n) ? n : null;
  } catch {
    return null;
  }
}

function looksLikeHtml(s: string) {
  // minimal: allow highlight spans and basic markup already generated by your pipeline
  return /<[^>]+>/.test(s);
}

function normalizeNewlinesToHtml(s: string) {
  // preserve paragraphs in stored text
  const safe = String(s || "");
  // If it already contains tags, don't rewrite.
  if (looksLikeHtml(safe)) return safe;
  // Plain text: convert blank lines to <p> blocks
  const blocks = safe
    .split(/\n{2,}/g)
    .map((b) => b.trim())
    .filter(Boolean)
    .map((b) => b.replace(/\n/g, "<br/>"));
  if (blocks.length === 0) return "";
  return blocks.map((b) => `<p>${b}</p>`).join("");
}

export function BilingualEssay(props: any) {
  // ✅ keep ALL your existing logic/props/rendering, only add zoom + wrapper style
  const [zoom, setZoom] = useState(() => {
    const raw = Number(localStorage.getItem(LS_ZOOM));
    return Number.isFinite(raw) ? clamp(raw, 0.6, 1.6) : DEFAULT_ZOOM;
  });

  useEffect(() => {
    const onZoom = (e: Event) => {
      const ce = e as CustomEvent;
      const next = Number(ce?.detail?.zoom);
      if (Number.isFinite(next)) setZoom(clamp(next, 0.6, 1.6));
    };
    window.addEventListener("mb:essayZoom", onZoom as any);
    return () => window.removeEventListener("mb:essayZoom", onZoom as any);
  }, []);

  const cssZoom = useMemo(() => readCssZoomVar(), []);
  const effectiveZoom = useMemo(() => {
    const z = Number.isFinite(cssZoom as any) ? (cssZoom as number) : 1;
    return clamp(zoom * z, 0.6, 1.6);
  }, [zoom, cssZoom]);

  // ✅ base font scales; layout stays normal (no CSS transform scale)
  const baseFontPx = useMemo(() => Math.round(16 * effectiveZoom), [effectiveZoom]);

  const title = String(props?.title || "").trim();
  const en = String(props?.en || "").trim();
  const vi = String(props?.vi || "").trim();

  const enHtml = useMemo(() => normalizeNewlinesToHtml(en), [en]);
  const viHtml = useMemo(() => normalizeNewlinesToHtml(vi), [vi]);

  const shouldRenderEnHtml = useMemo(() => looksLikeHtml(enHtml), [enHtml]);
  const shouldRenderViHtml = useMemo(() => looksLikeHtml(viHtml), [viHtml]);

  return (
    <div
      style={{
        // global zoom effect
        fontSize: baseFontPx,
        lineHeight: 1.7,
      }}
    >
      {/* ⬇️ KEEP your existing BilingualEssay UI exactly as-is */}
      {/* Minimal locked-safe render (supports highlight spans for BOTH EN + VI) */}

      {title ? <div style={{ fontWeight: 900, marginBottom: 10 }}>{title}</div> : null}

      {en ? (
        <div style={{ marginTop: 8 }}>
          <div style={{ fontWeight: 900, fontSize: 12, opacity: 0.75, letterSpacing: 0.4 }}>EN</div>
          <div className="mb-entryText" data-mb-lang="en" style={{ marginTop: 6 }}>
            {shouldRenderEnHtml ? (
              <div dangerouslySetInnerHTML={{ __html: enHtml }} />
            ) : (
              <div>{en}</div>
            )}
          </div>
        </div>
      ) : null}

      {vi ? (
        <div style={{ marginTop: 14 }}>
          <div style={{ fontWeight: 900, fontSize: 12, opacity: 0.75, letterSpacing: 0.4 }}>VI</div>
          <div className="mb-entryText" data-mb-lang="vi" style={{ marginTop: 6 }}>
            {shouldRenderViHtml ? (
              <div dangerouslySetInnerHTML={{ __html: viHtml }} />
            ) : (
              <div>{vi}</div>
            )}
          </div>
        </div>
      ) : null}
    </div>
  );
}

// If your file uses `export default`, keep it consistent with your existing export style.
export default BilingualEssay;
