// Auto-generated by scripts/split-lessons-by-level.mjs.
// Edit the source lesson content here directly. DO NOT regenerate
// from a stale lessons.ts — the registry replaced that file.

import type { JapaneseLesson } from "./lessons";

export const lessons: JapaneseLesson[] = [
  {
    "id": 31,
    "title": "Business Meetings",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "会議",
        "english": "meeting"
      },
      {
        "japanese": "議題",
        "english": "agenda"
      },
      {
        "japanese": "進行",
        "english": "facilitation"
      },
      {
        "japanese": "発言",
        "english": "speaking / remark"
      },
      {
        "japanese": "賛成",
        "english": "agree"
      },
      {
        "japanese": "反対",
        "english": "oppose"
      },
      {
        "japanese": "意見",
        "english": "opinion"
      },
      {
        "japanese": "決める",
        "english": "to decide"
      },
      {
        "japanese": "確認する",
        "english": "to confirm"
      },
      {
        "japanese": "資料",
        "english": "documents"
      }
    ],
    "grammar": [
      {
        "point": "～たほうがいい",
        "explanation": "It's better to ~ (suggestion)"
      },
      {
        "point": "～べきだ",
        "explanation": "Should / ought to (obligation)"
      }
    ],
    "examples": [
      {
        "japanese": "議題について意見があります。",
        "english": "I have an opinion about the agenda.",
        "pronunciation_focus_en": [
          "議題 (ぎだい) → 'gi-da-i'; hard g, three even mora",
          "について → 'ni-tsu-i-te' = 'regarding'; つ is 'tsu', tongue behind teeth (carried from A2)",
          "意見 (いけん) → 'i-ken'; ん is its own beat (moraic n)",
          "があります → 'ga a-ri-mas'; が subject particle (hard g), あります for inanimate existence"
        ]
      },
      {
        "japanese": "私はその提案に賛成です。",
        "english": "I agree with that proposal.",
        "pronunciation_focus_en": [
          "私は → 'wa-ta-shi wa'; は = topic particle 'wa', never 'ha'",
          "提案 (ていあん) → 'te-i-an'; ん its own beat",
          "に → marks what you agree WITH (賛成 takes に, not を — a fixed pairing)",
          "賛成です → 'san-se-e des'; せい a long 'eh', です devoiced"
        ]
      },
      {
        "japanese": "もう一度確認したほうがいいと思います。",
        "english": "I think we should check once more.",
        "pronunciation_focus_en": [
          "もう一度 → 'mo-o i-chi-do'; もう a long 'oh' ('once more')",
          "確認した → 'ka-ku-nin-shi-ta'; plain past inside 〜たほうがいい (the past form is required here)",
          "ほうがいい → 'ho-o ga i-i'; ほう a long 'oh'; 〜たほうがいい = 'had better / should'",
          "と思います → 'to o-mo-i-mas'; と quotes the thought, softening the assertion"
        ]
      },
      {
        "japanese": "会議は三時からです。",
        "english": "The meeting is from 3 o'clock.",
        "pronunciation_focus_en": [
          "会議 (かいぎ) → 'ka-i-gi'; hard g",
          "は → topic particle, 'wa'",
          "三時 → 'san-ji'; the hour counter 時 = じ (carried from A1)",
          "からです → 'ka-ra des'; から here = the starting-point 'from' (a second job of から — see the tip)"
        ]
      },
      {
        "japanese": "次の議題に移りましょう。",
        "english": "Let's move on to the next agenda item.",
        "pronunciation_focus_en": [
          "次の → 'tsu-gi no'; つ is 'tsu'; の links to the noun",
          "議題に → 'gi-da-i ni'; に marks the destination of 移る ('move to')",
          "移りましょう → 'u-tsu-ri-ma-sho-o'; 〜ましょう = polite 'let's'; しょう a long 'oh'",
          "even, unstressed delivery throughout — no English-style stress peak"
        ]
      }
    ],
    "cultural_notes_en": "A Japanese business meeting (会議) is often a ratification ceremony, not a decision arena — the opposite of the American 'we'll hash it out in the room' expectation. Real decisions are typically pre-built through 根回し (nemawashi, informal groundwork: lobbying each stakeholder beforehand) and circulated via 稟議 (ringi, a written proposal stamped up the hierarchy), so by meeting time consensus already exists and open disagreement is rare. This is why disagreement is voiced obliquely — 'I think this plan is a bit unrealistic' (少し無理がある) rather than 'I disagree.' Underpinning daily work is 報連相 (hō-ren-sō: 報告 report / 連絡 inform / 相談 consult) — a junior is expected to keep superiors continuously updated, far more than a typical American 'I'll flag it if there's a problem' norm. Seating and speaking order track seniority (上座/下座, the seat farthest from the door is the honored one). For the learner the practical takeaway: at B1 you're not expected to run the meeting, but you must recognize that 賛成です/反対です are stated softly, decisions are pre-cooked, and the hedged 〜と思います is doing real social work, not just grammar.",
    "tip_advice_en": "Highest-leverage B1 pattern here: 〜たほうがいい for advice/recommendation — and note the trap, it takes the PLAIN PAST even for present advice: 確認した + ほうがいい = 'had better check' (NOT 確認するほうがいい for this 'should' sense). The 〜た is mandatory; getting it as 〜るほうがいい weakens the meaning. Pair it with 〜と思います, which at B1 genuinely softens a claim (Japanese meeting register expects the hedge — dropping it to 'just state it' reads as blunt, the inverse of American directness). Particle nuance to lock: から has two jobs — starting point 'from' (三時から, from 3:00) and 'because'; same particle, context decides, exactly like the A2 から (source/reason) note. Pronunciation watch-points: every polite ending devoices its final vowel (あります 'a-ri-mas', 思います 'o-mo-i-mas'); long 'oh' in もう/ほう/ましょう must be held two beats. Drill: give one recommendation as '[plain past]ほうがいいと思います.'",
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "今日の議題は来月のプロジェクトについてです。",
        "english": "Today's agenda is about next month's project."
      },
      {
        "speaker": "B",
        "japanese": "はい、まずスケジュールを確認しましょう。",
        "english": "Yes, let's first confirm the schedule."
      },
      {
        "speaker": "A",
        "japanese": "それでは、資料の二ページをご覧ください。",
        "english": "Then, please look at page 2 of the handout."
      },
      {
        "speaker": "B",
        "japanese": "この計画は少し無理があると思います。",
        "english": "I think this plan is a bit unrealistic."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "私はその提案に___です。",
        "answer": "賛成"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "議題",
            "english": "agenda"
          },
          {
            "japanese": "資料",
            "english": "handout"
          }
        ],
        "instruction": "Match the Japanese meeting vocabulary"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi nghĩ chúng ta nên thảo luận vấn đề này trước.",
        "japanese": "この問題を先に議論したほうがいいと思います。"
      }
    ]
  },
  {
    "id": 32,
    "title": "Giving Presentations",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "プレゼンテーション",
        "english": "presentation"
      },
      {
        "japanese": "スライド",
        "english": "slide"
      },
      {
        "japanese": "グラフ",
        "english": "graph"
      },
      {
        "japanese": "データ",
        "english": "data"
      },
      {
        "japanese": "説明する",
        "english": "to explain"
      },
      {
        "japanese": "質問",
        "english": "question"
      },
      {
        "japanese": "要約する",
        "english": "to summarize"
      },
      {
        "japanese": "導入",
        "english": "introduction"
      },
      {
        "japanese": "結論",
        "english": "conclusion"
      },
      {
        "japanese": "強調する",
        "english": "to emphasize"
      }
    ],
    "grammar": [
      {
        "point": "～について",
        "explanation": "Regarding / about ~"
      },
      {
        "point": "～のです（説明）",
        "explanation": "Used for explanation / emphasis."
      }
    ],
    "examples": [
      {
        "japanese": "本日は市場動向について発表します。",
        "english": "Today I will present about market trends.",
        "pronunciation_focus_en": [
          "本日 (ほんじつ) → 'hon-ji-tsu'; the formal word for 今日 ('today') — note the kanji is read じつ here",
          "は → topic particle, 'wa'",
          "市場動向 → 'shi-jo-o-do-o-ko-o'; THREE long 'oh' (じょう/どう/こう) — hold each two beats",
          "発表します → 'ha(p)-pyo-o-shi-mas'; small っ a held beat, ぴょう glided + long 'oh'"
        ]
      },
      {
        "japanese": "次のスライドをご覧ください。",
        "english": "Please look at the next slide.",
        "pronunciation_focus_en": [
          "次の → 'tsu-gi no'; つ is 'tsu'",
          "スライド → 'su-ra-i-do'; katakana, four even mora, tapped r",
          "を → object particle, pronounced 'o'",
          "ご覧ください → 'go-ran ku-da-sa-i'; ご覧 = RESPECTFUL 'look' (尊敬語 of 見る) — said TO the audience"
        ]
      },
      {
        "japanese": "このグラフは売上の推移を示しています。",
        "english": "This graph shows the sales trend.",
        "pronunciation_focus_en": [
          "グラフ → 'gu-ra-fu'; ふ is soft bilabial (lips near, not touching teeth)",
          "売上 (うりあげ) → 'u-ri-a-ge'; の links it to 推移",
          "推移 (すいい) → 'su-i-i'; two distinct い mora — don't merge into one long 'ee'",
          "示しています → 'shi-me-shi-te i-mas'; 〜ている = a continuing STATE/result ('shows / is showing')"
        ]
      },
      {
        "japanese": "質問がありますか。",
        "english": "Are there any questions?",
        "pronunciation_focus_en": [
          "質問 (しつもん) → 'shi-tsu-mon'; つ is 'tsu', ん its own beat",
          "が → subject particle, hard g",
          "ありますか → 'a-ri-mas-ka'; あります (inanimate existence) + か question",
          "pitch rises only on the final か"
        ]
      },
      {
        "japanese": "結論として、この戦略は有効です。",
        "english": "In conclusion, this strategy is effective.",
        "pronunciation_focus_en": [
          "結論 (けつろん) → 'ke-tsu-ron'; つ is 'tsu', ん its own beat",
          "として → 'to-shi-te' = 'as / by way of' (set connector, 'in conclusion')",
          "戦略は → 'sen-rya-ku wa'; りゃ one glided mora; は = 'wa'",
          "有効です → 'yu-u-ko-o des'; ゆう and こう both long 'oh', です devoiced"
        ]
      }
    ],
    "cultural_notes_en": "Japanese presentations run on a higher, more fixed register than American ones, and this lesson is where 尊敬語 (respectful language) first appears as something to recognize rather than improvise. ご覧ください ('please look,' respectful 見る) is directed AT the audience to elevate them; the speaker simultaneously lowers themselves with humble verbs (ご説明します, 発表します). 本日 replaces casual 今日, 弊社 ('our humble company') replaces うち — the whole vocabulary shifts up a notch in a formal setting, much as an American might move from 'so, today I'll show you…' to 'I'd like to walk you through…', but Japanese grammaticalizes it. Structurally, presentations are expected to be modest in delivery (over-confident American-style salesmanship can read as untrustworthy), data-led, and tightly framed with 導入→本論→結論 signposting. The 〜ている in 示しています is doing a specific job: it marks a graph's displayed state ('the graph shows / is showing'), not an action in progress — a B1 nuance English's '-ing' blurs. At B1 you should recognize ご覧ください and the humble/respectful split, not yet produce full keigo.",
    "tip_advice_en": "Highest-leverage recognition target: 尊敬語 vs 謙譲語 as a pair. ご覧ください raises the listener (respectful 見る); ご説明します / 発表します lower the speaker (humble) — same uchi/soto axis as the A1 family terms and A2 keigo, now in presentation set-phrases. At B1 you RECOGNIZE these in fixed expressions; free keigo production is a later level — don't fabricate honorific verbs you haven't been taught (the #491 restraint rule). Second, lock the 〜ている = resultant-state reading: グラフは…を示しています is 'the graph shows' (a standing state), not 'is in the act of showing' — mapping it to English progressive misfires, exactly the A2 ています point levelled up. Pronunciation watch-points: 市場動向 stacks three long 'oh' vowels; 推移 is two separate い beats ('su-i-i'), commonly crushed to 'sui'. Drill the audience-facing line aloud: 次の[noun]をご覧ください, holding each long vowel.",
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "本日はお忙しい中お集まりいただきありがとうございます。",
        "english": "Thank you for taking time to gather today."
      },
      {
        "speaker": "B",
        "japanese": "最初に自己紹介をお願いします。",
        "english": "Please start with a self-introduction."
      },
      {
        "speaker": "A",
        "japanese": "はい、私は営業部の田中と申します。本日は新製品についてご説明します。",
        "english": "Yes, I'm Tanaka from Sales. Today I'll explain about the new product."
      },
      {
        "speaker": "B",
        "japanese": "それでは、お願いします。",
        "english": "Then, please go ahead."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "次の___をご覧ください。",
        "answer": "スライド"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "グラフ",
            "english": "graph"
          },
          {
            "japanese": "データ",
            "english": "data"
          }
        ],
        "instruction": "Match the Japanese presentation terms"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi sẽ giải thích về chiến lược tiếp thị mới.",
        "japanese": "新しいマーケティング戦略について説明します。"
      }
    ]
  },
  {
    "id": 33,
    "title": "Negotiating",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "交渉",
        "english": "negotiation"
      },
      {
        "japanese": "条件",
        "english": "condition"
      },
      {
        "japanese": "妥協",
        "english": "compromise"
      },
      {
        "japanese": "譲歩",
        "english": "concession"
      },
      {
        "japanese": "提案",
        "english": "proposal"
      },
      {
        "japanese": "合意",
        "english": "agreement"
      },
      {
        "japanese": "値引き",
        "english": "discount"
      },
      {
        "japanese": "期限",
        "english": "deadline"
      },
      {
        "japanese": "見積もり",
        "english": "quotation"
      },
      {
        "japanese": "契約",
        "english": "contract"
      }
    ],
    "grammar": [
      {
        "point": "～なければならない",
        "explanation": "must / have to"
      },
      {
        "point": "～てほしい",
        "explanation": "I want you to ~"
      }
    ],
    "examples": [
      {
        "japanese": "もう少し値引きしていただけませんか。",
        "english": "Could you give us a little more discount?",
        "pronunciation_focus_en": [
          "もう少し → 'mo-o su-ko-shi'; もう a long 'oh' ('a little more')",
          "値引き (ねびき) → 'ne-bi-ki', three even mora ('discount')",
          "していただけませんか → 'shi-te i-ta-da-ke-ma-sen-ka'; いただく = HUMBLE もらう (receive a favor)",
          "the negative-question form 〜ていただけませんか is the MOST polite request — 'might I receive your doing ~?'"
        ]
      },
      {
        "japanese": "この条件では合意できません。",
        "english": "We cannot agree on these conditions.",
        "pronunciation_focus_en": [
          "条件 (じょうけん) → 'jo-o-ken'; じょう a long 'joh', ん its own beat",
          "では → 'de-wa'; で (under these conditions) + は = 'under ~, [as for that]'",
          "合意 (ごうい) → 'go-o-i'; ごう a long 'oh'",
          "できません → 'de-ki-ma-sen'; potential negative of する ('cannot do/agree')"
        ]
      },
      {
        "japanese": "お互いに譲歩する必要があります。",
        "english": "We need to make mutual concessions.",
        "pronunciation_focus_en": [
          "お互いに → 'o-ta-ga-i ni'; に makes it adverbial ('mutually')",
          "譲歩する → 'jo-o-ho su-ru'; じょう a long 'joh' ('to concede')",
          "必要 (ひつよう) → 'hi-tsu-yo-o'; つ is 'tsu', よう a long 'oh' — a na-adjective",
          "があります → 〜する必要がある = 'there is a need to ~'; が, not を, marks 必要"
        ]
      },
      {
        "japanese": "この提案はいかがですか。",
        "english": "How about this proposal?",
        "pronunciation_focus_en": [
          "提案 (ていあん) → 'te-i-an'; ん its own beat",
          "は → topic particle, 'wa'",
          "いかが → 'i-ka-ga'; the polite form of どう ('how about')",
          "ですか → 'des-ka'; pitch rises only on か"
        ]
      },
      {
        "japanese": "契約の期限は来週です。",
        "english": "The contract deadline is next week.",
        "pronunciation_focus_en": [
          "契約 (けいやく) → 'ke-e-ya-ku'; けい a long 'eh'",
          "の → possessive ('the contract's deadline')",
          "期限は → 'ki-gen wa'; ん its own beat; は = 'wa'",
          "来週です → 'ra-i-shu-u des'; しゅう held two beats — a relative-time word, no particle"
        ]
      }
    ],
    "cultural_notes_en": "Japanese business negotiation prizes relationship and face over the American 'win the point' frame. Demands are wrapped in humble-receiving requests (〜ていただけませんか, 'might I receive your doing ~?') rather than imperatives, and a flat 'no' is almost never said: 検討します ('we'll consider it'), 難しいですね ('that's difficult'), 前向きに ('we'll look at it positively'), or a long inhaled すぅ are all, in practice, refusals — the A1/A2 'no that isn't said,' now at stakes. Pushing for an explicit yes/no, normal in US deal-making, is read as aggressive and can cost the relationship. Concessions are framed as mutual (お互いに譲歩) to preserve both sides' face, and silence is a tactic, not a gap to fill — Americans tend to talk into silence and concede; Japanese counterparts may use it deliberately. The practical B1 takeaway: hear 検討します as a likely soft no, keep requests in the 〜ていただけませんか register, and don't mistake politeness for agreement.",
    "tip_advice_en": "Highest-leverage receiving-side grammar: 〜ていただけませんか — the humble verb いただく (receive a favor) in a negative question = the single most polite way to request anything ('could I possibly have you ~?'). Ladder to lock: 〜てくれませんか (polite) < 〜ていただけませんか (humble, safest in negotiation/business), extending the A2 もらう/いただく point. Honest scope note (continuing the #491 flag): this is still only the RECEIVING half. The full giving/receiving trio — あげる (I give outward), くれる (someone gives toward me/my in-group), もらう (I receive) and their in-group directionality — is NOT taught with example coverage anywhere in B1 either; it appears only incidentally in dialogue/exercises. Master 〜ていただく here; the directional trio remains a flagged B2 target, not something to back-fill. Particle watch-point: 必要 takes が (〜する必要がある), not を. Pronunciation: いただけませんか is seven even mora — don't compress it; じょう/ごう long vowels held two beats. Drill: restate one demand as 〜ていただけませんか.",
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "この価格では厳しいです。もう少し安くできませんか。",
        "english": "This price is difficult. Can you make it a bit cheaper?"
      },
      {
        "speaker": "B",
        "japanese": "そうですね…では、一割引きなら可能です。",
        "english": "Let's see... Well, I can offer a 10% discount."
      },
      {
        "speaker": "A",
        "japanese": "一割引きではまだ厳しいです。二割はいかがですか。",
        "english": "10% is still tough. How about 20%?"
      },
      {
        "speaker": "B",
        "japanese": "二割は難しいです。一割五分でどうでしょうか。",
        "english": "20% is difficult. How about 15%?"
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "この___では合意できません。",
        "answer": "条件"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "妥協",
            "english": "compromise"
          },
          {
            "japanese": "譲歩",
            "english": "concession"
          }
        ],
        "instruction": "Match the Japanese negotiation terms"
      },
      {
        "type": "translation",
        "vietnamese": "Chúng tôi muốn yêu cầu giảm giá thêm.",
        "japanese": "さらなる値引きをお願いしたいです。"
      }
    ]
  },
  {
    "id": 34,
    "title": "Social Media",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "SNS",
        "english": "social media"
      },
      {
        "japanese": "投稿する",
        "english": "to post"
      },
      {
        "japanese": "フォローする",
        "english": "to follow"
      },
      {
        "japanese": "いいね",
        "english": "like"
      },
      {
        "japanese": "シェア",
        "english": "share"
      },
      {
        "japanese": "コメント",
        "english": "comment"
      },
      {
        "japanese": "プロフィール",
        "english": "profile"
      },
      {
        "japanese": "ハッシュタグ",
        "english": "hashtag"
      },
      {
        "japanese": "拡散",
        "english": "spread / viral"
      },
      {
        "japanese": "プライバシー",
        "english": "privacy"
      }
    ],
    "grammar": [
      {
        "point": "～たらどう？",
        "explanation": "How about if ~? (casual suggestion)"
      },
      {
        "point": "～みたいな",
        "explanation": "Like / similar to (casual)"
      }
    ],
    "examples": [
      {
        "japanese": "今日の写真をインスタに投稿しました。",
        "english": "I posted today's photo on Instagram.",
        "pronunciation_focus_en": [
          "今日の → 'kyo-o no'; 今日 irregular reading, long 'oh' (carried from A1)",
          "写真 (しゃしん) → 'sha-shin'; しゃ one glided mora, ん its own beat",
          "インスタ → 'in-su-ta'; clipped katakana for インスタグラム (Japanese loves clipping loanwords)",
          "に → marks the platform posted TO; 投稿しました 'to-o-ko-o-shi-ma-shi-ta', two long 'oh'"
        ]
      },
      {
        "japanese": "その投稿にいいねを押しました。",
        "english": "I liked that post.",
        "pronunciation_focus_en": [
          "投稿 (とうこう) → 'to-o-ko-o'; both long 'oh'",
          "に → marks what the 'like' is attached to",
          "いいね → 'i-i-ne'; held long 'ee' then ね — the noun 'a Like' (literally 'good, isn't it')",
          "押しました → 'o-shi-ma-shi-ta'; 'pressed' (you 'press' a Like in Japanese, not 'give' one)"
        ]
      },
      {
        "japanese": "ハッシュタグをつけると見つけやすいです。",
        "english": "Adding hashtags makes it easier to find.",
        "pronunciation_focus_en": [
          "ハッシュタグ → 'ha(s)-shu-ta-gu'; small っ a held beat (katakana loanword)",
          "つけると → 'tsu-ke-ru to'; 〜と = the natural-consequence conditional ('if/when you add, then…')",
          "見つけやすい → 'mi-tsu-ke-ya-su-i'; 〜やすい = 'easy to ~' (verb-stem + やすい, an i-adjective)",
          "です → 'des', devoiced — the i-adjective + です politeness"
        ]
      },
      {
        "japanese": "SNSで拡散されたニュースを見ました。",
        "english": "I saw news that went viral on social media.",
        "pronunciation_focus_en": [
          "SNS → 'e-su-e-nu-e-su'; spelled out letter by letter; Japanese says SNS, NOT 'social media'",
          "で → the location/means particle ('on social media')",
          "拡散された → 'ka-ku-san-sa-re-ta'; PASSIVE 〜された ('was spread') modifying ニュース directly — a relative clause (Lesson 45 preview)",
          "を見ました → 'o mi-ma-shi-ta'; を object particle 'o'"
        ]
      },
      {
        "japanese": "プライバシー設定を確認したほうがいいよ。",
        "english": "You should check your privacy settings.",
        "pronunciation_focus_en": [
          "プライバシー → 'pu-ra-i-ba-shi-i'; シー a long 'ee' (two beats)",
          "設定 (せってい) → 'se(t)-te-e'; small っ held, てい a long 'eh'",
          "確認したほうがいい → plain past 確認した + ほうがいい ('had better', from Lesson 31)",
          "よ → casual assertive sentence-final particle ('I'm telling you') — CASUAL register, not for a boss"
        ]
      }
    ],
    "cultural_notes_en": "First, a vocabulary reality: Japanese says SNS (エスエヌエス), not 'social media' — using the English term marks you as not localized; and loanwords get clipped hard (インスタ for Instagram, スマホ for smartphone, ツイ for tweet). Platform culture diverges sharply from the US: Japan is unusually anonymous-leaning — X/Twitter is huge and largely pseudonymous (本名 real-name posting like US Facebook is comparatively rare), and LINE, not iMessage/WhatsApp, is the default messaging fabric. The dominant social risk word is 炎上 (enjō, 'going up in flames') — a coordinated pile-on for a perceived misstep, more feared and faster-moving than the US 'getting ratioed,' which is why プライバシー設定 advice and self-censorship norms run strong. This lesson is also the register pivot: SNS speech is where plain/casual form lives. 確認したほうがいいよ ends in casual よ — fine peer-to-peer, wrong to a superior. American social media flattens register; Japanese keeps the polite/plain split online, and choosing casual with the wrong person online is as marked as offline.",
    "tip_advice_en": "Highest-leverage B1 shift introduced here: plain/casual register. Up to A2 you lived in です/ます; SNS, friends, and the dialogues from here on use plain form — plain verbs (見る, 行く), plain past (見た), and casual sentence-final particles よ ('I'm telling you'), ね ('right?'), and rising な/の. 確認したほうがいいよ is peer register; the same advice to a boss needs 〜ほうがいいですよ or softer. Don't treat plain form as 'broken polite' — it's a full register with its own social rules; the error is using casual よ/だ with someone who outranks you. Two grammar carries: 〜と (consequence conditional, つけると…) and 〜やすい ('easy to,' verb-stem + やすい → i-adjective). Also spot 拡散された — a passive (Lesson 44) embedded as a noun-modifier (Lesson 45), both previewed here in the wild. Pronunciation: clipped loans keep katakana length marks (プライバシー = シー held); the small っ in ハッシュタグ/設定 is a held beat. Drill: say one tip twice — casual 〜ほうがいいよ, then polite 〜ほうがいいですよ.",
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "今朝、面白いツイートを見たよ。",
        "english": "I saw an interesting tweet this morning."
      },
      {
        "speaker": "B",
        "japanese": "どんな内容？シェアしてくれる？",
        "english": "What was it about? Can you share it?"
      },
      {
        "speaker": "A",
        "japanese": "いいよ。このリンクを送るね。",
        "english": "Sure. I'll send you the link."
      },
      {
        "speaker": "B",
        "japanese": "ありがとう。後で見てみる。",
        "english": "Thanks. I'll check it out later."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "その投稿に___を押しました。",
        "answer": "いいね"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "フォロー",
            "english": "follow"
          },
          {
            "japanese": "拡散",
            "english": "viral"
          }
        ],
        "instruction": "Match the Japanese social media terms"
      },
      {
        "type": "translation",
        "vietnamese": "Bạn có thể gửi cho tôi đường dẫn đến bài viết đó không?",
        "japanese": "その投稿のリンクを送っていただけますか。"
      }
    ]
  },
  {
    "id": 35,
    "title": "Environmental Issues",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "環境",
        "english": "environment"
      },
      {
        "japanese": "問題",
        "english": "issue"
      },
      {
        "japanese": "温暖化",
        "english": "global warming"
      },
      {
        "japanese": "リサイクル",
        "english": "recycling"
      },
      {
        "japanese": "省エネ",
        "english": "energy saving"
      },
      {
        "japanese": "ごみ",
        "english": "garbage"
      },
      {
        "japanese": "汚染",
        "english": "pollution"
      },
      {
        "japanese": "再生可能エネルギー",
        "english": "renewable energy"
      },
      {
        "japanese": "自然",
        "english": "nature"
      },
      {
        "japanese": "保護する",
        "english": "to protect"
      }
    ],
    "grammar": [
      {
        "point": "～なければならない",
        "explanation": "must / have to (obligation)"
      },
      {
        "point": "～べきだ",
        "explanation": "should (moral obligation)"
      }
    ],
    "examples": [
      {
        "japanese": "環境問題について話し合いましょう。",
        "english": "Let's discuss environmental issues.",
        "pronunciation_focus_en": [
          "環境 (かんきょう) → 'kan-kyo-o'; ん its own beat, きょう a long 'oh'",
          "問題 (もんだい) → 'mon-da-i'; ん a beat",
          "について → 'ni-tsu-i-te' = 'about/regarding'",
          "話し合いましょう → 'ha-na-shi-a-i-ma-sho-o'; 〜ましょう polite 'let's', しょう long 'oh'"
        ]
      },
      {
        "japanese": "温暖化を防ぐために何ができますか。",
        "english": "What can we do to prevent global warming?",
        "pronunciation_focus_en": [
          "温暖化 (おんだんか) → 'on-dan-ka'; two ん, each a beat",
          "を防ぐ → 'o fu-se-gu'; ふ soft bilabial; を object particle 'o'",
          "ために → 'ta-me ni' = 'in order to' (purpose); attaches to the plain verb 防ぐ",
          "できますか → 'de-ki-mas-ka'; potential of する ('can do'), pitch up on か"
        ]
      },
      {
        "japanese": "リサイクルをもっと積極的にするべきです。",
        "english": "We should recycle more actively.",
        "pronunciation_focus_en": [
          "リサイクル → 'ri-sa-i-ku-ru'; katakana, tapped r at both ends",
          "もっと → 'mo(t)-to'; small っ a held silent beat ('more')",
          "積極的に → 'se(k)-kyo-ku-te-ki ni'; small っ held; に makes the na-adjective adverbial",
          "するべきです → 'su-ru be-ki des'; 〜べきだ = moral 'should/ought' (stronger than ほうがいい)"
        ]
      },
      {
        "japanese": "省エネ製品を使うことは重要です。",
        "english": "Using energy-saving products is important.",
        "pronunciation_focus_en": [
          "省エネ → 'sho-o-e-ne'; しょう a long 'oh' + clipped エネ(ルギー) — a hybrid kanji+katakana clip",
          "製品を → 'se-i-hin o'; を object particle 'o'",
          "使うこと → 'tsu-ka-u ko-to'; こと nominalizes the verb phrase ('the act of using')",
          "は重要です → 'wa ju-u-yo-o des'; は = 'wa', じゅう/よう long 'oh' — 重要 a na-adjective"
        ]
      },
      {
        "japanese": "自然を保護しなければなりません。",
        "english": "We must protect nature.",
        "pronunciation_focus_en": [
          "自然 (しぜん) → 'shi-zen'; ぜ voiced, ん a beat",
          "を保護 → 'o ho-go'; を object particle 'o'",
          "しなければ → 'shi-na-ke-re-ba'; the 〜なければ stem of the obligation form",
          "なりません → 'na-ri-ma-sen'; 〜なければなりません = 'must' (lit. 'if not ~, it won't do')"
        ]
      }
    ],
    "cultural_notes_en": "Environmental behavior in Japan is socially enforced at a granularity that genuinely has no American parallel: household ごみ is sorted into many streams (燃える/燃えない/資源/プラ/ペットボトル/粗大), put out on assigned days in designated bags at a shared neighborhood point, and getting it wrong is visible and quietly shaming — neighbors and the 自治会 (residents' association) notice. This is not 'recycling is nice' (the casual US framing) but a daily compliance ritual. Underneath sits もったいない (mottainai) — a culturally deep 'what a waste / don't be wasteful' value with no one-word English equivalent, invoked for food, resources, and objects alike. The grammar here carries the moral weight: 〜べきだ ('should,' duty/ethics) and 〜なければなりません ('must,' no choice) are stronger and more obligation-laden than the A2 〜たほうがいい advice, and Japanese discourse on the environment leans on them precisely because the topic is framed as collective duty (みんなで取り組む), not individual preference. For the learner: don't soften these to 'maybe we should' — they carry real obligation, and the gomi system is a rule to learn, not a guideline.",
    "tip_advice_en": "Highest-leverage obligation ladder to lock at B1: 〜たほうがいい (advice, A2) < 〜べきだ (moral should/ought) < 〜なければならない / 〜なければなりません (must, no choice). 〜べきだ carries an ethical 'ought' — using it for trivial advice over-weights the sentence; reserve it for duty. 〜なければなりません is literally 'if you don't ~, it won't do' — a double negative meaning 'must'; English speakers stall on its length, so drill the chunk 〜なければなりません as one unit. Note こと as a nominalizer (使うことは…, A2 point levelled up) turning a verb phrase into a subject. Pronunciation watch-points: small っ as a held silent beat recurs (もっと, 積極的, carried mora rule); long 'oh' in きょう/しょう/じゅう held two beats; ふ in 防ぐ is a soft bilabial, not an English 'f.' Drill one environmental claim at each obligation rung: 〜たほうがいい / 〜べきだ / 〜なければなりません.",
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "最近、環境問題に関心がありますか。",
        "english": "Are you interested in environmental issues lately?"
      },
      {
        "speaker": "B",
        "japanese": "はい、特にプラスチックごみの問題について勉強しています。",
        "english": "Yes, I'm studying the plastic waste problem."
      },
      {
        "speaker": "A",
        "japanese": "私もエコバッグを使うようにしています。",
        "english": "I also try to use eco-bags."
      },
      {
        "speaker": "B",
        "japanese": "それはいいですね。みんなで取り組むべきです。",
        "english": "That's great. We should all work on it."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "___を防ぐために何ができますか。",
        "answer": "温暖化"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "リサイクル",
            "english": "recycling"
          },
          {
            "japanese": "省エネ",
            "english": "energy saving"
          }
        ],
        "instruction": "Match the Japanese environment terms"
      },
      {
        "type": "translation",
        "vietnamese": "Chúng ta cần bảo vệ môi trường cho thế hệ tương lai.",
        "japanese": "将来の世代のために環境を保護しなければなりません。"
      }
    ]
  },
  {
    "id": 36,
    "title": "Expressing Opinions",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "意見",
        "english": "opinion"
      },
      {
        "japanese": "主張する",
        "english": "to assert"
      },
      {
        "japanese": "反論する",
        "english": "to counterargue"
      },
      {
        "japanese": "賛成",
        "english": "agreement"
      },
      {
        "japanese": "反対",
        "english": "opposition"
      },
      {
        "japanese": "根拠",
        "english": "evidence"
      },
      {
        "japanese": "観点",
        "english": "perspective"
      },
      {
        "japanese": "論点",
        "english": "point of discussion"
      },
      {
        "japanese": "明確にする",
        "english": "to clarify"
      },
      {
        "japanese": "納得する",
        "english": "to be convinced"
      }
    ],
    "grammar": [
      {
        "point": "～という観点から",
        "explanation": "From the perspective of ~"
      },
      {
        "point": "～とは言えない",
        "explanation": "Cannot say that ~ (negating a claim)"
      }
    ],
    "examples": [
      {
        "japanese": "私の意見を述べさせていただきます。",
        "english": "Allow me to state my opinion.",
        "pronunciation_focus_en": [
          "意見 (いけん) → 'i-ken'; ん its own beat",
          "を述べ → 'o no-be'; を object particle 'o'",
          "させていただきます → 'sa-se-te i-ta-da-ki-mas'; CAUSATIVE 〜させて + humble いただく = 'allow me to ~' (I humbly receive permission to do it)",
          "the most deferential way to introduce your own action — set business/formal phrase"
        ]
      },
      {
        "japanese": "その主張には根拠があるとは言えません。",
        "english": "One cannot say that the claim has solid grounds.",
        "pronunciation_focus_en": [
          "主張 (しゅちょう) → 'shu-cho-o'; しゅ and ちょう, ちょう a long 'oh'",
          "には → 'ni wa'; に + は = 'as for [in] that claim'",
          "根拠 (こんきょ) → 'kon-kyo'; ん a beat, きょ one glided mora",
          "とは言えません → 'to wa i-e-ma-sen'; 〜とは言えない = 'cannot (go so far as to) say that ~' — soft denial"
        ]
      },
      {
        "japanese": "経済の観点から見ると、この政策は有効です。",
        "english": "From an economic perspective, this policy is effective.",
        "pronunciation_focus_en": [
          "経済の → 'ke-e-za-i no'; けい long 'eh', ざ voiced",
          "観点 (かんてん) → 'kan-ten'; ん a beat",
          "から見ると → 'ka-ra mi-ru to'; 〜から見ると = 'seen from ~ / from the ~ standpoint' (と = consequence conditional)",
          "政策は → 'se-i-sa-ku wa'; は = 'wa'; 有効 'yu-u-ko-o' two long 'oh'"
        ]
      },
      {
        "japanese": "私はその意見に反対です。",
        "english": "I oppose that opinion.",
        "pronunciation_focus_en": [
          "私は → 'wa-ta-shi wa'; は = 'wa'",
          "意見に → 'i-ken ni'; に marks what you oppose (反対 takes に, like 賛成)",
          "反対 (はんたい) → 'han-ta-i'; ん a beat",
          "です → 'des', devoiced final vowel"
        ]
      },
      {
        "japanese": "もう一度説明していただければ納得します。",
        "english": "If you explain again, I'll be convinced.",
        "pronunciation_focus_en": [
          "もう一度 → 'mo-o i-chi-do'; もう long 'oh'",
          "説明して → 'se-tsu-me-i-shi-te'; せつ ends in 'tsu'",
          "いただければ → 'i-ta-da-ke-re-ba'; the 〜ば conditional ON the humble いただける ('if I may receive your ~ing')",
          "納得します → 'na-t-to-ku-shi-mas'; small っ a held beat"
        ]
      }
    ],
    "cultural_notes_en": "Stating an opinion in Japanese is wrapped in deference machinery that English lacks. 述べさせていただきます ('allow me to state') is the headline: a causative (させる, 'cause/let to do') fused with the humble receiving verb いただく — literally 'I will humbly receive the favor of being allowed to state' — to introduce your own opinion as if it were a privilege granted by the room. There is no American equivalent; 'I'd just like to say' is far flatter. Denial is equally cushioned: 〜とは言えません ('one cannot quite say that ~') softens 'that's wrong' into 'that can't really be claimed,' preserving the other side's face — the same indirection as the negotiation and meeting lessons. Even disagreement (反対です) is usually prefaced with partial agreement ('I partly agree, but…', as the dialogue shows) before the 'but.' For an American learner the instinct to 'just give your honest take directly' reads as combative; competence here is showing your view through the polite scaffolding, and at B1 you should recognize させていただく as a fixed humble frame, not yet generate causative-humble forms freely.",
    "tip_advice_en": "Highest-leverage recognition target: 〜させていただきます — causative (させる, B1 priority) + humble いただく — as a fixed 'allow me to ~' frame for your own actions in formal/business speech. At B1 you RECOGNIZE and deploy it whole (述べさせていただきます, 説明させていただきます); free causative and causative-passive production (〜させる / 〜させられる across verbs) is **flagged for B2 — no B1 lesson here teaches the causative system with example coverage**, only this frozen humble idiom, so don't back-fill a paradigm the lessons don't teach (the #488/#491 restraint rule). Second, lock 〜とは言えない as soft denial ('cannot go so far as to say'), and notice 〜ば conditional riding on a humble verb (いただければ, 'if I may receive'). Pronunciation watch-points: させていただきます is six even mora — don't compress; small っ a held beat in 納得 ('na-t-to-ku'). Drill: introduce one opinion with 〜させていただきます, then soft-deny a claim with 〜とは言えません.",
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "教育費を無料にするべきだと思います。",
        "english": "I think education should be free."
      },
      {
        "speaker": "B",
        "japanese": "その意見には一部賛成ですが、財源の問題があります。",
        "english": "I partly agree, but there's the issue of funding."
      },
      {
        "speaker": "A",
        "japanese": "税金を増やせば解決できるのでは？",
        "english": "Couldn't we solve it by raising taxes?"
      },
      {
        "speaker": "B",
        "japanese": "しかし、国民の負担も考慮すべきです。",
        "english": "But we should also consider the burden on citizens."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "その___には根拠がありません。",
        "answer": "主張"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "論点",
            "english": "point of discussion"
          },
          {
            "japanese": "根拠",
            "english": "evidence"
          }
        ],
        "instruction": "Match the Japanese discussion terms"
      },
      {
        "type": "translation",
        "vietnamese": "Theo quan điểm của tôi, vấn đề này cần được xem xét lại.",
        "japanese": "私の観点からすると、この問題は再検討すべきです。"
      }
    ]
  },
  {
    "id": 37,
    "title": "Making Suggestions",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "提案する",
        "english": "to suggest"
      },
      {
        "japanese": "勧める",
        "english": "to recommend"
      },
      {
        "japanese": "選択肢",
        "english": "option"
      },
      {
        "japanese": "代替案",
        "english": "alternative"
      },
      {
        "japanese": "考慮する",
        "english": "to consider"
      },
      {
        "japanese": "採用する",
        "english": "to adopt"
      },
      {
        "japanese": "メリット",
        "english": "merit"
      },
      {
        "japanese": "デメリット",
        "english": "demerit"
      },
      {
        "japanese": "優先順位",
        "english": "priority"
      },
      {
        "japanese": "試す",
        "english": "to try"
      }
    ],
    "grammar": [
      {
        "point": "～てはいかがですか",
        "explanation": "How about ~? (polite suggestion)"
      },
      {
        "point": "～たほうがいい",
        "explanation": "It would be better to ~"
      }
    ],
    "examples": [
      {
        "japanese": "新しいシステムを導入してはいかがですか。",
        "english": "How about introducing a new system?",
        "pronunciation_focus_en": [
          "新しい → 'a-ta-ra-shi-i'; i-adjective, final いい held",
          "システムを → 'shi-su-te-mu o'; katakana, を object particle 'o'",
          "導入して → 'do-o-nyu-u-shi-te'; どう and にゅう both long (にゅ glided)",
          "はいかがですか → 'wa i-ka-ga des-ka'; 〜てはいかがですか = polite 'how about ~ing?'"
        ]
      },
      {
        "japanese": "まずは小規模で試したほうがいいでしょう。",
        "english": "It would be better to try it on a small scale first.",
        "pronunciation_focus_en": [
          "まずは → 'ma-zu wa'; ず voiced; は = 'wa' ('first of all')",
          "小規模で → 'sho-o-ki-bo de'; しょう long 'oh'; で = means ('on a small scale')",
          "試した → 'ta-me-shi-ta'; plain past required before ほうがいい (Lesson 31 trap)",
          "ほうがいいでしょう → 'ho-o ga i-i de-sho-o'; でしょう softens the advice to a gentle conjecture"
        ]
      },
      {
        "japanese": "代替案として、オンライン会議を提案します。",
        "english": "As an alternative, I propose an online meeting.",
        "pronunciation_focus_en": [
          "代替案 (だいたいあん) → 'da-i-ta-i-an'; ん a beat",
          "として → 'to-shi-te' = 'as / by way of' (set connector)",
          "オンライン会議 → 'on-ra-i-n ka-i-gi'; katakana + kanji blend",
          "提案します → 'te-i-an-shi-mas'; を marks 会議 as the object proposed"
        ]
      },
      {
        "japanese": "このプランにはいくつかのメリットがあります。",
        "english": "This plan has several merits.",
        "pronunciation_focus_en": [
          "プランには → 'pu-ran ni wa'; に + は ('as for this plan')",
          "いくつかの → 'i-ku-tsu-ka no'; つ is 'tsu' ('several')",
          "メリット → 'me-ri(t)-to'; small っ held; means 'advantage/upside' — NOT English moral 'merit'",
          "があります → が subject, あります inanimate existence"
        ]
      },
      {
        "japanese": "優先順位を決める必要があります。",
        "english": "We need to set priorities.",
        "pronunciation_focus_en": [
          "優先順位 → 'yu-u-sen-jun-i'; ゆう long 'oh', two ん each a beat",
          "を決める → 'o ki-me-ru'; を object particle 'o'",
          "必要 (ひつよう) → 'hi-tsu-yo-o'; つ is 'tsu', よう long 'oh'",
          "があります → 〜する必要がある = 'there is a need to ~'; が, not を"
        ]
      }
    ],
    "cultural_notes_en": "Japanese suggestions are calibrated by how much they leave the decision with the listener. 〜てはいかがですか ('how about ~ing?') floats an idea without pushing; 〜たほうがいいでしょう adds でしょう to soften 'you should' into 'it would probably be better' — the でしょう is doing face-work, not expressing doubt. An American 'I suggest we do X' or 'we should just do X' lands as more assertive than the Japanese register wants; the polite move is to under-state and let the group converge, consistent with the meeting/negotiation lessons. A vocabulary trap worth flagging: メリット / デメリット are everyday Japanese for 'advantage / disadvantage' (pros and cons), NOT the English moral senses of 'merit' / 'demerit' — a classic 和製英語 (Japanese-made-English) false friend; treating them as the English words mistranslates ordinary business speech. The practical B1 takeaway: pitch suggestions low (〜てはいかがですか / 〜でしょう), read メリット as 'upside,' and expect the real decision to form by consensus, not by the strength of your pitch.",
    "tip_advice_en": "Highest-leverage suggestion ladder: 〜てはいかがですか (polite, hands the choice over) and 〜たほうがいいでしょう (soft 'you'd better,' でしょう blunts it) — both pitched below the American 'I suggest/we should' default; under-stating is the competent register here. Reuse the Lesson 31 trap: ほうがいい takes the PLAIN PAST (試した, not 試す) for the 'should' meaning. Vocabulary tip with teeth: メリット/デメリット = pros/cons (advantage/disadvantage), a 和製英語 false friend — never read them as English 'merit/demerit'; watch for more (テンション = mood/energy not 'tension,' クレーム = complaint not 'claim'). Pronunciation watch-points: long 'oh' in どう/しょう/ゆう held two beats; small っ a held silent beat in メリット ('me-ri-t-to'). Drill one proposal two ways: 〜てはいかがですか and 〜たほうがいいでしょう, feeling the deference.",
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "来月のイベント、どうしますか。",
        "english": "What shall we do about next month's event?"
      },
      {
        "speaker": "B",
        "japanese": "屋外でバーベキューをしてはいかがですか。",
        "english": "How about having a BBQ outdoors?"
      },
      {
        "speaker": "A",
        "japanese": "いいアイデアですね。でも天気が心配です。",
        "english": "Good idea. But I'm worried about the weather."
      },
      {
        "speaker": "B",
        "japanese": "では、室内と室外の両方のプランを準備しましょう。",
        "english": "Then, let's prepare both indoor and outdoor plans."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "新しい方法を___してはいかがですか。",
        "answer": "試し"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "提案",
            "english": "proposal"
          },
          {
            "japanese": "勧める",
            "english": "recommend"
          }
        ],
        "instruction": "Match the Japanese suggestion verbs"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi đề nghị chúng ta nên họp vào thứ Sáu.",
        "japanese": "金曜日に会議をすることを提案します。"
      }
    ]
  },
  {
    "id": 38,
    "title": "Apologizing and Making Excuses",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "謝る",
        "english": "to apologize"
      },
      {
        "japanese": "お詫び",
        "english": "apology (formal)"
      },
      {
        "japanese": "申し訳ない",
        "english": "I'm sorry (strong)"
      },
      {
        "japanese": "言い訳",
        "english": "excuse"
      },
      {
        "japanese": "理由",
        "english": "reason"
      },
      {
        "japanese": "不注意",
        "english": "carelessness"
      },
      {
        "japanese": "誤解",
        "english": "misunderstanding"
      },
      {
        "japanese": "謝罪する",
        "english": "to apologize (formal)"
      },
      {
        "japanese": "許す",
        "english": "to forgive"
      },
      {
        "japanese": "反省する",
        "english": "to reflect / regret"
      }
    ],
    "grammar": [
      {
        "point": "～てしまいました",
        "explanation": "I accidentally did (regret)"
      },
      {
        "point": "～せいで",
        "explanation": "because of ~ (blame)"
      }
    ],
    "examples": [
      {
        "japanese": "大変申し訳ございません。私の不注意でした。",
        "english": "I am very sorry. It was my carelessness.",
        "pronunciation_focus_en": [
          "大変 (たいへん) → 'ta-i-hen'; intensifier ('very/terribly')",
          "申し訳ございません → 'mo-o-shi-wa-ke go-za-i-ma-sen'; the strongest everyday apology (carried from A2)",
          "私の → 'wa-ta-shi no'; の possessive",
          "不注意でした → 'fu-chu-u-i de-shi-ta'; ちゅう long 'oh'; でした = polite past of です"
        ]
      },
      {
        "japanese": "約束を忘れてしまいました。",
        "english": "I accidentally forgot the appointment.",
        "pronunciation_focus_en": [
          "約束 (やくそく) → 'ya-ku-so-ku', four even mora",
          "を忘れて → 'o wa-su-re-te'; を object particle 'o'; te-form of 忘れる",
          "しまいました → 'shi-ma-i-ma-shi-ta'; 〜てしまいました = completion + REGRET ('went and forgot')",
          "in casual speech 〜てしまう contracts to 〜ちゃう (忘れちゃった) — note for recognition"
        ]
      },
      {
        "japanese": "電車の遅れのせいで遅刻しました。",
        "english": "I was late because of the train delay.",
        "pronunciation_focus_en": [
          "電車の遅れ → 'den-sha no o-ku-re'; の possessive ('the train's delay')",
          "せいで → 'se-i de' = 'because of ~' (BLAME — negative cause; contrast おかげで, positive)",
          "遅刻 (ちこく) → 'chi-ko-ku' ('lateness/tardiness')",
          "しました → 'shi-ma-shi-ta', polite past"
        ]
      },
      {
        "japanese": "言い訳をするつもりはありません。",
        "english": "I don't intend to make excuses.",
        "pronunciation_focus_en": [
          "言い訳 (いいわけ) → 'i-i-wa-ke'; いい a held long 'ee' ('excuse')",
          "をする → 'o su-ru'; を object particle 'o'",
          "つもり → 'tsu-mo-ri'; つ is 'tsu'; 〜つもり = 'intention to ~'",
          "はありません → 'wa a-ri-ma-sen'; はありません (not がありません) — は marks the negated intention"
        ]
      },
      {
        "japanese": "どうかお許しください。",
        "english": "Please forgive me.",
        "pronunciation_focus_en": [
          "どうか → 'do-o-ka'; どう long 'oh' — an earnest 'please, I beg you' (stronger than どうぞ)",
          "お許し → 'o yu-ru-shi'; お = humble/beautifying prefix on 許し",
          "ください → 'ku-da-sa-i'; 〜ください request",
          "said slowly and low — the pleading register, not a casual request"
        ]
      }
    ],
    "cultural_notes_en": "Apologizing in Japan is relationship repair, not an admission of legal fault, and the cultural script inverts the American litigation-shaped instinct to never say 'sorry' or to explain yourself. Here a fast, unqualified apology comes FIRST, and adding reasons reads as 言い訳 (iiwake, excuse-making) — socially worse than the original mistake, which is why 言い訳をするつもりはありません ('I don't intend to make excuses') is itself a virtuous thing to say. The apology scale from A2 deepens: すみません < ごめんなさい < 申し訳ありません < 大変申し訳ございません, matched to severity and audience. The grammar carries the attitude: 〜てしまいました is the key B1 form — it fuses completion with regret/unintendedness ('I went and forgot,' not just 'I forgot'); dropping it to plain 忘れました loses the contrition. Note the cause-particle asymmetry: せいで assigns blame (negative outcomes), おかげで assigns credit (positive) — using せいで for a good result, or おかげで for a bad one, is a real semantic error. B1 takeaway: apologize first and bare, hold the 〜てしまう regret nuance, and don't pile on reasons the way an American might 'explain.'",
    "tip_advice_en": "Highest-leverage B1 form: 〜てしまう / 〜てしまいました — completion + regret/unintendedness. 忘れてしまいました = 'I (regrettably, unintentionally) forgot'; plain 忘れました is just 'I forgot.' In apologies the しまう is the contrition, so don't drop it. Recognize the casual contractions: 〜てしまう→〜ちゃう, 〜でしまう→〜じゃう (忘れちゃった) — you'll hear these constantly even if you produce the full form at B1. Second, the cause-particle pair: せいで = because-of (blame, bad outcome) vs おかげで = thanks-to (credit, good outcome) — they are not interchangeable; matching polarity wrong is a clear error. Reuse the apology scale (A2) and lead with the apology, not the reason — explaining first reads as 言い訳. Pronunciation watch-points: long 'oh' in どうか/ちゅう held two beats; いい in 言い訳 a held long 'ee.' Drill: apologize for one mistake using 〜てしまいました, then explicitly decline to excuse it.",
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "すみません、約束の時間に遅れてしまいました。",
        "english": "I'm sorry, I was late for our appointment."
      },
      {
        "speaker": "B",
        "japanese": "どうしたんですか。",
        "english": "What happened?"
      },
      {
        "speaker": "A",
        "japanese": "電車が止まってしまって。本当に申し訳ありません。",
        "english": "The train stopped. I am truly sorry."
      },
      {
        "speaker": "B",
        "japanese": "次回から気をつけてくださいね。",
        "english": "Please be careful next time."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "私の___でミスをしました。",
        "answer": "不注意"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "謝罪",
            "english": "apology"
          },
          {
            "japanese": "言い訳",
            "english": "excuse"
          }
        ],
        "instruction": "Match the Japanese apology terms"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi xin lỗi vì đã làm vỡ cốc của bạn. Đó là do sơ suất của tôi.",
        "japanese": "コップを割ってしまい申し訳ありません。私の不注意でした。"
      }
    ]
  },
  {
    "id": 39,
    "title": "Giving Advice",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "アドバイス",
        "english": "advice"
      },
      {
        "japanese": "勧める",
        "english": "to recommend"
      },
      {
        "japanese": "忠告",
        "english": "warning / admonition"
      },
      {
        "japanese": "提案",
        "english": "proposal"
      },
      {
        "japanese": "助言",
        "english": "suggestion"
      },
      {
        "japanese": "役立つ",
        "english": "useful"
      },
      {
        "japanese": "経験談",
        "english": "story of experience"
      },
      {
        "japanese": "対策",
        "english": "countermeasure"
      },
      {
        "japanese": "～したらどうですか",
        "english": "How about doing ~?"
      },
      {
        "japanese": "～たほうがいい",
        "english": "You'd better ~"
      }
    ],
    "grammar": [
      {
        "point": "～といいですよ",
        "explanation": "It would be good if you ~ (advice)"
      },
      {
        "point": "～したほうがいい",
        "explanation": "You should ~ (stronger advice)"
      }
    ],
    "examples": [
      {
        "japanese": "早めに予約したほうがいいですよ。",
        "english": "You should make a reservation early.",
        "pronunciation_focus_en": [
          "早めに → 'ha-ya-me ni'; に makes it adverbial ('early / sooner')",
          "予約 (よやく) → 'yo-ya-ku', three even mora",
          "したほうがいい → plain past した + ほうがいい (the Lesson 31 'should' frame)",
          "ですよ → 'des yo'; the よ adds friendly emphasis to advice (softens, doesn't command)"
        ]
      },
      {
        "japanese": "日本語の勉強にはアニメを見るといいですよ。",
        "english": "For studying Japanese, it's good to watch anime.",
        "pronunciation_focus_en": [
          "勉強には → 'ben-kyo-o ni wa'; きょう long 'oh'; には = 'for the purpose of'",
          "アニメを → 'a-ni-me o'; を object particle 'o'",
          "見るといい → 'mi-ru to i-i'; 〜といい = 'it'd be good if/to ~' (と consequence + いい) — gentle advice",
          "ですよ → 'des yo'; friendly advisory よ"
        ]
      },
      {
        "japanese": "一度専門家に相談してみてはいかがですか。",
        "english": "How about consulting an expert?",
        "pronunciation_focus_en": [
          "一度 → 'i-chi-do' ('once / one time')",
          "専門家に → 'sen-mon-ka ni'; に marks the consult target; two ん each a beat",
          "相談してみて → 'so-o-dan-shi-te mi-te'; 〜てみる = 'try ~ing / give it a go' (te-form + みる)",
          "はいかがですか → 'wa i-ka-ga des-ka'; polite 'how about ~?'"
        ]
      },
      {
        "japanese": "私の経験から言うと、無理をしないことです。",
        "english": "From my experience, don't overdo it.",
        "pronunciation_focus_en": [
          "経験から言うと → 'ke-e-ken ka-ra i-u to'; 〜から言うと = 'speaking from ~'; と consequence",
          "無理を → 'mu-ri o'; を object particle 'o' ('overdoing it')",
          "しない → 'shi-na-i'; PLAIN negative of する (plain form inside the こと nominalization)",
          "ことです → 'ko-to des'; 〜ことです = 'the thing (to do) is ~' — an advice-giving frame"
        ]
      },
      {
        "japanese": "もっと休息を取ることをお勧めします。",
        "english": "I recommend taking more rest.",
        "pronunciation_focus_en": [
          "もっと → 'mo(t)-to'; small っ a held silent beat ('more')",
          "休息を取る → 'kyu-u-so-ku o to-ru'; きゅう long 'oh'; を object 'o'",
          "ことを → 'ko-to o'; こと nominalizes 'taking rest', を marks it as recommended",
          "お勧めします → 'o-su-su-me-shi-mas'; お humble prefix; final す devoiced"
        ]
      }
    ],
    "cultural_notes_en": "Advice in Japanese is softened structurally because unsolicited direct advice can imply the listener couldn't figure it out themselves — a face issue. The toolkit graduates the directness: 〜といいですよ ('it'd be good if you ~,' lightest), 〜てみてはいかがですか ('how about giving ~ a try,' tentative), 〜たほうがいいですよ ('you'd better ~,' firmer but the よ keeps it friendly), 〜ことです ('the thing is to ~,' summarizing wisdom). The friendly よ on advice is not the assertive よ of an argument — context flips its tone, and dropping it can make advice sound like an order. 〜てみる ('try doing, see how it goes') frames a suggestion as low-stakes experimentation rather than a directive, which fits the face-preserving norm. Compared to the American readiness to give brisk, confident advice ('you should just…'), the Japanese register stays provisional and routes through the listener's autonomy. B1 takeaway: pick the rung to match how close you are and how solicited the advice is, and treat 〜てみる as the gentle 'give it a shot' move.",
    "tip_advice_en": "Highest-leverage advice patterns to lock as a graded set: 〜といいですよ (lightest 'it'd be good if') → 〜てみてはいかがですか ('how about trying') → 〜たほうがいいですよ (firmer 'you'd better') → 〜ことです ('the thing is to'). Match the rung to closeness/solicitation; over-direct advice is a face issue, not just impolite. Key carry: 〜てみる = 'do ~ and see' (te-form + みる, the verb 'see' bleached to 'try') — a B1 attempt/experiment marker; recognize it everywhere. Reuse traps: ほうがいい takes plain PAST (したほうがいい); the こと/の nominalizer turns a clause into the advice noun (しないことです). Pronunciation watch-points: friendly よ stays light (not the argumentative よ); long 'oh' in きょう/きゅう/そう held two beats; small っ a held beat in もっと. Drill one piece of advice up the ladder: 〜といいですよ → 〜たほうがいいですよ.",
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "最近仕事が忙しくて疲れています。",
        "english": "I've been busy with work lately and I'm tired."
      },
      {
        "speaker": "B",
        "japanese": "それは大変ですね。休暇を取ったらどうですか。",
        "english": "That's tough. How about taking a vacation?"
      },
      {
        "speaker": "A",
        "japanese": "でも仕事が溜まっていて…",
        "english": "But work is piling up..."
      },
      {
        "speaker": "B",
        "japanese": "一度リセットすることも大事ですよ。",
        "english": "It's also important to reset once in a while."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "もっと休息を___ことをお勧めします。",
        "answer": "取る"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "忠告",
            "english": "warning"
          },
          {
            "japanese": "助言",
            "english": "advice"
          }
        ],
        "instruction": "Match the Japanese advice terms"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi khuyên bạn nên học tiếng Nhật mỗi ngày một chút.",
        "japanese": "毎日少しずつ日本語を勉強したほうがいいですよ。"
      }
    ]
  },
  {
    "id": 40,
    "title": "Describing Experiences",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "経験",
        "english": "experience"
      },
      {
        "japanese": "体験",
        "english": "hands-on experience"
      },
      {
        "japanese": "印象",
        "english": "impression"
      },
      {
        "japanese": "感動する",
        "english": "to be moved"
      },
      {
        "japanese": "記憶",
        "english": "memory"
      },
      {
        "japanese": "思い出",
        "english": "recollection"
      },
      {
        "japanese": "詳細",
        "english": "details"
      },
      {
        "japanese": "語る",
        "english": "to tell / narrate"
      },
      {
        "japanese": "振り返る",
        "english": "to look back"
      },
      {
        "japanese": "貴重",
        "english": "valuable"
      }
    ],
    "grammar": [
      {
        "point": "～たことがある",
        "explanation": "have done ~ (experience)"
      },
      {
        "point": "～時（とき）",
        "explanation": "when / during the time of ~"
      }
    ],
    "examples": [
      {
        "japanese": "富士山に登ったことがありますか。",
        "english": "Have you ever climbed Mt. Fuji?",
        "pronunciation_focus_en": [
          "富士山 (ふじさん) → 'fu-ji-san'; ふ soft bilabial, soft j",
          "に登った → 'ni no-bo(t)-ta'; に marks the climb target; small っ a held beat in 登った",
          "ことがありますか → 'ko-to ga a-ri-mas-ka'; 〜たことがある = 'have the experience of ~ing'",
          "this is EXPERIENCE ('have you ever'), distinct from plain past 登りましたか ('did you climb')"
        ]
      },
      {
        "japanese": "去年、日本に留学した時のことを話します。",
        "english": "I'll talk about when I studied in Japan last year.",
        "pronunciation_focus_en": [
          "去年 → 'kyo-nen'; きょ one glided mora — relative-time word, no particle",
          "留学した → 'ryu-u-ga-ku-shi-ta'; りゅう long (りゅ glided) — plain past MODIFYING 時 directly (no relative pronoun)",
          "時のこと → 'to-ki no ko-to'; 〜た時 = 'when [I] did ~'; のこと = 'the matter of'",
          "を話します → 'o ha-na-shi-mas'; を object 'o'"
        ]
      },
      {
        "japanese": "その経験は私にとって貴重なものでした。",
        "english": "That experience was valuable to me.",
        "pronunciation_focus_en": [
          "経験は → 'ke-e-ken wa'; けい long 'eh'; は = 'wa'",
          "私にとって → 'wa-ta-shi ni to(t)-te'; 〜にとって = 'for/to (someone)'; small っ a held beat",
          "貴重な → 'ki-cho-o na'; ちょう long 'oh'; な = na-adjective linker before もの",
          "ものでした → 'mo-no de-shi-ta'; でした = polite past of です"
        ]
      },
      {
        "japanese": "初めての海外旅行はとても感動的でした。",
        "english": "My first overseas trip was very moving.",
        "pronunciation_focus_en": [
          "初めての → 'ha-ji-me-te no'; soft j; の links to the noun ('first-time ~')",
          "海外旅行 → 'ka-i-ga-i ryo-ko-o'; りょ one glided mora, こう long 'oh'",
          "は → topic particle, 'wa'; とても → 'to-te-mo' (positive degree adverb)",
          "感動的でした → 'kan-do-o-te-ki de-shi-ta'; どう long 'oh'; な-adj past via でした"
        ]
      },
      {
        "japanese": "子どもの頃の記憶をよく覚えています。",
        "english": "I remember my childhood memories well.",
        "pronunciation_focus_en": [
          "子どもの頃 → 'ko-do-mo no ko-ro'; 頃 = 'around the time of' ('childhood')",
          "記憶を → 'ki-o-ku o'; を object particle 'o'",
          "よく → 'yo-ku' ('well / often')",
          "覚えています → 'o-bo-e-te i-mas'; 〜ている = STATE: 覚えている = 'remember' (a held state), NOT 'am memorizing'"
        ]
      }
    ],
    "cultural_notes_en": "This lesson hinges on a distinction English collapses: 〜たことがある ('have the experience of having done ~') vs plain past ('did ~'). 富士山に登ったことがありますか asks whether climbing Fuji is somewhere in your life's experience set; 登りましたか asks whether you did it on a specific occasion. English 'Have you ever…?' vs 'Did you…?' is the closest mirror, but Japanese makes it a fixed grammatical frame you must choose deliberately. Two more B1 structural shifts surface here. First, noun-modifying clauses without a relative pronoun: 留学した時 = 'the time [I] studied abroad' — the verb sits directly before the noun, no 'when/that/which' (a full preview of Lesson 45, and the structure English speakers find most disorienting). Second, 覚えています is a resultant STATE ('I remember,' the knowledge is held), not progressive ('I am memorizing') — the same 〜ている nuance as Lessons 32/40, and a perennial English-speaker misread. Culturally, climbing 富士山 once is a near-canonical Japanese life experience (the saying: a wise person climbs it once, a fool twice), which is why it's the textbook example here.",
    "tip_advice_en": "Highest-leverage B1 frame: 〜たことがある = experiential 'have you ever / I have once,' deliberately different from plain past 'did.' Choose by meaning: a life-experience question → 〜たことがありますか; a specific past event → 〜ましたか. Second, start internalizing noun-modifying clauses now (full lesson at 45): in 留学した時 / 子どもの頃 the modifier (verb or phrase) comes BEFORE the noun with no relative pronoun — there is no Japanese word for 'when/that/which'; the position does the work. Train yourself to read right-to-left from the head noun. Third, hold the 〜ている = state reading: 覚えています = 'I remember' (state), not 'I'm memorizing.' Pronunciation watch-points: small っ a held beat (登った, にとって); long glided mora りゅう/りょ/きょ; ふ in 富士 a soft bilabial. Drill: ask one 〜たことがありますか question, then answer with a 〜た時 modifying clause.",
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "日本に行ったことがありますか。",
        "english": "Have you ever been to Japan?"
      },
      {
        "speaker": "B",
        "japanese": "はい、二年前に旅行しました。",
        "english": "Yes, I traveled there two years ago."
      },
      {
        "speaker": "A",
        "japanese": "どこが一番印象に残っていますか。",
        "english": "What left the strongest impression?"
      },
      {
        "speaker": "B",
        "japanese": "京都の寺院がとても美しかったです。",
        "english": "The temples in Kyoto were very beautiful."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "その___は私にとって貴重でした。",
        "answer": "経験"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "思い出",
            "english": "memory"
          },
          {
            "japanese": "感動",
            "english": "being moved"
          }
        ],
        "instruction": "Match the Japanese experience-related words"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi chưa bao giờ ăn sushi ở Nhật Bản.",
        "japanese": "日本でお寿司を食べたことがありません。"
      }
    ]
  },
  {
    "id": 41,
    "title": "Comparing Options",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "比較する",
        "english": "to compare"
      },
      {
        "japanese": "選択",
        "english": "choice"
      },
      {
        "japanese": "違い",
        "english": "difference"
      },
      {
        "japanese": "共通点",
        "english": "common point"
      },
      {
        "japanese": "優れている",
        "english": "superior"
      },
      {
        "japanese": "劣る",
        "english": "inferior"
      },
      {
        "japanese": "同様に",
        "english": "similarly"
      },
      {
        "japanese": "一方で",
        "english": "on the other hand"
      },
      {
        "japanese": "どちらかと言えば",
        "english": "if I had to choose"
      },
      {
        "japanese": "対比",
        "english": "contrast"
      }
    ],
    "grammar": [
      {
        "point": "～より～のほうが",
        "explanation": "Compared to A, B is more ~"
      },
      {
        "point": "～に比べて",
        "explanation": "Compared to ~"
      }
    ],
    "examples": [
      {
        "japanese": "電車よりバスのほうが安いです。",
        "english": "The bus is cheaper than the train."
      },
      {
        "japanese": "A社とB社を比べてみましょう。",
        "english": "Let's compare Company A and Company B."
      },
      {
        "japanese": "両者には多くの共通点があります。",
        "english": "Both have many common points."
      },
      {
        "japanese": "品質ではA社が優れていますが、価格ではB社が劣ります。",
        "english": "Company A is superior in quality, but Company B is inferior in price."
      },
      {
        "japanese": "どちらかと言えば、私は都市より田舎が好きです。",
        "english": "If I had to choose, I prefer the countryside over the city."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "この二つのスマホ、どちらがいいと思う？",
        "english": "These two smartphones, which one do you think is better?"
      },
      {
        "speaker": "B",
        "japanese": "カメラの性能ではこちらのほうが優れているよ。",
        "english": "In terms of camera performance, this one is superior."
      },
      {
        "speaker": "A",
        "japanese": "でもバッテリーはあっちのほうが長持ちするね。",
        "english": "But the battery lasts longer on that one."
      },
      {
        "speaker": "B",
        "japanese": "そうだね。用途によって選ぶといいね。",
        "english": "Yeah. It's good to choose based on usage."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "電車___バスのほうが安いです。",
        "answer": "より"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "比較",
            "english": "comparison"
          },
          {
            "japanese": "対比",
            "english": "contrast"
          }
        ],
        "instruction": "Match the Japanese comparison terms"
      },
      {
        "type": "translation",
        "vietnamese": "So với xe đạp, xe máy nhanh hơn nhưng đắt hơn.",
        "japanese": "自転車に比べて、バイクのほうが速いですが高いです。"
      }
    ]
  },
  {
    "id": 42,
    "title": "Hypothetical Situations",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "仮定",
        "english": "assumption"
      },
      {
        "japanese": "もし",
        "english": "if"
      },
      {
        "japanese": "条件",
        "english": "condition"
      },
      {
        "japanese": "可能性",
        "english": "possibility"
      },
      {
        "japanese": "～たら",
        "english": "if (conditional)"
      },
      {
        "japanese": "～ば",
        "english": "if (conditional)"
      },
      {
        "japanese": "～なら",
        "english": "if (conditional)"
      },
      {
        "japanese": "現実的",
        "english": "realistic"
      },
      {
        "japanese": "想像する",
        "english": "to imagine"
      },
      {
        "japanese": "願望",
        "english": "desire"
      }
    ],
    "grammar": [
      {
        "point": "～たら、～のに",
        "explanation": "If ~, then ~ (counterfactual wish)"
      },
      {
        "point": "～ばいいのに",
        "explanation": "I wish ~ would happen (if only)"
      }
    ],
    "examples": [
      {
        "japanese": "もし宝くじが当たったら、世界旅行をしたいです。",
        "english": "If I won the lottery, I'd want to travel the world."
      },
      {
        "japanese": "もっと時間があれば、もっと勉強できるのに。",
        "english": "If I had more time, I could study more."
      },
      {
        "japanese": "雨が降らなければ、ピクニックに行けたのに。",
        "english": "If it hadn't rained, we could have gone on a picnic."
      },
      {
        "japanese": "日本語がもっと上手なら、日本人と友達になれるのに。",
        "english": "If I were better at Japanese, I could make friends with Japanese people."
      },
      {
        "japanese": "彼が来ればいいのに。",
        "english": "I wish he would come."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "もし一億円あったら、何をする？",
        "english": "If you had 100 million yen, what would you do?"
      },
      {
        "speaker": "B",
        "japanese": "家を買って、世界旅行に行くかな。",
        "english": "Maybe buy a house and travel the world."
      },
      {
        "speaker": "A",
        "japanese": "私は投資をして、将来のために使いたい。",
        "english": "I'd invest and use it for the future."
      },
      {
        "speaker": "B",
        "japanese": "現実的だね。でも夢を見るのは楽しいね。",
        "english": "You're realistic. But it's fun to dream."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "もし時間が___、手伝ってあげられるのに。",
        "answer": "あれば"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "仮定",
            "english": "assumption"
          },
          {
            "japanese": "可能性",
            "english": "possibility"
          }
        ],
        "instruction": "Match the Japanese hypothetical terms"
      },
      {
        "type": "translation",
        "vietnamese": "Nếu tôi biết sớm hơn, tôi đã có thể giúp bạn.",
        "japanese": "もっと早く知っていれば、あなたを助けられたのに。"
      }
    ]
  },
  {
    "id": 43,
    "title": "Reporting Speech",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "伝聞",
        "english": "hearsay"
      },
      {
        "japanese": "引用",
        "english": "quotation"
      },
      {
        "japanese": "～そうだ",
        "english": "I heard that ~"
      },
      {
        "japanese": "～と言う",
        "english": "say that ~"
      },
      {
        "japanese": "～と聞く",
        "english": "hear that ~"
      },
      {
        "japanese": "～と述べる",
        "english": "state that ~"
      },
      {
        "japanese": "～と説明する",
        "english": "explain that ~"
      },
      {
        "japanese": "～と報告する",
        "english": "report that ~"
      },
      {
        "japanese": "要約",
        "english": "summary"
      },
      {
        "japanese": "直接話法",
        "english": "direct speech"
      }
    ],
    "grammar": [
      {
        "point": "～と言っている",
        "explanation": "He/she says that ~ (reporting)"
      },
      {
        "point": "～とのことだ",
        "explanation": "I understand that ~ (hearsay, formal)"
      }
    ],
    "examples": [
      {
        "japanese": "彼は明日来ると言っていました。",
        "english": "He said he would come tomorrow."
      },
      {
        "japanese": "田中さんは来月結婚するそうです。",
        "english": "I heard that Tanaka-san is getting married next month."
      },
      {
        "japanese": "社長は新しいプロジェクトを始めると発表しました。",
        "english": "The president announced that he would start a new project."
      },
      {
        "japanese": "天気予報によると、明日は雨とのことです。",
        "english": "According to the weather forecast, it will rain tomorrow."
      },
      {
        "japanese": "彼女は「今日は忙しい」と言いました。",
        "english": "She said, 'I'm busy today.'"
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "山田さんが転職するって知ってる？",
        "english": "Did you know Yamada-san is changing jobs?"
      },
      {
        "speaker": "B",
        "japanese": "えっ、本当？誰から聞いたの？",
        "english": "What? Really? Who told you?"
      },
      {
        "speaker": "A",
        "japanese": "本人から直接聞いたんだ。来月から新しい会社だって。",
        "english": "I heard it directly from him. He said he'll start at a new company next month."
      },
      {
        "speaker": "B",
        "japanese": "そうなんだ。ビックリした。",
        "english": "I see. I'm surprised."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "彼は今日は休むと___。",
        "answer": "言っていました"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "伝聞",
            "english": "hearsay"
          },
          {
            "japanese": "引用",
            "english": "quotation"
          }
        ],
        "instruction": "Match the Japanese reporting terms"
      },
      {
        "type": "translation",
        "vietnamese": "Cô ấy nói rằng cô ấy sẽ đến muộn.",
        "japanese": "彼女は遅れると言っていました。"
      }
    ]
  },
  {
    "id": 44,
    "title": "Passive Voice",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "受身形",
        "english": "passive voice"
      },
      {
        "japanese": "作られる",
        "english": "is made"
      },
      {
        "japanese": "書かれる",
        "english": "is written"
      },
      {
        "japanese": "食べられる",
        "english": "is eaten"
      },
      {
        "japanese": "呼ばれる",
        "english": "is called"
      },
      {
        "japanese": "使われる",
        "english": "is used"
      },
      {
        "japanese": "建てられる",
        "english": "is built"
      },
      {
        "japanese": "知られる",
        "english": "is known"
      },
      {
        "japanese": "見られる",
        "english": "is seen"
      },
      {
        "japanese": "考えられる",
        "english": "is considered"
      }
    ],
    "grammar": [
      {
        "point": "～（ら）れる",
        "explanation": "Passive form (infinitive) – ru-verbs add られる, u-verbs change to ～れる"
      },
      {
        "point": "～によって",
        "explanation": "by (agent marker in passive)"
      }
    ],
    "examples": [
      {
        "japanese": "この寺は何世紀に建てられましたか。",
        "english": "In what century was this temple built?"
      },
      {
        "japanese": "日本のアニメは世界中で見られています。",
        "english": "Japanese anime is watched all over the world."
      },
      {
        "japanese": "この言葉はあまり使われません。",
        "english": "This word is not used much."
      },
      {
        "japanese": "その本は多くの人に読まれています。",
        "english": "That book is read by many people."
      },
      {
        "japanese": "彼はクラスで一番賢いと考えられています。",
        "english": "He is considered the smartest in the class."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "このお寺はいつ建てられたんですか。",
        "english": "When was this temple built?"
      },
      {
        "speaker": "B",
        "japanese": "八世紀に建てられたと言われています。",
        "english": "It is said to have been built in the 8th century."
      },
      {
        "speaker": "A",
        "japanese": "へえ、そんなに古いんですね。",
        "english": "Wow, that old, huh."
      },
      {
        "speaker": "B",
        "japanese": "はい、国の重要文化財に指定されています。",
        "english": "Yes, it is designated as an Important Cultural Property."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "この映画は多くの人に___。",
        "answer": "見られています"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "作られる",
            "english": "is made"
          },
          {
            "japanese": "使われる",
            "english": "is used"
          }
        ],
        "instruction": "Match the Japanese passive forms"
      },
      {
        "type": "translation",
        "vietnamese": "Bức tranh này được vẽ bởi một họa sĩ nổi tiếng.",
        "japanese": "この絵は有名な画家によって描かれました。"
      }
    ]
  },
  {
    "id": 45,
    "title": "Relative Clauses",
    "level": "B1",
    "vocabulary": [
      {
        "japanese": "連体修飾節",
        "english": "relative clause"
      },
      {
        "japanese": "～がいる",
        "english": "there is ~"
      },
      {
        "japanese": "～という",
        "english": "called/named ~"
      },
      {
        "japanese": "場所",
        "english": "place"
      },
      {
        "japanese": "人",
        "english": "person"
      },
      {
        "japanese": "物",
        "english": "thing"
      },
      {
        "japanese": "こと",
        "english": "event"
      },
      {
        "japanese": "～をしている",
        "english": "wearing / doing ~"
      },
      {
        "japanese": "～だった",
        "english": "was ~"
      },
      {
        "japanese": "～な",
        "english": "attribute (na-adj)"
      }
    ],
    "grammar": [
      {
        "point": "Noun + が/を/に + Verb + Noun (relative clause)",
        "explanation": "A clause modifying a noun directly before it."
      },
      {
        "point": "～ている + Noun",
        "explanation": "Present continuous or state as modifier."
      }
    ],
    "examples": [
      {
        "japanese": "昨日食べたラーメンはとても美味しかった。",
        "english": "The ramen I ate yesterday was very delicious."
      },
      {
        "japanese": "あそこに立っている人は田中さんです。",
        "english": "The person standing over there is Tanaka-san."
      },
      {
        "japanese": "私が買いたい本はどこですか。",
        "english": "Where is the book I want to buy?"
      },
      {
        "japanese": "これは日本語の勉強に使うテキストです。",
        "english": "This is the textbook used for studying Japanese."
      },
      {
        "japanese": "彼女が作ったケーキを食べました。",
        "english": "I ate the cake she made."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "あの赤いコートを着ている人は誰？",
        "english": "Who is that person wearing the red coat?"
      },
      {
        "speaker": "B",
        "japanese": "ああ、彼女は私の高校の同級生です。",
        "english": "Oh, she is my high school classmate."
      },
      {
        "speaker": "A",
        "japanese": "そうなんだ。彼女が話していた内容は面白かった？",
        "english": "I see. Was the content she was talking about interesting?"
      },
      {
        "speaker": "B",
        "japanese": "うん、旅行の話だったよ。",
        "english": "Yeah, it was about travel."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "昨日___映画はとても感動的でした。",
        "answer": "見た"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "連体修飾節",
            "english": "relative clause"
          },
          {
            "japanese": "先行詞",
            "english": "antecedent"
          }
        ],
        "instruction": "Match the Japanese grammar terms"
      },
      {
        "type": "translation",
        "vietnamese": "Người đang đọc sách kia là giáo viên của tôi.",
        "japanese": "本を読んでいる人は私の先生です。"
      }
    ]
  }
];

export default lessons;
