// Auto-generated by scripts/split-lessons-by-level.mjs.
// Edit the source lesson content here directly. DO NOT regenerate
// from a stale lessons.ts — the registry replaced that file.

import type { JapaneseLesson } from "./lessons";

export const lessons: JapaneseLesson[] = [
  {
    "id": 16,
    "title": "Na-Adjectives (Present Tense)",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "静か (しずか)",
        "english": "quiet"
      },
      {
        "japanese": "賑やか (にぎやか)",
        "english": "lively"
      },
      {
        "japanese": "綺麗 (きれい)",
        "english": "beautiful / clean"
      },
      {
        "japanese": "元気 (げんき)",
        "english": "healthy / energetic"
      }
    ],
    "grammar": [
      {
        "point": "Na-adjective usage",
        "explanation": "Na-adjectives require な before a noun, and take です for polite predicate. Negative: add ではありません or じゃないです."
      }
    ],
    "examples": [
      {
        "japanese": "図書館は静かです。",
        "english": "The library is quiet."
      },
      {
        "japanese": "彼女は元気な人です。",
        "english": "She is an energetic person."
      }
    ]
  },
  {
    "id": 17,
    "title": "Verbs: Present Tense (Masu-form)",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "食べます (たべます)",
        "english": "eat"
      },
      {
        "japanese": "飲みます (のみます)",
        "english": "drink"
      },
      {
        "japanese": "行きます (いきます)",
        "english": "go"
      },
      {
        "japanese": "来ます (きます)",
        "english": "come"
      },
      {
        "japanese": "見ます (みます)",
        "english": "see / watch"
      }
    ],
    "grammar": [
      {
        "point": "Masu-form polite present",
        "explanation": "Add ます to verb stem. Stem of 食べる is 食べ-, so 食べます. Negative: ません."
      }
    ],
    "examples": [
      {
        "japanese": "毎日コーヒーを飲みます。",
        "english": "I drink coffee every day."
      },
      {
        "japanese": "明日学校へ行きます。",
        "english": "I will go to school tomorrow."
      }
    ]
  },
  {
    "id": 18,
    "title": "Verbs: Past Tense (Masu-form)",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "食べました (たべました)",
        "english": "ate"
      },
      {
        "japanese": "飲みました (のみました)",
        "english": "drank"
      },
      {
        "japanese": "行きました (いきました)",
        "english": "went"
      },
      {
        "japanese": "来ました (きました)",
        "english": "came"
      },
      {
        "japanese": "見ました (みました)",
        "english": "saw / watched"
      }
    ],
    "grammar": [
      {
        "point": "Past tense masu-form",
        "explanation": "Change ます to ました for affirmative past. Negative past: ませんでした."
      }
    ],
    "examples": [
      {
        "japanese": "昨日すしを食べました。",
        "english": "I ate sushi yesterday."
      },
      {
        "japanese": "映画を見ませんでした。",
        "english": "I did not watch a movie."
      }
    ]
  },
  {
    "id": 19,
    "title": "Particles: は, が, を",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "は (wa)",
        "english": "topic marker"
      },
      {
        "japanese": "が (ga)",
        "english": "subject marker"
      },
      {
        "japanese": "を (o)",
        "english": "object marker"
      }
    ],
    "grammar": [
      {
        "point": "Particle functions",
        "explanation": "は marks the topic (what you are talking about). が marks the grammatical subject. を marks the direct object. は can contrast, が is used for new information."
      }
    ],
    "examples": [
      {
        "japanese": "私は学生です。",
        "english": "I am a student (topic)."
      },
      {
        "japanese": "猫がいます。",
        "english": "There is a cat (subject)."
      },
      {
        "japanese": "本を読みます。",
        "english": "I read a book (object)."
      }
    ]
  },
  {
    "id": 20,
    "title": "Te-Form Basics",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "食べて (たべて)",
        "english": "eating / please eat"
      },
      {
        "japanese": "飲んで (のんで)",
        "english": "drinking / please drink"
      },
      {
        "japanese": "行って (いって)",
        "english": "going / please go"
      },
      {
        "japanese": "見て (みて)",
        "english": "seeing / please see"
      },
      {
        "japanese": "読んで (よんで)",
        "english": "reading / please read"
      }
    ],
    "grammar": [
      {
        "point": "Te-form formation & uses",
        "explanation": "Te-form connects verbs, makes requests (~てください), and forms progressive (~ている). Formation rules: る→て, う/つ/る→って, む/ぬ/ぶ→んで, etc."
      }
    ],
    "examples": [
      {
        "japanese": "窓を開けてください。",
        "english": "Please open the window."
      },
      {
        "japanese": "今、勉強しています。",
        "english": "I am studying now."
      }
    ]
  },
  {
    "id": 21,
    "title": "Making Phone Calls",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "もしもし",
        "english": "hello (on phone)"
      },
      {
        "japanese": "電話番号",
        "english": "phone number"
      },
      {
        "japanese": "電話をかける",
        "english": "to make a phone call"
      },
      {
        "japanese": "電話に出る",
        "english": "to answer the phone"
      },
      {
        "japanese": "切る",
        "english": "to hang up"
      },
      {
        "japanese": "伝言",
        "english": "message"
      },
      {
        "japanese": "折り返し",
        "english": "call back"
      },
      {
        "japanese": "話し中",
        "english": "busy (line)"
      },
      {
        "japanese": "留守番電話",
        "english": "answering machine"
      },
      {
        "japanese": "間違い電話",
        "english": "wrong number"
      }
    ],
    "grammar": [
      {
        "point": "～てもいいですか",
        "explanation": "May I...? Polite request form."
      },
      {
        "point": "～んですが",
        "explanation": "Used to softly introduce a request or reason."
      }
    ],
    "examples": [
      {
        "japanese": "田中さんはいらっしゃいますか。",
        "english": "Is Mr./Ms. Tanaka there?"
      },
      {
        "japanese": "山田と申しますが、田中さんをお願いします。",
        "english": "My name is Yamada, may I speak to Tanaka?"
      },
      {
        "japanese": "すみません、今電話に出られません。",
        "english": "Sorry, I can't answer the phone right now."
      },
      {
        "japanese": "折り返しお電話いただけますか。",
        "english": "Could you call me back?"
      },
      {
        "japanese": "伝言をお願いできますか。",
        "english": "Can I leave a message?"
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "はい、田中です。",
        "english": "Yes, this is Tanaka."
      },
      {
        "speaker": "B",
        "japanese": "もしもし、山田ですが。",
        "english": "Hello, this is Yamada."
      },
      {
        "speaker": "A",
        "japanese": "あ、山田さん、こんにちは。",
        "english": "Oh, Yamada-san, hello."
      },
      {
        "speaker": "B",
        "japanese": "明日の会議について話したいんですが。",
        "english": "I wanted to talk about tomorrow's meeting."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "もしもし、田中さんは___か。",
        "answer": "いらっしゃいます"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "電話をかける",
            "english": "to make a phone call"
          },
          {
            "japanese": "電話に出る",
            "english": "to answer the phone"
          }
        ],
        "instruction": "Match the Japanese phrases with their English meanings"
      },
      {
        "type": "translation",
        "vietnamese": "Xin chào, tôi có thể nói chuyện với anh Tanaka được không?",
        "japanese": "もしもし、田中さんと話してもいいですか。"
      }
    ]
  },
  {
    "id": 22,
    "title": "Writing Emails",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "メール",
        "english": "email"
      },
      {
        "japanese": "件名",
        "english": "subject line"
      },
      {
        "japanese": "本文",
        "english": "body (of email)"
      },
      {
        "japanese": "送信する",
        "english": "to send"
      },
      {
        "japanese": "受信する",
        "english": "to receive"
      },
      {
        "japanese": "返信する",
        "english": "to reply"
      },
      {
        "japanese": "添付ファイル",
        "english": "attachment"
      },
      {
        "japanese": "宛先",
        "english": "recipient"
      },
      {
        "japanese": "CC",
        "english": "CC (carbon copy)"
      },
      {
        "japanese": "拝啓",
        "english": "Dear (formal opening)"
      }
    ],
    "grammar": [
      {
        "point": "～ていただけますか",
        "explanation": "Could you please...? Very polite request."
      },
      {
        "point": "～させていただきます",
        "explanation": "Humble form meaning 'allow me to...'."
      }
    ],
    "examples": [
      {
        "japanese": "件名：来週の打ち合わせについて",
        "english": "Subject: Regarding next week's meeting"
      },
      {
        "japanese": "お世話になっております。",
        "english": "Thank you for your continued support (standard opening)."
      },
      {
        "japanese": "資料を添付いたしました。",
        "english": "I have attached the documents."
      },
      {
        "japanese": "ご確認のほど、よろしくお願いいたします。",
        "english": "Please review it. (formal request)"
      },
      {
        "japanese": "以上、よろしくお願い申し上げます。",
        "english": "That is all, thank you. (formal closing)"
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "添付ファイルが開けません。",
        "english": "I can't open the attachment."
      },
      {
        "speaker": "B",
        "japanese": "申し訳ありません。PDF形式で再送します。",
        "english": "I'm sorry. I'll resend it as a PDF."
      },
      {
        "speaker": "A",
        "japanese": "ありがとうございます。確認します。",
        "english": "Thank you. I'll check it."
      },
      {
        "speaker": "B",
        "japanese": "何か問題があれば、またご連絡ください。",
        "english": "If you have any issues, please let me know."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "___、田中でございます。",
        "answer": "お世話になっております"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "件名",
            "english": "subject"
          },
          {
            "japanese": "添付",
            "english": "attachment"
          }
        ],
        "instruction": "Match the Japanese email terms with English"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi đã gửi email cho bạn. Bạn đã nhận được chưa?",
        "japanese": "メールを送りました。受信されましたか。"
      }
    ]
  },
  {
    "id": 23,
    "title": "At the Bank",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "銀行",
        "english": "bank"
      },
      {
        "japanese": "口座",
        "english": "account"
      },
      {
        "japanese": "預ける",
        "english": "to deposit"
      },
      {
        "japanese": "引き出す",
        "english": "to withdraw"
      },
      {
        "japanese": "振り込み",
        "english": "bank transfer"
      },
      {
        "japanese": "残高",
        "english": "balance"
      },
      {
        "japanese": "通帳",
        "english": "bank book"
      },
      {
        "japanese": "キャッシュカード",
        "english": "cash card"
      },
      {
        "japanese": "窓口",
        "english": "teller window"
      },
      {
        "japanese": "手数料",
        "english": "fee"
      }
    ],
    "grammar": [
      {
        "point": "～たいんですけど",
        "explanation": "I'd like to... (soft request pattern)."
      },
      {
        "point": "～ていただけませんか",
        "explanation": "Could you do... for me? Polite request."
      }
    ],
    "examples": [
      {
        "japanese": "口座を開きたいんですが。",
        "english": "I'd like to open an account."
      },
      {
        "japanese": "お金を預けたいです。",
        "english": "I want to deposit money."
      },
      {
        "japanese": "残高を確認してください。",
        "english": "Please check the balance."
      },
      {
        "japanese": "振り込みをお願いします。",
        "english": "I'd like to make a transfer."
      },
      {
        "japanese": "キャッシュカードをなくしました。",
        "english": "I lost my cash card."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "すみません、口座を開きたいんですが。",
        "english": "Excuse me, I'd like to open an account."
      },
      {
        "speaker": "B",
        "japanese": "かしこまりました。こちらに必要事項をご記入ください。",
        "english": "Certainly. Please fill in the necessary information here."
      },
      {
        "speaker": "A",
        "japanese": "はい。身分証明書は必要ですか。",
        "english": "Yes. Do I need identification?"
      },
      {
        "speaker": "B",
        "japanese": "パスポートか運転免許証をお願いします。",
        "english": "Your passport or driver's license, please."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "口座を___たいんですが。",
        "answer": "開き"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "預ける",
            "english": "to deposit"
          },
          {
            "japanese": "引き出す",
            "english": "to withdraw"
          }
        ],
        "instruction": "Match the Japanese verbs with their meanings"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi muốn chuyển khoản đến ngân hàng này.",
        "japanese": "この銀行に振り込みたいです。"
      }
    ]
  },
  {
    "id": 24,
    "title": "At the Post Office",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "郵便局",
        "english": "post office"
      },
      {
        "japanese": "切手",
        "english": "stamp"
      },
      {
        "japanese": "はがき",
        "english": "postcard"
      },
      {
        "japanese": "速達",
        "english": "express mail"
      },
      {
        "japanese": "書留",
        "english": "registered mail"
      },
      {
        "japanese": "小包",
        "english": "parcel"
      },
      {
        "japanese": "航空便",
        "english": "airmail"
      },
      {
        "japanese": "船便",
        "english": "surface mail"
      },
      {
        "japanese": "送料",
        "english": "shipping fee"
      },
      {
        "japanese": "追跡",
        "english": "tracking"
      }
    ],
    "grammar": [
      {
        "point": "～ていただけますか",
        "explanation": "Polite request: 'Could you...?'"
      },
      {
        "point": "～でお願いします",
        "explanation": "I'd like it by... (method)."
      }
    ],
    "examples": [
      {
        "japanese": "この手紙を航空便で送りたいです。",
        "english": "I want to send this letter by airmail."
      },
      {
        "japanese": "切手を五枚ください。",
        "english": "Please give me five stamps."
      },
      {
        "japanese": "小包を海外に送りたいんですが。",
        "english": "I'd like to send a parcel overseas."
      },
      {
        "japanese": "書留にしてください。",
        "english": "Please make it registered mail."
      },
      {
        "japanese": "追跡番号を教えてください。",
        "english": "Please tell me the tracking number."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "すみません、この小包をベトナムに送りたいです。",
        "english": "Excuse me, I'd like to send this parcel to Vietnam."
      },
      {
        "speaker": "B",
        "japanese": "航空便と船便がありますが、どちらになさいますか。",
        "english": "We have airmail and surface mail. Which would you like?"
      },
      {
        "speaker": "A",
        "japanese": "航空便でお願いします。いくらですか。",
        "english": "Airmail, please. How much is it?"
      },
      {
        "speaker": "B",
        "japanese": "二千五百円です。",
        "english": "It's 2,500 yen."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "この手紙を___で送りたいです。",
        "answer": "航空便"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "速達",
            "english": "express mail"
          },
          {
            "japanese": "書留",
            "english": "registered mail"
          }
        ],
        "instruction": "Match the Japanese mail services with English"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi muốn mua vài con tem để gửi bưu thiếp.",
        "japanese": "はがきを送るための切手を何枚か買いたいです。"
      }
    ]
  },
  {
    "id": 25,
    "title": "Renting an Apartment",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "アパート",
        "english": "apartment"
      },
      {
        "japanese": "賃貸",
        "english": "rental"
      },
      {
        "japanese": "家賃",
        "english": "rent"
      },
      {
        "japanese": "敷金",
        "english": "deposit"
      },
      {
        "japanese": "礼金",
        "english": "key money"
      },
      {
        "japanese": "契約",
        "english": "contract"
      },
      {
        "japanese": "保証人",
        "english": "guarantor"
      },
      {
        "japanese": "間取り",
        "english": "floor plan"
      },
      {
        "japanese": "駅から徒歩",
        "english": "walk from station"
      },
      {
        "japanese": "更新料",
        "english": "renewal fee"
      }
    ],
    "grammar": [
      {
        "point": "～たいんですが",
        "explanation": "I'd like to... (polite request)."
      },
      {
        "point": "～なければならない",
        "explanation": "must / have to"
      }
    ],
    "examples": [
      {
        "japanese": "駅から徒歩五分以内のアパートを探しています。",
        "english": "I'm looking for an apartment within a 5-minute walk from the station."
      },
      {
        "japanese": "家賃はいくらですか。",
        "english": "How much is the rent?"
      },
      {
        "japanese": "敷金と礼金はそれぞれ一か月分です。",
        "english": "Deposit and key money are each one month's rent."
      },
      {
        "japanese": "保証人が必要ですか。",
        "english": "Is a guarantor necessary?"
      },
      {
        "japanese": "契約期間は二年です。",
        "english": "The contract period is two years."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "このアパートの家賃はいくらですか。",
        "english": "How much is the rent for this apartment?"
      },
      {
        "speaker": "B",
        "japanese": "月額八万円です。敷金と礼金が別にかかります。",
        "english": "80,000 yen per month. Deposit and key money are separate."
      },
      {
        "speaker": "A",
        "japanese": "敷金はいくらですか。",
        "english": "How much is the deposit?"
      },
      {
        "speaker": "B",
        "japanese": "家賃一か月分です。",
        "english": "It's one month's rent."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "保証人が___。",
        "answer": "必要です"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "敷金",
            "english": "deposit"
          },
          {
            "japanese": "礼金",
            "english": "key money"
          }
        ],
        "instruction": "Match the Japanese rental terms"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi muốn tìm một căn hộ gần nhà ga.",
        "japanese": "駅の近くのアパートを探したいです。"
      }
    ]
  },
  {
    "id": 26,
    "title": "Complaints and Returns",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "苦情",
        "english": "complaint"
      },
      {
        "japanese": "返品",
        "english": "return (product)"
      },
      {
        "japanese": "交換",
        "english": "exchange"
      },
      {
        "japanese": "不良品",
        "english": "defective product"
      },
      {
        "japanese": "レシート",
        "english": "receipt"
      },
      {
        "japanese": "返金",
        "english": "refund"
      },
      {
        "japanese": "対応",
        "english": "response / handling"
      },
      {
        "japanese": "申し訳ありません",
        "english": "I'm very sorry"
      },
      {
        "japanese": "確認する",
        "english": "to check"
      },
      {
        "japanese": "交換していただけますか",
        "english": "Could you exchange it?"
      }
    ],
    "grammar": [
      {
        "point": "～ていただけますか",
        "explanation": "Could you...? Polite request."
      },
      {
        "point": "～てしまいました",
        "explanation": "I accidentally did (regretful)."
      }
    ],
    "examples": [
      {
        "japanese": "この商品は不良品です。",
        "english": "This product is defective."
      },
      {
        "japanese": "レシートをなくしてしまいました。",
        "english": "I lost the receipt."
      },
      {
        "japanese": "返金していただけますか。",
        "english": "Could you give me a refund?"
      },
      {
        "japanese": "交換してもらえますか。",
        "english": "Can I exchange it?"
      },
      {
        "japanese": "大変申し訳ございません。すぐに対応いたします。",
        "english": "We apologize sincerely. We'll handle it immediately."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "すみません、昨日買ったこのシャツ、サイズが合わないんですが。",
        "english": "Excuse me, this shirt I bought yesterday doesn't fit."
      },
      {
        "speaker": "B",
        "japanese": "レシートはお持ちですか。",
        "english": "Do you have the receipt?"
      },
      {
        "speaker": "A",
        "japanese": "はい、これです。交換できますか。",
        "english": "Yes, here it is. Can I exchange it?"
      },
      {
        "speaker": "B",
        "japanese": "かしこまりました。お好きなサイズと交換いたします。",
        "english": "Certainly. We'll exchange it for your preferred size."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "この製品は___です。",
        "answer": "不良品"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "返品",
            "english": "return"
          },
          {
            "japanese": "交換",
            "english": "exchange"
          }
        ],
        "instruction": "Match the Japanese words with English"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi muốn trả lại cái áo này vì nó bị lỗi.",
        "japanese": "このシャツは不良品なので返品したいです。"
      }
    ]
  },
  {
    "id": 27,
    "title": "Giving Detailed Directions",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "交差点",
        "english": "intersection"
      },
      {
        "japanese": "信号",
        "english": "traffic light"
      },
      {
        "japanese": "曲がる",
        "english": "to turn"
      },
      {
        "japanese": "まっすぐ",
        "english": "straight"
      },
      {
        "japanese": "～つ目の",
        "english": "the (number)th"
      },
      {
        "japanese": "角",
        "english": "corner"
      },
      {
        "japanese": "看板",
        "english": "signboard"
      },
      {
        "japanese": "目印",
        "english": "landmark"
      },
      {
        "japanese": "徒歩",
        "english": "on foot"
      },
      {
        "japanese": "～分",
        "english": "minutes"
      }
    ],
    "grammar": [
      {
        "point": "～と（条件）",
        "explanation": "If you do ~, then... (conditional)"
      },
      {
        "point": "～てから",
        "explanation": "After doing ~"
      }
    ],
    "examples": [
      {
        "japanese": "次の信号を右に曲がってください。",
        "english": "Please turn right at the next traffic light."
      },
      {
        "japanese": "まっすぐ行って、三つ目の角を左です。",
        "english": "Go straight and it's the third corner on the left."
      },
      {
        "japanese": "駅を出て、右に行くと銀行があります。",
        "english": "After leaving the station, go right and there's a bank."
      },
      {
        "japanese": "この道をまっすぐ五分歩いてください。",
        "english": "Walk straight on this road for five minutes."
      },
      {
        "japanese": "コンビニが目印です。その隣です。",
        "english": "The convenience store is the landmark. It's next to it."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "すみません、駅への道を教えてください。",
        "english": "Excuse me, could you tell me the way to the station?"
      },
      {
        "speaker": "B",
        "japanese": "この道をまっすぐ行って、最初の交差点を左に曲がってください。",
        "english": "Go straight on this road and turn left at the first intersection."
      },
      {
        "speaker": "A",
        "japanese": "左ですね。どのくらいかかりますか。",
        "english": "Left, right? How long does it take?"
      },
      {
        "speaker": "B",
        "japanese": "徒歩で十分くらいです。",
        "english": "About ten minutes on foot."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "次の___を右に曲がってください。",
        "answer": "信号"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "曲がる",
            "english": "to turn"
          },
          {
            "japanese": "まっすぐ",
            "english": "straight"
          }
        ],
        "instruction": "Match the Japanese direction words"
      },
      {
        "type": "translation",
        "vietnamese": "Đi thẳng và rẽ trái ở ngã tư thứ hai.",
        "japanese": "まっすぐ行って、二つ目の交差点を左に曲がってください。"
      }
    ]
  },
  {
    "id": 28,
    "title": "Discussing News",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "ニュース",
        "english": "news"
      },
      {
        "japanese": "記事",
        "english": "article"
      },
      {
        "japanese": "見出し",
        "english": "headline"
      },
      {
        "japanese": "話題",
        "english": "topic"
      },
      {
        "japanese": "政治",
        "english": "politics"
      },
      {
        "japanese": "経済",
        "english": "economy"
      },
      {
        "japanese": "事件",
        "english": "incident"
      },
      {
        "japanese": "報道",
        "english": "reporting"
      },
      {
        "japanese": "影響",
        "english": "influence"
      },
      {
        "japanese": "意見",
        "english": "opinion"
      }
    ],
    "grammar": [
      {
        "point": "～によると",
        "explanation": "According to ~"
      },
      {
        "point": "～らしい",
        "explanation": "It seems that ~ (hearsay/evidential)"
      }
    ],
    "examples": [
      {
        "japanese": "ニュースによると、明日は雨らしいです。",
        "english": "According to the news, it seems it will rain tomorrow."
      },
      {
        "japanese": "この事件についてどう思いますか。",
        "english": "What do you think about this incident?"
      },
      {
        "japanese": "経済のニュースはあまり詳しくないです。",
        "english": "I'm not very familiar with economic news."
      },
      {
        "japanese": "今日の見出しを見ましたか。",
        "english": "Did you see today's headlines?"
      },
      {
        "japanese": "その話題はとても重要だと思います。",
        "english": "I think that topic is very important."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "今日のニュースを見ましたか。大きな地震があったそうです。",
        "english": "Did you see today's news? There was a big earthquake, apparently."
      },
      {
        "speaker": "B",
        "japanese": "えっ、本当ですか。どこですか。",
        "english": "What? Really? Where?"
      },
      {
        "speaker": "A",
        "japanese": "北海道らしいです。",
        "english": "It seems it was in Hokkaido."
      },
      {
        "speaker": "B",
        "japanese": "それは大変ですね。被害は大きくないといいですが。",
        "english": "That's terrible. I hope the damage isn't severe."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "ニュース___、明日は雪が降るそうです。",
        "answer": "によると"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "見出し",
            "english": "headline"
          },
          {
            "japanese": "記事",
            "english": "article"
          }
        ],
        "instruction": "Match the Japanese news vocabulary"
      },
      {
        "type": "translation",
        "vietnamese": "Theo tin tức, ngày mai sẽ có mưa lớn.",
        "japanese": "ニュースによると、明日大雨が降るそうです。"
      }
    ]
  },
  {
    "id": 29,
    "title": "Cultural Differences",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "文化",
        "english": "culture"
      },
      {
        "japanese": "習慣",
        "english": "custom"
      },
      {
        "japanese": "違い",
        "english": "difference"
      },
      {
        "japanese": "マナー",
        "english": "manners"
      },
      {
        "japanese": "礼儀",
        "english": "etiquette"
      },
      {
        "japanese": "交流",
        "english": "exchange"
      },
      {
        "japanese": "理解する",
        "english": "to understand"
      },
      {
        "japanese": "驚く",
        "english": "to be surprised"
      },
      {
        "japanese": "失礼",
        "english": "rude"
      },
      {
        "japanese": "適応する",
        "english": "to adapt"
      }
    ],
    "grammar": [
      {
        "point": "～と比べて",
        "explanation": "Compared to ~"
      },
      {
        "point": "～というのは",
        "explanation": "Speaking of ~, (explanation)"
      }
    ],
    "examples": [
      {
        "japanese": "日本とベトナムでは習慣が違います。",
        "english": "Customs differ between Japan and Vietnam."
      },
      {
        "japanese": "初めての時はとても驚きました。",
        "english": "I was very surprised the first time."
      },
      {
        "japanese": "靴を脱ぐ習慣は日本の文化です。",
        "english": "The custom of taking off shoes is Japanese culture."
      },
      {
        "japanese": "ベトナムと比べて、日本は時間に厳しいです。",
        "english": "Compared to Vietnam, Japan is strict about time."
      },
      {
        "japanese": "異文化を理解するのは大切です。",
        "english": "Understanding different cultures is important."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "日本では、電車の中で電話をしないんですね。",
        "english": "In Japan, you don't make phone calls on the train, right?"
      },
      {
        "speaker": "B",
        "japanese": "そうです。マナーとして静かにするのが普通です。",
        "english": "Yes, it's common to be quiet as a manner."
      },
      {
        "speaker": "A",
        "japanese": "ベトナムではよく電話をします。それが普通です。",
        "english": "In Vietnam, we often make calls. It's normal."
      },
      {
        "speaker": "B",
        "japanese": "文化の違いですね。面白いです。",
        "english": "That's a cultural difference. Interesting."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "日本とベトナムでは___が違います。",
        "answer": "習慣"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "マナー",
            "english": "manners"
          },
          {
            "japanese": "礼儀",
            "english": "etiquette"
          }
        ],
        "instruction": "Match the Japanese words with English"
      },
      {
        "type": "translation",
        "vietnamese": "So với Việt Nam, Nhật Bản có nhiều quy tắc hơn.",
        "japanese": "ベトナムと比べて、日本はルールが多いです。"
      }
    ]
  },
  {
    "id": 30,
    "title": "Job Interviews",
    "level": "A2",
    "vocabulary": [
      {
        "japanese": "面接",
        "english": "interview"
      },
      {
        "japanese": "志望動機",
        "english": "motivation for applying"
      },
      {
        "japanese": "自己紹介",
        "english": "self-introduction"
      },
      {
        "japanese": "長所",
        "english": "strength"
      },
      {
        "japanese": "短所",
        "english": "weakness"
      },
      {
        "japanese": "経験",
        "english": "experience"
      },
      {
        "japanese": "資格",
        "english": "qualification"
      },
      {
        "japanese": "採用",
        "english": "hiring"
      },
      {
        "japanese": "応募する",
        "english": "to apply"
      },
      {
        "japanese": "履歴書",
        "english": "resume"
      }
    ],
    "grammar": [
      {
        "point": "～させていただきます",
        "explanation": "Humble form: 'I will do (for you)'."
      },
      {
        "point": "～ていただけませんか",
        "explanation": "Could you please...? (polite request in interview context)"
      }
    ],
    "examples": [
      {
        "japanese": "私の長所は責任感が強いことです。",
        "english": "My strength is a strong sense of responsibility."
      },
      {
        "japanese": "志望動機を教えてください。",
        "english": "Please tell me your motivation for applying."
      },
      {
        "japanese": "この業界での経験は一年です。",
        "english": "I have one year of experience in this industry."
      },
      {
        "japanese": "どうぞよろしくお願いいたします。",
        "english": "I look forward to working with you. (humble)"
      },
      {
        "japanese": "短所は、細かいところに気を使いすぎることです。",
        "english": "My weakness is paying too much attention to details."
      }
    ],
    "dialogue": [
      {
        "speaker": "A",
        "japanese": "自己紹介をお願いします。",
        "english": "Please introduce yourself."
      },
      {
        "speaker": "B",
        "japanese": "はい、私はベトナムから参りましたチャンと申します。",
        "english": "Yes, I'm Tran from Vietnam."
      },
      {
        "speaker": "A",
        "japanese": "なぜこの会社を志望したのですか。",
        "english": "Why did you apply to this company?"
      },
      {
        "speaker": "B",
        "japanese": "御社のグローバルな事業に魅力を感じました。",
        "english": "I was attracted to your company's global business."
      }
    ],
    "exercises": [
      {
        "type": "fill-blank",
        "question": "私の___は責任感が強いことです。",
        "answer": "長所"
      },
      {
        "type": "matching",
        "pairs": [
          {
            "japanese": "志望動機",
            "english": "motivation"
          },
          {
            "japanese": "履歴書",
            "english": "resume"
          }
        ],
        "instruction": "Match the Japanese interview terms"
      },
      {
        "type": "translation",
        "vietnamese": "Tôi muốn giới thiệu bản thân. Tôi tốt nghiệp đại học năm ngoái.",
        "japanese": "自己紹介させていただきます。去年大学を卒業しました。"
      }
    ]
  }
];

export default lessons;
