// Auto-generated by scripts/split-lessons-by-level.mjs.
// Edit the source lesson content here directly. DO NOT regenerate
// from a stale lessons.ts — the registry replaced that file.

import type { JapaneseLesson } from "./lessons";

export const lessons: JapaneseLesson[] = [
  {
    "id": 1,
    "title": "Hiragana Introduction",
    "title_vi": "Giới thiệu Hiragana",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "fa289444-1247-40ed-9e11-98d73a99e2df",
        "japanese": "あ",
        "english": "a"
      },
      {
        cell_id: "8f1694f8-feb8-4f10-849f-7a17bb99a95a",
        "japanese": "い",
        "english": "i"
      },
      {
        cell_id: "bfe79df6-466a-4ebb-a412-4c8405ec4f9b",
        "japanese": "う",
        "english": "u"
      },
      {
        cell_id: "d036aecb-ca52-4df9-8a99-cfbe2ad4f164",
        "japanese": "え",
        "english": "e"
      },
      {
        cell_id: "bcc0cf31-ef89-40db-84d8-4eaff5789039",
        "japanese": "お",
        "english": "o"
      }
    ],
    "grammar": [
      {
        "point": "Hiragana",
        "explanation": "Hiragana is the basic phonetic script used for native Japanese words and grammatical elements."
      }
    ],
    "examples": [
      {
        "japanese": "あい",
        "english": "love",
        "pronunciation_focus_en": [
          "あ → 'ah' as in 'father', short and flat — never the English 'ay'",
          "い → 'ee' as in 'see', but clipped short",
          "あい → two equal beats 'a-i', NOT the single glide in English 'eye'"
        ],
        "pronunciation_focus": [
          "あ → như âm 'a' trong tiếng Việt, ngắn và phẳng — không phải 'ây'",
          "い → như âm 'i' trong 'đi', nhưng gọn hơn",
          "あい → hai nhịp đều bằng nhau 'a-i', không lướt thành một âm"
        ]
      },
      {
        "japanese": "うえ",
        "english": "above",
        "pronunciation_focus_en": [
          "う → 'oo' as in 'food' but lips relaxed and unrounded — lighter than English 'oo'",
          "え → 'eh' as in 'bed', flat; do not let it drift toward 'ay'",
          "うえ → two even mora 'u-e', each held the same length"
        ],
        "pronunciation_focus": [
          "う → gần âm 'ư' tiếng Việt nhưng môi thả lỏng, không tròn môi như 'u'",
          "え → như âm 'ê' trong 'lê', phẳng; đừng để trượt thành 'ây'",
          "うえ → hai mora đều 'u-e', giữ độ dài bằng nhau"
        ]
      },
      {
        "japanese": "えいご",
        "english": "English language",
        "pronunciation_focus_en": [
          "え → 'eh' as in 'bed'",
          "えい → a long 'eh' held two beats here, not 'ay' as in 'day'",
          "ご → hard 'g' as in 'go' (g is always hard in Japanese) + short 'oh'"
        ],
        "pronunciation_focus": [
          "え → như âm 'ê' trong 'lê'",
          "えい → giữ âm 'ê' kéo dài hai nhịp, không phải 'ây'",
          "ご → 'g' cứng như trong 'gà' (g tiếng Nhật luôn cứng) + 'ô' ngắn"
        ]
      }
    ],
    "cultural_notes_en": "Japanese writes with three scripts at once — hiragana, katakana, and kanji — and one ordinary sentence routinely uses all three. There is no real American parallel; the nearest is mixing print, italics, and numerals, and that still understates it. Hiragana is the phonetic backbone: ~46 basic characters, each a fixed sound, learned first because it spells grammar and any word not written in kanji. Unlike English letters, a hiragana character never changes its sound — あ is always 'a' as in 'father,' anywhere it appears, which makes Japanese reading far more predictable than English spelling (compare English 'a' in 'cat / car / care / about'). The five vowels あいうえお are the foundation of the whole system: every other kana is a consonant fused onto one of these five, so locking them in now pays off for the entire language. Children's books and learner signage are written largely in hiragana, so this one script already unlocks a surprising amount.",
    "cultural_notes_vi": "Tiếng Nhật viết bằng BA hệ chữ cùng lúc — hiragana, katakana và kanji — một câu bình thường thường dùng cả ba. Tiếng Việt chỉ có một bộ chữ Latin nên đây là điều hoàn toàn mới với người Việt: hãy hình dung như trộn lẫn chữ thường, chữ in nghiêng và chữ Hán trong cùng một câu. Hiragana là xương sống ngữ âm: khoảng 46 ký tự cơ bản, mỗi ký tự một âm CỐ ĐỊNH, học trước tiên vì nó dùng để viết ngữ pháp và mọi từ không viết bằng kanji. Khác với tiếng Việt (chữ \"a\" trong \"ăn\", \"ay\", \"âu\" đọc khác nhau), một ký tự hiragana KHÔNG BAO GIỜ đổi âm — あ luôn là \"a\" ở mọi vị trí, nên đọc tiếng Nhật dễ đoán hơn nhiều. Năm nguyên âm あいうえお là nền tảng của cả hệ thống: mọi kana khác đều là một phụ âm ghép vào một trong năm nguyên âm này. Sách thiếu nhi và biển báo cho người mới học chủ yếu viết bằng hiragana.",
    "tip_advice_en": "Highest-leverage habit: treat the five vowels as pure and constant — they never glide. Japanese あ/い/う/え/お are 'ah/ee/oo/eh/oh,' and crucially they do NOT diphthongize the way English stressed vowels do (English 'o' drifts to 'ow,' long 'a' to 'ay-ee'). Say え as a flat, short 'eh' and stop — don't let it slide toward 'ay.' う is lighter and less rounded than English 'oo'; relax the lips. When two vowels sit together (あい, うえ, えいご) give each its own equal beat — Japanese is mora-timed, so あい is two even beats 'a-i,' not the single English glide in 'eye.' Drill: clap once per mora — え-い-ご, three claps, three even sounds. Lock the evenness in now; this same mora timing governs long vowels and double consonants for the rest of the language.",
    "tip_advice_vi": "Thói quen quan trọng nhất: coi năm nguyên âm là âm THUẦN và KHÔNG ĐỔI — chúng không bao giờ trượt âm. あ/い/う/え/お đọc là \"a/i/ư/ê/ô\" ngắn, gọn, phẳng. Người Việt có lợi thế: tiếng Việt vốn đã đọc từng âm rõ ràng, nên đừng kéo dài hay uốn âm theo kiểu tiếng Anh. え đọc \"ê\" ngắn và dừng lại — đừng cho trượt thành \"ây\". う nhẹ và môi không tròn như \"u\" tiếng Việt, để môi thả lỏng. Khi hai nguyên âm đứng cạnh nhau (あい, うえ, えいご) hãy cho MỖI âm một nhịp đều bằng nhau — tiếng Nhật tính theo \"mora\": あい là hai nhịp \"a-i\", không phải một âm lướt. Bài tập: vỗ tay một cái mỗi mora — え-い-ご, ba cái vỗ, ba âm đều nhau. Nhịp đều này sẽ chi phối nguyên âm dài và phụ âm đôi về sau."
  },
  {
    "id": 2,
    "title": "Katakana Introduction",
    "title_vi": "Giới thiệu Katakana",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "68cc0a07-e74c-4fa7-94cf-ecfefc657dfe",
        "japanese": "カ",
        "english": "ka"
      },
      {
        cell_id: "07c64ab3-a108-4884-9427-2cbab41900f8",
        "japanese": "キ",
        "english": "ki"
      },
      {
        cell_id: "9eb5c3a4-c8be-4814-8286-7c0a89c06ddc",
        "japanese": "ク",
        "english": "ku"
      },
      {
        cell_id: "f8c8af8c-997e-46a3-a020-8dad987f6c3d",
        "japanese": "ケ",
        "english": "ke"
      },
      {
        cell_id: "d11f9cef-821e-4000-8a98-a880ec06cc4e",
        "japanese": "コ",
        "english": "ko"
      }
    ],
    "grammar": [
      {
        "point": "Katakana",
        "explanation": "Katakana is used for foreign loanwords, onomatopoeia, and emphasis."
      }
    ],
    "examples": [
      {
        "japanese": "カメラ",
        "english": "camera",
        "pronunciation_focus_en": [
          "カ → 'ka' as in 'car', hard k, short 'ah'",
          "メ → 'meh' as in 'met'",
          "ラ → a light tapped 'r', between English 'r' and 'd' (like the fast 'tt' in American 'butter')",
          "カメラ → three even beats, no stressed syllable (not 'CA-me-ra')"
        ],
        "pronunciation_focus": [
          "カ → 'ka' như trong 'cá', k cứng, 'a' ngắn",
          "メ → 'mê' như trong 'mê'",
          "ラ → 'r' búng lưỡi nhẹ, nằm giữa 'r' và 'đ' của tiếng Việt — không rung mạnh",
          "カメラ → ba nhịp đều, không nhấn âm nào ('CA-me-ra' là sai)"
        ]
      },
      {
        "japanese": "コーヒー",
        "english": "coffee",
        "pronunciation_focus_en": [
          "コ → 'ko', short 'oh'",
          "コー → the ー is a length mark, not a letter: hold the 'oh' two beats",
          "ヒ → 'hi' as in 'he', breathy",
          "ヒー → hold 'ee' two beats; コーヒー is four beats ko-o-hi-i, not two-syllable 'CAW-fee'"
        ],
        "pronunciation_focus": [
          "コ → 'kô', 'ô' ngắn",
          "コー → dấu ー là dấu kéo dài, không phải chữ cái: giữ 'ô' hai nhịp",
          "ヒ → 'hi' như trong 'hi vọng', hơi thoát ra",
          "ヒー → giữ 'i' hai nhịp; コーヒー là bốn nhịp kô-ô-hi-i, không phải hai âm"
        ]
      },
      {
        "japanese": "アメリカ",
        "english": "America",
        "pronunciation_focus_en": [
          "ア → 'ah' as in 'father'",
          "メ → 'meh' as in 'met'",
          "リ → light tapped 'r' + 'ee'",
          "アメリカ → four flat even beats a-me-ri-ka; no stressed syllable, unlike English 'a-MER-i-ca'"
        ],
        "pronunciation_focus": [
          "ア → âm 'a' phẳng như trong tiếng Việt",
          "メ → 'mê' như trong 'mê'",
          "リ → 'r' búng lưỡi nhẹ + 'i'",
          "アメリカ → bốn nhịp phẳng đều a-mê-ri-ka; không nhấn âm nào"
        ]
      }
    ],
    "cultural_notes_en": "Katakana is the second phonetic script — the same sound inventory as hiragana but a sharper, more angular set of characters. Functionally it works like italics or ALL CAPS in English: it flags a word as foreign, technical, onomatopoeic, or emphasized. The payoff for an English speaker is immediate and motivating: a huge share of katakana words are borrowed from English, so once you can sound out the script you can already read コーヒー (coffee), カメラ (camera), テレビ (TV), コンピューター (computer), and アメリカ (America) with no new vocabulary. The catch is that loanwords are remodeled to Japanese sound rules — every consonant gets a vowel, English v/l/r collapse, and word stress disappears — so マクドナルド ('Makudonarudo') is McDonald's only once you stop expecting English rhythm. Brand names, menus, and tech terms lean heavily on katakana, which makes this script disproportionately useful from day one in a Japanese city. Think of it like reading words you already know in a thick, regular accent: the meaning is there once you drop the English stress pattern.",
    "cultural_notes_vi": "Katakana là hệ chữ ngữ âm thứ hai — cùng bộ âm với hiragana nhưng nét sắc và gãy góc hơn. Vai trò của nó như chữ in nghiêng hay CHỮ HOA: đánh dấu một từ là ngoại lai, kỹ thuật, tượng thanh hoặc nhấn mạnh. Lợi thế lớn: phần lớn từ katakana mượn từ tiếng Anh, mà người Việt nay đa số biết ít tiếng Anh, nên đánh vần được là đọc ngay コーヒー (cà phê), カメラ (máy ảnh), テレビ (ti vi), アメリカ (nước Mỹ) mà không cần học từ mới. Cái bẫy: từ mượn bị nắn lại theo luật âm tiếng Nhật — mỗi phụ âm phải kèm một nguyên âm, không còn trọng âm — nên マクドナルド là \"McDonald's\" chỉ khi bạn thôi mong nó đọc theo kiểu tiếng Anh. Tên hãng, thực đơn, từ công nghệ dùng katakana rất nhiều, nên hệ chữ này cực kỳ hữu dụng ngay từ ngày đầu ở Nhật.",
    "tip_advice_en": "Highest-leverage habit: don't read katakana as English — read it as even Japanese mora and the English word surfaces. Each katakana is a consonant+vowel beat, so コーヒー is four beats, ko-o-hi-i, where ー doubles the previous vowel. That long-vowel bar is the single biggest katakana trap for English speakers: ビル (biru, building) vs ビール (bīru, beer) differ ONLY by that held vowel — a genuine ordering mistake waiting to happen. Drill: read アメリカ as four flat even beats 'a-me-ri-ka,' not English 'a-MER-i-ca' — Japanese has no English-style stress accent, so deliberately flatten it. Train your eye to spot ー and physically hold the vowel; mora length carries meaning here, exactly as in Lesson 1.",
    "tip_advice_vi": "Thói quen quan trọng nhất: đừng đọc katakana theo kiểu tiếng Anh — đọc thành các mora đều của tiếng Nhật thì từ gốc tự hiện ra. Mỗi katakana là một nhịp phụ âm + nguyên âm, nên コーヒー là bốn nhịp kô-ô-hi-i, dấu ー nhân đôi nguyên âm trước. Dấu kéo dài này là bẫy lớn nhất của katakana: ビル (biru, tòa nhà) và ビール (bīru, bia) chỉ khác nhau ở nguyên âm giữ dài — gọi nhầm là chuyện thật. Bài tập: đọc アメリカ thành bốn nhịp phẳng đều \"a-mê-ri-ka\", tiếng Nhật không có trọng âm nên cố ý làm phẳng. Tập mắt nhìn ra dấu ー và giữ nguyên âm dài; độ dài mora mang nghĩa, đúng như Bài 1."
  },
  {
    "id": 3,
    "title": "Basic Greetings",
    "title_vi": "Lời chào cơ bản",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "daaae015-3a04-4ee1-a818-e01923a104ff",
        "japanese": "こんにちは",
        "english": "hello / good afternoon"
      },
      {
        cell_id: "f12e1a87-e124-4cc1-9cce-189df2195e87",
        "japanese": "おはようございます",
        "english": "good morning"
      },
      {
        cell_id: "9f5bb080-f8aa-41a8-9b6c-ff05e288493b",
        "japanese": "こんばんは",
        "english": "good evening"
      },
      {
        cell_id: "fc96c5a4-7836-4367-a4d9-d0252c08e383",
        "japanese": "さようなら",
        "english": "goodbye"
      },
      {
        cell_id: "69168fe9-e83c-45b9-a1ba-282fbf42436a",
        "japanese": "ありがとうございます",
        "english": "thank you"
      }
    ],
    "grammar": [
      {
        "point": "Greeting time frames",
        "explanation": "Use おはようございます until around 10 AM, こんにちは in the afternoon, こんばんは in the evening."
      }
    ],
    "examples": [
      {
        "japanese": "こんにちは、元気ですか？",
        "english": "Hello, how are you?",
        "pronunciation_focus_en": [
          "こんにちは → 'kon-ni-chi-wa'; the final は is the topic particle, pronounced 'wa', NEVER 'ha'",
          "元気 (げんき) → 'gen-ki', hard g, two even beats",
          "ですか → 'des-ka'; the う in です is devoiced — say 'des', not 'deh-soo'",
          "let the pitch rise only on the final か to mark the question; keep everything before it flat"
        ],
        "pronunciation_focus": [
          "こんにちは → 'kon-ni-chi-wa'; chữ は cuối là trợ từ chủ đề, đọc 'wa', KHÔNG BAO GIỜ 'ha'",
          "元気 (げんき) → 'gen-ki', g cứng như 'gà', hai nhịp đều",
          "ですか → 'des-ka'; âm う trong です bị lướt — đọc 'des', không phải 'đê-su'",
          "chỉ lên giọng ở か cuối để hỏi; phần trước giữ phẳng"
        ]
      },
      {
        "japanese": "ありがとうございます、お元気で。",
        "english": "Thank you, take care.",
        "pronunciation_focus_en": [
          "ありがとう → 'a-ri-ga-to-o', five even mora; final とう is a long 'oh', not 'tow'",
          "ございます → 'go-za-i-mas'; final す devoiced to a soft 's', not 'moss'",
          "お元気で → 'o-gen-ki-de'; the お is a polite prefix, kept light",
          "で → short flat 'deh', the particle that closes this fixed farewell"
        ],
        "pronunciation_focus": [
          "ありがとう → 'a-ri-ga-tô-ô', năm mora đều; cuối とう là 'ô' kéo dài",
          "ございます → 'go-za-i-mas'; す cuối lướt thành 's' nhẹ",
          "お元気で → 'o-gen-ki-de'; お là tiền tố lịch sự, đọc nhẹ",
          "で → 'đê' ngắn phẳng, trợ từ khép lại câu chào tạm biệt cố định này"
        ]
      }
    ],
    "cultural_notes_en": "Greetings in Japan ride on a bow, not a handshake and emphatically not a hug — an American-style hug, or even a hand on the shoulder, reads as startling intimacy with someone you have just met. The everyday version is a small head-nod and it is genuinely expected; you do not need a deep formal bow for a casual hello. The greetings are time-boxed more strictly than English: おはようございます until roughly 10–11 a.m., こんにちは midday to dusk, こんばんは after dark. Two things surprise English speakers. First, こんにちは and こんばんは are sentence fragments ('as for today… / this evening…'), so they are greetings only — never a bedtime 'good night' (that is おやすみなさい). Second, the ございます on おはようございます is a politeness layer, so close friends clip it to plain おはよう, much as Americans drop 'good' and just say 'morning.' さようなら is heavier and more final than English 'goodbye' — for everyday partings Japanese speakers say じゃあ ('well then…') or またね ('see you'); さようなら to a coworker you'll see in an hour sounds oddly dramatic. Well-being sign-offs like お元気で ('keep well') are routine, reflecting a culture that builds health and season into ordinary phatic speech.",
    "cultural_notes_vi": "Chào ở Nhật đi kèm cái cúi đầu, không bắt tay và tuyệt đối không ôm. Người Việt vốn cũng ít ôm người lạ, nhưng ở đây cả vỗ vai cũng bị coi là suồng sã với người mới gặp. Kiểu thường ngày chỉ là gật đầu nhẹ và điều đó được mong đợi thật sự; chào xã giao không cần cúi sâu trang trọng. Lời chào bị đóng khung theo giờ chặt hơn tiếng Việt: おはようございます đến khoảng 10–11 giờ sáng, こんにちは giữa trưa đến chạng vạng, こんばんは sau khi tối. Hai điều cần nhớ: こんにちは và こんばんは là câu cụt (\"về hôm nay… / tối nay…\"), chỉ để chào — không bao giờ dùng làm \"chúc ngủ ngon\" (đó là おやすみなさい). Và ございます trong おはようございます là lớp lịch sự, nên bạn thân rút gọn thành おはよう. さようなら nặng và dứt khoát hơn \"tạm biệt\" — chia tay thường ngày người Nhật nói じゃあ hoặc またね; nói さようなら với đồng nghiệp lát nữa gặp lại nghe kịch tính lạ.",
    "tip_advice_en": "Highest-leverage fact: は in こんにちは is pronounced 'wa,' not 'ha.' This is your first meeting with Japanese's single biggest beginner trap — the topic particle は — frozen inside a fixed greeting. こんにちは = 'kon-ni-chi-wa'; こんばんは = 'kon-ban-wa.' Pronounce the 'ha' and you mark yourself instantly as someone who has never heard the word spoken. Second watch-point: long vowels carry meaning — おはよう ends in a held 'oh' (o-ha-yo-o) and さようなら has a long 'oh' (sa-yo-o-na-ra); clipping them sounds abrupt. ございます is 'go-za-i-mas' with a devoiced final す, almost a whispered 's.' Drill the greetings aloud while giving a small head-nod on each; pairing the bow with the sound now builds the motor habit before you need it live.",
    "tip_advice_vi": "Điều quan trọng nhất: は trong こんにちは đọc là \"wa\", không phải \"ha\". Đây là lần đầu bạn gặp cái bẫy lớn nhất của người mới — trợ từ chủ đề は — nằm cứng trong lời chào. こんにちは = \"kon-ni-chi-wa\"; こんばんは = \"kon-ban-wa\". Đọc \"ha\" là lộ ngay chưa từng nghe ai nói từ này. Điểm thứ hai: nguyên âm dài mang nghĩa — おはよう kết bằng \"ô\" giữ dài (o-ha-yô-ô) và さようなら có \"ô\" dài (sa-yô-ô-na-ra); cắt ngắn nghe cộc lốc. ございます đọc \"go-za-i-mas\", す cuối lướt gần như thì thầm. Tập chào to thành tiếng kèm gật đầu nhẹ mỗi câu; ghép cái cúi với âm thanh ngay bây giờ để thành phản xạ trước khi cần dùng thật."
  },
  {
    "id": 4,
    "title": "Self Introduction",
    "title_vi": "Tự giới thiệu bản thân",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "eadcb38f-1133-467e-8708-b3cd2ad120d6",
        "japanese": "わたし",
        "english": "I"
      },
      {
        cell_id: "0c1d06be-0a9e-4da5-940c-031f89d80553",
        "japanese": "名前 (なまえ)",
        "english": "name"
      },
      {
        cell_id: "7b9e4a55-0680-4e3f-b20a-32a4cd20165b",
        "japanese": "出身 (しゅっしん)",
        "english": "hometown / origin"
      },
      {
        cell_id: "1b0b204e-5478-4b62-bc5b-550680815aaf",
        "japanese": "～です",
        "english": "am / is / are"
      }
    ],
    "grammar": [
      {
        "point": "です (desu)",
        "explanation": "です is a polite copula used to equate two nouns: A is B."
      }
    ],
    "examples": [
      {
        "japanese": "わたしは田中です。",
        "english": "I am Tanaka.",
        "pronunciation_focus_en": [
          "わたし → 'wa-ta-shi', three flat even beats; the final し is 'shi', not 'see'",
          "は → here the topic particle: pronounced 'wa', not 'ha' (same rule as こんにちは)",
          "田中 (たなか) → 'ta-na-ka', evenly weighted; a surname — Japanese gives family name first",
          "です → 'des', devoiced final vowel; do not say 'deh-soo'"
        ],
        "pronunciation_focus": [
          "わたし → 'wa-ta-shi', ba nhịp phẳng đều; し cuối là 'shi', không phải 'si'",
          "は → đây là trợ từ chủ đề: đọc 'wa', không phải 'ha' (cùng luật với こんにちは)",
          "田中 (たなか) → 'ta-na-ka', đều nhau; là họ — tiếng Nhật đặt họ trước tên",
          "です → 'des', nguyên âm cuối lướt; đừng đọc 'đê-su'"
        ]
      },
      {
        "japanese": "出身は東京です。",
        "english": "I am from Tokyo.",
        "pronunciation_focus_en": [
          "出身 (しゅっしん) → 'shu(s)-shin'; the small っ is a held beat of silence — a full mora, not skipped",
          "は → topic particle 'wa'",
          "東京 (とうきょう) → 'to-o-kyo-o', four beats — BOTH long vowels held; 'TOH-kee-oh' is wrong",
          "です → 'des'"
        ],
        "pronunciation_focus": [
          "出身 (しゅっしん) → 'shu(s)-shin'; chữ っ nhỏ là một nhịp ngừng lặng — một mora đầy đủ, không bỏ qua",
          "は → trợ từ chủ đề 'wa'",
          "東京 (とうきょう) → 'tô-ô-kyô-ô', bốn nhịp — giữ CẢ HAI nguyên âm dài; đọc 'Tô-ki-ô' là sai",
          "です → 'des'"
        ]
      }
    ],
    "cultural_notes_en": "This lesson introduces the structural heart of Japanese, and the gap from English is large. Word order is subject–object–verb, with the verb (or です) last — 'I Tanaka am,' not 'I am Tanaka.' Names run family-name-first (田中 is the surname), the reverse of American order, and in real life a Japanese person introducing themselves usually gives only the surname. Crucially, さん is an honorific you attach to OTHER people's names (田中さん) and never to your own — calling yourself 'Tanaka-san' is like an American saying 'I'm Mr. Smith' to a peer: it lands as either a joke or arrogance. The topic particle は (written with the hiragana for 'ha' but read 'wa') marks what the sentence is about; English has no equivalent, so learners over-translate it as 'is.' です is a polite copula roughly equal to 'am/is/are,' but its real job is signaling politeness, which is why A1 lives almost entirely in the です/ます polite register — the casual plain form exists but is socially risky for a learner and is deferred. American comparison: think of です as closer to the deference baked into 'sir/ma'am' than to a neutral verb 'to be.'",
    "cultural_notes_vi": "Bài này giới thiệu trái tim cấu trúc của tiếng Nhật, và khoảng cách với tiếng Việt rất lớn. Trật tự là chủ–tân–động, động từ (hay です) đứng cuối — \"Tôi Tanaka là\", không phải \"Tôi là Tanaka\". Người Việt cũng đặt họ trước tên, nên 田中 là họ thì quen — nhưng khi tự giới thiệu người Nhật thường chỉ nói họ. Quan trọng: さん là kính ngữ gắn vào tên NGƯỜI KHÁC (田中さん), không bao giờ gắn vào tên mình — tự gọi \"Tanaka-san\" giống như tự xưng \"ông Tanaka\" với người ngang hàng: nghe như đùa hoặc kiêu. Trợ từ chủ đề は (viết bằng kana \"ha\" nhưng đọc \"wa\") đánh dấu câu nói VỀ cái gì; tiếng Việt không có thứ tương đương nên người học hay dịch nhầm thành \"là\". です là hệ từ lịch sự gần với \"là\", nhưng nhiệm vụ thật của nó là báo hiệu sự lịch sự — vì vậy A1 gần như sống hoàn toàn trong văn phong lịch sự です/ます; thể suồng sã có tồn tại nhưng rủi ro xã hội cho người học nên để sau.",
    "tip_advice_en": "Highest-leverage point of the whole level: は is the topic marker and it is pronounced 'wa.' Lock in the template 'X は Y です' = 'as for X, it is Y' and you can already self-introduce, state your origin, and describe things. Do not hunt for a word-by-word English match — は has no English word; treat 'X は' as 'speaking of X.' Pronunciation watch-points: the small っ in 出身 (しゅっしん) is a real silent beat — pause on it, because しゅしん and しゅっしん are different words elsewhere; and 東京 is four held beats (to-o-kyo-o), a classic place where English speakers crush a long vowel and say 'Tokyo' in two. Drill aloud: わたしは [your name] です — five-plus even beats, は as 'wa,' です as 'des.'",
    "tip_advice_vi": "Điểm quan trọng nhất của cả cấp độ: は là trợ từ chủ đề và đọc là \"wa\". Khóa chặt mẫu \"X は Y です\" = \"nói về X, nó là Y\" là bạn đã tự giới thiệu, nói quê quán và mô tả được rồi. Đừng tìm từ tiếng Việt dịch sát từng chữ — は không có từ tương đương; hãy hiểu \"X は\" là \"nói về X\". Điểm phát âm: chữ っ nhỏ trong 出身 (しゅっしん) là một nhịp ngừng lặng thật — phải ngừng, vì ở chỗ khác しゅしん và しゅっしん là hai từ khác nhau; và 東京 là bốn nhịp giữ dài (tô-ô-kyô-ô), chỗ người mới hay nuốt nguyên âm dài thành \"Tô-ki-ô\". Tập đọc to: わたしは [tên bạn] です — năm nhịp trở lên đều nhau, は đọc \"wa\", です đọc \"des\"."
  },
  {
    "id": 5,
    "title": "Numbers 1–10",
    "title_vi": "Số đếm từ 1 đến 10",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "e83eb16d-6c7e-4a02-bbca-2d397169b382",
        "japanese": "いち",
        "english": "1"
      },
      {
        cell_id: "42a98d70-d480-4c46-934b-3bad8c4abcb7",
        "japanese": "に",
        "english": "2"
      },
      {
        cell_id: "4ce7600a-8b3d-41ce-ab42-bb35cc3a37ac",
        "japanese": "さん",
        "english": "3"
      },
      {
        cell_id: "89ca025a-dc9d-4558-84a0-539952154129",
        "japanese": "し / よん",
        "english": "4"
      },
      {
        cell_id: "22d7102a-b85c-409a-b095-5ad809186e58",
        "japanese": "ご",
        "english": "5"
      },
      {
        cell_id: "76d8d2e2-17f5-40d6-ab6d-18b237809542",
        "japanese": "ろく",
        "english": "6"
      },
      {
        cell_id: "e5d2e943-b8c0-43ff-ae4b-13d63f758ed8",
        "japanese": "しち / なな",
        "english": "7"
      },
      {
        cell_id: "88b5731e-8ccc-458c-bb1a-8e8513e16bdb",
        "japanese": "はち",
        "english": "8"
      },
      {
        cell_id: "e2a564ac-1224-486b-b0bb-33a919d7c12b",
        "japanese": "きゅう / く",
        "english": "9"
      },
      {
        cell_id: "c7c05eca-04da-4b41-bf84-82abccd7f265",
        "japanese": "じゅう",
        "english": "10"
      }
    ],
    "grammar": [
      {
        "point": "Number variations",
        "explanation": "4 can be ‘し’ or ‘よん’, 7 can be ‘しち’ or ‘なな’, 9 can be ‘きゅう’ or ‘く’. よん and なな are more common in modern speech."
      }
    ],
    "examples": [
      {
        "japanese": "りんごが三つあります。",
        "english": "There are three apples.",
        "pronunciation_focus_en": [
          "りんご → 'rin-go', tapped r; the ん is its own beat (a moraic 'n')",
          "が → subject particle, hard 'g' as in 'go' — say 'ga', not 'gha'",
          "三つ (みっつ) → 'mi(t)-tsu'; the small っ doubles the t and is a held beat — みつ ≠ みっつ",
          "あります → 'a-ri-mas', final す devoiced ('-mas', not '-masu')"
        ],
        "pronunciation_focus": [
          "りんご → 'rin-go', r búng lưỡi; ん là một nhịp riêng (n thành mora)",
          "が → trợ từ chủ ngữ, 'g' cứng như 'gà' — đọc 'ga'",
          "三つ (みっつ) → 'mi(t)-tsu'; chữ っ nhỏ nhân đôi t và là một nhịp giữ — みつ ≠ みっつ",
          "あります → 'a-ri-mas', す cuối lướt ('-mas', không phải '-ma-su')"
        ]
      },
      {
        "japanese": "今、四時です。",
        "english": "It is 4 o'clock now.",
        "pronunciation_focus_en": [
          "今 (いま) → 'i-ma', two flat even beats",
          "四時 → read 'yo-ji' (4 o'clock); the '4' here is よ, NOT し or よん — an irregular counter reading",
          "じ → soft 'j' as in 'jeep' + short 'i'",
          "です → 'des', devoiced final vowel"
        ],
        "pronunciation_focus": [
          "今 (いま) → 'i-ma', hai nhịp phẳng đều",
          "四時 → đọc 'yo-ji' (4 giờ); số '4' ở đây là よ, KHÔNG phải し hay よん — cách đọc bất quy tắc",
          "じ → 'j' mềm như trong 'jazz' + 'i' ngắn",
          "です → 'des', nguyên âm cuối lướt"
        ]
      }
    ],
    "cultural_notes_en": "Number-sound superstition runs through Japanese life much as it does in China, and the mechanism is the same: homophones. 四 (four) can be read し, which is identical to 死 ('death'), and 九 (nine) can be read く, a homophone of 苦 ('suffering'). The cultural result is concrete: hospital room and floor numbering frequently skips 4 (and sometimes 9), gift sets avoid quantities of four, and speakers actively prefer the alternate readings よん (4) and きゅう (9) to dodge the unlucky sound — exactly why this lesson lists both readings. Compare the American hotel that has no 13th floor; here it is the 4 that vanishes. Counting on the hand also differs from the American style: Japanese typically starts from an open palm and folds fingers IN for 1–5, then unfolds for 6–10. And numbers almost never travel alone — Japanese attaches a counter word to whatever is being counted (covered next lesson), so 'three apples' is not 'three + apple' but a number-plus-counter unit. Dates and prices, like Chinese, run large-to-small.",
    "cultural_notes_vi": "Kiêng số theo âm chạy suốt đời sống Nhật, giống hệt văn hóa Việt kiêng số qua âm đọc. Cơ chế là từ đồng âm: 四 (bốn) đọc し, trùng âm với 死 (\"chết\"), và 九 (chín) đọc く, đồng âm với 苦 (\"khổ\"). Hệ quả rất cụ thể: số phòng và tầng bệnh viện thường bỏ số 4 (đôi khi cả 9) — giống ta kiêng tầng/phòng số xui — bộ quà tránh số bốn, và người ta chủ động dùng cách đọc thay thế よん (4), きゅう (9) để né âm xui, đó chính là lý do bài này liệt kê cả hai cách đọc. Đếm bằng tay cũng khác: người Nhật thường mở bàn tay rồi GẬP ngón vào cho 1–5, sau đó duỗi ra cho 6–10. Và số gần như không đứng một mình — tiếng Nhật gắn một từ đếm vào vật được đếm (bài sau), nên \"ba quả táo\" không phải \"ba + táo\" mà là cụm số-cộng-từ-đếm. Ngày tháng và giá tiền, như tiếng Trung, đọc từ lớn đến nhỏ.",
    "tip_advice_en": "Highest-leverage warning: several Japanese numbers have two readings, and which one you use is not free — it is fixed by context, especially by the counter that follows. 4 is し OR よん, 7 is しち OR なな, 9 is きゅう OR く; よん/なな/きゅう dominate modern speech, but 4 o'clock is irregularly よじ (yo-ji), not し-じ or よん-じ. Do not try to systematize this today — just expect that 'four' will not always sound like the 'shi' you first learned. Pronunciation watch-point: いち and ろく end in vowels that devoice or clip before some counters (いっぷん, ろっぷん), so the clean dictionary form is not always what you hear. Drill 1–10 aloud twice, once with し/しち/く and once with よん/なな/きゅう, so both are familiar when a counter forces one.",
    "tip_advice_vi": "Cảnh báo quan trọng nhất: vài số tiếng Nhật có hai cách đọc, và dùng cách nào không tùy ý — bị quy định bởi ngữ cảnh, nhất là từ đếm đi sau. 4 là し HOẶC よん, 7 là しち HOẶC なな, 9 là きゅう HOẶC く; よん/なな/きゅう chiếm ưu thế trong nói hiện đại, nhưng 4 giờ đọc bất quy tắc là よじ (yo-ji), không phải し-じ hay よん-じ. Đừng cố hệ thống hóa hôm nay — chỉ cần biết \"bốn\" không phải lúc nào cũng nghe như \"shi\" bạn học đầu tiên. Điểm phát âm: いち và ろく có nguyên âm cuối lướt hoặc cắt trước vài từ đếm (いっぷん, ろっぷん), nên dạng từ điển không phải lúc nào cũng là cái bạn nghe. Tập đọc 1–10 hai lượt, một lượt với し/しち/く và một lượt với よん/なな/きゅう."
  },
  {
    "id": 6,
    "title": "Counting Objects",
    "title_vi": "Đếm đồ vật",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "e663126e-af51-45f7-be1a-ac3376aaa0e4",
        "japanese": "一つ (ひとつ)",
        "english": "one (general counter)"
      },
      {
        cell_id: "25f96287-8ce2-4c29-b067-d4813f07919c",
        "japanese": "二つ (ふたつ)",
        "english": "two"
      },
      {
        cell_id: "9c411042-8c91-4bfe-b7c0-46ffbc9debfe",
        "japanese": "三つ (みっつ)",
        "english": "three"
      },
      {
        cell_id: "54799cee-21b8-4b17-bf0f-04122feef7aa",
        "japanese": "人 (ひと)",
        "english": "person"
      },
      {
        cell_id: "aaa8b7d3-98d8-409c-912f-5f838d691875",
        "japanese": "〜人 (〜にん)",
        "english": "counter for people"
      }
    ],
    "grammar": [
      {
        "point": "Japanese counters",
        "explanation": "Japanese uses different counters for objects, people, animals, etc. つ is for general small objects; 人 is for people."
      }
    ],
    "examples": [
      {
        "japanese": "本が一冊あります。",
        "english": "There is one book.",
        "pronunciation_focus_en": [
          "本 (ほん) → 'hon'; the ん is its own beat (moraic n)",
          "が → subject particle, hard 'g' ('ga')",
          "一冊 (いっさつ) → 'i(s)-sa-tsu'; small っ = held silent beat, then the book-counter 冊 さつ",
          "あります → 'a-ri-mas', final す devoiced (used for inanimate things)"
        ],
        "pronunciation_focus": [
          "本 (ほん) → 'hon'; ん là một nhịp riêng (n thành mora)",
          "が → trợ từ chủ ngữ, 'g' cứng ('ga' như 'gà')",
          "一冊 (いっさつ) → 'i(s)-sa-tsu'; っ nhỏ = nhịp ngừng lặng, rồi từ đếm sách 冊 さつ",
          "あります → 'a-ri-mas', す cuối lướt (dùng cho vật vô tri)"
        ]
      },
      {
        "japanese": "友達が二人います。",
        "english": "I have two friends.",
        "pronunciation_focus_en": [
          "友達 (ともだち) → 'to-mo-da-chi', four flat even beats",
          "二人 → read 'fu-ta-ri' (two people) — an IRREGULAR people-counter reading, not に-にん",
          "います → 'i-mas' (used for people/animate beings, vs あります for things)",
          "に in にん vs ふたり → note 一人/二人 are ひとり/ふたり, then 三人 onward is regular さん-にん"
        ],
        "pronunciation_focus": [
          "友達 (ともだち) → 'to-mo-da-chi', bốn nhịp phẳng đều",
          "二人 → đọc 'fu-ta-ri' (hai người) — cách đọc từ đếm người BẤT QUY TẮC, không phải に-にん",
          "います → 'i-mas' (dùng cho người/sinh vật, khác あります cho vật)",
          "にん vs ふたり → 一人/二人 là ひとり/ふたり, từ 三人 trở đi mới đều: さん-にん"
        ]
      }
    ],
    "cultural_notes_en": "Japanese cannot usually count a noun bare: a number takes a counter word matched to the thing's shape or category — つ for general objects, 人 (にん) for people, 冊 (さつ) for bound volumes, 本 (ほん) for long thin things, 枚 (まい) for flat thin things, 匹 (ひき) for small animals, 台 (だい) for machines. English speakers meet a faint version of this in 'two HEAD of cattle' or 'three SHEETS of paper,' but Japanese applies it to nearly everything, and it is more elaborate than Chinese measure words because Japan runs two number systems in parallel: the native ひとつ/ふたつ/みっつ series (general counter, irregular, tops out around とお = 10) and the Sino-Japanese いち/に/さん series that takes specialized counters. Worse for tidy rules, the counter triggers sound changes — 一冊 is いっさつ (not いち-さつ), 一本 is いっぽん — so the 'one' you learned mutates on contact. The everyday upshot: pointing and saying ひとつ ('one, please') with a gesture is a perfectly natural survival strategy in a shop while the full counter system is still settling in.",
    "cultural_notes_vi": "Tiếng Nhật thường không đếm danh từ trần: một con số phải kèm từ đếm khớp với hình dạng hay loại của vật — つ cho vật chung, 人 (にん) cho người, 冊 (さつ) cho sách, 本 (ほん) cho vật dài mảnh, 枚 (まい) cho vật dẹt mỏng, 匹 (ひき) cho con vật nhỏ, 台 (だい) cho máy móc. Người Việt đã quen điều này: ta cũng nói \"ba CON cá\", \"hai CÁI bàn\", \"một QUYỂN sách\" — loại từ tiếng Việt chính là từ đếm. Khác biệt: tiếng Nhật chạy song song HAI hệ số — hệ thuần Nhật ひとつ/ふたつ/みっつ (từ đếm chung, bất quy tắc, dừng quanh とお = 10) và hệ Hán-Nhật いち/に/さん dùng từ đếm chuyên biệt. Rắc rối hơn: từ đếm làm đổi âm — 一冊 là いっさつ (không phải いち-さつ), 一本 là いっぽん — nên số \"một\" bạn học bị biến âm khi gặp từ đếm. Mẹo sống còn: chỉ tay và nói ひとつ (\"một cái\") là cách hoàn toàn tự nhiên trong cửa hàng khi chưa thạo hệ từ đếm.",
    "tip_advice_en": "Highest-leverage move: at A1, memorize the general ひとつ・ふたつ・みっつ counter and the people counter (ひとり・ふたり・さんにん…) as ready-made sets, and let the rest arrive one counter at a time with the nouns that need them — do NOT try to learn the whole counter chart up front; that is an A2+ project. The two genuine traps: (1) 一人/二人 are irregular — ひとり, ふたり — then it regularizes to さんにん, よにん; and (2) animate vs inanimate verbs — います for people/animals, あります for objects; saying 友達があります treats a friend like furniture. Pronunciation watch-point: the small っ in いっさつ/いっぽん is a full silent beat — hold it. Drill: count 1–3 of three different things (本・人・つ) so the sound shifts and the irregular ひとり/ふたり become reflexes.",
    "tip_advice_vi": "Việc lợi nhất: ở A1, học thuộc từ đếm chung ひとつ・ふたつ・みっつ và từ đếm người (ひとり・ふたり・さんにん…) thành bộ sẵn, còn lại để từng từ đếm đến cùng danh từ cần nó — ĐỪNG học cả bảng từ đếm ngay; đó là việc của A2 trở lên. Hai bẫy thật: (1) 一人/二人 bất quy tắc — ひとり, ふたり — rồi mới đều thành さんにん, よにん; và (2) động từ cho vật sống vs vật vô tri — います cho người/con vật, あります cho đồ vật; nói 友達があります là coi bạn mình như đồ đạc. Điểm phát âm: chữ っ nhỏ trong いっさつ/いっぽん là một nhịp lặng đầy đủ — phải giữ. Bài tập: đếm 1–3 ba loại vật khác nhau (本・人・つ) để âm chuyển và ひとり/ふたり bất quy tắc thành phản xạ."
  },
  {
    "id": 7,
    "title": "Days of the Week",
    "title_vi": "Các ngày trong tuần",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "a5c043c6-ed4e-4e20-8662-c9206ae956a1",
        "japanese": "月曜日 (げつようび)",
        "english": "Monday"
      },
      {
        cell_id: "0006fb14-f233-4373-9563-f7edb6da35e4",
        "japanese": "火曜日 (かようび)",
        "english": "Tuesday"
      },
      {
        cell_id: "c9b78834-a051-450a-b19c-cfb249674441",
        "japanese": "水曜日 (すいようび)",
        "english": "Wednesday"
      },
      {
        cell_id: "e3424893-35d6-4dfa-bf3e-fff638c7fc79",
        "japanese": "木曜日 (もくようび)",
        "english": "Thursday"
      },
      {
        cell_id: "43f95af2-f1fa-4537-9c96-792b079f6282",
        "japanese": "金曜日 (きんようび)",
        "english": "Friday"
      },
      {
        cell_id: "e081ceb9-3ae9-4e0e-8731-aafcf1f6ead6",
        "japanese": "土曜日 (どようび)",
        "english": "Saturday"
      },
      {
        cell_id: "db2b4d14-618b-4341-911b-fbb960fdf22a",
        "japanese": "日曜日 (にちようび)",
        "english": "Sunday"
      }
    ],
    "grammar": [
      {
        "point": "曜日 (youbi)",
        "explanation": "The days are named after celestial bodies: 月(moon), 火(mars), 水(mercury), 木(jupiter), 金(venus), 土(saturn), 日(sun)."
      }
    ],
    "examples": [
      {
        "japanese": "今日は金曜日です。",
        "english": "Today is Friday.",
        "pronunciation_focus_en": [
          "今日 → read 'kyo-o' (today) — an irregular kanji reading, two held beats, not 'kee-yo'",
          "は → topic particle, 'wa' not 'ha'",
          "金曜日 (きんようび) → 'kin-yo-o-bi'; ん is its own beat, よう is a long 'oh'",
          "です → 'des', devoiced final vowel"
        ],
        "pronunciation_focus": [
          "今日 → đọc 'kyô-ô' (hôm nay) — cách đọc kanji bất quy tắc, hai nhịp giữ dài, không phải 'ki-yô'",
          "は → trợ từ chủ đề, 'wa' không phải 'ha'",
          "金曜日 (きんようび) → 'kin-yô-ô-bi'; ん là một nhịp riêng, よう là 'ô' kéo dài",
          "です → 'des', nguyên âm cuối lướt"
        ]
      },
      {
        "japanese": "日曜日に映画を見ます。",
        "english": "I will watch a movie on Sunday.",
        "pronunciation_focus_en": [
          "日曜日 (にちようび) → 'ni-chi-yo-o-bi'; よう held two beats",
          "に → time particle here ('on Sunday'); short flat 'ni' — a grammatical marker, keep it light",
          "映画 (えいが) → 'e-e-ga'; えい is a long 'eh', hard g in が",
          "を → object particle, pronounced 'o' (not 'wo'); 見ます → 'mi-mas', devoiced final"
        ],
        "pronunciation_focus": [
          "日曜日 (にちようび) → 'ni-chi-yô-ô-bi'; よう giữ hai nhịp",
          "に → trợ từ thời gian ('vào Chủ nhật'); 'ni' ngắn phẳng — dấu hiệu ngữ pháp, đọc nhẹ",
          "映画 (えいが) → 'ê-ê-ga'; えい là 'ê' kéo dài, g cứng trong が",
          "を → trợ từ tân ngữ, đọc 'o' (không phải 'wo'); 見ます → 'mi-mas', cuối lướt"
        ]
      }
    ],
    "cultural_notes_en": "The seven weekday names are a small astronomy lesson: each is a celestial body or element + 曜日 ('day of the week') — 月 moon (Monday), 火 fire/Mars (Tuesday), 水 water/Mercury (Wednesday), 木 wood/Jupiter (Thursday), 金 gold/Venus (Friday), 土 earth/Saturn (Saturday), 日 sun (Sunday). This is the same Sun/Moon/Saturn logic buried in English 'Sunday/Monday/Saturday,' just kept fully transparent — so the system is more memorable than it first looks, not less. This lesson is also where the script mix becomes unavoidable: 金曜日 is kanji, the reading きんようび is hiragana, and you will see both, which is exactly why A1 Japanese material prints the hiragana reading in parentheses. The day particle に ('on') appears here too — and a useful asymmetry for English speakers: 今日 (today), 明日 (tomorrow), 毎日 (every day) take NO に, while a named day (日曜日に) does. Culturally, the work-week frame matters: Saturday is widely a half- or full work/school day historically, and seasonal awareness threads through scheduling talk far more than in the US.",
    "cultural_notes_vi": "Bảy tên ngày trong tuần là một bài thiên văn nhỏ: mỗi tên là một thiên thể hoặc nguyên tố + 曜日 (\"ngày trong tuần\") — 月 mặt trăng (thứ Hai), 火 lửa/Hỏa tinh (thứ Ba), 水 nước/Thủy tinh (thứ Tư), 木 mộc/Mộc tinh (thứ Năm), 金 kim/Kim tinh (thứ Sáu), 土 thổ/Thổ tinh (thứ Bảy), 日 mặt trời (Chủ nhật). Người Việt có lợi thế: đây đúng là kim–mộc–thủy–hỏa–thổ trong âm Hán-Việt ta đã quen, nên hệ này dễ nhớ hơn vẻ ngoài. Bài này cũng là lúc trộn hệ chữ thành bắt buộc: 金曜日 là kanji, cách đọc きんようび là hiragana, bạn sẽ thấy cả hai — đó là lý do tài liệu A1 in cách đọc hiragana trong ngoặc. Trợ từ ngày に (\"vào\") xuất hiện ở đây — và một điểm bất đối xứng hữu ích: 今日 (hôm nay), 明日 (mai), 毎日 (hằng ngày) KHÔNG dùng に, còn ngày có tên (日曜日に) thì có. Văn hóa: thứ Bảy trong lịch sử là ngày làm/học nửa hoặc cả ngày, và ý thức về mùa len lỏi vào chuyện sắp lịch.",
    "tip_advice_en": "Highest-leverage move: don't memorize seven opaque words — learn the seven one-character elements (月火水木金土日) and tack on 〜ようび; the whole set then comes nearly free, and those same kanji return for planets, elements, money (金), and 'sun/day' (日). The particle rule worth burning in now: な named day + に ('日曜日に', on Sunday), but relative-time words 今日・明日・毎日 take NO particle — over-adding に here is the classic English-speaker error because English uses 'on' for both. Pronunciation watch-points: 今日 is irregular きょう (kyo-o, two beats, NOT 'kon-nichi'); ようび hides a long 'oh' — clip it and 金曜日 sounds wrong. Drill: say each day as 'element + ようび' while writing the single kanji, so sound and script lock together.",
    "tip_advice_vi": "Việc lợi nhất: đừng học bảy từ rời rạc — học bảy ký tự nguyên tố đơn (月火水木金土日) rồi ghép thêm 〜ようび; cả bộ gần như tự có, và đúng các kanji đó quay lại cho hành tinh, nguyên tố, tiền (金) và \"mặt trời/ngày\" (日). Luật trợ từ cần khắc ngay: ngày có tên + に ('日曜日に', vào Chủ nhật), nhưng từ chỉ thời gian tương đối 今日・明日・毎日 KHÔNG dùng trợ từ — thừa に ở đây là lỗi kinh điển vì người học hay áp \"vào\" cho cả hai. Điểm phát âm: 今日 bất quy tắc là きょう (kyô-ô, hai nhịp, KHÔNG phải 'kon-nichi'); ようび giấu một 'ô' dài — cắt ngắn thì 金曜日 nghe sai. Bài tập: đọc mỗi ngày là 'nguyên tố + ようび' trong khi viết ký tự kanji đơn, để âm và chữ khóa cùng nhau."
  },
  {
    "id": 8,
    "title": "Months of the Year",
    "title_vi": "Các tháng trong năm",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "344e5c40-5d75-446a-9987-09b5758e3d57",
        "japanese": "一月 (いちがつ)",
        "english": "January"
      },
      {
        cell_id: "731ef304-e6ec-46a6-aef1-63d10a32f99a",
        "japanese": "二月 (にがつ)",
        "english": "February"
      },
      {
        cell_id: "e1158c65-a66a-43a0-8e42-341117135b2d",
        "japanese": "三月 (さんがつ)",
        "english": "March"
      },
      {
        cell_id: "650d8529-f97f-4f32-9e6f-21045850d9c6",
        "japanese": "四月 (しがつ)",
        "english": "April"
      },
      {
        cell_id: "b504cd97-bc3c-4125-9e16-87cc19085676",
        "japanese": "五月 (ごがつ)",
        "english": "May"
      },
      {
        cell_id: "298f3140-4e59-4d44-9a39-b612d710c137",
        "japanese": "六月 (ろくがつ)",
        "english": "June"
      },
      {
        cell_id: "e3d5dc00-1cdc-4aa3-a86b-5c400f84a80f",
        "japanese": "七月 (しちがつ)",
        "english": "July"
      },
      {
        cell_id: "6b57c399-8f6a-4391-89ac-9864ca2ce990",
        "japanese": "八月 (はちがつ)",
        "english": "August"
      },
      {
        cell_id: "2bacc95c-ab59-413d-a282-6ad0d1effd11",
        "japanese": "九月 (くがつ)",
        "english": "September"
      },
      {
        cell_id: "3d58d98c-98f1-44ec-baf6-4ef1b15f94f8",
        "japanese": "十月 (じゅうがつ)",
        "english": "October"
      },
      {
        cell_id: "91c9f8ec-1426-4eaa-815b-bc95c34f033f",
        "japanese": "十一月 (じゅういちがつ)",
        "english": "November"
      },
      {
        cell_id: "0d66c725-e8c8-45f6-b51c-1bddaec68c67",
        "japanese": "十二月 (じゅうにがつ)",
        "english": "December"
      }
    ],
    "grammar": [
      {
        "point": "Month formation",
        "explanation": "Simply add がつ to the number (1–12). Note April (4), July (7), September (9) have irregular readings."
      }
    ],
    "examples": [
      {
        "japanese": "誕生日は五月です。",
        "english": "My birthday is in May.",
        "pronunciation_focus_en": [
          "誕生日 (たんじょうび) → 'tan-jo-o-bi'; ん is its own beat, じょう a long 'joh'",
          "は → topic particle, 'wa'",
          "五月 (ごがつ) → 'go-ga-tsu'; つ is 'tsu' (tongue behind teeth), not 'too'",
          "です → 'des', devoiced"
        ],
        "pronunciation_focus": [
          "誕生日 (たんじょうび) → 'tan-jô-ô-bi'; ん là một nhịp riêng, じょう là 'jô' kéo dài",
          "は → trợ từ chủ đề, 'wa'",
          "五月 (ごがつ) → 'go-ga-tsu'; つ là 'tsu' (đầu lưỡi sau răng trên), không phải 'tu'",
          "です → 'des', lướt"
        ]
      },
      {
        "japanese": "十二月に日本へ行きます。",
        "english": "I will go to Japan in December.",
        "pronunciation_focus_en": [
          "十二月 (じゅうにがつ) → 'ju-u-ni-ga-tsu'; じゅう is a long 'joo' (two beats)",
          "に → time particle ('in December'); 日本 (にほん) → 'ni-hon', ん its own beat",
          "へ → direction particle: written as the kana 'he' but pronounced 'e'",
          "行きます → 'i-ki-mas', final す devoiced"
        ],
        "pronunciation_focus": [
          "十二月 (じゅうにがつ) → 'jû-û-ni-ga-tsu'; じゅう là 'jû' dài (hai nhịp)",
          "に → trợ từ thời gian ('vào tháng Mười hai'); 日本 (にほん) → 'ni-hon', ん một nhịp riêng",
          "へ → trợ từ phương hướng: viết bằng kana 'he' nhưng đọc 'e'",
          "行きます → 'i-ki-mas', す cuối lướt"
        ]
      }
    ],
    "cultural_notes_en": "Months are the single most regular thing in A1 Japanese: a number 1–12 plus がつ, full stop — 一月 'month-one' = January through 十二月 = December. There are no month names to memorize; if you can count, you can say every month — the same leverage Chinese gives with 月. But Japanese adds a twist Chinese does not: three months keep an OLD reading. 4 is しがつ (not よん-がつ), 7 is しちがつ (not なな-がつ), 9 is くがつ (not きゅう-がつ) — precisely the readings that the unlucky-number lesson taught you to avoid elsewhere, here mandatory. (Day-of-month numbers are even more irregular, which is why dates are introduced separately.) Two cultural notes worth carrying: dates run largest-to-smallest like Chinese (year → month → day), and Japan's calendar life is intensely seasonal — months are bound up with cherry blossoms (4), rainy season (6), festivals (7–8), and momiji leaves (11), so a Japanese person naming a month is often also naming a season, much as 'December' instantly says 'holidays' to an American.",
    "cultural_notes_vi": "Tháng là thứ quy tắc nhất trong A1 tiếng Nhật: một số 1–12 cộng がつ, hết — 一月 \"tháng-một\" = tháng Giêng cho đến 十二月 = tháng Mười hai. Người Việt cực kỳ lợi: ta cũng gọi \"tháng một, tháng hai…\", cùng kiểu số + tháng, biết đếm là nói được mọi tháng. Nhưng tiếng Nhật thêm một cái mà tiếng Việt không có: ba tháng giữ cách đọc CŨ. 4 là しがつ (không phải よん-がつ), 7 là しちがつ (không phải なな-がつ), 9 là くがつ (không phải きゅう-がつ) — đúng những cách đọc mà bài số xui dạy bạn tránh ở chỗ khác, ở đây lại bắt buộc. (Ngày trong tháng còn bất quy tắc hơn, nên ngày tháng được dạy riêng.) Hai điểm văn hóa: ngày tháng đọc từ lớn đến nhỏ (năm → tháng → ngày), và lịch của Nhật gắn rất chặt với mùa — tháng gắn với hoa anh đào (4), mùa mưa (6), lễ hội (7–8), lá đỏ momiji (11), nên người Nhật gọi tên tháng thường cũng là gọi tên một mùa.",
    "tip_advice_en": "Highest-leverage rule: master 'number + がつ' once and all twelve months are free — never drill them as twelve separate words. The one thing to actively memorize is the three irregulars: 4=しがつ, 7=しちがつ, 9=くがつ. Do not 'fix' them to よん/なな/きゅう — that is the predictable English-speaker over-correction, and it is wrong for months even though it is right for bare counting. Particle watch-point introduced here: へ (direction, 'to Japan') is written with the kana for 'he' but pronounced 'e' — the second hiragana-particle-with-a-surprise-reading after は='wa.' Pronunciation: the small つ in がつ is 'tsu' (tongue tip behind upper teeth), a sound English lacks word-initially — practice it. Drill: count 一月→十二月 aloud, pausing hard on し-がつ, しち-がつ, く-がつ.",
    "tip_advice_vi": "Luật lợi nhất: nắm 'số + がつ' một lần là cả mười hai tháng tự có — đừng bao giờ học chúng thành mười hai từ rời. Điều duy nhất cần học thuộc là ba ngoại lệ: 4=しがつ, 7=しちがつ, 9=くがつ. Đừng \"sửa\" chúng thành よん/なな/きゅう — đó là kiểu tự sửa quá tay, sai cho tháng dù đúng cho đếm trần. Điểm trợ từ mới: へ (phương hướng, 'sang Nhật') viết bằng kana 'he' nhưng đọc 'e' — trợ từ-hiragana-đọc-bất-ngờ thứ hai sau は='wa'. Phát âm: chữ つ nhỏ trong がつ là 'tsu' (đầu lưỡi sau răng trên), âm tiếng Việt không có ở đầu từ — phải tập. Bài tập: đếm 一月→十二月 to thành tiếng, ngừng mạnh ở し-がつ, しち-がつ, く-がつ."
  },
  {
    "id": 9,
    "title": "Telling Time",
    "title_vi": "Nói giờ",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "2e380726-5aed-4a33-8195-31659e367350",
        "japanese": "時 (じ)",
        "english": "hour / o'clock"
      },
      {
        cell_id: "a88c7ff3-bd07-4578-8806-8d54359cd788",
        "japanese": "分 (ふん / ぷん)",
        "english": "minute"
      },
      {
        cell_id: "7f4e7812-4d16-4c2a-981c-f4ec1edadf6f",
        "japanese": "半 (はん)",
        "english": "half (half past)"
      },
      {
        cell_id: "6e37b374-2b17-422d-a3c7-480e3b48cdd9",
        "japanese": "今 (いま)",
        "english": "now"
      }
    ],
    "grammar": [
      {
        "point": "Time structure",
        "explanation": "Use [number]時[number]分. For half past, add 半 after hour. Minutes have irregular pronunciations for 1,3,4,6,8,10, etc."
      }
    ],
    "examples": [
      {
        "japanese": "今、三時です。",
        "english": "It is 3 o'clock now.",
        "pronunciation_focus_en": [
          "今 (いま) → 'i-ma', two flat even beats",
          "三時 (さんじ) → 'san-ji'; ん its own beat; 時 = soft 'j' + short 'i' (the hour counter)",
          "です → 'des', devoiced final vowel",
          "no stress accent — keep 'san-ji-des' flat and evenly timed"
        ],
        "pronunciation_focus": [
          "今 (いま) → 'i-ma', hai nhịp phẳng đều",
          "三時 (さんじ) → 'san-ji'; ん một nhịp riêng; 時 = 'j' mềm + 'i' ngắn (từ đếm giờ)",
          "です → 'des', nguyên âm cuối lướt",
          "không nhấn trọng âm — giữ 'san-ji-des' phẳng và đều nhịp"
        ]
      },
      {
        "japanese": "七時半に起きます。",
        "english": "I wake up at half past seven.",
        "pronunciation_focus_en": [
          "七時 → read 'shi-chi-ji' (7 o'clock) — uses しち, NOT なな, before 時",
          "半 (はん) → 'han' = 'half past'; ん is a full beat",
          "に → time-point particle ('at 7:30'); short flat 'ni', keep it light",
          "起きます → 'o-ki-mas', final す devoiced"
        ],
        "pronunciation_focus": [
          "七時 → đọc 'shi-chi-ji' (7 giờ) — dùng しち, KHÔNG phải なな, trước 時",
          "半 (はん) → 'han' = 'rưỡi'; ん là một nhịp đầy đủ",
          "に → trợ từ điểm thời gian ('lúc 7:30'); 'ni' ngắn phẳng, đọc nhẹ",
          "起きます → 'o-ki-mas', す cuối lướt"
        ]
      }
    ],
    "cultural_notes_en": "Time uses the counter 時 (じ) for the hour and 分 (ふん/ぷん) for minutes, with 半 (はん, 'half') for the half hour — 七時半 is literally 'seven-hour-half.' The pattern is regular but the readings are not: 4時 is よじ, 7時 is しちじ, 9時 is くじ — a third reshuffle of 4/7/9 that does NOT match either the bare-counting set or the months set, which is the real difficulty here. Minutes add rendaku (sound-voicing): 一分 いっぷん, 三分 さんぷん, 四分 よんぷん, 六分 ろっぷん — the ふ flips to ぷ and small っ appears, so the clean form 'fun' is often not what you hear. Culturally, the headline fact for an American is punctuality: Japanese trains and appointments run to the literal minute, and 'on time' means a few minutes early; the famous train-delay apologies for 90 seconds are real. The particle に marks a clock point ('at 7:30'), and — useful contrast — に attaches to clock times and named days but not to 今 (now), 今日 (today), or other relative-time words.",
    "cultural_notes_vi": "Giờ dùng từ đếm 時 (じ) cho giờ và 分 (ふん/ぷん) cho phút, với 半 (はん, \"rưỡi\") cho nửa giờ — 七時半 nghĩa đen là \"bảy-giờ-nửa\". Mẫu thì đều nhưng cách đọc thì không: 4時 là よじ, 7時 là しちじ, 9時 là くじ — lần xáo trộn thứ ba của 4/7/9, KHÔNG khớp với bộ đếm trần lẫn bộ tháng, đó là cái khó thật. Phút có biến âm (rendaku): 一分 いっぷん, 三分 さんぷん, 六分 ろっぷん — ふ chuyển thành ぷ và xuất hiện っ nhỏ, nên dạng sạch \"fun\" thường không phải cái bạn nghe. Văn hóa: điều cần khắc cho người Việt là tính đúng giờ — tàu và lịch hẹn ở Nhật chạy đúng tới từng phút, \"đúng giờ\" nghĩa là đến sớm vài phút; chuyện hãng tàu xin lỗi vì trễ 90 giây là có thật. Trợ từ に đánh dấu một điểm đồng hồ ('lúc 7:30'), và — đối lập hữu ích — に gắn vào giờ đồng hồ và ngày có tên nhưng không gắn vào 今 (bây giờ), 今日 (hôm nay).",
    "tip_advice_en": "Highest-leverage warning: 4/7/9 change reading AGAIN. For the hour it is よじ (4), しちじ (7), くじ (9) — note 7時 is しちじ, the opposite of the よん/なな instinct you may have just built, and 4時 is よじ (not よん-じ). Treat clock-4/7/9 as three vocabulary items, not a rule to derive. Second: minutes voice — いっぷん, さんぷん, ろっぷん — so listen for 'pun' with a held っ, not a tidy 'fun.' Particle rule to lock: clock time + に ('七時半に', at 7:30) but 今 takes no particle. Pronunciation: the small っ in いっぷん/ろっぷん is a silent held beat — skipping it is the commonest A1 timing error. Drill: say every hour 1→12 with 時, stopping hard on よじ・しちじ・くじ until they are reflexes.",
    "tip_advice_vi": "Cảnh báo lợi nhất: 4/7/9 đổi cách đọc LẦN NỮA. Với giờ là よじ (4), しちじ (7), くじ (9) — chú ý 7時 là しちじ, ngược với phản xạ よん/なな bạn vừa xây, và 4時 là よじ (không phải よん-じ). Coi 4/7/9-giờ là ba từ vựng, không phải luật suy ra. Thứ hai: phút biến âm — いっぷん, さんぷん, ろっぷん — nghe ra 'pun' với っ giữ, không phải 'fun' gọn. Luật trợ từ cần khóa: giờ đồng hồ + に ('七時半に', lúc 7:30) nhưng 今 không dùng trợ từ. Phát âm: chữ っ nhỏ trong いっぷん/ろっぷん là một nhịp lặng giữ — bỏ qua nó là lỗi nhịp A1 phổ biến nhất. Bài tập: đọc mọi giờ 1→12 với 時, ngừng mạnh ở よじ・しちじ・くじ tới khi thành phản xạ."
  },
  {
    "id": 10,
    "title": "Asking for Directions",
    "title_vi": "Hỏi đường",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "9279d91e-27cc-429d-a99a-4cf2e1dd1af7",
        "japanese": "どこ",
        "english": "where"
      },
      {
        cell_id: "134adc2a-e957-4165-b91a-b4c4917a6de1",
        "japanese": "駅 (えき)",
        "english": "station"
      },
      {
        cell_id: "9e747306-dd4d-4e04-a3db-8e62505cf774",
        "japanese": "交番 (こうばん)",
        "english": "police box"
      },
      {
        cell_id: "4e48a279-fd48-4ca4-a8e0-d7e44c138bec",
        "japanese": "右 (みぎ)",
        "english": "right"
      },
      {
        cell_id: "47ff24c4-fd83-4c48-9603-a813a2f2ef05",
        "japanese": "左 (ひだり)",
        "english": "left"
      },
      {
        cell_id: "1dac82c8-3921-4859-9df2-06422c2445ec",
        "japanese": "まっすぐ",
        "english": "straight"
      }
    ],
    "grammar": [
      {
        "point": "～はどこですか？",
        "explanation": "Use ～はどこですか to ask 'Where is ~?'."
      }
    ],
    "examples": [
      {
        "japanese": "駅はどこですか？",
        "english": "Where is the station?",
        "pronunciation_focus_en": [
          "駅 (えき) → 'e-ki', two flat even beats",
          "は → topic particle, 'wa' not 'ha'",
          "どこ → 'do-ko' ('where'); both vowels short and equal",
          "ですか → 'des-ka'; pitch rises only on か to mark the question"
        ],
        "pronunciation_focus": [
          "駅 (えき) → 'e-ki', hai nhịp phẳng đều",
          "は → trợ từ chủ đề, 'wa' không phải 'ha'",
          "どこ → 'do-ko' ('ở đâu'); cả hai nguyên âm ngắn và đều",
          "ですか → 'des-ka'; chỉ lên giọng ở か để hỏi"
        ]
      },
      {
        "japanese": "まっすぐ行って、右です。",
        "english": "Go straight, then it's on the right.",
        "pronunciation_focus_en": [
          "まっすぐ → 'ma(s)-su-gu'; the small っ is a held silent beat before すぐ",
          "行って → 'i(t)-te'; another small っ — a clipped pause, then 'te' (the connecting て-form)",
          "右 (みぎ) → 'mi-gi', hard g; (contrast 左 ひだり = left)",
          "です → 'des', devoiced final vowel"
        ],
        "pronunciation_focus": [
          "まっすぐ → 'ma(s)-su-gu'; chữ っ nhỏ là một nhịp lặng giữ trước すぐ",
          "行って → 'i(t)-te'; một っ nhỏ nữa — ngừng ngắt, rồi 'te' (thể て nối câu)",
          "右 (みぎ) → 'mi-gi', g cứng như 'gà'; (đối lập 左 ひだり = trái)",
          "です → 'des', nguyên âm cuối lướt"
        ]
      }
    ],
    "cultural_notes_en": "Two things make Japanese directions distinctive for an American. First, the landmark: the 交番 (kōban), a small neighborhood police box, is the normal place to ask the way — officers there expect direction questions and often have local maps; there is no real US equivalent (it is not a 'police station' you would hesitate to bother). Second, the address system itself: Japanese addresses are area-block-building, not street-based, so even locals navigate by landmarks and ask at the kōban — getting lost and asking is ordinary, not a failure. The sentence frame here, 〜はどこですか ('where is ~?'), is one of the highest-value survival templates in the language. Politeness also shapes the answers you'll hear: a helper who is unsure will often soften with 〜と思います ('I think…') rather than guess flatly, and may walk you part-way rather than say 'you can't miss it' — declining that escort with a quick ありがとうございます is fine. The て-form (行って, 'go and then…') appears here as the everyday way to chain instructions: do this, then that.",
    "cultural_notes_vi": "Hai điều làm chỉ đường kiểu Nhật khác lạ với người Việt. Thứ nhất, mốc hỏi đường: 交番 (kōban), chốt cảnh sát nhỏ trong khu phố, là nơi bình thường để hỏi đường — cảnh sát ở đó chờ được hỏi và thường có bản đồ khu vực; ta không có thứ tương đương, đừng ngại như ngại vào đồn công an. Thứ hai, hệ địa chỉ: địa chỉ Nhật theo khu–lô–tòa nhà chứ không theo tên đường, nên cả dân địa phương cũng định hướng bằng mốc và hỏi ở kōban — lạc đường rồi hỏi là chuyện thường, không phải thất bại. Mẫu câu 〜はどこですか (\"~ ở đâu?\") là một trong những công thức sống còn giá trị nhất. Lịch sự cũng định hình câu trả lời: người không chắc thường làm dịu bằng 〜と思います (\"tôi nghĩ là…\") thay vì đoán chắc nịch, và có thể dẫn bạn đi một đoạn; từ chối được dẫn bằng một câu ありがとうございます là ổn. Thể て (行って, \"đi rồi…\") xuất hiện ở đây như cách thường để nối các bước: làm cái này, rồi cái kia.",
    "tip_advice_en": "Highest-leverage template: lock 〜はどこですか and you can locate anything — 駅は / トイレは / 交番はどこですか. Slot any noun in front of は; that single pattern plus pointing handles most lost-tourist situations. The new grammar to notice, not yet master, is the て-form (行って = 'go and…'): A1 only needs to recognize it as the 'and then' connector; its full conjugation is A2. Pronunciation watch-point dominates this lesson: small っ appears twice — まっすぐ and 行って — and each is a real silent beat. English speakers blur it (\"masugu\", \"ite\"), which makes you hard to understand and means you'll miss it when spoken to you. Drill: clap the beats — ma–(stop)–su–gu, i–(stop)–te — exaggerating the silent hold until the double consonant is automatic. Pair each direction word with its kanji (右/左/駅) so signage becomes readable, since direction signs rarely show furigana.",
    "tip_advice_vi": "Công thức lợi nhất: khóa chặt 〜はどこですか là định vị được mọi thứ — 駅は / トイレは / 交番はどこですか. Đặt danh từ bất kỳ trước は; mẫu duy nhất đó cộng chỉ tay xử lý hầu hết tình huống du khách bị lạc. Ngữ pháp mới cần nhận ra, chưa cần thạo, là thể て (行って = 'đi rồi…'): A1 chỉ cần nhận ra nó là từ nối 'rồi sau đó'; chia đầy đủ là việc của A2. Điểm phát âm chi phối bài này: っ nhỏ xuất hiện hai lần — まっすぐ và 行って — mỗi cái là một nhịp lặng thật. Người học hay làm mờ nó (\"masugu\", \"ite\"), khiến khó hiểu và bỏ lỡ khi người ta nói với mình. Bài tập: vỗ tay theo nhịp — ma–(ngừng)–su–gu, i–(ngừng)–te — phóng đại chỗ ngừng lặng tới khi phụ âm đôi thành tự động. Ghép mỗi từ chỉ hướng với kanji của nó (右/左/駅) vì biển chỉ đường hiếm khi có furigana."
  },
  {
    "id": 11,
    "title": "Ordering Food",
    "title_vi": "Gọi món ăn",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "b4395a5d-4da6-4c1e-a325-e4d2e21bde44",
        "japanese": "メニュー",
        "english": "menu"
      },
      {
        cell_id: "0d029588-5167-4854-94a8-dfab2cb2c9ec",
        "japanese": "注文 (ちゅうもん)",
        "english": "order"
      },
      {
        cell_id: "e69704dc-742b-4f44-ab9c-4dd7370883c7",
        "japanese": "ください",
        "english": "please (give me)"
      },
      {
        cell_id: "df8bb3c6-e527-40c2-9808-69aedfec40fd",
        "japanese": "お願いします (おねがいします)",
        "english": "please (request)"
      },
      {
        cell_id: "5b2e7d7a-c4c0-41dc-8d80-6c9b16e3588b",
        "japanese": "お会計 (おかいけい)",
        "english": "bill / check"
      }
    ],
    "grammar": [
      {
        "point": "～をください",
        "explanation": "Use ～をください to order something. ～をお願いします is a polite alternative."
      }
    ],
    "examples": [
      {
        "japanese": "ラーメンをください。",
        "english": "Ramen, please.",
        "pronunciation_focus_en": [
          "ラーメン → 'ra-a-men'; ー holds the 'ah' two beats, ん is its own beat (katakana = loanword styling)",
          "を → object particle, pronounced 'o' (never 'wo'); keep it very light",
          "ください → 'ku-da-sa-i', four even beats; final い is a clear short 'ee'",
          "no stress accent — flat, even timing across the whole phrase"
        ],
        "pronunciation_focus": [
          "ラーメン → 'ra-a-men'; ー giữ âm 'a' hai nhịp, ん là một nhịp riêng (katakana = kiểu từ mượn)",
          "を → trợ từ tân ngữ, đọc 'o' (không bao giờ 'wo'); đọc rất nhẹ",
          "ください → 'ku-da-sa-i', bốn nhịp đều; い cuối là 'i' ngắn rõ",
          "không nhấn trọng âm — phẳng, đều nhịp suốt cả cụm"
        ]
      },
      {
        "japanese": "コーヒーをお願いします。",
        "english": "Coffee, please.",
        "pronunciation_focus_en": [
          "コーヒー → 'ko-o-hi-i', four beats (both ー held) — same word as Lesson 2",
          "を → object particle, 'o'",
          "お願いします → 'o-ne-ga-i-shi-mas'; お is the polite prefix, final す devoiced",
          "ねがい → 'ne-ga-i', three even mora; do not crush 'ga-i' into one"
        ],
        "pronunciation_focus": [
          "コーヒー → 'kô-ô-hi-i', bốn nhịp (giữ cả hai ー) — cùng từ với Bài 2",
          "を → trợ từ tân ngữ, 'o'",
          "お願いします → 'o-ne-ga-i-shi-mas'; お là tiền tố lịch sự, す cuối lướt",
          "ねがい → 'ne-ga-i', ba mora đều; đừng dồn 'ga-i' thành một"
        ]
      },
      {
        "japanese": "お会計お願いします。",
        "english": "Check, please.",
        "pronunciation_focus_en": [
          "お会計 (おかいけい) → 'o-ka-i-ke-e'; the お is a politeness prefix on 会計",
          "けい → a long 'eh' (ke held two beats), not 'kay'",
          "お願いします → 'o-ne-ga-i-shi-mas', devoiced final す",
          "slight natural pause between お会計 and お願いします (a comma is often implied)"
        ],
        "pronunciation_focus": [
          "お会計 (おかいけい) → 'o-ka-i-ke-e'; お là tiền tố lịch sự gắn vào 会計",
          "けい → 'ê' kéo dài (ke giữ hai nhịp), không phải 'kây'",
          "お願いします → 'o-ne-ga-i-shi-mas', す cuối lướt",
          "ngừng tự nhiên nhẹ giữa お会計 và お願いします (thường ngầm có dấu phẩy)"
        ]
      }
    ],
    "cultural_notes_en": "Restaurant Japanese has a politeness ladder English flattens into one word, 'please.' 〜をください is 'give me ~' — direct, fine for ordering a dish; 〜をお願いします is softer and more deferential ('I request ~'), the safer default with staff and the normal way to ask for the check (お会計お願いします). The honorific お on お会計, お願い, お茶, お水 is not optional decoration — dropping it sounds curt. Behaviorally, several things invert American instincts: slurping noodles audibly is correct and signals enjoyment, not rudeness; you do not tip — leaving cash on the table reads as confusing or as if you forgot your change, and staff may chase you to return it; water and tea are free, brought unasked, and refilled; and you typically pay at a register on the way out, not by leaving money at the table. Menus lean heavily on katakana for foreign dishes (ラーメン, カレー, ハンバーガー), so Lesson 2's loanword skill pays off directly here. Calling a server is done with a clear 'すみません' (excuse me) across the room — normal and expected, not impolite.",
    "cultural_notes_vi": "Tiếng Nhật trong nhà hàng có thang lịch sự mà tiếng Việt gom vào một chữ \"làm ơn / cho\". 〜をください là \"cho tôi ~\" — trực tiếp, ổn khi gọi món; 〜をお願いします dịu và nhún hơn (\"tôi xin ~\"), là lựa chọn an toàn hơn với nhân viên và là cách thường để xin tính tiền (お会計お願いします). Tiền tố kính ngữ お trên お会計, お願い, お茶, お水 không phải trang trí tùy chọn — bỏ đi nghe cộc. Hành vi đảo ngược thói quen Việt: húp mì kêu thành tiếng là đúng và báo hiệu ngon, không phải bất lịch sự; không boa tiền — để tiền trên bàn bị hiểu là khó hiểu hoặc như bạn quên tiền thừa, nhân viên có thể chạy theo trả lại; nước và trà miễn phí, tự mang ra và châm thêm; thường trả tiền ở quầy lúc ra về, không để tiền trên bàn. Thực đơn dùng katakana rất nhiều cho món ngoại (ラーメン, カレー, ハンバーガー), nên kỹ năng từ mượn của Bài 2 trả công ngay ở đây. Gọi nhân viên bằng một tiếng \"すみません\" rõ từ xa — bình thường và được mong đợi.",
    "tip_advice_en": "Highest-leverage habit: default to 〜をお願いします for almost everything in a shop or restaurant — it is never too polite, while 〜をください can sound brusque to staff if your tone is flat. Reserve plain ください for simple item requests. The grammar to lock is the object particle を: it marks WHAT you want and is pronounced 'o,' a bare vowel — the third hiragana-particle-with-a-surprise after は='wa' and へ='e.' English speakers over-pronounce it as 'wo' or stress it; keep it nearly weightless. Pronunciation watch-point: long vowels decide meaning on menus — ビール (beer) vs ビル (building), コーヒー's doubled vowels — so hold every ー. Drill the three politeness levels on one item: 'コーヒー' / 'コーヒーをください' / 'コーヒーをお願いします,' feeling the deference rise.",
    "tip_advice_vi": "Thói quen lợi nhất: mặc định dùng 〜をお願いします cho gần như mọi thứ trong cửa hàng hay nhà hàng — không bao giờ là quá lịch sự, còn 〜をください có thể nghe cộc với nhân viên nếu giọng bạn phẳng. Để dành ください trần cho yêu cầu món đơn giản. Ngữ pháp cần khóa là trợ từ tân ngữ を: nó đánh dấu CÁI bạn muốn và đọc là 'o', một nguyên âm trần — trợ từ-hiragana-bất-ngờ thứ ba sau は='wa' và へ='e'. Người học hay đọc quá thành 'wo' hoặc nhấn nó; giữ gần như không trọng lượng. Điểm phát âm: nguyên âm dài quyết định nghĩa trên thực đơn — ビール (bia) vs ビル (tòa nhà), các nguyên âm đôi của コーヒー — nên giữ mọi dấu ー. Bài tập ba mức lịch sự trên một món: 'コーヒー' / 'コーヒーをください' / 'コーヒーをお願いします', cảm nhận độ nhún tăng dần."
  },
  {
    "id": 12,
    "title": "Shopping Phrases",
    "title_vi": "Mẫu câu mua sắm",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "05482bde-6f6b-49e5-9632-8c0c181d6f8e",
        "japanese": "いくら",
        "english": "how much"
      },
      {
        cell_id: "3e57941f-695a-4bda-aa63-4f3574c65489",
        "japanese": "高い (たかい)",
        "english": "expensive / high"
      },
      {
        cell_id: "223699e9-edb0-4f78-b567-420ada803fe3",
        "japanese": "安い (やすい)",
        "english": "cheap"
      },
      {
        cell_id: "d7b46c4e-9621-4ca7-851c-33657e661e8b",
        "japanese": "これをください",
        "english": "I'll take this"
      },
      {
        cell_id: "f158dc89-4d54-494a-9fc9-7ed286a368db",
        "japanese": "袋 (ふくろ)",
        "english": "bag"
      }
    ],
    "grammar": [
      {
        "point": "いくらですか",
        "explanation": "Use いくらですか to ask the price. これをください to purchase."
      }
    ],
    "examples": [
      {
        "japanese": "これはいくらですか？",
        "english": "How much is this?",
        "pronunciation_focus_en": [
          "これ → 'ko-re' ('this one, near me'); tapped r, two even beats",
          "は → topic particle, 'wa'",
          "いくら → 'i-ku-ra' ('how much'); flat and even, no stressed syllable",
          "ですか → 'des-ka'; pitch rises only on か"
        ],
        "pronunciation_focus": [
          "これ → 'ko-re' ('cái này, gần tôi'); r búng lưỡi, hai nhịp đều",
          "は → trợ từ chủ đề, 'wa'",
          "いくら → 'i-ku-ra' ('bao nhiêu'); phẳng và đều, không nhấn âm nào",
          "ですか → 'des-ka'; chỉ lên giọng ở か"
        ]
      },
      {
        "japanese": "もう少し安いのはありますか？",
        "english": "Do you have something a bit cheaper?",
        "pronunciation_focus_en": [
          "もう少し → 'mo-o-su-ko-shi'; もう is a long 'oh' (two beats) = 'a bit more'",
          "安い (やすい) → 'ya-su-i', three mora; an い-adjective ('cheap')",
          "のは → 'no-wa'; の turns 'cheap' into 'a cheap one', は again 'wa'",
          "ありますか → 'a-ri-mas-ka', devoiced す; rising pitch on final か"
        ],
        "pronunciation_focus": [
          "もう少し → 'mô-ô-su-ko-shi'; もう là 'ô' kéo dài (hai nhịp) = 'thêm một chút'",
          "安い (やすい) → 'ya-su-i', ba mora; một tính từ-い ('rẻ')",
          "のは → 'no-wa'; の biến 'rẻ' thành 'cái rẻ', は lại là 'wa'",
          "ありますか → 'a-ri-mas-ka', す lướt; lên giọng ở か cuối"
        ]
      }
    ],
    "cultural_notes_en": "Prices in Japan are almost always fixed and displayed; haggling is normal only at flea markets and some electronics districts, so the everyday shopping script is 'ask, decide, pay,' not 'negotiate' — closer to an American department store than a bazaar. The deictic これ/それ/あれ ('this near me / that near you / that over there') is doing real work in a shop: which word you choose tells the clerk which item, so pointing plus これ is a complete, polite request. The cultural subtlety to internalize is indirect refusal: a shop that cannot do something will rarely say a flat 'no.' You will hear ちょっと…('that's a little…', trailing off), 難しいですね ('it's difficult, isn't it'), or a sucked-in breath — all of which mean no. Pushing for an explicit 'no' makes everyone uncomfortable; reading the soft signal and backing off gracefully is the competent move, the opposite of the American instinct to get a clear yes/no. Sales tax is usually already shown, and a small tray is used for money rather than hand-to-hand exchange — place cash on the tray, don't press it into the clerk's palm.",
    "cultural_notes_vi": "Giá ở Nhật gần như luôn cố định và niêm yết; mặc cả chỉ bình thường ở chợ trời và vài khu điện tử, nên kịch bản mua sắm thường ngày là \"hỏi, quyết, trả\", không phải \"trả giá\" — khác chợ truyền thống ở Việt Nam, gần với siêu thị hơn. Các từ chỉ định これ/それ/あれ (\"cái này gần tôi / cái đó gần bạn / cái kia đằng xa\") làm việc thật trong cửa hàng: chọn từ nào là báo cho người bán món nào, nên chỉ tay cộng これ là một yêu cầu đầy đủ và lịch sự. Tinh tế văn hóa cần thấm: từ chối gián tiếp. Cửa hàng không làm được điều gì hiếm khi nói \"không\" thẳng. Bạn sẽ nghe ちょっと… (\"hơi…\", bỏ lửng), 難しいですね (\"khó đấy nhỉ\"), hoặc một tiếng hít vào — đều nghĩa là không. Ép cho ra một câu \"không\" rõ ràng làm mọi người khó chịu; đọc được tín hiệu mềm và lùi lại nhã nhặn mới là người khéo. Thuế thường đã gộp sẵn, và tiền đặt vào khay nhỏ chứ không trao tay — đặt tiền lên khay, đừng dúi vào tay người bán.",
    "tip_advice_en": "Highest-leverage template: 〜はいくらですか ('how much is ~?') plus これ/それ/あれ and pointing handles essentially all A1 shopping. Memorize これ as 'this (by me)' and you can buy anything by pointing. The cultural skill that matters more than vocabulary: learn to hear soft 'no.' ちょっと… with a trailing pause, an inhaled breath, or 難しいですね is a polite refusal — accept it with わかりました ('understood') and stop; do not press for a yes. Pronunciation watch-points: もう and other long-'oh' words must be held (もう少し) or they change meaning; the の in 安いの is a nominalizer ('a cheap one'), unstressed and light. Drill: point at three things and ask これはいくらですか, then practice receiving a soft 'ちょっと…' without pushing back.",
    "tip_advice_vi": "Công thức lợi nhất: 〜はいくらですか ('~ bao nhiêu tiền?') cộng これ/それ/あれ và chỉ tay xử lý gần như mọi tình huống mua sắm A1. Học thuộc これ là 'cái này (gần tôi)' là mua được mọi thứ bằng cách chỉ tay. Kỹ năng văn hóa quan trọng hơn từ vựng: tập nghe ra \"không\" mềm. ちょっと… với một quãng ngừng bỏ lửng, một tiếng hít vào, hoặc 難しいですね là lời từ chối lịch sự — nhận lấy bằng わかりました ('hiểu rồi') rồi dừng; đừng ép cho ra một câu đồng ý. Điểm phát âm: もう và các từ 'ô' dài khác phải giữ (もう少し) nếu không sẽ đổi nghĩa; chữ の trong 安いの là từ danh-hóa ('cái rẻ'), không nhấn và đọc nhẹ. Bài tập: chỉ ba vật và hỏi これはいくらですか, rồi tập nhận một tiếng 'ちょっと…' mềm mà không phản đối lại."
  },
  {
    "id": 13,
    "title": "Family Members",
    "title_vi": "Các thành viên trong gia đình",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "25f58bf4-fbcf-4dbc-8b38-b1c18c027dd5",
        "japanese": "お父さん (おとうさん)",
        "english": "father"
      },
      {
        cell_id: "31d387a0-6361-4d56-a2fd-c2ee561e4d86",
        "japanese": "お母さん (おかあさん)",
        "english": "mother"
      },
      {
        cell_id: "8615f514-4ef1-41b3-b4f4-c88bd2d767fd",
        "japanese": "お兄さん (おにいさん)",
        "english": "older brother"
      },
      {
        cell_id: "59d84467-5662-41ee-b535-02be5ff0bf8e",
        "japanese": "お姉さん (おねえさん)",
        "english": "older sister"
      },
      {
        cell_id: "f9e8ab44-3b6f-46c2-be9e-384868c1344b",
        "japanese": "弟 (おとうと)",
        "english": "younger brother"
      },
      {
        cell_id: "e595d20a-9323-4550-8358-03fdb09c273f",
        "japanese": "妹 (いもうと)",
        "english": "younger sister"
      }
    ],
    "grammar": [
      {
        "point": "Honorific family terms",
        "explanation": "When speaking about your own family, use humble forms (e.g., 父, 母). When speaking about someone else's family, use respectful forms (お父さん, お母さん)."
      }
    ],
    "examples": [
      {
        "japanese": "私の父は医者です。",
        "english": "My father is a doctor.",
        "pronunciation_focus_en": [
          "私の → 'wa-ta-shi-no'; の = possessive 'my', light and short",
          "父 → read 'chi-chi' (my own father) — the humble form, NOT お父さん here",
          "は → topic particle, 'wa'",
          "医者 (いしゃ) → 'i-sha', two beats; です → 'des', devoiced"
        ],
        "pronunciation_focus": [
          "私の → 'wa-ta-shi-no'; の = sở hữu 'của tôi', nhẹ và ngắn",
          "父 → đọc 'chi-chi' (cha của chính tôi) — thể khiêm, KHÔNG phải お父さん ở đây",
          "は → trợ từ chủ đề, 'wa'",
          "医者 (いしゃ) → 'i-sha', hai nhịp; です → 'des', lướt"
        ]
      },
      {
        "japanese": "お母さんは元気ですか？",
        "english": "How is your mother?",
        "pronunciation_focus_en": [
          "お母さん → 'o-ka-a-san'; ー-like long 'ah' in かあ (two beats), さん the polite suffix — used for SOMEONE ELSE'S mother",
          "は → topic particle, 'wa'",
          "元気 (げんき) → 'gen-ki', hard g, ん its own beat",
          "ですか → 'des-ka'; pitch rises only on か"
        ],
        "pronunciation_focus": [
          "お母さん → 'o-ka-a-san'; 'a' kéo dài trong かあ (hai nhịp), さん hậu tố lịch sự — dùng cho mẹ của NGƯỜI KHÁC",
          "は → trợ từ chủ đề, 'wa'",
          "元気 (げんき) → 'gen-ki', g cứng như 'gà', ん một nhịp riêng",
          "ですか → 'des-ka'; chỉ lên giọng ở か"
        ]
      }
    ],
    "cultural_notes_en": "Family words encode the deepest organizing principle in Japanese politeness: uchi (内, in-group/'us') vs soto (外, out-group/'them'). You use HUMBLE plain words for your own family when speaking to outsiders — 父 (chichi) 'my father,' 母 (haha) 'my mother' — but RESPECTFUL お…さん forms for someone else's family — お父さん, お母さん. Saying お父さん about your own dad to a stranger sounds childish or self-elevating; saying 父 about their dad sounds rude. English has no grammatical version of this; the nearest analogy is the American instinct to say 'my dad' casually but 'your father' more carefully — Japanese turns that instinct into a hard lexical rule. (Inside the family, children do call their own parents お母さん/お父さん directly — the humble form is specifically for talking ABOUT them to outsiders.) The same uchi/soto axis later governs honorific and humble verbs, so meeting it here with concrete kin terms builds the intuition early. Note also the possessive の (私の父 = 'my father'), which is the same particle as Lesson 12's nominalizer doing a different job — context decides.",
    "cultural_notes_vi": "Từ chỉ gia đình mã hóa nguyên lý sâu nhất của lịch sự Nhật: uchi (内, người trong/\"ta\") vs soto (外, người ngoài/\"họ\"). Dùng từ KHIÊM, trần cho gia đình mình khi nói với người ngoài — 父 (chichi) \"cha tôi\", 母 (haha) \"mẹ tôi\" — nhưng dùng dạng KÍNH お…さん cho gia đình người khác — お父さん, お母さん. Người Việt vốn có hệ xưng hô phân biệt theo quan hệ, nên ý niệm này không xa lạ; cái mới là tiếng Nhật biến nó thành luật từ vựng cứng. Nói お父さん về cha mình với người lạ nghe trẻ con hoặc tự đề cao; nói 父 về cha họ nghe thất lễ. (Trong nhà, con vẫn gọi cha mẹ mình trực tiếp là お母さん/お父さん — dạng khiêm chỉ dùng khi NÓI VỀ họ với người ngoài.) Cùng trục uchi/soto này về sau chi phối động từ kính ngữ và khiêm nhường, nên gặp nó ở đây với từ thân tộc cụ thể giúp xây trực giác sớm. Cũng chú ý sở hữu の (私の父 = \"cha tôi\"), cùng trợ từ với từ danh-hóa ở Bài 12 nhưng làm việc khác — ngữ cảnh quyết định.",
    "tip_advice_en": "Highest-leverage rule, and it is cultural before it is grammatical: two words for every relative — humble for mine, honorific for yours. 父/母/兄/姉 when talking about MY family to others; お父さん/お母さん/お兄さん/お姉さん for YOUR family (and when calling my own parents directly at home). Get the direction wrong and the error is social, not just grammatical, so drill them as opposing pairs, never singly. The grammar to lock is possessive の: 'A の B' = 'A's B' (私の父 = my father) — same character as the Lesson 12 の, different job; let context, not a rule, sort them at A1. Pronunciation watch-point: お母さん (o-kaa-san) and お父さん (o-tou-san) hide long vowels (かあ, とう) — clip them and they sound wrong; 父 alone is ちち (chi-chi), two crisp equal beats. Drill: introduce your family with humble forms, then ask about someone's with お…さん.",
    "tip_advice_vi": "Luật lợi nhất, và là văn hóa trước khi là ngữ pháp: hai từ cho mỗi người thân — khiêm cho người nhà tôi, kính cho người nhà bạn. 父/母/兄/姉 khi nói về gia đình TÔI với người khác; お父さん/お母さん/お兄さん/お姉さん cho gia đình BẠN (và khi gọi cha mẹ mình trực tiếp ở nhà). Sai hướng thì lỗi là xã hội, không chỉ ngữ pháp, nên luyện chúng thành cặp đối nghịch, đừng học lẻ. Ngữ pháp cần khóa là sở hữu の: 'A の B' = 'B của A' (私の父 = cha tôi) — cùng ký tự với の ở Bài 12, việc khác; để ngữ cảnh, không phải luật, phân biệt ở A1. Điểm phát âm: お母さん (o-kaa-san) và お父さん (o-tou-san) giấu nguyên âm dài (かあ, とう) — cắt ngắn thì sai; 父 đứng riêng là ちち (chi-chi), hai nhịp đều rõ. Bài tập: giới thiệu gia đình mình bằng thể khiêm, rồi hỏi về gia đình ai đó bằng お…さん."
  },
  {
    "id": 14,
    "title": "Colors",
    "title_vi": "Màu sắc",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "26a7540a-a8e3-4fa6-89ec-4fe65921902b",
        "japanese": "赤 (あか)",
        "english": "red"
      },
      {
        cell_id: "46cb326c-43e4-4164-bed3-df2b0ea98f0b",
        "japanese": "青 (あお)",
        "english": "blue"
      },
      {
        cell_id: "4f0467ac-7e7f-49a2-bcd1-e31c0cba81ef",
        "japanese": "黄色 (きいろ)",
        "english": "yellow"
      },
      {
        cell_id: "ff77b8a5-628f-43f1-816b-52abefdc05da",
        "japanese": "白 (しろ)",
        "english": "white"
      },
      {
        cell_id: "9b6f389d-b76a-4023-affe-48a5250529f1",
        "japanese": "黒 (くろ)",
        "english": "black"
      },
      {
        cell_id: "d1f03bae-1d8f-4219-a350-9fb21cbe33cf",
        "japanese": "緑 (みどり)",
        "english": "green"
      }
    ],
    "grammar": [
      {
        "point": "Color adjectives",
        "explanation": "Colors can be nouns or い-adjectives. Add い to form adjective: 赤い, 青い, 白い, 黒い, 黄色い. 緑 is a noun only."
      }
    ],
    "examples": [
      {
        "japanese": "赤い花が好きです。",
        "english": "I like red flowers.",
        "pronunciation_focus_en": [
          "赤い (あかい) → 'a-ka-i', three even mora; the trailing い makes it the ADJECTIVE 'red' (赤 alone = the noun)",
          "花 (はな) → 'ha-na' (here 花 IS 'ha-na' — flower); が = subject particle, hard 'ga'",
          "好き (すき) → 'su-ki'; the う is devoiced, so it sounds almost 'ski'",
          "です → 'des', devoiced final vowel"
        ],
        "pronunciation_focus": [
          "赤い (あかい) → 'a-ka-i', ba mora đều; chữ い cuối biến nó thành TÍNH TỪ 'đỏ' (赤 đứng riêng = danh từ)",
          "花 (はな) → 'ha-na' (ở đây 花 đọc 'ha-na' — hoa); が = trợ từ chủ ngữ, 'ga' cứng",
          "好き (すき) → 'su-ki'; âm う lướt, nên nghe gần như 'ski'",
          "です → 'des', nguyên âm cuối lướt"
        ]
      },
      {
        "japanese": "青い空がきれいです。",
        "english": "The blue sky is beautiful.",
        "pronunciation_focus_en": [
          "青い (あおい) → 'a-o-i', three separate even mora — do not glide 'a-o' together",
          "空 (そら) → 'so-ra', tapped r; が subject particle",
          "きれい → 'ki-re-e'; the final い is a long 'eh', so it sounds 'ki-ray', NOT 'ee'",
          "です → 'des', devoiced"
        ],
        "pronunciation_focus": [
          "青い (あおい) → 'a-o-i', ba mora riêng đều — đừng lướt 'a-o' dính vào nhau",
          "空 (そら) → 'so-ra', r búng lưỡi; が trợ từ chủ ngữ",
          "きれい → 'ki-re-e'; chữ い cuối là 'ê' dài, nên nghe 'ki-rê', KHÔNG phải 'i'",
          "です → 'des', lướt"
        ]
      }
    ],
    "cultural_notes_en": "Colors hide two traps for English speakers. First, grammatical: some colors are both a noun and an い-adjective (赤 'red [noun]' → 赤い 'red [describing something]'), while others, like 緑 (green), are noun-only and cannot take い — so 赤い花 works but 緑い is wrong; you say 緑の (green + の). Second, cultural-historical: 青 (ao) classically covered both blue AND green, and that older boundary survives in fixed expressions — a green traffic light is 青信号 (literally 'blue signal'), unripe/green apples and fresh greenery are 青…, and a 'greenhorn' is 青二才. 緑 (midori) as a separate everyday 'green' is relatively modern. The American parallel: imagine if 'blue' had once meant blue-or-green and English still said 'the blue light means go' — that is exactly the residue here, so don't 'correct' 青信号 to green. White (白) and red (赤) also carry strong ceremonial weight (the 紅白 red-white pairing is celebratory, on the flag and at weddings), unlike their more neutral US associations.",
    "cultural_notes_vi": "Màu sắc giấu hai bẫy. Thứ nhất, ngữ pháp: vài màu vừa là danh từ vừa là tính từ-い (赤 'đỏ [danh từ]' → 赤い 'đỏ [mô tả vật]'), trong khi vài màu, như 緑 (xanh lá), chỉ là danh từ và không thêm được い — nên 赤い花 đúng nhưng 緑い sai; phải nói 緑の (xanh lá + の). Thứ hai, văn hóa-lịch sử: 青 (ao) ngày xưa bao gồm cả xanh dương LẪN xanh lá, và ranh giới cũ đó còn sót trong cụm cố định — đèn xanh giao thông là 青信号 (nghĩa đen 'tín hiệu xanh dương'), táo xanh và cây cối tươi là 青…, người non kinh nghiệm là 青二才. 緑 (midori) thành 'xanh lá' riêng hằng ngày là tương đối mới. Người Việt cũng quen điều này: ta gọi cả bầu trời và lá cây là \"xanh\" rồi mới phân biệt \"xanh da trời / xanh lá\" — đừng \"sửa\" 青信号 thành xanh lá. Trắng (白) và đỏ (赤) còn mang nặng nghĩa lễ nghi (cặp đỏ-trắng 紅白 là mừng vui, trên quốc kỳ và trong đám cưới).",
    "tip_advice_en": "Highest-leverage distinction: is the color an い-adjective or a noun? 赤・青・白・黒・黄色 add い to describe something (赤い車); 緑 does not — use 緑の (緑の車). Mislabeling a noun-color as an い-adjective is the predictable A1 error. Don't fight 青信号 ('blue' = green light): memorize it as a fixed phrase and you've absorbed a real piece of the language's history. Pronunciation watch-points: きれい ends in a long 'eh' and sounds 'ki-ray,' a classic mishearing as 'ee'; 好き drops its う and comes out near 'ski'; and 青い is three clean mora a-o-i — English speakers collapse 'a-o' into one. Drill: pair each color with a noun, switching between 赤い〜 (adjective) and 緑の〜 (noun + の) so the two patterns stay separate.",
    "tip_advice_vi": "Phân biệt lợi nhất: màu này là tính từ-い hay danh từ? 赤・青・白・黒・黄色 thêm い để mô tả vật (赤い車); 緑 thì không — dùng 緑の (緑の車). Gắn nhầm màu-danh-từ thành tính từ-い là lỗi A1 dễ đoán. Đừng chống 青信号 ('xanh dương' = đèn xanh): học thuộc như cụm cố định là bạn đã hấp thụ một mảnh lịch sử thật của tiếng này. Điểm phát âm: きれい kết bằng 'ê' dài và nghe 'ki-rê', hay bị nghe nhầm thành 'i'; 好き rụng âm う và phát ra gần 'ski'; và 青い là ba mora rõ a-o-i — người học hay dồn 'a-o' thành một. Bài tập: ghép mỗi màu với một danh từ, đổi qua lại giữa 赤い〜 (tính từ) và 緑の〜 (danh từ + の) để hai mẫu tách bạch."
  },
  {
    "id": 15,
    "title": "I-Adjectives (Present Tense)",
    "title_vi": "Tính từ -i (thì hiện tại)",
    "level": "A1",
    "vocabulary": [
      {
        cell_id: "4fcee055-e8c0-48c1-ba7f-96de835c364e",
        "japanese": "大きい (おおきい)",
        "english": "big"
      },
      {
        cell_id: "c5cbc4ee-50da-4b8a-a4cc-48115e84a0d9",
        "japanese": "小さい (ちいさい)",
        "english": "small"
      },
      {
        cell_id: "ebeb3ac9-fff2-484e-87ca-cc0c54f3083f",
        "japanese": "新しい (あたらしい)",
        "english": "new"
      },
      {
        cell_id: "d7ee7d87-0731-40bc-a79b-64d7542faa24",
        "japanese": "古い (ふるい)",
        "english": "old"
      },
      {
        cell_id: "8a611dd0-60e2-449a-aaff-cb761ca20bf6",
        "japanese": "美味しい (おいしい)",
        "english": "delicious"
      }
    ],
    "grammar": [
      {
        "point": "I-adjective conjugation",
        "explanation": "I-adjectives end in い. To make a polite non-past affirmative, attach です: 大きいです. To make negative, change い to くないです: 大きくないです."
      }
    ],
    "examples": [
      {
        "japanese": "このケーキは美味しいです。",
        "english": "This cake is delicious.",
        "pronunciation_focus_en": [
          "この → 'ko-no' ('this' + noun); ケーキ → 'ke-e-ki' (katakana 'cake', ー holds the 'eh')",
          "は → topic particle, 'wa'",
          "美味しい (おいしい) → 'o-i-shi-i', four mora; the final いい is a held long 'ee'",
          "です → 'des'; here です adds POLITENESS, not 'is' — 美味しい already means 'is delicious'"
        ],
        "pronunciation_focus": [
          "この → 'ko-no' ('này' + danh từ); ケーキ → 'ke-e-ki' (katakana 'bánh kem', ー giữ 'ê')",
          "は → trợ từ chủ đề, 'wa'",
          "美味しい (おいしい) → 'o-i-shi-i', bốn mora; いい cuối là 'i' dài giữ lâu",
          "です → 'des'; ở đây です thêm SỰ LỊCH SỰ, không phải 'là' — 美味しい đã nghĩa là 'ngon'"
        ]
      },
      {
        "japanese": "そのスマホは高くないです。",
        "english": "That smartphone is not expensive.",
        "pronunciation_focus_en": [
          "その → 'so-no' ('that, near you'); スマホ → 'su-ma-ho' (clipped loanword, 'smartphone')",
          "は → topic particle, 'wa'",
          "高くない → 'ta-ka-ku-na-i'; the い of 高い becomes くない for the negative — the い itself conjugates",
          "です → 'des', devoiced; keeps the negative polite (高くないです)"
        ],
        "pronunciation_focus": [
          "その → 'so-no' ('đó, gần bạn'); スマホ → 'su-ma-ho' (từ mượn cắt gọn, 'điện thoại thông minh')",
          "は → trợ từ chủ đề, 'wa'",
          "高くない → 'ta-ka-ku-na-i'; chữ い của 高い thành くない khi phủ định — chính chữ い chia",
          "です → 'des', lướt; giữ phủ định ở mức lịch sự (高くないです)"
        ]
      }
    ],
    "cultural_notes_en": "This lesson exposes a deep design difference: in Japanese an い-adjective is itself a predicate — 美味しい already means 'is delicious,' tense and all. There is no separate verb 'to be' propping it up the way English needs 'is' in 'the cake IS good.' The です that follows (美味しいです) is a politeness marker, not the verb — which is why the negative changes the adjective itself (高い → 高くない, 'is not expensive'), not a separate 'be' verb. English speakers consistently misanalyze this because their native grammar forces a 'to be': they produce ×美味しいだ or ×高いじゃないです by analogy with noun sentences (学生だ / 学生じゃない). The cultural-pragmatic layer matters too: 美味しい said aloud during a meal is active, expected appreciation — Japanese dining is verbally responsive (a clear ごちそうさま after, いただきます before), more vocal about food than typical American table habits. この/その/あの mirror the これ/それ/あれ system from Lesson 12, but attach directly to a noun (このケーキ = 'this cake'), so the deixis you already learned transfers with a small shape change.",
    "cultural_notes_vi": "Bài này phơi bày một khác biệt thiết kế sâu: trong tiếng Nhật, tính từ-い tự nó là vị ngữ — 美味しい đã nghĩa là 'ngon', kèm cả thì. Không có động từ 'là' riêng chống đỡ như tiếng Việt cần \"thì/là\". Chữ です đi sau (美味しいです) là dấu lịch sự, không phải động từ — vì vậy phủ định đổi chính tính từ (高い → 高くない, 'không đắt'), không phải một động từ 'là' riêng. Người học hay phân tích sai vì tiếng mẹ đẻ đẩy họ thêm 'là': họ tạo ra ×美味しいだ hoặc ×高いじゃないです bắt chước câu danh từ (学生だ / 学生じゃない). Tầng văn hóa-ngữ dụng cũng quan trọng: nói 美味しい thành tiếng trong bữa ăn là lời khen chủ động, được mong đợi — ăn uống ở Nhật rất có lời (một câu ごちそうさま sau, いただきます trước), nói về món ăn nhiều hơn thói quen Việt ở bàn ăn. この/その/あの phản chiếu hệ これ/それ/あれ ở Bài 12, nhưng gắn thẳng vào danh từ (このケーキ = 'cái bánh này'), nên cách chỉ định bạn đã học chuyển sang với một biến đổi hình nhỏ.",
    "tip_advice_en": "Highest-leverage rule that closes A1: an い-adjective is a complete predicate — 高い = 'is expensive' — so do NOT add だ to it (×高いだ is wrong; 学生だ is right because 学生 is a noun). For the polite negative, conjugate the adjective, not a 'be' verb: 高い → 高くないです (or 高くありません), never ×高いじゃないです. This だ/じゃない-with-い-adjectives error is the single most common A1 graduation mistake for English speakers, precisely because English grammar pushes you toward it. Pronunciation watch-points: doubled final vowels — 美味しい ends おいしい (long 'ee'), ケーキ holds the ー — and loanword clipping (スマホ, not 'smart-phone'). Drill the contrast aloud: 高いです / 高くないです / 美味しいです / 美味しくないです, feeling that the い is what carries tense and polarity while です only carries politeness.",
    "tip_advice_vi": "Luật lợi nhất khép lại A1: tính từ-い là một vị ngữ hoàn chỉnh — 高い = 'đắt' — nên ĐỪNG thêm だ vào nó (×高いだ là sai; 学生だ đúng vì 学生 là danh từ). Với phủ định lịch sự, chia chính tính từ, không phải động từ 'là': 高い → 高くないです (hoặc 高くありません), không bao giờ ×高いじゃないです. Lỗi だ/じゃない-với-tính-từ-い này là lỗi tốt nghiệp A1 phổ biến nhất, đúng vì ngữ pháp tiếng Việt cũng đẩy bạn về phía đó. Điểm phát âm: nguyên âm cuối đôi — 美味しい kết おいしい ('i' dài), ケーキ giữ dấu ー — và từ mượn cắt gọn (スマホ, không phải 'smart-phone'). Tập đối lập to thành tiếng: 高いです / 高くないです / 美味しいです / 美味しくないです, cảm nhận chữ い mang thì và phủ định còn です chỉ mang sự lịch sự."
  }
];

export default lessons;
