-- Insert VIP9 tier
INSERT INTO public.subscription_tiers (
  id,
  name,
  name_vi,
  description_en,
  description_vi,
  price_monthly,
  price_yearly,
  room_access_per_day,
  custom_topics_allowed,
  priority_support,
  display_order,
  is_active
) VALUES (
  '00000000-0000-0000-0000-000000000009',
  'VIP9',
  'VIP9',
  'Strategic Mastery - Individual, Corporate & National Strategy',
  'Bậc Thầy Chiến Lược - Cá Nhân, Doanh Nghiệp & Quốc Gia',
  150,
  1500,
  NULL,
  NULL,
  true,
  9,
  true
);

-- Insert all 55 VIP9 rooms
INSERT INTO public.rooms (id, schema_id, title_en, title_vi, tier, is_demo, entries) VALUES
-- Individual Strategic Mastery (20 rooms)
('strategic_foundations_vip9', 'default', 'Strategic Foundations', 'Nền Tảng Chiến Lược', 'vip9', false, '[]'),
('strategic_cognitive_models_vip9', 'default', 'Strategic Cognitive Models', 'Mô Hình Tư Duy Chiến Lược', 'vip9', false, '[]'),
('strategic_long_horizon_vip9', 'default', 'Long Horizon Thinking', 'Tư Duy Dài Hạn', 'vip9', false, '[]'),
('strategic_deep_work_vip9', 'default', 'Strategic Deep Work', 'Làm Việc Sâu Chiến Lược', 'vip9', false, '[]'),
('strategic_adaptive_intelligence_vip9', 'default', 'Adaptive Intelligence', 'Trí Tuệ Thích Nghi', 'vip9', false, '[]'),
('strategic_risk_calibration_vip9', 'default', 'Risk Calibration', 'Hiệu Chỉnh Rủi Ro', 'vip9', false, '[]'),
('strategic_personal_systems_vip9', 'default', 'Personal Systems Design', 'Thiết Kế Hệ Thống Cá Nhân', 'vip9', false, '[]'),
('strategic_self_governance_vip9', 'default', 'Self Governance', 'Tự Quản Trị', 'vip9', false, '[]'),
('strategic_signal_detection_vip9', 'default', 'Signal Detection', 'Phát Hiện Tín Hiệu', 'vip9', false, '[]'),
('strategic_compounding_learning_vip9', 'default', 'Compounding Learning', 'Học Tập Tích Lũy', 'vip9', false, '[]'),
('strategic_emotional_neutrality_vip9', 'default', 'Emotional Neutrality', 'Trung Lập Cảm Xúc', 'vip9', false, '[]'),
('strategic_scenario_thinking_vip9', 'default', 'Scenario Thinking', 'Tư Duy Kịch Bản', 'vip9', false, '[]'),
('strategic_pattern_recognition_vip9', 'default', 'Pattern Recognition', 'Nhận Diện Mô Thức', 'vip9', false, '[]'),
('strategic_influence_individual_vip9', 'default', 'Strategic Influence', 'Ảnh Hưởng Chiến Lược', 'vip9', false, '[]'),
('strategic_negotiation_individual_vip9', 'default', 'Strategic Negotiation', 'Đàm Phán Chiến Lược', 'vip9', false, '[]'),
('strategic_failure_recovery_vip9', 'default', 'Failure Recovery', 'Phục Hồi Thất Bại', 'vip9', false, '[]'),
('strategic_antifragile_growth_vip9', 'default', 'Antifragile Growth', 'Tăng Trưởng Chống Đỡ', 'vip9', false, '[]'),
('strategic_reputation_individual_vip9', 'default', 'Reputation Strategy', 'Chiến Lược Danh Tiếng', 'vip9', false, '[]'),
('strategic_lifelong_fitness_vip9', 'default', 'Lifelong Fitness', 'Rèn Luyện Suốt Đời', 'vip9', false, '[]'),
('strategic_identity_vip9', 'default', 'Strategic Identity', 'Bản Sắc Chiến Lược', 'vip9', false, '[]'),

-- Corporate & Organizational Strategy (20 rooms)
('corporate_foundations_vip9', 'default', 'Corporate Strategy Foundations', 'Nền Tảng Chiến Lược Doanh Nghiệp', 'vip9', false, '[]'),
('corporate_org_architecture_vip9', 'default', 'Organizational Architecture', 'Kiến Trúc Tổ Chức', 'vip9', false, '[]'),
('corporate_leadership_leverage_vip9', 'default', 'Leadership Leverage', 'Đòn Bẩy Lãnh Đạo', 'vip9', false, '[]'),
('corporate_team_culture_vip9', 'default', 'Team Culture Engineering', 'Xây Dựng Văn Hóa Đội Nhóm', 'vip9', false, '[]'),
('corporate_execution_systems_vip9', 'default', 'Execution Systems', 'Hệ Thống Thực Thi', 'vip9', false, '[]'),
('corporate_analytics_strategy_vip9', 'default', 'Analytics & Strategy', 'Phân Tích & Chiến Lược', 'vip9', false, '[]'),
('corporate_innovation_engines_vip9', 'default', 'Innovation Engines', 'Động Cơ Đổi Mới', 'vip9', false, '[]'),
('corporate_resource_allocation_vip9', 'default', 'Resource Allocation', 'Phân Bổ Nguồn Lực', 'vip9', false, '[]'),
('corporate_positioning_vip9', 'default', 'Strategic Positioning', 'Định Vị Chiến Lược', 'vip9', false, '[]'),
('corporate_long_cycle_planning_vip9', 'default', 'Long Cycle Planning', 'Hoạch Định Chu Kỳ Dài', 'vip9', false, '[]'),
('corporate_resilience_vip9', 'default', 'Corporate Resilience', 'Khả Năng Phục Hồi Doanh Nghiệp', 'vip9', false, '[]'),
('corporate_conflict_navigation_vip9', 'default', 'Conflict Navigation', 'Điều Hướng Xung Đột', 'vip9', false, '[]'),
('corporate_negotiation_vip9', 'default', 'Corporate Negotiation', 'Đàm Phán Doanh Nghiệp', 'vip9', false, '[]'),
('corporate_cross_functional_vip9', 'default', 'Cross-Functional Strategy', 'Chiến Lược Liên Chức Năng', 'vip9', false, '[]'),
('corporate_governance_vip9', 'default', 'Corporate Governance', 'Quản Trị Doanh Nghiệp', 'vip9', false, '[]'),
('corporate_scaling_strategy_vip9', 'default', 'Scaling Strategy', 'Chiến Lược Mở Rộng', 'vip9', false, '[]'),
('corporate_talent_architecture_vip9', 'default', 'Talent Architecture', 'Kiến Trúc Nhân Tài', 'vip9', false, '[]'),
('corporate_crisis_strategy_vip9', 'default', 'Crisis Strategy', 'Chiến Lược Khủng Hoảng', 'vip9', false, '[]'),
('corporate_global_strategy_vip9', 'default', 'Global Strategy', 'Chiến Lược Toàn Cầu', 'vip9', false, '[]'),
('corporate_foresight_vip9', 'default', 'Strategic Foresight', 'Tầm Nhìn Chiến Lược', 'vip9', false, '[]'),

-- National & Geostrategic Intelligence (15 rooms)
('national_strategy_foundations_vip9', 'default', 'National Strategy Foundations', 'Nền Tảng Chiến Lược Quốc Gia', 'vip9', false, '[]'),
('national_power_capability_vip9', 'default', 'National Power & Capability', 'Sức Mạnh & Năng Lực Quốc Gia', 'vip9', false, '[]'),
('national_energy_security_vip9', 'default', 'Energy Security', 'An Ninh Năng Lượng', 'vip9', false, '[]'),
('national_economic_strategy_vip9', 'default', 'Economic Strategy', 'Chiến Lược Kinh Tế', 'vip9', false, '[]'),
('national_culture_power_vip9', 'default', 'Cultural Power', 'Sức Mạnh Văn Hóa', 'vip9', false, '[]'),
('national_military_strategy_vip9', 'default', 'Military Strategy', 'Chiến Lược Quân Sự', 'vip9', false, '[]'),
('national_geopolitical_mapping_vip9', 'default', 'Geopolitical Mapping', 'Bản Đồ Địa Chính Trị', 'vip9', false, '[]'),
('national_diplomacy_vip9', 'default', 'Strategic Diplomacy', 'Ngoại Giao Chiến Lược', 'vip9', false, '[]'),
('national_risk_intelligence_vip9', 'default', 'Risk Intelligence', 'Tình Báo Rủi Ro', 'vip9', false, '[]'),
('national_cyber_strategy_vip9', 'default', 'Cyber Strategy', 'Chiến Lược Không Gian Mạng', 'vip9', false, '[]'),
('national_civilization_cycles_vip9', 'default', 'Civilization Cycles', 'Chu Kỳ Văn Minh', 'vip9', false, '[]'),
('national_megatrends_vip9', 'default', 'Megatrends Analysis', 'Phân Tích Xu Hướng Lớn', 'vip9', false, '[]'),
('national_space_strategy_vip9', 'default', 'Space Strategy', 'Chiến Lược Không Gian', 'vip9', false, '[]'),
('national_resilience_systems_vip9', 'default', 'National Resilience Systems', 'Hệ Thống Phục Hồi Quốc Gia', 'vip9', false, '[]'),
('national_identity_strategy_vip9', 'default', 'National Identity Strategy', 'Chiến Lược Bản Sắc Quốc Gia', 'vip9', false, '[]');