// Path: src/lib/__tests__/audio-key-parity.test.ts
//
// Contract test: the runtime path-generator (`src/lib/lessonAudio.ts`) and
// the manifest builder (`scripts/build-audio-manifest.ts`) MUST produce
// byte-identical Supabase storage keys for the same lesson input. If they
// drift, the runtime asks Supabase for one URL while the manifest builder
// records / generates another — silently breaking audio for users while
// producing a "0 missing" reading on storage audits.
//
// What this test guards:
//   1. Slug derivation — both files implement `lessonStorageSlug(lang, id, level)`
//      with regex-based prefix stripping. Drift here = wrong subdirectory.
//   2. Phonics filter — both files implement `isPhonicsOnly(text)` against
//      the same Unicode ranges. Drift = wrong skip set, wrong file count.
//   3. Full storage key shape — `extractFrenchOrGerman` and `extractAsianLang`
//      in the script emit storage_key strings via inline templates. The
//      runtime composes the same string via `lessonAudioBase` + `lessonAudioKey`.
//      Drift = wrong file path.
//
// What this test does NOT cover (and why):
//   - Vietnamese (`vi`) is generated by a separate script
//     `scripts/generate-vietnamese-audio.ts`, NOT by build-audio-manifest.ts.
//     That script's path template is fully inline (no exportable helper);
//     extracting one would exceed this PR's "export-only" scope. The vi
//     section below mirrors the documented inline template as a static
//     string and asserts the runtime matches it. If the script's vi
//     template changes, this test will not catch it directly — update both
//     in lockstep, or follow up with a helper extraction in that script.
//   - Full enumeration of every lesson in every file — sample a representative
//     cross-section instead, to keep the test fast (<1s).

import { describe, it, expect } from "vitest";

import {
  lessonAudioBase,
  lessonAudioKey,
  lessonStorageSlug as runtimeStorageSlug,
  isPhonicsOnly as runtimeIsPhonicsOnly,
  type LessonAudioLang,
  type LessonAudioLevel,
} from "../lessonAudio";

import {
  lessonStorageSlug as manifestStorageSlug,
  isPhonicsOnly as manifestIsPhonicsOnly,
  extractFrenchOrGerman,
  extractAsianLang,
} from "../../../scripts/build-audio-manifest";

// ── Slug parity ────────────────────────────────────────────────────────────

describe("audio key parity — lessonStorageSlug", () => {
  // String-ID langs: French / German.
  // The slug strips one of three prefix patterns: <lang>_<level>_, <lang>_fluency_, <lang>_.
  const stringIdSamples: Array<{
    lang: "french" | "german";
    runtimeLang: LessonAudioLang;
    level: LessonAudioLevel;
    id: string;
    expectedSlug: string;
  }> = [
    // French — every prefix pattern present in the corpus
    { lang: "french", runtimeLang: "fr", level: "A1", id: "french_a1_greetings_intro", expectedSlug: "lgreetings_intro" },
    { lang: "french", runtimeLang: "fr", level: "B1", id: "french_b1_renting_apartment", expectedSlug: "lrenting_apartment" },
    { lang: "french", runtimeLang: "fr", level: "B2", id: "french_b2_salary_negotiation", expectedSlug: "lsalary_negotiation" },
    { lang: "french", runtimeLang: "fr", level: "C1", id: "french_fluency_conditional", expectedSlug: "lconditional" },
    { lang: "french", runtimeLang: "fr", level: "C1", id: "french_greetings_intro", expectedSlug: "lgreetings_intro" },
    // German — same patterns
    { lang: "german", runtimeLang: "de", level: "A1", id: "german_a1_greetings", expectedSlug: "lgreetings" },
    { lang: "german", runtimeLang: "de", level: "B2", id: "german_b2_workplace_conflict", expectedSlug: "lworkplace_conflict" },
    { lang: "german", runtimeLang: "de", level: "C2", id: "german_c2_philosophical_debate", expectedSlug: "lphilosophical_debate" },
  ];

  it.each(stringIdSamples)(
    "agrees on string-id slug ($lang/$level/$id)",
    ({ lang, runtimeLang, level, id, expectedSlug }) => {
      const fromRuntime = runtimeStorageSlug(runtimeLang, id, level);
      const fromManifest = manifestStorageSlug(lang, id, level);
      expect(fromRuntime).toBe(fromManifest);
      expect(fromRuntime).toBe(expectedSlug);
    },
  );

  // Numeric-ID langs: Japanese / Korean / Chinese / Vietnamese.
  // Slug rule is unconditional: `l${id}`.
  const numericIdSamples: Array<{
    lang: "japanese" | "korean" | "chinese";
    runtimeLang: LessonAudioLang;
    level: LessonAudioLevel;
    id: number;
  }> = [
    { lang: "japanese", runtimeLang: "ja", level: "A1", id: 1 },
    { lang: "japanese", runtimeLang: "ja", level: "B2", id: 47 },
    { lang: "korean", runtimeLang: "ko", level: "A1", id: 12 },
    { lang: "korean", runtimeLang: "ko", level: "C1", id: 8 },
    { lang: "chinese", runtimeLang: "zh", level: "B1", id: 3 },
    { lang: "chinese", runtimeLang: "zh", level: "C2", id: 50 },
  ];

  it.each(numericIdSamples)(
    "agrees on numeric-id slug ($lang/$level/$id)",
    ({ lang, runtimeLang, level, id }) => {
      const fromRuntime = runtimeStorageSlug(runtimeLang, id, level);
      const fromManifest = manifestStorageSlug(lang, id, level);
      expect(fromRuntime).toBe(fromManifest);
      expect(fromRuntime).toBe(`l${id}`);
    },
  );

  // Vietnamese — runtime only (vi is not in build-audio-manifest's LANG_CODES).
  // Asserts the runtime slug shape that generate-vietnamese-audio.ts
  // mirrors inline (`l${lesson.id}`).
  it("vi numeric-id slug matches the documented vi generator template", () => {
    expect(runtimeStorageSlug("vi", 17, "B1")).toBe("l17");
    expect(runtimeStorageSlug("vi", 99, "C2")).toBe("l99");
  });
});

// ── Phonics filter parity ──────────────────────────────────────────────────

describe("audio key parity — isPhonicsOnly", () => {
  const cases: Array<{ text: string; expected: boolean; why: string }> = [
    // Single hiragana — skip
    { text: "あ", expected: true, why: "hiragana A" },
    { text: "ん", expected: true, why: "hiragana N" },
    // Single katakana — skip
    { text: "カ", expected: true, why: "katakana KA" },
    { text: "ヴ", expected: true, why: "katakana VU" },
    // Single Korean compatibility jamo — skip
    { text: "ㄱ", expected: true, why: "jamo giyeok" },
    { text: "ㅏ", expected: true, why: "jamo a" },
    // Single Hangul jamo (modern initial) — skip
    { text: "ᄀ", expected: true, why: "modern jamo giyeok" },
    // Multi-char kana real word — keep
    { text: "カメラ", expected: false, why: "katakana real word: camera" },
    { text: "こんにちは", expected: false, why: "hiragana real word: hello" },
    // Hangul syllable block — keep (not in compat-jamo range)
    { text: "가", expected: false, why: "hangul syllable GA — real syllable" },
    // CJK ideograph — keep
    { text: "我", expected: false, why: "CJK: I/me" },
    // English / latin — keep
    { text: "a", expected: false, why: "single latin letter" },
    { text: "hello", expected: false, why: "english word" },
    // Empty / whitespace — keep (length-1 gate fails)
    { text: "", expected: false, why: "empty string" },
    { text: "  ", expected: false, why: "whitespace only" },
  ];

  it.each(cases)("agrees on phonics filter ($why)", ({ text, expected }) => {
    const fromRuntime = runtimeIsPhonicsOnly(text);
    const fromManifest = manifestIsPhonicsOnly(text);
    expect(fromRuntime).toBe(fromManifest);
    expect(fromRuntime).toBe(expected);
  });
});

// ── Full storage_key parity (extract* vs lessonAudioBase + lessonAudioKey) ──

describe("audio key parity — full storage_key (script-emitted vs runtime-composed)", () => {
  // Build a minimal lesson object the extractor can consume. Schema mirrors
  // the real per-lang shape documented in build-audio-manifest.ts header.

  it("French A1: sentence + dialogue + vocab + idiom keys all match runtime", () => {
    const lesson = {
      id: "french_a1_greetings_intro",
      level: "A1",
      sentences: [
        { en: "Bonjour, ça va ?" },
        { en: "Comment tu t'appelles ?" },
      ],
      dialogue: [
        { speaker: "A", text: "Salut !" },
        { speaker: "B", text: "Salut, ça va ?" },
      ],
      vocabulary: [
        { word: "bonjour" },
        { word: "salut" },
      ],
      idiom_glosses: [
        { example: "à tout à l'heure" },
      ],
    };

    const entries = extractFrenchOrGerman("french", lesson, 0, "A1");
    const base = lessonAudioBase("fr", lesson.id, "A1");

    // sentences → sentence_{n}.mp3
    expect(entries.find((e) => e.unit_kind === "sentence" && e.unit_index === 1)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "sentence", index: 1 }));
    expect(entries.find((e) => e.unit_kind === "sentence" && e.unit_index === 2)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "sentence", index: 2 }));

    // dialogue → dialogue_short_{n}_{A|B}.mp3
    expect(entries.find((e) => e.unit_kind === "dialogue_short" && e.unit_index === 1)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "dialogue_short", index: 1, speaker: "A" }));
    expect(entries.find((e) => e.unit_kind === "dialogue_short" && e.unit_index === 2)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "dialogue_short", index: 2, speaker: "B" }));

    // vocab → vocab_{n}.mp3
    expect(entries.find((e) => e.unit_kind === "vocab" && e.unit_index === 1)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "vocab", index: 1 }));

    // idiom → idiom_{n}.mp3
    expect(entries.find((e) => e.unit_kind === "idiom" && e.unit_index === 1)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "idiom", index: 1 }));
  });

  it("Japanese A1: numeric id + sentence + vocab keys all match runtime", () => {
    const lesson = {
      id: 5,
      level: "A1",
      sentences: [
        { japanese: "おはようございます。" },
        { japanese: "こんにちは。" },
      ],
      vocabulary: [
        { japanese: "本" },         // real word — kept
        { japanese: "あ" },         // single hiragana — phonics-skip
      ],
    };

    const entries = extractAsianLang("japanese", lesson, 0, "A1", {
      sentence: "japanese",
      dialogue: "japanese",
      vocab: "japanese",
      vocabKey: "vocabulary",
    });
    const base = lessonAudioBase("ja", lesson.id, "A1");

    // sentences
    expect(entries.find((e) => e.unit_kind === "sentence" && e.unit_index === 1)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "sentence", index: 1 }));

    // vocab — phonics-only entry should NOT be in entries (filter at pushEntry)
    expect(entries.find((e) => e.unit_kind === "vocab" && e.unit_index === 1)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "vocab", index: 1 }));
    expect(entries.find((e) => e.unit_kind === "vocab" && e.unit_index === 2))
      .toBeUndefined();
  });

  it("Korean A1: numeric id + dialogue (long, role names) keys all match runtime", () => {
    const lesson = {
      id: 14,
      level: "A1",
      dialogue_long: [
        { speaker: "선생님", hangul: "안녕하세요." },   // index 0 → A
        { speaker: "학생", hangul: "안녕히 가세요." },  // index 1 → B
        { speaker: "선생님", hangul: "잘 가요." },      // index 2 → A
      ],
    };

    const entries = extractAsianLang("korean", lesson, 0, "A1", {
      sentence: "korean",
      dialogue: "hangul",
      vocab: "hangul",
      vocabKey: "vocabulary",
    });
    const base = lessonAudioBase("ko", lesson.id, "A1");

    // dialogue_long uses the i % 2 === 0 ? "A" : "B" heuristic
    expect(entries.find((e) => e.unit_kind === "dialogue_long" && e.unit_index === 1)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "dialogue_long", index: 1, speaker: "A" }));
    expect(entries.find((e) => e.unit_kind === "dialogue_long" && e.unit_index === 2)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "dialogue_long", index: 2, speaker: "B" }));
    expect(entries.find((e) => e.unit_kind === "dialogue_long" && e.unit_index === 3)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "dialogue_long", index: 3, speaker: "A" }));
  });

  it("Chinese B1: vocab field is named 'vocab' (not 'vocabulary') — key still matches", () => {
    const lesson = {
      id: 3,
      level: "B1",
      vocab: [
        { chinese: "你好" },
        { chinese: "再见" },
      ],
    };

    const entries = extractAsianLang("chinese", lesson, 0, "B1", {
      sentence: "chinese",
      dialogue: "chinese",
      vocab: "chinese",
      vocabKey: "vocab",
    });
    const base = lessonAudioBase("zh", lesson.id, "B1");

    expect(entries.find((e) => e.unit_kind === "vocab" && e.unit_index === 1)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "vocab", index: 1 }));
    expect(entries.find((e) => e.unit_kind === "vocab" && e.unit_index === 2)?.storage_key)
      .toBe(lessonAudioKey(base, { kind: "vocab", index: 2 }));
  });
});

// ── Vietnamese — separate generator, template-mirror only ──────────────────
//
// `scripts/generate-vietnamese-audio.ts` builds entries with this inline template:
//   `${level.toLowerCase()}/vi/l${lesson.id}/phrase_${i + 1}.mp3`
//   `${level.toLowerCase()}/vi/l${lesson.id}/dialogue_${i + 1}.mp3`
// (Lines ~78 and ~88 of that script as of 2026-05-09.)
// We mirror the template here as a static expectation and assert the runtime
// matches it. If that script's template changes, update both sides; consider
// extracting a helper in that script so this test can call it directly.

describe("audio key parity — vietnamese (template-mirror)", () => {
  it("vi phrase: runtime composer matches generate-vietnamese-audio.ts inline template", () => {
    const id = 17;
    const level: LessonAudioLevel = "B1";
    const i = 2; // 0-based loop index in the script
    const expectedFromGeneratorTemplate = `${level.toLowerCase()}/vi/l${id}/phrase_${i + 1}.mp3`;

    const base = lessonAudioBase("vi", id, level);
    const fromRuntime = lessonAudioKey(base, { kind: "phrase", index: i + 1 });
    expect(fromRuntime).toBe(expectedFromGeneratorTemplate);
  });

  it("vi dialogue: runtime composer matches generate-vietnamese-audio.ts inline template", () => {
    const id = 99;
    const level: LessonAudioLevel = "C2";
    const i = 0;
    const expectedFromGeneratorTemplate = `${level.toLowerCase()}/vi/l${id}/dialogue_${i + 1}.mp3`;

    const base = lessonAudioBase("vi", id, level);
    const fromRuntime = lessonAudioKey(base, { kind: "dialogue_vi", index: i + 1 });
    expect(fromRuntime).toBe(expectedFromGeneratorTemplate);
  });
});
